### ISSUE TITLE
save more than 2 weights, and show epoch, loss in filename

### ISSUE THREAD

**Issue by jimmy-evo** [ultralytics/yolov5#1001]
## 🚀 Feature
save weights as {epoch}_{loss}.pt, not just best and last

## Motivation
i want to know and select weight with specific epoch/loss after training.
when i see best.pt , i can't know which epoch reached this metric.

## Pitch
save not only best.pt/last.pt, but {epoch}_{loss}_best.pt. Also! {epoch}_{loss}.pt every {save_period}, for example, every 5 epochs save one weight.

**Comment by glenn-jocher** [comment]
@jinmingyi1998 see Tensorboard or results.png for your training results. You can modify checkpointing to suit your needs here:
https://github.com/ultralytics/yolov5/blob/4fce0096fa2f2dc7db12b422200009362de9a056/train.py#L342-L356


This change is not suitable for general adoption due to hard drive space constraints.
