### ISSUE TITLE
What causes CPU to degrade when I load the weight with torch.hub.load()

### ISSUE THREAD

**Issue by TRINHHOANGANH** [ultralytics/yolov5#10033]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

## My problem
 Hi @ultralytics,

I use detect.py file to detect object then CPU: 78.1%.
On the other hand, I  load weight by **_torch.hub.load()_** then CPU: 16,2%. 
- torch.hub.load()
![Screenshot from 2022-11-04 15-43-55](https://user-images.githubusercontent.com/83366198/199931602-25dbd47d-26c3-44f1-aeef-1fe65100d775.png)

- run detect.py
 
![Screenshot from 2022-11-04 15-51-50](https://user-images.githubusercontent.com/83366198/199932821-5232721a-f356-4aba-aef8-4b15093f3fd6.png)

Can you point out what the cause is?

**Comment by glenn-jocher** [comment]
Maybe the dataloader you've created for your PyTorch Hub model?

**Comment by TRINHHOANGANH** [comment]
I don't known but in my code, i load weight by **torch.hub.load()** such as in line 10: https://github.com/TRINHHOANGANH/test_yolov5_torch_hub.git
![image](https://user-images.githubusercontent.com/83366198/200096005-faca8e3d-30e2-4c5b-bb98-f04609b6c8c6.png)

**Comment by HuuDat0311** [comment]
I also had the same problem.
When I run with multiple threads, using **torch.hub.load()** the cpu is only **8-21%**. While using **detect.py --source multicam.txt,** the cpu is up to **80-83%.**
Can you explain to me where the problem lies?

**Comment by glenn-jocher** [comment]
@HuuDat0311 it appears that when you run detect.py with multiple threads, the CPU usage increases significantly, and you're experiencing a discrepancy in CPU usage when using torch.hub.load(). 🔍🖥️ While running detect.py with multiple threads, higher CPU usage is expected due to the increased computational load caused by the multiple threads. On the other hand, torch.hub.load() may not max out the CPU since it typically involves loading the pre-trained model without intense computation. 

The Torch Hub model for YOLOv5 can be identified from the 'model.yaml' file in the associated repository: https://github.com/ultralytics/yolov5.

If you have further questions or encounter any issues, please feel free to ask!
