### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#10099]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question about the confusion matrix where I don't fully understand it. @glenn-jocher Could you please have a look at my confusion matrix and tell me what does it mean to have background as 1.0 with another class.

![image](https://user-images.githubusercontent.com/49511207/200804159-57e890ff-60b5-409f-a7ac-fcc1b8856451.png)

**Comment by glenn-jocher** [comment]
Predicted is on y axis, True is on horizontal axis. FPs show in last column. Columns are normalized, so to see with counts instead of normalized change normalized=False in confusion matrix here:
https://github.com/ultralytics/yolov5/blob/86decb3c49f91547975d7b7399290eb247888f6f/utils/metrics.py#L190
