### ISSUE TITLE
Variant of failure to download Arial.ttf from https://ultralytics.com/assets/Arial.ttf (url of downloading font does NOT work #5643)

### ISSUE THREAD

**Issue by kecaj** [ultralytics/yolov5#10113]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It is my first attempt to run YOLOv5 on Mac (macOS Version 11.7.1). I followed the guidelines, installed the required packages for the local run, and executed "./run.zsh". 

It seems it needs Arial.ttf to annotate images.

Attached is the screenshot. 

Why it fails "[SSL: CERTIFICATE_VERIFY_FAILED] ...: unable to get local issuer certificate (_ssl.C:997)"?

I would appreciate the advice.

Kecaj

<img width="2560" alt="Screen Shot 2022-11-09 at 21 47 43" src="https://user-images.githubusercontent.com/15880763/201016459-306a025e-4359-4d86-b775-135232e8c5f6.png">

**Comment by glenn-jocher** [comment]
@kecaj this is unrelated to YOLOv5. 

You need to install certificates when installing a new version of python. You can find these in your python directory, just double click them and they'll intall.

**Comment by kecaj** [comment]
@glenn-jocher Thanks for taking the time. I don't quite understand what you mean though.

I do have the certifi package installed, and 
```
>>> import certifi
>>> certifi.where()
'.../yolo5-venv/lib/python3.10/site-packages/certifi/cacert.pem'
```

FWIW, I'm running this on a Mac, and I don't see anything obviously clickable in my Python directory. I'm not sure I understand enough about certificates to follow along. What needs to be done?

**Comment by glenn-jocher** [comment]
Again this is not a YOLOv5 issue and should be searched elsewhere like stackoverflow
<img width="1062" alt="Screenshot 2022-11-16 at 19 32 46" src="https://user-images.githubusercontent.com/26833433/202264047-24e0ee16-a7c7-4f27-bd47-b1bc6f258b8c.png">

**Comment by longlizhi** [comment]
> 感谢您抽出宝贵时间。我不太明白你的意思。
> 
> 我确实安装了证书包，并且
> 
> ```
> >>> import certifi
> >>> certifi.where()
> '.../yolo5-venv/lib/python3.10/site-packages/certifi/cacert.pem'
> ```
> 
> FWIW，我在 Mac 上运行它，在我的 Python 目录中没有看到任何明显可点击的内容。我不确定我对证书的了解是否足够。需要做什么？

Hello, have you solved this problem? If so, can you tell me how to solve it?

**Comment by glenn-jocher** [comment]
@longlizhi hello, 

I apologize for any confusion earlier. Regarding the SSL certificate issue, it seems to be unrelated to YOLOv5 specifically. It is more likely related to your Python environment and the SSL configuration on your Mac.

One possible solution is to manually update the CA certificates on your machine. You can do this by following these steps:

1. Download the latest certificate bundle from the official website, such as `cacert.pem`.

2. In your Python script, you can set the SSL certificate path explicitly using the `certifi` package. Here's an example:

   ```python
   import certifi
   import ssl

   ssl._create_default_https_context = ssl._create_unverified_context
   ssl._ssl._DEFAULT_CERT_FILE = certifi.where()

   # Rest of your code
   ```

Please note that this is just a workaround, and it's important to understand the security implications of disabling certificate verification. Make sure to only use this approach in trusted environments.

If you're still experiencing issues, I recommend searching for similar problems on platforms like Stack Overflow, as this issue seems to be related to the SSL configuration on your specific machine.

I hope this helps! Let me know if you have any further questions.
