### ISSUE TITLE
RuntimeError: The size of tensor a (1520) must match the size of tensor b (4) at non-singleton dimension 1

### ISSUE THREAD

**Issue by huranzhijian** [ultralytics/yolov5#10185]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

r = wh[:, None] / k[None]
RuntimeError: The size of tensor a (1520) must match the size of tensor b (4) at non-singleton dimension 1
when i am traning my own datasets,  the image size is 1280 * 10,  and i set 4 anchors
![QQ图片20221117201042](https://user-images.githubusercontent.com/40172397/202443880-ecec7767-dc49-4582-8142-32f2a7f16b7d.png)
![QQ图片20221117201100](https://user-images.githubusercontent.com/40172397/202443895-4f6c38e4-9d25-4eab-869f-cf0b55075b09.png)

### Environment

centos and windows
pytorch                   1.12.1

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.

Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e. 
```yaml
# Specify anchor count (per layer)
anchors: 3

# --OR-- Specify anchor values manually
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a [Genetic Evolution](https://en.wikipedia.org/wiki/Genetic_algorithm) (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with [Best Possible Recall](https://en.wikipedia.org/wiki/Precision_and_recall) (BPR) as its fitness function.

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

<img width="1200" alt="Screenshot 2022-03-24 at 10 58 28" src="https://user-images.githubusercontent.com/26833433/159891298-8b15f80b-f5b0-4fa9-8824-7380bae32a76.png">

**No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
```shell
python train.py --noautoanchor
```

For more details on AutoAnchor see:
https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py

Good luck 🍀 and let us know if you have any other questions!

**Comment by huranzhijian** [comment]
> 

I think the yaml is  no problem, but I can not find the problem by debug.

**Comment by huranzhijian** [comment]
> I think the yaml is no problem, but I can not find the problem by debug.

I think the yaml is no problem, but I can not find the problem by debug.
![Uploading QQ图片20221117203645.png…]()

**Comment by huranzhijian** [comment]
> 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.
> 
> Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e.
> 
> ```yaml
> # Specify anchor count (per layer)
> anchors: 3
> 
> # --OR-- Specify anchor values manually
> anchors:
>   - [10,13, 16,30, 33,23]  # P3/8
>   - [30,61, 62,45, 59,119]  # P4/16
>   - [116,90, 156,198, 373,326]  # P5/32
> ```
> 
> When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a [Genetic Evolution](https://en.wikipedia.org/wiki/Genetic_algorithm) (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with [Best Possible Recall](https://en.wikipedia.org/wiki/Precision_and_recall) (BPR) as its fitness function.
> 
> Notebook example: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> <img alt="Screenshot 2022-03-24 at 10 58 28" width="1200" src="https://user-images.githubusercontent.com/26833433/159891298-8b15f80b-f5b0-4fa9-8824-7380bae32a76.png">
> 
> **No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
> 
> ```shell
> python train.py --noautoanchor
> ```
> 
> For more details on AutoAnchor see: https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py
> 
> Good luck 🍀 and let us know if you have any other questions!

when I set the number of the anchor is 3,it will be ok, but when set it 4,it will hava the problem.

**Comment by huranzhijian** [comment]
> 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.
> 
> Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e.
> 
> ```yaml
> # Specify anchor count (per layer)
> anchors: 3
> 
> # --OR-- Specify anchor values manually
> anchors:
>   - [10,13, 16,30, 33,23]  # P3/8
>   - [30,61, 62,45, 59,119]  # P4/16
>   - [116,90, 156,198, 373,326]  # P5/32
> ```
> 
> When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a [Genetic Evolution](https://en.wikipedia.org/wiki/Genetic_algorithm) (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with [Best Possible Recall](https://en.wikipedia.org/wiki/Precision_and_recall) (BPR) as its fitness function.
> 
> Notebook example: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> <img alt="Screenshot 2022-03-24 at 10 58 28" width="1200" src="https://user-images.githubusercontent.com/26833433/159891298-8b15f80b-f5b0-4fa9-8824-7380bae32a76.png">
> 
> **No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
> 
> ```shell
> python train.py --noautoanchor
> ```
> 
> For more details on AutoAnchor see: https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py
> 
> Good luck 🍀 and let us know if you have any other questions!

![QQ图片20221117203645](https://user-images.githubusercontent.com/40172397/202451502-dd537045-cb27-43e5-98e9-0bbdadee321f.png)

**Comment by glenn-jocher** [comment]
If your model only has 3 output layers you can't assign 4 lists of anchors

**Comment by huranzhijian** [comment]
> If your model only has 3 output layers you can't assign 4 lists of anchors
My model layers is 4,  I think it would be my images size problem,  the image size is weird, when i decrease the arguments of gen from 1000 to 900, it will be ok,  but i do not know why.

**Comment by glenn-jocher** [comment]
@huranzhijian your data is not going to be trainable. The console output itself is showing that all of our labels are < 3 pixels in size.

**Comment by huranzhijian** [comment]
> @huranzhijian your data is not going to be trainable. The console output itself is showing that all of our labels are < 3 pixels in size.
thanks!

**Comment by pderrenger** [comment]
@huranzhijian you're welcome! If you need further assistance, feel free to ask.

**Comment by 1455586787** [comment]
![0683122188d072ac853adb6eb3d7908](https://github.com/user-attachments/assets/eb614ff7-105c-4301-94c5-6b3a7044a1dd)
This error occurred during the initial training phase.
![19ec25d4bc5874ff2f73d18ae3a4a1c](https://github.com/user-attachments/assets/15ef11dc-bbf1-45b5-ad75-0fb2d3052a8f)
After training with the command python train.py --noautoanchor, the only remaining issue is this one, but I checked my NumPy version, and it seems fine.

(yolov5) PS E:\Anaconda\yolov5_Source_code\yolov5-6.0> pip install numpy
Requirement already satisfied: numpy in e:\anaconda\envs\yolov5\lib\site-packages (1.18.5)，
Can someone help me solve this issue?

**Comment by pderrenger** [comment]
The issue seems related to an outdated version of NumPy. YOLOv5 requires a newer version of NumPy than `1.18.5`. Please update NumPy using the following command:

```bash
pip install --upgrade numpy
```

Ensure it upgrades to at least `1.20.0` or higher. After upgrading, retry your training command. If the issue persists, confirm that all dependencies are up-to-date by running:

```bash
pip install -r requirements.txt
```

Let us know if further issues arise!
