### ISSUE TITLE
How can we know how many resources my training is using?

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [ultralytics/yolov5#10186]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I wanted to know why the value of the gpu_mem increases with the passage of the epochs and it's not a constant (or almost constant) value, because every epoch has the same batch size and input size, so the memory usage should be the same, shouldn't it? 

Also I wanted to know how can we know how many RAM memory is necessary for our training in case, for example, we want to deploy a service on a cluster to train models.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by JesusSilvaUtrera** [comment]
For example, if I throw a training in local, it takes a lot more time than when I use docker compose for example, but in the docker compose if I use more than 100 images it exceeds the resources (I have 8 gb RAM dedicated to docker), whereas in my local I can throw a training with 200 images and it goes slow but doesn't show any error. i want to know why this happens and how to fix this, or at least know how many resources my training needs

**Comment by glenn-jocher** [comment]
@JesusSilvaUtrera Great observations! The local training may be taking longer due to hardware acceleration differences or other system-specific factors. The Docker environment with 8GB of RAM dedicated may be insufficient for larger workloads, causing resource exhaustion during training.

To determine your training's resource requirements, start with smaller batches and incrementally increase the batch size until you encounter resource limitations. Likewise, monitor GPU memory usage and adjust your batch size or image resolution to fit within your available resources. You can use system monitoring tools such as `nvidia-smi` for GPU memory usage and `top` for CPU and RAM utilization.

In the Docker environment, you might consider increasing the allocated memory to support larger workloads. Additionally, using resource limits, such as setting a memory limit with the `--memory` flag in Docker, can help avoid resource exhaustion.

Optimizing resource usage often involves a balance of batch size, image resolution, and available hardware. Feel free to reach out if you have further questions or need assistance!
