### ISSUE TITLE
How we can run yolo on multiple inputs parallelly?

### ISSUE THREAD

**Issue by Curious404** [ultralytics/yolov5#10198]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have multiple data for the input. I wanted to perform object detection on multiple inputs and process them parallelly instead of one by one. 

### Additional

Example:
3 inputs fed => showing All 3s output window simultaneously which having object detection.

**Comment by MartinPedersenpp** [comment]
https://github.com/ultralytics/yolov5/blob/ff6e6e328efe43547bc57d4e02ae8ddc3387ef58/detect.py#L98-L110

Not tested, but if you increase the batch size and feed detect.py with an array of images It might do the trick?
If you use TorchHub I think you need to use the torch dataloader or create your own?

Hope this helps

**Comment by Curious404** [comment]
@MartinPedersenpp I think your are increasing the batch size only. 
I am asking about direct n separate inputs.

**Comment by MartinPedersenpp** [comment]
> @MartinPedersenpp I think your are increasing the batch size only. I am asking about direct "3" separate inputs to the model.

Yes that was my thought.
if you put your 3 inputs in to a dataloader with batch size 3, would that not feed all three images to your model?
Again not tested, but that is how I have used dataloaders in the past

**Comment by Curious404** [comment]
And what commandl line do you pass? Because it is giving anerror.

**Comment by MartinPedersenpp** [comment]
Well the dataloader accepts lists or tuples, so I would assume that `[img1_path, img2_path, img3_path]` would work, but again, you might have to tweak some code if you get errors.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp is correct. You can input multiple images by passing their file paths as a list to the `--source` argument in the `detect.py` script. For example, `python detect.py --source ['img1.jpg', 'img2.jpg', 'img3.jpg']`. If you encounter any errors, feel free to refer to our [documentation](https://docs.ultralytics.com/yolov5/) for further assistance.

**Comment by vano-vega** [comment]
> @MartinPedersenpp I think your are increasing the batch size only. I am asking about direct "3" separate inputs to the model.

Did you find any solution for this parallel input issue?

**Comment by Jeong-m1n** [comment]
@glenn-jocher 

Hi, I am trying to put multi video to yolo model and I tried this method.
`results=model.track(source_list, persist=True, device= torch.device('cuda'), 
                        tracker ="bytetrack.yaml", conf=0.6)`
Then, I got seperate result for each video but **YOLOv8 tracking model assign same ID to different objects.**

![image](https://github.com/user-attachments/assets/b5bd5965-efba-4f15-8fa7-2ae3e1f401b9)
5 inputs (elements of source_list) are from one original frame, cropped image by `frame[x1:x2, y1:y2] ` to put only ROI as input of yolo.

And strange thing is only one output shows ID with detected results(class and confidence) and others show only bounding box.
![image](https://github.com/user-attachments/assets/60c9de05-979c-4beb-a9db-915994e3e993)
- result[0] has 7 results including ID and works well (two objects are assigned as 1 and 154 and represented in output video)
- result[1] and result[2] exclude ID (6 infos) : model.track acts like model.detect 
- result[3] and  result[4] include ID but have same ID and not showing in output image (assigned as 27)

Can you tell me what cause this problem?

**Comment by glenn-jocher** [comment]
Hi @Jeong-m1n,

Thank you for reaching out with your issue. It seems like you're encountering a problem with the YOLOv8 tracking model assigning the same ID to different objects when processing multiple videos or cropped regions of interest (ROIs) from a single frame.

Here are a few suggestions to help you troubleshoot and potentially resolve this issue:

1. **Verify Latest Versions**: Ensure you are using the latest versions of YOLOv5/YOLOv8 and all dependencies. Sometimes, bugs are fixed in newer releases.

2. **Separate Tracking Contexts**: When processing multiple inputs, especially cropped ROIs from a single frame, it's crucial to maintain separate tracking contexts for each input. This can help avoid ID conflicts. You might need to instantiate separate tracker objects for each input.

3. **Check Tracker Configuration**: Ensure that your tracker configuration (e.g., `bytetrack.yaml`) is correctly set up for handling multiple inputs. Sometimes, tweaking the tracker parameters can help resolve ID assignment issues.

4. **Batch Processing**: If you are processing multiple inputs in a batch, ensure that the batch processing logic correctly handles the tracking IDs. You might need to modify the code to ensure that IDs are unique across different inputs.

5. **Debugging**: Add debugging statements to check the intermediate outputs and ensure that the tracking IDs are being assigned correctly at each step. This can help identify where the IDs are getting mixed up.

Here is an example of how you might modify your code to handle separate tracking contexts:

```python
results = []
for source in source_list:
    result = model.track(source, persist=True, device=torch.device('cuda'), 
                         tracker="bytetrack.yaml", conf=0.6)
    results.append(result)
```

This approach ensures that each input is processed independently, which might help resolve the ID conflict issue.

If the issue persists, please provide more details about your setup and any error messages you encounter. This will help us better understand the problem and provide more specific guidance.

Feel free to check out our [documentation](https://docs.ultralytics.com/yolov5/) for additional resources and examples.
