### ISSUE TITLE
miss state_dict when save model (AttributeError: Can't pickle local object)?

### ISSUE THREAD

**Issue by anhtu-phan** [ultralytics/yolov5#10207]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have tried to pre-train YOLOv5x with the command  `python train.py --img 640 --batch 8 --epochs 150 --data data/coco128.yaml --weights checkpoint/yolov5x.pt` and met the bellow error

`Traceback (most recent call last):
  File "train.py", line 638, in <module>
    main(opt)
  File "train.py", line 531, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 385, in train
    torch.save(ckpt, last)
  File "/home/students/anhtu/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 423, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/students/anhtu/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 635, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'TorchHistory.add_log_parameters_hook.<locals>.<lambda>'`

I found that in `train.py` line 374-382 file when saving the model, it seems we miss `state_dict()`.  I have changed line 374-382 like below and it run? Am I wrong?
`ckpt = {
                    'epoch': epoch,
                    'best_fitness': best_fitness,
                    'model': deepcopy(de_parallel(model)).half().state_dict(),
                    'ema': deepcopy(ema.ema).half().state_dict(),
                    'updates': ema.updates,
                    'optimizer': optimizer.state_dict(),
                    'opt': vars(opt),
                    'date': datetime.now().isoformat()}`

**Comment by glenn-jocher** [comment]
That modification is not correct.

**Comment by anhtu-phan** [comment]
> 

Hello, could you please explain in more detail why that is not correct? And if it is not could you provide the solution to solve the error?

**Comment by glenn-jocher** [comment]
@anhtu-phan seems like your checkpoint may simply be corrupt or not fully downloaded. Just delete it and run your command again to let yolov5x.pt auto-download fully.

**Comment by anhtu-phan** [comment]
@glenn-jocher I have run again with command `python train.py --img 640 --batch 8 --epochs 300 --data data/coco128.yaml --weights yolov5x.pt`. The  error still occurs

**Comment by glenn-jocher** [comment]
@anhtu-phan 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by anhtu-phan** [comment]
@glenn-jocher Thank you for your support. It is my fault when adding another wandb to log :D

**Comment by glenn-jocher** [comment]
@anhtu-phan you're welcome! Glad to hear you figured it out. Don't hesitate to reach out if you have any more questions or need further assistance. Good luck with your YOLOv5 project! 👍
