### ISSUE TITLE
onnx export with detection layer: error:Detect object has no attribute forward_export 

### ISSUE THREAD

**Issue by Edwardmark** [ultralytics/yolov5#1023]
## ❔Question

I try to export to onnx with detection layer, and uncommnet the https://github.com/ultralytics/yolov5/blob/master/models/export.py#L38,
but it failed with error:
Detect object has no attribute forward_export 
## Additional context
so how to convert to onnx with detection layer correctly?
Thanks.

**Comment by Edwardmark** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
Hello @Edwardmark, thank you for your interest in our work! Please visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) to get started, and see our [Jupyter Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>, [Docker Image](https://hub.docker.com/r/ultralytics/yolov5), and [Google Cloud Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) for example environments.

If this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.

If this is a custom model or data training question, please note Ultralytics does **not** provide free personal support. As a leader in vision ML and AI, we do offer professional consulting, from simple expert advice up to delivery of fully customized, end-to-end production solutions for our clients, such as:
- **Cloud-based AI** systems operating on **hundreds of HD video streams in realtime.**
- **Edge AI** integrated into custom iOS and Android apps for realtime **30 FPS video inference.**
- **Custom data training**, hyperparameter evolution, and model exportation to any destination.

For more information please visit https://www.ultralytics.com.

**Comment by zhiqwang** [comment]
Hi @Edwardmark , I have exported the yolov5 with detection layers (containing `batched_nms` ops) based on ultralytics implementation [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/cc3e669989b4c98108b7c0693703e7784c0d68ed/test/test_onnx.py#L28) and [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/cc3e669989b4c98108b7c0693703e7784c0d68ed/models/__init__.py#L9) .

Also there is a onnx export [notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb).

**Comment by Edwardmark** [comment]
@zhiqwang Thanks, zhiq.
