### ISSUE TITLE
detect.py returns corrupted model error

### ISSUE THREAD

**Issue by oliviervluijk** [ultralytics/yolov5#10241]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone,

I’m running a YoloV5 model on Azure ML using a compute cluster which all works perfectly fine. In the train file I changed opt.save_dir from `str(increment_path(Path(opt.project) / opt.name, exist_ok=opt.exist_ok))` to `'logs/'`, since that is required when running on AzureML (to save the weights somewhere). The folder is indeed created, but when downloading last.pt/best.pt and running `!python detect.py --img 512 --data data/images --weights last.pt` the following error will occur: `RuntimeError: PytorchStreamReader failed reading file data/0: invalid header or archive is corrupted.`

Does anyone know what could go wrong?

EDIT: Downloading best.pt during training a yolov5l model resulted in this error: `RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`. Training parameters were: `python train.py --img 512 --batch 4 --epochs 300 --data data.yaml --weights yolov5l.pt --cfg yolov5l.yaml`

Thanks for your help,
Kind Regards,
Olivier

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by zihanding819** [comment]
hi @oliviervluijk, i've met the same issue with 'yolov5s.pt' ckpt, while there isn't any problem when evaluating with 'yolov5m.pt'. Have you got any idea to solve it ?

**Comment by glenn-jocher** [comment]
@zihanding819 your model is not fully downloaded, delete it and redownload it.
