### ISSUE TITLE
How does it work the dataloader? is it constantly getting frames?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#10243]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Maybe this is a question more related with OpenCV, but I would like to know how the data consumption works for remote streams.

In my case, I don't want to evaluate each frame from a rtsp url, so I add a `time.sleep(1)` to evaluate 1 fps. But I would like to know if despite my time sleep, the data consumption (transfer MB) is still happening. I mean, there's still a "tunnel" opened that allow me to request a frame in just a miliseconds. 

From [`dataloaders.py`](https://github.com/ultralytics/yolov5/blob/72cad39854a7d9ebbd4d58994cefa966b0da8fc1/utils/dataloaders.py#L405) file, I can assume there's just an update each time a frame is requested:
```
    def update(self, i, cap, stream):
        # Read stream `i` frames in daemon thread
        n, f = 0, self.frames[i]  # frame number, frame array
        while cap.isOpened() and n < f:
            n += 1
            cap.grab()  # .read() = .grab() followed by .retrieve()
            if n % self.vid_stride == 0:
                success, im = cap.retrieve()
                if success:
                    self.imgs[i] = im
                else:
                    LOGGER.warning('WARNING ⚠️ Video stream unresponsive, please check your IP camera connection.')
                    self.imgs[i] = np.zeros_like(self.imgs[i])
                    cap.open(stream)  # re-open stream if signal was lost
            time.sleep(0.0)  # wait time

    def __iter__(self):
        self.count = -1
        return self

    def __next__(self):
        self.count += 1
        if not all(x.is_alive() for x in self.threads) or cv2.waitKey(1) == ord('q'):  # q to quit
            cv2.destroyAllWindows()
            raise StopIteration

        im0 = self.imgs.copy()
        if self.transforms:
            im = np.stack([self.transforms(x) for x in im0])  # transforms
        else:
            im = np.stack([letterbox(x, self.img_size, stride=self.stride, auto=self.auto)[0] for x in im0])  # resize
            im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW
            im = np.ascontiguousarray(im)  # contiguous

        return self.sources, im, im0, None, ''
```

But I need to confirm if I'm right, i.e., there's no data consumption if I don't request a new frame, despite the "tunnel" is still open.

Thanks in advance

### Additional

I just add a `time.sleep(1)` (previously imported `time`) in [this](https://github.com/ultralytics/yolov5/blob/72cad39854a7d9ebbd4d58994cefa966b0da8fc1/detect.py#L206) line from `detect.py` as follows:

```
...
                    vid_writer[i].write(im0)

        # Print time (inference-only)
        LOGGER.info(f"{s}{'' if len(det) else '(no detections), '}{dt[1].dt * 1E3:.1f}ms")
        time.sleep(1)
...

```

**Comment by MartinPedersenpp** [comment]
If I remember correctly, an OpenCV pipeline/capture/stream will read data from the source at cv2.CAP_PROP_FPS = frames per second. 
If you add a time.sleep(n) you are creating a bottleneck that only allows for n frames per second, but the capture still runs at the predefined frames per second. 
So that might be why you are seeing data being transferred, the capture keeps pushing data, but your script will only process one each second.

I might be wrong, but this is what I noticed when working with OpenCV on a local webcam.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp thanks for your question! It seems like you've approached the situation correctly. When using time.sleep(n) with OpenCV, as you mentioned, the capture still runs at the predefined frames per second and continues to push data. Your script will only process one frame each second due to the bottleneck created by time.sleep(n). 

Your understanding of this mechanism is accurate, and your approach to managing the frame rate appears to be sound. Let us know if you have any more questions or need further assistance!
