### ISSUE TITLE
Class ids of custom dataset not being consecutive sequence

### ISSUE THREAD

**Issue by sclc713** [ultralytics/yolov5#1026]
## ❔Question
Hello, I am trying to train my custom dataset. Initially, I had a dataset of 12 classes of objects, and they were labeled with a consective sequence of class ids (from 0 to 11). Now, I need to merge objects of 2 classes into 1 class. The method I used was to simply change the class id in the annotations file. For instance, I replaced all ids of objects of class 8 with 1, when I wanted to merge all objects of class 8 into class 1. However, the class ids of my dataset would no longer be consecutive sequence then, since there was a hole (8) in the class id sequence.  And there would be only 11 classes left though the class ids were still from 0 to 11, after the replacement.

Will my way of merging object classes cause problems during training and inference?

I want to know the answer since I found that class names are defined in the yaml file (e.g. coco128.yaml). And the class id-name relation is not explicitly written in the file. Therefore, I am worrying that the hole in the class id sequence could cause id-name mis-matching issues. Am I right about this ?

Thanks

**Comment by glenn-jocher** [comment]
@CharLi713 if your classes are not sequential, there will simply be unused outputs in the model, which is not optimal but is not the end of the world either. Every class requires a name in your data.yaml, you can simply pass '' for unlabelled classes.

**Comment by sclc713** [comment]
I got it. Thanks !

**Comment by AbrahamRoshan** [comment]
challenges faced in Xtream1 tool while creating classes

I'm currently using the Xtreme1 tool for creating classes in the ontology section. I’m facing a couple of challenges and would appreciate any help:
 
Manual Assignment of Class IDs:
When I create a new class, the Class IDs are automatically assigned in sequential order. However, I need to assign specific Class IDs manually. Is there a way to override the automatic assignment and set the Class ID myself?
 
Managing Class ID Sequence After Deleting Datasets:
After deleting a dataset, Xtreme1 continues to track the previously generated Class IDs, and new classes are assigned the next available number. How can I reset or fix the Class ID sequence so that I can reuse or specify certain IDs?
 
Has anyone encountered similar issues, or does anyone know how to configure these settings?

**Comment by glenn-jocher** [comment]
Thank you for reaching out. Unfortunately, I'm not familiar with the Xtreme1 tool and its specific functionalities. For YOLOv5-related issues, I recommend ensuring your class IDs are sequential and correctly mapped in your data.yaml file. If you have further questions about YOLOv5, feel free to ask!
