### ISSUE TITLE
Easy way to specify a class's detect result

### ISSUE THREAD

**Issue by aileenfun** [ultralytics/yolov5#10275]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

For example there are 2 classes in the model. For class 0 return all result. For class 1, I only want the best confidence result.
Is there any way to do that?

Thank you!

**Comment by JustasBart** [comment]
Hi, how about you set the confidence to something rather low such so that everything gets detected and just do a manual check on the class type to see if it's say class '0' or class '1' and then if the class is '0' - simply display it - but if it's class '1' then do an **if** operation to check if the confidence is high enough and if it is - display it, but if it's not then ignore that prediction?

```
if (class == 1)
    if (classConfidence > 0.85)
        drawPrediction()
```

Where all **class == 0's** are displayed and **classes == 1** are conditionally displayed...

Or are you asking is there an existing mechanism that does this? Because I haven't seen one, but it should be somewhat easy to implement by yourself anyway...

**Comment by JustasBart** [comment]
@aileenfun I see, you could still achieve this by filtering out a list of some sort of **'class == 1'** detections only and then iterate them to find the one with the most confidence?

Consider the pseudo-code:
```
max_conf = 0
class1_highest_detection = 0

for (detection d : class1_detections):
    if (d.confidence > max_conf)
        class1_highest_detection = d
        max_conf = class1_highest_detection.confidence
```

Now your **class1_highest_detection** holds the highest confidence class 1 prediction by the end of this loop?

**Comment by aileenfun** [comment]
> @aileenfun I see, you could still achieve this by filtering out a list of some sort of **'class == 1'** detections only and then iterate them to find the one with the most confidence?
> 
> Consider the pseudo-code:
> 
> ```
> max_conf = 0
> class1_highest_detection = 0
> 
> for (detection d : class1_detections):
>     if (d.confidence > max_conf)
>         class1_highest_detection = d
>         max_conf = class1_highest_detection.confidence
> ```
> 
> Now your **class1_highest_detection** holds the highest confidence class 1 prediction by the end of this loop?

That's exactly  what I did.
Thank you!
