### ISSUE TITLE
How to save the predictions of a batch of images in a text file or a csv ?

### ISSUE THREAD

**Issue by souvikg544** [ultralytics/yolov5#10280]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to save the predictions of a batch of images in a text file or a csv ?

**Comment by JustasBart** [comment]
Hi, detect.py has a flag called **--save-txt**

Using this you can set up something like:

```
python3 detect.py \
--data /data/images/*.png \
--img 640 \
--save-txt \
--nosave \
--device 0
```
Where the **--nosave** flag means do not copy over the images. Of course don't use this if you do want to copy the images...

I would just save this as a .sh file so that I could remember and re-use it for later!

Hope that answer your question.

**Comment by glenn-jocher** [comment]
@JustasBart hi there! Thanks for jumping in to help. That's a great suggestion using the **--save-txt** flag in detect.py to save predictions in a text file. It's a handy feature for efficiently saving and reusing batch predictions. Your input is valuable to the YOLO community. Looking forward to more of your contributions. Cheers!
