### ISSUE TITLE
help yolo understand what to look for

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#10285]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all!

Quick question. lets say i have to train yolo to find cars, based on the color of the door handle. its a rather small detail of the car. Is there a way to tell yolo what to look for? the bounding box should remain on the whole car. so the class is the car itself, but the detail that classifies that car as car A or car B is the handle color. 

Thank you

Best regards

**Comment by JustasBart** [comment]
Hi, why not have two labels one for the car and the other for the handle itself? That way you should end up with two overlapping classes and from that you can determine car A from car B and just don't draw (Don'r visualise) the handle bounding box?

**Comment by tanzerlana** [comment]
Hi! isnt the handle too generic?
it will probably be found everywhere since its just a short line..

**Comment by JustasBart** [comment]
@tanzerlana But I mean if the handle is what tells car A apart from car B then isn't that the only (And therefore the best) option available to you to play with?
Because let's assume that the handle is too generic and that therefore it won't work... Well what isn't generic then? What else can you do to make it work? If there's a plan B then perhaps try both approaches, but if there is no plan B then just try it on a smaller dataset like 100 images train / 30 images val or something and you'll know your answer.

Also, don't underestimate the power of yolov5 in terms of generic features, it may turn out to be better than you might think (Or not)... If you're worried though use a bigger input size to the Network and please visualise it beforehand!

What I mean is if your data is 1920x1080 and if you train a 640x640 model then I'd say you're not in good shape! But you can use the --rect approach and train your model as say 1920x1088 and so now you'll know that if you can see the handle yolov5 should be able to see and hopefully learn the handle well enough.

Good luck!
