### ISSUE TITLE
How can I change my class name when using detect.py?

### ISSUE THREAD

**Issue by NeroChou66** [ultralytics/yolov5#10313]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have tried using 
python detect.py --data data/path/dataset.py 
but it does not do any thing, so what can I do else?

**Comment by JustasBart** [comment]
Hi, I believe that the way that it's done currently is by having your class names in your **_.yaml_** file like so:
```
path: **Your dataset base path**
train: **Your training images path relative to the base path**
val: **Your validation images path relative to the base path**
test:  **Your (optional) test images path relative to the base path**

# Classes
names:
  0: person
  1: bicycle
  2: etc...
```
Afterwards, once you train your model and run inference via **detect.py** it should know the correct names of those classes.
The alternative is though to just run inference yourself instead of relying on what **detect.py** does or even to just modify **detect.py** for your needs...

I personally run my inference via (C++ -> OpenCV -> OpenCV::dnn -> ONNX) and what that ultimately outputs is just class indexes (0, 5, 3, 2, 5, 1) etc... and so I can associate any name thereafter even after the model is trained...
And so you can do the same, figure out what needs to happen for Python to give you the class indexes and then read in the class names either from a file or hard-code them at that stage :)

Hope that helps

**Comment by RizwanMunawar** [comment]
@NeroChou66! Assume you have trained the model to detect **football**. In start of training, you have set the class name as **Football** in **data.yaml** file. Now, when you will run detect.py file to do detection on video/image/RTSP stream, the algorithm will show a label "Football" with every detection. If you want to replace it, you can add your own names in [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py#L97), something like mentioned below.

```
stride, names, pt = model.stride, model.names, model.pt   #original detect.py code line
names = ["class a name", "class b name", "class c name"........,"class n name"]
```

**Comment by NeroChou66** [comment]
> @NeroChou66! Assume you have trained the model to detect **football**. In start of training, you have set the class name as **Football** in **data.yaml** file. Now, when you will run detect.py file to do detection on video/image/RTSP stream, the algorithm will show a label "Football" with every detection. If you want to replace it, you can add your own names in [detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py#L97), something like mentioned below.
> 
> ```
> stride, names, pt = model.stride, model.names, model.pt   #original detect.py code line
> names = ["class a name", "class b name", "class c name"........,"class n name"]
> ```

thank you very much!! it works!!

**Comment by RizwanMunawar** [comment]
@NeroChou66! Glad your problem solved
