### ISSUE TITLE
Why does Yolov5 Trim my annotations ? 

### ISSUE THREAD

**Issue by arconym1** [ultralytics/yolov5#10310]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why does Yolov5 trim my annotations ? 
My labels are not in the right position.
But when I open labelimg they are in the right position ? 
https://user-images.githubusercontent.com/103209354/204126759-888f93f1-b111-47ac-a75c-299815a7a2bf.png)

I get this error when I try to upload the .png + .xml in Roboflow.
https://user-images.githubusercontent.com/103209354/204126868-93d41a40-5daf-4f91-a972-fd30263947f8.png

**Comment by glenn-jocher** [comment]
@arconym1 hi there! It sounds like you might be experiencing an issue with YOLOv5 trimming your annotations. This could be due to a variety of reasons, such as incorrect formatting or coordinate systems.

When using YOLOv5, it's important to ensure that your labels are in YOLO format and match the format expected by the model. Additionally, check if the coordinate system of your annotations is consistent with what's required by YOLOv5.

If your labels are correct in LabelImg but appear trimmed in YOLOv5, it's possible that there may be a discrepancy in how the annotations are interpreted between tools.

As for the error you're encountering in Roboflow, it could be related to the format or content of the annotations.

I'd recommend checking the YOLOv5 documentation for specific instructions and guidelines on annotation formatting and coordinate systems. If the issue persists, feel free to provide more details for further assistance. Keep up the great work!
