### ISSUE TITLE
Actual Convolutional layers doesn't reflect the parameters we pass via the config file

### ISSUE THREAD

**Issue by manikandakrishnan** [ultralytics/yolov5#10317]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/84121347/204273846-b598b45d-955c-4f83-b143-501c643b1032.png)
The yolov5s.yaml states that we want the output of the conv layer to give 64 features but what is being passed is 32.  This also gets reflected if you do a print(model) to print the torch style model output.

The logic in  line numbers 320-322 of model/yolo.py is causing this to happen , Is this by design ? What does this logic do ?

            c1, c2 = ch[f], args[0]
            if c2 != no:  # if not output
                c2 = make_divisible(c2 * gw, 8)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Zephyr69** [comment]
The width_multiple for yolov5s is 0.50

**Comment by glenn-jocher** [comment]
@Zephyr69 thanks for reaching out! The `width_multiple` parameter in the configuration file `yolov5s.yaml` scales the number of channels in the network layers. Specifically, the logic in `model/yolo.py` scales the channels according to the `width_multiple` value. 

By design, if the `width_multiple` is set to 0.50, it scales down the number of channels to half, hence resulting in 32 features instead of the originally specified 64 in your case.

If you have additional questions or need further assistance, feel free to ask!
