### ISSUE TITLE
ImportError: cannot import name 'TryExcept' from 'utils'

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/yolov5#10323]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

```
python train.py --data D:/0SDXX/yolov5/data/VOC.yaml --epochs 300 --weights D:/0SDXX/yolov5/Yolov5_PT/yolov5s6.pt --cfg D:/0SDXX/yolov5/models/yolov5s.yaml  --batch-size 60

Traceback (most recent call last):
  File "train.py", line 42, in <module>
    import val as validate  # for end-of-epoch mAP
  File "D:\0SDXX\yolov5\val.py", line 38, in <module>
    from models.common import DetectMultiBackend
  File "D:\0SDXX\yolov5\models\common.py", line 28, in <module>
    from utils import TryExcept
ImportError: cannot import name 'TryExcept' from 'utils' (D:\0SDXX\yolov5\utils\__init__.py)
```

### Environment

WIN11
v7.0 - YOLOv5
torch 1.13.0   
cuda11.6  cudnn8.4
Python 3.8.13

### Minimal Reproducible Example

```
path: D:/0SDXX/labelme/examples/bbox_detection/TouBU_CJ_OK_VOC/0VOC2
train: # train images (relative to 'path')  16551 images
  - D:/0SDXX/labelme/examples/bbox_detection/TouBU_CJ_OK_VOC/0VOC2/train_list.txt
val: # val images (relative to 'path')  4952 images
  - D:/0SDXX/labelme/examples/bbox_detection/TouBU_CJ_OK_VOC/0VOC2/val_list.txt
test: # test images (optional)
  - D:/0SDXX/labelme/examples/bbox_detection/TouBU_CJ_OK_VOC/0VOC2/test_list.txt
```

`JPEGImages\TouBU_CJ_5311.jpg Annotations\TouBU_CJ_5311.xml
`
`python train.py --data D:/0SDXX/yolov5/data/VOC.yaml --epochs 300 --weights D:/0SDXX/yolov5/Yolov5_PT/yolov5s6.pt --cfg D:/0SDXX/yolov5/models/yolov5s.yaml  --batch-size 60`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Davidsonson** [comment]
If anyone else sees this, I found the issue was that I has a different utils.py being loaded. Solutions for me was to use 2 different scripts for the json2yolo conversion and the actual training.

**Comment by flag16** [comment]
Hi, I had a similar problem, did you finally solve the problem?

**Comment by Davidsonson** [comment]
my issue was that I had 2 different packages that both had a utils.py file so I had to split the functions of those into separate scripts. 
You could possibly also alter all of the `from utils import ...` lines to use relative paths but that was harder than I needed it to be since I could just split into 2 scripts, 1 for loading data and 1 for training. If your use case won't allow splitting then changing those imports is your only option.

**Comment by flag16** [comment]
Thank you very much, I have solved the problem

**Comment by GeniusMpala** [comment]
@flag16  can you show me

**Comment by glenn-jocher** [comment]
@GeniusMpala hello, if you're still having issues with the `ImportError: cannot import name 'TryExcept' from 'utils'` error, it is likely due to having multiple versions of the `utils.py` file in your Python path. You can try running `python -c "import utils; print(utils.__file__)"` to see which `utils.py` file is being loaded. 

If you have multiple versions, you can try renaming or deleting the one causing the conflict. Another solution is to change the import statements to include the full path to the `utils.py` file. 

If you have any more questions or issues, feel free to ask!

**Comment by marcemq** [comment]
Hello @GeniusMpala what I did to work-around this issue: rename my local `utils` module, i.e.: `myUtils`.

```
├── myUtils
│   └── parser.py
```

**Comment by glenn-jocher** [comment]
Hello @marcemq, 

Thank you for bringing this issue to our attention. Renaming your local `utils` module to something else, for example `myUtils` is a good workaround since this error is usually caused by having multiple versions of the `utils.py` file in your Python path. 

If you have any further issues or questions, please don't hesitate to ask. Thank you for using YOLOv5!

**Comment by ljubanradisin** [comment]
For me, that error was occuring when using predict.py for yolov5 classification in the form of ImportError: cannot import name 'TryExcept' from 'utils' ('path to init.py' (which is inside site_packages/utils, in my conda environment)). Also this py file was empty.
After trying this command : python -c "import utils; print(utils.file)", it seems that it wants to load init.py from my utils module inside yolov5 folder. So I just erased this init.py file from my conda environment, and it seems to work now for predicting.

**Comment by ljubantomic01** [comment]
For me, that error was occuring when using predict.py for yolov5 classification in the form of **ImportError: cannot import name 'TryExcept' from 'utils'** ('path to init.py' (which is inside site_packages/utils, in my conda environment)). Also this py file was empty.
After trying this command : python -c "import utils; print(utils.file)", it seems that it wants to load init.py from my utils module inside yolov5 folder. So I just erased this init.py file from my conda environment, and it seems to work now for predicting.

**Comment by glenn-jocher** [comment]
@ljubanradisin hello,

Thank you for sharing your experience and workaround regarding the `ImportError: cannot import name 'TryExcept' from 'utils'` error in predict.py for YOLOv5 classification.

It appears that the issue was caused by conflicting `init.py` files in your conda environment. By removing the `init.py` file from the utils module inside the YOLOv5 folder, you were able to resolve the error.

We appreciate you sharing your solution, as it may help others facing a similar issue. If you have any further questions or need additional assistance, please don't hesitate to ask.

Thank you for your contribution and support of YOLOv5!

**Comment by Bhavana22-cmd** [comment]
Hi, I am running the below code snippet in my anaconda environment, "best.pt" contains my custom model weights , it is throwing errors related to utils, i removed __init__.py file from my anaconda environment as mentioned by @ljubantomic01 and its still not working 

```
from ultralytics import YOLO
import torch

model = torch.hub.load('C:/Users/Name/Documents/AI/yolov5', 'custom', path='best.pt', source='local') 
model.conf = 0.5
model.iou = 0.5
results= model('BloodImage_00038_jpg.rf.96272d1d5af9fb649cfcb2b36f4895f6.jpg', size=416)
results.show()
```

Its giving the following errors:
---------------------------------------------------------------------------
**ImportError**                               Traceback (most recent call last)
Cell In[15], line 4
      1 from ultralytics import YOLO
      2 import torch
----> 4 model = torch.hub.load('C:/Users/Name/Documents/AI/yolov5', 'custom', path='best.pt', source='local') 
      5 # model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt', force_reload=True)
      6 model.conf = 0.5

File ~\Anaconda3\envs\ML-DL\lib\site-packages\torch\hub.py:566, in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    562 if source == 'github':
    563     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
    564                                        verbose=verbose, skip_validation=skip_validation)
--> 566 model = _load_local(repo_or_dir, model, *args, **kwargs)
    567 return model

File ~\Anaconda3\envs\ML-DL\lib\site-packages\torch\hub.py:595, in _load_local(hubconf_dir, model, *args, **kwargs)
    592     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
    594     entry = _load_entry_from_hubconf(hub_module, model)
--> 595     model = entry(*args, **kwargs)
    597 return model

File C:/Users/Name/Documents/AI/yolov5\hubconf.py:88, in custom(path, autoshape, _verbose, device)
     86 def custom(path="path/to/model.pt", autoshape=True, _verbose=True, device=None):
     87     # YOLOv5 custom or local model
---> 88     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)

File C:/Users/Name/Documents/AI/yolov5\hubconf.py:34, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     17 """
     18 Creates or loads a YOLOv5 model.
     19 
   (...)
     30     YOLOv5 model
     31 """
     32 from pathlib import Path
---> 34 from models.common import AutoShape, DetectMultiBackend
     35 from models.experimental import attempt_load
     36 from models.yolo import ClassificationModel, DetectionModel, SegmentationModel

File ~\Documents\AI\yolov5\models\common.py:38
     34     import ultralytics
     36 from ultralytics.utils.plotting import Annotator, colors, save_one_box
---> 38 from utils import TryExcept
     39 from utils.dataloaders import exif_transpose, letterbox
     40 from utils.general import (
     41     LOGGER,
     42     ROOT,
   (...)
     55     yaml_load,
     56 )

**ImportError:** cannot import name 'TryExcept' from 'utils' (unknown location)
Selection deleted

**Comment by glenn-jocher** [comment]
Hi there! It looks like the issue might be related to Python not being able to find the correct `utils` module due to a path conflict. Here are a couple of things you could try:

1. **Ensure Correct Import Paths**: Make sure that the directory containing your `utils` module is correctly included in your Python path. You can check your current Python path by printing `sys.path`.

2. **Use Absolute Imports**: Modify the import statements in your YOLOv5 code to use absolute imports. For example, change `from utils import TryExcept` to `from yolov5.utils import TryExcept` assuming `yolov5` is the root directory of your project.

3. **Check for Name Conflicts**: Ensure there are no other files or directories in your project or Python path named `utils` that could be causing conflicts.

If these suggestions don't resolve the issue, you might want to ensure that all files are correctly placed and that there are no missing `__init__.py` files in your directories which are necessary for Python to recognize directories as packages.

Hope this helps! Let me know if you have any more questions. 😊

**Comment by SabarishCodeWizard** [comment]
Title: ImportError: Cannot Import Name 'TryExcept' Due to Circular Import in utils Module

Body:

I'm encountering a circular import error in my Python project related to the `TryExcept` class in the `utils` module. The error traceback is as follows:


Traceback (most recent call last):
  File "C:\Users\ravik\Downloads\prabha\backend\app.py", line 10, in <module>
    from models.common import DetectMultiBackend
  File "C:\Users\ravik\Downloads\prabha\backend\models\common.py", line 38, in <module>
    from utils import TryExcept
  File "C:\Users\ravik\Downloads\prabha\backend\utils\__init__.py", line 12, in <module>
    from utils.general import LOGGER, colorstr, cv2
  File "C:\Users\ravik\Downloads\prabha\backend\utils\general.py", line 48, in <module>
    from utils import TryExcept, emojis
ImportError: cannot import name 'TryExcept' from partially initialized module 'utils' (most likely due to a circular import) (C:\Users\ravik\Downloads\prabha\backend\utils\__init__.py)


Details:
- The circular import seems to occur between `utils/__init__.py` and `utils/general.py`.
- `TryExcept` is being imported in both `common.py` and `general.py`.
- This results in the module `utils` being partially initialized when `TryExcept` is imported, leading to the `ImportError`.

Steps I've Taken:
- Tried moving the import statement inside the functions that use it, but the issue persists.
- Double-checked the import paths for possible inadvertent recursive imports.

Request:
I’m looking for advice on how to resolve this circular import. Should I restructure my modules, or is there a simpler solution? Any guidance or best practices would be appreciated!

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue. Circular imports can be tricky. To resolve this, you can try restructuring your imports to avoid circular dependencies. One approach is to move the import statements inside the functions or methods where they are used. Alternatively, consider refactoring your code to reduce interdependencies between modules. If the issue persists, please verify if it occurs with the latest version of the YOLOv5 repository.
