### ISSUE TITLE
Why the value of target in build_target is empty, but my labels aren't empty?

### ISSUE THREAD

**Issue by broalantaps** [ultralytics/yolov5#10422]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Why the value of target in build_target is empty, but my labels aren't empty?
And I got the fail tip:

Traceback (most recent call last):
  File "train.py", line 366, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/loss.py", line 487, in __call__
    tcls, tbox, indices, anchors, anchors_box_, txyxyxyxy_ = self.build_targets(p, targets)  # targets
  File "/home/rp/DeepLearning/RobotPilots-master/utils/loss.py", line 648, in build_targets
    **gi, gj = gij.T  # grid xy indices
ValueError: not enough values to unpack (expected 2, got 0)**

When I debug, I found that build_targets(p, targets) -> targets is empty at the third layer(when nl = 2).

When I checked my labels by python, they aren't empty.

Could you please help me to solve this problem? Appreciate!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@broalantaps 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by broalantaps** [comment]
> @broalantaps wave hi, thanks for letting us know about this possible problem with YOLOv5 rocket. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.
> ## How to create a Minimal, Reproducible Example
> 
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
>     * white_check_mark **Minimal** – Use as little code as possible to produce the problem
> 
>     * white_check_mark **Complete** – Provide all parts someone else needs to reproduce the problem
> 
>     * white_check_mark **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
>     * white_check_mark **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> 
>     * white_check_mark **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code warning.
> 
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the bug **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! smiley

Sorry, I think it's no bug because I have edited the code (I want to change the output)
