### ISSUE TITLE
How can I use USB camera to detect?(I have already tried modifying track.py --device 1 to 50)

### ISSUE THREAD

**Issue by weichen1209** [ultralytics/yolov5#10456]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I use USB camera to detect?(I have already tried to modifying track.py --device 1 to 50)

**Comment by barney2074** [comment]
- Not sure what track.py is- perhaps you are using StrongSort with YoloV5 ?
- With plain YoloV5, the --device argument for detect.py determines if CPU or GPU(s) are used for inferencing. You can probably leave this blank
- for detect.py- the --source argument will allow you to select a webcam
i.e `python detect.py --weights yolov5s.pt --source 0 `

**Comment by glenn-jocher** [comment]
@barney2074 thanks for reaching out! For using a USB camera with YOLOv5, you can specify the source as the USB camera using the --source argument in detect.py. For example, you can use `python detect.py --weights yolov5s.pt --source 0` to select the webcam. The --device argument is usually for specifying CPU or GPU usage and can be left blank for most cases. Let me know if you have any more questions!

**Comment by jin0506** [comment]
Hi, I am also running YOLOv5 on my usb camera. However, I got this error "AttributeError: 'NoneType' object has no attribute shape." when I run it. But it runs perfectly fine if I am using my webcam.

**Comment by glenn-jocher** [comment]
@jin0506 It seems like the error "AttributeError: 'NoneType' object has no attribute shape" could be due to an issue with accessing frames from the USB camera. This could be caused by the camera resolution or format. You may want to check if your USB camera is providing frames correctly and in a compatible format for YOLOv5. You could also try specifying the resolution or format of the USB camera using additional arguments in the detect.py script, such as `--img-size` or `--format`. Let me know if you need further assistance!
