### ISSUE TITLE
Yolov5_openvino_model not working on raspberrypi4 with ncs2

### ISSUE THREAD

**Issue by glennford49** [ultralytics/yolov5#10463]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have successfully run yolov5n model in raspberrypi, 
I also have run successfully the intel openvino models on my raspberry with NCS2, since I build openvino 2022.2.0 from source however running yolov5 using the exported model to openvino on my raspberry is not working, it needs openvino-dev, i have my openvino 2022.2.0 built from scratch. And openvino-dev is not yet supported on arm i think... any fix for this problem?

### Additional

I ran the same yolov5 openvino exported model on my laptop, it works just fine since it has openvino-dev installed
Is there any way that i can modify the code to use existing openvino version (2.0)? instead of looking only for openvino-dev which 64 bit arm currently not supported.

**Comment by glenn-jocher** [comment]
@glennford49 hi there! Thanks for reaching out. It sounds like you've encountered an issue with the YOLOv5_openvino_model on your Raspberry Pi 4 with the NCS2.

Currently, Raspberry Pi support in OpenVINO is limited, and it seems that the lack of openvino-dev for ARM architecture may be causing the issue. Modifying the code to use an existing OpenVINO version (2022.2.0) instead of openvino-dev could be a potential workaround, but it might involve significant changes to the YOLOv5_openvino_model codebase and possibly the OpenVINO toolkit itself.

I'd recommend checking the official OpenVINO documentation and community forums for any updates or workarounds related to ARM support. You might also want to explore alternative deployment options or consider reaching out to the OpenVINO community for further guidance.

Please let me know if you have any other questions, and we'll do our best to assist you!
