### ISSUE TITLE
How does conf-thres affect main MOT metric results?

### ISSUE THREAD

**Issue by lorenzlorg** [ultralytics/yolov5#10489]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've **trained** YOLOv5 on a custom dataset and then I **validated** it on test data using _val.py_ using default values for conf-thres (0
.001) and iou-thres (0.6). I've obtained good results in mAP@0.5.

Now I was trying to use my YOLOv5 weights to make some **inferences**, on new images/videos, in particular I'm using YOLOv5+deepSORT to track pedestrians. 

**It does make sense to consider a higher conf-thres in _detect.py_ or _track.py_ in order to obtain more accurate results. Or should I use the same threshold values used in the validation phase?**

**Comment by AyushExel** [comment]
@lorenzlorg the detect.py thresholds are meant to be tuned by the user depending on your task and performance you need.
It should be fixed in val.py to make sure your tests are standard. But you can change it too if you want.
Regarding track.py, I can't say much as we currently don't support tracking but our friend @mikel-brostrom might be able to help. He's the creator of the most popular tracking project - https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet

**Comment by mikel-brostrom** [comment]
As @AyushExel pointed out. The threshold depends on your use case and your specific model. For `track.py` in https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet and a standard `Yolov5m` model these are the results for the different MOT metrics wrt. the `conf-thres`:

<div align="center">
<p>
<img src="https://user-images.githubusercontent.com/18719680/207555371-75d3af29-7fa3-4fdc-84f6-23d74f833795.png"  width=300>
</p>
</div>

The crux here is that different metrics peak differently for different `conf-thres` values, but the general guideline is that you should be aiming for maximum HOTA for best tracking results. In order to understand this you need some MOT metric background: MOTA and IDF1 overemphasize detection and association respectively. HOTA explicitly measures both types of errors and combines these in a balanced way. HOTA also incorporates measuring the localization accuracy of tracking results which isn’t present in either MOTA or IDF1.

Moreover,

↑ conf-thres: faster tracker inference time as there are less detections to process
↓ conf-thres: slower tracker inference time as there are more detections to process

**Comment by lorenzlorg** [comment]
many thanks for your explanation @AyushExel @mikel-brostrom

**Comment by mikel-brostrom** [comment]
Maybe this discussion should be renamed to: 

> How does `conf-thres` affect main MOT metric results?

@AyushExel
