### ISSUE TITLE
Yolov5 upgrade leads to reduced performance 

### ISSUE THREAD

**Issue by RRighart** [ultralytics/yolov5#10533]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Recently, I have upgraded Yolov5 that runs in Docker on my machine.
Before, it was YOLOv5 🚀 v6.1-25-gcaf7ad0 torch 1.10.2+cu113 CPU
Now it is YOLOv5 🚀 v7.0-41-g10e93d2 Python-3.8.10 torch-1.13.0a0+936e930 CPU.

I am using the following line for training :
    
`python train.py --img 640 --batch 16 --epochs 80 --workers 4 --data /usr/src/datasets/data.yaml --hyp hyp.ownsettings.yaml --weights yolov5s.pt
`
There is a clear difference in the results. 
My previous version of Yolov5 seemed better than the current one while they used the same data as input. 
However, as you see, the number of layers is also different in the model summary (now 157, before 213 layers).

**Now :**
Model summary: _157_ layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:03<00:00,  1.96s/it]
                   all         39        480      0.667      0.828      0.788      0.724
               A         39        261      0.706      0.766      0.858      0.784
                B         39        219      0.629       0.89      0.719      0.665
      
**Before:**
Model Summary: _213_ layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 2/2 [00:04<00:00,  2.09s/it] 
                 all         39        480      0.761      0.886      0.879      0.819
             A         39        261      0.791      0.858       0.92      0.856
              B         39        219       0.73      0.914      0.838      0.781

Would you have any idea why the number of layers is different ? What could be the reason for the difference in performance ?
Thank you very much in advance for your help!

**Comment by glenn-jocher** [comment]
@RRighart 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

I'd recommend providing a script like this showing a reproducible difference between commit hashes with a common model on a common dataset, otherwise there is no action for us to take:

```bash
git clone https://github.com/ultralytics/yolov5
git checkout COMMIT1
python val.py --weights yolov5s.pt --data coco128.yaml
git checkout COMMIT2
python val.py --weights yolov5s.pt --data coco128.yaml  # allegedly different result
```

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
