### ISSUE TITLE
I am getting error when running yolov5 in container, whereas it works fine in local machine. I am trying batch inference

### ISSUE THREAD

**Issue by vipingautam1906** [ultralytics/yolov5#10584]
Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to yolov5s.pt...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14.1M/14.1M [00:03<00:00, 4.68MB/s]

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    results = model(all_frames, size = 640)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 697, in forward
    shape1 = [make_divisible(x, self.stride) for x in np.array(shape1).max(0)]  # inf shape
  File "/opt/conda/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by glenn-jocher** [comment]
@vipingautam1906 this error can occur due to mismatched input dimensions. It's possible that the batched inputs have different sizes, resulting in an empty array. Ensure that your input frames have consistent dimensions. For further assistance with batch inference, do refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. If issues persist, please feel free to provide more context or a minimal reproducible example for us to better assist you.
