### ISSUE TITLE
How to generate predictions during training for segmentation? 

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/yolov5#10597]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training is done, YOLO5 is awesome enough to automatically provide images with predictions of the model (val_batch0_pred.jpg). 
![image](https://user-images.githubusercontent.com/95919873/209572701-a6dec831-dbe9-4bc1-8980-8d0434ad28d7.png)

I would like to generate those images every X epochs when training for instance segmentation. 
I've looked at yolov5/segment/train.py to see if there are any argument options, but didnt find any for validation batch predictions.
![image](https://user-images.githubusercontent.com/95919873/209576599-396d3ca1-2f84-488d-b0df-6260c53785f1.png)

**Comment by AyushExel** [comment]
@Robotatron thanks for the kind words. Yes, the segmentation task doesn't support setting prediction intervals. Initially, we didn't provide this because segmentation plotting is memory demanding so it becomes easier to shoot oneself in the foot. 
But in the next release which is coming soon, we'll have better support for plotting settings

**Comment by Robotatron** [comment]
@AyushExel Awesome, great to hear!

Another question, similar to plotting predictions, would be about per class validation mAP scores for instance segmentation:

1. It would be very helpful to log per class validation mAP during training for tensorboard (in addition to mAP_0.5:0.95(M) etc), example:
![image](https://user-images.githubusercontent.com/95919873/210022352-46100de1-6a13-47be-922a-e67fa7c81336.png)

2. As above, but for the console output,  it would be very helpful to log per class validation mAP to the console during training like YOLO5 does now at the end of training:
![image](https://user-images.githubusercontent.com/95919873/210022316-74aafee0-b03d-4033-af1a-e71b6cf2a25f.png)

Are there any plans on adding per class validation mAP scores in the future?

**Comment by AyushExel** [comment]
@Robotatron that's a good point. I think a few users have raised this issue. The problem here is that if we do that by default then there will be a lot of noise in the terminal and dashboard. I think the right way would be to allow setting a verbosity level. I'll add that to our TODOs for later releases

**Comment by Robotatron** [comment]
@AyushExel yes, it could be an option for the console. For tensorboard I think you can safely log it by default, maybe in a different tab that can be easily collapsed in Tensorboard.

Thanks adding this to TODO, YOLO5 seems like a great framework so far. Adding interval for prediction plotting and per class mAP would make it even better :)

Will wait for future releases, thanks!

**Comment by Robotatron** [comment]
@AyushExel Should I open two feature requests for two suggestions mentioned above or is it fine as it is?

**Comment by AyushExel** [comment]
@Robotatron No its fine. I've added it to our feature requests
