### ISSUE TITLE
Slow Training on Jetson Orin

### ISSUE THREAD

**Issue by LinirZamir** [ultralytics/yolov5#10620]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am currently trying to train a very simple model on my Jetson Orin. 

The purpose is to train it using custom dataset of only 10 images, for 100 epochs.
I am using the yolov5/train.py with a custom dataset and yaml file. 

When I train it on my Lenovo Titan Nvidia, it runs fast and the results are good. 
However, when I test it on a newly flashed Jetson Orin with Pytorch version 1.13 and Cuda 11.4 it runs extremely slow.. 

It must be something to do with the configuration, but I couldn't find any possible solutions to this issue. 
Training command:

python3 yolov5/train.py --data custom.yaml

**Also**
I am getting a WARNING NMS time limit 0.850s exceeded every epoch. 

I would appreciate any help on the matter. Thank you.

**Comment by glenn-jocher** [comment]
@LinirZamir hi there,

Training YOLOv5 on Jetson Orin can indeed be slower compared to high-end desktop GPUs due to hardware limitations. You might want to consider reducing the model size or batch size to speed up training. Additionally, the NMS time limit warning can indicate that the NMS (Non-Maximum Suppression) is taking too long, which could also affect training speed.

Make sure you have installed the necessary dependencies for GPU support on Jetson Orin and consider performance optimization strategies such as adjusting batch size and model architecture. For more detailed guidance, check out the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Hope this helps!
