### ISSUE TITLE
Object detection with Yolov5 and webcam

### ISSUE THREAD

**Issue by AfiaFaith** [ultralytics/yolov5#10643]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

After training my dataset on Google Colab, i am trying to apply my model to my webcam but i am getting this error:

AttributeError Traceback (most recent call last)
C:\Users\xxxxx~1\AppData\Local\Temp/ipykernel_19392/3255609503.py in
2 from imageai import Detection
3 yolo = Detection.ObjectDetection()
----> 4 yolo.setModelTypeAsYOLOv5()
5 yolo.setModelPath(modelpath)
6 yolo.loadModel()

AttributeError: 'ObjectDetection' object has no attribute 'setModelTypeAsYOLOv5'

### Environment

YOLOv5
Windows 11
Python 3.9

### Minimal Reproducible Example

Below is my code.

modelpath = "C:/Users/xxxxx/Downloads/project/best.pt" #best.pt is my trained model
from imageai import Detection
yolo = Detection.ObjectDetection()
yolo.setModelTypeAsYOLOv5()
yolo.setModelPath(modelpath)
yolo.loadModel()

import cv2
cam = cv2.VideoCapture(0) #0=front-cam, 1=back-cam
cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1300)
cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 1500)

while True: ## read frames
ret, img = cam.read() ## predict yolo
img, preds = yolo.detectCustomObjectsFromImage(input_image=img,
custom_objects=None, input_type="array",
output_type="array",
minimum_percentage_probability=70,
display_percentage_probability=False,
display_object_name=True) ## display predictions
cv2.imshow("", img) ## press q or Esc to quit
if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
break## close camera
cam.release()
cv2.destroyAllWindows()

### Additional

I am new to computer vision and python.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Tabbleman** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.
> 
> ### YOLOv5 Component
> _No response_
> 
> ### Bug
> After training my dataset on Google Colab, i am trying to apply my model to my webcam but i am getting this error:
> 
> AttributeError Traceback (most recent call last) C:\Users\xxxxx~1\AppData\Local\Temp/ipykernel_19392/3255609503.py in 2 from imageai import Detection 3 yolo = Detection.ObjectDetection() ----> 4 yolo.setModelTypeAsYOLOv5() 5 yolo.setModelPath(modelpath) 6 yolo.loadModel()
> 
> AttributeError: 'ObjectDetection' object has no attribute 'setModelTypeAsYOLOv5'
> 
> ### Environment
> YOLOv5 Windows 11 Python 3.9
> 
> ### Minimal Reproducible Example
> Below is my code.
> 
> modelpath = "C:/Users/xxxxx/Downloads/project/best.pt" #best.pt is my trained model from imageai import Detection yolo = Detection.ObjectDetection() yolo.setModelTypeAsYOLOv5() yolo.setModelPath(modelpath) yolo.loadModel()
> 
> import cv2 cam = cv2.VideoCapture(0) #0=front-cam, 1=back-cam cam.set(cv2.CAP_PROP_FRAME_WIDTH, 1300) cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 1500)
> 
> while True: ## read frames ret, img = cam.read() ## predict yolo img, preds = yolo.detectCustomObjectsFromImage(input_image=img, custom_objects=None, input_type="array", output_type="array", minimum_percentage_probability=70, display_percentage_probability=False, display_object_name=True) ## display predictions cv2.imshow("", img) ## press q or Esc to quit if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27): break## close camera cam.release() cv2.destroyAllWindows()
> 
> ### Additional
> I am new to computer vision and python.
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

so how did you fixed it?

**Comment by glenn-jocher** [comment]
@Tabbleman, the `AttributeError` you are experiencing indicates that the `ObjectDetection` object does not have the method `setModelTypeAsYOLOv5()`.

It seems like you are using the `imageai` library instead of the official `yolov5` library. The `imageai` library uses a different API than the one provided by YOLOv5. The method `setModelTypeAsYOLOv5()` does not exist in the `ObjectDetection` class of the `imageai` library.

To use YOLOv5 with your webcam, I recommend using the official `yolov5` library. You can find the official repository at https://github.com/ultralytics/yolov5. 

Make sure you have cloned the repository and installed the required dependencies. Then you can modify your code to use the `yolov5` library:

```python
import cv2
import torch
from IPython.display import Image, display

# Load the model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Set webcam input
cam = cv2.VideoCapture(0)

while True:
    # Read frames
    ret, img = cam.read()

    # Perform object detection
    results = model(img)

    # Display predictions
    results.show()
    
    # Press 'q' or 'Esc' to quit
    if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
        break

# Close the camera
cam.release()
cv2.destroyAllWindows()
```

This code uses the official `yolov5` library to load the model and perform object detection on webcam frames. The predictions are then displayed using the `show()` method provided by the library. Remember to install the required dependencies and replace the model path with your trained model.

Let me know if you have any further questions or issues!

**Comment by Tabbleman** [comment]
thanks for your early reply:-)

**Comment by glenn-jocher** [comment]
@Tabbleman hi there,

Thank you for reaching out and providing your code snippet. Upon reviewing your code, it seems that you are using the `imageai` library instead of the official `yolov5` library.

The `AttributeError` you encountered indicates that the `ObjectDetection` object from the `imageai` library does not have the `setModelTypeAsYOLOv5()` method.

To resolve the issue and use YOLOv5 with your webcam, I recommend utilizing the official `yolov5` library. You can find the official repository at https://github.com/ultralytics/yolov5.

Please ensure that you have cloned the repository and installed the necessary dependencies. Afterwards, make the following modifications to your code:

```python
import cv2
import torch
from IPython.display import Image, display

# Load the model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Set webcam input
cam = cv2.VideoCapture(0)

while True:
    # Read frames
    ret, img = cam.read()

    # Perform object detection
    results = model(img)

    # Display predictions
    results.show()
    
    # Press 'q' or 'Esc' to quit
    if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
        break

# Close the camera
cam.release()
cv2.destroyAllWindows()
```

Please note that this code makes use of the official `yolov5` library to load the model and perform object detection on webcam frames. The predictions are displayed using the `show()` method provided by the library. Remember to replace the model path with the path to your trained model and install the required dependencies.

Feel free to ask if you have any further questions or encounter any issues!

**Comment by ASV1995** [comment]
This code worked for me. Need to train my model more though (Using custom data)

`import cv2
import torch
from IPython.display import Image, display

path = r'best.pt'
model = torch.hub.load('ultralytics/yolov5', 'custom', path, force_reload=True)
model.eval()

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    frame=cv2.resize(frame, (500,500))
    results = model(frame)
    frame = np.squeeze(results.render())
    cv2.imshow('FRAME',frame)
    
    
    if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
        break

cam.release()
cv2.destroyAllWindows()`

**Comment by ASV1995** [comment]
"This code worked for me. Need to train my model more though (Using custom data)

`import cv2
import torch
from IPython.display import Image, display

path = r'best.pt'
model = torch.hub.load('ultralytics/yolov5', 'custom', path, force_reload=True)
model.eval()

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    frame=cv2.resize(frame, (500,500))
    results = model(frame)
    frame = np.squeeze(results.render())
    cv2.imshow('FRAME',frame)
    
    
    if (cv2.waitKey(1) & 0xFF == ord("q")) or (cv2.waitKey(1)==27):
        break

cam.release()
cv2.destroyAllWindows()`"
