### ISSUE TITLE
YOLOv5m-seg and YOLOv5s-seg post processing different?

### ISSUE THREAD

**Issue by himansh1314** [ultralytics/yolov5#10670]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there a difference in the post processing of YOLOv5m-seg and YOLOv5s-seg? I made a pipeline for YOLOv5s-seg and it worked fine, however after training YOLOv5m-seg and using the same model there, It's throwing some error in non max suppression. Apparently the output dimensions aren't the same and the YOLOv5m-seg seems to be returning some feature pyramid.

**Comment by glenn-jocher** [comment]
@himansh1314 the post-processing for YOLOv5m-seg and YOLOv5s-seg models should behave similarly. However, the different model sizes may result in output dimensions that need to be handled accordingly. YOLOv5m-seg is designed to utilize feature pyramids, which may require adjustments to your post-processing pipeline. You can refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for further details on working with different model variations. If you encounter specific errors, please provide more details so that I can assist you further.
