### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.downloads'

### ISSUE THREAD

**Issue by kevserbusrayildirim** [ultralytics/yolov5#10694]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I'm getting this error after cloning the yolov5 repo and installing requirements. I'm trying to run the codes on my own computer by downloading them from colab as .ipynp file.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], line 3
      1 import torch
      2 from IPython.display import Image, clear_output  # to display images
----> 3 from utils.downloads import attempt_download  # to download models/datasets
      5 # clear_output()
      6 print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

ModuleNotFoundError: No module named 'utils.downloads'

### Environment

-Yolo : YOLOv5
-I'm using MACOS (M2)
-Python 3.9.13

### Minimal Reproducible Example

import torch
from IPython.display import Image, clear_output  # to display images
from utils.downloads import attempt_download  # to download models/datasets

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kevserbusrayildirim hi there! It looks like you are experiencing an issue with the YOLOv5 repository. The error you are encountering is likely due to changes in the project structure. 

The `utils.downloads` module has been refactored to `utils.general` since v5.0. To resolve the issue, you can update the import statement to `from utils.general import attempt_download`.

Let me know if this fixes the problem for you or if you need further assistance. Thank you for reaching out!

**Comment by xiaokelly** [comment]
@kevserbusrayildirim Hi，I have encountered the same problem as you. Perhaps you can try changing the code as follows:
`from ultralytics.yolo.utils.downloads import download`
My Environment
-Yolo : YOLOv8
-I'm using MACOS 
-Python 3.8.19
