### ISSUE TITLE
Model parameter issues

### ISSUE THREAD

**Issue by huangqi111** [ultralytics/yolov5#10718]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why yolov5s is used as a pre-trained model, and the model parameters that start training are more than the pre-trained model parameters？

**Comment by glenn-jocher** [comment]
@huangqi111 hi there! When using a pre-trained model like YOLOv5s, the number of parameters for training may differ from the pre-trained model due to the addition of auxiliary layers and reorganization of weights. This is a common practice in transfer learning to adapt the pre-trained model to new data. If you need further details, our documentation at https://docs.ultralytics.com/yolov5/ offers in-depth explanations for model parameters and training. Let us know if you have any other questions, we're here to help!
