### ISSUE TITLE
Exception has occurred: NotImplementedError cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by V4A001** [ultralytics/yolov5#10720]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

After training I wanted to use the last.pt and best.pt. But both throw this 'PosixPath' exception. I tried using the provided models and they do not throw any error. python segment/predict.py --weights best.pt --source testimage.jpg

![image](https://user-images.githubusercontent.com/9630343/211281708-ff24c4a8-83fc-4675-b3c2-f501983e79dc.png)

segment/train.py --device 0 --img 640 --cfg yolov5s-seg.yaml --hyp data/hyps/hyp.scratch-high.yaml --batch 16 --epochs 100 --data my.yaml --weights yolov5s-seg.pt

I am now trying training with yolov5l-seg.yaml to see if this makes a difference. I had working version with https://github.com/WongKinYiu/yolov7, but was not able to create a proper ONNX file. So now doing the same with this library. Previously I used Google Colab, but I believe that does not make the difference.

### Environment

- Windows machine, but trained in Azure ML cloud on T80 Tesla.

### Minimal Reproducible Example

I used segment/train.py --device 0 --img 640 --cfg yolov5s-seg.yaml --hyp data/hyps/hyp.scratch-high.yaml --batch 16 --epochs 100 --data my.yaml --weights yolov5s-seg.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by V4A001** [comment]
This issue does not occur in Google Colab. It is windows and this .pt file related.

**Comment by akashAD98** [comment]
@V4A001 im also facing same, defult yolov5-cls.pt working but custom trained model not working

**Comment by danielsoy** [comment]
me too.
I can predict.py in my local PC, only with a model trained locally.
But got the same error, trying to predict locally, with best.pt or last.pt trained in Colab.
The model trained in colab, predicts fine in colab.

**Comment by glenn-jocher** [comment]
Hey @danielsoy and @arreios, thanks for your reports. This issue might involve the way the file paths are handled in your local environment. You can try using the `Path` from the `pathlib` library to handle file paths in a platform-independent way. You can also check that the file paths you are using are correct and accessible. Let me know if you need further assistance. Remember, the YOLOv5 community is here to help each other out! 🚀

**Comment by Krushu24365** [comment]
yes i am with same error can anyone help with exact steps about how to do this

**Comment by glenn-jocher** [comment]
@Krushu24365 hello everyone, it seems like the issue might be related to the way file paths are handled across different operating systems. Here's a quick step you can try:

1. Ensure that you're using string representations of the file paths when loading the weights. Instead of using a `PosixPath` object, convert it to a string.

For example, if you have:
```python
weights_path = Path('best.pt')
```
Convert it to a string like this:
```python
weights_path = str(Path('best.pt'))
```

Then use `weights_path` as the argument for loading weights.

If you continue to encounter issues, please ensure that your environment is set up correctly and that the file paths are accessible. If the problem persists, providing the exact error message and the code snippet where the error occurs could help us diagnose the issue more effectively. 🛠️
