### ISSUE TITLE
The resulting curve does not coincide

### ISSUE THREAD

**Issue by chaodreaming** [ultralytics/yolov5#10723]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Setting random seed to 0 or 42 will not produce the same result at the same time
![image](https://user-images.githubusercontent.com/49591435/211327715-869e2764-dc5e-4659-902a-a9cbb8669b64.png)
I try to change many parameters, but I can't get the same result. I think this is not normal, so others can't repeat my result

**Comment by glenn-jocher** [comment]
@chaodreaming hi there! Thank you for reaching out. YOLOv5 doesn't include deterministic training functionality yet due to PyTorch’s limited determinism. We're actively working on this, but for now, you can explore the available options in our documentation.

Let me know if there's anything else I can help you with.
