### ISSUE TITLE
--save-conf with "segment/predict.py" doesn't seem to work.

### ISSUE THREAD

**Issue by sarpx** [ultralytics/yolov5#10743]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Below is sample data and I can't see the result values..

python segment/predict.py --source ./g/images/seg_1673248832121 --weights runs/train-seg/faz030123/seg_1673248832121/weights/best.pt --conf 0.10 --device 0 --nosave --save-txt --save-conf --name ./c/faz030123/seg_1673248832121_10

### Minimal Reproducible Example

69 0.309375 0.71875 0.307813 0.720833 0.304688 0.720833 0.304688 0.722917 0.303125 0.725 0.303125 0.7875 0.301562 0.789583 0.301562 0.80625 0.303125 0.808333 0.303125 0.810417 0.304688 0.810417 0.30625 0.8125 0.310937 0.8125 0.3125 0.814583 0.317187 0.814583 0.31875 0.816667 0.325 0.816667 0.326562 0.81875 0.33125 0.81875 0.332812 0.820833 0.340625 0.820833 0.342187 0.822917 0.35 0.822917 0.351562 0.825 0.359375 0.825 0.360938 0.827083 0.371875 0.827083 0.373437 0.829167 0.384375 0.829167 0.385938 0.83125 0.395312 0.83125 0.396875 0.833333 0.409375 0.833333 0.410937 0.835417 0.445312 0.835417 0.446875 0.8375 0.545313 0.8375 0.546875 0.835417 0.565625 0.835417 0.567187 0.833333 0.58125 0.833333 0.582812 0.83125 0.595312 0.83125 0.596875 0.829167 0.603125 0.829167 0.604688 0.827083 0.6125 0.827083 0.614062 0.825 0.626562 0.825 0.628125 0.822917 0.639063 0.822917 0.640625 0.820833 0.64375 0.820833 0.645312 0.81875 0.648438 0.81875 0.65 0.816667 0.651563 0.816667 0.651563 0.8125 0.653125 0.810417 0.653125 0.80833

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
--save-txt and --augment and model ensembling don't work either

**Comment by woniu0126** [comment]
yes, --augment will throw TypeError: 'NoneType' object is not subscriptable, does it occur to anoyone else?

**Comment by glenn-jocher** [comment]
@woniu0126 the error message "TypeError: 'NoneType' object is not subscriptable" typically occurs when trying to subscript or access a value from a variable that is None. This suggests that there may be an issue with the input arguments or data being passed to the script. Please make sure that you are providing valid input arguments and that the data is in the correct format. If the issue persists, please provide more details about your environment and data, and try to reproduce the issue step-by-step so that we can help diagnose the issue.
