### ISSUE TITLE
val.py pycocotools mAP eval is different from the default mAP eval results when using custom datasets?

### ISSUE THREAD

**Issue by SamSamhuns** [ultralytics/yolov5#10747]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to get the mAP small, medium, and large values that are present in the pycocoeval tool for a **custom dataset**. I tried the solution provided in #4535 where I convert my custom YOLO labels to COCO JSON format and change the `anno_json = str(Path('../datasets/coco/annotations/instances_val2017.json'))  # annotations` in `val.py` to my converted coco JSON GT file.

However, I get a decent mAP from the `val.py` test metrics but the same metrics are substantially lower in the pycocotools evaluation. Do we know why this happens? Or is the pycocotools evaluation only useful for the coco dataset and not for custom datasets?

![Screenshot 2023-01-12 at 11 51 15 AM](https://user-images.githubusercontent.com/13418507/212041318-0de332b1-d9de-4a5b-8497-7119ddffbc89.png)

Issues #7658, #8070, and #6110 have similar problems but were not resolved with a working solution.

My GT reference coco JSON file is [visdrone2019-det-test-dev.json.zip](https://github.com/ultralytics/yolov5/files/10400540/visdrone2019-det-test-dev.json.zip) and the predicted JSON file from the `--save-json` parameter from `val.py` is [best_predictions.json.zip](https://github.com/ultralytics/yolov5/files/10400545/best_predictions.json.zip)

**Comment by SamSamhuns** [comment]
Finally solved after days, the solution from #4535 has a huge issue where converting the annotation format from YOLO to COCO had created some problems. The first thing is the image_id must be set to match the image_id created from the Yolo val.py and the second most important thing, the yolo2coco converter in #4535 was starting my class indexes with 1 but the JSON generated by the `--save-json` from val.py indexes classes from 0, so the problem was in the converted COCO annotation

**Comment by Hezey** [comment]
> 
Hello, I have the same problem. Could you please share the code of yolo_to_coco with me? Thank you

**Comment by SamSamhuns** [comment]
https://github.com/Taeyoung96/Yolo-to-COCO-format-converter

You can use this but change the image_id to match that generated from val.py and set the category_id to start from 0 instead of 1.

**Comment by Hezey** [comment]
Ok, I'll have a try, thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] val.py pycocotools mAP eval is different from the default mAP eval results when using custom datasets? (Issue #10747)





 
https://github.com/Taeyoung96/Yolo-to-COCO-format-converter
 
You can use this but change the image_id to match that generated from val.py and set the category_id to start from 0 instead of 1.

**Comment by SamSamhuns** [comment]
I've made changes to that repo to make it easier to use for yolov5 based conversion which you can also find here https://github.com/SamSamhuns/ml_data_processing/tree/master/annotation_format_conv

**Comment by MatoFD** [comment]
Thanks! I had also read all the issues on the repository about evaluating pycocotools with a custom dataset and was stuck for a couple of days. In the end the key was that the class indexes were starting with 1 instead of 0, like @SamSamhuns said. 
So if anyone else is having this problem, please confirm that the labels in the results file and annotations file are the same.

**Comment by Hezey** [comment]
Yeah,I regenerated the annotation file, it is indeed the problem, thank you for your joint efforts

**Comment by glenn-jocher** [comment]
@Hezey you're welcome! It's great to hear that you were able to resolve the issue. If you have any other questions or need further assistance, feel free to ask. The YOLO community is full of helpful individuals who can provide valuable insights. Good luck with your further developments!
