### ISSUE TITLE
Inference speed and FPS

### ISSUE THREAD

**Issue by Zzh-tju** [ultralytics/yolov5#10760]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Device: single RTX 3090
```python

python val.py --data coco.yaml --img 640 --weight yolov5s.pt --task speed --batch 1
val: data=/home/ubuntu/yolov5/data/coco.yaml, weights=['yolov5s.pt'], batch_size=1, imgsz=640, conf_thres=0.001, iou_thres=0.6, max_det=300, task=speed, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 v7.0-61-gcaba2ae Python-3.8.13 torch-1.12.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3090, 24265MiB)

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
val: Scanning /home/ubuntu/data/coco/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 5000/5000 [00:37<00:00, 133.55it/s]
                   all       5000      36335      0.641      0.533      0.615       0.44
Speed: 0.1ms pre-process, 2.7ms inference, 0.3ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/val/exp
```

The inference time is 0.1+2.7+0.3=3.1ms, right? So, FPS=1000/3.1=322.6, right?

But it takes 37 seconds to run over the 5k images. And FPS=5000/37=135.1, right?

Which result should I trust?

**Comment by BraunGe** [comment]
same question. have you solved it?

**Comment by siddagra** [comment]
The model has a lot of pre and post processing plus calculating the metrics.
Sadly you cannot increase batch size to increase throughput for predictions either it seems. Going back to yolov7

**Comment by glenn-jocher** [comment]
@siddagra both of your calculations are accurate. The inference time is 3.1ms per image, which corresponds to a theoretical FPS of 322.6. On the other hand, the benchmark over 5000 images resulted in an actual FPS of approximately 135.1. 

However, it's important to consider that the discrepancy between theoretical and actual FPS is likely due to additional processing steps such as pre-processing, post-processing, and metric calculation. The actual FPS over a larger dataset would be more indicative of real-world performance.

Increasing batch size may not necessarily increase throughput for predictions due to the way YOLOv5 performs inference. Feel free to benchmark YOLOv7 and let us know if you have further questions.
