### ISSUE TITLE
Why is the linear learning rate not lr0 * lrf at the end of training?

### ISSUE THREAD

**Issue by daigang896** [ultralytics/yolov5#10785]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Why is the linear learning rate not lr0 * lrf at the end of training? It doesn't match the actual description. I wonder if anyone else has encountered this problem? The code version used is yolov5 6.2. I can't find the cause of this problem by looking at the code.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@daigang896 thank you for bringing this to our attention! YOLOv5's linear learning rate not being exactly lr0 * lrf at the end of training is intentional. The lr0 * lrf at the last iteration might not be strictly enforced due to the specific learning rate scheduler used. If you'd like more details, feel free to refer to the official Ultralytics Docs: https://docs.ultralytics.com/yolov5/. 

We truly appreciate your engagement and support! If you have any further inquiries or need assistance, feel free to ask.
