### ISSUE TITLE
WARNING  Environment does not support cv2.imshow() or PIL Image.show()

### ISSUE THREAD

**Issue by alesvaz** [ultralytics/yolov5#10791]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello,

since a week I have been unable to use yolov5 for real-time recognition with the webcam as stream source (when using saved images or videos, it displays no issues). 

![image](https://user-images.githubusercontent.com/108015100/213134090-20ee7a66-6e1f-4b71-beb3-3803fe5d8f6a.png)

I have tried to re-install requirements, to update libraries, to copy the repository again from git as I saw in another issue, but nothing has worked so far (I am running the detection from Anaconda Prompt). Any help would be greatly appreciated.

Thank you.

### Environment

- Yolov5
- Windows 10
- Python 3.9.12, Anaconda

### Minimal Reproducible Example

C:\yolov5>python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source 0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@alesvaz hi there,

It looks like the issue you're encountering may be due to an environment that doesn't support displaying images with `cv2.imshow()` or `PIL Image.show()` when using real-time recognition with the webcam. This typically occurs on certain platforms, including Windows 10.

While we can't provide a direct fix for this, an alternative approach could be to save the real-time stream to a video file using the `--save-txt` argument with `detect.py`. Then, you can view the results using a video player.

For more tips, please check the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/), and feel free to join the YOLOv5 Discord community to get further assistance.

Thank you for using YOLOv5, and good luck with your real-time recognition project!
