### ISSUE TITLE
Ultralytics HUB Android App doesn't export the Model

### ISSUE THREAD

**Issue by seimonb** [ultralytics/yolov5#10823]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

Ultralytics HUB Android App doesn't export the Model.

After exporting the (self trained) Model (with custom data in roboflow) from the Ultralytics HUB Website. 
Have a look at Screenshot1

The new Project and Model is visible in the Ultralytics HUB Android App.
Have a look at Screenshot2 and Screenshot3

But the Project is not loading/exporting to use and try out with the App on the phone.
Have a look at Screenshot3 and Screenshot4

Do you habe any sugestions?
Thank you for your help!

Screenshots:
![Screenshot1](https://user-images.githubusercontent.com/123466327/214297012-4af8673a-bae4-4fc7-b112-48a4520cc31e.JPG)

![Screenshot2](https://user-images.githubusercontent.com/123466327/214297020-3734f713-8214-41f5-aa06-62e973b2e3e6.jpg)

![Screenshot3](https://user-images.githubusercontent.com/123466327/214297059-f6838a0a-aefe-477a-8d2d-5801805c987f.jpg)

![Screenshot4](https://user-images.githubusercontent.com/123466327/214297110-0e9671c4-8459-4089-aebd-0bc3db3dc928.jpg)

### Environment

- New version of the app: Ultralytics HUB Android App 
- Working on the Website: Ultralytics HUB and Roboflow
- PC: Windows 10
- Android Phone: Samsung Galaxy S21 FE

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@seimonb hi there! 👋 Thanks for reaching out. It looks like you're encountering an issue with the Ultralytics HUB Android App not exporting the model properly. I appreciate you including the screenshots, they really help in understanding the problem.

When you export the model from the Ultralytics HUB website, it appears in the Android app, but it's not loading/exporting for use. In order to investigate this further, could you provide some additional details about the specific steps you've taken and any error messages (if any) you're encountering?

We'll do our best to help you with this. Thanks for your patience!
