### ISSUE TITLE
How to add 80, 81 class to COCO dataset

### ISSUE THREAD

**Issue by L1gHtFox** [ultralytics/yolov5#10832]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

As I understood weights for training are pretrained on COCO dataset. I want to save these ability t o detect pretrained classes and add 2 more.

I added to coco128 2 more classes and puted images for train and test to directories.
So here is my images:
![labels](https://user-images.githubusercontent.com/44618739/214595689-a623134d-ee66-4937-8900-51141f214dfd.jpg)

But after training model can detect only classes that I added. It seems like model trained only on images that I it got in dataset and previous progress not saved.

Sorry for stupied questions :D

**Comment by bit-scientist** [comment]
Did you train tour new images along with `coco128` dataset when you put your new class dataset? <br>The rule is : if you want to add more classes to the original 80, new class ids should be `80`, `81` (`0` to `79` are for existing 80 classes) and add new image paths. However, if you don't have `coco128` dataset, you'd better download it. Also, as the image shows, you have a dataset imbalance, you could consider training bigger `coco` (not `coco128`) dataset to remedy this.

**Comment by glenn-jocher** [comment]
@bit-scientist thanks for reaching out! When adding new classes, ensure that the new class IDs are `80` and `81` (as IDs `0` to `79` are reserved for the existing 80 classes). Also, make sure to include your new image paths, and consider balancing your dataset by using the larger `coco` dataset instead of `coco128`. This should improve the detection ability of the model for your new classes. Good luck!
