### ISSUE TITLE
Allow overlapping bounding boxes.

### ISSUE THREAD

**Issue by YeetMasterYeet** [ultralytics/yolov5#10870]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, currently working with YOLOV5, i am in a case where i have multiple objects from the same class to be detected in images.
In some cases where my objects (from the same class) are overlapping, instead of having two different bounding boxes, i have one bounding box that englobes my two objects or even three in some cases, even though i have trained my model with a dataset that has those cases taken into consideration.
is there any hyperparameter that i can modify in order to allow overlapping boxes for the same class or i have to retrain a new model where i take into consideration overlapping objects as a completely new class ?
Thanks!

**Comment by glenn-jocher** [comment]
@YeetMasterYeet hi there! YOLOv5 currently doesn't support overlapping bounding boxes for the same class by design. This behavior is controlled by the model architecture and existing hyperparameters, and retraining with a new class for overlapping objects would be the recommended approach. Remember, you can find detailed documentation on YOLOv5 at https://docs.ultralytics.com/yolov5/. Good luck with your project!
