### ISSUE TITLE
Do the training images need to be all 640x480?

### ISSUE THREAD

**Issue by smalik89** [ultralytics/yolov5#10875]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! Quick question: Do the training images all need to be 640x480 for a --img 640 input argument? How about for the testing images?

**Comment by smalik89** [comment]
Yes I did look through the tutorials but cannot find a holistic answer. Do the training & testing images need to be 640x480 to successfully train the YOLOV5 model?

**Comment by JustasBart** [comment]
Hi @smalik89 the input images can be of any size when training/inferencing a yolov5 model. The data will be automatically scaled during training and automatically scaled during inference.

Good luck! :rocket:

**Comment by smalik89** [comment]
Thank you so much for your response @JustasBart !! So should I not put the argument of --640 during training/testing? (If images are different sizes)

**Comment by JustasBart** [comment]
@smalik89 This is my training shell script:

```
python3 train.py \
--data /home/.../10_Class_dataset/10Class.yaml \
--hyp data/hyps/hyp.scratch-custom.yaml \
--weights yolov5s6.pt \
--img 1280 \
--batch -1 \
--epochs 600 \
--device 0
```

As you can see you do need a **--img** in order to determine the size of your **model** but your training images that it'll use for training will be automatically scaled to 640x640 and when you're running inference you'll also have to pass in **--img 640** because on a .pt model you can actually train it on one resolution and attempt to inference on a different resolution, so just specify that, and be aware that 640x640 are the defaults so if you don't use **--img** on your training/inference it'll default to that.

But then likewise you can run inference on any size images and it'll automatically scale them to 640x640 (Or whatever you specify). Also be aware that if you want to export as say .onnx then the Network output size will be fixed (Unless you export as dynamic).

Good luck! :rocket:
