### ISSUE TITLE
Segmentation result only have two points

### ISSUE THREAD

**Issue by nanfei666** [ultralytics/yolov5#10888]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

i found that when infer, the segmentation model sometimes may give a segmentation result with only two points, which i think is wrong since two points can't form a mask.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nanfei666 hi there, thanks for reaching out. This issue seems related to the segmentation model's output, which at times may provide segmentation results with only two points. We appreciate you bringing this to our attention and will investigate further. If you have a minimal reproducible example or additional details, feel free to share them here. Your input is valuable to the YOLO community!
