### ISSUE TITLE
Why FLOPs is different in Readme.md?

### ISSUE THREAD

**Issue by wenjunx** [ultralytics/yolov5#10898]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I train the yolov5-s model, the training info display FLOPs 15.9G. Why is not 16.5G in readme.md?

**Comment by glenn-jocher** [comment]
@wenjunx the FLOPs (floating point operations) in the YOLOv5 readme.md are an estimation for the yolov5m model, and actual FLOPs may vary during training and inference. The discrepancy is likely due to differences in your specific training process and hardware optimizations. If you'd like to dive deeper into understanding FLOPs and model performance, I recommend checking out the Ultralytics Docs for YOLOv5. Keep up the great work!
