### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

### ISSUE THREAD

**Issue by Kcud** [ultralytics/yolov5#10904]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used to be able to use yolov5 for identification normally, but it started to appear urllib.error.URLError: <urlopen error [WinError 10061] > on February 3, 2023
![20230204231448](https://user-images.githubusercontent.com/53012617/216775004-f493c0a8-82d6-4dbf-b20a-4e45826e62d5.jpg)

### Additional

```
import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
imgs = ['https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/zidane.jpg']
results = model(imgs)
print(results)
```

**Comment by glenn-jocher** [comment]
@Kcud hi there! It looks like you are encountering a URLError when using YOLOv5 for identification. The error code `[WinError 10061]` typically indicates a connection issue. This could be due to network problems or firewall settings on your machine.

As of now, there are no widespread reports of similar issues with YOLOv5. However, I recommend checking your network settings, ensuring that the URLs you are using are accessible, and verifying that your firewall settings are not blocking the connection.

If the issue persists, feel free to provide more details, and we'll do our best to assist you further. You can also refer to the YOLOv5 documentation for more information on how to troubleshoot and resolve common issues: https://docs.ultralytics.com/yolov5/

Thanks for reaching out, and I hope this helps!

**Comment by Kcud** [comment]
Thank you for your reply, I have solved it




accelerator
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。&gt; (Issue #10904)





 
@Kcud hi there! It looks like you are encountering a URLError when using YOLOv5 for identification. The error code [WinError 10061] typically indicates a connection issue. This could be due to network problems or firewall settings on your machine.
 
As of now, there are no widespread reports of similar issues with YOLOv5. However, I recommend checking your network settings, ensuring that the URLs you are using are accessible, and verifying that your firewall settings are not blocking the connection.
 
If the issue persists, feel free to provide more details, and we'll do our best to assist you further. You can also refer to the YOLOv5 documentation for more information on how to troubleshoot and resolve common issues: https://docs.ultralytics.com/yolov5/
 
Thanks for reaching out, and I hope this helps!

**Comment by glenn-jocher** [comment]
You're welcome, @Kcud! I'm glad to hear that you were able to solve the issue. If you have any more questions or encounter any other challenges, don't hesitate to reach out. The YOLOv5 community and the Ultralytics team are here to help. Good luck with your future YOLOv5 projects and happy coding!
