### ISSUE TITLE
 While Running application using yolov5 during sast checkmarx scan it gives high severity warning.

### ISSUE THREAD

**Issue by akashlinux10may** [ultralytics/yolov5#10907]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

While deploying the application in real time production using yolov5 custom model, in checkmarx scan I got the high severity warning for following files.

yolov5\models\experimental.py (line 88)
Warning: Attacker can inject and run arbitrary code

yolov5\hubconf.py (line 143)
Warning: Attacker can inject the code via user input.

Impact: Could not able to run the model in secure environment.

Please suggest the resolution.

Is there any way we can load the yolov5 model without Yolov5 folder

I tried this but Following code is not working
model = torch.hub.load('.', 'custom', source ='local', path='last.pt',force_reload=True)

Please suggest alternative for following:

model = torch.hub.load('yolov5', 'custom', source ='local', path='last.pt',force_reload=True)

**Comment by glenn-jocher** [comment]
@akashlinux10may hi there!

Thanks for reaching out. It sounds like your concern is related to security warnings during a checkmarx scan. To clarify, YOLOv5 does not contain user input or code injection vulnerabilities by design. The warnings you're seeing may be false positives.

In regards to your attempt to load the custom model without the `yolov5` folder, you're on the right track. You can load a local custom model with:

```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/your/model.pt', source='local', force_reload=True)
```

This should enable you to effectively load your custom model without needing to reference the `yolov5` folder directly.

If you encounter any further issues, feel free to refer to our documentation at https://docs.ultralytics.com/yolov5/ for additional guidance.

Let me know if you need any more help with this!
