### ISSUE TITLE
WANDB sweep.py saves mostly last.pt instead of best.pt

### ISSUE THREAD

**Issue by wasif-manto** [ultralytics/yolov5#10968]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I'm facing an issue while using the sweep.py. After running the sweep most of the time the model that is saved (loacally and on WANDB) is last.pt instead of best.pt.  If there are 20 runs in the sweep then only one run has both last.pt and best.pt saved and the rest has only last.pt saved. Does anyone else has the same issue who used the sweep.py ? or any suggestions on what could be wrong?
Thanks.

**Comment by wasif-manto** [comment]
I just noticed here  https://github.com/ultralytics/yolov5/pull/10902 that sweep functionality is probably removed. Any explanation why is it removed ?

**Comment by Alberto1404** [comment]
> I just noticed here #10902 that sweep functionality is probably removed. Any explanation why is it removed ?

Same question here @glenn-jocher

**Comment by glenn-jocher** [comment]
@Alberto1404 the removal of sweep functionality on YOLOv5 was intended and due to WandB's decision to end sweep in favor of their newer and more powerful tool: **Sweeps**. To achieve similar functionality, please consider migrating to the new Sweeps tool. If you need assistance with transitioning to Sweeps, please refer to the Ultralytics Docs for guidance. Thank you for your understanding and your support.
