### ISSUE TITLE
Illegal Instruction (Core dumped) Jetson Nano

### ISSUE THREAD

**Issue by aryanbarik** [ultralytics/yolov5#10981]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

On the Jetson, I have yolov5 installed. It's able to run the example DeepStream Configuration for YOLOv5 shown in the NVIDIA Jetson tutorial. However, when I run `python3 detect.py --weights yolov5s.pt --source 0` with my webcam plugged in I receive the message `Illegal instruction (core dumped`

Can anyone help me out?

**Comment by aryanbarik** [comment]
Seemed to work with
`sudo apt-get install -y python-numpy python3-numpy`
and then `sudo apt update && sudo apt upgrade`

Now we are getting a different error saying we are missing opencv

**Comment by Denizzje** [comment]
Did you run pip install -r requirements.txt in the yolov5 folder? That should install all the dependencies required such as OpenCV. Though I believe the Nano's python version (from Ubuntu 18.04 default) is no longer supported so you need to check if you are on 3.7 or above.

**Comment by aryanbarik** [comment]
I am on Python 3.6.9. How do I upgrade it to Python 3.7?

**Comment by aqibriaz95** [comment]
The 'illegal instruction' could be due to an change in the getauxval(AT_HWCAP).

An attempt to read cpuid information from /sys/devices in the event that getauxval did not succeed. (OpenBLAS PRs 2952 and 3004)

export OPENBLAS_CORETYPE=ARMV8 (or whatever the actual hardware is) before launching python should hopefully get around this. For example:

`OPENBLAS_CORETYPE=ARMV8 python`

If you would like to make this export permanent, you should open your .bashrc file by typing on the terminal:

nano ~/.bashrc

Afterwards, just add "export OPENBLAS_CORETYPE=ARMV8" to the bottom of your .bashrc file, save/exit and reboot your system:

`export OPENBLAS_CORETYPE=ARMV8`

for more details look at:

[https://github.com/numpy/numpy/issues/18131 https://www.reddit.com/r/JetsonNano/comments/ktcyoh/illegal_instructioncore_dumped_error_on_jetson/]

**Comment by glenn-jocher** [comment]
@aqibriaz95 thanks for sharing this valuable information! Your explanation of the 'illegal instruction' issue and providing the solution for setting the OPENBLAS_CORETYPE to ARMV8 will certainly help others facing a similar problem on the Jetson Nano. Your contribution to the community is greatly appreciated! If you encounter any further issues or need assistance with anything else, feel free to ask! 👍

**Comment by dariogonle** [comment]
@glenn-jocher I have the same problem and this hasn't fixed it.

**Comment by glenn-jocher** [comment]
@dariogonle thanks for reaching out! It's possible that the issue might have a different root cause, and I'd like to assist you in resolving it. To help us narrow down the problem, could you please provide more details about your specific setup? Additionally, you can visit the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ for additional troubleshooting tips and configuration options.

**Comment by 808947** [comment]
Hi i have faced same trouble while trying do custom data training with yolov5 in jetson nano. But while running the code python3 train.py  it show a error message [ illegal instruction (core dumped) ] how can i solve this? Please any help is appreciated. 

Thanks in advance

Simon Jain Luiz

![17018924700171482020226893351283](https://github.com/ultralytics/yolov5/assets/151402502/86bbdc67-2dff-4068-8422-7c8ceff0ce50)

**Comment by 808947** [comment]
Illegal instruction ( core dumped ) on jetson nano.

**Comment by glenn-jocher** [comment]
@808947 hi Simon, I appreciate your interest in using YOLOv5 on the Jetson Nano! The "illegal instruction (core dumped)" issue can be related to several factors such as CPU architecture compatibility and software dependencies. Have you had a chance to ensure that your Jetson Nano's Python version, dependencies, and OpenBLAS settings are all correctly configured as per the recommendations in the previous responses? Taking these steps might resolve the issue. If you need further assistance, feel free to reach out, and we'll work on finding a solution together. Wishing you success in your custom data training with YOLOv5!

**Comment by 808947** [comment]
Hi thank you for your response...
When i try to run it in the directory without using any virtual environment
it's shows another error as " ultralytics is missing " but i have followed
the steps carefully. If i try to run it in virtual environment the error "
illegal instruction (core dumped) occur". I checked the version of python
it shows python 3.8, do you think that's the problem?
Can you guide me do it properly with correct steps. I am using jetpack
version 4.6

**Comment by glenn-jocher** [comment]
@808947 It seems that the "ultralytics is missing" error might be related to the YOLOv5 installation within the specific environment. You can try reinstalling YOLOv5 within your virtual environment using the command `pip install -U -r requirements.txt`. This will ensure that all the necessary dependencies, including 'ultralytics', are installed. Regarding the "illegal instruction (core dumped)" error in the virtual environment, it's possible that this could be due to compatibility issues. 

Python 3.8 should not cause an "illegal instruction" error as long as it is supported for your Jetson Nano's architecture. Make sure to follow the installation steps for YOLOv5 within the virtual environment mentioned in the YOLOv5 documentation. If you encounter any further issues, please feel free to let me know, and we can work through it together. Good luck and looking forward to your success with YOLOv5!

**Comment by rsemihkoca** [comment]
i think you should get rid of this ai bot. It did not help to resolve issues any way.

**Comment by glenn-jocher** [comment]
Thank you for your feedback. If you have specific issues or questions, please provide details, and I'll do my best to assist you.
