### ISSUE TITLE
Custom Model on Ultralytics App

### ISSUE THREAD

**Issue by michalkrawczyk** [ultralytics/yolov5#11004]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How can I deploy already trained custom model yolov5 on ultralytics hub?
Also is it possible to have it not public?

**Comment by glenn-jocher** [comment]
@michalkrawczyk you can train and deploy any custom model you want with HUB to iOS and Android, nothing is public unless you want to make it public.

**Comment by michalkrawczyk** [comment]
@glenn-jocher Thanks for response. I've already have trained model on my computer, but I wanted to test it with app. I haven't found how to upload it and that's the main problem.

**Comment by glenn-jocher** [comment]
@michalkrawczyk you can deploy your trained model to the Ultralytics app by following the documentation at https://docs.ultralytics.com/yolov5/. Look for the "Deploying Custom Models" section.

**Comment by cezbloch** [comment]
Hi, I followed the instructions for your hub at https://docs.ultralytics.com/hub/models/#preview-model .
I have trained models but they don't show up in the app. The models show at the hub.
In the app I go to Projects->Private, and I see my project with a description near project name saying there are 4 models (which is true - just 2 models are finished training). However when I click on the project in the app I get "Models:0". My model is here:
https://hub.ultralytics.com/models/9nraZYaKXcZunSi6rZt6?tab=preview
How to make my models appear in the app? I would like to test it live in the app. Thanks

**Comment by glenn-jocher** [comment]
Hello @cezbloch, I'm sorry to hear you're experiencing issues with the app. It sounds like you've done everything correctly by training your models and they are visible on the hub. If they are not appearing in the app under your private projects, this could be a synchronization issue or a bug.

Please ensure that you are logged into the app with the same account used on the hub. If everything seems in order and the issue persists, I would recommend you to clear the app's cache or try reinstalling the app to ensure it's not a local issue.

If the problem is still not resolved, please open an issue on the YOLOv5 repository with detailed information about the steps you've taken, any error messages you've encountered, and the behavior of the app. This will help us to diagnose the problem more effectively and provide you with a solution.

Thank you for your patience and for using YOLOv5! 🚀
