### ISSUE TITLE
xception in thread

### ISSUE THREAD

**Issue by WUPENGDENG** [ultralytics/yolov5#11011]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

Hi, When I validate the trained model, the validation cannot be conducted as follows
![image](https://user-images.githubusercontent.com/89204648/219805439-2ea47c11-8078-4082-888a-bf9725248627.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WUPENGDENG hi there! Thank you for reaching out. The error you're encountering during model validation could be due to various reasons such as incorrect data paths, data format, or model configuration. Please ensure that your data paths are correctly specified and that the validations set format matches that of the training set.

For more detailed guidance on how to troubleshoot this issue, I recommend checking out our documentation at https://docs.ultralytics.com/yolov5/. 

Your willingness to submit a pull request is appreciated! We welcome contributions from the community. If you identify the cause of the issue and are able to address it, please feel free to submit a PR. 

Let us know if you need further assistance, and thank you for your support!
