### ISSUE TITLE
when i run python detect.py --source 0,it didn't work.

### ISSUE THREAD

**Issue by shizishen** [ultralytics/yolov5#11020]
![image](https://user-images.githubusercontent.com/85082613/219989672-5a2dc61a-78ec-42e3-aebc-a8be4b96e0d8.png)
It's been stuck here

**Comment by smalik89** [comment]
Hi @shizishen ! I had posted a similar question [https://github.com/ultralytics/yolov5/issues/10978](https://github.com/ultralytics/yolov5/issues/10978). The issue is that the model is currently being run on cloud instead of locally. Therefore need to download the model. Subscribe the post so hopefully we can get an answer.
