### ISSUE TITLE
Are --image-weights and DDP training still incompatible?

### ISSUE THREAD

**Issue by shenck0** [ultralytics/yolov5#11037]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

In train.py, I found that the assert is made here:
```Python
    if LOCAL_RANK != -1:
        msg = 'is not compatible with YOLOv5 Multi-GPU DDP training'
        assert not opt.image_weights, f'--image-weights {msg}'      # <----- this assert
        assert not opt.evolve, f'--evolve {msg}'
```
This assert was added by https://github.com/ultralytics/yolov5/pull/3275 , and according to https://github.com/ultralytics/yolov5/pull/4579, --image-weights can be use with DDP training.
I comment out this assert line and found dataset.indices modified at every epoch beginning can be broadcast to other processes correctly.
Are --image-weights and DDP training still incompatible now?

**Comment by ztyree42** [comment]
Bumping because the question was not answered. It appears that DDP and --image-weights run fine together but is there still some sort of foot-gun present in their interaction and if so what is it?

**Comment by glenn-jocher** [comment]
@shenck0, I apologize for the confusion. You are correct, based on this [PR](https://github.com/ultralytics/yolov5/pull/4579) as and as of the current implementation, there are no known issues or incompatibilities with using DDP and `--image-weights` together. Previously, the assert checked that `--image-weights` were not present when using DDP in older implementation, but it has since been updated.

Thank you for bringing this to our attention and please let me know if you have any further questions or concerns.
