### ISSUE TITLE
wh = wh0[(wh0 >= 2.0).any(1)].astype(np.float32)  # filter > 2 pixels

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/yolov5#11043]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, glenn-jocher:

i have a question about :
https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py#:~:text=wh%20%3D%20wh0%5B(wh0%20%3E%3D%202.0).any(1)%5D.astype(np.float32)%20%20%23%20filter%20%3E%202%20pixels

at row:126, the code "**wh = wh0[(wh0 >= 2.0).any(1)].astype(np.float32)  # filter > 2 pixels**"  means to use pixel big than 2 gt box and not use < 2 pixel gt box，but when some extream situaltion, the gt [width, height] = [1, 3] then will not filter, so could use np.all() ?

**Comment by glenn-jocher** [comment]
@HonestyBrave hi there! Thanks for reaching out. The line of code you mentioned filters bounding boxes with both width and height greater than 2 pixels. If you're looking to filter out bounding boxes with either width or height less than 2 pixels, you can indeed use `np.all()` instead of `np.any()`. Feel free to give it a try and let us know if you encounter any issues. We're here to help!
