### ISSUE TITLE
Exported coreml don't have "Class Labels"

### ISSUE THREAD

**Issue by waheed0332** [ultralytics/yolov5#1104]
This is the conversion I did for SSD MobileNet
<img width="1102" alt="old" src="https://user-images.githubusercontent.com/6158735/95551583-7b613280-0a24-11eb-9a60-1b4d99c3950a.png">
This has class labels in it.

How do I add class labels for yolo?
<img width="1102" alt="new" src="https://user-images.githubusercontent.com/6158735/95551564-743a2480-0a24-11eb-926c-9d4ec3f0e83a.png">

**Comment by ALMerrill** [comment]
Check out step four [at this link](https://coremltools.readme.io/docs/pytorch-conversion). You can add class labels from a file as you serialize the model

**Comment by zetstream33** [comment]
Did you solve it? Same Problem here.

**Comment by glenn-jocher** [comment]
@zetstream33 hi there! 

Can you please clarify what problem you are experiencing with YOLOv5? I would be happy to help you troubleshoot any issues you are encountering. Please provide as much information as possible, such as error messages and steps to reproduce the problem, to help me understand the root cause of the issue. 

Looking forward to hearing back from you!

**Comment by zetstream33** [comment]
@glenn-jocher 
Hello. Thank you for replying. I'm having same problem when i export yolov5 pt model to coreml. I trained with custom dataset and used export.py to convert my model to coreml. I tried "python export.py --weight my_weight.pt --include coreml" but the result file(.mlmodel) doesn't have "Class Labels". How could i fix it? Thanks 
<img width="1512" alt="스크린샷 2023-05-04 오후 1 13 58" src="https://user-images.githubusercontent.com/11455035/236111218-136974ce-34e0-44ea-9b41-9a30f31dc1ae.png">

**Comment by glenn-jocher** [comment]
Hello @zetstream33, 

Thank you for reaching out regarding your issue with exporting a custom model from YOLOv5 to CoreML format. 

To add class labels when exporting to CoreML format, you can use the `--classes` flag when running the `export.py` script. For example: 

```
python export.py --weights my_weight.pt --include coreml --classes class_names.txt
```

Where `class_names.txt` is a text file that contains a list of class names, one on each line. 

Please ensure that the class names in `class_names.txt` are in the same order as the classes in your YOLOv5 model. 

I hope this helps! Let me know if you have any other questions or problems.

**Comment by zetstream33** [comment]
@glenn-jocher 
Thank you so much! I solved the problem with this method. Appreciate it!

**Comment by glenn-jocher** [comment]
@zetstream33 you're very welcome! I'm glad to hear that the solution I provided was helpful in resolving your issue. Don't hesitate to reach out again if you have any further questions or problems with YOLOv5. Happy coding!

**Comment by zetstream33** [comment]
@glenn-jocher 
Hello, I'm sorry to say this but it seems export.py dosen't have --classes attribute. I thought i've solved problem without typing --classes flag. Sorry for this. May i ask you to how can i solve this problem?

![image](https://user-images.githubusercontent.com/11455035/236445734-e9a18bdc-a5b8-4a8b-a86b-b9ed1e23c8e1.png)

**Comment by glenn-jocher** [comment]
@zetstream33 hello, 

Thank you for bringing this to our attention. You are correct that `export.py` in the current version of YOLOv5 does not have the `--classes` attribute. I apologize for any confusion that I may have caused by suggesting its usage. 

In order to include class labels when exporting to CoreML format, currently you will need to perform the following extra steps: 

1. Edit the `coreml.py` script in the `models/experimental` folder of the YOLOv5 repository to include your class labels and their associated indices. 
2. Run your edited `coreml.py` script directly, passing in your trained weight file and the desired output CoreML model file name as command line arguments. 

These steps are somewhat cumbersome, but I hope this helps you achieve your desired functionality in the meantime. We appreciate your patience and understanding as we work to improve the YOLOv5 repository. 

Please let me know if you have any further questions or concerns, and I will do my best to assist you. 

Thank you, 
Glenn Jocher

**Comment by annlima** [comment]
@glenn-jocher I don't find the coreml.py script in the models/experimental folder. Is the experimental.py?

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/4bdacedd-9f7c-4214-ae4a-10036cc93a4f" />
