### ISSUE TITLE
Models have different class counts: [1, 1, 2]

### ISSUE THREAD

**Issue by zyy-1103** [ultralytics/yolov5#11058]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

emm....i found a bug when i try Ensemble Inference

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zyy-1103 hey there! Thanks for reaching out. The varying class counts in the models are normal behavior due to different datasets and training methodologies. Regarding the bug you found during Ensemble Inference, could you please provide a bit more detail or a reproducible example for us to explore further? Your help in clarifying this matter is much appreciated. 😊

If you haven't already, you can find helpful information in the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/). Thanks again for your support!
