### ISSUE TITLE
Unable to use results.save() from PyTorch Hub

### ISSUE THREAD

**Issue by xuyiwei0812** [ultralytics/yolov5#11055]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

When using results.save(), error is :'list' object has no attribute 'save'
Same with results.xyxy[0] , error is :'list' object has no attribute 'xyxy'

### Environment
yolov5 7.0, PyCharm

### Minimal Reproducible Example

my code:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

IMAGENET_MEAN = 0.485, 0.456, 0.406
IMAGENET_STD = 0.229, 0.224, 0.225

def classify_transforms(size=224):
    return T.Compose([T.ToTensor(), T.Resize(size), T.CenterCrop(size), T.Normalize(IMAGENET_MEAN, IMAGENET_STD)])

image = "aaa1.jpg"
image = Image.open(image)

transformations = classify_transforms()
convert_tensor = transformations(image)
convert_tensor = convert_tensor.unsqueeze(0)
#print(convert_tensor.shape)

results = model(convert_tensor)
print(results)
print(results.xyxy[0])

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xuyiwei0812 hi there! It looks like you're trying to save results obtained from the YOLOv5 model loaded through PyTorch Hub. The issue you're encountering is due to the fact that `results` is a list, and not an object with a `save` attribute. To save the results, you can iterate through the list and save each item individually, or save the whole list using Python's built-in serialization methods, like `pickle`.

Regarding the error `'list' object has no attribute 'xyxy'`, it seems like `results` might be a list of predictions, hence accessing `xyxy` on `results[0]` should work.

I hope this helps! If you have any further questions, please feel free to ask. Also, for more detailed guidance, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/.

Keep up the great work!
