### ISSUE TITLE
small object val metric

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#11073]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Does yolov5 can get the small object mAP?

![image](https://user-images.githubusercontent.com/59388989/221413004-1e990a1c-eff8-4186-8c22-ea8fc01c2816.png)

**Comment by alicera** [comment]
issue

**Comment by glenn-jocher** [comment]
@alicera hi there,

Thank you for your question. YOLOv5 does support small object detection and we have tested it on various datasets. However, it's worth noting that small objects can often be quite challenging to detect accurately and this can significantly impact the model's performance. We recommend carefully selecting the appropriate dataset and fine-tuning the model's parameters in order to achieve the best possible results.

If you have any other questions or concerns, please don't hesitate to let us know. We're always here to help!

Best, 
[Ultralytics Team Member Name]
