### ISSUE TITLE
YOLOV5N EXPORT TO ONX FORMAT

### ISSUE THREAD

**Issue by Psigedar** [ultralytics/yolov5#11105]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I know if the file is converted correctly fro .pt to onx? When I run detect.py on colab I get good resulst howver when i convert it into onx and then use it in opencv I am facing issues.

**Comment by glenn-jocher** [comment]
@Psigedar hi there! 👋 To verify if your .pt file is correctly converted to ONNX format, you can use the `onnxsim` package to simplify and optimize the ONNX model. You can install it via pip and then run `onnxsim` on your converted file to ensure it's properly formatted for use with OpenCV. If you continue to face issues, please provide more details about the problems you're encountering so that we can assist you further. Good luck!
