### ISSUE TITLE
custom yolov5: detect.py with source video mp4 shows 2 Bounding Boxes overlapping from 2 models 

### ISSUE THREAD

**Issue by RoBoFAU** [ultralytics/yolov5#11112]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I trained my yolov5s model with custom data (3 classes: bottle, chair, book)
If I try detect.py with an image, everything works perfectly fine.
python3 detect.py --weights runs/train/exp9/weights/best.pt --img 640 --conf 0.4 --exampleimage.jpg

But now I want to try the model on a video.
python3 detect.py --weights runs/train/exp9/weights/best.pt --img 640 --conf 0.4 --source test_video.mp4

I don't know why, but there are 2 bounding boxes from different models.

**I just want to see the thinner one with chair!**
**I don't know why there is an other model!**

The thicker one is based on coco.yaml dataset configuration (I know this because in the first run, the class 1 from the thicker model was 'bicycle' and from my model it was 'chair')

I changed the weights root (best.pt) and the data root (own dataset.yaml) in detect.py.

![detect py video1](https://user-images.githubusercontent.com/109748738/222737097-009401ee-5d5c-41c4-9adb-b16d5039e8a1.PNG)

![detect py video2](https://user-images.githubusercontent.com/109748738/222737114-3c813c66-f805-45cd-947c-3c7067d36bb1.PNG)

Do you have any idea why this is happening?

**Comment by glenn-jocher** [comment]
@RoBoFAU hello there,

It looks like you might be encountering issues with multiple models being applied to your video inference. This could be due to the default behavior of YOLOv5, which applies all available models unless specified otherwise.

You can rectify this by explicitly mentioning the model name or path as an argument in your detect.py command. For example:
```
python3 detect.py --weights runs/train/exp9/weights/best.pt --img 640 --conf 0.4 --source test_video.mp4 --model yolov5s
```
This ensures that only the specified model is used for inference, reducing the likelihood of overlap from different models.

This should provide you with the desired output. If you have any further questions or need additional assistance, feel free to ask. Keep up the great work!
