### ISSUE TITLE
Maximum Higher Batch Size on RTX 3060ti  vs distributed ( 2080ti + 2080ti )

### ISSUE THREAD

**Issue by Razamalik4497** [ultralytics/yolov5#11121]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

If I use two distributed 1660 (or 2080) to train yolov5 with a higher batch size(16,32,64 etc ). It will work? 

Because to train the model on a higher batch size we require a High VRam GPU
I usually train yolov5 with 8 BS on RTX 3060ti.

**Comment by glenn-jocher** [comment]
@Razamalik4497 hey there! Thanks for reaching out. When training YOLOv5 with multiple GPUs, the effective batch size is divided by the number of GPUs used, so training with two distributed GPUs might allow for a higher effective batch size. However, it typically doesn't scale linearly due to communication overhead. You can check out the Ultralytics Docs for specific guidelines on multi-GPU training. Let me know if you have any other questions!
