### ISSUE TITLE
EdgeTpu export fail for custom data

### ISSUE THREAD

**Issue by ymotola** [ultralytics/yolov5#11183]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

Exporting Yolov5n out of the box with 80 classes works well
While trying to export custom data Yolov5n model with 7 classes (changed the yolov5n.yaml and db.yaml files accordingly), works well (only 3 operations run on CPU)
While trying to export custom data Yolov5n model with 2 classes (changed the yolov5n.yaml and db.yaml files accordingly), I get the following:

Number of operations that will run on Edge TPU: 123
Number of operations that will run on CPU: 139

Can you help me explain why?

Thanks,
Yoel

**Comment by glenn-jocher** [comment]
@ymotola hi Yoel,

It's great to hear that you've had success with exporting YOLOv5n for your custom data.

The difference in the number of operations running on Edge TPU versus CPU is likely due to the complexity and number of classes in your custom dataset. The model's architecture and the number of classes can impact the operations distributed to different hardware targets.

For further insights, you may want to review the YOLOv5n architecture or reach out to the Ultralytics community for additional guidance.
