### ISSUE TITLE
How does yolov5 use the mac m2 gpu chip for training?

### ISSUE THREAD

**Issue by rojamajor** [ultralytics/yolov5#11185]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How does yolov5 use the mac m2 gpu chip for training?

 thanks！

**Comment by rojamajor** [comment]
ok

**Comment by glenn-jocher** [comment]
@rojamajor great to hear that you're interested in training YOLOv5 on the Mac M2 GPU chip! The M1 and M1 Pro/Max GPUs are supported for training with PyTorch's Metal backend. You can find detailed information on how to use the Metal backend for training in the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. If you have any further questions, feel free to ask!

**Comment by no0b2no0b** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> How does yolov5 use the mac m2 gpu chip for training?
> 
> thanks！
> 
> ### Additional
> _No response_

The training must be explicitly configured to use the 'mps' device identifier. 
In Python, this is done by setting the device parameter to 'mps' when calling the model.train() or model() methods.

**Comment by pderrenger** [comment]
Good call, and to clarify for YOLOv5 specifically: use PyTorch’s Metal backend by selecting device=mps via the CLI, for example: python train.py --device mps --weights yolov5s.pt --data data.yaml; from Python you can call the script entrypoint: from train import run; run(device='mps', data='data.yaml', weights='yolov5s.pt') rather than model.train(); ensure your PyTorch build exposes MPS (python -c "import torch; print(torch.backends.mps.is_available())"); see the YOLOv5 v6.2 release notes for MPS support and the Ultralytics Docs for details. See the YOLOv5 v6.2 release notes and Ultralytics Docs.
