### ISSUE TITLE
How can I train the yolov5 with the  extremely imbalance dataset well?

### ISSUE THREAD

**Issue by David-19940718** [ultralytics/yolov5#11182]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/38575158/225543168-85580c6f-6c96-487b-94c1-8c14dd65379c.png)

During the training process, I found the recall is hardly pull, so sad :) 

Someboy can help me？

![image](https://user-images.githubusercontent.com/38575158/225543486-08b63fbc-5f36-499b-b46a-9ed37b54a86c.png)

**Comment by David-19940718** [comment]
It is worth mentioning that these unbalanced targets are evenly distributed on each image, which prevents me from properly applying the image-weights parameter.

**Comment by JustasBart** [comment]
Hi @David-19940718 one hack-around that I could think of would be to create a custom Python script to essentially black-out the dominating instances such so that they are not present when training. I understand that this is not an elegant solution, but at the minute your best 'real' choice would be to obtain more data of the missing classes otherwise you're going to force yolov5 to become bias towards your dominant class. So perhaps a quick try would be to literally mask out some of the dominant objects such as to end up with something reasonably balanced and then perhaps train the model and use the model to collect more data of the missing classes?

Good luck! :rocket:

**Comment by David-19940718** [comment]
> Hi @David-19940718 one hack-around that I could think of would be to create a custom Python script to essentially black-out the dominating instances such so that they are not present when training. I understand that this is not an elegant solution, but at the minute your best 'real' choice would be to obtain more data of the missing classes otherwise you're going to force yolov5 to become bias towards your dominant class. So perhaps a quick try would be to literally mask out some of the dominant objects such as to end up with something reasonably balanced and then perhaps train the model and use the model to collect more data of the missing classes?
> 
> Good luck! 🚀

Hi @JustasBart, thank u for your kindlness advice. Unfortunately, the masked method that you  mentioned above I had try, but it got nothing change~~~The only way to tackle this problem maybe is that collect more relative rare instances  as much as possiable. If you have any other awesome suggestion for me, please feel free contact with me without hesitated.

**Comment by john-tseng-710** [comment]
@David-19940718 
Do you mean this improvement? though which change is not merged yet.
[https://github.com/ultralytics/yolov5/pull/8766#issue-1321102694](url)
