### ISSUE TITLE
 The inference result of yolov5s.engine is incorrect

### ISSUE THREAD

**Issue by zeng121** [ultralytics/yolov5#11214]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Italy](https://user-images.githubusercontent.com/96764904/226905313-4c9894e9-1fa0-4837-bfe5-368723da4e80.jpg)
env:TensorRT8.4.0.6、cuda11.6、cudnn8.7.0、pytorch1.12

**Comment by RobinHan24** [comment]
enen, I met the same problem, pytorch1.10, ubunutu20.04, cuda11.3, tensorrt8.4.3,
![bus](https://user-images.githubusercontent.com/12028744/227083080-9dbb7dbe-89ba-4a46-9e4b-0953f3e8f876.jpg)

**Comment by glenn-jocher** [comment]
@RobinHan24 hi there! Thank you for reaching out. 🌟 The inference issue might be due to compatibility or configuration settings. You can refer to our documentation at https://docs.ultralytics.com/yolov5/ for guidance on troubleshooting and ensuring the correct environment setup. If the problem persists, feel free to provide additional details for further assistance. We are here to help!
