### ISSUE TITLE
"rect" true but image shape is not rectangular

### ISSUE THREAD

**Issue by mm0806son** [ultralytics/yolov5#11223]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I have a question about the flag "rect". If I understand well, during inference, the flag "rect" should be set to TRUE automatically. But the shape of image is not a rectangular, i.e. height != width.

And I fonud this [line](https://github.com/ultralytics/yolov5/blob/78a90c9661a05e8e1b7cc52a0989e4895fd96981/utils/dataloaders.py#L672) of code. If the `rect` is TRUE, the `shape` is equal to `batch_shape` which is not rectangular. In contrast, when `rect` is FALSE, the `shape` is set to `(int)img_size` and hence set to `(img_size, img_size)` later in the function `letterbox`.

`shape = self.batch_shapes[self.batch[index]] if self.rect else self.img_size  # final letterboxed shape`

Is this made on prupose? Did I misunderstand sth? Thanks for help.

Best regards,

### Additional

None.

**Comment by glenn-jocher** [comment]
@mm0806son hi there,

Thanks for reaching out! The "rect" flag is indeed automatically set to True during inference, and the code you found is intentional. In YOLOv5, when "rect" is set to True, the image is letterboxed to a rectangular shape using the "batch_shape", which allows for efficient batching of non-square images. This process ensures that the model input is always rectangular, regardless of the original image aspect ratio.

If you have any further questions or need assistance with anything else, feel free to ask. We're here to help!
