### ISSUE TITLE
How to save Detected Class Name in Text file Instead of Label

### ISSUE THREAD

**Issue by hammad2008** [ultralytics/yolov5#11248]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question on this please, as I have been searching all over google and cannot seem to get a fruitful response.

Can I get the same output using this command?

```
python3 detect.py --weights /Users/yolov5/runs/train/exp6/weights/best.pt  --img 640 --conf 0.25 --iou-thres  0.10 --source '/Users/vids50.mp4' --line-thickness 1
```
as demonstrate here:
```
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie
*** IF yes!! may I request your guidance to this example, please?*** I've been struggling with this expression for some weeks now.
```
I am getting the --saved txt files but not in the about format..please help
Thanx for acknowledging my digital requests.

**Comment by hammad2008** [comment]
@glenn-jocher  Can you help me with that?

**Comment by glenn-jocher** [comment]
@hammad2008 hey there! 😊 To save the detected class names in a text file instead of labels, you can use the `--save-txt` option with the YOLOv5 detect.py script. This will generate text files containing the class names for each detection. You can find more details on different output formats in the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. I hope this helps! Let me know if you need further assistance.
