### ISSUE TITLE
6anchor

### ISSUE THREAD

**Issue by Potato640** [ultralytics/yolov5#11241]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hello, why set 6 anchor raise error
like this
![b6f177572eb6014cbfbf5c18b30cafc](https://user-images.githubusercontent.com/72743157/227723779-ed678dda-5f4a-42ab-9336-b8c3753422da.png)
![image](https://user-images.githubusercontent.com/72743157/227723794-e22806b1-fc96-40ff-9d16-9ce8eb5687d6.png)
![image](https://user-images.githubusercontent.com/72743157/227723804-696ceb0d-154e-46ed-90a8-b70afc80a5ee.png)

**Comment by glenn-jocher** [comment]
@Potato640 hi there! It seems like you are encountering an error when setting 6 anchors. This error can occur due to various reasons, such as incompatible anchor dimensions or incorrect input format. You may want to verify the format and dimensions of the anchors you are using, and ensure they match the expected input for YOLOv5.

Additionally, our documentation at https://docs.ultralytics.com/yolov5/ provides detailed information on anchor settings and troubleshooting tips that could be helpful in resolving this issue.

Let us know if you have any further questions or encounter any other issues!
