### ISSUE TITLE
High GPU usage after model loaded for inference

### ISSUE THREAD

**Issue by Siddhantjad** [ultralytics/yolov5#11253]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

There is High GPU usage when Yolov5s is loaded for inference which should not be case for small model.
![image](https://user-images.githubusercontent.com/90169527/227916673-3cd81039-e288-42e7-9844-c3b63c15d76f.png)

### Environment

![image](https://user-images.githubusercontent.com/90169527/227916870-efbe6e81-94e6-4c84-8aea-e0a6d0c66f14.png)

### Minimal Reproducible Example

```
import torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/content/yolov5/yolov5s-seg.pt')  # local model or from repo
!nvidia-smi
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Siddhantjad hi there! Thanks for reaching out. This issue can be caused by various factors, such as the system's GPU configurations or the workload during inference. However, YOLOv5 is designed to efficiently utilize GPU resources. As for your issue, it's essential to validate the inference performance across sample workloads and architectures, which our team continuously benchmarks.

You can refer to our [Ultralytics YOLOv5 Docs](https://docs.ultralytics.com/yolov5/) for comprehensive guidance and best practices. For specific issues related to the YOLOv5 model, your input, insights, and contributions are always welcome, whether through PRs or detailed bug reports.

Your feedback and engagement in improving the YOLOv5 project are greatly appreciated, and we're here to support you along the way!
