### ISSUE TITLE
Training by pieces

### ISSUE THREAD

**Issue by Enverrrr** [ultralytics/yolov5#11261]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I've a question, I want to train parts of network by pieces. For example firstly backbone then neck then head. I tried to write specific yaml file like this one 

nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

backbone:
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]
head:
  [
  ]

however it didn't work.

Running command: python3 train.py --weights "" --noautoanchor --cfg ./models/backbone.yaml 

It raises 

![error](https://user-images.githubusercontent.com/60448321/228258441-4cddf5e0-2b45-43f2-9464-d0e4507309c9.png)

How can i fix the error?

**Comment by glenn-jocher** [comment]
@Enverrrr hi there! To train parts of the network separately, you can achieve this by creating custom config files for each part. For instance, "backbone.yaml", "neck.yaml", and "head.yaml". Then you'd train each part separately using the corresponding config file. It's important to ensure the parts are compatible and that the output of the backbone matches the input of the neck, and so on. The error you're encountering might be due to an incorrect structure or configuration mismatch. If you need further assistance, please refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/ or feel free to ask. Good luck!
