### ISSUE TITLE
Wrong label

### ISSUE THREAD

**Issue by dungx48** [ultralytics/yolov5#11263]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I exported engine model ( tensorrt). And i use it, my result have right bbox but wrong label. I try use onnx haven't problem.

**Comment by 827346462** [comment]
I met same question， I train self model, it nc=4.
I detect.py use .pt is ok.
I use export.py make .pt to .engine
try detect.py us .engine is wrong.result view show coco 80 labels.

**Comment by 827346462** [comment]
> 

my version is yolov5 6.1

**Comment by glenn-jocher** [comment]
@827346462 it sounds like you have successfully trained and exported a custom YOLOv5 model to TensorRT, but when you use the TensorRT engine file with `detect.py`, the labels shown in the results are incorrect. This could be due to a variety of reasons, but here are a few steps to help diagnose and solve the issue:

1. Verify that your TensorRT engine builder is using the correct output format for your custom YOLOv5 model. By default, YOLOv5 outputs bounding boxes in `(x, y, w, h)` format, but some TensorRT builders may require a different output format.

2. Check to see if your labels file is being read correctly by `detect.py`. You can verify this by printing the contents of the `class_names` variable in `detect.py` and making sure that they match the labels in your custom YOLOv5 model. If not, you may need to modify the code to read your custom labels file.

3. If the above steps do not solve the issue, try using the `--source` flag with `detect.py` to manually specify the image you want to run inference on. This will help ensure that the correct input and output tensors are being used when running inference on your custom YOLOv5 model.

4. Lastly, ensure that you are using the latest version of YOLOv5 and TensorRT, as both are constantly being updated with bug fixes and performance improvements.

**Comment by jiahao-xiang** [comment]
> 

Have you solved this problem? I have the same problem as you. I trained the model with my own dataset and the labels are correct when run detect.py with xx.pt. But when I run export.py to convert xx.pt to xx.engine, an error occurs. The boxes are right, but the labels are wrong which show coco 80 labels.

**Comment by glenn-jocher** [comment]
@jiahao-xiang hello! Thank you for your interest in YOLOv5.

Regarding your issue, it sounds like you are experiencing problems with getting the correct labels when converting your custom YOLOv5 PyTorch model to a TensorRT engine file using `export.py` script. 

To diagnose and solve the issue, you can try the following:

1. Verify that there are no issues with the conversion process, and that the TensorRT builder is using the correct output format for your custom model. You can do this by using the `--verbose` flag with `export.py` to print debug information. 

2. Check that the exported `*.engine` file is being loaded correctly. You can check this by modifying the `detect.py` code to print out the details of the engine input bindings and output tensors and to confirm that they match the inputs and outputs of the model that you trained.

3. Ensure that your custom labels file is being loaded correctly by `detect.py`. You can check this by printing out the contents of the `class_names` variable in `detect.py`, and confirming that they match the labels in your custom YOLOv5 model.

If none of the above suggestions provide a solution, please provide some more details about the environment you are working in (e.g. version of TensorRT and CUDA, details of your custom model and dataset), and any error messages that you see on converting. 

Hope this helps! Let us know if you have any other questions.

**Comment by rijaraju** [comment]
Hi, I am also facing the same issue with yolov5 detect.py is detecting 80 coco classes after exporting the xxx.pt model to xx.engine. But xx.pt works fine

**Comment by glenn-jocher** [comment]
@rijaraju hello! Thank you for your interest in YOLOv5 and sorry to hear you are experiencing issues with using the TensorRT engine file (.engine) generated by the `export.py` script.

It sounds like you are having an issue with the labels not being correctly recognized when running inference using the .engine file of your custom YOLOv5 model generated by TensorRT. 

To diagnose and solve the issue, here are a few suggestions:

1. Make sure that the `class_names` variable in the `detect.py` script is correctly updated with the list of class names in your custom YOLOv5 model. Otherwise, you may see incorrect labels in the inference results.

2. Check that your custom labels file is being loaded correctly by `detect.py`, and that the names in the file match the classes in your custom YOLOv5 model.

3. Verify that there are no errors in generating the .engine file using the TensorRT engine builder, and that the output format used in TensorRT matches the output format of your custom YOLOv5 model. 

4. Ensure that you are using the latest version of YOLOv5 and TensorRT, as both are constantly being updated with bug fixes and performance improvements.

If none of the above recommendations solve the issue, please provide more information about your environment, any error messages you encounter, or any other details that may help to identify and address the issue.

I hope this response is helpful. Please let us know if you have any further questions or concerns.
