### ISSUE TITLE
How to use auto-anchors.py?

### ISSUE THREAD

**Issue by llavkush** [ultralytics/yolov5#11288]
I am training object detection with yolov5m, what I want to know is for custom datatset how can I update anchor boxes, I have come across autoanchor.py, Is the model auto updating the achor boxes  or please let me know how to do it?

**Comment by Jibanul** [comment]
During training, YOLOv5 automatically checks if the current/predetermined anchors are a good fit for your dataset, custom or otherwise. If they find it's not a good fit then they attempt to improve the anchors using kmean_anchors. I don't think there is any option for recalculating the anchors regardless of their fitness. There is an option ```noautoanchor``` which can disable AutoAnchor. By default, AutoAnchor is on.

**Comment by Haalum** [comment]
During training, YOLOv5 automatically checks if the current/predetermined anchors are a good fit for your dataset, custom or otherwise. If they find it's not a good fit then they attempt to improve the anchors using kmean_anchors. I don't think there is any option for recalculating the anchors regardless of their fitness. There is an option ```noautoanchor``` which can disable AutoAnchor. By default, AutoAnchor is on.

**Comment by glenn-jocher** [comment]
@Jibanul thank you for using YOLOv5 for your object detection needs. As you mentioned, YOLOv5 automatically updates the anchor boxes during training, and there is currently no option to recalculate them regardless of their fitness. However, you can disable the AutoAnchor feature using the ```noautoanchor``` option if you prefer to use your own predefined anchors. This option is turned on by default, so it is important to make sure that you have the most optimal anchor values for your dataset configuration. If you have any further questions or concerns, please do not hesitate to continue the conversation.
