### ISSUE TITLE
get the label from the image

### ISSUE THREAD

**Issue by DangTranQL** [ultralytics/yolov5#11295]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![Screenshot 2023-04-03 235425](https://user-images.githubusercontent.com/72413423/229683257-657721c0-0ec5-4520-b0aa-edbc3fb50c4d.png)
I've added additional labels to the model. Now I wanna assign the value of 'name' to a string, but I couldn't figure out how. Any help would be appreciated

**Comment by glenn-jocher** [comment]
@DangTranQL to get the 'name' value of labels, you can use the following code snippet:

```python
# create a dictionary with label names and their respective IDs
label_dict = {label[0]: label_idx for label_idx, label in enumerate(model.module.names)}

# retrieve 'name' of label index 1
label_idx = 1
label_name = model.module.names[label_idx]
```

where `model` is your trained YOLOv5 model. 

In this example, I created a dictionary that maps label names to their respective IDs so that you can easily convert between them. Then, to get the 'name' of a particular label index, you can simply use the `model.module.names` list and index it with the label index.

Let me know if you have any questions!
