### ISSUE TITLE
new ultralytics custom trained model issue

### ISSUE THREAD

**Issue by hakmesyo** [ultralytics/yolov5#11307]
Hi all,

new ultralytics custom trained model raises an exception 

Exception: 'Detect' object has no attribute 'grid'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.

this issue appeared yesterday. there is no problem model obtained yolov5 from ultralytics hub before yesterday.

Regards

**Comment by glenn-jocher** [comment]
Hi @angrypenguin89,

This error message typically appears when there are changes made to the source code and cache, which causes inconsistencies. You could try running with `force_reload=True` to rebuild the cache and see if that solves your issue.

If the problem persists, please describe your use case and environment more specifically and provide the exact steps and code that led to this error. Any additional information that can help diagnose the issue would be appreciated.

Feel free to reach out if you have any further questions or concerns.

**Comment by hakmesyo** [comment]
Thanks for your cooperations,

indeed i have already added force_reload term as it can be seen code snippets below;

import os  
import torch 

modelPath=r'c:\yolov5/models/yolov5s_robotaksi_ds_1.pt'

model = torch.hub.load('ultralytics/yolov5', 'custom', path=modelPath, force_reload=True) 

this error comes yesterday. Because model generated from ultrlaytics hub two days ago runs without any issues. We need urgent fix since we use ultralytics in our running projects.

Thanks in advance.

**Comment by glenn-jocher** [comment]
Hi @hakmesyo,

I'm sorry to hear that you are still experiencing issues with the `Detect` object attribute error even when using `force_reload=True`.  

If you are unable to solve the issue, please consider opening a Github issue in the YOLOv5 repository that describes the error in more detail and provides your code, environment, and other relevant details related to your issue. You can also include a minimum reproducible code example so that the developers can reproduce the issue and evaluate the necessary fix. 

The YOLOv5 developers will be able to provide you with more targeted assistance and help address the issue quicker.

Please feel free to let me know if you have any other questions.

**Comment by Wu-Jian-Ting** [comment]
i also have this problem.
`import cv2`
 `import torch `
 `from torchvision import transforms`
 `from PIL import Image`
 `model = torch.hub.load('.', 'custom',path='weights/best.pt',source='local',force_reload=True)`


and cause 
AttributeError                            Traceback (most recent call last)
File ~/yolov5/hubconf.py:73, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     72         LOGGER.setLevel(logging.INFO)  # reset to default
---> 73     return model.to(device)
     75 except Exception as e:

File ~/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py:1145, in Module.to(self, *args, **kwargs)
   1143     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
-> 1145 return self._apply(convert)

File ~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py:651, in AutoShape._apply(self, fn)
    650 m.stride = fn(m.stride)
--> 651 m.grid = list(map(fn, m.grid))
    652 if isinstance(m.anchor_grid, list):

File ~/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'Detect' object has no attribute 'grid'

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
Cell In[17], line 7
      4 from PIL import Image
      6 # 加载自训练的YOLOv5模型
----> 7 model = torch.hub.load('.', 'custom',path='weights/best.pt',source='local',force_reload=True)
      9 # 打开摄像头
     10 cap = cv2.VideoCapture(0)

File ~/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/hub.py:558, in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    554 if source == 'github':
    555     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
    556                                        verbose=verbose, skip_validation=skip_validation)
--> 558 model = _load_local(repo_or_dir, model, *args, **kwargs)
    559 return model

File ~/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/hub.py:587, in _load_local(hubconf_dir, model, *args, **kwargs)
    584     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
    586     entry = _load_entry_from_hubconf(hub_module, model)
--> 587     model = entry(*args, **kwargs)
    589 return model

File ~/yolov5/hubconf.py:83, in custom(path, autoshape, _verbose, device)
     81 def custom(path='path/to/model.pt', autoshape=True, _verbose=True, device=None):
     82     # YOLOv5 custom or local model
---> 83     return _create(path, autoshape=autoshape, verbose=_verbose, device=device)

File ~/yolov5/hubconf.py:78, in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     76 help_url = 'https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading'
     77 s = f'{e}. Cache may be out of date, try `force_reload=True` or see {help_url} for help.'
---> 78 raise Exception(s) from e

Exception: 'Detect' object has no attribute 'grid'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.

how can  i do?

**Comment by glenn-jocher** [comment]
Hi @Wu-Jian-Ting,

The error that you are seeing with the 'Detect' object not having an attribute 'grid' is a known issue that has been reported by other users recently. 

The error is due to inconsistencies between the source code and the cache resulting from changes made to the source code. One possible solution is to run with `force_reload=True` to rebuild the cache and see if that resolves the issue.

If that does not work, it may be helpful for you to open a new issue on the YOLOv5 repository with a minimum reproducible code example, details about your environment, and the specific steps that led to this error.

The development team can then evaluate the issue and provide you with additional assistance and help you resolve this issue.

Thank you for your patience and understanding.
