### ISSUE TITLE
yolov5/utils/loss.py/line 198   AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by PhilCuriosity** [ultralytics/yolov5#11342]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

  When I tried to run train.py, I encountered the following problem：

>       File "yolov5/utils/loss.py", line 198, in build_targets
>       anchors, shape = self.anchors[i], p[i].shape
>       AttributeError: 'list' object has no attribute 'shape'

The parameters are set as follows：
`  parser.add_argument('--weights', type=str, default=ROOT / 'yolov5s-seg.pt', help='initial weights path')
    parser.add_argument('--cfg', type=str, default=ROOT / 'models/segment/yolov5s-seg.yaml', help='model.yaml path')
    parser.add_argument('--data', type=str, default=ROOT / 'data/coco128-seg.yaml', help='dataset.yaml path')`
and the rest remain at default settings.

### Environment

ubuntu18.04
cuda10.2
torch2.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PhilCuriosity** [comment]
https://github.com/ultralytics/yolov5/issues/10967

**Comment by glenn-jocher** [comment]
@PhilCuriosity, there are a few things you could try to solve this issue:

- Make sure that you are using the latest version of YOLOv5 by updating to the master branch with `git pull`.
- If you have custom anchors defined, ensure they are not in the wrong format. Anchors should be specified in pixels and in descending order of area for each scale.
- If none of the above work, try using the default anchors for your chosen model size by removing the `anchors` key from your `yolo` layer in the model YAML file.

I hope this helps! Let me know if you have any additional questions.

**Comment by bl6g6** [comment]
Make sure use segment/train.py to train segment instead of normal train.py

**Comment by glenn-jocher** [comment]
@bl6g6 thank you for your input regarding training the segmentation functionality of YOLOv5. Indeed, using `segment/train.py` instead of `train.py` is the recommended way to train a YOLOv5 segmentation model. 

The `segment/train.py` script includes additional functionality to build segmentation ground-truth masks and calculate loss values appropriately. 

We appreciate your contribution and hope that this information is helpful for others who may have the same question. If you have any further inquiries, please don't hesitate to let us know.
