### ISSUE TITLE
All performance metrics were reported as 0

### ISSUE THREAD

**Issue by Tiepifengdou** [ultralytics/yolov5#11347]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training yolov5-7.0-segment on my dataset, based on the output of this program, I encountered some issues during model validation. After validating the model, all performance metrics (Precision, Recall, mAP) were reported as 0. Additionally, an error occurred while saving the results, indicating that a sequence cannot be multiplied by a non-integer of type 'float'.
![1681381915](https://user-images.githubusercontent.com/130656766/231732874-7c4cc2c8-4055-42aa-a174-c1a508ff830f.jpg)
But after validating, everything is in a right way.
![1681382527](https://user-images.githubusercontent.com/130656766/231735416-4bf09a3d-36a8-446e-b782-9a81af4cc845.png)
Besides, the last row in results.csv contains errors, while the rest of the rows are correct. The following are the results of my training for 100 epochs.
![1681382906](https://user-images.githubusercontent.com/130656766/231736750-1f26117d-b137-4085-83ba-635de1e6a990.png)
Finally, there is also an issue with my results.png. I will post my image below.
![results](https://user-images.githubusercontent.com/130656766/231737196-ba75383f-c4b7-43a5-8bec-44658bebb411.png)
These issues have been bothering me for a long time. What should I do? Thank you.

### Additional

No response

**Comment by glenn-jocher** [comment]
@Tiepifengdou, it looks like you are experiencing multiple issues with YOLOv5 model validation and saving, as well as with result visualization. Given the details you have provided, it's hard to pinpoint exactly what went wrong with your training and validation. Could you provide more information on the datasets and configurations you used when training and validating your model?

In the meantime, here are a few general suggestions that might help you troubleshoot:

1. Try running validation with the `--save-json` argument, which produces a JSON file in COCO format. This file can be used as input to external tools such as COCO API or Pycocotools to calculate metrics.

2. Double check the contents of your .yaml file, which includes the training and validation data paths, along with other important configurations.

3. Check that you are using the latest version of YOLOv5 and are up to date with all dependencies.

4. Go through and try to reproduce the errors that were thrown when validating the model. Check if there is a specific data sample or operation that is causing these errors.

If these suggestions don't help, please share any additional information or details you have, and I'll do my best to help you out.

**Comment by Tiepifengdou** [comment]
Thank you! This is the content of my data.yaml file, which was modified from coco128-seg.yaml.
![1681438748](https://user-images.githubusercontent.com/130656766/231927113-a24e784f-9d32-4723-a21f-6d69b2f9f181.jpg)
This is the path of each file in my project. I have created an image for illustration. The weights folder contains files such as best.pt and last.pt.
![1681439558](https://user-images.githubusercontent.com/130656766/231926994-90eb645d-1855-4385-8c07-a0bcd6169e24.jpg)
This is some information from train.py.
![1681439989](https://user-images.githubusercontent.com/130656766/231928064-eb7759b5-1b38-40b2-a328-c27f06ef7a61.jpg)
I'm not sure if there are any errors in the paths in my fruit.yaml file. I modified it based on the original file, and my final training weights, best.pt and last.pt, seem to be intact. So I think my issue may not be related to the paths in my file.

**Comment by Tiepifengdou** [comment]
Sorry, there is an incorrect file name in the second image. ymal --> yaml

**Comment by glenn-jocher** [comment]
@Tiepifengdou, thank you for providing additional information! Based on what you have shared, it seems like the paths in your `data.yaml` file and the locations of the `best.pt` and `last.pt` files look correct. 

Given that your training weights have been saved correctly, one possibility is that the issue might be with the `val.py` script you're using to run model validation. It's worth checking if the version of `val.py` is compatible with the version of YOLOv5 you're using. 

Another suggestion would be to validate the model using the official COCO validation dataset and see if the same issues occur. You can download the dataset from the COCO website (http://cocodataset.org/). This will help you narrow down whether the issue is with the dataset you created or your validation setup. 

Finally, for the errors in the `results.csv` file and `results.png`, double check that the paths and file names were correctly specified when running the validation script, and that sufficient permissions are granted to the specified directories.

Let me know if these suggestions help you!

**Comment by Tiepifengdou** [comment]
Thank you. I previously trained using the coco128-seg dataset, and the results are the same as now. It's worth noting that everything seemed normal when I ran val.py, as shown in my previous images. However, when running train.py, the above error occurs during the final validation stage. As for compatibility issues with val.py, I downloaded it from https://github.com/ultralytics/yolov5/tree/v7.0, and I will try to download it again, but the problem may not be here.

**Comment by glenn-jocher** [comment]
@Tiepifengdou, I see. Based on what you've mentioned, it sounds like the issue may indeed be with the final validation stage. When you train with YOLOv5, the `train.py` script automatically initiates a validation step at the end of each epoch using the validation dataset specified in the `.yaml` file. If there are any issues during the validation step at the end of the epoch (such as errors you've mentioned), `train.py` will terminate before the end of the epoch and throw an error message.

Assuming you have followed the steps properly (listed in this [tutorial](https://docs.ultralytics.com/tutorials/) provided by Ultralytics), one possible explanation for the error during the final validation stage could be because of a small or low quality dataset (which can cause overfitting). 

Another possibility is that you may have run into hardware limitations, especially if you're training with a GPU. Ensure that you have enough free VRAM on your graphics card, as insufficient VRAM can cause the training/validation to freeze or halt completely.

I suggest trying to use an external tool like the COCO API to evaluate your validation results to see if they make sense to corroborate that your validation dataset and configurations are correct. If everything else checks out, you may want to consider transferring your training to a more powerful environment with better hardware.

**Comment by Tiepifengdou** [comment]
Thank you very much for your help. When I tried setting '--device' to 'cpu' in train.py, everything worked fine, including the printing during the final validation stage, the values on the last line of the results.csv file, and the output of the results.png image. I have always set the '--device' parameter to 0, so it seems the problem was with my hardware. 
![1681632217](https://user-images.githubusercontent.com/130656766/232283745-e141bc11-04b0-4ceb-a88e-f79cdc6a0c56.jpg)
Because I only trained for one epoch, there are only two rows of data.
![1681632288(1)](https://user-images.githubusercontent.com/130656766/232283805-a177197b-0b68-4dd1-b27c-cab72a0ed70a.jpg)
![results](https://user-images.githubusercontent.com/130656766/232283815-a2d4aa28-67c9-48e9-82c7-ed372e5d660d.png)
Thanks again for your help! I think I have finally identified where my problem lies!

**Comment by glenn-jocher** [comment]
@Tiepifengdou you're welcome! I'm glad that you were able to identify the issue and resolve it by setting `--device` to `cpu` in `train.py`. This suggests that the issue was indeed related to hardware limitations on your GPU. I hope this solves all the issues you were experiencing and you're able to successfully complete your training! Let me know if you need further help.

**Comment by Tiepifengdou** [comment]
Thank you very much for your help. I think I have resolved all the issues I encountered during my training.

**Comment by glenn-jocher** [comment]
You're welcome @Tiepifengdou! I'm glad to hear that you were able to resolve all the issues during your training. If you have any further questions or run into any more issues, don't hesitate to ask! Good luck with your training!
