### ISSUE TITLE
Custom input size: letterbox vs resizing

### ISSUE THREAD

**Issue by bartlomiejgadzicki-digica** [ultralytics/yolov5#11350]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there,

I have a custom dataset with images in various resolutions. My model (after deployment to ONNX) will have to work on a very specific input size of 544x320, where images will be squeezed to this resolution, disregarding the aspect ratio.

**How can I ensure the best possible performance after deployment?**

I know that yolov5 training pipeline uses a letterbox i.e. resizes images to a long dim of ~576 (closest multiply of stride), adds padding, and keeps the original aspect ratio. Should I force an input size of 544x320 with letterbox or maybe rewrite the input preprocessing to force resizing without keep the original aspect ratio (both cases would happen during training)?

And how does the `--rect` argument fits here? Should I train for `--imgsz 576` with that `--rect` flag and resize the images during inference? What would be the best approach in my case?

My current idea is to train on img size 576 with letterbox (without `--rect` argument), and then during ONNX inference resize the imgs to 544x320 (with disregarding the original aspect ratio) and see how it works. I have to use my own codebase for inference tho.

**Comment by glenn-jocher** [comment]
Hi @bartlomiejgadzicki-digica, 

To adjust the input image size to a specific resolution of 544x320 without preserving the aspect ratio, You can use the `letterbox()` function in the inference script to resize the image while maintaining the aspect ratio, then add padding to the dimensions that do not align with the network's input resolution (in this case 544x320). 

The `--rect` flag is used to remove the letterboxing effect by changing the default aspect ratio preservation to input-size-to-image-size matching. It's best to use this flag when testing validation accuracy on your testing dataset to ensure a fair validation comparison since letterboxing tends to provide more context and advantage over rectangular aspect ratios.

Therefore, your strategy to train on img size 576 with letterbox (without --rect argument), and then during ONNX inference resize the images to 544x320 (with disregarding the original aspect ratio) looks promising. Please try it out and see how it works.

Let me know if you have any further questions.

**Comment by bartlomiejgadzicki-digica** [comment]
Thank you for the response! Fortunately, I managed to get square inference input for the deployment, so the issue with rectangular input is no more. 

Thanks again <3

**Comment by glenn-jocher** [comment]
@bartlomiejgadzicki-digica you're welcome! If you have any further questions or issues, don't hesitate to ask. Good luck with your YOLOv5 deployment!
