### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by rohinish404** [ultralytics/yolov5#11368]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm trying to train a yolo model on custom dataset (object detection) but i'm getting this error 
"NoneType object has no attribute keys". I tried changing the dataset.yml file but still getting this.
Can anyone tell me why i'm getting this error and how can i resolve it?
<img width="1021" alt="Screenshot 2023-04-16 at 10 08 45 AM" src="https://user-images.githubusercontent.com/92542124/232269848-78c5efaa-7fa4-4bb5-aca4-4a58238e1304.png">

**Comment by glenn-jocher** [comment]
@rohinish404, the error message you're seeing seems to indicate that the `config` argument passed to `train.py` function call does not have any keys. This could be caused by an improperly formatted `dataset.yaml` file, or incorrect data or paths specified in the `train.yaml` or `dataset.yaml` files. 

Please ensure that your dataset is in the format of YOLO's annotation file style: 
```
path/to/img1.jpg xmin,ymin,xmax,ymax,class_id xmin,ymin,xmax,ymax,class_id ... 
path/to/img2.jpg xmin,ymin,xmax,ymax,class_id xmin,ymin,xmax,ymax,class_id ...
```

Alternatively, could you provide a more detailed traceback of the error message? A minimum reproducible example would allow us to provide further assistance to you.

**Comment by rohinish404** [comment]
The dataset.yml file i created looks like below which i copied from https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/#13-prepare-dataset-for-yolov5 this link. Do i need to make changes here?
<img width="853" alt="Screenshot 2023-04-16 at 7 59 12 PM" src="https://user-images.githubusercontent.com/92542124/232319883-dfac6b59-aa7d-45b6-b387-961b2f1eb6d2.png">

**Comment by rohinish404** [comment]
Solved the error. Thank you so much for the reply:)

**Comment by glenn-jocher** [comment]
You're welcome @rohinish404! So glad to hear that you were able to solve the error. Don't hesitate to reach out if you have any further questions or issues in the future. Good luck with your YOLOv5 project!

**Comment by rohinish404** [comment]
Yeah sure!! I'll reach out if i get stuck some where!
And thank you for the wishes....
Shall i close this issue?

**Comment by glenn-jocher** [comment]
@rohinish404 yes, you can go ahead and close this issue. Don't hesitate to open a new one if you have any further questions or issues. Have a great day!

**Comment by rohinish404** [comment]
Yeah sure!! Have a great day:)

**Comment by glenn-jocher** [comment]
@rohinish404 you too!
