### ISSUE TITLE
Should I have argument while training?

### ISSUE THREAD

**Issue by AlecMaxPro** [ultralytics/yolov5#11374]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

  I use the version of  Yolov5-6.1. I notice there is no the default of cfg argument. But others basic argument have all defaults. Should I have "--cfg models/yolov5s.yaml" while I'm training my own models? Whether there is a bad influence in results, if I don't have this cfg(models/yolov5s.yaml).
  
  But I also find whether I add "--cfg yolov5s.yaml" or not, the layers of this models (yolov5s) can always be run.

  Thanks a lot!

**Comment by glenn-jocher** [comment]
Hello @AlecMaxPro, thank you for your question! The `--cfg` argument specifies which configuration file to use, which contains the model architecture and hyperparameters. If it is not specified, YOLOv5 will use the default configuration file for the selected model size (`yolov5s.yaml` for `--weights yolov5s.pt`, `yolov5m.yaml` for `--weights yolov5m.pt`, etc). However, it is recommended to specify the `--cfg` argument to ensure reproducibility between training and inference. It should not have a bad influence on the results if you don't specify it, but it is always better to be explicit. 

Regarding the layers of the model being able to run without specifying the `--cfg` argument, this is because the default configuration file for each model size is used. If you specify a different configuration file, the architecture and hyperparameters of the model will be different, which can impact the results. 

Please let me know if you have any further questions or concerns.

**Comment by AlecMaxPro** [comment]
Ok, I know it. That's a very explicit answer. 

Thanks again!

**Comment by glenn-jocher** [comment]
You're welcome, @AlecMaxPro! I'm glad I could help. If you have any more questions or run into any issues in the future, don't hesitate to ask. Have a great day!
