### ISSUE TITLE
NameError: name 'nearest' is not defined

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/yolov5#11405]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

name 'nearest' is not defined
  File "/home/ojun.kwon/workspace/ojun.kwon/baseline-yolov5/models/yolo.py", line 314, in parse_model
    args[j] = eval(a) if isinstance(a, str) else a  # eval strings
  File "/home/ojun.kwon/workspace/ojun.kwon/baseline-yolov5/models/yolo.py", line 185, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "/home/ojun.kwon/workspace/ojun.kwon/baseline-yolov5/train.py", line 133, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/ojun.kwon/workspace/ojun.kwon/baseline-yolov5/train.py", line 534, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/ojun.kwon/workspace/ojun.kwon/baseline-yolov5/train.py", line 643, in <module>
    main(opt)
NameError: name 'nearest' is not defined

<img width="740" alt="image" src="https://user-images.githubusercontent.com/49416429/233553835-f758f1d8-8427-4025-9c32-3ed4eea412a2.png">

` with contextlib.suppress(NameError):
                args[j] = eval(a) if isinstance(a, str) else a  # eval strings`

NameError shouldn't happen in this syntax, but I wonder why it does
please help me..

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ohjunee hi there! It looks like you're encountering a `NameError: name 'nearest' is not defined` issue during training. This may be caused by a missing "import" statement or incorrect variable usage in your code. 

The snippet you've shared uses `eval(a) if isinstance(a, str) else a`, which may be evaluating a string that references the `nearest` variable that is not defined. 

To assist you further, it would be helpful to see the related parts of your code where `nearest` is used and how it's defined. If you could provide a minimal reproducible example or more context, it would greatly aid in pinpointing the issue.

Feel free to refer to the YOLOv5 documentation (https://docs.ultralytics.com/yolov5/) for additional guidance on training and syntax.

I appreciate your willingness to submit a PR! Your contributions are valuable to the YOLO community and the project. Thank you for helping to improve YOLOv5!
