### ISSUE TITLE
I would like to add the following features: the ability to output images beyond the box detection range, the ability to normalize facial images to the same size based on facial proportion, the ability to process images with alpha channels, and the ability to output images with alpha channels.

### ISSUE THREAD

**Issue by shelly-luo** [ultralytics/yolov5#11413]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

the ability to output images beyond the box detection range, 
the ability to normalize facial images to the same size based on facial proportion,
the ability to process images with alpha channels,
and the ability to output images with alpha channels.

### Use case

I am an art professional, and I dislike cutting images. I hope to automate the image processing.

### Additional

By modifying plots.py, I successfully increased the cropping range of the cropped image. (I modified pad=300.)
`def save_one_box(xyxy, im, file=Path('im.jpg'), gain=1.02, pad=300, square=False, BGR=False, save=True):`

However, I couldn't handle the issue with the alpha channel. My coding skills are poor, so I could only write two scripts - one for adding a green background to the image, and another for removing the green background from the image - to deal with the transparency issue.

Add a green background
[批量添加绿幕.txt](https://github.com/ultralytics/yolov5/files/11299600/default.txt)

Remove a green background.
[批量去除绿幕.txt](https://github.com/ultralytics/yolov5/files/11299601/default.txt)

This is my processing workflow: original image with alpha channel > add green background to images using batch processing script > use YOLOv5 to detect faces > crop beyond the detected box > remove green background from output images using batch processing script.

![未标题-2](https://user-images.githubusercontent.com/113850302/233745371-20125ed2-e24a-4c83-bf9e-2b8844316b8e.jpg)

I really need these features! Please help me out!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shelly-luo thank you for your detailed description and for taking the time to create those scripts. Regarding your feature requests, it seems like the ability to process images with alpha channels could be added to the code. To normalize facial images based on facial proportion, you may want to look into OpenCV or other image processing libraries, as this may not be a direct feature addition to the YOLOv5 code. Additionally, adding the ability to output images with alpha channels may also be possible, but it will likely require changes to the code or post-processing steps. I would recommend creating separate issues for each specific feature request so that it is easier to track and address them. Thank you for contributing to YOLOv5 with your proposed PR, and please let us know if you need further assistance.
