### ISSUE TITLE
AttributeError: 'function' object has no attribute 'imgpath'

### ISSUE THREAD

**Issue by Itzsaggy** [ultralytics/yolov5#11416]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

AttributeError: 'function' object has no attribute 'imgpath'

**Comment by glenn-jocher** [comment]
@Itzsaggy, 

This error message typically arises due to an incorrect or non-existent attribute in your code. Please double-check your code and ensure that 'imgpath' is defined as an attribute and not as a function.

If you continue to have issues, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your code and error message, so we can better assist you.
