### ISSUE TITLE
git.Repo(path).remotes.origin report AttributeError: 'IterableList' object has no attribute 'origin'

### ISSUE THREAD

**Issue by xingguang12** [ultralytics/yolov5#11415]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I just cloned yolov5 from official website, and ran it directly and reported an error.  I'm confused.
/root/miniconda3/bin/python3 /root/autodl-tmp/yolov5-test/train.py 
Traceback (most recent call last):
  File "/root/autodl-tmp/yolov5-test/train.py", line 67, in <module>
    GIT_INFO = check_git_info()
  File "/root/miniconda3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/root/autodl-tmp/yolov5-test/utils/general.py", line 362, in check_git_info
    remote = repo.remotes.origin.url.replace('.git', '')  # i.e. 'https://github.com/ultralytics/yolov5'
  File "/root/miniconda3/lib/python3.8/site-packages/git/util.py", line 1001, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xingguang12 it seems like the error you're seeing is due to `git` not being installed or set up correctly. You can either try installing `git` or simply removing the following line of code in `yolov5/utils/general.py`:

`remote = repo.remotes.origin.url.replace('.git', '')  # i.e. 'https://github.com/ultralytics/yolov5'`

This line of code is used to display the remote URL of the cloned repository and isn't necessary for YOLOv5 to function properly. Let us know if this resolves your issue! For any further questions, you may find our documentation helpful: https://docs.ultralytics.com/yolov5/.

**Comment by xingguang12** [comment]
> @xingguang12 it seems like the error you're seeing is due to `git` not being installed or set up correctly. You can either try installing `git` or simply removing the following line of code in `yolov5/utils/general.py`:
> 
> `remote = repo.remotes.origin.url.replace('.git', '') # i.e. 'https://github.com/ultralytics/yolov5'`
> 
> This line of code is used to display the remote URL of the cloned repository and isn't necessary for YOLOv5 to function properly. Let us know if this resolves your issue! For any further questions, you may find our documentation helpful: https://docs.ultralytics.com/yolov5/.
Thank you for your time. I can run it by directly removing these lines. I have installed gitpython, but I still wonder why this error occurs.

**Comment by glenn-jocher** [comment]
@xingguang12 it's possible that the error is occurring due to gitpython not being compatible with the version of git installed on your system. Alternatively, there may be an issue with the git repository itself that's causing the error. 

If you're interested in further troubleshooting, you can try upgrading or downgrading your version of git or gitpython to see if that resolves the issue. You can also try cloning the repository again from scratch to ensure that there are no issues with the repository. 

In any case, I'm glad that you were able to get YOLOv5 running by removing the line of code in question. Let us know if you have any further issues or questions!
