### ISSUE TITLE
Training terminated unexpectedly

### ISSUE THREAD

**Issue by Aurora1-max** [ultralytics/yolov5#11429]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello author, when I was training a model of 200 generations with yolov5-master recently, an unexpected interruption occurred at generation 164. At that time, the error was reported as being interrupted by the keyboard's CTRL+C, but I clearly remember that I was sleeping at that time and did not interrupt manually. In addition, I tried to continue training from the 164th generation using resume, but unfortunately, the error message showed that my weights had been trained to the 200th generation, but it was not, and my last training information had ended at the 164th generation. What is the situation? I put the specific pictures below for your observation. Thanks you! !
（I saved the error message, but there is no screenshot. In addition, my path is pure English）
![7a0f9db5ffbc08a458046bc4680bff6](https://user-images.githubusercontent.com/81025651/233904729-6ef6a9e5-134d-4695-ac8b-b18b479c4322.png)
![f94a6dd15b49934a273917fffbe2a49](https://user-images.githubusercontent.com/81025651/233904801-1bf1a008-d81f-4cab-b1ef-e46a72fce8cb.png)

### Environment

--YOLOv5-master torch 2.0.0 cudnn 7.6.5+cuda 11.8+ NVIDIA RTX 2080 TI 11GMiB
--OS:Windows 10
--Python:3.8

### Minimal Reproducible Example

   tenth training with { weight : yolov5s.pt, cfg : yolov5s.yaml, data : data/wheat_datasets.yaml }

       else setting--single-cls : true  + yolo5.yaml nc : 80 -> 1+batch_size=4+moment : 0.9 weight_decay : 0.0001+learn : 0.0025

		batch_size : 4, epoch : 200 }    start_time : 4.22/22.30   end_time : 4.23/2.36

		            Estimated time-consuming :   5 hours Actual time consuming : 4.1 hours

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @Aurora1-max, thank you for providing such a detailed issue report. From your error messages, it appears that your training was interrupted at generation 164 due to a keyboard interrupt, as you have suspected. 

Regarding your issue with resuming training, the error message suggests that the weights you were attempting to resume from were trained for 200 epochs. This could be due to a number of reasons, such as incorrect weights or save intervals, so please verify the save interval setting during training. 

It is also possible that your training was not properly resumed from the correct checkpoint. Please ensure that the provided `--resume` argument points to the correct `.pt` weights checkpoint file. You can also try deleting the last checkpoint file and resuming training again.

If the issue persists, please provide more specific details such as the `--resume` command you used and the exact error message you received.

**Comment by Aurora1-max** [comment]
> Hi @Aurora1-max, thank you for providing such a detailed issue report. From your error messages, it appears that your training was interrupted at generation 164 due to a keyboard interrupt, as you have suspected.
> 
> Regarding your issue with resuming training, the error message suggests that the weights you were attempting to resume from were trained for 200 epochs. This could be due to a number of reasons, such as incorrect weights or save intervals, so please verify the save interval setting during training.
> 
> It is also possible that your training was not properly resumed from the correct checkpoint. Please ensure that the provided `--resume` argument points to the correct `.pt` weights checkpoint file. You can also try deleting the last checkpoint file and resuming training again.
> 
> If the issue persists, please provide more specific details such as the `--resume` command you used and the exact error message you received.

Thank you very much for your reply, according to your description, I checked the weight path of last.pt and made sure it is correct (the file saving location is automatically generated by the algorithm, and I have not moved it since then). In addition, I am not quite sure what you mean by deleting the last checkpoint file. If I delete it, I will not be able to use the --resume parameter to resume training, or I may have misunderstood it. I hope you could point me out again. Finally, I reproduced the error and gave it in the terminal. The following are some screenshots:
![image](https://user-images.githubusercontent.com/81025651/234273276-4e239522-d630-442c-a292-4eefc2e360da.png)

**Comment by glenn-jocher** [comment]
@Aurora1-max, thank you for the additional information and screenshots. Based on your error message, it seems to indicate that `last.pt` was not saved correctly during the training process. One reason this could happen is if the GPU crashes or if there is some interruption during training that prevents `last.pt` from being saved correctly.

To try to resolve this issue, you could try deleting the `last.pt` file and starting training from the beginning again. Once you have verified that your new training is progressing correctly and you have advanced to the point where `last.pt` should be saved, you can try resuming from that checkpoint again using the `--resume` flag.

Alternatively, you could also try using an older weight checkpoint file from a previous epoch to resume training instead of using `last.pt`. 

I hope that helps, and feel free to reach out if you have any further questions or issues!

**Comment by Aurora1-max** [comment]
> @Aurora1-max, thank you for the additional information and screenshots. Based on your error message, it seems to indicate that `last.pt` was not saved correctly during the training process. One reason this could happen is if the GPU crashes or if there is some interruption during training that prevents `last.pt` from being saved correctly.
> 
> To try to resolve this issue, you could try deleting the `last.pt` file and starting training from the beginning again. Once you have verified that your new training is progressing correctly and you have advanced to the point where `last.pt` should be saved, you can try resuming from that checkpoint again using the `--resume` flag.
> 
> Alternatively, you could also try using an older weight checkpoint file from a previous epoch to resume training instead of using `last.pt`.
> 
> I hope that helps, and feel free to reach out if you have any further questions or issues!

As you said, there is no problem when I try to use the --resume parameter to execute other unfinished training weights. So there is a high probability that the problem occurs in this training task, and it is likely to be due to the reason you mentioned that the GPU crashed or the weights were not saved correctly (my computer was turned on for 120 hours during training for this task!!) , Of course, the occurrence of this situation is due to my personal reasons rather than algorithm bugs. Of course, you can also try to reproduce or re-test the --resume parameter, and I am also very happy to provide you with more detailed information. Next I will try to train the new weights from scratch, hope all goes well!

**Comment by glenn-jocher** [comment]
@Aurora1-max, it sounds like you have a good handle on the situation now. Long training sessions can indeed sometimes lead to unexpected issues, such as GPU crashes or interruptions that affect the saving of weights. Starting fresh with a new training session is a good approach, and keeping an eye on the system's stability during the process can help prevent similar issues.

Remember to monitor your GPU usage and system temperatures to ensure everything is running smoothly. If you encounter any further issues or have more questions, don't hesitate to reach out. Good luck with your new training run, and I hope it goes smoothly! 🤞🚀
