### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by Abecadarian** [ultralytics/yolov5#11442]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

When trying to load a custom detection model using torch.hub, I got the message 'ImportError: cannot import name 'Mapping' from 'collections''.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Abecadarian hello and thank you for reaching out! 

Regarding the `ImportError: cannot import name 'Mapping' from 'collections'` error message, it might be caused by a version incompatibility between the Python version you are using and other libraries that you have installed. Could you please ensure that you have the latest version of Python 3 installed, and that all the packages required by YOLOv5 (as listed in `requirements.txt`) are up-to-date as well?

If you have already ensured that your environment is up-to-date, and the issue persists, please let us know and we'll do our best to help you troubleshoot it.

Thanks for your support and interest in YOLOv5!
