### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by device-4** [ultralytics/yolov5#11451]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/132016311/234991096-d1198e42-bc5b-4200-a8d5-bbea82c09c89.png)
I discovered this error during the training process,it appears in the generals.py on the no.523 line,and I can't find a solution

### Environment

python:3.9.13
pytorch:1.9.1

### Minimal Reproducible Example

Traceback (most recent call last):
  File "D:\YOLOV5\yolov5-master\train.py", line 643, in <module>
    main(opt)
  File "D:\YOLOV5\yolov5-master\train.py", line 532, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\YOLOV5\yolov5-master\train.py", line 113, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "D:\YOLOV5\yolov5-master\utils\general.py", line 523, in check_dataset
    if isinstance(data['names'], (list, tuple)):  # old array format
TypeError: string indices must be integers

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @device-4! Thanks for reporting this issue 🙌.

This error seems to be caused by the `data` dictionary not including a `names` key of the expected format (it should be an indexable, such as a list or tuple). Could you check your dataset to verify that it is in the correct format?

If the dataset itself looks okay, this could also be an issue with how the dataset is being read by YOLOv5. Have you modified the `data.yaml` or any of the `.yaml` files in the `./data` directory in any way?

We appreciate your willingness to submit a PR. Before submitting, please make sure you are able to reproduce the error with a minimal example, preferably using one of the demo datasets from the YOLOv5 repository. This will help us verify that the issue is with the YOLOv5 code and not with the dataset itself.

Best of luck and please let us know if you have any further questions or information that could help us track down the issue!

**Comment by device-4** [comment]
I've solved that problem,my data.yaml file format is incorrect,thank u very much!

**Comment by glenn-jocher** [comment]
@device-4 glad to hear that your issue is resolved! We're always here to help if you encounter any more issues in the future.
Have a great day!
