### ISSUE TITLE
training with custom dataset: wrong class detected

### ISSUE THREAD

**Issue by roroloveorea** [ultralytics/yolov5#11467]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train a bear detection model using only the bear images and bbox from coco dataset. 
format of the bbox is smth like that:

0 0.5012201365187713 0.54809375 0.9975597269624574 0.8811562500000001

training seems ok
I've changed the nc to nc:1

but when I am detecting, all the bears are labelled as "person"

how can I fix this to make the detection label them as bears?

this is my yaml data file:
path: ./
train: train.txt  # train images (relative to 'path') 118287 images
val: val.txt  # val images (relative to 'path') 5000 images
test: test.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794
nc: 1
# Classes
names:
  0: bear

### Additional

no

**Comment by glenn-jocher** [comment]
@roroloveorea hello! Thank you for your question. 

The issue may be caused by YOLOv5 not being able to detect bears properly because the model was produced using the COCO dataset which doesn't have a "bear" class label. One way to solve this is to train the YOLOv5 model using the images and bounding boxes from COCO, but add the "bear" label as a new class. 

You have already done this by adding the class label "bear" in your YAML file. However, it's important to ensure that you have annotated the images correctly with the new "bear" class label and that the annotations match the format specified in the YAML file.

If you have already made sure that these requirements are met, it may be beneficial to verify your model by visualizing the predictions on a few images by using `--view-imgs` flag in the detect.py script to see if the bear class is being detected correctly. 

Additionally, you may need to adjust the confidence threshold in order to achieve better detection results. You can do this by adjusting the `--conf` flag in the detect.py script. 

I hope this helps! Let me know if you have any other questions.

**Comment by roroloveorea** [comment]
Thank You!

**Comment by glenn-jocher** [comment]
Hello @roroloveorea,

Thank you for your question. One possible reason why YOLOv5 is not detecting bears correctly is because the COCO dataset doesn't include a "bear" class label. You have done the correct step by adding the "bear" label as a new class in your YAML file. It is also important to ensure that your images were annotated correctly, and that the annotations match the format specified in the YAML file. 

To verify the model, you may want to visualize the detection results on a few images using the `--view-imgs` flag in the detect.py script. You can also adjust the confidence threshold by using the `--conf` flag to optimize the detection results.

I hope this helps. If you have any other questions, feel free to ask.
