### ISSUE TITLE
I successfully exported model.pt to TensorRT, but why is the runtime usage of TensorRT slower than using .pt?

### ISSUE THREAD

**Issue by anhquyetnguyen** [ultralytics/yolov5#11478]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I successfully exported model.pt to TensorRT, but why is the runtime usage of TensorRT slower than using .pt?

**Comment by glenn-jocher** [comment]
@anhquyetnguyen hello,

We're glad to hear that you have successfully exported your model.pt to TensorRT using YOLOv5.

Regarding your question, TensorRT generally runs faster than PyTorch because it optimizes the neural network specifically for your GPU. However, it's possible that your TensorRT implementation may not be optimized or configured correctly. 

We recommend that you check your TensorRT version, ensure that it's properly set up and configured with your GPU, and use TensorRT benchmarking tools to identify bottlenecks or performance issues.

Feel free to share more information or code snippets related to your use case, so that we can provide more specific help.

Best regards!

**Comment by anhquyetnguyen** [comment]
@glenn-jocher Thank you for your response 
What version do you recommend? I have tried several versions of TensorRT, but they run slower when inferring from the PT file. Could you provide some information about the CUDA, cuDNN, TensorRT, and NVIDIA TensorRT versions? I am using your source code to train, export, and infer

**Comment by glenn-jocher** [comment]
Hello @anhquyetnguyen, 

Thanks for getting back to me. Since the performance of your TensorRT implementation is slower than using PT file, I recommend you to check your hardware drivers and make sure they are updated to the latest version. 
Regarding the version of TensorRT, CUDA, cuDNN, and NVIDIA TensorRT, it depends on the configurations of your hardware and software. For further assistance, please provide more details of your computer hardware specifications, including GPU type, and software specifications such as the operating system, PyTorch version, CUDA version, and cuDNN version.

Looking forward to hearing back from you with more details!

**Comment by anhquyetnguyen** [comment]
hi @glenn-jocher 
ubuntu 18.04
Nvidia Tesla T4 16GB
cuda: 11.3
cudnn: 8.x
torch. 1.13.1

**Comment by glenn-jocher** [comment]
Hello @anhquyetnguyen,
Thanks for providing the specifications of your hardware and software configurations. You seem to have an Nvidia Tesla T4 with 16GB memory, and CUDA 11.3, and cuDNN 8.x installed. However, you mentioned that YOLOv5's TensorRT implementation running slower than using PT file. 
Since you're using PyTorch 1.3.1, I encourage you to update your PyTorch version to the latest version to ensure that your system is compatible with the latest TensorRT version. 
Additionally, you may want to check the version compatibility table of TensorRT with CUDA and cuDNN on the Nvidia website to ensure that the versions you have installed are compatible with each other and your hardware.
I hope this helps, please let me know if you have any further questions!

**Comment by Shahji55** [comment]
Hi @glenn-jocher,
I'm encountering a similar issue. I trained a yolov5s model on a custom dataset and converted the .pt weight to TensorRT (fp16 precision) using the repo's export.py script. I used a custom Docker for running the export.py script and then used the same Docker to perform video inference on a Windows machine using both .pt and .engine weights.

OS: Windows 10 64-bit
Cuda: 11.1
Pytorch: 1.8.2
GPU: Nvidia GTX 1650 - 4 GB
TensorRT version: 7.2.3.4

While processing the video I get less FPS with the .engine weight as compared to the .pt weight.

However, when I use the same Docker to process the video on a Ubuntu (18.04 64 bit) machine with a Geforce RTX 2080Ti - 11GB GPU, I get more FPS with the .engine weight as compared to the .pt weight.

Do you have any insights as to why this might be? Thank you.

**Comment by glenn-jocher** [comment]
Hello @Shahji55,

Thank you for your question. Based on your description, it appears that TensorRT performs slower than using .pt weights when processing video inferences on a Windows machine with Nvidia GTX 1650, while on a Ubuntu (18.04 64 bit) machine with a Geforce RTX 2080Ti, you observed the opposite behavior.

There could be many reasons for this behavior, such as the version of TensorRT and the driver used on the Windows machine might not be set up correctly, or the configuration of your Docker container may not be optimized for the Windows environment. To resolve this issue, we would recommend the following steps:

- Check if TensorRT and the driver are installed correctly on your Windows machine and update them to the latest version if possible.
- Ensure that the environment and configuration of your Docker container are optimized for your Windows machine, including the configuration of the Docker runtime with the Nvidia runtime for GPU acceleration.
- To avoid CUDA version mismatch between different platforms, you may want to have the same environment, including TensorRT and CUDA version, on both machines.

Please give these steps a try and let us know if they help resolve the issue. Feel free to let us know if you have any further queries!
