### ISSUE TITLE
No detection for a .mlmodel with detect.py

### ISSUE THREAD

**Issue by Larvouu** [ultralytics/yolov5#11484]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hello, i have successfully exported my model to the .mlmodel format. However, the performances on my iPhone are quite poor (but still working).
I have tried to use detect.py to see if the problem comes from my model or from the implementation of the model in my app. 
I got not a single detection from it even if I put --conf-thres 0.01 (see the screenshot). I tried detect.py with my best.pt of the same train and it works perfectly fine.

Any clue on this one ?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/37505516/236175535-94d92187-4b24-4192-9ddf-afd01fe10ed1.png">

### Environment

YOLOv5n 
Python-3.10.9 torch-2.0.0 CPU
Mac OS 13.2.1

### Minimal Reproducible Example

python detect.py --weights best_ober.mlmodel --source ./data/images/ --conf-thres 0.01 --img 320

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Larvouu hello! Thank you for reaching out to us regarding YOLOv5. It's great to hear that you were able to export your model successfully. 

Poor performance on mobile devices could be due to various reasons such as hardware limitations, suboptimal implementation of the model on the device, or even model architecture choices that might be computationally heavy. 

In regards to your issue with `detect.py`, if you were able to get successful detections using `best.pt` but not using your exported `.mlmodel`, this could suggest that there could be a problem with how you exported the model to that format or that the model architecture might not be compatible with Core ML.

With the current information provided, it might be hard to give a pinpoint solution. However, here are some things you could check for:

- Make sure the model was exported correctly without any errors. Sometimes, the export process might not be completely successful and could result in a corrupted or suboptimal model.
- Verify if the model architecture you have used is compatible with Core ML requirements.
- Check if the input and output layers of your exported `.mlmodel` are set correctly. They have to be compatible with the Core ML model format.
- Confirm that the version of the Core ML framework that is being used is compatible with the exported model.

I hope this helps! Let us know if you have any further questions or need additional assistance.

**Comment by Larvouu** [comment]
@glenn-jocher To bring more information, I tried with two different **export.py**.

For the first one, I use this command : 
**python export_iphone.py --weights new_yolov5/runs/train/exp16_ober/weights/best.pt --train  --img 320**

This one is from an old **export.py** (I think the parameter **--train** doesn't exist anymore in the recent **detect.py**).
Here is what I get from the console : 

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/37505516/236215648-ccd5157f-d375-44ac-ab89-7b0c2cf2bee2.png">
 
And this is the model I get :

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/37505516/236215993-5f56c41d-f946-4882-b30d-bfb75d8e1147.png">

This is the model I tried with **detect.py** and got no detection (but no error).


I then thought that maybe it was because I used an old **export.py** and that the structure of my model wasn't right. So I tried with the most recent **export.py** on the same **best.pt** using this command:
**python export.py --weights runs/train/exp16_ober/weights/best.pt --include coreml --img 320**

This is what I get from the console: 

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/37505516/236217450-9ca66516-bf3b-4697-a4fa-7d774d9246b1.png">


Everything seems to went smoothly and I got no error. 
But then I tried **detect.py** on this **.mlmodel** and got this unexpected error : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37505516/236217901-a6eaaad4-0953-42bb-975c-1f0eba602510.png">

I tried to look for a solution but didn't find anything related at all. 
In addition I didn't find a way to implement this model into an app as its structure is different from the other one. 
Here is the structure of it using the latest yolov5 pull and so the latest **export.py**:

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/37505516/236218722-88b971be-8330-46f5-911f-204ee4e1c090.png">

I also looked the default **yolov5n.mlmodel** in the official documentation and it also has a different structure that my two other ones. 
I'm really confused right now and I can't really see what I can do to know what structure of **mlmodel** is the good one and how to implement it in my app and why I can't manage to try them with **detect.py**.

Thank you and sorry for the long answer, I tried to bring as much information as possible

**Comment by glenn-jocher** [comment]
Hello @Larvouu! Thank you for providing a detailed explanation of the issue you are facing while trying to use your exported ML model with `detect.py`. Based on the information you have provided, it seems like the exported ML model might not be in a format that is compatible with Core ML.

To ensure that the exported model has been successfully converted to the Core ML format, you can follow these steps: 

- Load the `.mlmodel` file in Xcode and inspect the input and output formats of the layers. 
- Check if the input and output formats are compatible with the formats used by the `detect.py` script. 
- Verify that the model architecture used in the export process is compatible with the Core ML framework. 

To make it easier to integrate your model into your app, you can use a mobile deep learning framework that is compatible with Apple devices, such as Core ML. 

Regarding the differences in model structure between the exported models, it's important to note that the structure of an exported model depends on the export script being used. We recommend using the most recent version of the export script to ensure compatibility with the latest version of YOLOv5.

I hope this information helps! Please let us know if you have any further questions or need additional assistance.
