### ISSUE TITLE
Update train.py to save and load only the model parameters

### ISSUE THREAD

**Issue by mmenbawy** [ultralytics/yolov5#1149]
## 🚀 Feature

Update train.py to save only the state dicts and not whole model objects.

## Motivation

It's extremely frustrating to retrain the model to produce a new set of weights and then find up that the weights can not be used in a different directory structure.
https://github.com/ultralytics/yolov5/issues/22
and per https://github.com/pytorch/pytorch/issues/3678 torch recommends saving only the state dicts and not whole model objects to avoid having serialized data bound to the specific classes and the exact directory structure used.

## Pitch

Change https://github.com/ultralytics/yolov5/blob/c67e72200e8b5caab6b2b2fa560cdb647b46f004/train.py#L353
to `torch.save(ckpt.state_dict(), last)`

**Comment by glenn-jocher** [comment]
@Mostafa-Elmenbawy yes, I understand, thanks for the feedback. 

We saved separate weights and cfg files in our older https://github.com/ultralytics/yolov3 repo, but we saw that this generated confusion among users, who would inadvertently attempt to pair incompatible cfg and weights files, and of course also added complications when exporting, since two arguments were required rather than one whenever a model needed to be specified.

So with YOLOv5 we created simplified standalone models that are self contained with all info required (config, weights, anchors, class names, etc.). Inference with yolov3 for example requires you to pass the --cfg, the --weights, and the --names. YOLOv5 inference requires only --weights, an argument reduction of 3x.

The easiest way to use YOLOv5 independent of this repo is PyTorch Hub. See https://docs.ultralytics.com/yolov5

**Comment by glenn-jocher** [comment]
@Mostafa-Elmenbawy see https://github.com/ultralytics/yolov5/pull/1153#issuecomment-709512324 for our awesome new standalone YOLOv5 functionality. 

You pass in a PIL image, you get out detections, everything handled automatically, and no dependency on cloning the ultralytics/yolov5 repo.

**Comment by Sagor-Saha** [comment]
@Mostafa-Elmenbawy you saved the state_dict of the model while training. How to load the model during prediction of images? Code?
