### ISSUE TITLE
Inconsistent inference time

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#11510]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi all! I am facing inconsistent inference times.

I am on windows, and running the inference on CPU. 

The inference time is always 84/85 ms for lets say 30 pictures straight.. then there are 1 or 2 that take 125ms or even more. and then it goes back again to the usual 84 ms. its not picture related as the same picture takes 84 ms if run again. 

any idea on what might be causing these inconsistencies? 
there are no other programs using the cpu, just the OS. 

Thank you 

Best regards

------------ EDIT --------------

it is this line that has that variable time: 

pred = model(im, augment=False, visualize=False)

**Comment by glenn-jocher** [comment]
@MasIgor hi,

Inconsistency in inference time can be due to many factors like hardware performance, memory, CPU usage, and so on. 

Our recommendation would be to profile the inference execution and check where is it spending more time. You can use python's built-in `cProfile` library to profile the inference execution and `pstats` for the analysis. 

Another suggestion could be to try running the inference on GPU or a Linux machine (if possible) and see if the inconsistency is still there.

Let us know if this helps.

Best.
