### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [255, 128, 1, 1], but got 5-dimensional input of size [8, 3, 80, 80, 85] instead

### ISSUE THREAD

**Issue by Hukongtao** [ultralytics/yolov5#1151]
I want to know what the output of the network is， so I run
python yolo.py
Of course I added the following two sentences
img = torch.rand(8 if torch.cuda.is_available() else 1, 3, 640, 640).to(device)
y = model(img, profile=True)
but I got an error

**Comment by glenn-jocher** [comment]
Do not use a bug report for questions. `$ python models/yolo.py` executes correctly.

<img width="1545" alt="Screenshot 2020-10-15 at 17 52 31" src="https://user-images.githubusercontent.com/26833433/96154568-40249f00-0f0f-11eb-997c-e1b1776e476a.png">

**Comment by Pluto1314** [comment]
@glenn-jocher Hi, I got a same error.
![图片](https://user-images.githubusercontent.com/47765770/97431356-23e42180-1955-11eb-997f-91f65552b86c.png)

**Comment by glenn-jocher** [comment]
@Pluto1314 yolo.py is not intended for running. I don't know what you are seeking to do, but would recommend viewing all tutorials in README:
https://docs.ultralytics.com/yolov5

This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a new `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible with [COCO](https://cocodataset.org/#home) or [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, ensure your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Pluto1314** [comment]
@glenn-jocher Yes, all my environment are based on the README, I just want to calculate FLOPS.

**Comment by glenn-jocher** [comment]
@Pluto1314 FLOPS are automatically displayed when the `thop` package is installed. No modifications to the code are required. See requirements.txt

**Comment by Pluto1314** [comment]
@glenn-jocher Thanks.

**Comment by murphypei** [comment]
the code of profile in yolo.py results in the problem:
```py
img = torch.rand(8 if torch.cuda.is_available() else 1, 3, 640, 640).to(device)
y = model(img, profile=True)
```

**Comment by glenn-jocher** [comment]
@murphypei if you want the run the model in `profile=True` mode there is a small manual step you need to take. Please uncomment L44 in the Detect() forward function:
https://github.com/ultralytics/yolov5/blob/e92245a38c90be884a05cb1e3fe325037b9f1379/models/yolo.py#L43-L44

**Comment by murphypei** [comment]
> ent L44 in the Detect() forward func

Thank you, this is my mistake.

**Comment by murphypei** [comment]
> @murphypei if you want the run the model in `profile=True` mode there is a small manual step you need to take. Please uncomment L44 in the Detect() forward function:
> https://github.com/ultralytics/yolov5/blob/e92245a38c90be884a05cb1e3fe325037b9f1379/models/yolo.py#L43-L44

Thank you, this is my mistake.

**Comment by murphypei** [comment]
@glenn-jocher Thank you, this is my mistake.
