### ISSUE TITLE
 i need to run multiple object detection models(yolo) on single video (model running should be simultaneously ) and output shall also be in single video.

### ISSUE THREAD

**Issue by mkuntal4015** [ultralytics/yolov5#11521]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have problem where i need to run multiple object detection models(yolo) on single video and output shall also be in single video .Performance should be close to real time. Database can not be merged. model running should be simultaneously .How can i solved this problem.

**Comment by glenn-jocher** [comment]
@mkuntal4015 hello!

To run multiple object detection models on a single video and output it into a single video, you can leverage multiprocessing in Python. You can have each model run simultaneously on a separate process and merge the output frames using OpenCV. This way, you can achieve a close to real-time performance and have the models run separately.

You can check out the Python `multiprocessing` library and `OpenCV` for more information on how to implement this. Feel free to let us know if you have any further questions!

Best regards.

**Comment by jaswanth1507** [comment]
@mkuntal4015 Hey

In order to get multiple outputs on one video several steps are required:
1.Split the video into smaller segments using ffmpeg or any similar application.
2.Create a pipeline for each model
3.Run each model for which you want to perform identification for on separate threads using parallel processing
4.Combine the segments of the videos based on any metric, for example, timestamps
5.Merge the smaller segments of the video into a larger one using ffmpeg
6.Once the frames are merged, you will need to encode the video to create the final output. Utilize the video encoding capabilities of ffmpeg.

This should provide you with a method to detect and display multiple objects on the same video.
For more information check out FFmpeg, OpenCV and multiprocessing.

**Comment by glenn-jocher** [comment]
Hello @jaswanth1507,

To get multiple outputs on one video, you can follow these steps:

1. Split the video into smaller segments using a tool like ffmpeg
2. Create a pipeline for each model
3. Run each model on a separate thread using parallel processing
4. Combine the segments of the video based on timestamps or any other metric
5. Merge the smaller video segments into a larger one using ffmpeg
6. Encode the video to create the final output using ffmpeg's video encoding capabilities.

These steps should help you detect and display multiple objects on the same video. For more information and guidance, you can check out FFmpeg, OpenCV, and multiprocessing.

If you have any further questions or need more help, feel free to ask.

Thank you and have a good day!
