### ISSUE TITLE
detect.py with Redis

### ISSUE THREAD

**Issue by waseemR02** [ultralytics/yolov5#11549]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

So as far as I understand, when we pass the index for device to `detect.py`, it calls `LoadStreams()` from `dataloaders.py`. This returns *sources,images with transforms/resizes, original images, video_cap, s*. The *images* list is updated in a separate thread and the `__next__`method performs the resizes and returns. So now I need help with the modification the `detect.py`. I'm working with **Realsense D435i**, and for obvious reasons I can't simply run `detect.py` on the camera when it is busy with `librealsense` sdk. 
My plan was to use **redis** to share frames in memory. I have already have the sdk ready which updates the frames in bytes in a queue of 5. Now all i need to modify is the detect.py to take the frames(after converting it to proper format from bytes) and perform inference. Any help would be really appreciated.
One other thing i thought of was to create a separate script all together and use `pytorch.model.load()`  to pass the frames to infer, but that removes all the other things i can do with `detect.py`

**Comment by glenn-jocher** [comment]
@waseemR02 hi there!

It sounds like you have an interesting use case for YOLOv5 and it's great that you are exploring different options to integrate it with your Realsense D435i camera. Modifying `detect.py` to take frames from Redis should be possible, but it may require some restructuring of the code.

One approach could be to modify `LoadStreams()` to read from Redis instead of the camera stream, and then pass the received frames to the detection pipeline. This may require some changes to the image resizing and transformations depending on the format of the Redis frames. 

Alternatively, you could create a separate script to interface with Redis, preprocess the frames, and then pass them to the YOLOv5 model using `pytorch.model.load()`. This may be simpler to implement, but may not offer all the functionality of `detect.py`.

I hope this helps and good luck with your project!
