### ISSUE TITLE
AssertionError: input size torch.Size([1, 3, 1280, 960]) not equal to max model size (1, 3, 1280, 1280)

### ISSUE THREAD

**Issue by qianqiuRex** [ultralytics/yolov5#11541]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I train a yolov5s model which used the input size of 1280.Then export to tensorrt engine by "python export.py --include engine --weights /home/rex/projects/yolov5/weights1280/best.pt --img 1280 --device 0 "
When I run the following code, 
     model = torch.hub.load('.', 'custom', 'weights1280/best.engine', source='local')
     image = cv2.imread('data/images/bus.jpg')[..., ::-1]
     results = model(image, size=1280)
I get an error
    AssertionError: input size torch.Size([1, 3, 1280, 960]) not equal to max model size (1, 3, 1280, 1280)

**Comment by glenn-jocher** [comment]
@qianqiuRex hello! Thank you for reaching out.

I believe the error you are encountering is due to a mismatch between the input size and the size of the model.

As you have mentioned, you trained a YOLOv5s model using an input size of 1280. However, when you exported it to a TensorRT engine, you set the `--img` parameter to 1280 instead of the expected 1280x1280.

This has resulted in the engine expecting an input size of (1, 3, 1280, 1280) while you are providing the model with an input size of (1, 3, 1280, 960), hence the error.

I hope this solves your issue! Feel free to reach out if you have any further questions.

**Comment by harryc7** [comment]
> @qianqiuRex hello! Thank you for reaching out.
> 
> I believe the error you are encountering is due to a mismatch between the input size and the size of the model.
> 
> As you have mentioned, you trained a YOLOv5s model using an input size of 1280. However, when you exported it to a TensorRT engine, you set the `--img` parameter to 1280 instead of the expected 1280x1280.
> 
> This has resulted in the engine expecting an input size of (1, 3, 1280, 1280) while you are providing the model with an input size of (1, 3, 1280, 960), hence the error.
> 
> I hope this solves your issue! Feel free to reach out if you have any further questions.

so，how to deal with it？

**Comment by glenn-jocher** [comment]
@harryc7, thank you for following up! To resolve the error, please export your YOLOv5s model again to TensorRT engine using the correct size. You can do this by setting the `--img` parameter to 1280x1280 instead of just 1280. This way, the engine will expect an input size of (1, 3, 1280, 1280) which matches the size of your model.

After exporting the model with the correct input size, you should be able to run it without encountering the error that you previously encountered. Please let me know if you have any other questions or concerns.

**Comment by harryc7** [comment]
> @harryc7, thank you for following up! To resolve the error, please export your YOLOv5s model again to TensorRT engine using the correct size. You can do this by setting the `--img` parameter to 1280x1280 instead of just 1280. This way, the engine will expect an input size of (1, 3, 1280, 1280) which matches the size of your model.
> 
> After exporting the model with the correct input size, you should be able to run it without encountering the error that you previously encountered. Please let me know if you have any other questions or concerns.

@glenn-jocher thank you for your reply.  Another problem I have is when I trained a YOLOv5s model using an input size of 640x640 and exported it to TensorRT engine using the  same size,  I get the following error when I detect the video(1920x1080) by TensorRT engine.  However, when I exported my  YOLOv5s model to TensorRT engine using the size of 608x1088, the program did not report an error. How to explain and solve this problem?
`  File "F:\Anaconda3\envs\pytorch-y\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dL\wh\yolov5\models\common.py", line 424, in forward
    assert im.shape == self.bindings['images'].shape, (im.shape, self.bindings['images'].shape)
AssertionError: (torch.Size([1, 3, 384, 640]), (1, 3, 640, 640))
`
Python 3.8
CUDA 11.6
cuDNN 8.4
TensorRT 8.4.1.5
Windows 10

**Comment by glenn-jocher** [comment]
@harryc7, thank you for providing these additional details. 

It seems that, in this case, the issue is related to the aspect ratio of your input images. Your video has an aspect ratio of 16:9 (1920x1080), while your YOLOv5s model was trained using an input size of 640x640 which has an aspect ratio of 1:1. This difference in aspect ratio causes the error you are encountering when detecting the video using the TensorRT engine.

One possible solution is to modify the input size of your YOLOv5s model during export to match the aspect ratio of your input data. For example, you could use an input size of 608x1088 which has the same aspect ratio as 1920x1080. 

If this solution does not work for you, please let me know and we can continue to troubleshoot the issue.

**Comment by harryc7** [comment]
> @harryc7，感谢您提供这些额外的详细信息。
> 
> 在这种情况下，问题似乎与输入图像的纵横比有关。您的视频的纵横比为 16:9 (1920x1080)，而您的 YOLOv5s 模型使用 640x640 的输入尺寸进行训练，纵横比为 1:1。这种宽高比差异会导致您在使用 TensorRT 引擎检测视频时遇到错误。
> 
> 一种可能的解决方案是在导出期间修改 YOLOv5s 模型的输入大小，以匹配输入数据的纵横比。例如，您可以使用 608x1088 的输入尺寸，其纵横比与 1920x1080 相同。
> 
> 如果此解决方案对您不起作用，请告诉我们，我们可以继续解决问题。

@glenn-jocher Thanks! I will try it.

**Comment by glenn-jocher** [comment]
@harryc7 you're welcome! Please let us know if this solution works for you. It's important to ensure that the input size of your YOLOv5s model matches the aspect ratio of your input data in order to avoid errors. If you continue to encounter issues, please don't hesitate to reach out to us for further assistance.

**Comment by fatemeh-mohseni-AI** [comment]
i had similar issue . 

this is how i export my model :
>> model.export(format='engine', half=True, int8=True, imgsz=(320, 320))

and this was how i used the model: 
>> results = self.model.track(
            source=cv_image,
            conf=self.conf_thres,
            iou=self.iou_thres,
            max_det=self.max_det,
            classes=self.classes,
            tracker=self.tracker,
            device=self.device,
            verbose=False,
            retina_masks=True,
)

in my case , adding imgsz=320 to result solved my issue  . 

the final code was : 

>> results = self.model.track(
            source=cv_image,
            conf=self.conf_thres,
            iou=self.iou_thres,
            max_det=self.max_det,
            classes=self.classes,
            tracker=self.tracker,
            device=self.device,
            verbose=False,
            retina_masks=True,
            imgsz=320
        )

**Comment by kanis777** [comment]
@glenn-jocher .I tried to understand how the layers input and output channels work and for that i added print statements to the classes c2f and conv in blocks.py and conv.py . After that i ran a py file to check model info 

modified conv class (with print stmts) in conv.py:

```
class Conv(nn.Module):
    """Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)."""

    default_act = nn.SiLU()  # default activation

    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=True):
        """Initialize Conv layer with given arguments including activation."""
        super().__init__()
        # Print input and output channels and other parameters
        print(f"Conv Initializing Conv layer: c1={c1}, c2={c2}, kernel={k}, stride={s}, padding={p}, groups={g}, dilation={d}")
        
        # Initialize the convolutional layer
        self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p, d), groups=g, dilation=d, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        # Set the activation function
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        """Apply convolution, batch normalization and activation to input tensor."""
        print(f"Conv Input shape: {x.shape}")  # Print the shape of the input tensor
        x = self.conv(x)
        print(f"Conv After Conv: {x.shape}")  # Print the shape after convolution
        x = self.bn(x)
        print(f"Conv After BatchNorm: {x.shape}")  # Print the shape after batch normalization
        x = self.act(x)
        print(f"Conv After Activation: {x.shape}")  # Print the shape after activation
        return x

    def forward_fuse(self, x):
        """Perform transposed convolution of 2D data."""
        print(f"Conv Input shape (forward_fuse): {x.shape}")  # Print the shape of the input tensor
        x = self.conv(x)
        print(f"Conv After Conv (forward_fuse): {x.shape}")  # Print the shape after convolution
        x = self.act(x)
        print(f"Conv After Activation (forward_fuse): {x.shape}")  # Print the shape after activation
        return x
```
