### ISSUE TITLE
cannot load .engine generated by deepstream

### ISSUE THREAD

**Issue by 13randNEW** [ultralytics/yolov5#11564]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I encountered `KeyError: 'images'` when I tried to use .engine file generated by deepstream-app. Could you help me with this?
```
python3 detect.py --source 4 --weights yolov5s.engine --device 0

detect: weights=['yolov5s.engine'], source=4, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 2022-11-22 Python-3.8.10 torch-1.12.0a0+2c916ef.nv22.3 CUDA:0 (Orin, 62795MiB)

Loading yolov5s.engine for TensorRT inference...
[05/21/2023-23:10:30] [TRT] [I] Loaded engine size: 28 MiB
[05/21/2023-23:10:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +27, now: CPU 0, GPU 27 (MiB)
[05/21/2023-23:10:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +144, now: CPU 0, GPU 171 (MiB)
Traceback (most recent call last):
  File "detect.py", line 259, in <module>
    main(opt)
  File "detect.py", line 254, in main
    run(**vars(opt))
  File "/home/rg-orin0/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 96, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/home/rg-orin0/workspaces/yolov5-7.0/models/common.py", line 419, in __init__
    batch_size = bindings['images'].shape[0]  # if dynamic, this is instead max batch size
KeyError: 'images'

```
Platform info:
Jetson AGX Orin
Jetpack 5.1.1
CUDA 11.4
TensorRT 8.5.2

### Environment

YOLOv5 
Jetson AGX Orin
Jetpack 5.1.1
Python 3.8.10
CUDA 11.4
TensorRT 8.5.2
Torch  1.12.0a0+2c916ef.nv22.3

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@13randNEW hello! It looks like there is a KeyError in the detect.py script when trying to load the .engine file generated by deepstream-app. The error message mentions that there is no key named 'images' in the bindings dictionary which is why the KeyError is raised.

Without more context, it is hard to say exactly what is causing this issue. However, it is possible that the .engine file was not generated correctly by deepstream-app. You may want to try regenerating the .engine file again from the source code and see if that resolves the issue.

Alternatively, you may want to check that the .yaml file for the data and the .weights file for the model are correctly specified and located in the correct directories.

Please let us know if you have any further questions or if there is anything else we can assist you with.

**Comment by mztony** [comment]
i also have the same problem, did u solve it later?

> ### Search before asking
> 
>     * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.
> 
> 
> ### YOLOv5 Component
> 
> _No response_
> ### Bug
> 
> Hi, I encountered `KeyError: 'images'` when I tried to use .engine file generated by deepstream-app. Could you help me with this?
> 
> ```
> python3 detect.py --source 4 --weights yolov5s.engine --device 0
> 
> detect: weights=['yolov5s.engine'], source=4, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
> YOLOv5 🚀 2022-11-22 Python-3.8.10 torch-1.12.0a0+2c916ef.nv22.3 CUDA:0 (Orin, 62795MiB)
> 
> Loading yolov5s.engine for TensorRT inference...
> [05/21/2023-23:10:30] [TRT] [I] Loaded engine size: 28 MiB
> [05/21/2023-23:10:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +27, now: CPU 0, GPU 27 (MiB)
> [05/21/2023-23:10:30] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +144, now: CPU 0, GPU 171 (MiB)
> Traceback (most recent call last):
>   File "detect.py", line 259, in <module>
>     main(opt)
>   File "detect.py", line 254, in main
>     run(**vars(opt))
>   File "/home/rg-orin0/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "detect.py", line 96, in run
>     model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
>   File "/home/rg-orin0/workspaces/yolov5-7.0/models/common.py", line 419, in __init__
>     batch_size = bindings['images'].shape[0]  # if dynamic, this is instead max batch size
> KeyError: 'images'
> ```
> 
> Platform info: Jetson AGX Orin Jetpack 5.1.1 CUDA 11.4 TensorRT 8.5.2
> ### Environment
> 
> YOLOv5 Jetson AGX Orin Jetpack 5.1.1 Python 3.8.10 CUDA 11.4 TensorRT 8.5.2 Torch 1.12.0a0+2c916ef.nv22.3
> ### Minimal Reproducible Example
> 
> _No response_
> ### Additional
> 
> _No response_
> ### Are you willing to submit a PR?
> 
>     * [ ]  Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mztony i apologize for the inconvenience you're experiencing. The `KeyError: 'images'` issue you encountered is likely due to an error in the process of generating the .engine file using deepstream-app.

To resolve this issue, I recommend checking the following:

1. Ensure that the .yaml file for the data and the .weights file for the model are correctly specified and located in the appropriate directories.
2. Verify that you have generated the .engine file using deepstream-app correctly. It's possible that there was an error during the process, so you may want to regenerate the .engine file from the source code.
3. Double-check that the necessary dependencies, such as CUDA and TensorRT versions, are correctly installed and compatible with YOLOv5.

If the issue persists after following these steps, please provide more information or code snippets that could help in diagnosing and resolving the problem.

Thank you for using YOLOv5, and please don't hesitate to ask if you have any further questions or concerns.

**Comment by wolfworkpc33** [comment]
![Screenshot from 2023-11-29 09-59-41](https://github.com/ultralytics/yolov5/assets/101696046/774143ca-eab9-46d2-a7e6-fcff21aa49b8)

**Comment by wolfworkpc33** [comment]
Any one can help me?

**Comment by glenn-jocher** [comment]
@wolfworkpc33 i'd be happy to help you with that! From the screenshot you provided, it seems like you are encountering an error related to the 'KeyError: 'images'' when using the .engine file generated by deepstream-app.

As mentioned in my previous responses, this issue is likely related to the .engine file generation process or the configuration of the YOLOv5 setup on your system. I recommend checking the points mentioned earlier and ensuring that the relevant files and dependencies are correctly set up.

If you have any specific code snippets, error messages, or additional details that you can share, it would be very helpful in diagnosing and resolving the problem.

Thank you for reaching out, and we are here to assist you further!
