### ISSUE TITLE
No results printed for each epoch

### ISSUE THREAD

**Issue by chenyutian0822** [ultralytics/yolov5#11579]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello @glenn-jocher, when m training yolov5-v6.2 with yolov5m.yaml ,  i can see the train is working, but after each epoch i couldn't get any validation output print on the screen, yet i can see mAP in the results.csv after training, i have no idea what went wrong, could you please help it out, many thanx !
 
![2023-05-23 195021](https://github.com/ultralytics/yolov5/assets/49404778/c2c16858-741a-4f50-a1c8-5d1c1a6d7fd4)

![2023-05-23 195917](https://github.com/ultralytics/yolov5/assets/49404778/2dc39df3-bc44-4e70-a396-4e3a68bb8931)

### Environment

-YOLOV5-V6.2 torch 1.13.1+cu11.7 CUDA:0
(RTX2080ti, 11264MiB)
-OS: Ubuntu 22.04.2
-Python: 3.9.16

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @chenyutian0822, I'm glad to hear that you're training YOLOv5-v6.2 with yolov5m.yaml. Based on what you mentioned, it seems like you're not getting any validation output print on the screen after each epoch, but you can see mAP in the results.csv after training. 

There is nothing to worry about as it's an expected behavior. The current version of YOLOv5 does not print validation results to the console during training. As you mentioned, you can see the mAP in the results.csv after training, which confirms that validation is occurring. 

If you're interested in seeing validation results during training, you can modify the training script to print validation results. 

Please let me know if you have any further questions or concerns.

**Comment by chenyutian0822** [comment]
Thank you  @glenn-jocher, i will check it out and see if i can modify the code to print out.

**Comment by glenn-jocher** [comment]
You're welcome @chenyutian0822! I'm glad to hear that my response was helpful. 

Please feel free to reach out to us if you need any further assistance. We are always happy to help.

**Comment by chenyutian0822** [comment]
Hi @glenn-jocher, just wanna let you know the problem is solved now. the set_logging var "name" was empty in original code that the logging function was not working properly, set the name as below that all log info will be printed.

Just in case someone one has the same problem that they can fix it by it.
Thank you for your reply!

![2023-05-24 145037](https://github.com/ultralytics/yolov5/assets/49404778/b882f79d-b7d1-457a-b8b7-a522ecf88261)




![2023-05-24 145806](https://github.com/ultralytics/yolov5/assets/49404778/545aef75-4942-4cec-a309-6ff579a6de60)

**Comment by glenn-jocher** [comment]
That's great to hear, @chenyutian0822! Thank you for sharing the solution you found. Your contribution to the community is much appreciated.

If you have any other questions or need further assistance, feel free to reach out. Keep up the great work!
