### ISSUE TITLE
Why is MPS significantly slower than CPU?

### ISSUE THREAD

**Issue by stevemac00** [ultralytics/yolov5#11589]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**device='mps'**
image 1/2 yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 166.9ms
image 2/2 yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, 219.1ms

**device='cpu'**
image 1/2 yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 56.2ms
image 2/2 yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, 43.8ms

This is on Mac Studio M1 Max with idle cores.
torch.__version__ == 2.0.0
ultralytics.__version__ == 8.0.107

### Additional
Clarify title to detect.py inference
_No response_

**Comment by stevemac00** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> **device='mps'** image 1/2 yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 166.9ms image 2/2 yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, 219.1ms
> 
> **device='cpu'** image 1/2 yolov5/data/images/bus.jpg: 640x480 4 persons, 1 bus, 56.2ms image 2/2 yolov5/data/images/zidane.jpg: 384x640 2 persons, 2 ties, 43.8ms
> 
> This is on Mac Studio M1 Max with idle cores. torch.**version** == 2.0.0 ultralytics.**version** == 8.0.107
> 
> ### Additional
> Clarify title to detect.py inference _No response_
Interesting torch thread on this issue https://github.com/pytorch/pytorch/issues/77799

**Comment by glenn-jocher** [comment]
Hello @stevemac00, we appreciate your interest in YOLOv5 and apologies for any inconvenience you may be experiencing. The discrepancies that you are seeing in inference time between 'mps' and 'cpu' devices may be due to differences in the hardware architecture of each device, with the 'mps' device being optimized for machine learning tasks. However, the actual inference times may also depend on the individual task size, complexity and the model architecture being used.

We recommend trying to perform inference on a set of tasks with various sizes and complexities to understand the indications for the difference you are seeing. Also, thanks for sharing the referenced thread on the PyTorch issue, that is an interesting topic to follow along with.

Please let us know if you have any further questions or concerns.

**Comment by stevemac00** [comment]
Also https://discuss.pytorch.org/t/sequential-throughput-of-gpu-execution/156303

Obviously not directly related to yolov5.
Apparently it's the lack of mps optimization and thus on all mps related architecture. It's all over my head so I'll stick to device('cpu') for now.

**Comment by glenn-jocher** [comment]
Hello @stevemac00, thank you for reaching out and your interest in YOLOv5! It is unfortunate to hear of any issues faced, and we hope to provide some helpful information.

Based on the issue you have shared, it appears that with respect to running inference on certain architectures specifically MPS architecture, the YOLOv5 model seems to perform slower compared to CPU. This could be due to differences in the hardware architecture of each device, with the MPS device being optimized for machine learning tasks. However, this may also depend on the task size, complexity, and the model architecture being used. 

As you mentioned, it might be best to utilize the CPU device for inference, in case there are conflicting issues with the MPS device. We are sorry that you are experiencing these difficulties while using YOLOv5, and we hope that this information has been helpful. Let us know if there is anything else we can assist you with, we are always here to help.

**Comment by stevemac00** [comment]
Followup note. I did more extensive testing for my code* where I loop through many images on device='cpu' then same on device='mps' and the results surprised me.

I don't understand but guessing initial overhead with mps.
```
--------------------------
device:cpu, detectTime: 67.640ms, postTime: 11.518ms, totalTime: 79.159ms
device:mps, detectTime: 27.345ms, postTime: 11.341ms, totalTime: 38.686ms
--------------------------
```
I watched [asitop](https://github.com/tlkh/asitop) and swap inactive and memory stayed the same while gpu is inactive when running cpu and vice versa.

*`model(maskImage).pandas().xyxy[0].to_dict(orient="records")`

**Comment by glenn-jocher** [comment]
Hello @stevemac00, thank you for your interest in YOLOv5 and sharing your findings. We appreciate your feedback and glad to see that you have further tested this and found additional information.

As for the discrepancy in inference time between 'cpu' and 'mps' devices, it might be due to differences in the hardware architecture of each device, with the 'mps' device being optimized for machine learning tasks. However, these differences in inference time position may depend on the individual task sizes, model architecture used, and other factors as well.

Your findings seem to indicate that there might be an initialization overhead with the 'mps' device, but this would vary based on the specific task and architecture being used. Furthermore, the swap of inactive and memory staying the same while running on 'cpu' and 'mps' devices indicate a lack of sufficient data to make additional inferences.

Again, thank you for bringing this to our attention, and let us know if there is anything else we can assist you with.
