### ISSUE TITLE
Shouldn't the segmentation mask colors of different object instances of the same category be different?

### ISSUE THREAD

**Issue by superman-liu** [ultralytics/yolov5#11592]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

We learned that semantic segmentation only needs to distinguish different categories, and the instance masks of the same category are the same color. But instance segmentation not only needs to distinguish categories, but also needs to distinguish different objects of the same category, which requires visual masks of different colors for different objects of the same category. But in the 7.0 code, I found that the color of the mask is distinguished according to the category, and the colors of the same category are the same, which degenerates into semantic segmentation. How can I make different objects of the same category have different colors?

**Comment by glenn-jocher** [comment]
@superman-liu hello! Thank you for bringing up this question. 

You are correct that the current version of YOLOv5 assigns the same colors to instance masks of the same category, which is indeed similar to semantic segmentation. This is because the current focus of YOLOv5 is primarily object detection rather than instance segmentation. 

If you would like to have a visual mask that distinguishes different objects of the same category, you might consider looking into pytorch-segmentation-toolbox (PST), a separate image segmentation library that supports color-class segmentation. It offers a number of helpful features, including the ability to assign different colors to the same category.

Please let us know if you have any further questions or feedback!

**Comment by superman-liu** [comment]
Thanks for your reply, I will try to use it.


Thanks for your reply, I will try to use it

stone。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] Shouldn't the segmentation mask colors of different object instances of the same category be different? (Issue #11592)





 
@superman-liu hello! Thank you for bringing up this question.
 
You are correct that the current version of YOLOv5 assigns the same colors to instance masks of the same category, which is indeed similar to semantic segmentation. This is because the current focus of YOLOv5 is primarily object detection rather than instance segmentation.
 
If you would like to have a visual mask that distinguishes different objects of the same category, you might consider looking into pytorch-segmentation-toolbox (PST), a separate image segmentation library that supports color-class segmentation. It offers a number of helpful features, including the ability to assign different colors to the same category.
 
Please let us know if you have any further questions or feedback!

**Comment by glenn-jocher** [comment]
@superman-liu hi stone,

You're welcome! I'm glad I could help. If you need any further assistance, please don't hesitate to ask.

Best,
Glenn Jocher, Ultralytics YOLOv5
