### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by Amirhosein-mkh** [ultralytics/yolov5#11629]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello Dear. thanks for Yolov5.
I want to detections pedestrians in my dataset images on COCO pre-trained model. my images size =1280

But, When I use the command "python val.py --img 1280 --weights yolov5x.pt --data LLVIP.yaml" to evaluate my test data, I encounter the error in the picture below:

![Screenshot (246)](https://github.com/ultralytics/yolov5/assets/40248073/0bf6af1d-6af2-4b8c-ae9d-ca467d2ed2d1)

Screenshot of the details of the libraries I have installed (I am using "Python 3.8.8rc1" version ):

![Screenshot (247)](https://github.com/ultralytics/yolov5/assets/40248073/6586c98b-eb59-4a9b-a775-33796233f8da)

please help me 

### Additional

Detail image of LLVIP.yaml file :
![Screenshot (249)](https://github.com/ultralytics/yolov5/assets/40248073/06b2bbd1-b933-4e5e-8259-f8ffa546eacd)

**Comment by glenn-jocher** [comment]
@Amirhosein-mkh hello there!

Thank you for using YOLOv5 and reaching out. The error message indicates that the index you are using is out of bounds for the given size. It is most likely caused by the dataset size or the batch size being too large for your GPU. 

I would recommend trying to reduce your batch size or image size to see if it solves the issue. Also, double-check that your dataset and annotations are correctly formatted.

Let me know if this helps or if you have any other questions.
