### ISSUE TITLE
no acceleration onnx on e5 2680v3

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [ultralytics/yolov5#11636]
onnx version :'1.14.0'

When I convert the weight file to .onnx (half=True)
When using cpu for inference at that time
Inference speed is 1.5 times faster than .pt on my own computer (i7 12700)
Predicting 15 images
.pt: 6.50s
.onnx: 4.8s 

But when I put the same weights on the e5 2680v4 server, the result is basically the same, even slower  

.pt: 8.50s
.onnx: 9.8s 

What is going on here? Does onnx not support e3 and e5 cpu's?

**Comment by glenn-jocher** [comment]
@xiaoguaishoubaobao hi! The performance of ONNX models can depend on many factors, including the CPU type, system configuration, and the specific details of the model and the inference environment. 

It is unlikely that the issue is related to ONNX not supporting e3 and e5 CPUs. ONNX runtime is known to be highly optimized for CPU inference. However, it is possible that the performance difference on the two machines is due to a difference in the hardware. 

Please provide more details about the e5 2680v4 server specifications, the environment in which you are running the inference, and the methods you are using to measure the performance. This will help to narrow down the possible causes of the performance difference.

Best regards.

**Comment by xiaoguaishoubaobao** [comment]
This is the code I use
The current version uses yolov8


`import glob
import os.path

import time
import cv2
from ultralytics import YOLO

model = YOLO('runs/detect/train2/weights/best_m.onnx')  # load a custom model

if __name__ == '__main__':
    jsonFIle = glob.glob(r"PredictImage/*.jpg")

    start_time = time.time()

    for index, imagePath in enumerate(jsonFIle):
        results = model.predict(imagePath, imgsz=640, conf=0.5)

    end_time = time.time()
    run_time = end_time - start_time 
    print('总时间:'+str(run_time))`



The e5 2680v4 is the heart of linux's server
The server uses kvm's virtualization technology
My server is configured with 8 cores and 8G of RAM

ONNX:
![image](https://github.com/ultralytics/yolov5/assets/21216881/b0cfa648-15f1-43e2-977a-82f9fee3a2a7)
PT:
![image](https://github.com/ultralytics/yolov5/assets/21216881/158aa628-0d5f-4256-abe8-7c9873079c0c)

**Comment by glenn-jocher** [comment]
Hello @xiaoguaishoubaobao,

Thank you for providing the additional information on your inference environment. Based on the images you provided, the ONNX model performance on the e5 2680v4 server is indeed slower compared to the PT model.

One possible explanation for this is that the e5 2680v4 server hardware is not optimized for running deep learning models. The KVM virtualization technology can also introduce additional overhead and impact performance. 

Another possibility is that the conversion from PT to ONNX has resulted in a sub-optimal ONNX model. We suggest performing a detailed profiling of the ONNX model to identify any bottlenecks in the model.

You could also try optimizing the ONNX model for better performance on the e5 2680v4 server by using the onnxruntime backend instead of pytorch. Please refer to the YOLOv5 onnxruntime backend [documentation](https://docs.ultralytics.com/tutorials/ultralytics_yolov5_onnx_runtime/) for more information.

Best regards,

**Comment by xiaoguaishoubaobao** [comment]
Thank you very much for your prompt reply
pt->onnx I used the code provided by yolov8 as follows.

````
from ultralytics import YOLO
model = YOLO('runs/detect/train3/weights/best_m.pt')
model.export(format='onnx', half=True)
````

If it's the same onnx but with different speeds on different platforms (windows and linux)
I don't think it has to do with the onnx
It should have something to do with the system, the system environment or the hardware

Linux systems should be fine
Environment: I recreated the environment using requirements.txt and the onnx version is the same, which means it's not an environment problem either.
Then it should only be a hardware problem (or a kvm virtualization problem)

**Comment by glenn-jocher** [comment]
You're welcome @xiaoguaishoubaobao!Yes, it is most likely a hardware problem or a KVM virtualization problem that is causing the performance difference on the e5 2680v4 server. The ONNX model is highly optimized for CPU inference and should perform well on most CPU architectures. Since you have confirmed that the environment and ONNX versions are the same, this further strengthens the hypothesis that it is a hardware issue. 

If you wish to optimize the ONNX model for better performance on the e5 2680v4 server, you could try using the onnxruntime backend instead of Pytorch. This can potentially improve the performance of the ONNX model. Please refer to the YOLOv5 onnxruntime backend documentation for implementation details.

Let us know if there's anything else we can help you with.

Thanks!

**Comment by xiaoguaishoubaobao** [comment]
Thank you very much for your reply I will test the way you said
I will also consider not using kvm cloud server and use physical server directly
Finally, thank you again for your reply

**Comment by Zephyr69** [comment]
> Thank you very much for your reply I will test the way you said I will also consider not using kvm cloud server and use physical server directly Finally, thank you again for your reply

Dude, I think that is a GPT glenn. My 2cents on this is that e5 2680 v4 is an ancient CPU and it's possible it simply lacks some infrastructure to fully support onnx optimization. Moreover, server cpus boost to much lower clock than desktop cpus, which may also lead to this result depending on how well .pt and .onnx utilize multiple cores respectively.

**Comment by xiaoguaishoubaobao** [comment]
Thank you very much for your reply
onnx is 1.14.0
onnx runtime is 1.15.0
I think this may be better than the result of my server being virtualized as a result of KVM
My server is a cloud server and I am not using a dedicated server

**Comment by glenn-jocher** [comment]
@xiaoguaishoubaobao hello,

Thank you for providing the ONNX and ONNX runtime versions. It is possible that the performance difference you are observing is due to the e5 2680v4 server lacking some of the hardware infrastructure that is required for optimal ONNX optimization. Additionally, server CPUs typically boost to much lower clock speeds than desktop CPUs, which can also impact performance depending on how well the ONNX and PT utilize multiple cores.

Since you are using a cloud server, it is possible that the virtualization layer may be introducing additional overhead which could negatively impact the model's performance. If possible, it may be worth trying the model on a dedicated physical server to see if this improves the performance.

Best regards.
