### ISSUE TITLE
Is there away to use tf.image.non_max_suppression instead of tf.image.combined_non_max_suppression?

### ISSUE THREAD

**Issue by Leael** [ultralytics/yolov5#11637]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Is there away to use tf.image.non_max_suppression instead of tf.image.combined_non_max_suppression?
I wanted to remove the FlexCombinedNonMaxSuppression since it is not supported in the system we used. Is there a way modify it?
![image](https://github.com/ultralytics/yolov5/assets/59642936/d2b486b1-8290-41ff-a379-2794a8d49292)

I've tried to use tf.image.non_max_suppression but the model output is incorrect.

**Comment by glenn-jocher** [comment]
@Leael hi there! You can certainly use `tf.image.non_max_suppression` instead of `tf.image.combined_non_max_suppression`. To do this, you can directly replace the call to `tf.image.combined_non_max_suppression` with `tf.image.non_max_suppression` in the YOLOv5 codebase. However, please note that you may need to adjust other parts of the code to ensure compatibility.

Let me know if you have any other questions or need further assistance!
