### ISSUE TITLE
When I try to train on the cached data, the program gets stuck on loading the data?

### ISSUE THREAD

**Issue by songjiahao-wq** [ultralytics/yolov5#11639]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I try to train on the cached data, the program gets stuck on loading the data
![image](https://github.com/ultralytics/yolov5/assets/75210061/9f416807-eb16-4724-8962-72e33dee5e3f)

**Comment by songjiahao-wq** [comment]
I am running on a Windows system,use python train.py --cache --data coco128.yaml

**Comment by glenn-jocher** [comment]
@songjiahao-wq hello! Sorry to hear that you are having trouble loading the cached data while training YOLOv5 on a Windows system. 

There might be different reasons why this could happen. One possible cause could be related to the amount of memory available on your system, especially if the cached data is too large. You could also check if the GPU memory is being properly allocated during training. 

Another potential cause could be related to a compatibility issue with the specific version of Python or PyTorch that you are using. Please check that you have met the requirements and dependencies necessary for running YOLOv5 and ensure that you are using the latest version of the Ultralytics YOLOv5 repository. 

I would recommend that you try running the same command on a Linux system or on a cloud service such as AWS, which would help identify if the issue is related to your local Windows setup or not. 

Please let us know if this helps and if the issue persists, feel free to provide us with more information about your setup and any error messages or logs that you have encountered. We will do our best to assist you further.
