### ISSUE TITLE
Import "utils.general" could not be resolved

### ISSUE THREAD

**Issue by mrsapph** [ultralytics/yolov5#11677]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I fix this? It doesn't seem possible to install with pip nor can I find a file anywhere for it.

**Comment by glenn-jocher** [comment]
@SapphirePredictor hello! Thank you for reaching out. 

The import error you're experiencing may occur due to a few reasons, including a missing or incorrect package installation. Please ensure that you have installed all of the requirements listed in the YOLOv5 repository, including PyTorch, with `pip install -r requirements.txt`.

If the issue persists, it may be helpful to provide additional information such as the exact error message and steps to reproduce the error. We would be happy to help you further.

Best regards.
