### ISSUE TITLE
Get backbone of a model

### ISSUE THREAD

**Issue by Alberto1404** [ultralytics/yolov5#11670]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher! 
I am attepmting to build an image similarity system. HuggingFace might be helpful with this as they provide [this notebook](https://github.com/huggingface/notebooks/blob/main/examples/image_similarity.ipynb). 
I have finetuned yolov5x with a custom dataset. Nevertheless, transformers.AutoModel cannot read the best.pt obtained. 

```
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/configuration_utils.py", line 659, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/configuration_utils.py", line 750, in _dict_from_json_file
    text = reader.read()
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 444, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/alberto/anaconda3/envs/detr/lib/python3.10/site-packages/transformers/configuration_utils.py", line 662, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/home/alberto/Repo/yolov5/ptz/baseline2/weights/epoch190.pt' is not a valid JSON file.
```

For the model, my initial approach is to read it via torch.hub.load. However, I am unable to extract the backbone from the model. 
Can you share some tips to achieve this?
Any other suggestions for the image similarity computation are appreciated as well

**Comment by lucastack** [comment]
Hello @Alberto1404!

You can see your model definition inside your `model.yaml` file. In particular the backbone of a `yolov5s` looks like this

https://github.com/ultralytics/yolov5/blob/89c3040e734e8a0185fb49c667184600bb827f25/models/yolov5s.yaml#L13-L25

So, you should get the modules till the 9th layer plus one because of the input.

Due to several layers of abstraction in the codebase, if you have a `model` as a `DetectMultiBackend` object the you can get the backbone with the following line

`backbone = list(model.model.model.modules())[0][:10]`

Then you can just use this as a model, indeed, if you pass let's say `x = torch.rand(size=[1, 3, 640, 640])` you get the corresponding features with  `feats = backbone(x)`

Hope it helps

Regards!

**Comment by glenn-jocher** [comment]
Hello @lucastack,

You can see your model definition inside your `model.yaml` file. In particular, the backbone of a `yolov5s` can be found [here](https://github.com/ultralytics/yolov5/blob/89c3040e734e8a0185fb49c667184600bb827f25/models/yolov5s.yaml#L13-L25).
 
You should get the modules till the 9th layer plus one because of the input.

Inside the codebase, due to several layers of abstraction, if you have a `model` as a `DetectMultiBackend` object, you can get the backbone with the following line: `backbone = list(model.model.model.modules())[0][:10]`. You can use this as a model and obtain the corresponding features with `feats = backbone(x)`. 

I hope this helps!

**Comment by Alberto1404** [comment]
Thank you so much @glenn-jocher @lucastack !

**Comment by glenn-jocher** [comment]
@Alberto1404 hello! You're very welcome! We are always happy to help. If you have any further questions or concerns, please don't hesitate to ask. Have a great day!

**Comment by Alberto1404** [comment]
Hello @glenn-jocher @lucastack again, sorry for bothering again. 
With the purpose of extracting the image embeddings, how can I get the last hidden state of the model? Following the strategy commented above, my idea was to do something like this:
``` python
up_to_last_hidden_state = list(model.model.model.modules())[0][:24]
last_hidden_state = up_to_last_hidden_state(torch.rand(size=[1,3,640,640]))
```
But is does not work: 
``` sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alberto/Repo/yolov5/models/common.py", line 312, in forward
    return torch.cat(x, self.d)
TypeError: cat() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)
```
Thank you

**Comment by glenn-jocher** [comment]
@Alberto1404 hello, no bother at all! It looks like you are almost there! The error seems to be due to trying to concatenate tensors using `torch.cat`. Instead, you can directly pass the input through the backbone modules to get the last hidden state as follows:

```python
last_hidden_state = list(model.model.model.modules())[0][:24](torch.rand(size=[1, 3, 640, 640]))
```

This should give you the last hidden state of the model. Let me know if that works for you!
