### ISSUE TITLE
When I was running tutorial.ipynb on colab, it occured "RuntimeError: Cannot find callable yolov5s-seg in hubconf"

### ISSUE THREAD

**Issue by yhm138** [ultralytics/yolov5#11695]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

2023-06-13

When I was running [tutorial.ipynb on colab](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/segment/tutorial.ipynb#scrollTo=GMusP4OAxFu6),

```
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-7-9c7b34200154>](https://localhost:8080/#) in <cell line: 4>()
      2 import torch
      3 
----> 4 model = torch.hub.load('ultralytics/yolov5', 'yolov5s-seg')  # yolov5n - yolov5x6 or custom
      5 im = 'https://ultralytics.com/images/zidane.jpg'  # file, Path, PIL.Image, OpenCV, nparray, list
      6 results = model(im)  # inference

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/hub.py](https://localhost:8080/#) in _load_entry_from_hubconf(m, model)
    338 
    339     if func is None or not callable(func):
--> 340         raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
    341 
    342     return func

RuntimeError: Cannot find callable yolov5s-seg in hubconf
```

**Comment by glenn-jocher** [comment]
@yhm138 hi there! The error you're encountering is likely due to a mismatch between the model name you're trying to load and the available models in the YOLOv5 repository. It seems there is no model with the name "yolov5s-seg" in the hubconf at the moment. You can refer to the YOLOv5 documentation for the correct model options and their respective names. If you have any further questions or run into any issues, feel free to ask.
