### ISSUE TITLE
Cropping images from test data

### ISSUE THREAD

**Issue by aan2907** [ultralytics/yolov5#11700]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The cropped images returned after predicting model with parameter save_crop= True is of low resolution. 
Is there any other way to crop the  object detected for objects belonging to a particular class?

**Comment by glenn-jocher** [comment]
@aan2907 hey there! Thanks for reaching out. The resolution of the cropped images will match the resolution of the detection bounding box, so if you're experiencing low-resolution crops, it might be due to small bounding boxes. One way to address this could be to filter the detections for objects belonging to a particular class before saving the crops. You can achieve this by post-processing the model's output to filter detections by class before saving the crops. For more information on post-processing the model's output, you can refer to the Ultralytics YOLOv5 documentation at https://docs.ultralytics.com/yolov5. Let me know if you need further assistance with this!
