### ISSUE TITLE
Train Model on GPU but CPU usage is 100%

### ISSUE THREAD

**Issue by SJavad** [ultralytics/yolov5#11705]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi
Im Trying to train Yolov5s on CUDA.🧐
when I train a model on gpu, gpu memory is used. 👍👌
but cpu usage is very very high, 100%  🥵😡
why?
GPU : Nvidia GTX 1080ti 💪
CPU : Intel Core i7 4770 😩
command: 
`python .\train.py --weights .\models\PretrainedModels\yolov5s.pt --data .\data\coco.yaml --epochs 1500 --device 0 --batch-size 40`
several ecpohs after this happend, system crashed and train uncomplete
my question is, why is this happend ? 😑
what is the solution 🤔
![image](https://github.com/ultralytics/yolov5/assets/64639184/5ae07528-4a49-416c-bcbc-a5f9fb33434f)

**Comment by glenn-jocher** [comment]
@SJavad hi there! 🌟

It sounds like your GPU is working as expected during training, but your CPU is maxing out. This can happen when the CPU is bottlenecked due to data loading, augmentation, or model post-processing.

To help, you can try limiting the CPU threads using `--workers` in your training command. Also, consider updating your GPU drivers and ensuring CUDA/cuDNN are installed correctly.

Finally, training on a larger batch size might be exacerbating CPU usage. You could try reducing the batch size to lessen the CPU load.

I hope this helps! The YOLO community and the Ultralytics team are here to support you. 🚀
