### ISSUE TITLE
TFlite INT8 Interpreter Export 

### ISSUE THREAD

**Issue by smtalds** [ultralytics/yolov5#11709]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection, Export, Integrations

### Bug

Hi everyone , i exported my model tflite int8 format with `python export.py  --data data.yaml --weights best.pt --batch-size 1 --include tflite --int8 --img 224` , after that i got this error [https://oxidized-minnow-233.notion.site/yolov5-tflite-export-error-4e6c599ee7114d7393ad4fef0c8b4ec6?pvs=4](url) but its converted i guess . I get this info from shell :

`TensorFlow Lite: export success ✅ 50.5s, saved as best-int8.tflite (7.0 MB) Export complete (55.8s)`

Then i detected with `python detect.py  --data data.yml --weights best-int8-tflite --img 224 --source demo.jpg` , i did not get error. I detected truly. Then i try detect with interpreter like [https://github.com/ultralytics/yolov5/issues/11395#issuecomment-1582319590](url) 
i got this errors :
`Got value of type FLOAT32 but expected type UINT8 for input 0, name: serving_default_input_1:0 `
Then i changed astype float32 to uint8 , i got this error :
`cannot compute CombinedNonMaxSuppression as input #0(zero-based) was expected to be a float tensor but is a uint8 tensor`

How can i solve this problem ?

### Environment

YOLOv5 🚀 v6.2-228-g6ae3dff7  torch-1.13.0+cu117 CPU
Ubuntu 20.04.5 LTS
Python-3.8.11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@smtalds hi there! Thanks for reaching out! It sounds like you've successfully exported your model to TFLite INT8 format, but are encountering issues when using the interpreter for detection. 

The first error suggests a type mismatch for the input tensor. To resolve this, you may need to ensure that the input tensor is correctly formatted as UINT8. 

Regarding the second error, it seems the interpreter is expecting a float tensor instead of UINT8. Ensure that the input tensor type matches the interpreter's expectations.

Additionally, you may want to check the compatibility of the model with the interpreter and ensure that the interpreter is set up correctly for TFLite INT8 models.

Feel free to refer to the Ultralytics Docs for more detailed guidance on TFLite model conversion and compatibility with the YOLOv5 interpreter.

Let me know if you need further assistance! Keep up the great work!
