### ISSUE TITLE
ImportError: cannot import name 'TryExcept' from 'utils' (C:\Users\User\XXX\utils\__init__.py)

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#11721]
Hi
I jsut download new yolov5-7.0 version today and pip install -r requirements.txt
when i python segment/predict.py --weights weights/crack.pt --img 1280, got this error.

but i python detect.py --weights weights/yolov5s  --img 1280, it is ok.

what happened

**Comment by glenn-jocher** [comment]
@stphtan94117 hi,

Thank you for reaching out and providing details about the error you encountered.

It looks like you are facing an ImportError when trying to import the 'TryExcept' module from the 'utils' package in the yolov5-7.0 version. This error is most likely due to a missing or incompatible package or module in your environment.

To troubleshoot this issue, I recommend checking the following steps:

1. Ensure that you have correctly installed all the required packages mentioned in the 'requirements.txt' file. Please note that some packages may require specific versions or dependencies.

2. Verify that the 'utils' package is present in the correct location within the yolov5-7.0 directory. Double-check if the necessary files and folders are intact.

3. It is also possible that there might be conflicting versions of packages installed in your Python environment. You can try creating a new virtual environment and installing the required packages there to isolate any potential conflicts.

If the issue still persists, please provide more information about your environment, including the versions of Python, PyTorch, and any other relevant packages you are using. Additionally, please specify how you downloaded the yolov5-7.0 version, as it will help us understand if there might have been any issues during the download process.

Remember, I'm here to assist you, but please note that the YOLOv5 repository is maintained by the Ultralytics team and the YOLO community, so any praise or acknowledgments should be directed towards them.

Best regards,
Glenn Jocher
