### ISSUE TITLE
Unable to get NMS in TFJS exported model

### ISSUE THREAD

**Issue by Abhishekvats1997** [ultralytics/yolov5#11728]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I tried exporting my trained .pt model to tfjs. The --nms flag and --topk-per-class flags do not seem to have any effect on the exported model.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Abhishekvats1997 hi there!

Thank you for bringing this issue to our attention. I understand that you are experiencing trouble with the `--nms` and `--topk-per-class` flags not having any effect on the exported model when using YOLOv5 with TensorFlow.js.

To investigate this issue further, it would be helpful if you could provide a minimal reproducible example, including the steps to export the model and any relevant code snippets. This will allow us to better understand the problem and assist you with finding a solution.

Furthermore, if you are willing to submit a pull request to address this issue, we greatly appreciate your contribution! Our team will be more than happy to review and merge your changes. Please ensure that your proposed changes follow our contribution guidelines.

Thank you again for your report, and we look forward to working with you to address this issue.

**Comment by Abhishekvats1997** [comment]
Code used to export
python export.py --weights ../shibumi/model.pt --topk-per-class 1 --include tfjs --nms
Expectation
A model which gives out 1 object per class with nms.

After a bit of digging I could see the reason for this as 
https://github.com/ultralytics/yolov5/blob/2334aa733872bc4bb3e1a1ba90e5fd319399596f/export.py#LL787C78-L787C78

The "or" here is causing the model conversion to default to class-agnostic NMS in the case of tfjs. After trying to remove this condition I get errors highlighting that the CombinedNonMax Suppression layer is not implemented on TFJs. Is this the reason that you have introduced the above-mentioned "or" condition? If yes, can you suggest a possible solution to use yolov5 on tfjs with per class NMS and limit objects per class other than the manual for loops in JS :( .

**Comment by glenn-jocher** [comment]
@Abhishekvats1997 hello!

Thank you for bringing this issue to our attention. I understand that you're experiencing difficulty with the `--nms` and `--topk-per-class` flags while exporting a YOLOv5 model to TensorFlow.js.

After further investigation, it appears that the "or" condition you noticed in the export script is indeed causing the model conversion to default to class-agnostic NMS in the case of TensorFlow.js. Unfortunately, the CombinedNonMax Suppression layer is not implemented in TensorFlow.js, which is why the condition is in place.

As of now, there is no straightforward solution to accomplish per-class NMS and limit the number of objects per class in TensorFlow.js without resorting to manual for loops in JavaScript. It would involve implementing custom JavaScript code for performing per-class NMS and enforcing the object limits.

We understand that this could lead to potential performance overhead due to the need for additional computation in JavaScript. If this functionality is critical for your use case, we recommend considering alternative options such as using Python or exploring other object detection frameworks that support per-class NMS and object limits in TensorFlow.js.

We hope this information clarifies the situation. Please let us know if you have any further questions or concerns. We appreciate your interest in YOLOv5 and the Ultralytics team's work.

Thank you for your understanding and contribution to the YOLO community!
