### ISSUE TITLE
weights size changes after training

### ISSUE THREAD

**Issue by guetaro** [ultralytics/yolov5#11735]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I found out an issue - before training the pretrained model (small), it's size is around 14.5MB
After training, it's around 55.5MB. In addition, the FPS is decrease by half. The train is done on default setting. This issue happens with Large architecture as well. 
Do you have an idea why it happens?

Thanks.

**Comment by glenn-jocher** [comment]
@guetaro hi,

The increase in weights size after training is normal and usually indicative of successful learning. The decrease in FPS is expected due to the additional complexity introduced by training. For improved performance, consider optimizing the model via techniques such as quantization, pruning, or model distillation. Our documentation provides further insights on post-training optimizations.

Best regards.
