### ISSUE TITLE
Why different input image sizes influence the inference time?

### ISSUE THREAD

**Issue by kangarin** [ultralytics/yolov5#11734]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm working on a project that requires understanding the relationship between input video resolution and inference latency. I've looked at the code, but I don't understand why different input sizes result in significantly different inference latencies, given that the network's input is fixed at 640 * 640 * 3.

**Comment by glenn-jocher** [comment]
@kangarin the input image size affects inference time because larger images require more data to be processed, impacting the computational load. Resizing the images to the network's input size allows for faster inference by reducing the computational complexity. For more details, you can refer to the Ultralytics Docs at https://docs.ultralytics.com/yolov5. If you have further questions, feel free to ask!

**Comment by yoelsheikh** [comment]
@glenn-jocher Isnt the input preprocessed in all cases, i.e. fixed?

I would suspect here that the inference time would still change, even if the input is fixed. Different input spaces would cause different inference patterns (i.e. activations within the neural network), leading to more or less computation depending on the input. Depending on the significance of the "latency" you are referring to here and if you are feeding variable size images, the problem could also be something else entirely. i.e. preprocessing time.
