### ISSUE TITLE
Non-Max Suppression: Its Impact on the Model and Inference Time

### ISSUE THREAD

**Issue by 34fg** [ultralytics/yolov5#11736]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm attempting to export an ONNX model for my task while enabling non-maximum suppression, which can be done using export.py. However, I'm not seeing any changes in the model after exporting it with NMS enabled (verified using the Netron app). Additionally, I haven't noticed any differences in inference time either. I would greatly appreciate it if someone could assist me with this issue.

**Comment by glenn-jocher** [comment]
@34fg thanks for reaching out! Enabling non-maximum suppression (NMS) through export.py simply includes the NMS layer in the exported ONNX model. In order to actually observe changes in model behavior and inference time, you'll need to run inference using the exported ONNX model, as detection results are post-processed with NMS during inference. Additionally, do note that inference time can vary based on the hardware and software setup used.

Feel free to give it a try and let us know if you have any other questions. Cheers!
