### ISSUE TITLE
nan values in model predicted output  i.e. model(img)

### ISSUE THREAD

**Issue by Ching87** [ultralytics/yolov5#11746]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

Everything works fine with the system-1

But when it comes to system-2, firstly during training i got model predicted (i.e. model(img)) values as nan. Then, i passed an argument dtype = torch.float32 in with torch.cuda.amp.autocast(enabled=True, dtype = torch.float32), i do not get nan values and thus i donot get nan losses. So, training goes without nan, with that change. 
Then, during validation, i.e. validate.run() in line 210 of val.py , during model prediction for validation, i get nan values. And ultimately i get all metrics ap, p, recall all as zero.
I did training for some epochs. and tried to do inference on some of my test data, and model could do some correct predictions despite of showing metrics as zero during validation Inference works fine for both systems.

### Environment

System-1:
os - ubuntu 18.04
torch = 1.10.1 + cu111 (NVIDIA GeForce GTX 1660 SUPER)
torchvision = 0.11.2 + cu111
numpy = 1.19.5
python3.6.9

System-2:
os - ubuntu 20.04
torch = 1.10.1 + cu111 (NVIDIA GeForce GTX 1660 SUPER)
torchvision = 0.11.2 + cu111
numpy = 1.19.5
python3.6.15

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by HerrAskinSM** [comment]
similar problem and solution:
https://github.com/opencv/opencv/issues/23850

**Comment by glenn-jocher** [comment]
@HerrAskinSM thanks for reporting this. 👍🏼 It sounds like the nan issues you're encountering during validation on system-2 may be related to the datatype handling, particularly given your success with dtype=torch.float32 during training.

To help you effectively, could you please provide more specifics on the model and the input data to better understand the root cause? Additionally, have you tried adjusting other parameters such as the batch size, image size, or the optimizer settings?

Your input will help us find a solution faster. Thank you for your patience and for reaching out.
