### ISSUE TITLE
Why does the confidence threshold of 0.001 in val.py result in good results?

### ISSUE THREAD

**Issue by Jobvdlaken** [ultralytics/yolov5#11745]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I load my custom trained model and make predictions with model.conf at 0.001. Then I see quite a few bounding boxes at random places where there are no objects (see photo 1 with model.conf at 0.001 and photo with model.conf at 0.25), which can be related to a large number of False Positives. So even though there are a lot of FPs, my precision is 0.98, recall is 0.97 and my mAP0.5 is 0.99 when I validate with val.py. I would expect this low confidence threshold to result in low precision due to the high number of FPs.

![image](https://github.com/ultralytics/yolov5/assets/120382552/6a422e44-b417-4ce1-aa1d-c336f5dd9a7e)
![image](https://github.com/ultralytics/yolov5/assets/120382552/15a39f89-8e3d-431d-bec0-f1ee6ebefcc0)

Many thanks in advance for any help :)

**Comment by vtyw** [comment]
@Jobvdlaken Good question.

I believe yolov5 is a bit peculiar in that it produces lower confidence scores than other detectors, and so it requires low confidence thresholds to include all detected objects.

As for how this affects the metrics, here's an example:
```
$ python val.py --data example.yaml --exist-ok --weights example/weights/best.pt --conf-thres 0.000001
                 Class     Images  Instances          P          R      mAP50   mAP50-95:
                   all        130        719      0.935       0.86      0.886      0.592
```

- yolov5 does not actually report P and R, it reports AP and AR
- AP, AR, and mAP are not really affected by the confidence being lower than ideal, other than a threshold of 0.001 being used by default to calculate AP, AR, mAP in  `val.py` and `train.py`
- So you are correct to be confused, and if yolov5 did actually report P for a given confidence threshold like 0.001 or lower, then in your example it would be a much lower value (e.g., less than 20% in your top picture).

**Comment by Jobvdlaken** [comment]
Dear @vtyw, 
Thank you very much for your explanation! It is completely clear now :)

**Comment by wongs19** [comment]
> @Jobvdlaken Good question.
> 
> I believe yolov5 is a bit peculiar in that it produces lower confidence scores than other detectors, and so it requires low confidence thresholds to include all detected objects.
> 
> As for how this affects the metrics, here's an example:
> 
> ```
> $ python val.py --data example.yaml --exist-ok --weights example/weights/best.pt --conf-thres 0.000001
>                  Class     Images  Instances          P          R      mAP50   mAP50-95:
>                    all        130        719      0.935       0.86      0.886      0.592
> ```
> 
> * yolov5 does not actually report P and R, it reports AP and AR
> * AP, AR, and mAP are not really affected by the confidence being lower than ideal, other than a threshold of 0.001 being used by default to calculate AP, AR, mAP in  `val.py` and `train.py`
> * So you are correct to be confused, and if yolov5 did actually report P for a given confidence threshold like 0.001 or lower, then in your example it would be a much lower value (e.g., less than 20% in your top picture).

sorry I dont understand why you said AP, AR, and mAP are not really affected by the confidence being lower than ideal, other than a threshold of 0.001 being used by default to calculate AP, AR, mAP in val.py and train.py. Because I think the threshold will influence the result of NMS, and then influence the preds. So I dont know why the lower conf have a good result.

**Comment by glenn-jocher** [comment]
@wongs19 the confidence threshold in YOLOv5 does indeed affect the number of predictions and can impact the results of NMS (non-maximum suppression). 

However, in terms of AP (average precision), AR (average recall), and mAP (mean average precision), these metrics are not significantly affected by the confidence threshold being lower than ideal. This is because the default threshold of 0.001 is used to calculate these metrics in `val.py` and `train.py`. The purpose of this low threshold is to ensure that all possible objects are included, even if their confidence scores are low.

In your specific example, the low confidence threshold allows more predictions to be made, resulting in a higher recall, but it may also introduce some false positives in the form of bounding boxes where there are no objects. However, due to the nature of the YOLOv5 model, even with a higher number of false positives, the precision, recall, and mAP metrics can still be high.

If a higher confidence threshold, such as 0.25, was used, the precision would likely be lower due to the true positives being filtered out. But in your case, due to the low confidence threshold, more true positives are included, resulting in higher precision, recall, and mAP.

I hope this clarifies the impact of confidence thresholds on the metrics. If you have any further questions or concerns, feel free to ask.

**Comment by wongs19** [comment]
> 

em.... I still have three questions.
1. "the default threshold of 0.001 is used in val.py and train.py". Yes, but it is used in training. If we used val.py to inference, we can have own conf_thres and iou_thres, and is this will influence the result of ap\ar\map?
2. As I think, the low confidence will decrease the TP and increase the recall. So I dont understand the third paragraph. Could you explain it? Thank you very much.
3. When training, we dont need to modify the threshold of conf and iou. Only if we use the model trained to inference and predict, we can use own threshold. Is it right? I was confused.

Thank you very much!!!

**Comment by glenn-jocher** [comment]
@wongs19 1. Yes, you are correct. The default confidence threshold of 0.001 in val.py and train.py is used during training. However, when using val.py for inference, you can specify your own confidence threshold using the `--conf-thres` parameter. This allows you to adjust the threshold and see its impact on the results of AP (average precision), AR (average recall), and mAP (mean average precision) during inference.

2. I apologize for any confusion caused by the third paragraph. In YOLOv5, low confidence thresholds can indeed decrease the number of true positives (TP) and increase the recall. The reason for the higher precision, recall, and mAP metrics with low confidence thresholds is that the YOLOv5 model is designed to perform well even with a higher number of false positives. By including more predictions with lower confidence scores, it aims to capture as many objects as possible, even if their confidence is low. Keep in mind that this approach may introduce some false positives, but the model compensates for them by having a high recall and effectively localizing objects.

3. During training, you are correct that there is no need to modify the threshold of confidence (conf) and intersection over union (iou). These thresholds are typically set as hyperparameters during model development and are used consistently throughout training. However, when using the trained model for inference and prediction, you have the flexibility to adjust these thresholds based on your specific requirements. Modifying the thresholds during inference allows you to find the balance between precision and recall that best fits your application's needs.

I hope this answers your questions. If you have any further inquiries, feel free to ask.

**Comment by probicheaux** [comment]
@glenn-jocher @wongs19 @Jobvdlaken  I'm pretty sure the answer to this question is actually here https://github.com/ultralytics/yolov5/blob/9974d51f1b155b7145cceec8cd6b51691668ca96/utils/metrics.py#L91C39-L91C39
```
    i = smooth(f1.mean(0), 0.1).argmax()  # max F1 index
    p, r, f1 = p[:, i], r[:, i], f1[:, i]
    tp = (r * nt).round()  # true positives
    fp = (tp / (p + eps) - tp).round()  # false positives
    return tp, fp, p, r, f1, ap, unique_classes.astype(int)
```

this line shows that the reported precision, recall, and f1 during validation are taken with the confidence that maximizes f1. So setting a very low confidence threshold will allow the validation to perform optimally here.

**Comment by glenn-jocher** [comment]
@probicheaux the reported precision, recall, and F1 during validation in YOLOv5 are determined based on the confidence that maximizes the F1 score. This can be seen in the code snippet you provided from the `metrics.py` file.

```python
i = smooth(f1.mean(0), 0.1).argmax()  # max F1 index
p, r, f1 = p[:, i], r[:, i], f1[:, i]
tp = (r * nt).round()  # true positives
fp = (tp / (p + eps) - tp).round()  # false positives
return tp, fp, p, r, f1, ap, unique_classes.astype(int)
```

The line `i = smooth(f1.mean(0), 0.1).argmax()` calculates the index that corresponds to the maximum F1 score. The precision (`p`), recall (`r`), and F1 scores (`f1`) are then extracted using this index. Consequently, when setting a very low confidence threshold during validation, it allows the validation process to perform optimally in terms of F1 score.

If you have any further questions or require additional clarification, please let us know.

**Comment by probicheaux** [comment]
@glenn-jocher right, that was my point! Glad we're on the same page

**Comment by glenn-jocher** [comment]
@probicheaux Indeed, I apologize for any confusion caused. It seems we are in agreement regarding the impact of confidence thresholds on the validation results in YOLOv5. It's great to be on the same page. If you have any more questions or concerns, feel free to ask.

**Comment by JelmervanL** [comment]
Just to make sure, do I understand correctly that the metrics that are reported during validation in the terminal, are not AP (average precision) and AR (average recall) as suggested earlier in this thread? But are precision and recall with a confidence threshold that maximizes F1 score?

However, you also mention that AP and AR does get calculated during validation. Where does this happen?

**Comment by glenn-jocher** [comment]
@JelmervanL the metrics reported during validation in the terminal are not AP and AR, as suggested earlier in this thread. Instead, they are precision and recall values associated with the confidence threshold that maximizes the F1 score. This is determined by calculating the index that corresponds to the maximum F1 score.

However, AP and AR are still calculated during validation. This occurs within the YOLOv5 codebase, but the specific location where this calculation takes place is not explicitly mentioned in this thread.

If you have any more questions or require further clarification, please let us know.

**Comment by amriyan** [comment]
@glenn-jocher For each fold, obtain precision and recall values at different confidence thresholds. how do i save the values to create the average PR curve for 10 fold?

**Comment by glenn-jocher** [comment]
@amriyan To save precision and recall values at different confidence thresholds for each fold and create an average Precision-Recall (PR) curve for a 10-fold cross-validation, you would typically follow these steps:

1. **Run Validation for Each Fold**: For each of the 10 folds, run the validation process using `val.py` and collect the precision and recall values at various confidence thresholds.

2. **Save Metrics**: After each fold's validation, save the precision and recall values to a file. You can use a CSV file, a JSON file, or any other format that you prefer. Ensure that you save the data in a way that allows you to identify which fold the metrics belong to.

3. **Aggregate Results**: Once you have the precision and recall values for all folds, aggregate them by calculating the mean precision and recall at each confidence threshold across all folds.

4. **Plot PR Curve**: Use the aggregated precision and recall values to plot the average PR curve. You can use libraries such as Matplotlib, Seaborn, or Plotly in Python to create the plot.

Here's a pseudo-code example of how you might implement this:

```python
import numpy as np
import matplotlib.pyplot as plt

# Initialize lists to store precision and recall values for all folds
all_precision = []
all_recall = []

# Loop over each fold
for fold in range(10):
    # Run validation for the current fold and collect precision and recall
    precision, recall = run_validation(fold)
    
    # Save the precision and recall values for the current fold
    save_metrics(fold, precision, recall)
    
    # Append the results to the lists
    all_precision.append(precision)
    all_recall.append(recall)

# Convert lists to numpy arrays for easier manipulation
all_precision = np.array(all_precision)
all_recall = np.array(all_recall)

# Calculate the mean precision and recall across all folds
mean_precision = np.mean(all_precision, axis=0)
mean_recall = np.mean(all_recall, axis=0)

# Plot the average PR curve
plt.plot(mean_recall, mean_precision, marker='.')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Average PR Curve')
plt.show()
```

Remember to replace `run_validation(fold)` and `save_metrics(fold, precision, recall)` with the actual code that runs the validation and saves the metrics for your specific setup.

If you have any further questions or need more detailed guidance, feel free to ask.

**Comment by JelmervanL** [comment]
@glenn-jocher I do have an additional question. I know that the Precision and Recall metrics reported in the terminal are associated with the condifence threshold that maximizes F1 score. However, do the Precision and Recall metrics also consider an IoU threshold? Or do the Precision and Recall metrics not consider any bounding box location?

If the  Precision and Recall do consider an IoU threshold, what is this threshold by default and where is it set in `val.py`?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@JelmervanL Yes, the precision and recall metrics reported in the terminal during validation do consider an IoU (Intersection over Union) threshold. The IoU threshold is used to determine whether a predicted bounding box is a true positive or a false positive by comparing it with the ground truth bounding boxes.

By default, the IoU threshold is set to 0.5, which is a common standard for object detection tasks. This means that for a predicted bounding box to be considered a true positive, it must have an IoU of 0.5 or higher with a corresponding ground truth bounding box.

In the YOLOv5 `val.py` script, the IoU threshold can be set using the `--iou-thres` argument. If you do not specify this argument, it will use the default value set in the code.

The IoU threshold is applied during the calculation of precision and recall, as well as during the computation of AP (Average Precision) for each class and the mAP (mean Average Precision) across all classes.

If you need to adjust the IoU threshold for your validation, you can pass the desired value using the `--iou-thres` argument when running `val.py`. For example:

```bash
python val.py --weights your_model.pt --data your_data.yaml --iou-thres 0.6
```

This command would set the IoU threshold to 0.6 for the validation process.

If you have any more questions or need further assistance, feel free to reach out.
