### ISSUE TITLE
Convert to tflite, the output is "StatefulPartitionedCall:0" or "PartitionedCall:0"

### ISSUE THREAD

**Issue by alps-sun** [ultralytics/yolov5#11743]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I execute  
```python
python export.py --weights yolov5s.pt --include  tflite
```
I got  the tfltie model and use Netron Viewer to view the exported model.

 The output layer of the model is "StatefulPartitionedCall:0" or "PartitionedCall:0",

![image](https://github.com/ultralytics/yolov5/assets/31961986/b9c8434d-c499-4adb-ab51-97d7ae5accdd)

![image](https://github.com/ultralytics/yolov5/assets/31961986/ecd56ea1-a059-408c-82ba-297bc9e80861)

When using rust to import the tfllite model, the output result cannot be obtained, what should I do? 

thank you ！

**Comment by alps-sun** [comment]
Resolved

**Comment by glenn-jocher** [comment]
@alps-sun thanks for using YOLOv5! 👍

Regarding the issue you mentioned, the output layer of the converted tflite model is "StatefulPartitionedCall:0" or "PartitionedCall:0". This is expected behavior when exporting a model using our export script.

To use the exported tflite model in Rust, you may need to update your code accordingly. Please refer to the TensorFlow Lite documentation or Rust TensorFlow Lite bindings for guidance on how to correctly load and run the model.

If you encounter any difficulties or have further questions, feel free to ask for assistance. We're here to help!

And thank you for your support! 🙌
