### ISSUE TITLE
AllocateTensors() failed

### ISSUE THREAD

**Issue by khairulr36** [ultralytics/yolov5#11772]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a problem when I want to change the model Yolov5 from (.pt) to (.tflite). An error message appears on android kotlin
java.lang.IllegalStateException: Error occurred when initializing ObjectDetector: AllocateTensors() failed.

When converting (.pt) to (.tflite) using the code :
`!python export.py --weights runs/train/exp/weights/best.pt --include tflite --agnostic-nms`

and add the metadata with code :
`ObjectDetectorWriter = object_detector.MetadataWriter
_MODEL_PATH = "best-fp16.tflite"

_LABEL_FILE = "labelmaps.txt"
_SAVE_TO_PATH = "best-fp16_Meta.tflite"

_INPUT_NORM_MEAN = 127.5
_INPUT_NORM_STD = 127.5

writer = ObjectDetectorWriter.create_for_inference(
    writer_utils.load_file(_MODEL_PATH), [_INPUT_NORM_MEAN], [_INPUT_NORM_STD],
    [_LABEL_FILE])
print(writer.get_metadata_json())

writer_utils.save_file(writer.populate(), _SAVE_TO_PATH)`

is there something wrong?
or
any additional code?

**Comment by glenn-jocher** [comment]
@khairulr36 hello, 

The error message you received - "AllocateTensors() failed" - suggests that there may be an issue when initializing the object detector. 

Since the error occurred after you converted the model to .tflite format, it is possible that there was an error during the conversion process. 

To help troubleshoot the issue, could you please provide the following information?

1. The exact command you used to convert the .pt model to .tflite.
2. The version of TensorFlow you are using.
3. Any other relevant information that may be helpful in identifying the root cause of the issue.

Once we have this information, we'll be better able to assist you in resolving the issue.

**Comment by khairulr36** [comment]
@glenn-jocher This is the information that I can provide : 

1. The command I use to convert a .pt model to .tflite is: 
`!python export.py --weights runs/train/exp/weights/best.pt --include tflite --agnostic-nms`

2. The TensorFlow version I am using is : 
`2.12.0`

**Comment by glenn-jocher** [comment]
Hello @khairulr36,

Thank you for providing the information. It seems that you are using an older version of TensorFlow (2.12.0) which may not be compatible with the YOLOv5 codebase.

We recommend using the latest version of TensorFlow (currently 2.6.0) with YOLOv5 to ensure optimal compatibility and performance. 

Could you please upgrade your TensorFlow version to the latest version and try again with the conversion?

Let me know if you need further help.

Best, 
Glenn Jocher

**Comment by khairulr36** [comment]
@glenn-jocher  Based on the data obtained from the TensorFlow website : 
[https://www.tensorflow.org/versions?hl=id](url)

The latest version of TensorFlow is 2.12.0, released in March 2023.
[https://github.com/tensorflow/tensorflow/releases/tag/v2.12.0](url)

And for TensorFlow 2.6.0, it was released in August 2021.
[https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0](url)

"What else should I do?"

**Comment by glenn-jocher** [comment]
@khairulr36 hello there,

Thank you for your reply.

Please accept my apologies for the confusion. You are correct that the latest version of TensorFlow available currently is 2.6.0. My earlier message was incorrect in stating that the latest version was 2.12.0. I apologize for any confusion this may have caused.

To proceed, could you please verify that you have installed the latest version of TensorFlow and try again with the conversion? 

If the issue persists, please let us know and we can work together to identify the root cause and help you resolve the issue.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@khairulr36 I apologize for the confusion. It seems that there was an error in the provided information. 

It appears that you are already using the latest version of TensorFlow, and that should not be the cause of the issue you are facing.

In order to further investigate the "AllocateTensors() failed" issue, we would need some additional details:

1. The complete error message or stack trace you are seeing when you encounter the issue.
2. Any additional context or code related to the execution of the TFLite model on Android that may help in identifying the root cause of the problem.

With this additional information, we should be able to provide you with a more effective solution.

Best, 
Glenn Jocher
