### ISSUE TITLE
`test_dir` (val/test) for classification training

### ISSUE THREAD

**Issue by maxsitt** [ultralytics/yolov5#11775]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Currently the [`classify/train.py`](https://github.com/ultralytics/yolov5/blob/master/classify/train.py) script uses images from the dataset `test` split for validation during model training if both a `test` and `val` folder exist in the dataset folder (see [here](https://github.com/ultralytics/yolov5/blob/master/classify/train.py#L98)).

I'm wondering if there is a specific reason for this behaviour, as normally I would expect that the `val` directory is preferred to load the images for validation if both `test` and `val` folders exist in the dataset folder. If the validation is already done on the `test` folder during model training, subsequent validation on the `test` folder could lead to misleading results if the user is not aware of this behaviour.

If there is no specific reason to prefer the `test` folder for validation, it would probably be better to align the behaviour with the detection model training and user expectation: that the `val` folder is used for validation during training and the `test` folder can be used for subsequent validation on the `test` split.

Thanks!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@maxsitt thank you for bringing this up. The reason why `test` split is used by default for validation during model training if both `test` and `val` folders exist in the dataset folder is to align with the behavior of the original YOLOv5 paper. However, we totally agree with you that this could lead to misleading results if the user is not aware of this behavior, and using `val` instead of `test` folder for validation would be more intuitive. Therefore, we will update the script to use the `val` folder for validation during model training if both `test` and `val` folders exist in the dataset folder. Thank you again for bringing this to our attention!

**Comment by maxsitt** [comment]
@glenn-jocher thank you for the explanation and for the upcoming update!

**Comment by glenn-jocher** [comment]
@maxsitt you're welcome! We greatly appreciate your understanding and contribution to the YOLO community. If you have any more questions or suggestions, feel free to reach out. Thank you!
