### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by PoivronMax** [ultralytics/yolov5#11783]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After I have completed all the required configurations of yolov5 in Ubuntu20.04, I run the "ppython detect.py --source data/images/ --weights yolov5s.pt" code, it occurs:

python detect.py --source data/images/ --weights yolov5s.pt
detect: weights=['yolov5s.pt'], source=data/images/, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=True, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-187-g0004c74 Python-3.7.0 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5947MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/home/max/anaconda3/envs/new_env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 173, in run
    annotator.box_label(xyxy, label, color=colors(c, True))
  File "/home/maxime/vision/yolov5/utils/plots.py", line 103, in box_label
    p1, p2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))
ValueError: cannot convert float NaN to integer

i want to know how to fix this issue.The images are example images(bus)

**Comment by glenn-jocher** [comment]
@PoivronMax hi there! It looks like you're experiencing an error while running YOLOv5's `detect.py` script. The error message indicates a "ValueError: cannot convert float NaN to integer." 

This error typically occurs when there is an issue with the bounding box coordinates for object detection. NaN (Not a Number) represents missing or undefined values, and in this case, it suggests that there may be a problem with the bounding box coordinates of the detected objects in your images.

To fix this issue, I would recommend the following:

1. Check your dataset: Ensure that your dataset has accurate bounding box annotations for the objects you are trying to detect. Any missing or incorrectly defined bounding box coordinates could result in NaN values.

2. Verify the integrity of your data: Double-check that your images and annotations are correctly formatted and there are no empty or corrupted files.

3. Update YOLOv5: Make sure you have the latest version of YOLOv5 installed. You can update to the latest version by running `git pull` in the yolov5 repository directory.

If you're still encountering issues after attempting these steps, it would be helpful if you could provide more information about your dataset, such as a sample image and its corresponding annotation file. Additionally, any specific steps or modifications you made to the code would assist in identifying the cause of the issue.

Please feel free to ask further questions or provide more details. The YOLO community and the Ultralytics team are here to help you out!

**Comment by rt0821** [comment]
Hello, did you fix this issue, I also had the same problem

**Comment by glenn-jocher** [comment]
@rt0821 hi there! If you're encountering the same "ValueError: cannot convert float NaN to integer" issue, it's likely due to a similar cause as mentioned previously. Here are a few steps you can take to troubleshoot the problem:

1. **Check Annotations**: Ensure that your annotations are correct and that no bounding box coordinates are missing or improperly formatted.

2. **Data Integrity**: Verify that your images and corresponding annotation files are not corrupted and are accessible by the script.

3. **Update YOLOv5**: Make sure you're using the latest version of YOLOv5 by updating your local repository.

4. **Debugging**: Add print statements before the error line to print out the values of `box` and `label`. This can help you identify if and where NaN values are coming from.

5. **Review Changes**: If you've made any changes to the code, review those changes to ensure they're not causing the issue.

If you've tried these steps and the issue persists, please provide additional details such as the exact command you're running, a snippet of the annotation file for one of the images that's causing the error, and any modifications you've made to the code. This information will be crucial in diagnosing the problem more effectively.

Remember, the more specific you can be about your setup and the issue, the easier it will be to provide assistance. 👍

**Comment by ist-am** [comment]
I had the same issue. Resolved by matching image size (`--img-size`) of the input and model (the `--img-size` passed to `train.py`).

**Comment by glenn-jocher** [comment]
@tosfaq Great to hear you resolved the issue! 🎉 Matching the `--img-size` parameter between training and detection is indeed crucial for maintaining consistency in how the model processes images. Thanks for sharing your solution with the community! If anyone else encounters similar issues, ensuring that the image sizes align during both training and detection can be a helpful check. Happy detecting!
