### ISSUE TITLE
running medium or larger model creates an unkillable zombie process

### ISSUE THREAD

**Issue by YourRoommate01** [ultralytics/yolov5#11789]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When running training using train.py with a medium sized YOLOv5 model, after the training completes the process doesn't kill itself and continues using a large portion of GPU and CPU processing power. Here's what still shows in top
   PID     USER  PR  NI    VIRT    RES  SHR S  %CPU  %MEM     TIME+    COMMAND
  10806 [user]  20   0       0      0      0     Z  100.0      0.0     187:30.34  python
After this occurs, neither I or our sysadmin seem to be able to kill the process in any way other than resetting the server (which is a large multi-GPU server run by our university, so there shouldn't be any problem with not having enough processing power). Further attempts at training freeze either right before or right after the process outputs "Starting training for [x] epochs...". I'd do further testing on my own, but resetting the server is a 30-minute process and requires being on-site - most of us do remote work.

### Environment

- YOLOv5 🚀 v7.0-168-gec2b853 Python-3.7.13 torch-1.10.2+cu102 CUDA:1 (Quadro RTX 5000, 16125MiB)
- OS: Ubuntu 20.04.4 LTS
- Python 3.8.5

### Minimal Reproducible Example

python train.py --data [your data] --weights yolov5m.pt

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@YourRoommate01 thank you for reporting this issue. We appreciate your contribution to improving YOLOv5.

The behavior you described, where the training process does not kill itself after completion and continues using GPU and CPU processing power, is unexpected. We apologize for any inconvenience this may have caused.

We will investigate this issue further to identify the root cause and provide a solution. In the meantime, if possible, could you please provide additional information such as the specific dataset you are training on and any custom modifications you have made to the code? This will help us in reproducing the issue and finding a resolution.

If you or your sysadmin are able to capture any error logs or additional information when attempting to kill the process, please share that as well.

Thank you for your patience and cooperation. We will keep you updated on the progress of resolving this issue. If you have any further questions or concerns, please don't hesitate to ask.

**Comment by YourRoommate01** [comment]
Hi! Thanks for the response. I can't link the datasets, but this has
happened on 3 separate datasets, all of plant images, with either 1 or 2
classes at most. The largest dataset included 400 images, and the one I
personally used contains 263 images. All data was trained at the default
image size for the model size. There are no error messages when attempting
to kill the processes, the kill commands run but do not change the number
of processes which are running. In all cases, it turns each instance of
training save one into a process labeled [python] <defunct>. This is true
whether we use the PID directly or pipe ps -x into grep to select all of
the processes causing issues. Further kill commands make no changes to the
processes.

**Comment by glenn-jocher** [comment]
@YourRoommate01 thank you for providing additional information about the issue. We apologize for the inconvenience you are experiencing.

Based on the details you provided, it seems that the training process is not terminating properly and is leaving behind defunct processes. We will investigate this behavior further to determine the root cause and provide a solution.

In the meantime, if you have any additional information or error logs that you can provide when attempting to kill the processes, it would be helpful for us in debugging the issue.

We appreciate your patience and cooperation as we work to resolve this issue. We will keep you updated on our progress. If you have any further questions or concerns, please feel free to ask.

Thank you.
