### ISSUE TITLE
very low GPU usage while training yolov5 on system GPU

### ISSUE THREAD

**Issue by Razamalik4497** [ultralytics/yolov5#11815]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Why GPU usage is very low " 0.6G  gpu_mem " while I train with the same configuration on  colab it uses " 14.6G gpu_mem "  

### Additional

Hello, 
I'm trying to train my Yolov5 on GPU Manli RTX 3060ti, with 62,600 labeled datasets split into 70-30%. 

System Specs : 
- Ryzen 5 5600
- RAM 16GB single slot 
- CPU Core 6 
- GPU RTX 3060ti VRAM 8GB
- Dataset 62601 ( train = 45044, valid =  17557 )

command: 
python train.py --img 640 --batch 1 --epochs 30 --data yolov5/data.yaml --cfg models/yolov5s.yaml --name yolov5s_results --weights "yolov5s.pt"

Question: 
---------------------------------------------------------------------------------------------
Why GPU usage is very low " 0.6G  gpu_mem " while I train with the same configuration on  colab it uses " 14.6G gpu_mem "  
---------------------------------------------------------------------------------------------

My GPU outputs :
Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/29     0.6G   0.08648   0.06779   0.01729      1140       640:  21% 5671/17557 [07:51<26:15,  2.82s/it]

**Comment by glenn-jocher** [comment]
@Razamalik4497 hi there,

The GPU memory usage can vary depending on multiple factors, such as the specific configuration of your system and the number of training workers you use. It is not necessarily indicative of an issue.

In Colab, the GPU memory usage might be higher due to the nature of the environment. However, it is important to note that the YOLOv5 training process is optimized to use the available resources efficiently, so lower GPU memory usage does not necessarily mean that the training process is not working correctly.

If your training is progressing smoothly and you are getting good results, you should not worry too much about the GPU memory usage. YOLOv5 is designed to work with limited resources, and it will adjust its memory usage based on the available GPU memory.

If you encounter any specific issues or errors during training, please do not hesitate to provide more details so that we can assist you further.

Best regards,
Glenn Jocher
