### ISSUE TITLE
Unable to get feature map if path of images (string) are passed as arguments

### ISSUE THREAD

**Issue by nrvora** [ultralytics/yolov5#11836]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Question
I have trained a custom yolov5 model for a specific task, Now I want to use a feature map of the detection layer to further use it in different pipelines. Though I am able to get the feature map, there is one problem.

1. If I pass the image argument as NumPy array:-
    ![image](https://github.com/ultralytics/yolov5/assets/42088255/82800c63-c5e3-4d0e-87d2-66cf3d2ead7e)
    I get output as a list from where I can get my feature map.

2. If I pass the image argument as file path:-
    ![image](https://github.com/ultralytics/yolov5/assets/42088255/3e34211b-eaee-4382-bf1e-7064edd876b4)
    I get output as Detections class from common.py, from where I can get my bounding box but cannot get the feature map

I would like to know why is this the case and also how can I get a feature map given the second case.

I have gone through https://github.com/ultralytics/yolov5/issues/3522 but here it is mentioned to use the detection class of yolo.py but my model uses the detection class of common.py

### Additional

#11581 is on stale, so creating a new one.

**Comment by glenn-jocher** [comment]
@freaksie hi there,

Thank you for reaching out with your question about YOLOv5 and the feature map.

When you pass the image argument as a NumPy array, you receive a list from which you can extract your feature map. However, when you pass the image argument as a file path, you receive the Detections class from common.py, which only provides bounding box information and not the feature map.

To access the feature map in the second case, you can modify the code to use the detection class from yolo.py instead of common.py. This will give you access to the feature map you are looking for.

Please note that this behavior difference is due to how the different detection classes are implemented in YOLOv5. The common.py class focuses on providing bounding box information, whereas the yolo.py class includes additional functionality for accessing the feature map.

I hope this helps! Let me know if you have any further questions or need any additional assistance.

Best regards,
Glenn Jocher

**Comment by nrvora** [comment]
Got it. Thank you for the response @glenn-jocher.

**Comment by glenn-jocher** [comment]
@freaksie you're welcome! I'm glad I could help. If you have any more questions or need further assistance, feel free to ask. Cheers!
