### ISSUE TITLE
opencv::dnn failed load onnx

### ISSUE THREAD

**Issue by nimeng1299** [ultralytics/yolov5#11848]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

from google translator:

pt to onnx
```
python export.py --weights runs/train/exp4/weights/best.pt --include onnx --img 640

I tried
export.py --weights runs/train/exp4/weights/best.pt --include onnx --opset 12
but it still doesn't work
```
when i load onnx in c++ opencv
```
void cvonnx(cv::Mat& input, cv::Mat& output)
{
	try {
		cv::dnn::Net net = cv::dnn::readNetFromONNX("E:\\111\\yolov5s.onnx");
	}
	catch (cv::Exception& e) {
		std::cerr << e.what() << std::endl;
	}
...
}

//error:
OpenCV(4.7.0-dev) C:\GHA-OCV-2\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
> Node [Split@ai.onnx]:(onnx_node!/model.24/Split) parse error: OpenCV(4.7.0-dev) C:\GHA-OCV-2\_work\ci-gha-workflow\ci-gha-workflow\opencv\modules\dnn\src\layers\slice_layer.cpp:274: error: (-215:Assertion failed) splits > 0 && inpShape[axis_rw] % splits == 0 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'
> 
```

How should I convert pt to onnx to be recognized by opencv?

**Comment by glenn-jocher** [comment]
@nimeng1299 hi there! It seems like you're having trouble loading an ONNX model in OpenCV using YOLOv5. 

When converting your `.pt` model to ONNX with YOLOv5, you can try specifying the `--opset` argument to match the version supported by your OpenCV installation. For example, if you have OpenCV 4.7.0-dev, you can try `--opset 12` like you mentioned.

However, the error message you provided indicates an issue with the ONNX model itself. The error `(-215:Assertion failed) splits > 0 && inpShape[axis_rw] % splits == 0` in the `Split` node suggests that there might be an error with the ONNX exporter or with the model itself.

To resolve this, I would suggest the following steps:
1. Make sure you are using the latest version of YOLOv5.
2. Verify that your `best.pt` model is valid and can be loaded in YOLOv5.
3. Try using a different version of OpenCV, or update your current version, to see if the issue persists.
4. Explore alternative methods of loading your model in OpenCV, such as using the TensorFlow backend instead of ONNX.

If after following these steps you still encounter issues, please provide more information, such as the specific versions of YOLOv5, OpenCV, and PyTorch that you're using, as well as any error messages or stack traces you receive. This will help us further diagnose the issue.

Remember, if you don't get a response right away, it could be because other community members might not have encountered this specific issue yet. Thank you for your understanding and patience.

**Comment by nimeng1299** [comment]
> @nimeng1299 hi there! It seems like you're having trouble loading an ONNX model in OpenCV using YOLOv5.
> 
> When converting your `.pt` model to ONNX with YOLOv5, you can try specifying the `--opset` argument to match the version supported by your OpenCV installation. For example, if you have OpenCV 4.7.0-dev, you can try `--opset 12` like you mentioned.
> 
> However, the error message you provided indicates an issue with the ONNX model itself. The error `(-215:Assertion failed) splits > 0 && inpShape[axis_rw] % splits == 0` in the `Split` node suggests that there might be an error with the ONNX exporter or with the model itself.
> 
> To resolve this, I would suggest the following steps:
> 
> 1. Make sure you are using the latest version of YOLOv5.
> 2. Verify that your `best.pt` model is valid and can be loaded in YOLOv5.
> 3. Try using a different version of OpenCV, or update your current version, to see if the issue persists.
> 4. Explore alternative methods of loading your model in OpenCV, such as using the TensorFlow backend instead of ONNX.
> 
> If after following these steps you still encounter issues, please provide more information, such as the specific versions of YOLOv5, OpenCV, and PyTorch that you're using, as well as any error messages or stack traces you receive. This will help us further diagnose the issue.
> 
> Remember, if you don't get a response right away, it could be because other community members might not have encountered this specific issue yet. Thank you for your understanding and patience.

This may be a problem with the opencv 4.7 . After I upgraded to version 4.8, the problem was solved。
version 4.8  support ONNX Split, Slice, Clip (Relu6) and Conv with auto_pad.

**Comment by glenn-jocher** [comment]
@nimeng1299 this may be a problem with the OpenCV 4.7 version you are using. Upgrading to version 4.8 could potentially solve the issue. The newer version (4.8) provides support for ONNX operations such as Split, Slice, Clip (Relu6), and Conv with auto_pad. 

Please try upgrading your OpenCV version to 4.8 and see if the problem persists. In case you continue to encounter any issues, it would be helpful to provide specific details about the versions of YOLOv5, OpenCV, and PyTorch you are using, as well as any error messages or stack traces you receive. This additional information will assist us in further diagnosing the problem.

Please note that response times may vary, as it is possible that other community members may not have encountered the same issue yet. Your patience is greatly appreciated.
