### ISSUE TITLE
YOLOv5 7.0 PR_curve.png,P_curve.png appear legend, x-axis, y-axis display dislocation

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#11845]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component
Training

### Bug
I train the model using this command：`python train.py  --batch-size 8 --epochs 300 --img 1280 --workers 2 --data ./data/allObject.yaml  --weights weights/yolov5m.pt  --cfg models/yolov5m.yaml`  

After I train the model, check the PR_curve.png and P_curve.png picture in the `runs/train/exp` folder,Appears legend, x-axis, y-axis display dislocation.  

![PR_curve](https://github.com/ultralytics/yolov5/assets/9715013/9b806ad9-b0ef-4480-8ad0-281afeb6b64b)

Sometimes there is a problem with PR_curve.png, sometimes there is a problem with P_curve.png

![P_curve](https://github.com/ultralytics/yolov5/assets/9715013/871837bc-50fa-4075-b13c-785edf16511e)

### Environment

- YOLO: YOLOv5 🚀 v7.0 torch 1.7.1+cu11.0 CUDA:11.0
- OS: win11
- Python: 3.8.5

### Minimal Reproducible Example

I just had a problem after training the model,I can't provide a Minimal Reproducible Example.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dapsjj hi there,

Thank you for bringing this issue to our attention. We appreciate your thoroughness in searching for similar bug reports beforehand.

Regarding the PR_curve.png picture displaying dislocation, we apologize for any inconvenience caused. Please note that the issue you mentioned seems to be related to a display problem with the legend, x-axis, and y-axis. 

To better understand and address this issue, it would be helpful if you could provide a minimal reproducible example, or additional information and steps to reproduce the problem. This will greatly assist us in identifying the root cause and finding a solution.

If you have the time and are willing to contribute, we would greatly appreciate your help in submitting a pull request. Any assistance from the community is always welcomed and appreciated.

Thank you again for bringing this to our attention, and we look forward to resolving this issue together.

Best regards,
Glenn
