### ISSUE TITLE
After EarlyStopping, confusion_matrix.png, P_curve.png, PR_curve.png, R_curve.png, results.png are not generated in the runs/train/exp folder

### ISSUE THREAD

**Issue by dapsjj** [ultralytics/yolov5#11850]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

The model training is completed, but after EarlyStopping, confusion_matrix.png, P_curve.png, PR_curve.png, R_curve.png, results.png are not generated in the runs/train/exp folder.

![1](https://github.com/ultralytics/yolov5/assets/9715013/d8453358-e0bc-4927-aa95-a65e6b355b18)

### Environment

- YOLO: YOLOv5 🚀 v7.0 torch 1.7.1+cu11.0 CUDA:11.0
- OS: win11
- Python: 3.8.5

### Minimal Reproducible Example

I just had a problem after training the model,I can't provide a Minimal Reproducible Example.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dapsjj hi there,

Thank you for reaching out. I understand that you are experiencing an issue with the YOLOv5 model training, specifically after EarlyStopping, where the generated files such as confusion_matrix.png, P_curve.png, PR_curve.png, R_curve.png, and results.png are not present in the runs/train/exp folder.

To better assist you, could you kindly provide some additional information? Specifically, it would be helpful to know the following:

1. The command or script you are using for training the model.
2. Any modifications or customizations you have made to the training process.
3. Any relevant error messages or logs generated during training.

Additionally, I would recommend checking the permissions and access rights of the runs/train/exp folder to ensure that the files are being written properly.

Please provide the requested information, and we will do our best to assist you further.

Thank you for your understanding and patience.

Best regards,
Glenn Jocher

**Comment by dapsjj** [comment]
@glenn-jocher 
Hi,I use this command to train:`python train.py  --batch-size 8 --epochs 300 --img 1280 --workers 2 --data ./data/object.yaml  --weights weights/yolov5m.pt  --cfg models/yolov5m.yaml`

There is no error messages generated during training.

**Comment by glenn-jocher** [comment]
@dapsjj 

Thank you for providing the command you are using for training the YOLOv5 model. 

Based on the command you shared, it seems like you are training the model with a batch size of 8, for 300 epochs, using an image size of 1280, and utilizing a pre-trained weight file (`yolov5m.pt`). The data configuration file (`object.yaml`) and model configuration file (`yolov5m.yaml`) are also specified.

Since you mentioned that there are no error messages generated during training, I suspect that the missing files (`confusion_matrix.png`, `P_curve.png`, `PR_curve.png`, `R_curve.png`, and `results.png`) might be related to the early stopping mechanism.

Could you please share more information about the early stopping configuration you have used? This will help in understanding if there are any specific settings or conditions that might prevent the generation of these files.

Additionally, I would recommend checking the evaluation section of your training script to ensure that the code responsible for generating these files is present. You may need to make sure that the code for saving the evaluation outputs (`confusion_matrix.png`, `P_curve.png`, `PR_curve.png`, `R_curve.png`, and `results.png`) is correctly implemented.

Please provide the additional information requested, and I will be glad to assist you further.

Thank you for your patience and cooperation.

Glenn Jocher
