### ISSUE TITLE
NMS  BUG

### ISSUE THREAD

**Issue by wujun007** [ultralytics/yolov5#11859]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

当前克隆的版本启动后，报错异常NMS 

### Environment

显卡使用4080

### Minimal Reproducible Example

Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at C:\b\abs_61prww4bv9\croot\torchvision_1689079992237\work\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\b\abs_61prww4bv9\croot\torchvision_1689079992237\work\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at C:\cb\pytorch_1000000000000\work\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at C:\cb\pytorch_1000000000000\work\aten\src\ATen\core\PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at C:\cb\pytorch_1000000000000\work\aten\src\ATen\functorch\DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at C:\cb\pytorch_1000000000000\work\aten\src\ATen\FunctionalizeFallbackKernel.cpp:280 [backend fallback]

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wujun007 hi there! Thank you for reaching out and reporting this bug.

It looks like you are experiencing an issue with the NMS (Non-maximum Suppression) function in YOLOv5. Based on the error message you provided, it seems that the function `torchvision::nms` is not available for the CUDA backend.

Please make sure that you have the appropriate dependencies installed and that you are using a compatible version of PyTorch. Additionally, ensure that you have followed the installation instructions correctly.

If you are still facing this issue, I encourage you to open a new issue on the YOLOv5 GitHub repository, so that the community and the Ultralytics team can provide you with further assistance. They will be able to guide you through the debugging process and find a solution to this problem.

Thank you for your understanding and willingness to contribute by submitting a PR if necessary. Your support and feedback are greatly appreciated by the entire YOLOv5 community!
