### ISSUE TITLE
[yolov5s][INT8] Quantizing yolov5s model with batch-size > 1 to OpenVINO format

### ISSUE THREAD

**Issue by txlim96** [ultralytics/yolov5#11884]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

When exporting the quantized yolov5s model with batch-size=1, the openvino IR files can be exported
![image](https://github.com/ultralytics/yolov5/assets/30485660/98fa3220-8081-4b03-8f80-e57ee2d0d271)

However, when changing the batch-size to a different number, 4 in this scenario, the following error popped up
![image](https://github.com/ultralytics/yolov5/assets/30485660/e50a8826-6927-4292-9751-8f1b66c33ed3)

It seems to me it somehow is related to the batch size causing some issues in reshaping, however without quantizing (without --int8 argument), the model is able to be exported to openvino IR with different batch sizes, not sure is this a yolov5 repo issue or openvino issue?

### Environment

- YOLO: YOLOv5 🚀 v7.0-193-g485da42 Python-3.10.6 torch-2.0.1+cu117 CPU
- Ubuntu: 22.04
- Python: 3.10.6

### Minimal Reproducible Example

```bash
python3 export.py --weights yolov5s.pt --int8 --include openvino --batch-size 4
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@txlim96 hi there! Thank you for bringing this issue to our attention. We appreciate your detailed report.

Based on the error you encountered when changing the batch size to a different number during the export process, it appears that there might be a reshaping issue related to the batch size. Without quantization (without the `--int8` argument), you mentioned that the model can be successfully exported to openvino IR with different batch sizes.

To determine whether this is a YOLOv5 repository issue or an OpenVINO issue, it would be helpful to investigate further. Could you please provide some additional information?

1. Are you able to export a quantized model with batch size other than 1 using other formats apart from OpenVINO?
2. Have you tried running the quantized model with a batch size other than 1 in other frameworks (e.g., PyTorch) to assess if the error is specific to OpenVINO?

Please let us know your findings, and we will be happy to assist you further in resolving this issue. Thank you for your valuable contribution!

**Comment by txlim96** [comment]
Hi @glenn-jocher,

1. I did try out with other int8-available model formats like coreml and tflite, and they can be exported
2. I did run the quantized tflite model (batch-size=4) with val.py and looks like there is a dimension mismatch error
```bash
# Export model
python3 export.py --weights yolov5s.pt --int8 --include tflite --batch-size 4
# Validation
python3 val.py --weights yolov5s-int8.tflite --batch-size 4
```
![image](https://github.com/ultralytics/yolov5/assets/30485660/4d648566-43da-4daa-a74f-a2bd5a0ce6bd)

**Comment by glenn-jocher** [comment]
Hi @txlim96,

Thank you for providing the additional information. Based on your findings, it seems that the issue lies with the model export process when using batch size other than 1 with quantization. The dimension mismatch error you encountered when running the quantized tflite model with a batch size of 4 further confirms this.

This suggests that there may be certain constraints or limitations when quantizing the model with a batch size other than 1 using YOLOv5's current implementation. It's possible that the reshaping operations during the quantization process are not handling the batch dimension correctly.

To address this issue, I recommend looking into the specific code responsible for the quantization process in YOLOv5 and checking for any potential issues related to reshaping operations with different batch sizes.

Alternatively, you may also consider reaching out to the YOLOv5 community or the Ultralytics team for further assistance. They have extensive knowledge and expertise with the YOLOv5 framework and may be able to provide more insights or guidance on this issue.

Thank you for bringing this to our attention, and, once again, thank you for your valuable contribution to the YOLOv5 project!
