### ISSUE TITLE
A very confusing issues about converting .pt to .onnx

### ISSUE THREAD

**Issue by Greatlover** [ultralytics/yolov5#11886]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I'm getting the following error when trying to convert a Pytorch YoloV5 model to ONNX format:

Traceback (most recent call last):

File "E:\yolov5-master\py_to_onnx.py", line 17, in <module>
    torch.onnx.export(
        
File "E:\anaconda\envs\yolo_v5\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
        
File "E:\anaconda\envs\yolo_v5\lib\site-packages\torch\onnx\utils.py", line 1506, in _export
    with exporter_context(model, training, verbose):
        
File "E:\anaconda\envs\yolo_v5\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
        
File "E:\anaconda\envs\yolo_v5\lib\site-packages\torch\onnx\utils.py", line 176, in exporter_context
    with select_model_mode_for_export(
        
File "E:\anaconda\envs\yolo_v5\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
        
File "E:\anaconda\envs\yolo_v5\lib\site-packages\torch\onnx\utils.py", line 137, in disable_apex_o2_state_dict_hook
    for module in model.modules():

AttributeError: 'dict' object has no attribute 'modules'
No matter how I modify the code, using the official YoloV5 models or my own trained models, I get this error when converting to ONNX. Is there any way to resolve this? Any help would be greatly appreciated!

### Environment

Python 3.9.0
pytroch 1.13.0+cu116
cuda 11.6
yolov5 

### Minimal Reproducible Example

Here is the .py code
import torch
import torch.nn

model_file = 'E:\\yolov5-master\\runs\\train\\exp9\\weights\\best.pt'

export_file = 'E:\\yolov5-master\\export_all\\onnxs\\try\\train\\fuck.onnx'

model = torch.load(model_file)

dummy_input = torch.randn(1, 2, 640, 640)

torch.onnx.export(
    model,
    dummy_input,
    export_file,
    opset_version=11
)

### Additional

Here is the .py code
import torch
import torch.nn

model_file = 'E:\\yolov5-master\\runs\\train\\exp9\\weights\\best.pt'

export_file = 'E:\\yolov5-master\\export_all\\onnxs\\try\\train\\fuck.onnx'

model = torch.load(model_file)

dummy_input = torch.randn(1, 2, 640, 640)

torch.onnx.export(
    model,
    dummy_input,
    export_file,
    opset_version=11
)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Greatlover hi there! It seems like you're encountering an error when trying to convert a PyTorch YOLOv5 model to ONNX format. The error message suggests that the 'dict' object you're using doesn't have the 'modules' attribute.

To resolve this issue, you need to load the YOLOv5 model using the `torch.hub.load` function instead of `torch.load`. Here's an updated version of your code:

```python
import torch
import torch.nn as nn
import torchvision

model_file = 'E:\\yolov5-master\\runs\\train\\exp9\\weights\\best.pt'
export_file = 'E:\\yolov5-master\\export_all\\onnxs\\try\\train\\fuck.onnx'

model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_file)

dummy_input = torch.randn(1, 2, 640, 640)

torch.onnx.export(
    model,
    dummy_input,
    export_file,
    opset_version=11
)
```

Make sure you have the latest version of YOLOv5 installed by running `pip install --upgrade yolov5`. Also, please ensure that you have the correct versions of PyTorch and CUDA installed. In your case, you mentioned using PyTorch 1.13.0, which seems to be a typo. It should be PyTorch 1.7.0 or above.

Let me know if this solves your issue, and don't hesitate to reach out if you have any further questions!
