### ISSUE TITLE
BUG and Solution in yolov5 7.0 yaml.reader.ReaderError: unacceptable character #x0080: special characters are not allowed   in "data\coco.yaml", position 141 

### ISSUE THREAD

**Issue by xibici** [ultralytics/yolov5#11897]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

yaml.reader.ReaderError: unacceptable character #x0080: special characters are not allowed
  in "data\coco.yaml", position 141

### Additional
Solution:

delete  #5 and #6 in the coco.yaml

#5 ├── yolov5
#6 └── datasets

I think that the '├' can not be recognized in win10/win11.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xibici this issue seems to be related to a special character error in the coco.yaml file. To solve this, you can try deleting lines #5 and #6 which contain special characters ('├'). It is possible that these characters are not recognized in Windows 10 or Windows 11.

If this solution works for you, great! If you encounter any further issues or have additional questions, please don't hesitate to ask. We're here to help!
