### ISSUE TITLE
GitHub Desktop in Visual Studio Code, and torch.hub.load()

### ISSUE THREAD

**Issue by GeneRuan** [ultralytics/yolov5#11907]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I'm trying to start a program in Visual Studio Code to use to transfer images to be used for analysis. I already have the dataset created, but I am testing the basics first to see if I understand them. 

I'm using the initial function `torch.hub.load()` to run the inference code as directed in the main page.

```
import torch

# Model
model = torch.hub.load("ultralytics/yolov5", "yolov5s")  # or yolov5n - yolov5x6, custom

# Images
img = "https://ultralytics.com/images/zidane.jpg"  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

However, when I try to run it, it gives me a long list of errors.

```
Traceback (most recent call last):
  File "/Users/generuan/Desktop/Research Reports/pytorch_test1.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', source='github')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 555, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 199, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 156, in _parse_repo_info
    raise RuntimeError(
RuntimeError: It looks like there is no internet connection and the repo could not be found in the cache (/Users/generuan/.cache/torch/hub)
```

I'm using GitHub Desktop to directly run this very repository through, in the same manner as it had worked in Google Colab (which I cannot use by the directions of my given task, due to not being in `.py` format, but in `.ipynb` format). There is nothing I can find online that references Visual Studio Code as a platform, nor using Mac in general.

Is there something I'm doing wrong? I'm following exactly as I'm told, and getting errors constantly.

To recreate:
1. Run the installation code found in the Documentation on the main page.
```
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```
2. Download and open GitHub Desktop. 
3. Add the `Ultralytics/YOLOv5` Repository in GitHub Desktop.
4. Open in Visual Studio Code. Copy and paste the inference code as referenced above.
5. Click "Run Python File". Get error.

(macOS Monterey, version 12.5.1; Python Version 3.9.13; Python Interpreter 3.10.7 64-bit, as listed in VSC)

### Additional

Apologies for the long string of text, but this has frustrated me to no end, and I'm trying to be as detailed as possible. If there's anything I'm missing, write a message and I'll get back once I can.

**Comment by glenn-jocher** [comment]
@GeneRuan it appears that the error you are encountering is related to the internet connection. The error message suggests that there is no internet connection available, and it is unable to find the repository in the cache.

To resolve this issue, please ensure that you have a stable internet connection and try running the code again. Additionally, you can check if you have any network restrictions or firewalls that might be blocking the connection.

If the issue persists, you can try manually downloading the YOLOv5 repository from GitHub and specifying the local path when loading the model. Here's an example:

```python
import torch

# Local path to YOLOv5 repository
repo_path = "/path/to/yolov5"

# Model
model = torch.hub.load(repo_path, "yolov5s")  # or yolov5n - yolov5x6, custom

# Rest of the code...
```

Replace `/path/to/yolov5` with the actual local path where you have cloned the YOLOv5 repository.

Please let me know if this resolves your issue.

**Comment by GeneRuan** [comment]
Unfortunately, it did not. Internet connection is stable, no firewalls or restrictions to speak of. I downloaded and cloned the repository separately, to see if either solution would work, but still coming up short.

This code:
```
import torch

repo_path = "/Users/generuan/Downloads/yolov5-master"

# Model
model = torch.hub.load(repo_path, 'yolov5s')
```

Leads to:
```
Traceback (most recent call last):
  File "/Users/generuan/Desktop/Research Reports/pytorch_test1.py", line 6, in <module>
    model = torch.hub.load(repo_path, 'yolov5s')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 555, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 199, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/hub.py", line 135, in _parse_repo_info
    repo_owner, repo_name = repo_info.split('/')
ValueError: too many values to unpack (expected 2)
```

At the current time point, I have been switching over to Windows 10, as there is more documentation on it, but since I'm less experienced with that, that will only bring more problems. Thank you for taking the time to try though, and I would prefer if it did work in Mac, but alas, it does not.

**Comment by glenn-jocher** [comment]
@GeneRuan i apologize for the inconvenience and the issues you are facing with YOLOv5 on macOS. It seems that the provided code snippet is encountering a "ValueError" due to an error when parsing the repository information.

To further troubleshoot this issue, I would recommend checking the following points:

1. Ensure that the path to the YOLOv5 repository is correct and accessible. Double-check that the repository is cloned successfully at the specified location `/Users/generuan/Downloads/yolov5-master`. You can confirm this by checking the existence of the required files and directories within the repository.

2. Verify that you have the correct version of the torch library installed. YOLOv5 requires PyTorch>=1.7.0. You can check the installed PyTorch version by running `print(torch.__version__)` in your Python environment.

If the above steps do not resolve the issue, you could try the following approach to load the YOLOv5 model:

```python
import torch
from pathlib import Path

# Path to YOLOv5 repository
repo_path = Path("/Users/generuan/Downloads/yolov5-master")

# Load YOLOv5 model
model = torch.load(repo_path / "yolov5s.pt")  # or yolov5m.pt, yolov5l.pt, yolov5x.pt, depending on the desired model

# Rest of the code...
```

This code directly loads the pre-trained YOLOv5 model from the repository without using the `torch.hub.load()` function. Please make sure to adjust the model file name (`yolov5s.pt`, `yolov5m.pt`, etc.) based on the model variant you want to use.

I hope this approach resolves the issue you encountered, and please let me know if you need any further assistance or have additional questions.

**Comment by GeneRuan** [comment]
It does a little better, but now I'm searching for a module named 'models' due to a ModuleNotFoundError, even though it appears as though it no longer exists and is called 'doqu' instead, according to online resources.

```
import torch
from pathlib import Path

# Path to YOLOv5 repository
repo_path = Path("/Users/generuan/Downloads/yolov5-master")

# Load YOLOv5 model
model = torch.load(repo_path / "yolov5s.pt") 
```

```
  File "/Users/generuan/Desktop/Research Reports/pytorch_test1.py", line 8, in <module>
    model = torch.load(repo_path / "yolov5s.pt")  # or yolov5m.pt, yolov5l.pt, yolov5x.pt, depending on the desired model
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'
```

P.S.:
Is there any resources on this venture (`.py` file, Visual Studio Code) that are readily available, or easy enough to locate? Everything I try to find on the subject either use something separate to YOLOv5, or work in `.ipynb`(the file format for Google Colab and other often recommended programs), and it feels like I'm chasing a dead end.

**Comment by glenn-jocher** [comment]
@GeneRuan hi,

Regarding the `ModuleNotFoundError` you are encountering when trying to load the YOLOv5 model, it seems that the module name has been changed in more recent versions of the YOLOv5 repository. As you mentioned, it appears that the module name `models` has been renamed to `doqu`.

You can try modifying the code accordingly to load the model:

```python
import torch
from pathlib import Path

# Path to YOLOv5 repository
repo_path = Path("/Users/generuan/Downloads/yolov5-master")

# Load YOLOv5 model
model = torch.load(repo_path / "doqu" / "yolov5s.pt") 
```

This modification specifies the new module name `doqu` when loading the model.

As for resources related to using YOLOv5 with a `.py` file and Visual Studio Code, it's recommended to refer to the official YOLOv5 documentation. The documentation provides comprehensive information and examples on how to work with YOLOv5 using a `.py` file and different IDEs, including Visual Studio Code.

I hope this helps resolve the error you encountered, and feel free to reach out if you have any further questions.

**Comment by GeneRuan** [comment]
Okay, so I changed the code looking at the documentation, having found the page on Python [here](https://docs.ultralytics.com/usage/python/). And now, my code actually works... only for the pre-trained models.

For the project, I need a custom model to work. While I can train it by running it through the Google Colab tutorial document and downloading it from the files, I cannot run it through in the same way as I had with the pre-trained models.

This works:
```
from ultralytics import YOLO
# Load the model
model = YOLO('yolov5nu.pt')  # load a pretrained model
```

And this does not:
```
from ultralytics import YOLO
# Load the model
model = YOLO('/Users/generuan/Downloads/best.pt')  # load a pretrained model
```

When I run the latter, I get:
```
TypeError: ERROR ❌️ /Users/generuan/Downloads/best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
```

What do I do in this case? I couldn't find a solution online for this, despite combing through many of the YOLOv5 issues and search terms.

P.S.:
While my project technically doesn't need to load images directly, I do need to print and export the results eventually. However, functions like below only give me another error:

```
results.print()
results.show()
---
AttributeError: 'list' object has no attribute 'print'
AttributeError: 'list' object has no attribute 'show'
```

Thank you for the time spent helping me out here.

**Comment by glenn-jocher** [comment]
@GeneRuan hi,

Regarding your first issue with loading a custom model using YOLOv5, it appears that the `best.pt` file you are trying to load is not compatible with the current version of YOLOv5. The error message suggests that the model was originally trained with a previous version of the Ultralytics YOLOv5 repository and is not forwards compatible with YOLOv8.

To resolve this, you have a couple of options. You can either retrain your custom model using the latest version of the Ultralytics `yolov5` package, or you can switch to using a command with an official YOLOv8 model, such as `'yolo predict model=yolov8n.pt'`.

Regarding your second issue with printing and exporting results, it seems that the `results` object you are trying to print or show is actually a list object instead of an expected object type. This is why you encounter the `AttributeError` indicating that a list object has no `print` or `show` attribute.

To address this, you need to make sure that the `results` object is of the expected type. You can refer to the documentation or examples provided by Ultralytics to ensure that you are using the correct methods and object types for printing and exporting results.

I understand that you were unable to find a specific solution for these issues online, but I recommend reaching out to the official Ultralytics YOLOv5 repository or their support channels for further assistance. They would be in the best position to provide specific guidance on loading custom models and working with the results object.

I hope this helps, and please let me know if you have any further questions or need additional assistance.

**Comment by GeneRuan** [comment]
Thank you for all of the assistance. However, I recently had a meeting regarding the research, and while this does work, it had not actually fit the specifications in the project. While I would ask for more (it's in regards to refitting the base YOLOv5/YOLOv8 program to fit a new model), that may be subject to a different issue, as this one has too many to begin with.

Thank you for helping.

**Comment by glenn-jocher** [comment]
@GeneRuan thank you for reaching out and for providing the details of your project's specifications. I apologize if the solution provided did not fully meet your requirements. 

If you have additional questions or need further assistance in refitting the base YOLOv5/YOLOv8 program to fit a new model, I would recommend creating a new issue specifically for that topic. This will allow the community to focus on the new issue and provide relevant guidance and support. 

Please feel free to create a new issue with the necessary details, and we will do our best to assist you. 

Thank you again for reaching out, and we appreciate your understanding.
