### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by Beingbe7** [ultralytics/yolov5#11903]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i run train.py, ValueError: attempted relative import beyond top-level package, how to 解决

**Comment by glenn-jocher** [comment]
@Beingbe7 hi there! 

It seems like you're encountering a `ValueError` with the message "attempted relative import beyond top-level package" when running `train.py`. This error typically occurs when there is an issue with the way you are importing modules or packages within your code.

To help you resolve this issue, could you provide more information about your setup and the specific code where you're seeing this error? This will help us better understand the problem and provide you with a more accurate solution.

Looking forward to your response!

**Comment by Beingbe7** [comment]
I have solved the problem. But now a new problem is that after I annotate the data and fill in the data set path in the data configuration file, he still reports errors：No labels found in /home/rpdzkj/Desktop/zzs/3test/yolo/image.cache, can not start training. why？Is this file being generated automatically? When is that?
![image](https://github.com/ultralytics/yolov5/assets/140502052/2ba4a6d4-6fdc-4a81-95e6-ab4460b3314b)
![c6a42918c094d1e882f3629d42999a8](https://github.com/ultralytics/yolov5/assets/140502052/7ba150b3-ac03-4fff-8aa9-3516b36bb361)

There's something wrong with my data set?

**Comment by glenn-jocher** [comment]
@Beingbe7 it looks like you're encountering an issue with the YOLOv5 training process. 

The error message indicates that no labels were found in the specified image cache path. The image cache file is typically created automatically during the annotation process. 

To resolve this issue, please double-check the following:

1. Ensure that you have correctly annotated your dataset and saved the annotations in the expected format (e.g., YOLO format).
2. Verify that the image cache file (`image.cache`) is present in the specified directory (`/home/rpdzkj/Desktop/zzs/3test/yolo`).

If the image cache file is missing, you may need to re-annotate your dataset or check if there was an issue during the annotation process.

Please let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by Beingbe7** [comment]
@glenn-jocher thanks for your help！
1.This is a screenshot of the image I annotated, in the format yolo
![image](https://github.com/ultralytics/yolov5/assets/140502052/39f637f8-12fb-4580-b615-1e4b8d9dc1d3)
I annotated it on a windows computer and copied it to a linux computer。
2. The image cache file (image.cache) is present in the specified directory (/home/rpdzkj/Desktop/zzs/3test/yolo).But I don't know why there is 0 image after he scans the image.cache. Image. cache is not generated according to the image file?
![image](https://github.com/ultralytics/yolov5/assets/140502052/94a0d1bb-a4b1-4873-810c-1a422b5cd404)
Is there a problem with my folder name? I named image instead of images

**Comment by glenn-jocher** [comment]
@Beingbe7, thank you for providing the additional information. Let's try to troubleshoot the issue.

1. The annotated image you shared seems to be in the correct YOLO format. The format should be `<class index> <x_center> <y_center> <width> <height>` for each bounding box annotation.

2. The presence of the image cache file (`image.cache`) in the specified directory is a good sign. However, it seems that the training script is not able to recognize any images from the cache. This may suggest an issue with the cache file or the image file paths.

To further investigate, could you please check the following:

- Verify that the image cache file contains the correct paths to your annotated images. Each line in the file should correspond to the path of an annotated image.
- Ensure that the image files referenced in the cache file are present in the directory structure and accessible by the training script.
- Confirm that the image file extensions match the annotations (e.g., `.jpg`, `.png`, etc.).

Regarding your folder name, the script should be able to handle an "image" folder instead of an "images" folder, as long as the folder structure and file paths are correctly indicated in the image cache file.

Please let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by Beingbe7** [comment]
@jkocherhans I can start training already, I just changed image to images, I want to know why

**Comment by glenn-jocher** [comment]
@Beingbe7 It's great to hear that you were able to start training by changing "image" to "images". The reason for this change is most likely related to the expected folder structure and naming conventions in the YOLOv5 training script.

By default, the training script expects the annotated images to be stored in a folder named "images" (plural), and the corresponding annotation files to be in the YOLO format. This is the standard convention used in YOLOv5.

In your case, changing "image" to "images" aligns with the expected folder structure, allowing the training script to locate and properly utilize your annotated image dataset.

Please let me know if you have any more questions or if there's anything else I can assist you with.
