### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Iyyappan-vw** [ultralytics/yolov5#11910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

module 'numpy' has no attribute 'object'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Iyyappan-vw** [comment]
n

**Comment by glenn-jocher** [comment]
@Iyyappan-vw hi there! It seems you're facing an attribute error related to the 'numpy' module. To help you out, we need a bit more information. Could you please provide a minimal reproducible example of the code that triggers this error?

By sharing the code, we'll be better equipped to diagnose the issue and provide you with a suitable solution. Thanks for your cooperation!

**Comment by Iyyappan-vw** [comment]
using yolov5 module in commend promp:
> python train.py --img 640 --batch 16 --epoch 100 --data dataset.yaml 
> --weights yolov5s.pt –-name rubber

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid 
this error in existing code, use `object` by itself. Doing this will not 
modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details 
and guidance see the original release note at:
     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by glenn-jocher** [comment]
@Iyyappan-vw thanks for reporting this issue! It appears that you are encountering an `AttributeError` related to the `numpy` module. This error message suggests that `np.object` is no longer a valid attribute in recent versions of `numpy`.

To resolve this issue, you can modify your code to use `object` instead of `np.object`. This change should not impact your code's behavior and is safe. 

If you have any further questions or encounter any additional issues, please feel free to provide a minimal reproducible example of your code so that we can assist you more effectively. Your cooperation is greatly appreciated!
