### ISSUE TITLE
weights trained in higher resolution not working well in lower, while objects are clearly visible

### ISSUE THREAD

**Issue by pydoni** [ultralytics/yolov5#11911]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone!

I've been trying to do some research in license plate ocr, and tried to use yolo to detect the letters at a plate, I've got a medium size dataset with a good accuracy on all characters trained on the standar 640 res, with the images of the dataset having the same size. After the train when I trie to run the weights in a batch of images with size around 100x40 I got almost 0 detections, but when I use it on the test dataset the weights work fine. Do I have to train my network in a lower res? How could I improve the accuracy on thse lower resolution images, the objects are clearly visible so I don't get why the resolution is a problem.

Example of 100x30 image
![EEJ1G87](https://github.com/ultralytics/yolov5/assets/52361210/e20c4e49-36f6-4e6e-9c86-691264d781af)

Example of dataset image
![00c2ea96-e815-47a0-b8e4-e449685ce829_jpg rf 8fb30414e3c990cce838648b448f4223](https://github.com/ultralytics/yolov5/assets/52361210/f19b5330-7beb-471e-bb9e-ec94d6d68688)

**Comment by glenn-jocher** [comment]
@pydoni hi,

The issue you're experiencing is likely due to the difference in resolution between the images you trained on (640x640) and the images you're inference on (100x40). YOLOv5 is sensitive to changes in image resolution, and lower resolution images may cause issues with detection.

To improve accuracy on lower resolution images, you have a few options:

1. Re-train your network on a lower resolution. This will help the model learn to detect objects at the specific resolution you're interested in.

2. Use a different model architecture or modify the existing one to better handle lower resolution images.

3. Augment your training dataset with lower resolution images. This will allow the model to see and learn from examples at the target resolution.

Keep in mind that while YOLOv5 is a powerful object detection model, it may still have limitations in certain scenarios. If you're looking for further improvements, I recommend reaching out to the wider YOLO community or the Ultralytics team for more specific guidance and insights.

Best regards,
Glenn Jocher

**Comment by pydoni** [comment]
Thanks for the answer @glenn-jocher ! I will try to retrain it, thanks!

**Comment by glenn-jocher** [comment]
@pydoni you're welcome! I'm glad I could help. Retraining your network at a lower resolution should help improve accuracy on the lower resolution images. If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
