### ISSUE TITLE
Yolov5 Anchors

### ISSUE THREAD

**Issue by smtalds** [ultralytics/yolov5#11975]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to ask something. I want to quantize and deploy on fpga. Can we retrain with only 1 anchors like [10,14] ?  My output is 13x13x18 , i want to get 13x13x6 maybe (this 6 i guess x,y,w,h,conf,c) ?

**Comment by glenn-jocher** [comment]
@smtalds hi there,

Yes, you can retrain YOLOv5 with custom anchors. In the `models/yolov5.yaml` file, you can change the `anchors` parameter to your desired anchor size, such as `[10, 14]`. 

To get the output shape of `13x13x6`, you need to update the model architecture accordingly. In the `models/yolov5s.yaml` file, you can modify the final convolutional layer to output 6  values for each grid cell.

Please note that modifying the anchor size and output shape may affect the model's performance and accuracy. It's recommended to experiment and fine-tune these changes based on your specific requirements and dataset.

I hope this helps! Let me know if you have any further questions.

Note: The YOLOv5 community and the Ultralytics team have contributed to the development and maintenance of the YOLOv5 repository.

**Comment by smtalds** [comment]
OK, I'll try. I think this issue should stay open for a while. I can feed back.

**Comment by smtalds** [comment]
@glenn-jocher Hi Glenn , its worked. Thanks for you. Can i ask a question ? When i detect with video, model is detected objects but for photo, it can not detect. Also , for validation , model is detected for labels but for predict its not worked. Is it about `train.py` file ? Can have to configure this file too ?

**Comment by glenn-jocher** [comment]
@smtalds Hi! Glad to hear that the custom anchors worked for you!

Regarding the detection issue with photos and validation, it's unlikely to be related to the `train.py` file configuration. More likely, this issue is related to the input pipeline or inference scripts.

I'd recommend checking the inference script or the code you are using for photo detection and validation. It's crucial to ensure that the input images are being pre-processed in the same way as during training and that the inference code is correctly loading the model and running the detection.

If you're using the YOLOv5 inference script, please ensure that the input images are in the correct format and size, and that the model and weights are properly loaded and initialized before running inference.

Feel free to provide more details about your setup or code if you need further assistance!

The YOLOv5 community and the Ultralytics team have put in significant effort to develop and maintain the YOLOv5 repository.
