### ISSUE TITLE
Different result on detect.py or one line inference by torch.hub()

### ISSUE THREAD

**Issue by MohammadsAdrA-AI** [ultralytics/yolov5#11989]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I saw some other people mention that but because you guys couldn't replicate the issue you abandoned them. 
but you can test yolov5m.pt with this image, you can see my result as well. 
the source image: 
![UOG-5](https://github.com/ultralytics/yolov5/assets/77414512/3019b414-9127-4d9c-a0a1-95b9ebd379a3)
when I run :
```
python detect.py --source UOG-5.jpg --weight yolov5m.pt 
```
the result is: 
![UOG-5](https://github.com/ultralytics/yolov5/assets/77414512/9299de0e-7d1b-415b-9c86-06abd6e0dea2)
but when I run the torch hub command: 
```
model = torch.hub.load('ultralytics/yolov5', 'yolov5m')
frame = cv2.imread('/home/sadra/yolov5/fad-images/UOG-5.jpg')
results = model(frame)
res = results.pandas().xyxy[0]
print(res)
```
the results are different: 

![Uploading image.png…]()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MohammadsAdrA-AI** [comment]
xmin        ymin        xmax        ymax  confidence  class  \
0  478.912598  127.212547  939.188782  633.890564    0.593158      0   
1  528.975830  232.735260  588.229248  345.902679    0.286835     67   

         name  
0      person  
1  cell phone

**Comment by MohammadsAdrA-AI** [comment]
anyone tried this?

**Comment by glenn-jocher** [comment]
@MohammadsAdrA-AI yes, many people have tried using YOLOv5 both with the `detect.py` script and with one-line inference using `torch.hub.load()`. Both methods are widely used and reliable for object detection tasks. If you are experiencing a difference in results between the two, it could be due to various factors such as different default thresholds or different post-processing settings. It would be helpful if you could provide more details about the specific issue you are facing, such as the specific differences you are observing in the results. This will allow us to better assist you in resolving the issue.
