### ISSUE TITLE
urllibError, training on computer without internet

### ISSUE THREAD

**Issue by lixiaoqingnnz** [ultralytics/yolov5#11997]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to train custom data in a computer without internet. I downloaded the whole repository and installed all the necessary packages. However, when I trained the model, it appeared an error:
urllib.error.URLError: <urlopen error [Error104] Connect reset by peer>

The error appeared after the following message:
TensorBoard: Start with 'tensorboard --logdir runs/train', view at https://localhost:6006/
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...

Therefore, I think the error appears because the computer has no internet, so it can not go to the url and download files. 

I think the solution is to download all the resources, such as the fonts, before training the model. But how could I know what resources that I need to download in advance?

Thanks!

**Comment by davidzwart** [comment]
Im also experiencing this issue and managed to bring it a step further:
- tensorboard install is not required in latest version
- fonts predownloaded
- Release asset for yolo*.pt predownloaded

Now I've spotted the git fetch/git pull and requirements checks. Those are possibly impeding the air-gapped execution of YoloV5.

**Comment by glenn-jocher** [comment]
@lixiaoqingnnz you are correct in your assessment. The error is likely due to the inability to access external resources without an internet connection. You can download the required resources in advance by following these steps:

1. Manually download the required resources, such as fonts, and place them in the appropriate directories as specified in the code or configuration files.

2. Check the specific references to external resources in the code, such as font or weight files, and ensure these are available locally before initiating the training process.

Let me know if you need further assistance with this.
