### ISSUE TITLE
Webcam Connected detect.py

### ISSUE THREAD

**Issue by Choi-YoungHyun** [ultralytics/yolov5#12019]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I'm Student

I have some questions

I want to get detect class name to webcam if I press the key which is 'esc'

So I start command key "python detect.py --weight best.py --source 0
But When I press 'esc' but Webcam is not shutdown... 

I want  to ask How do I stop it by pressing 'esc'?

**Comment by glenn-jocher** [comment]
@Choi-YoungHyun hello there!

To stop the webcam stream by pressing the "esc" key during object detection with YOLOv5, you can modify the `detect.py` script as follows:

1. Open the `detect.py` file in your code editor.
2. Locate the code block that processes key events. It should look something like this:

```python
def run(img):
    ...
    while True:
        ...
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Press 'q' to exit
            break
        ...
    ...
```

3. Modify the code to check for the "esc" key instead of the "q" key:

```python
def run(img):
    ...
    while True:
        ...
        key = cv2.waitKey(1) & 0xFF
        if key == 27:  # Press 'esc' to exit
            break
        ...
    ...
```

Now, when you run the `detect.py` script and press the "esc" key, the webcam stream should stop.

I hope this helps! Let me know if you have any further questions.
