### ISSUE TITLE
有人做过中文文字识别训练嘛？或者能推荐下，比较容易上手的项目？

### ISSUE THREAD

**Issue by xiayuer0114** [ultralytics/yolov5#12013]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

中文文字识别训练问题，如题，谢谢！

**Comment by glenn-jocher** [comment]
@xiayuer0114 hello! YOLOv5 is primarily focused on object detection rather than text recognition. However, there are other popular projects and libraries specifically designed for Chinese text recognition, such as [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) and [EasyOCR](https://github.com/JaidedAI/EasyOCR).

These projects provide pre-trained models and comprehensive documentation, making it easier for you to get started with Chinese text recognition. I recommend exploring these projects to find a suitable solution for your training needs. Good luck with your project!
