### ISSUE TITLE
dataset auto-download error

### ISSUE THREAD

**Issue by ampelmannnys** [ultralytics/yolov5#12024]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I understand that some datasets, including coco dataset, can be downloaded automatically over the link, but when I run the code myself, I get the following error. I was struggling alone with the py files related to downloading, but I was confused after confirming that the general.py file I received on git was different from the file on the official website. Please check.
![문의글](https://github.com/ultralytics/yolov5/assets/107301769/4f5f9bb4-b1c1-463a-ab30-a8fc2958fef7)

**Comment by glenn-jocher** [comment]
@ampelmannnys hi there,

Thanks for reaching out. It seems that you are facing an issue with the auto-download functionality for datasets. 

The error you're encountering might be due to a mismatch between the `general.py` file you have and the one on the official website. To resolve this, make sure you have the latest version of the `general.py` file from the official Ultralytics YOLOv5 repository.

If you continue to face problems, it would be helpful if you could provide more details about the specific error message you are receiving. This will enable us to assist you more effectively.

Thank you!

**Comment by ampelmannnys** [comment]
This is the result of the general.py file, the latest version of the official Ultraetics YOLOv5 repository. It was to mention that the git clone file and the file on the website are different. 
Please check again the following link that can be downloaded automatically except for coco/coco128.
https://github.com/ultralytics/yolov5/releases/download/v1.0/

**Comment by glenn-jocher** [comment]
@ampelmannnys thanks for bringing this to our attention.

We apologize for the confusion. The `general.py` file you have received from the GitHub repository might not be up to date. We recommend downloading the latest version of the file from the official Ultralytics YOLOv5 repository.

Regarding the auto-download functionality for datasets such as coco/coco128, it's important to note that these datasets are not included in the default auto-download process. However, you can manually download them from the link you provided.

If you have any further questions or need assistance with anything else, please don't hesitate to let us know.

Thank you!
