### ISSUE TITLE
Can you help me with activating exe file?

### ISSUE THREAD

**Issue by whitenugul** [ultralytics/yolov5#12029]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

HI I'm a student.
I'm trying to make an exe file with yolov5 model with pyinstaller module. I created Scenario.py in yolov5 folder to make .exe file.
However when I created exe file with pyinstaller module and activated it. I got an error which is 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\82107\\AppData\\Local\\Temp\\_MEI184402\\ultralytics\\cfg\\default.yaml'. 
I've never heard of default.yaml... so can you help to solve my problem?

**Comment by glenn-jocher** [comment]
@whitenugul hi there! I'd be happy to help you with your issue.

The error you encountered indicates that the default.yaml file is missing. This file is needed for the correct execution of the yolov5 model within the .exe file. The default.yaml file contains configuration settings for the model.

To resolve this issue, you need to include the default.yaml file in your .exe file. One way to accomplish this is by modifying the pyinstaller command you used to create the .exe file, to include the default.yaml file as a resource to be bundled.

You can refer to the pyinstaller documentation for more information on how to include additional files as resources in the .exe file. Specifically, check out the `--add-data` option or the `datas` parameter in the spec file.

Let me know if you need further assistance or have any other questions!

**Comment by whitenugul** [comment]
Thank you for your advice :)

However, I'm still confused for creating default.yaml file.

Can you show me an example for default.yaml file?
Also, I thought that when I created exe file, _MEI folder should be created in Temp folder, but I have noticed that _MEI folder wasn't created.... if you know anything about that can you give me additional advice..?

**Comment by glenn-jocher** [comment]
@whitenugul i understand your confusion. The default.yaml file contains configuration settings for the yolov5 model. You can find an example default.yaml file in the yolov5 repository in the `configs` folder. This file specifies various parameters such as model architecture, input size, training settings, and more.

To create a default.yaml file, you can make a copy of the example default.yaml file from the yolov5 repository and modify it according to your needs.

Regarding the issue with the _MEI folder not being created, this can be caused by various factors. One possibility is that the pyinstaller command or configuration you used to create the .exe file is not correctly including the required folders and files. I recommend double-checking your pyinstaller command or configuration to ensure that it correctly includes all the necessary resources, including the default.yaml file.

If the issue persists, please provide more details about the steps you took, the specific command or configuration you used, and any error messages you encountered. This will help in diagnosing the issue and providing further assistance.

Let me know if you have any other questions or concerns!

**Comment by ramihatim** [comment]
@whitenugul you will find the default.yaml file in the cfg folder, since you're using pyinstaller you can use this script:

`pyinstaller --add-data "your-path/default.yaml:." your_script.py
`
hope this helps :)

**Comment by glenn-jocher** [comment]
@ramihatim Thanks for reaching out! You can find the default.yaml file in the cfg folder of the YOLOv5 repository. When using pyinstaller to create the .exe file, you can include the default.yaml file using the `--add-data` option. You can use the following script as an example:

```bash
pyinstaller --add-data "your-path/default.yaml:." your_script.py
```

Make sure to replace "your-path" with the actual path to the default.yaml file and "your_script.py" with your script's name. This will ensure that the default.yaml file is included in the .exe file.

I hope this helps! Let me know if you have any further questions.

**Comment by whitenugul** [comment]
@ramihatim Thanks for your help I solved the problem!!
By the way, I have additional Questions...

I'm trying to train yolov5 model on jupyter notebook with using GPU. 
I used codes below however there was a problem though I found my gpu number is 0 with nvidia-smi

python train.py --data "C:\Users\WIN10\Desktop\folder\custom.yaml" --epochs 1 --device "cuda:0"
python train.py --data "C:\Users\WIN10\Desktop\folder\custom.yaml" --epochs 1 --device 0

Can you help me with these problems?

**Comment by glenn-jocher** [comment]
@whitenugul That's great to hear that you solved the problem! 
Now, regarding your additional questions:

When training YOLOv5 on a Jupyter notebook using a GPU, you need to ensure that all the necessary dependencies are properly installed. Please make sure you have installed the CUDA toolkit, cuDNN, PyTorch with GPU support, and the required Python packages. 

If you have confirmed that your GPU is accessible and working correctly (as you mentioned using nvidia-smi), you can specify the GPU device in the `--device` argument as you did in your command:
```bash
python train.py --data "C:\Users\WIN10\Desktop\folder\custom.yaml" --epochs 1 --device "cuda:0"
```
or
```bash
python train.py --data "C:\Users\WIN10\Desktop\folder\custom.yaml" --epochs 1 --device 0
```
Both of the commands you provided should work correctly. They specify that training should be done on GPU number 0, which is `"cuda:0"` or simply `0`. Make sure the GPU device number you are using is correct and matches the actual GPU device.

If you are still encountering issues, please provide more details such as any error messages you are receiving or any other relevant information that can help in troubleshooting the problem.

Let me know if there's anything else I can assist you with!

**Comment by pubpy2015** [comment]
@glenn-jocher @whitenugul 

in yolov5 repository dont have config or cfg folder, or default.yaml file.
![ảnh](https://github.com/ultralytics/yolov5/assets/59004953/b7a64fd7-882b-496f-a21f-4e385f8b4380)

So, can i copy it from yolov8 repository "https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg" ?

**Comment by glenn-jocher** [comment]
@pubpy2015 the yolov5 repository indeed does not have a specific folder called "config" or "cfg," nor does it contain a default.yaml file. The file structure and configuration format may differ between the yolov5 and yolov8 repositories.

Instead of copying the default.yaml file from the yolov8 repository, I suggest following the configuration guidelines provided in the yolov5 repository. The yolov5 repository includes a wiki page that explains how to create and modify the yaml configuration files needed for training and inference.

Please refer to the yolov5 wiki for comprehensive instructions on configuring the model for your specific use case. Make sure to follow their guidelines to achieve the desired results.

Let me know if you have any further questions or need additional assistance!

**Comment by pubpy2015** [comment]
Thanks,
 The error: "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\yolov5-7.0_07092023\\dist\\PlateDetect\\ultralytics\\cfg\\default.yaml'"
![ảnh](https://github.com/ultralytics/yolov5/assets/59004953/cc05f6b2-4dd2-487a-a15a-c212a1e82531)

only happens when I use Pyinstaller to create the exe file and run it.

Python code still works fine and this also only happens with the latest yolov5 code (yolov5 6.2 and 7.0 does not have this error).

**Comment by glenn-jocher** [comment]
@pubpy2015 this error occurs when using Pyinstaller to create the .exe file and run it. It seems to be specific to the latest version of yolov5 (6.2 and 7.0). The error message indicates that the default.yaml file is not found in the specified directory.

To resolve this issue, you can try including the default.yaml file as a resource in your Pyinstaller command. This will ensure that the file is bundled correctly in the .exe file. You can refer to the Pyinstaller documentation for more information on how to include additional files as resources.

Additionally, you can also check if the file paths in your code are correct and accessible when running as an .exe file. Make sure that the paths are relative or absolute to the correct location.

Please let me know if you need further assistance or have any other questions!

**Comment by pubpy2015** [comment]
Hi,

Looks like this is a function of yolov8 mixed in with yolov5.
In yolov8, I see here:
![ảnh](https://github.com/ultralytics/yolov5/assets/59004953/ed9d7d93-08cd-4947-b152-c20789f38fbb)

But in yolov5 I don't see anything like that.

**Comment by glenn-jocher** [comment]
@pubpy2015 hi,

Yes, you are correct. The feature you are referring to is specific to YOLOv8 and is not present in YOLOv5. In YOLOv8, there is a specific file structure and configuration setup that includes the "config" folder and the use of a default.yaml file.

However, in YOLOv5, the file structure and configuration format have been simplified, and the default.yaml file is not included. Instead, YOLOv5 relies on command-line arguments to specify the training and inference configurations.

If you have any further questions or need assistance with YOLOv5, please feel free to ask.

Thanks!

**Comment by pubpy2015** [comment]
Thanks,

using this command: pyinstaller **--collect-data ultralytics** PlateDetect.py

It will create the folder ultralytics\cfg as follows:
![ảnh](https://github.com/ultralytics/yolov5/assets/59004953/cfabcb01-b53e-4fd3-aa36-c58b3785b78c)

Or simply copy only "default.yaml" file from YOLOV8, the program can run normally.

**Comment by glenn-jocher** [comment]
@pubpy2015 hi,

It appears that you have encountered an issue related to the creation of an executable file using PyInstaller in YOLOv5. In the command you mentioned, "pyinstaller --collect-data ultralytics PlateDetect.py", it creates the folder "ultralytics\cfg" as shown in the image you provided.

Alternatively, you mentioned that simply copying the "default.yaml" file from YOLOv8 allows the program to run normally. However, please note that YOLOv5 and YOLOv8 have different file structures and configuration formats. Simply copying the "default.yaml" file from YOLOv8 may not provide the desired results.

If you have any specific issues or questions related to YOLOv5, please feel free to provide more details so that we can assist you further.

Thank you!
