### ISSUE TITLE
How should I integrate GhostNetV2 into C3 and bottleneck modules? Just like in the yolov5s-ghost.yaml officially provided by the author

### ISSUE THREAD

**Issue by nortorious** [ultralytics/yolov5#12026]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I try to directly replace the bottleneckV2 in ghostnetV2 with the ghostbottleneck in yolov5, but an error will occur.

I want to know how to modify C3GhostV2, GhostBottleneckV2 so that yolov5 can run correctly

thanks a lot

**Comment by glenn-jocher** [comment]
@nortorious hi there,

To integrate GhostNetV2 into the C3 and bottleneck modules of YOLOv5, you can follow the structure and configuration provided in the `yolov5s-ghost.yaml` file available in the official repository. However, please note that directly replacing the bottleneckV2 in GhostNetV2 with the ghostbottleneck in YOLOv5 may result in an error.

In order to modify C3GhostV2 and GhostBottleneckV2 to ensure proper functioning of YOLOv5, I recommend referring to the official code and documentation of GhostNet, as well as the YOLOv5 code. This will give you a better understanding of how these components are implemented and help you make the necessary modifications.

Feel free to reach out if you have any further questions or need additional assistance.

Thank you!
