### ISSUE TITLE
Custom video prediction Failed

### ISSUE THREAD

**Issue by JoabDavid** [ultralytics/yolov5#1202]
I was using the following command to make predictions on my custom video but the predictions stop after a certain frame.

!python detect.py --weights /content/yolov5/runs/exp0_yolov5s_results/weights/best.pt --source /content/yolov5/GH011314.MP4 --output inference/output

![yolov5detections_1rnmep6](https://user-images.githubusercontent.com/64147683/97094221-2d1e7700-1653-11eb-83c1-25b169eba0db.png)

**Comment by glenn-jocher** [comment]
@JoabDavid Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a new `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible with [COCO](https://cocodataset.org/#home) or [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, ensure your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Ammad53** [comment]
<img width="1147" alt="Screenshot 2020-10-29 at 7 08 06 PM" src="https://user-images.githubusercontent.com/13869900/97614446-3f653000-1a1a-11eb-8ba3-e09bd395c671.png">
<img width="1401" alt="Screenshot 2020-10-29 at 7 08 55 PM" src="https://user-images.githubusercontent.com/13869900/97614452-41c78a00-1a1a-11eb-8699-e16279f83410.png">
<img width="1204" alt="Screenshot 2020-10-29 at 7 07 09 PM" src="https://user-images.githubusercontent.com/13869900/97614529-57d54a80-1a1a-11eb-9050-8e0e6ae72779.png">

Video inference was working fine. With a recent update, it stopped working.  I have attached 3 screenshots. 
In my pycharm, previous version of yolov5, it's working fine. It used to work fine on google colab with the latest update, it is broken. What should I do in the latest update?

**Comment by glenn-jocher** [comment]
Video inference is working correctly. Tested today 29 October 2020.

<img width="1273" alt="Screenshot 2020-10-29 at 21 53 48" src="https://user-images.githubusercontent.com/26833433/97631519-667b2c00-1a31-11eb-8921-f44276938e49.png">
