### ISSUE TITLE
IndexError: The shape of the mask [3, 2] at index 1 does not match the shape of the indexed tensor [3, 11] at index 1

### ISSUE THREAD

**Issue by Lanson426** [ultralytics/yolov5#12046]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I was using yolov5 2.0, I kept having different problems with the training data,but some problems have been solved.

Traceback (most recent call last):
  File "train.py", line 469, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 291, in train
    loss, loss_items = compute_loss(pred, targets.to(device), model)  # scaled by batch_size
  File "D:\Code\yolov5-2.0\utils\utils.py", line 444, in compute_loss
    tcls, tbox, indices, anchors = build_targets(p, targets, model)  # targets
  File "D:\Code\yolov5-2.0\utils\utils.py", line 533, in build_targets
    a, t = at[j], targets[j]  # filter
IndexError: The shape of the mask [3, 2] at index 1 does not match the shape of the indexed tensor [3, 11] at index 1

I know that the new version of yolov5 will not be a problem but I can only use version 2.0 because the other project is yolov5+deepsort using yolov5-2.0

I hope I can get your help！thanks

**Comment by glenn-jocher** [comment]
@Lanson426 hi there! It looks like you're encountering an `IndexError` while using YOLOv5 version 2.0. The error message suggests that the shape of the mask [3, 2] doesn't match the shape of the indexed tensor [3, 11].

To better understand your issue, could you provide some additional information? Specifically, it would be helpful to know:

1. The command or script you ran that resulted in the error.
2. The structure and format of your training data.
3. Any modifications you made to the YOLOv5 codebase.

Additionally, please note that YOLOv5 v2.0 might have some compatibility issues. It's recommended to use the latest version of YOLOv5, which has undergone significant improvements and bug fixes. However, if you're working on a project that specifically requires YOLOv5 v2.0, please let us know the reason, and we'll do our best to assist you.

Looking forward to your response so that we can help you further!
