### ISSUE TITLE
inference on a video with pytorch hub

### ISSUE THREAD

**Issue by inginfor** [ultralytics/yolov5#12047]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i am loading a model from PYTORCH HUB and doing inference like this

import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
imgs = ['https://ultralytics.com/images/zidane.jpg'] # batch of images
results = model(imgs)
results.print()
results.save() # or .show()
results.xyxy[0] # img1 predictions (tensor)
results.pandas().xyxy[0]

with images it works but not with videos how can I make inference on video with pytorch hub?

**Comment by glenn-jocher** [comment]
@inginfor hi there,

To perform inference on a video using PyTorch Hub, you need to use the `yolov5s` model module provided by the Ultralytics repository. However, currently, the PyTorch Hub version of YOLOv5 only supports image inference and doesn't include video support.

If you'd like to perform inference on a video, you can refer to the official Ultralytics YOLOv5 repository (https://github.com/ultralytics/yolov5) and use their code examples and guides.

Feel free to ask if you have any further questions or need additional assistance.

Kind regards,
Glenn Jocher

**Comment by inginfor** [comment]
passing as a parameter to the above code the path of a video from error how to process a video

**Comment by glenn-jocher** [comment]
@inginfor hi there,

To process a video using the code you mentioned, you would need to modify it slightly. Instead of passing a list of image URLs to the `model` function, you need to provide a path to your video file. Here is an example:

```python
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
video_path = 'path/to/your/video.mp4'
results = model(video_path)
results.print()
results.save()  # or .show()
```

Make sure to replace `'path/to/your/video.mp4'` with the actual path to your video file. This should allow you to process the video using YOLOv5.

Let me know if you have any further questions.

Regards,
Glenn Jocher

**Comment by inginfor** [comment]
I had already tried to do so but ot gives an error so I asked
UnidentifiedImageError: cannot identify image file

**Comment by glenn-jocher** [comment]
@inginfor hi there,

The error you're encountering, `UnidentifiedImageError: cannot identify image file`, typically occurs when the image file specified is not in a valid format or cannot be opened. 

In the case of processing a video, you might be mistakenly providing the path to a video file instead of an image file. The `model` function expects an image file path or a list of image file paths, not a video file path.

To process a video, you'll need to use a different approach. In the Ultralytics YOLOv5 repository, there are examples and guides available specifically for video processing. I recommend checking the repository's documentation for proper video processing techniques.

If you have any more questions or need further assistance, feel free to ask.

Best,
Glenn Jocher

**Comment by inginfor** [comment]
@glenn-jocher thanks.
Why running detect.py and doing inference loading the model with pytorch hub come out different results even if you set the same confidence thresholds etc.?

**Comment by inginfor** [comment]
thanks

**Comment by glenn-jocher** [comment]
@inginfor hi there!

Thank you for reaching out to us. We appreciate your interest in YOLOv5 and your feedback.

Regarding your question, the current PyTorch Hub version of YOLOv5 provided by Ultralytics only supports image inference and does not include video support.

If you would like to perform inference on a video, I recommend referring to the official Ultralytics YOLOv5 repository. They provide code examples and guides specifically for video processing.

If you have any further questions or need additional assistance, please don't hesitate to ask.

Kind regards,
Glenn Jocher
