### ISSUE TITLE
YOLOv5 OBB Inference with OpenCV DNN

### ISSUE THREAD

**Issue by zijian98** [ultralytics/yolov5#12056]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have tested out one of the variant of yolov5 which can detect oriented bounding boxes in DOTA dataset and I am wondering if anyone had successfully implemented their model and run inference with C++ code?

This is the repo but the author seems to be inactive: https://github.com/hukaixuan19970627/yolov5_obb 

Thank You!

**Comment by glenn-jocher** [comment]
@zijian98 hi there,

Thank you for reaching out. While I'm not aware of anyone specifically implementing the YOLOv5-oriented bounding box (OBB) variant and running inference with C++ code, it is certainly possible to do so.

You can start by referring to the YOLOv5 [PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/) for the official PyTorch model weights. From there, you can use a PyTorch C++ extension to load the model and run inference on your images.

To implement the YOLOv5 OBB variant, you can take inspiration from the repository you shared (https://github.com/hukaixuan19970627/yolov5_obb). While the author may be inactive, you can still examine the codebase and adapt it to your needs.

Feel free to ask for further clarification or assistance if needed. Good luck with your project!

**Comment by zijian98** [comment]
Hi @glenn-jocher ,

Thanks for the reference links. Maybe I can start off with running inference with an exported ONNX model using Python OpenCV DNN first. I have read through the codes for both your YOLOv5 and the obb variant and the main difference would be the input data having an extra "theta" parameter to determine the angle of rotation of the bounding box.

The issue I am facing is extracting the detected bbox information from the output. From your pre-trained YOLOv5s, I understand that the output shape (25200, 85) represents 25200 rows of predictions with 85 values in it (5 for bbox information and confidence and 80 for class probabilities). 

Using the same preprocessing method for the OBB variant also allows me the generate the correct output shape dimension (25200 201) which can be verified in their Detect.py script. However, I am not sure why are there 201 values in each row when we only trained 16 classes from DOTA dataset. 

This may not be the right repo to ask but hope that you can share some expertise regarding this post processing. You can also correct me should I mentioned any wrong information based on my own understanding.

Thank You!

Reference python code for usage with original YOLOv5 models: https://github.com/doleron/yolov5-opencv-cpp-python/blob/main/python/yolo.py

**Comment by glenn-jocher** [comment]
@zijian98,

You're correct that the OBB variant will have an additional "theta" parameter for the bounding box rotation angle. As for the output shape from the model, while the standard YOLOv5 model outputs a tensor of shape (N, 85), the OBB variant should output a tensor of shape (N, 201) for 16 classes.

This discrepancy could be due to the format used for representing the oriented bounding boxes, which may include additional parameters such as the rotation angle and dimensions. To better understand the output format, I recommend consulting the specific implementation details within the OBB variant, especially the `Detect.py` script you mentioned.

Although I can't provide specific details on the OBB variant repository you referenced, you can consider examining the post-processing steps within their code to understand how the output tensor is handled and interpreted for inference results.

Remember, the YOLOv5 community and the Ultralytics team are valuable resources for expertise on model variants and their implementations. Best of luck, and feel free to ask for further clarification or assistance.

**Comment by Sriyab002** [comment]
@glenn-jocher hello. 
i have been working on point cloud object detection and was wondering if i can use yolov5_obb model. I could train the model with 2D bird eye view images of the kitti dataset and implement detection right?
