### ISSUE TITLE
How to only get the metrics with yolov5 ? 

### ISSUE THREAD

**Issue by le02146** [ultralytics/yolov5#12061]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Now, I have two folders where each saved the annotated yolo format label txt files and  predicted files, how to only evaluate the `precision, recall or f1-score, map@50 `based on these two folders? 

I find that pycocoapi do not have the metrics of precision, recall or f1-score.

Thanks.

**Comment by glenn-jocher** [comment]
Hi there!

To evaluate the metrics such as precision, recall, F1-score, and mAP @le02146 based on the annotated YOLO format label txt files and predicted files in two folders, you can use the `test.py` script provided in the YOLOv5 repository.

Here's an example command to run the evaluation:
```
python test.py --data your_data.yaml --weights your_weights.pt --test-txt folder1 --predictions folder2
```

Make sure to replace `your_data.yaml` with your dataset configuration file, `your_weights.pt` with your trained model weights, and `folder1` and `folder2` with the paths to your annotation txt files folder and predicted files folder, respectively.

Please note that the mAP@50 evaluation metric is only available for COCO-style datasets. If your dataset is not in COCO format, you might need to convert it to COCO format or adapt the evaluation script accordingly.

Let me know if you have any further questions or need additional assistance!

**Comment by le02146** [comment]
@le02146 , Thank you so much for your answer! 
But in my case, I have used the `yolov5` (or other model like `yolov6,7,8，yolox `with other tools/packages  ) to obtain the predicted results (txt) file. I do not need `the trained model ` to predict again. 
Why should I define  `--weights `in the command?

**Comment by glenn-jocher** [comment]
@le02146, thank you for your question! In the `test.py` script, the `--weights` argument is used to specify the path to the trained model weights. This argument is required because the evaluation process needs to load the model in order to compare the predicted results with the ground truth labels.

Even though you have already obtained the predicted results (txt) files using YOLOv5 (or other models like YOLOv6, YOLOv7, YOLOv8, YOLOX) with other tools/packages, you still need to provide the model weights so that the evaluation script can load the model architecture and apply the same network inference process as during training. This is necessary to ensure consistent evaluation metrics such as precision, recall, F1-score, and mAP.

If you don't have the trained model weights, you can consider using the `--weights` argument to provide the path to a pre-trained YOLOv5 model that closely matches the architecture and task of your original model.

Please let me know if you have any more questions or if there's anything else I can assist you with!

**Comment by Naren83** [comment]
Hi @glenn-jocher  , This was the process i done untill now ,

Step 1 : Labelled my dataset using Roboflow, I have the coco format of the test dataset ( Ground truth labels )

Step 2 : Trained the model using the google colab using ultra analytics and run an inference on the test images. I have the test images ( Predicted ones ) with the bounding boxes but not the Coco format

Can you please tell me the best  and easy way to find out the metrics such as mAP, IoU , Precision and recall for my model ?

**Comment by glenn-jocher** [comment]
@Naren83 hi there!

To calculate metrics such as mAP, IoU, precision, and recall for your model, you can follow these steps:

1. Convert your predicted bounding box results to the COCO format: Since you have the test images with the predicted bounding boxes but not in the COCO format, you can use the `XYXY` format (xmin, ymin, xmax, ymax) in a text file for each image. Each line in the file should contain the predicted bounding box in the format `label_id confidence_score xmin ymin xmax ymax`. You can create a separate text file for each image.

2. Use the COCO API: The COCO API provides evaluation functions to calculate metrics such as precision, recall, and mAP. It requires the ground truth annotations (coco format) and the predicted bounding boxes (converted to coco format) to perform the evaluation. You can use the `cocoapi` Python package to work with the COCO API.

   - Install the `cocoapi` package:
     ```
     pip install cython; pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
     ```

   - Write a Python script to calculate the metrics:
     ```
     import json
     from pycocotools.coco import COCO
     from pycocotools.cocoeval import COCOeval
     
     # Load ground truth annotations
     gt_coco = COCO('path_to_ground_truth_annotations.json')
     
     # Load predicted bounding boxes in COCO format
     pred_coco = gt_coco.loadRes('path_to_predicted_bounding_boxes.json')
     
     # Run COCO evaluation
     coco_eval = COCOeval(gt_coco, pred_coco, 'bbox')
     coco_eval.evaluate()
     coco_eval.accumulate()
     coco_eval.summarize()
     ```
     Make sure to replace `'path_to_ground_truth_annotations.json'` with the path to your ground truth annotations file in COCO format and `'path_to_predicted_bounding_boxes.json'` with the path to your predicted bounding boxes in COCO format.

This approach will allow you to evaluate the metrics, including mAP, IoU, precision, and recall for your model based on the ground truth annotations and predicted bounding boxes in the COCO format.

I hope this helps! Let me know if you have any further questions.

**Comment by Naren83** [comment]
Hello @glenn-jocher .Thanks for the response

My ground truth labels are in this format  - 0 0.4359375 0.52109375 0.3375 0.95390625 
and predicted labels are in this format - 1 0.445312 0.523438 0.39375 0.953125 0.936459
 

Do you mean i should first convert this into XYXY format (xmin, ymin, xmax, ymax) and then into COCO format whis is label_id confidence_score xmin ymin xmax ymax ?

**Comment by glenn-jocher** [comment]
@Naren83 yes, you need to convert your ground truth labels and predicted labels into the XYXY format (xmin, ymin, xmax, ymax), and then into the COCO format which includes label_id, confidence_score, xmin, ymin, xmax, and ymax.

The XYXY format represents the coordinates of the top-left and bottom-right corners of the bounding boxes. 

Here's an example of the conversion:

Ground truth label: 0 0.4359375 0.52109375 0.3375 0.95390625
- Convert to XYXY format: xmin = 0.4359375, ymin = 0.52109375, xmax = 0.4359375 + 0.3375, ymax = 0.52109375 + 0.95390625

Predicted label: 1 0.445312 0.523438 0.39375 0.953125 0.936459
- Convert to XYXY format: xmin = 0.445312, ymin = 0.523438, xmax = 0.445312 + 0.39375, ymax = 0.523438 + 0.953125

To convert to COCO format, you will need to include the label_id, confidence_score, xmin, ymin, xmax, and ymax for each bounding box. The confidence_score represents the confidence or probability score assigned to the predicted label.

Please make sure to perform this conversion for all the ground truth labels and predicted labels in your dataset.

Let me know if you need any further clarification or assistance!

**Comment by Naren83** [comment]
Hey @glenn-jocher . Thanks for the information. Hereby attaching my coco files for the predicted and ground lables XYXY format. Would this be enough to calculate metrics or should i have to change anything to my coco files annotations 
[New Compressed (zipped) Folder.zip](https://github.com/ultralytics/yolov5/files/12588219/New.Compressed.zipped.Folder.zip)

**Comment by glenn-jocher** [comment]
@Naren83 hello,

Thank you for sharing the COCO files for the ground truth and predicted labels in the XYXY format. These files will be helpful for calculating the evaluation metrics.

To ensure the accuracy of the evaluation metrics, please make sure that your COCO files follow the required format. Specifically, ensure that each annotation contains the following information: label_id, confidence_score, xmin, ymin, xmax, and ymax. This format is necessary for the COCO API to compute metrics such as mAP, IoU, precision, and recall correctly.

Please let me know if you have any further questions or need any additional assistance.

Thank you!

**Comment by Naren83** [comment]
Hello @glenn-jocher ,

As the json format i shared contains the following information -   image_id , catergory id , comfidence score , xmin, ymin, xmax, ymax. Do i have to remove the category id values and try the code you provided to me ?

**Comment by glenn-jocher** [comment]
@Naren83 hi there!

You can keep the category id values in your coco json file while using the code provided. The category id is used to identify the object category associated with each bounding box. The COCO API takes this into account during the evaluation process, allowing you to calculate metrics such as mAP, IoU, precision, and recall for specific object categories.

So, there is no need to remove the category id values from your json file. The evaluation code will still work properly with the provided format.

Let me know if you have any further questions or need any more assistance.

**Comment by Naren83** [comment]
Hello @glenn-jocher 

Traceback (most recent call last):
  File "\metrics.py", line 7, in <module>
    coco_gt = COCO(ground_truth_file)
  File "\venv\lib\site-packages\pycocotools\coco.py", line 83, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
AssertionError: annotation file format <class 'list'> not supported

These are the errors i am struggling with the code you provided. Do i have to change the annotation format ?

**Comment by glenn-jocher** [comment]
@Naren83 hello,

The `AssertionError` you encountered indicates that the annotation file format is not supported by the COCO API. Specifically, it expects the annotation file to be in dictionary format, but it appears to be in list format.

To resolve this issue, you need to ensure that your annotation file is in the correct format. The correct format for the annotation file is a dictionary containing the required fields such as `images`, `annotations`, `categories`, etc.

You may need to review the code responsible for generating the annotation file and make sure it follows the correct format. You can refer to the COCO dataset format documentation to understand the required fields and their structure.

If you have any further questions or need additional assistance, please let me know.

Thank you!

**Comment by leeeenammmmm** [comment]
Hi @glenn-jocher, now i don't find file test.py in yolov5 repository. Can you show me the link to this file. Thank you!

**Comment by glenn-jocher** [comment]
Hello,

The `test.py` script is no longer a standalone file in the YOLOv5 repository. The testing functionality has been integrated into the `val.py` script, which is used for validating the model on a dataset.

To evaluate your model on a test set and obtain metrics, you can use the `val.py` script with the `--task test` argument. This will run the model on the test set and provide you with the precision, recall, mAP @leeeenammmmm.5, and other metrics.

If you need further assistance or have any more questions, feel free to ask.

Thank you!

**Comment by leeeenammmmm** [comment]
Thank you for your response @glenn-jocher, 

But when I read source code of val.py, I don't see the arg --test-txt and --predictions.  

I want to calculate the matrics from to file predict.txt and label.txt.

**Comment by glenn-jocher** [comment]
@leeeenammmmm hello,

Apologies for the confusion. The `val.py` script is designed to validate a model against a dataset in the expected YOLOv5 format, not to directly calculate metrics from `.txt` files.

If you want to calculate metrics from `.txt` files containing predictions and labels, you would need to write a custom script or modify an existing one to parse these files and compute the desired metrics.

The YOLOv5 repository does not provide a ready-made script for this specific purpose. You would typically use the `val.py` script with a dataset in the correct format to evaluate the model's performance.

For custom evaluation from `.txt` files, you might need to:
1. Parse your ground truth and prediction `.txt` files to extract the bounding boxes and class labels.
2. Use a library or write your own functions to calculate IoU and apply the necessary logic to compute precision, recall, F1-score, and mAP.

If you have any further questions or need additional guidance, please let me know.

Thank you!

**Comment by jintaoyang0729** [comment]
> @glenn-jocher  hi there!
> 
> To calculate metrics such as mAP, IoU, precision, and recall for your model, you can follow these steps:
> 
> 1. Convert your predicted bounding box results to the COCO format: Since you have the test images with the predicted bounding boxes but not in the COCO format, you can use the `XYXY` format (xmin, ymin, xmax, ymax) in a text file for each image. Each line in the file should contain the predicted bounding box in the format `label_id confidence_score xmin ymin xmax ymax`. You can create a separate text file for each image.
> 2. Use the COCO API: The COCO API provides evaluation functions to calculate metrics such as precision, recall, and mAP. It requires the ground truth annotations (coco format) and the predicted bounding boxes (converted to coco format) to perform the evaluation. You can use the `cocoapi` Python package to work with the COCO API.
>    
>    * Install the `cocoapi` package:
>      ```
>      pip install cython; pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
>      ```
>    * Write a Python script to calculate the metrics:
>      ```
>      import json
>      from pycocotools.coco import COCO
>      from pycocotools.cocoeval import COCOeval
>      
>      # Load ground truth annotations
>      gt_coco = COCO('path_to_ground_truth_annotations.json')
>      
>      # Load predicted bounding boxes in COCO format
>      pred_coco = gt_coco.loadRes('path_to_predicted_bounding_boxes.json')
>      
>      # Run COCO evaluation
>      coco_eval = COCOeval(gt_coco, pred_coco, 'bbox')
>      coco_eval.evaluate()
>      coco_eval.accumulate()
>      coco_eval.summarize()
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      Make sure to replace `'path_to_ground_truth_annotations.json'` with the path to your ground truth annotations file in COCO format and `'path_to_predicted_bounding_boxes.json'` with the path to your predicted bounding boxes in COCO format.
> 
> This approach will allow you to evaluate the metrics, including mAP, IoU, precision, and recall for your model based on the ground truth annotations and predicted bounding boxes in the COCO format.
> 
> I hope this helps! Let me know if you have any further questions.

hello,

I just tried your method, and I noticed that my results do not include P and R: 
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.52s).
Accumulating evaluation results...
DONE (t=0.18s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.538
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.758
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.597
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.010
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.214
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.581
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.643
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.697
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.697
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.074
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.363
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.744

Is it because I have some misunderstanding about P and R, and they seem to be quite different from the P and R calculated by YOLOv5? 

I look forward to your reply.

**Comment by glenn-jocher** [comment]
Hello!

It looks like you're doing great with the COCO API evaluation! The metrics you're seeing, such as Average Precision (AP) and Average Recall (AR), are indeed versions of precision and recall, but they are calculated over a range of IoU thresholds and object sizes, which is typical in COCO evaluation.

In the COCO metric system:
- **AP** is an integrated measure of precision across different recall levels, averaged over multiple IoU thresholds (from 0.5 to 0.95).
- **AR** measures the maximum recall given a fixed number of detections per image.

These metrics are more comprehensive than single-value precision and recall, as they account for performance across various conditions, providing a robust measure of detector performance.

If you're looking for traditional single-threshold precision and recall, you might need to adapt or extend the evaluation script to calculate these at a specific IoU threshold (e.g., 0.5). This involves modifying the COCOeval object's parameters or processing its outputs accordingly.

Keep up the good work, and let me know if you need further clarification or assistance! 😊

**Comment by jintaoyang0729** [comment]
@glenn-jocher Thank you very much for your reply. However, it seems that the calculation of P and R similar to YOLO has not been completed.

Can the P and R be calculated directly from the following metrics:

loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type bbox
DONE (t=0.52s).
Accumulating evaluation results...
DONE (t=0.18s).
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.538
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.758
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.597
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.010
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.214
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.581
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.643
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.697
Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.697
Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.074
Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.363
Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.744

Can these values be directly used to calculate the Precision and Recall similar to YOLO?

I write the code:

     coco_p_all = coco_p[:, :, :, 0, 2]
    
    
    map = np.mean(coco_p_all[coco_p_all>-1])
    
    coco_p_iou50 = coco_p[0, :, :, 0, 2]
    map50 = np.mean(coco_p_iou50[coco_p_iou50>-1])
    mp = np.array([np.mean(coco_p_iou50[ii][coco_p_iou50[ii]>-1]) for ii in range(coco_p_iou50.shape[0])])
    mr = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
    mf1 = 2 * mp * mr / (mp + mr + 1e-16)
    i = mf1.argmax()  # max F1 index
    

    
    
    pf = '%-16s' + '%12i' * 2 + '%12.3g' * 5  # print format
    # LOGGER.info(pf % ('all', val_dataset_img_count, val_dataset_anns_count, mp[i], mr[i], mf1[i], map50, map))
    print(f"{mp[i]*100:.1f} {mr[i]*100:.1f} {map50*100:.1f} {map_75:.1f} {map*100:.1f}")
    
The above code's calculated Precision and Recall, are they the same as the Precision and Recall in YOLO?

**Comment by glenn-jocher** [comment]
Hello @jintaoyang0729,

The values you've obtained from the COCO API (AP and AR across various IoU thresholds and object sizes) are indeed comprehensive metrics, but they are calculated differently from the straightforward precision and recall metrics typically reported in YOLO evaluations.

In YOLO, precision and recall are usually calculated at a specific IoU threshold (often 0.5) for each class and then averaged. The COCO metrics provide a more integrated view across multiple IoU thresholds.

Your code snippet attempts to extract and average precision values at IoU=0.50 and calculate F1 scores, which is a good approach if you want metrics more aligned with traditional YOLO outputs. However, keep in mind that these values, while informative, might still not exactly match YOLO's calculations due to differences in methodology, especially in how negatives are handled and the averaging process across different classes and IoU thresholds.

For exact YOLO-like precision and recall, you would need to directly compare the true positives, false positives, and false negatives at your chosen IoU threshold, without integrating across a range as COCO does.

Hope this helps clarify things! 😊
