### ISSUE TITLE
torch hub load

### ISSUE THREAD

**Issue by inginfor** [ultralytics/yolov5#12076]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I didn't understand if you can load with pytorch hub a model trained with a custom dataset it can be done.
If you do this
 model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')
 what happens? is best.pt a model saved locally on your PC once the yolo model has been trained with a custom dataset?

**Comment by glenn-jocher** [comment]
@inginfor yes, you can load a model trained with a custom dataset using `torch.hub.load`. When you use the code `model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')`, it will load the model saved locally on your PC at the specified path (`path/to/best.pt`). The model should be a `.pt` file containing the trained weights of the custom YOLOv5 model. If you have any further questions, feel free to ask.

**Comment by inginfor** [comment]
@glenn-jocher thanks.
Why running detect.py and doing inference loading the model with pytorch hub come out different results even if you set the same confidence thresholds etc.?

**Comment by glenn-jocher** [comment]
@inginfor the results obtained from running `detect.py` and doing inference by loading the model with PyTorch Hub might differ due to various reasons. It is important to note that PyTorch Hub loads the model with default settings, which might differ from the settings used in `detect.py` such as anchor priors, augmentation, or other specialized configurations.

To ensure consistent results, you can manually load the model and use the same settings as `detect.py`, including confidence thresholds, input image size, and any other parameters that might affect the inference process.

If you have further questions or need assistance, please let me know.

**Comment by inginfor** [comment]
thanks

**Comment by glenn-jocher** [comment]
@inginfor hi there,

Thanks for reaching out. It looks like you're encountering different results when running `detect.py` and doing inference by loading the model with PyTorch Hub, even when using the same confidence thresholds.

There could be a few reasons for this discrepancy. One possibility is that the default settings used by PyTorch Hub might differ from the settings used in `detect.py`. This includes factors such as anchor priors, augmentation, or other specialized configurations.

To ensure consistent results, I recommend manually loading the model and using the same settings as `detect.py`. This way, you can ensure that all the parameters, including confidence thresholds, input image size, and any other relevant factors, remain consistent.

If you have any further questions, feel free to ask. We're here to help!

Regards,
Glenn Jocher
