### ISSUE TITLE
what's the difference between these two rknn formats?

### ISSUE THREAD

**Issue by K-tang-mkv** [ultralytics/yolov5#12097]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![3cc149425322e02da4be4ee24a0c0bd](https://github.com/ultralytics/yolov5/assets/59059785/123cf494-1b46-4433-bbed-288c23f7bed4)
The left rknn model is exported from yolov5.onnx using rknntoolkit1.7.3, and the right rknn model is exported using rknntoolkit1.5.
Why did I get these two different type format of rknn? I saw someone using rknntoolkit1.7.3 to get the right format, but I always can't get it.

**Comment by glenn-jocher** [comment]
@K-tang-mkv the difference between the two RKNN formats is likely due to changes or improvements in the rknntoolkit between versions 1.5 and 1.7.3. It is not uncommon for software tools to undergo updates that introduce changes in the way models are exported or saved.

If you are unable to get the desired format using rknntoolkit1.7.3, it may be worth checking the documentation or release notes of the toolkit to see if there are any specific instructions or requirements for exporting the RKNN model in the desired format.

If you continue to encounter difficulties, feel free to provide more information about the steps you followed and any error messages you received, so that we can further assist you.
