### ISSUE TITLE
About the pretrained model of yolov5s-LeakyReLU

### ISSUE THREAD

**Issue by jasonchenPJ** [ultralytics/yolov5#12096]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
Is there any pretrained models of yolov5s-LeakyReLU available for download?

**Comment by glenn-jocher** [comment]
@jasonchenPJ yes, there are pretrained models available for the yolov5s-LeakyReLU variant. You can download the pretrained models from the YOLOv5 repository's `weights` folder. These models can be used for various computer vision tasks such as object detection and image classification. Let me know if there's anything else I can help you with!

**Comment by jasonchenPJ** [comment]
Thanks for your reply,
But, I can't found the `weights` folder under the YOLOv5 repository.
![image](https://github.com/ultralytics/yolov5/assets/47911137/51fb189e-3d6a-4354-8755-1d6f34912d9c)

In my case the edge device didn't support SiLu operator so I need changed to LeakyReLU activation.
Fortunately I found the [yolov5s-LeakyReLU.yaml](https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5s-LeakyReLU.yaml), it match our requirements perfectly.
But I can't found the pre-trained weight download link.

**Comment by glenn-jocher** [comment]
@jasonchenPJ the `weights` folder is located in the `yolov5` repository. To access it, you can clone the repository using the following command:

```bash
git clone https://github.com/ultralytics/yolov5.git
```

Regarding your specific requirement for the `yolov5s-LeakyReLU` variant, you can find the corresponding configuration file `yolov5s-LeakyReLU.yaml` in the `models/hub` folder of the repository. However, there is currently no pre-trained weight download link available specifically for the `yolov5s-LeakyReLU` model. 

If you need to use the `LeakyReLU` activation instead of `SiLU` on your edge device, you can train the model using your own dataset or fine-tune an existing model using the configuration file mentioned above.

Let me know if you have any further questions or need additional assistance!

**Comment by jasonchenPJ** [comment]
Understood,thanks.

**Comment by glenn-jocher** [comment]
@jasonchenPJ hi there! I understand that you are looking for pretrained models of the yolov5s-LeakyReLU variant. Currently, there are no pre-trained weights specifically available for yolov5s-LeakyReLU. However, you can find the configuration file for yolov5s-LeakyReLU in the models/hub folder of the YOLOv5 repository. If you need to use the LeakyReLU activation instead of the SiLU activation on your edge device, you can train the model using your own dataset or fine-tune an existing model. Let me know if you have any other questions or need further assistance!
