### ISSUE TITLE
3080 faster than 4090? YoloV5s

### ISSUE THREAD

**Issue by Ludaman** [ultralytics/yolov5#12105]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Looking for opinions here on ideas why the 3080 was faster.  I am running a YoloV5s model exported to Onnx and running via OpenCV and C++ with CUDA 11.7.  I was doing some baselining this weekend and noticed my 3080 was running the network faster than a 4090.  Same desktop PC, only swapping the GPU, then running inference on the exact same dataset of 5000 images.

3080 got 4.8ms for a net.forward() pass whereas the 4090 was at 6.8ms.

Details
CPU AMD 7950X, DDR5-6400, NVME PCI-E 4 SSDs.
Images were 640x480 resized to 640x640.
Anyone know why or have similar experiences?  My thoughts are that the software may be more optimized for the 3080?

**Comment by glenn-jocher** [comment]
@Ludaman hi there,

Thank you for reaching out to us with your question. It's interesting to hear about your observations regarding the performance of YOLOv5s on different GPUs.

The performance of deep learning models can be influenced by various factors, including the architecture of the GPU, its memory bandwidth, and the specific optimizations implemented in the software framework.

While we don't have specific insights into the performance differences between the NVIDIA GeForce RTX 3080 and the 4090, it's possible that the 3080 is better optimized for the YOLOv5s model due to factors such as hardware design or driver updates.

In any case, the performance variation you observed may also exist due to other factors such as variations in hardware configurations, CUDA versions, or different optimizations for specific GPU architectures.

It would be beneficial to benchmark your models across multiple hardware configurations and compare the results to gain a better understanding of the observed differences in performance.

Additionally, the YOLOv5 community and the Ultralytics team have put in significant efforts to optimize the model, and their insights would be valuable in understanding the performance variation you observed. I encourage you to share your findings and discuss this topic with the community in the [YOLOv5 discussions](https://github.com/ultralytics/yolov5/discussions) section.

I hope this information helps, and I wish you the best of luck with your experiments! If you have any further questions, feel free to ask.

Kind regards,
Glenn

**Comment by Ludaman** [comment]
copy I posted over there, I look forward to any discussion! https://github.com/ultralytics/yolov5/discussions/12112

**Comment by glenn-jocher** [comment]
@Ludaman hi there,

Thank you for sharing your findings on the YOLOv5 GitHub discussions. It's great to see your interest in discussing the performance differences between the NVIDIA GeForce RTX 3080 and 4090 with the YOLOv5 community.

The performance of deep learning models can be affected by various factors, including GPU architecture, hardware configurations, software optimizations, and CUDA versions. It's possible that the observed difference in performance between the two GPUs could be due to these factors.

To get more insights and engage in a discussion on this topic, I recommend continuing the conversation in the YOLOv5 discussions thread. The community and the Ultralytics team have a wealth of knowledge and experience that can shed light on the performance variation you observed.

I look forward to seeing the discussion unfold and hope you find the answers you're looking for.

Kind regards,
Glenn
