### ISSUE TITLE
Error loading with torch hub

### ISSUE THREAD

**Issue by ammar3010** [ultralytics/yolov5#12123]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I am loading model using torch hub by below code.

```
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True, trust_repo=True)
```

It is giving this error:

```
Traceback (most recent call last):
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 49, in _create
    model = DetectMultiBackend(path, device=device, fuse=autoshape)  # detection model
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 356, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 60, in _create
    model = attempt_load(path, device=device, fuse=False)  # arbitrary model
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aidev/VectraCom/crowd_count/counter_yolo.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/aidev/anaconda3/envs/person_count/lib/python3.10/site-packages/torch/hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 93, in yolov5s
    return _create('yolov5s', pretrained, channels, classes, autoshape, _verbose, device)
  File "/home/aidev/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 78, in _create
    raise Exception(s) from e
Exception: PytorchStreamReader failed reading zip archive: failed finding central directory. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
```

### Environment

-OS: Ubuntu 22.04
-Python: 3.10.12

### Minimal Reproducible Example

import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True, trust_repo=True)

### Additional

I tried creating new environment and started from scratch but still the same error.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ammar3010 hi there,

Thanks for reaching out and providing detailed information about the error you encountered when loading the YOLOv5 model using torch hub. 

The error message suggests that there is an issue with the PyTorch file reading process, specifically with finding the central directory in the zip archive. This could be caused by a caching problem or an outdated cache.

To resolve this issue, you can try the following steps:
1. Add the `force_reload=True` parameter to your `torch.hub.load` function call. This will force a reload of the model and clear any cached files.
2. Make sure you have the latest version of the YOLOv5 repository and the dependencies installed. You can do this by running `pip install --upgrade yolov5`.
3. Check if there are any conflicting packages or dependencies in your environment that might be causing the issue. You can try creating a fresh environment and installing the necessary packages from scratch.
4. If the issue persists, you can try reinstalling PyTorch and torch hub.

Please give these steps a try and let us know if the issue is resolved. If you are still experiencing the error, please provide additional information about your environment and any error logs that you receive.

We appreciate your willingness to help by submitting a PR. Feel free to create one if you have any fixes or improvements to contribute to the YOLOv5 project.

Please note that the YOLOv5 GitHub repository is maintained by the Ultralytics team, and any updates or fixes to the model implementation are a collaborative effort by the YOLO community.

Kind regards,
Glenn Jocher

**Comment by ammar3010** [comment]
I've done all the steps you mentioned above but I am still getting the same error.

**Comment by glenn-jocher** [comment]
@ammar3010 your code works correctly for me in Google Colab, so it's likely an issue with local code or perhaps you need to update your dependencies including `pip install -U ultralytics`

<img width="1257" alt="Screenshot 2023-09-15 at 11 57 51" src="https://github.com/ultralytics/yolov5/assets/26833433/2bc857be-6bcb-4000-9dc3-1915161fb25a">

**Comment by ammar3010** [comment]
Okay thanks

**Comment by glenn-jocher** [comment]
@ammar3010 hi there,

I'm sorry to hear that you're still experiencing the same error even after trying the suggested steps. 

To further troubleshoot the issue, it would be helpful to have more information about your environment, such as the versions of PyTorch, torch hub, and other relevant dependencies you are using. Additionally, any error logs or stack traces you can provide would be beneficial in identifying the cause of the problem. 

In the meantime, I recommend reaching out to the YOLOv5 community or the Ultralytics team directly for further assistance. They may have encountered similar issues and could provide more specific guidance based on your setup. 

I appreciate your patience and willingness to contribute. If you have any further questions or need additional help, please don't hesitate to ask. 

Thanks,
Glenn Jocher
