### ISSUE TITLE
Running yolov5 in deepstream

### ISSUE THREAD

**Issue by AbhishekPSI7042** [ultralytics/yolov5#12122]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,

I have converted the yolov5 model in tensorrt engine and in onnx too. now when I run the model in deepstream it is giving error NvDsInfer Error: NVDSINFER_CONFIG_FAILED.

SEND ME TO SOLUTION.

**Comment by AbhishekPSI7042** [comment]
I used custom dataset to train yolov5 and converted in tensorrt engine and onnx and then running in deepstream. There it is giving error NvDsInfer Error: NVDSINFER_CONFIG_FAILED.

Solve this issue..

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042 hi,

It looks like you encountered an error while running YOLOv5 in Deepstream and received the "NvDsInfer Error: NVDSINFER_CONFIG_FAILED" message.

To help you solve this issue, could you provide some additional information such as the specific command or script you used to convert the model to TensorRT engine or ONNX format? Also, please check that you have installed all the necessary dependencies and versions required for Deepstream.

In the meantime, you can try the following troubleshooting steps:

1. Ensure that the Deepstream configuration file is correctly set up and points to the location of your converted model.
2. Double-check that the model conversion process was successful without any errors or warnings.
3. Verify that the input data to the Deepstream pipeline matches the expectations of the YOLOv5 model (e.g., correct input shape, data format, preprocessing steps).
4. Confirm that the required libraries and dependencies for Deepstream and YOLOv5 are installed and up-to-date.

If the issue persists, please provide more details about your setup and any error logs or messages you received, so that we can better assist you in finding a solution.

Keep in mind that YOLOv5 is an open-source project maintained by the Ultralytics team, and we strive to provide the best community support possible. If you have any other questions or concerns, feel free to ask.

Let's debug this issue together!

**Comment by AbhishekPSI7042** [comment]
@glenn-jocher Hello,

So, I have use this command "**python export.py --weights yolov5s.pt --include torchscript onnx**" for converting the yolov5 model in onnx and tensorrt engine and now when I pass this engine to deepstream there it is giving this error and my deepstream version is 6.0 and I'm using jetson nano.

The complete error is :- 
"**Error in NvDsInferContextImpl::buildModel()**"
"**Error in NvDsInferContextImpl::generateBackendContext()**"
"**Error in NvDsInferContextImpl::initialize()**"
"**Config file path: mconfig.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED**"

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042

Hello,

I can see that you are encountering an error while trying to use the converted YOLOv5 model in Deepstream. The error message you provided indicates that there is an issue with the NvDsInfer configuration, resulting in the "NVDSINFER_CONFIG_FAILED" error.

To help you resolve this issue, I have a few suggestions:

1. Confirm that the Deepstream configuration file is properly set up and references the correct paths to your converted model and other required files. Make sure to double-check the paths in the configuration file to eliminate any potential errors.

2. Verify that the model conversion process to the TensorRT engine or ONNX format completed successfully without any errors or warnings. Confirm that you are using the correct version of the model and the appropriate conversion script. 

3. Ensure that you have installed all the necessary dependencies and versions required for both Deepstream and YOLOv5. Check that the version of Deepstream you are using is compatible with your setup, including the operating system and CUDA version.

Please try these troubleshooting steps and let me know if the issue persists. If possible, provide any error logs or additional details that may help in diagnosing the problem further.

I'm here to assist you, so don't hesitate to ask any more questions or provide more information.

**Comment by AbhishekPSI7042** [comment]
@glenn-jocher 

I have checked all the things you have but it is giving same error. For converting yolov5 model in tensorrt engine I followed this github [repo ](https://github.com/mailrocketsystems/JetsonYolov5) and I successfully run the engine and inferencing is done successfully but when the same engine I passed to the deepstream it is giving error.

**Comment by RizwanMunawar** [comment]
@AbhishekPSI7042 I have tested the YOLOv5 model multiple times on Jetson Nano with Deepstream, it works fine. You can follow the [YOLOv5-DeepStream-Documentation](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md). You can also check [Yolov5+DeepSteam Error](https://forums.developer.nvidia.com/t/yolov5-deepsteam-error/226595).

**Comment by AbhishekPSI7042** [comment]
@RizwanMunawar hii,

Could you please upload your config file and proto file for reference, I want to check with my files.

**Comment by RizwanMunawar** [comment]
@AbhishekPSI7042, when running YOLOv5 with Deepstream, there's no need for a proto file to be generated. All you require is the engine file along with the [configuration file](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/config_infer_primary_yoloV5.txt).

You can follow the instructions outlined in this [documentation](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv5.md) step by step, and everything will work by the end.

**Comment by AbhishekPSI7042** [comment]
@RizwanMunawar,

**Comment by AbhishekPSI7042** [comment]
@RizwanMunawar , All the errors that were shown before are gone now I'm getting only one error which is this "**ERROR: Deserialize engine failed because file path: /home/photon/dev/=/home/photon/Downloads/New_Engine_12072022/new-model.engine open error**" please help me to resolve this issue.

**Comment by RizwanMunawar** [comment]
@AbhishekPSI7042! Please try to run the Deepstream command with sudo. Also, I see your path is wrong in the configuration file. The path should be like `/home/photon/Downloads/New_Engine_12072022/new-model.engine`.

**Comment by AbhishekPSI7042** [comment]
@RizwanMunawar , Sorry for that path mistake, I gave right path but still getting same error, so I'm uploading my [code](https://github.com/AbhishekPSI7042/deepstream). Could you please check it and solve this issue, I have jetson nano deepstream 6.0 and command to run this is **sudo ./vasd2**

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042

Thank you for providing your code. I understand that despite correcting the path, you are still encountering the same error when running the command `sudo ./vasd2` on your Jetson Nano with Deepstream 6.0.

After reviewing your code, I noticed that the issue might be related to the incorrect configuration of the `appsrc` element in your Deepstream pipeline. Make sure that you have set the correct parameters such as `caps`, `is-live`, and `format` for the `appsrc` element to match your input source.

Additionally, please verify that all the required plugins and dependencies for Deepstream are properly installed and up-to-date on your Jetson Nano.

If the issue persists, it would be helpful if you could provide the specific error logs or messages that you are encountering during execution. This will allow us to further investigate and provide a more accurate solution.

Please remember that the YOLOv5 repository mainly focuses on the YOLOv5 model itself, and the Deepstream integration is a separate topic. Feel free to reach out to the Deepstream community or Nvidia support for further assistance with Deepstream-related issues.

I hope this guidance leads you closer to resolving the issue. If you have any further questions or concerns, please don't hesitate to ask.

Happy coding!

**Comment by AbhishekPSI7042** [comment]
@glenn-jocher @RizwanMunawar 
Getting these errors please check.

**ERROR: [TRT]: 1: [pluginV2Runner.cpp::load::290] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)**

**ERROR: [TRT]: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)**
**ERROR: Deserialize engine failed from file: /home/photon/Downloads/New_Engine_12072022/best.engine**

**Comment by glenn-jocher** [comment]
@AbhishekPSI7042 hi,

The errors you're encountering seem to be related to the serialization and deserialization of the TensorRT engine file.

The first error, **ERROR: [TRT]: 1: [pluginV2Runner.cpp::load::290] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)**, indicates that there is an issue with the plugin being used in the engine file. This error typically occurs when the plugin required by the model is not found in the TensorRT plugin registry. Please ensure that the required plugin has been properly registered and is available in your environment.

The second error, **ERROR: [TRT]: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)**, suggests that there may be an internal error during the deserialization process of the engine file. This could be due to a corruption in the engine file or a version mismatch between the engine file and the TensorRT runtime. Double-check that you are using the correct version of TensorRT and ensure the engine file is not corrupted.

Please check the above suggestions and resolutions. If the issue persists, providing additional details such as the version of TensorRT and any changes made to the model or conversion process would help in further troubleshooting.

Remember, the YOLOv5 repository primarily focuses on the YOLOv5 model, and issues related to TensorRT and engine deserialization are typically handled by the TensorRT community or NVIDIA support.

Let us know if you have any further questions or concerns.

Happy coding!
