### ISSUE TITLE
Only the first three classes are shown?

### ISSUE THREAD

**Issue by JLIN77** [ultralytics/yolov5#12146]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I create my own data with 6 classes in data/coco.yaml
-----------------------------------------------------
# Classes
names:
  0: nc0
  1: nc1
  2: nc2
  3: nc3
  4: nc4
  5: nc5
------------------------------------------------------
And rewrite nc=6 in model/yolov5x.yaml. After training, I got a val result as follow,
----------------------------------------------------------
     Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 1/1 [00:00<00:00,  2.64it/s]
       all          3         45      0.668      0.771      0.733      0.371
       nc0          3         12      0.431      0.759      0.473      0.229
       nc1          3         18      0.753      0.556      0.733      0.272
       nc2          3         15      0.819          1      0.995      0.613
-----------------------------------------------------------------------
Where is the nc3~nc5

### Additional

I double-checked the val data and I'm sure there are some case of nc3~nc5.

**Comment by glenn-jocher** [comment]
@JLIN77 make sure that the images in your validation dataset actually contain instances of classes nc3, nc4, and nc5. It's possible that the instances of these classes are not present or not labeled correctly in your validation data, which could lead to them not appearing in the evaluation results.

You can also check your training logs to ensure that the model is correctly identifying instances of these classes during training. If the model is not able to detect them, it might be an issue with the training setup or parameters.

If you've verified that the instances of classes nc3, nc4, and nc5 exist in your validation data and the model is trained properly, please provide additional details so that we can assist you further.
