### ISSUE TITLE
How to freeze layers except backbone 

### ISSUE THREAD

**Issue by Flacon12** [ultralytics/yolov5#12159]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to freeze the number of layers after 10 layers. How should I change the code?
in train.py
    parser.add_argument('--freeze', nargs='+', type=int, default=[0], help='Freeze layers: backbone=10, first3=0 1 2')
If I set it to 10, does it freeze the number of layers 0, 1, 2, 3,...,10?

**Comment by glenn-jocher** [comment]
@Flacon12 in order to freeze the layers after the first 10 layers, you can set the `--freeze` argument in `train.py` to `10`. This will freeze the layers from 0 to 10 (inclusive).

Therefore, by setting `--freeze 10`, the layers 0, 1, 2, ..., 10 will be frozen and the rest of the layers will be trainable.

Let us know if you have any further questions or need additional assistance!

**Comment by Flacon12** [comment]
> @Flacon12 in order to freeze the layers after the first 10 layers, you can set the `--freeze` argument in `train.py` to `10`. This will freeze the layers from 0 to 10 (inclusive).
> 
> Therefore, by setting `--freeze 10`, the layers 0, 1, 2, ..., 10 will be frozen and the rest of the layers will be trainable.
> 
> Let us know if you have any further questions or need additional assistance!

I understand, thanks for your reply!

**Comment by glenn-jocher** [comment]
@Flacon12 you're welcome! I'm glad I could help. If you have any further questions or need additional assistance, feel free to ask. Happy training!
