### ISSUE TITLE
Changing backbone from Darknet to Resnet

### ISSUE THREAD

**Issue by muhammadd7** [ultralytics/yolov5#12175]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i am a fresh graduate of BSCS and a researcher and want to change the current backbon of YOLOv5 from darknet to resnet for that I added the these 2 classes in commons.py

```class MaxPooling2D(nn.Module):
    # MaxPooling2D layer with args(kernel, stride, padding)
    def __init__(self, k=2, s=2, p=0):
        super().__init__()
        self.maxpool = nn.MaxPool2d(k, s, p)

    def forward(self, x):
        return self.maxpool(x)

class ResBlock(nn.Module):
    def __init__(self, c1, num_repeats):
        super().__init__()
        self.blocks = nn.Sequential(*[
            nn.Identity() if i == 0 else Conv(c1, c1, k=3, s=1, act=True) for i in range(num_repeats)
        ])

    def forward(self, x):
        return torch.cat(x, self.blocks(x))
```
the backbone is given below:
```#Backbone
backbone: [
    [-1, 1, "Conv", [64, 6, 2, 2]],  # 0 - Conv1
    [-1, 1, "MaxPooling2D", [3, 2]],   # 1 - MaxPool
    [-1, 3, "ResBlock", [64]],         # 2 - Res2a, Res2b, Res2c
    [-1, 1, "Conv", [128, 3, 2]], # 3 - Conv3
    [-1, 4, "ResBlock", [128]],        # 4 - Res3a, Res3b, Res3c, Res3d
    [-1, 1, "Conv", [256, 3, 2]], # 5 - Conv4
    [-1, 6, "ResBlock", [256]],        # 6 - Res4a, Res4b, Res4c, Res4d, Res4e, Res4f
    [-1, 1, "Conv", [512, 3, 2]], # 7 - Conv5
    [-1, 3, "ResBlock", [512]],        # 8 - Res5a, Res5b, Res5c
    [-1, 1, "SPPF", [1024, 5]]         # 9 - SPPF
    ]
    
```
i am getting this shape error after adding Maxpooling2D and Resblock class names in Yolo.py
model summary is printed on screen succesfully after that this error occurs.

### Additional
```
Traceback (most recent call last):
  File "train.py", line 647, in <module>
    main(opt)
  File "train.py", line 536, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 130, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/dev/Documents/yolov5/models/yolo.py", line 195, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/home/dev/Documents/yolov5/models/yolo.py", line 194, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, Segment) else self.forward(x)
  File "/home/dev/Documents/yolov5/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/dev/Documents/yolov5/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File  "/home/dev/Documents/yolov5/models/common.py", line 90, in forward
    return torch.cat(x, self.blocks(x))
  File "/home/dev/Documents/yolov5/models/common.py", line 68, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/dev/.cache/pypoetry/virtualenvs/yolov5-FT1Hnn5N-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dev/.cache/pypoetry/virtualenvs/yolov5-FT1Hnn5N-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
 RuntimeError: Given groups=1, weight of size [8, 8, 3, 3], expected input[1, 32, 13, 13] to have 8 channels, but got 32 channels instead```

**Comment by glenn-jocher** [comment]
@muhammadd7 hi there! It looks like you're trying to change the backbone of YOLOv5 from Darknet to ResNet. 

Based on the error message you provided, it seems that there is a mismatch between the number of channels in the input and the expected number of channels for the convolutional layers in your ResBlock class. 

To troubleshoot this issue, please ensure that the number of input channels for your ResBlock class matches the number of channels in the input tensor. In this case, it seems that you have an input tensor with 32 channels, but your ResBlock class is expecting an input with 8 channels. 

Make sure that the number of channels in the input tensor is consistent with the number of channels expected by the convolutional layers in your ResBlock class. 

If you continue to experience difficulties, please provide more details on how you are using the ResBlock class and any relevant code snippets, so that we can better assist you.

**Comment by muhammadd7** [comment]
@glenn-jocher so do I have to change rest of the code as well? because as the backbone includes maxpooling2D after conv layer, the shape will get changed as compared to darknets backbone that had 2 conv layers initially and then c3 layer.

**Comment by glenn-jocher** [comment]
@muhammadd7 yes, if you're changing the backbone of YOLOv5 from Darknet to ResNet, you will likely need to make further changes to the code. The backbone architecture affects the shape and structure of the subsequent layers in the model.

In the case of YOLOv5, the Darknet backbone consists of multiple layers, including convolutional layers and shortcut connections, that are specific to the Darknet architecture. If you switch to a different backbone like ResNet, you will need to adapt the subsequent layers to match the new backbone.

This may involve modifying or replacing layers, adjusting the tensor sizes, and ensuring compatibility between the backbone and the rest of the model.

I suggest reviewing the code and documentation for YOLOv5 to understand how the backbone interacts with the other components of the model. This will help you identify the necessary changes required when switching to ResNet or any other backbone architecture.

If you have further questions or need assistance with specific code changes, please provide more details or code snippets so that we can help you further.
