### ISSUE TITLE
np.bool() Error when using numpy >1.23.1

### ISSUE THREAD

**Issue by MOXHAN** [ultralytics/yolov5#12195]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I am using the l4t-ml-35.2.1 Docker image and try to load the yolov5 model through PyTorch Hub with the function:

`model = torch.hub.load('ultralytics/yolov5','custom',path='yolov5s.engine', force_reload=True)`

Originally, Numpy version 1.24.4 is installed in the container. But this gives me the warning:

 _"FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar."_ 

and then also this error:

In File /usr/lib/python3.8/dist-packages/tensorrt/__init__.py:166, in nptype(trt_type)
_AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:_

### Environment

- Yolov5.engine
- l4t-ml:r35.21 docker image
- additionally installed packages: ultralytics, "opencv-python-headless<4.3"
- Jetson AGX Orin

### Additional

I already found a workaround, which is to simply install Numpy version 1.23.1 

`pip install numpy==1.23.1`

But I dont understand why this works, the error says the aliases was already deprecated in version 1.20.

Also, I think the error appears in a tensorrt file, so feel free to delete this issue if this cant be fixed on your end. In that case, Im sorry for the inconvinience.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ashish-dahal** [comment]
Your observation is on point. The issue you're encountering is due to the deprecated `np.bool` alias from Numpy which seems to still be used by the version of TensorRT in the `l4t-ml-35.2.1` Docker image.

To clarify a bit:

- While the `np.bool` alias was deprecated starting in Numpy version 1.20, it was still present in the library. By the time Numpy 1.24.4 was released, this alias might have been removed or its deprecation was more strictly enforced.

- Downgrading to Numpy 1.23.1 works as a solution because in that version, the deprecated `np.bool` alias still exists.

The most permanent solution would be an update from the TensorRT team to replace the usage of `np.bool` with the appropriate alternative (`bool` or `np.bool_`). You might consider informing the TensorRT team about this issue so they can address it in future updates.

Your workaround of downgrading Numpy to 1.23.1 is a practical immediate solution, but it would be great if this could be fixed upstream in TensorRT. If you haven't already, I recommend opening an issue on NVIDIA's repository or forum for TensorRT or the Docker image.

**Comment by glenn-jocher** [comment]
@ashish-dahal thanks for reporting this issue! The problem you encountered seems to be related to the deprecated `np.bool` alias in Numpy. Although the deprecation was announced in Numpy version 1.20, it appears that the alias is still used in the version of TensorRT installed in the `l4t-ml-35.2.1` Docker image.

To address this, the TensorRT team should update their implementation to use the appropriate alternative (`bool` or `np.bool_`) and eliminate the reliance on the deprecated alias. It might be helpful to notify the TensorRT team about this issue so they can consider it for future updates.

In the meantime, downgrading Numpy to version 1.23.1 provides a viable workaround since the deprecated `np.bool` alias is still available in that version.

Thank you for bringing this to our attention, and if you have any further questions or encounter any other issues, please don't hesitate to ask.
