### ISSUE TITLE
How to export torchscript.pt model to .torchscript.ptl'?

### ISSUE THREAD

**Issue by Dhurgham2021** [ultralytics/yolov5#12206]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I trained a custom model using YOLOv5 and would like to convert torchscript to torchscript.ptl in order to use the model for mobile app. but when i used the below code and after changing only this line 
 f = file.with_suffix('.torchscript')
 f = file.with_suffix('.torchscript.ptl')

it says successful exporbut when i used it on xcode it says error to load the model.

@try_export
def export_torchscript(model, im, file, optimize, prefix=colorstr('TorchScript:')):
    # YOLOv5 TorchScript model export
    LOGGER.info(f'\n{prefix} starting export with torch {torch.__version__}...')
    f = file.with_suffix('.torchscript')

    ts = torch.jit.trace(model, im, strict=False)
    d = {'shape': im.shape, 'stride': int(max(model.stride)), 'names': model.names}
    extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
    if optimize:  # https://pytorch.org/tutorials/recipes/mobile_interpreter.html
        optimize_for_mobile(ts)._save_for_lite_interpreter(str(f), _extra_files=extra_files)
    else:
        ts.save(str(f), _extra_files=extra_files)
    return f, None

Plase if anyone  can help with this issuse. 

Much appreciated.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Dhurgham2021 hi there! Thank you for reaching out and providing the code snippet you used for exporting the model to TorchScript. 

To export your model to `.torchscript.ptl`, you can modify the code snippet as follows:

```python
f = file.with_suffix('.torchscript.ptl')
```

However, please note that the `.torchscript.ptl` extension is not a recognized format by PyTorch. You may need to use the regular `.pt` extension to export the model as a TorchScript file. 

Regarding the error you encountered when loading the model in Xcode, there might be other issues causing this problem. It would be helpful to have more details about the error message you received in order to provide a more accurate solution.

Please feel free to ask if you have any further questions or need additional assistance. Don't hesitate to contribute to the YOLOv5 project by submitting a Pull Request (PR)! We appreciate your support.

**Comment by Dhurgham2021** [comment]
Hi Glenn, 
Thank you for your reply. I used to convert the model before by using the Yolov5 version last year, and it was working well. I just changed the below code to export .ptl to run it on the mobile app.
def export_torchscript(model, im, file, optimize, prefix=colorstr('TorchScript:')):
    # YOLOv5 TorchScript model export
    try:
        LOGGER.info(f'\n{prefix} starting export with torch {torch.__version__}...')
        f = file.with_suffix('.torchscript.ptl')

        ts = torch.jit.trace(model, im, strict=False)
        d = {"shape": im.shape, "stride": int(max(model.stride)), "names": model.names}
        extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
       # if optimize:  # https://pytorch.org/tutorials/recipes/mobile_interpreter.html
        optimize_for_mobile(ts)._save_for_lite_interpreter(str(f), _extra_files=extra_files)
       # else:
         #   ts.save(str(f), _extra_files=extra_files)

        LOGGER.info(f'{prefix} export success, saved as {f} ({file_size(f):.1f} MB)')
        return f
    except Exception as e:
        LOGGER.info(f'{prefix} export failure: {e}')
-------------------------------------------------
Regarding the .ptl extension, it is still accessible check this link out https://pytorch.org/tutorials/recipes/mobile_interpreter.html#ios
there is something called Prepare model: Prepare the mobile interpreter version of model by run the script below to generate the scripted model deeplabv3_scripted.pt and deeplabv3_scripted.ptl
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile
model = torch.hub.load('pytorch/vision:v0.7.0', 'deeplabv3_resnet50', pretrained=True)
model.eval()

scripted_module = torch.jit.script(model)
# Export full jit version model (not compatible mobile interpreter), leave it here for comparison
scripted_module.save("deeplabv3_scripted.pt")
# Export mobile interpreter version model (compatible with mobile interpreter)
optimized_scripted_module = optimize_for_mobile(scripted_module)
optimized_scripted_module._save_for_lite_interpreter("deeplabv3_scripted.ptl")
____________________________________________________________________________________
see the attached image when I am trying to load the new model with .ptl or .pt . It still shows the error but when I used the old model it is working well.

Many Thanks again for your reply.
![ee](https://github.com/ultralytics/yolov5/assets/95029659/b81445e3-7efe-4930-91e7-658cd90ce68f)

**Comment by glenn-jocher** [comment]
@Dhurgham2021 hi there,

Thank you for providing the code snippet and the information about the `.ptl` extension. I apologize for any confusion I may have caused. I understand that you are trying to export your model with the `.ptl` extension for use in your mobile app.

However, based on my understanding, the `.ptl` extension is not a recognized format by PyTorch. PyTorch officially supports using the `.pt` extension for exporting TorchScript models. The link you provided appears to use a custom file extension for their specific use case and is not a standard PyTorch format.

Regarding the error you encountered when trying to load the model with either the `.ptl` or `.pt` extension, it would be helpful to have more information about the specific error message you received. Additionally, please note that YOLOv5 does not officially support the `.ptl` extension, so this issue may require further investigation to determine the root cause.

If possible, please provide more details about the error message or any other relevant information that could help me understand the issue better. I'm here to assist you further.

Best regards

**Comment by denismuler** [comment]
@Dhurgham2021 Hello. I've changed this lines below and ran this command: "python3 export.py --weights yolov5s.pt --include torchscript" in yolov5 directory. It generated yolov5s.torchscript.ptl and it works fine) Hope this will help)    
<img width="759" alt="Screenshot 2023-10-25 at 15 27 03" 
src="https://github.com/ultralytics/yolov5/assets/104255851/fc0d5ebe-db03-4d29-b4d7-c25c77480387">

**Comment by glenn-jocher** [comment]
@denismuler Thank you for sharing your experience! It's great to hear that you were able to generate the `yolov5s.torchscript.ptl` file successfully by modifying the code and running the export command. Your feedback will be helpful to others who may have a similar requirement.

If you have any further questions or need assistance with anything else, please don't hesitate to ask. We're here to help.
