### ISSUE TITLE
agnostic=True sometimes work sometime not

### ISSUE THREAD

**Issue by Rorschaaaach** [ultralytics/yolov5#12210]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi, when i use detect.py and set agnostic=True sometimes work sometimes not.
in the first image it works, in the second it dont work. Do u have any suggestions?
![1696833536919](https://github.com/ultralytics/yolov5/assets/37372729/22f523ef-c3af-4f00-a276-22db65754e09)
![1696833604789](https://github.com/ultralytics/yolov5/assets/37372729/f0b75d70-4858-4966-af1e-a6913a3f8abb)

**Comment by glenn-jocher** [comment]
@Rorschaaaach hi,

Thank you for reaching out. The `agnostic=True` parameter in detect.py is used to enable primitive shape support. However, it is not always guaranteed to work consistently with all images.

If you are experiencing different results with different images, it might be due to variations in object sizes, lighting conditions, or other factors. To improve detection performance, you could try adjusting other parameters such as the confidence threshold or the model architecture.

Additionally, ensure that your YOLOv5 installation is up to date and that you have the necessary dependencies installed.

If you have further questions or need more assistance, please feel free to ask.

Best regards,
