### ISSUE TITLE
Different output on android device than on pc

### ISSUE THREAD

**Issue by umaidzubair** [ultralytics/yolov5#12217]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained yolov5 on the custom dataset and then exported the model in mobile optimized torchscript format. Everything seems to be fine, it also provides good results with detect.py. 
I tried implementing the same model on android using the [tutorial](https://playtorch.dev/docs/tutorials/snacks/yolov5/) by playtorch. The results are completely different for the same image.

The results by detect.py
![image](https://github.com/ultralytics/yolov5/assets/144029027/8e39af75-f32d-4b1c-8242-c1f2cf9b652f)

The results on android device:
![image](https://github.com/ultralytics/yolov5/assets/144029027/269bd982-8fc1-4c45-915d-07db02438361)

**Comment by glenn-jocher** [comment]
@umaidzubair the difference in the output between your PC and Android device could be due to a few factors. Here are a few things to consider:

1. **Hardware Limitations**: The performance of the model may be affected by the hardware limitations of your Android device. This could result in variations in inference speed and accuracy compared to your PC.

2. **Preprocessing**: Ensure that the input image is preprocessed in the same way on both your PC and Android device. Any differences in resizing, normalization, or data augmentation techniques can impact the model's performance.

3. **Model Conversion**: Double-check the conversion process when exporting the model for mobile deployment. The conversion may introduce differences in precision, optimizations, or layer compatibility, leading to varying results.

4. **Runtime Environment**: Ensure that the runtime environment on your Android device matches the requirements specified for YOLOv5. This includes the version of Android, available memory, and other dependencies.

To troubleshoot further, provide additional information such as the exact steps you followed for exporting the model and the hardware and software specifications of your Android device. This will help the community and the Ultralytics team provide more specific guidance.

Remember, the YOLOv5 repository is a collaborative effort, and many contributors are eager to help. Feel free to share any additional details, and someone from the community will assist you further.
