### ISSUE TITLE
Single Channel image inference 

### ISSUE THREAD

**Issue by tarunn2799** [ultralytics/yolov5#12231]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I used the repo to train a model on single channel images. Training went really well after I made some changes (added ch:1, changed dataloader to read single channel images), and now I want to load the model using torch hub and perform inference on the model. 

I went through the autoshape forward function and I see a part of the code that enforces the image to be 3 channel, but my model errors out because the initial conv layer only accepts single channel images. 

https://github.com/ultralytics/yolov5/blob/30e4c4f09297b67afedf8b2bcd851833ddc9dead/models/common.py#L271C1-L272C1

I tried turning autoshape off, and passing a torch tensor directly like this 

```
model = torch.hub.load('ultralytics/yolov5', 'custom', path=path, autoshape=False)  # local model
im = cv2.imread('1.png', -1)[..., ::-1] 
img= torch.from_numpy(im[None][None].copy()).float()
model(img.cuda())
```

and I get the error : 
`RuntimeError: Sizes of tensors must match except in dimension 2. Got 13 and 14 (The offending index is 0)`

Can you help me understand what I need to modify to be able to pass a single-dim numpy array/png image to the torch hub model to perform inference? 

If this is a limitation through torch hub, I appreciate any guidance on how to do this using detect.py.

**Comment by glenn-jocher** [comment]
@tarunn2799 hi there! It's great to hear that you had success training a model on single-channel images using the YOLOv5 repository. I'd be happy to assist you with performing inference on the model.

The code you shared indicates that the initial convolutional layer expects a single-channel image, which explains the error you encountered when trying to perform inference with a three-channel image. To modify the model to accept single-channel images, you'll need to make a small change in the repository.

In the `models/common.py` file, you can modify the line you mentioned (`L271C1-L272C1`) to ensure that the expected number of input channels is 1 instead of 3. This change will align the model with your training settings for single-channel images.

Regarding your attempt to pass a single-dim numpy array or a PNG image to the Torch Hub model, the error message suggests a size mismatch between tensors. To resolve this, make sure that the tensor dimensions match the model's input size. For example, if your model expects a size of `[1, 3, height, width]`, ensure that your tensor has the same dimensions.

If you prefer to use `detect.py` instead of Torch Hub, you can pass your single-channel image to the script for inference. Please refer to the YOLOv5 documentation for instructions on running `detect.py`.

Let me know if you need any further assistance or clarification. Happy to help!

**Comment by glenn-jocher** [comment]
@tarunn2799 thanks for reaching out! It's great to hear that you have successfully trained a model on single-channel images using the YOLOv5 repository. I'd be happy to help you with performing inference on the model.

Based on the code snippet you provided, it looks like the initial convolutional layer expects a single-channel input, which aligns with your training setup for single-channel images. To modify the model to accept single-channel images for inference, you can make a small change to the model configuration in the YOLOv5 repository.

As for your attempt to pass a single-dim numpy array or a PNG image to the Torch Hub model and encountering a size mismatch error, ensure that the tensor dimensions match the model's input size. If the model expects a specific input size, make sure to resize or modify the input accordingly before passing it for inference.

If you are considering using `detect.py` for inference instead of Torch Hub, you can directly pass your single-channel image to the script for inference. For detailed instructions, you can refer to the YOLOv5 documentation or the script's usage.

Let me know if you need any further assistance or clarification. I'm here to help!
