### ISSUE TITLE
Unable to add NMS Layer to .mlmodel when exporting a custom.pt model

### ISSUE THREAD

**Issue by mdbtekny** [ultralytics/yolov5#12236]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I'm trying to export my custom trained yolov5s model to an .mlmodel . I followed this notebook found on internet https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov5-object-detection-on-custom-data.ipynb and I added this code to export my model https://colab.research.google.com/drive/1uR738UTlzI7apqeN0qr6mQ5ke_a5SKa8?usp=sharing&source=post_page-----113408b7a848-------------------------------- . I prepared my dataset on Roboflow and imported it into yolov5 project. The train.py runs smoothly but when I have to export the model I run into issues. When I try to convert export.py doesn't add NMS Layer to mlmodel making it unimpossible to use. (I am using coremltools 6.3.0). Following that code for exporting, my colab crash when I run addExportLayer function. I can't find any issue that can solve this problem.
I'm using Google colab for testing this code.

### Environment

Using torch 2.0.1+cu118
YOLOv5 🚀 v6.1-306-gfbe67e4 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Python: 3.10.12

### Minimal Reproducible Example

`!python export.py --weights /content/yolov5/runs/train/yolov5_results/weights/best.pt --include coreml

 PyTorch: starting from /content/yolov5/runs/train/yolov5_results/weights/best.pt with output shape (1, 25200, 7) (13.7 MB)
scikit-learn version 1.2.2 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
XGBoost version 2.0.0 has not been tested with coremltools. You may run into unexpected errors. XGBoost 1.4.2 is the most recent version that has been tested.
2023-10-16 08:53:42.323632: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 08:53:44.556980: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
TensorFlow version 2.13.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.10.0 is the most recent version that has been tested.
Torch version 2.0.1+cu118 has not been tested with coremltools. You may run into unexpected errors. Torch 1.12.1 is the most recent version that has been tested.
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mdbtekny the issue you're facing when exporting your custom trained YOLOv5s model to an .mlmodel might be due to the version compatibility between different libraries. 

Based on the error message you provided, it seems that some libraries are not supported or have not been tested with the version of coremltools you are using. Specifically, scikit-learn v1.2.2, XGBoost v2.0.0, TensorFlow v2.13.0, and Torch v2.0.1+cu118 may not be compatible or have not been tested with coremltools.

To resolve this issue, you can try the following steps:

1. Make sure you are using a compatible version of coremltools, scikit-learn, XGBoost, TensorFlow, and Torch. You may need to downgrade or upgrade these libraries to the versions that are known to be compatible with the version of coremltools you are using.

2. Check the coremltools documentation or GitHub repository for any known issues or workarounds related to the specific library versions you are using.

3. If you are still facing issues, try using a different environment or platform that has been verified to work with YOLOv5 and coremltools. For example, you can consider using Google Cloud Deep Learning VM or Amazon Deep Learning AMI, which have been tested and documented to work well with YOLOv5.

Please note that YOLOv5 is an open-source project maintained by the Ultralytics team, and this issue may require further investigation or assistance from the coremltools or YOLOv5 community. If you need more help, I recommend posting your question on the YOLOv5 [GitHub Discussions](https://github.com/ultralytics/yolov5/discussions) or coremltools [GitHub Issues](https://github.com/apple/coremltools/issues) pages, where the community can provide additional guidance and support.

Thank you for using YOLOv5, and I hope this helps you resolve the issue.
