### ISSUE TITLE
No output after export from .pt to .engine

### ISSUE THREAD

**Issue by homeboyinlove** [ultralytics/yolov5#12235]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

So im facing the problem when Im trying to export .pt to .engine file, my input and output are in the screenshot 
![image](https://github.com/ultralytics/yolov5/assets/91129946/7d9d06b6-280f-42e1-b950-94c19e621218)

### Environment

YOLOv5  v7.0-72-g064365d Python-3.9.0 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24564MiB)
Windows 11
Python 3.9

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@homeboyinlove hello there! Thank you for reaching out to us.

Based on the information you provided, it seems that you are not getting any output after exporting your `.pt` file to `.engine`. In order to better understand and assist with your issue, there are a few things we need to clarify:

1. Please double-check the screenshot link you provided, as it appears to be broken. We are unable to view the screenshot at the moment.

2. Could you provide us with the exact command you used to perform the export from `.pt` to `.engine`? This will help us in diagnosing the issue.

3. It would also be helpful if you could share any error messages or logs you received during the export process. This will aid in identifying the root cause of the problem.

Once we have this information, we will be able to provide you with further guidance and assistance. Thank you for your cooperation, and we look forward to helping you resolve this issue!

**Comment by homeboyinlove** [comment]
Thanks for your respond !

1.https://imgur.com/a/inEdLrT
2.python "C:\Users\hohom\OneDrive\Desktop\cheats\yolov5\export.py" --weights "C:\Users\hohom\OneDrive\Desktop\cheats\best.pt" --include engine --device 0 --img 736
3.there are no error messages for some reason, it all just stops at "ONNX: starting export with onnx 1.12.0..."

**Comment by glenn-jocher** [comment]
@homeboyinlove thank you for providing the details.

I apologize for the inconvenience. From your description, it seems that the export process stops at "ONNX: starting export with onnx 1.12.0..." and you do not receive any error messages.

To further investigate this issue, could you please provide the following information:

1. Confirm the version of ONNX you have installed. You can check this by running `import onnx` and `onnx.__version__` in a Python terminal.

2. Verify that you have the necessary CUDA and cuDNN versions installed. Please provide the version numbers for CUDA and cuDNN that are installed on your system.

3. Additionally, please check if you have any other existing ONNX-related packages or installations on your system. It's possible that there could be conflicts or compatibility issues with these installations.

Once we have this information, we can work together to troubleshoot the problem and find a solution. Thank you for your patience, and we'll do our best to assist you with this issue!

**Comment by homeboyinlove** [comment]
1. onnx.__version__='1.12.0', opset=17, IR_VERSION=8
2. nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
cuDNN Version : 8.9.0.131
3. I dont know how to do this properly, so i'll assume that there is only one package (installed with pip install onnxruntime-gpu)


upd. after running 'pip install onnx'  it tells that all requirements are already satisfied

**Comment by glenn-jocher** [comment]
@homeboyinlove thank you for providing the additional information.

Based on the information you provided:

1. The version of ONNX you have installed (`onnx.__version__`) is 1.12.0 with `opset=17` and `IR_VERSION=8`. Please ensure that this version is compatible with the YOLOv5 repo you are using.

2. The CUDA version (`nvcc`) you have installed is 12.1.105, and the cuDNN version is 8.9.0.131. These versions seem to be compatible with YOLOv5.

3. If you have only installed the ONNX package using `pip install onnxruntime-gpu`, it is unlikely to cause conflicts with the export process.

Since there are no error messages, it appears that the export process is getting stuck at the ONNX export step. Please try the following troubleshooting steps:

1. Update your ONNX version to the latest stable release (`pip install --upgrade onnx`).

2. Verify that your PyTorch version is up to date and compatible with the YOLOv5 repo.

3. Check if there are any specific model or configuration settings that could be causing the issue. It might be helpful to try exporting a different model or adjusting the settings to see if the problem persists.

If the issue still persists after attempting these steps, please provide the complete output log of the export command so we can analyze it further.

We appreciate your patience, and we will do our best to help you resolve this issue.

**Comment by homeboyinlove** [comment]
@glenn-jocher Everything is up to date. Also tried to export a different model - no results, and tried to use different include. ```--include onnx``` works fine, and it passes ```ONNX: starting export with onnx 1.14.1...```  "problem" and returns new exported file. However, still doesnt work with ```--include engine```. So i can guess the problem is not in onnx, but in tensorrt. After running ```pip install nvidia-tensorrt``` it returns this : 

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting nvidia-tensorrt
  Downloading nvidia-tensorrt-0.0.1.dev5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hohom\AppData\Local\Temp\pip-install-wbd8xhlm\nvidia-tensorrt_5c61b17f1e62464c8c7a2cb9a1f128cd\setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install nvidia-tensorrt
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


But ```$ pip install nvidia-pyindex```
      ```$ pip install nvidia-tensorrt``` 
return the same problem.

**Comment by glenn-jocher** [comment]
@homeboyinlove based on the information you provided, it seems that the issue might be related to TensorRT rather than ONNX. When you use the `--include onnx` flag, the export process works fine and returns a new exported file. However, when you use the `--include engine` flag, it does not work.

After attempting to install TensorRT using `pip install nvidia-tensorrt`, you encountered an error that mentioned the package is only a placeholder project on PyPI.org and should be installed from the NVIDIA Python Package Index. However, when you tried to install `nvidia-pyindex` and then `nvidia-tensorrt`, you still faced the same problem.

Considering these observations, it appears that the issue lies with installing TensorRT using `pip` and may require an alternative installation method or additional troubleshooting.

I suggest checking the NVIDIA developer documentation or community forums for detailed installation instructions and possible solutions specifically related to installing TensorRT via `pip` and encountering the placeholder error.

I hope this guidance helps you further investigate and resolve the issue.
