### ISSUE TITLE
Incremental learning

### ISSUE THREAD

**Issue by thiennn013** [ultralytics/yolov5#12244]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained a model consisting of 5 classes with an initial dataset of 1000 images. After a while, I had 500 more images. I want the model to learn more from these 500 images without having to retrain from the beginning, what should I do?

**Comment by glenn-jocher** [comment]
@thiennn013 hi,

To incrementally train your YOLOv5 model with the additional 500 images without starting from scratch, you can follow these steps:

1. Load the previously trained model using `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)`.

2. Train the model on the new dataset by running the following command: `python train.py --data your_data.yaml --weights runs/train/exp/weights/best.pt --batch-size 16 --epochs 10`.

   Make sure to replace `your_data.yaml` with the path to your new data YAML file containing the updated dataset information.

3. The training process will automatically initialize the model with the weights from the previous training, and continue training on the new dataset.

Note: It is recommended to use a small learning rate (e.g., `--lr 0.001`) during incremental training to avoid overfitting on the new data.

This approach allows you to continue training your model and incorporate new data without discarding the previous training progress.

Best regards.

**Comment by thiennn013** [comment]
So will the model forget the old data if done like this and is the model quality as good as training from scratch with all 1500 images?

**Comment by glenn-jocher** [comment]
@thiennn013 incremental training allows the model to learn from new data without forgetting the old data. The model will retain the knowledge from the previous training and incorporate the new information from the additional images. The quality of the model after incremental training with the combined 1500 images may not be as good as training from scratch with all 1500 images, but it should still be improved compared to solely training on the initial 1000 images.

**Comment by thiennn013** [comment]
Mình chưa hiểu ý bạn ở bước 1, bạn giải thích rõ hơn nhé. Và ở bước 2 dữ liệu chỉ có 500 ảnh mới hay 1500 ảnh cả cũ và mới?

**Comment by thiennn013** [comment]
I don't understand what you mean in step 1, please explain more clearly. And in step 2, does the data only have 500 new photos or 1500 photos both old and new?

**Comment by glenn-jocher** [comment]
@thiennn013 hi,

In step 1, what I meant is to load the previously trained model that you have already trained on the initial 1000 images. You can use the `torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)` function call to load the pre-trained YOLOv5 model.

In step 2, the data can contain either only the new 500 photos or the combined 1500 photos (i.e., both old and new). The `--data` argument should point to a YAML file that describes your dataset, regardless of whether it includes only the new images or both the old and new images.

I hope this clarifies the steps for you. If you have any further questions, please let me know.

Thanks!

**Comment by thiennn013** [comment]
Very useful to me, thank you very much ♥

**Comment by glenn-jocher** [comment]
@thiennn013 your kind words are greatly appreciated! However, the credit goes to the YOLO community and the talented team at Ultralytics who have contributed to the development and maintenance of YOLOv5. They have worked hard to make it a useful tool. If you have any further questions or need assistance, feel free to ask.

**Comment by chang50961471** [comment]
![Uploading image.png…]()

**Comment by chang50961471** [comment]
> 你好
> 
> 若要在不从头开始的情况下使用额外的 500 个映像增量训练 YOLOv5 模型，可以按照以下步骤操作：
> 
> 1. 使用 加载先前训练的模型。`model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)`
> 2. 通过运行以下命令，在新数据集上训练模型：。`python train.py --data your_data.yaml --weights runs/train/exp/weights/best.pt --batch-size 16 --epochs 10`
>    请确保替换为包含更新的数据集信息的新数据 YAML 文件的路径。`your_data.yaml`
> 3. 训练过程将使用先前训练的权重自动初始化模型，并继续在新数据集上进行训练。
> 
> 注意：建议在增量训练期间使用较小的学习率（例如，），以避免对新数据进行过度拟合。`--lr 0.001`
> 
> 此方法允许您继续训练模型并合并新数据，而不会丢弃以前的训练进度。
> 
> 此致敬意。

root@c1fb31f02a74:/mydata/data1/chang/docker/yolo/yolov5-5.0-ZDZG_person# python -m torch.distributed.launch --nproc_per_node 2 train.py --img 640 --batch 64 --data data/person.yaml --weights runs/train/person20231116s/weights/best.pt --epochs 200 --device 0,1 --lr 0.001
/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: train.py [-h] [--weights WEIGHTS] [--cfg CFG] [--data DATA] [--hyp HYP] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume [RESUME]] [--nosave] [--notest]
                [--noautoanchor] [--evolve] [--bucket BUCKET] [--cache-images] [--image-weights] [--device DEVICE] [--multi-scale] [--single-cls] [--adam] [--sync-bn] [--local_rank LOCAL_RANK] [--workers WORKERS]
                [--project PROJECT] [--entity ENTITY] [--name NAME] [--exist-ok] [--quad] [--linear-lr] [--label-smoothing LABEL_SMOOTHING] [--upload_dataset] [--bbox_interval BBOX_INTERVAL] [--save_period SAVE_PERIOD]
                [--artifact_alias ARTIFACT_ALIAS]
train.py: error: unrecognized arguments: --lr 0.001
usage: train.py [-h] [--weights WEIGHTS] [--cfg CFG] [--data DATA] [--hyp HYP] [--epochs EPOCHS] [--batch-size BATCH_SIZE] [--img-size IMG_SIZE [IMG_SIZE ...]] [--rect] [--resume [RESUME]] [--nosave] [--notest]
                [--noautoanchor] [--evolve] [--bucket BUCKET] [--cache-images] [--image-weights] [--device DEVICE] [--multi-scale] [--single-cls] [--adam] [--sync-bn] [--local_rank LOCAL_RANK] [--workers WORKERS]
                [--project PROJECT] [--entity ENTITY] [--name NAME] [--exist-ok] [--quad] [--linear-lr] [--label-smoothing LABEL_SMOOTHING] [--upload_dataset] [--bbox_interval BBOX_INTERVAL] [--save_period SAVE_PERIOD]
                [--artifact_alias ARTIFACT_ALIAS]
train.py: error: unrecognized arguments: --lr 0.001
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 322) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-20_14:12:28
  host      : c1fb31f02a74
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 323)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-20_14:12:28
  host      : c1fb31f02a74
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 322)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
调整lr之后报错，这个是什么问题？

**Comment by glenn-jocher** [comment]
@chang50961471 您好,

看起来您正在尝试使用 Elastic Training 来训练 YOLOv5 模型。根据您提供的错误信息，似乎在您的命令中发生了错误。可能是因为 Elastic Training 不支持 `--lr` 参数。您可以尝试删除 `--lr 0.001` 参数并重新运行命令，看看是否解决了问题。

如果问题仍然存在，请查看 Elastic Training 的官方文档，了解如何正确设置学习率参数，以确保您可以成功进行模型训练。同时也可以尝试在 YOLOv5 issue tracker 中寻求帮助，也许有其他人遇到过类似的问题。

祝您好运！
