### ISSUE TITLE
How to convert the exported ONNX format into three outputs of different sizes instead of merging them into one

### ISSUE THREAD

**Issue by 11Bin** [ultralytics/yolov5#12262]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I exported the onnx format using YOLOv5.6 version of PT, I found only one output0. I saw ONNX merging three outputs of different sizes, but I want to deploy it on a mobile device. When quantifying, merging the three outputs will result in an error. How can I change it to the normal three different outputs

**Comment by glenn-jocher** [comment]
@11Bin to achieve three separate outputs of different sizes instead of merging them into one in the exported ONNX format, you can modify the export code in yolov5/models/yolo.py. You will find the function forward, where the three output branches are defined. You can use this function to customize the output size and structure according to your requirements.

If you have any further questions or need assistance with the implementation, feel free to ask. We are here to help!

**Comment by mawei-north** [comment]
May I ask if your final deployment was successful? Like you, there is no detection box on the app in the end.

**Comment by glenn-jocher** [comment]
@mawei-north thank you for your interest! However, I'm simply a contributor to the YOLOv5 project, and the success of your deployment will depend on various factors such as your application's specific requirements, model optimization, and integration with your mobile device.

For deploying YOLOv5, you can refer to the Ultralytics Docs (https://docs.ultralytics.com/yolov5/) for guidance and best practices. If you have any specific issues or questions regarding the deployment, feel free to ask, and I'll do my best to help. Good luck with your deployment!
