### ISSUE TITLE
Using clearml logger, how to differentiate Testing tasks from Training tasks?

### ISSUE THREAD

**Issue by fadishaar84** [ultralytics/yolov5#12279]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have noticed that you have removed the task_type parameter from detect.py which is usefull for logging testing task using clearml: 
    parser.add_argument('--task_type', default='Testing', help='task type for clearml')
Can you guide me how to make clearml log my testing task and differentiate it from training tasks?
Previously I was using task_type parameter and it was working fine: 

![Screenshot from 2023-10-25 13-29-37](https://github.com/ultralytics/yolov5/assets/25133070/a00d2165-85ec-4318-a31e-60539afb54a7)

Thank you.

**Comment by glenn-jocher** [comment]
@fadishaar84 hi there! 

In YOLOv5, the `--task_type` parameter has been removed from `detect.py`. However, you can still differentiate your testing tasks from training tasks by utilizing the ClearML Logger.

To log your testing task, you can use the `logger.report_scalar()` function and provide a distinct tag or name for your testing task. For example:

```python
from clearml import Task

# Create a ClearML task
task = Task.init(project_name='YOLOv5', task_name='Testing_Task')

# Log your testing task
task.get_logger().report_scalar("Testing", 1, iteration=1)
```

By using a unique tag or name, you can easily differentiate and track your testing tasks within ClearML.

Hope this helps! Let me know if you have any further questions.

**Comment by fadishaar84** [comment]
@glenn-jocher Thanks for your answer. But I thought we can have clearml log from inside detect.py like using some callbacks like it has been done in the case of train.py using utils/loggers/clearml/clearml_utils.py.

**Comment by glenn-jocher** [comment]
@fadishaar84 hello! Thank you for your question.

You are correct that in the case of `train.py`, we have implemented ClearML logging using callbacks in `utils/loggers/clearml/clearml_utils.py`. 

Currently, in `detect.py`, we do not have built-in support for ClearML logging using callbacks like in `train.py`. However, you can still manually log your testing tasks using the approach I mentioned earlier using the ClearML Logger.

If you would like to have built-in ClearML logging support for testing tasks in `detect.py`, you can create a feature request on our GitHub repository so that our development team can consider implementing it in a future release.

Please let me know if you have any more questions!
