### ISSUE TITLE
Yolov5 detect.py\val.py\train.py cannot run after waiting for a long time to read the graphics card information

### ISSUE THREAD

**Issue by jay985735639** [ultralytics/yolov5#12280]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/yolov5/assets/72804737/8388ef38-7078-40da-9e50-b4674b91a8fd)

After reading the graphics card information, there was no follow-up, and it took a long time to execute.

**Comment by glenn-jocher** [comment]
@jay985735639 hi,

Thank you for reaching out. I'll be happy to help you with this.

The issue you described could be due to various reasons. To better understand and troubleshoot the problem, could you please provide more information? Specifically, could you let us know the following details:

1. The version of YOLOv5 you are using.
2. The specific command you ran that resulted in the issue.
3. The hardware specifications of your system.
4. Any error messages or logs that you encountered during the execution.

With this information, we will be able to assist you more effectively.

Best regards,
Glenn Jocher

**Comment by jay985735639** [comment]
I seem to know the problem. I used 4090 and used a lower version of Torch 1.9. I replaced Torch 2.0.0 and it was fine

**Comment by glenn-jocher** [comment]
@jay985735639 great! It's good to hear that you were able to resolve the issue. Upgrading to the latest version of Torch can often solve compatibility problems. 

If you have any further questions or need assistance with anything else, please don't hesitate to ask. 

Keep up the good work! 
Glenn Jocher
