### ISSUE TITLE
The trained model export onnx is too large

### ISSUE THREAD

**Issue by Rorschaaaach** [ultralytics/yolov5#12284]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i use: 
    python export.py --weights runs/train/v1/weights/best.pt --include onnx
export the onnx model, runs/train/v1/weights/best.pt model is only 14M but onnx model is 28M, so why export model so large? I didn't use --half because the model was used on the CPU.

**Comment by glenn-jocher** [comment]
@Rorschaaaach hi there,

The size of the exported ONNX model can be larger than the original PyTorch weights due to differences in serialization formats and optimizations performed by ONNX. The larger size is not indicative of any performance issues.

If you want to reduce the size of the exported ONNX model further, you can try quantization techniques offered by frameworks like ONNXRuntime or OpenVINO. These techniques can help to reduce the model size without significantly affecting the inference performance.

Feel free to explore these options, and let us know if you have any further questions.

Best regards.
