### ISSUE TITLE
I already made model with 10 classes 10 after training by Yolov5. I would like to add new two classes into the made model 12 classes. How can I modify the the made model 12 classes by 13 classes when I train by transfer Learning?

### ISSUE THREAD

**Issue by star4s** [ultralytics/yolov5#12281]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question about modification of the model.
I already made model with 12 classes after training by Yolov5. I would like to add new two classes into the made model 12 classes. How can I modify the the made model 12 classes by 13 classes  when I train by transfer Learning?

../model/epoch110.pt : 12 classes

New image class (for transfer learning): 13 classes

My run comment:

python train.py --weights ../model/epoch110.pt --epochs 20 --img 256 --batch 16 --cache ram --data trans.yaml --hyp './runs/evolve/exp9/hyp_evolve_1.yaml' --cfg './models/yolov5x6_trans.yaml' --save-period 1 &

For example,
12 classes: 1, 2, 3, ... , 9, 10, 11, 12
--->
13 classes: 1, 2, 3, ... , 9, 10, 11, 12, 13

Thank you for your attention.

And I Followed your Instruction.
===========================
To modify a YOLOv5 model from 12 classes to 13 classes, you will need to follow these steps:

1. Prepare your new dataset with the additional two classes. Make sure the new classes are properly annotated in your dataset.
2. Add the new classes to the data.yaml file in your YOLOv5 directory. Make sure to update the number of classes in the file.
3. Train the model using the updated dataset and data.yaml file. You can use the --weights flag to initialize the model with the previously trained weights.
4. Once the training is complete, the model should be updated with the additional two classes.
Please note that it's important to properly balance and annotate the new classes to avoid any biases in the model.

Best of luck with your modifications!
==========================
@glenn-jocher 
I followed your instruction. But, I met some error.

Traceback (most recent call last):
File "train.py", line 645, in
main(opt)
File "train.py", line 542, in main
train(opt.hyp, opt, device, callbacks)
File "train.py", line 203, in train
ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
File "/.conda/envs/yolo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
size mismatch for model.33.m.0.weight: copying a param with shape torch.Size([51, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 320, 1, 1]).
size mismatch for model.33.m.0.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
size mismatch for model.33.m.1.weight: copying a param with shape torch.Size([51, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 640, 1, 1]).
size mismatch for model.33.m.1.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
size mismatch for model.33.m.2.weight: copying a param with shape torch.Size([51, 960, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 960, 1, 1]).
size mismatch for model.33.m.2.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).
size mismatch for model.33.m.3.weight: copying a param with shape torch.Size([51, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 1280, 1, 1]).
size mismatch for model.33.m.3.bias: copying a param with shape torch.Size([51]) from checkpoint, the shape in current model is torch.Size([54]).

**Comment by glenn-jocher** [comment]
@star4s to modify a YOLOv5 model from 12 classes to 13 classes, you will need to follow these steps:

1. Prepare your new dataset with the additional two classes. Make sure the new classes are properly annotated in your dataset.
2. Add the new classes to the data.yaml file in your YOLOv5 directory. Make sure to update the number of classes in the file.
3. Train the model using the updated dataset and data.yaml file. You can use the --weights flag to initialize the model with the previously trained weights.
4. Once the training is complete, the model should be updated with the additional two classes.

Regarding the error you encountered with the size mismatch, it seems to be related to the network architecture. The number of classes should match the number of output channels in the last layer of the network. Make sure that the architecture definition file (e.g. yolov5x6_trans.yaml) also reflects the correct number of classes.

If the error persists, it could be caused by incompatible model weights saved from a different network architecture. In that case, retraining the model from scratch with the correct number of classes is recommended.

Please let me know if you have any further questions or issues. Good luck with your modifications!

And please note that I'm just a member of the YOLO community, and credit goes to the YOLOv5 developers and the Ultralytics team for their excellent work in creating the YOLOv5 repository.
