### ISSUE TITLE
Yolov5 detect with cuda shows assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \

### ISSUE THREAD

**Issue by NierAimer** [ultralytics/yolov5#12309]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

import subprocess
import torch

rtmp_stream_url = "rtmp://192.168.32.163/live/stream"
yolov5_weights = "../models/best.pt" 
print(torch.cuda.is_available())

yolov5_command = [
    "python",
    "detect.py",  
    "--source",
    rtmp_stream_url,
    "--weights",
    yolov5_weights,
    "--view-img",
]
subprocess.run(yolov5_command)

shows C:\Users\Ada\.conda\envs\Fire_Yolo\python.exe E:\PythonProject\Yolov5-Fire-Detection\yolov5\fire_detect.py 
True
detect: weights=['../models/best.pt'], source=rtmp://192.168.32.163/live/stream, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=1, view_img=True, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
Traceback (most recent call last):
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 285, in <module>
    main(opt)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 280, in main
    run(**vars(opt))
  File "C:\Users\Ada\.conda\envs\Fire_Yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 100, in run
    device = select_device(device)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\utils\torch_utils.py", line 118, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 1' requested, use '--device cpu' or pass valid CUDA device(s)

Process finished with exit code 0

### Environment

yolov5 conda create a env py3.10
os:win-x64
cuda:12.1 with 8.x cudnn
![image](https://github.com/ultralytics/yolov5/assets/33416196/4757928f-230b-4466-8c1f-b9ae0f4c631f)
![image](https://github.com/ultralytics/yolov5/assets/33416196/756eab13-a5af-44a2-b8e9-b576273a093a)

### Minimal Reproducible Example

import subprocess
import torch

rtmp_stream_url = "rtmp://192.168.32.163/live/stream"
yolov5_weights = "../models/best.pt"
print(torch.cuda.is_available())
print(torch.cuda.device_count())

yolov5_command = [
    "python",
    "detect.py", 
    "--source",
    rtmp_stream_url,
    "--weights",
    yolov5_weights,
    "--view-img",
]

subprocess.run(yolov5_command)

C:\Users\Ada\.conda\envs\Fire_Yolo\python.exe E:\PythonProject\Yolov5-Fire-Detection\yolov5\fire_detect.py 
True
1
detect: weights=['../models/best.pt'], source=rtmp://192.168.32.163/live/stream, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=1, view_img=True, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
Traceback (most recent call last):
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 285, in <module>
    main(opt)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 280, in main
    run(**vars(opt))
  File "C:\Users\Ada\.conda\envs\Fire_Yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 100, in run
    device = select_device(device)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\utils\torch_utils.py", line 118, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 1' requested, use '--device cpu' or pass valid CUDA device(s)

Process finished with exit code 0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NierAimer hi there,

Based on the provided traceback, it appears that you are encountering an assertion error related to the availability of CUDA and the specified device. The error message suggests using '--device cpu' or passing valid CUDA device(s) instead of '--device 1'.

To resolve this issue, you can try modifying your script as follows:

1. Replace `device = 1` with `device = 'cpu'` in the `detect.py` file.
2. If you want to use a specific CUDA device, ensure that you specify a valid device number (e.g., 0, 1, 2, etc.) rather than 'cpu'.

Please give this a try and let me know if the issue persists. Additionally, please ensure that you have CUDA properly installed and configured.

If you have any further questions or need additional assistance, feel free to ask.

Best regards.

**Comment by NierAimer** [comment]
import subprocess
import torch

# 定义RTMP流URL和YOLOv5权重文件
rtmp_stream_url = "rtmp://192.168.32.163/live/stream"
yolov5_weights = "../models/best.pt"  # 适当选择YOLOv5权重文件
print(torch.cuda.is_available())
print(torch.cuda.device_count())

# 定义YOLOv5检测命令
yolov5_command = [
    "python",
    "detect.py",  
    "--device",  
    "1", 
    "--source",
    rtmp_stream_url,
    "--weights",
    yolov5_weights,
    "--view-img",
]
subprocess.run(yolov5_command)

C:\Users\Ada\.conda\envs\Fire_Yolo\python.exe E:\PythonProject\Yolov5-Fire-Detection\yolov5\fire_detect.py 
True
1
detect: weights=['../models/best.pt'], source=rtmp://192.168.32.163/live/stream, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=1, view_img=True, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
Traceback (most recent call last):
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 285, in <module>
    main(opt)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 280, in main
    run(**vars(opt))
  File "C:\Users\Ada\.conda\envs\Fire_Yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\detect.py", line 100, in run
    device = select_device(device)
  File "E:\PythonProject\Yolov5-Fire-Detection\yolov5\utils\torch_utils.py", line 118, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 1' requested, use '--device cpu' or pass valid CUDA device(s)

Process finished with exit code 0

**Comment by NierAimer** [comment]
use the cpu it can work,but detect rtmp or rtsp so lage, I test by use OBS and srs detect by cpu shows
C:\Users\Ada\.conda\envs\Fire_Yolo\python.exe E:\PythonProject\Yolov5-Fire-Detection\yolov5\fire_detect.py 
True
1
detect: weights=['../models/best.pt'], source=rtmp://192.168.32.163/live/stream, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=cpu, view_img=True, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  v7.0-231-gc2f131ab Python-3.10.13 torch-2.1.0+cu121 CPU

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
1/1: rtmp://192.168.32.163/live/stream...  Success (inf frames 1280x720 at 60.00 FPS)

0: 384x640 1 fire, 92.5ms
0: 384x640 1 fire, 66.7ms
0: 384x640 1 fire, 60.4ms
0: 384x640 1 fire, 59.0ms
0: 384x640 1 fire, 60.0ms
0: 384x640 2 fires, 51.0ms
0: 384x640 2 fires, 49.0ms
0: 384x640 2 fires, 54.0ms
0: 384x640 2 fires, 59.0ms
0: 384x640 1 fire, 59.0ms
0: 384x640 1 fire, 52.5ms
0: 384x640 1 fire, 57.2ms
0: 384x640 1 fire, 57.0ms
0: 384x640 1 fire, 50.0ms
0: 384x640 1 fire, 48.7ms
0: 384x640 1 fire, 50.6ms
0: 384x640 1 fire, 51.0ms
0: 384x640 1 fire, 57.6ms
0: 384x640 1 fire, 50.5ms
0: 384x640 1 fire, 58.0ms
0: 384x640 1 fire, 52.0ms
0: 384x640 1 fire, 50.8ms
0: 384x640 1 fire, 52.0ms
0: 384x640 1 fire, 57.0ms
0: 384x640 1 fire, 50.0ms
0: 384x640 1 fire, 58.0ms
0: 384x640 1 fire, 52.0ms
0: 384x640 1 fire, 54.0ms
0: 384x640 1 fire, 58.0ms
0: 384x640 1 fire, 48.0ms
0: 384x640 1 fire, 50.0ms
0: 384x640 1 fire, 52.0ms
0: 384x640 1 fire, 54.5ms
0: 384x640 1 fire, 51.0ms
0: 384x640 1 fire, 45.6ms
0: 384x640 1 fire, 45.0ms
0: 384x640 1 fire, 47.3ms
0: 384x640 1 fire, 63.2ms

**Comment by glenn-jocher** [comment]
@NierAimer based on the provided information, it seems that running the detection on CPU is working for you, but it is causing a significant delay when detecting RTMP or RTSP streams.

Using CPU for detection is generally slower compared to using a GPU. If you're experiencing lags when detecting RTMP or RTSP streams, it could be because the CPU is not able to handle the processing speed required for real-time detection.

To address this issue, you can consider the following options:

1. Upgrade your hardware: If possible, upgrade your system to a machine with a more powerful CPU or, preferably, a compatible GPU. This will significantly improve the detection speed.

2. Optimize the detection process: You can try optimizing the detection process by making changes to the YOLOv5 model or the detection script. This might involve adjusting the model architecture, changing the input image size, or experimenting with different detection parameters. However, keep in mind that these optimizations may impact the accuracy of the detection.

3. Use a more efficient detection model: If you need real-time detection on lower-end hardware, you might consider using a more lightweight and efficient detection model. YOLOv5 is a good starting point, but there are other models available that are specifically designed for real-time detection on resource-constrained systems.

By considering these options, you should be able to improve the real-time detection performance when working with RTMP or RTSP streams.

I hope this helps! Let me know if you have any further questions or concerns.
