### ISSUE TITLE
Convert closed-loop binary mask to yolo format polygon

### ISSUE THREAD

**Issue by halqadasi** [ultralytics/yolov5#12332]
Hello, 
I am trying to train yolov5 or yolov8 with cracks segmentation data.  I read this issue posted below but it did not solve my problem since my binary mask is a bit tricky as shown below, it contains closed loop. 

![Volker_DSC01674_0_1080_1601_1598](https://user-images.githubusercontent.com/98920963/280698569-d0c81d94-1cc5-4be1-aa3f-44a5011648ae.jpg)
The cracks image

![Volker_DSC01674_0_1080_1601_1598](https://user-images.githubusercontent.com/98920963/280698886-17528d64-73b3-45eb-891c-4eb36c7c537c.jpg)
The binary mask

Could you please help me out with this problem since I spent hours?

> Thank you for reaching out. You can convert your binary mask images to YOLO annotation format by using a script that extracts the bounding box coordinates from each mask and saves them in a text file with the same name as the corresponding image.
> 
> The YOLOv8 repo offers a useful script, `create_masks.py`, which can be used to generate YOLO annotations from binary masks. It converts each mask to a grayscale image, thresholded at 127, and then creates a bounding box around each object in the image. The script then saves the bounding box coordinates in a text file with the same name as the corresponding image.
> 
> Once you have generated the YOLO annotations, you can use them to train your YOLOv8 model on your dataset.
> 
> I hope this helps! Let me know if you have any further questions.
> 
> Best regards,
> Glenn Jocher
> Ultralytics Team
> 
> _Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/3085#issuecomment-1583067093_

**Comment by glenn-jocher** [comment]
@halqadasi thank you for reaching out. You can convert your binary mask images to YOLO annotation format by using a script that extracts the bounding box coordinates from each mask and saves them in a text file with the same name as the corresponding image.

The YOLOv8 repo offers a useful script, `create_masks.py`, which can be used to generate YOLO annotations from binary masks. It converts each mask to a grayscale image, thresholded at 127, and then creates a bounding box around each object in the image. The script then saves the bounding box coordinates in a text file with the same name as the corresponding image.

Once you have generated the YOLO annotations, you can use them to train your YOLOv8 model on your dataset.

I hope this helps! Let me know if you have any further questions.

Ultralytics Team

**Comment by halqadasi** [comment]
@glenn-jocher , thank you for your reply. But you only copied and pasted your response from the quote I posted in my issue. I mentioned that I already read your response in the previous thread, but could you please take a minute to see how the binary mask is complicated and tricky, could you please answer these 3 questions: 

1. How can you draw a polygon for a binary mask containing a closed loop?
2. How can you count the number of polygons?
3. Could you please refer me to the `create_masks.py` since I searched in this repo and the yolov8 repo and I did not find this file?

**Comment by glenn-jocher** [comment]
Hi @halqadasi, my apologies for the confusion. I appreciate your patience. Let me address your questions:

1. In order to draw a polygon for a binary mask containing a closed loop, you can use computer vision techniques. One approach is to use contour detection to identify the shapes in your binary mask. Once you have the contours, you can approximate them into polygons using techniques like the Ramer-Douglas-Peucker algorithm or the Freeman chain code.

2. To count the number of polygons in your binary mask, you can use the same contour detection approach mentioned above. After detecting the contours, you can iterate over them and count the number of polygons found.

3. I apologize for the confusion, but there is no `create_masks.py` script in the YOLOv5 or YOLOv8 repos. I must have made an error in my previous response. I apologize for any inconvenience caused.

If you need further assistance with implementing these steps or have any other questions, please let me know. I'm here to help.

Ultralytics Team

**Comment by userwatch** [comment]
Hello @glenn-jocher , I have txt files that I use in the Yolo segmentation model. I want to convert these txt files into masked images. Can you give me an idea? I will use the masked images in the SAM model.
Best wishes :)
