### ISSUE TITLE
PYTORCH TO TFLITE

### ISSUE THREAD

**Issue by oranmichel** [ultralytics/yolov5#1234]
@zldrobit 
hello, is it possible to convert PYTORCH>ONNX>TF>TFLITE, without using keras in the middle?
thank's

**Comment by zldrobit** [comment]
@oranmichel Yes, it is possible. 
I have converted yolov5s model is such a way.
The converted TFLite model was inserted with 2x `#Conv` `transpose` operations by `onnx-tensorrt`:
one before each `Conv` operation and one after each `Conv` operation.
The reason is that ONNX only supports channels of `NCHW` order, while TFLite only supports channels of `NHWC` order.
Those `tranpose` operations takes about 1/3 inference time of whole inference time.
To avoid inserting `transpose` operations, I  use keras in the middle for TFLite export.

You could try to convert PYTORCH>ONNX>TF>TFLITE with `onnx==1.6.0` , `onnx-tensorflow==1.6.0` and `TensorFlow 2.3`.
I tried to convert PYTORCH>ONNX>TF>TFLITE with `onnx==1.6.0` , `onnx-tensorflow==1.6.0-tf1.5` and `TensorFlow 1.15`, but failed.

**Comment by oranmichel** [comment]
Do you mean that the conversion was PYTORCH>ONNX>KERAS>TFLITE?
did you use onnx2keras or built the keras model by urself?

**Comment by zldrobit** [comment]
No. I have converted it in two ways:
1. PyTorch>ONNX>TF>TFLite
2. PyTorch>TF (tf.keras TF 2.0 API)>TFLite as in https://github.com/ultralytics/yolov5/pull/1127.

I haven't used onnx2keras  and in the second method I build TF model by myself, see https://github.com/zldrobit/yolov5/blob/tf-only-export/models/tf.py.

**Comment by oranmichel** [comment]
how is that possible (PyTorch>ONNX>TF>TFLite) if we still have the problem of NCHW/NHWC?
when i try to predict the TFLITE model it won't work

**Comment by zldrobit** [comment]
The trick is inserting a `tranpose` op before to make `conv` of NHWC accept NCHW input, and 
inserting another `tranpose` op after to transfrom output of NHWC back to NCHW.
You could refer to the repo https://github.com/zldrobit/onnx_tflite_yolov3/, but it will take about 1/3 time doing `transpose`.
That repo is for yolov3, and yolov5 requires `onnx-tensorrt=1.6.0` and `tf2.3`.

**Comment by oranmichel** [comment]
OK THANKS

**Comment by zldrobit** [comment]
You're welcome.
