### ISSUE TITLE
Releases of Yolov5

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/yolov5#12356]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The releases of Yolov5 are in the form of v6, v7 ...  
but I see in my code Yolov5 version based on year eg. 2022-1-25.

Can you help me understand how to relate version and year ?
https://github.com/ultralytics/yolov5/releases

**Comment by glenn-jocher** [comment]
@yeongnamtan hi there,

The version numbers of YOLOv5 releases are based on a combination of the year and additional versioning for any changes within that year. For example, the version "2022-1-25" indicates the release made on January 25, 2022.

Hope this helps! Let us know if you have any further questions.

**Comment by yeongnamtan** [comment]
@glenn-jocher I use "2022-1-25" and get below error:
RuntimeError: Cannot find callable 2022-1-25 in hubconf

**Comment by glenn-jocher** [comment]
@yeongnamtan hi there! The error you're encountering is likely due to the fact that "2022-1-25" is not a callable function in the model hub configuration. To resolve this, you should use the correct function or model name as specified in the YOLOv5 documentation or source code. If you're still facing issues, please provide more details so we can assist you further.
