### ISSUE TITLE
 File "F:\yolov5-master\utils\plots.py", line 330, in imshow_cls     ax[i].imshow(blocks[i].squeeze().permute((1, 2, 0)).numpy().clip(0.0, 1.0)) AttributeError: 'numpy.ndarray' object has no attribute 'imshow'

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12365]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 File "F:\yolov5-master\utils\plots.py", line 330, in imshow_cls
    ax[i].imshow(blocks[i].squeeze().permute((1, 2, 0)).numpy().clip(0.0, 1.0))
AttributeError: 'numpy.ndarray' object has no attribute 'imshow'

**Comment by glenn-jocher** [comment]
@ly1035327995 thanks for reaching out. This issue seems to be related to the `imshow` function in the `plots.py` file. The error message indicates that a 'numpy.ndarray' object does not have an attribute 'imshow'. This is likely due to incorrect usage, maybe trying to call imshow on a numpy array.

For a quick resolution, check the usage of the `imshow` function and ensure that it is being called on the correct type of object. Make sure that the input to the `imshow` function is a valid object with the attribute `imshow`.

Let me know if you have any further questions or need additional assistance.

**Comment by ankit-tejwan** [comment]
yolov5-master\utils\plots.py", line 330, in imshow_cls ax[i].imshow(blocks[i].squeeze().permute((1, 2, 0)).numpy().clip(0.0, 1.0)) AttributeError: 'numpy.ndarray' object has no attribute 'imshow' 
*************************************************************************************************************************************
I also face the same issue while training yolov5 for classification so i
just pass the batch size this method --batch 1


its works for me:👍👍✔
CLI
python classify/train.py --model yolov5s-cls.pt --data cls_data  --batch 1 --epochs 200  --pretrained weights/yolov5s-cls.pt

**Comment by glenn-jocher** [comment]
Hey there! 👋 Great to hear you found a workaround by adjusting the batch size to 1. For those encountering the same issue with `imshow_cls` in `utils/plots.py`, this could indeed serve as a quick fix, especially during classification tasks.

In case others run into a similar situation, here's a quick snippet based on your solution:

```bash
python classify/train.py --model yolov5s-cls.pt --data cls_data --batch 1 --epochs 200 --pretrained weights/yolov5s-cls.pt
```

Remember, this approach adjusts the batch size, which might impact training dynamics, so keep an eye on your model's performance. If the problem persists or if you have other concerns, feel free to reach out again!

Happy training! 🚀
