### ISSUE TITLE
Issue: Different output video duration compared to input video

### ISSUE THREAD

**Issue by JerickoDG** [ultralytics/yolov5#12372]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi. While I was using `detect.py` perform inference on an .mp4 file, the output video (with bboxes) became shorter. To confirm it, I tried using another video and it also became shorter (from approximate 32 minutes to approximately 29 minutes). Here is the image that shows the issue I am pertaining to.

![image](https://github.com/ultralytics/yolov5/assets/60811658/3448b482-d05f-406d-b2b3-a9f551f94e8e)

May I ask the probable reason as to why this occurs and how it can be fixed? 

I hope for your response(s). Thank you.

**Comment by JerickoDG** [comment]
Here are some details about my input video:

![image](https://github.com/ultralytics/yolov5/assets/60811658/15209c7c-c79c-4a54-b16e-7ff82fdb8736)

The video was also sourced from a home security camera TP-Link Tapo TC70.

**Comment by JerickoDG** [comment]
I tried reading the frames of the video and reconstructing it using cv2.VideoWriter() and it provided the same problem leading me to think that the problem is either from the input video itself or cv2.VideoWriter(). However, I am not sure which of those and the reason why.

Any responses/insights will be much appreciated. Thank you.

**Comment by glenn-jocher** [comment]
@JerickoDG 👋 Thanks for providing more details on the issue. Since the problem persists when reconstructing the video using `cv2.VideoWriter()`, it's likely related to the input video itself. Some potential issues could be non-uniform frame rates, corrupted frames, or timestamps. 

To troubleshoot, I recommend checking the properties of the input video using OpenCV's `cv2.VideoCapture()` to inspect the frame rate and frame count. This may provide insights into any inconsistencies in the input video that could cause the output to be shorter.

Additionally, you may want to verify the integrity of the input video file, and consider trying the process with a different video source to see if the issue is specific to the TP-Link Tapo TC70 videos.

If you'd like to share your findings, we can help further diagnose the issue. Thank you for your patience and persistence in troubleshooting this.
