### ISSUE TITLE
val.py don't show the P, R, mAP50 and mAP50-95 score, and cannot run detect.py with custom model 

### ISSUE THREAD

**Issue by anhtr-nguyn** [ultralytics/yolov5#12384]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation, Detection

### Bug

The data I collected through roboflow and choose correct type: yolov5pytorch. I have also trained my custom model successfully on https://hub.ultralytics.com/ and download it. I also download the data and change the path to val and test.

When I run `python3 val.py --weights traffic_sign_yolov5s.pt --data /home/tronganh/hcmut/datasets/data.yaml --batch-size 1`, the output was quite normal:

`             Class     Images  Instances          P          R      mAP50   mAP50-95:   2%|▏         | 3/174 [00:00<00:49,  3.44itException in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tronganh/hcmut/yolov5/utils/plots.py", line 172, in plot_images
    cls = names[cls] if names else cls
KeyError: 8975
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 174/174 [00:31<00:00,  5.46
                   all        174        227          0          0          0          0
`, However, it could not show the score. 
 
Moreover, when I run ` python3 detect.py --weights traffic_sign_yolov5s.pt --source /home/tronganh/hcmut/datasets/test/images/` , the error is:
`
Traceback (most recent call last):
  File "detect.py", line 285, in <module>
    main(opt)
  File "detect.py", line 280, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 34, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 175, in run
    s += f"{n} {names[int(c)]}{'s' * (n > 1)}, "  # add to string
`.
When I change to default model yolov5s.pt, it could run normally

### Environment

OS: Ubuntu on Jetson Xavier, run on image of pytorch (l4t)
Python: 3.8.10 
YOLOv5 🚀 2023-11-15 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CUDA:0 (Xavier, 6857MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@anhtr-nguyn hi there! It looks like you're experiencing some issues with YOLOv5 validation and detection using a custom model. The validation `val.py` seems to be running normally but without displaying the scores, and the `detect.py` is throwing an error when using your custom model. The error may be caused by class name mapping or an incompatible custom model.

You could start by checking your custom model's class names and ensuring they correspond to the expected format. Also, ensure that the custom model you downloaded is compatible with the YOLOv5 implementation.

For the detection issue, you can try updating your custom model's class names and ensuring it is compatible with the `detect.py` script.

Let me know if you need further assistance with this! Also, make sure to refer to the YOLOv5 documentation (https://docs.ultralytics.com/yolov5/) for guidance on using custom models and troubleshooting common issues. 😊

**Comment by anhtr-nguyn** [comment]
@glenn-jocher Thanks for your reply. I have tried many methods including changing the name of model.  I realized that the model which was trained through **ultralytics HUB** has some error and could not run normally, maybe the version on **ultralytics HUB** is **Yolov5su**. After I trained the model on local, everything has worked. Thanks for your dedication

**Comment by glenn-jocher** [comment]
You're welcome, @anhtr-nguyn! I'm glad to hear that you were able to resolve the issue by training the model locally. The YOLOv5 community and the Ultralytics team are dedicated to providing a seamless experience for users, and your feedback is valuable for improving the platform. If you have any more questions or need further assistance in the future, feel free to reach out. Good luck with your YOLOv5 projects!
