### ISSUE TITLE
Problem when apply Yolov5 in PyQt 

### ISSUE THREAD

**Issue by anewworl** [ultralytics/yolov5#12387]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

So when i try to convert the processed image from the run() function in detect.py to present in on pyqt. I see that there is a window automatically pop up and turn off repeatedly which make conflict with the thread of qt. If you look the clip below you will understand more about my case. So i want to disable the small window which pop up repeatedly which have no name so i can not traceback where the code is located.

https://drive.google.com/file/d/17PbV7k3M9P6cdy9MbhjHUhtza1w87DBT/view?usp=drive_link

### Minimal Reproducible Example

this is the code for convert:
import cv2
import numpy as np
import math
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtCore import QElapsedTimer,QThread, QObject, pyqtSignal as Signal, pyqtSlot as Slot, Qt
from PyQt5 import QtGui
from test_seg_2 import run

class CaptureSignals(QObject):
    newPixmapCaptured = Signal(np.ndarray)

class capture_video(QThread):

    #updateDetail = Signal(list)

    def __init__(self) -> None:
        super().__init__()
        self.foreGroundIm: cv2.Mat # self.drawFrame = self.foreGroundIm.copy()
        self.backGroundIm: cv2.Mat
        self.RealsenseVideo: cv2.VideoCapture
        self.cameraState:bool = False
        self.num = 0
        self.signals = CaptureSignals()
        self.flag = 0

    def cvMatToQImage(self,inMat:cv2.Mat) -> QImage:
        rgb_image = cv2.cvtColor(inMat, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        image = QImage(rgb_image.data, w, h, ch * w, QImage.Format_RGB888)
        return image

    def connectCamera(self)-> None:
        self.RealsenseVideo = cv2.VideoCapture(1)
        self.RealsenseVideo.set(cv2.CAP_PROP_FRAME_WIDTH,640)
        self.RealsenseVideo.set(cv2.CAP_PROP_FRAME_HEIGHT,480)

    def getScreenShot(self) -> None:
        cv2.imwrite('sample/img' + str(self.num) + '.png', self.foreGroundIm)
        print("image saved!")
        self.num += 1

    def disconnectCamera(self) -> None:
        self.RealsenseVideo.release()

    #@Slot()
    def run(self):
        if self.flag == 1:
            print('thread0')
            #self.connectCamera()
            #while True:
            #ret, self.foreGroundIm = run(weights='best.pt',data='data.yaml', source=1, view_img=False)
            #weights = 'best.pt', data = 'data.yaml', source = 1
            while True:
                ret, self.foreGroundIm = run(weights='best.pt', data='data.yaml', source=1)
                print('emit')
                self.signals.newPixmapCaptured.emit(self.foreGroundIm)
                if cv2.waitKey(1) == ord('q'):  # 1 millisecond
                    exit()
        elif self.flag == 2:
            print('thread1')
            self.connectCamera()
            while True:
                ret, self.foreGroundIm = self.RealsenseVideo.read()
                if ret:
                    # print('emit')
                    self.signals.newPixmapCaptured.emit(self.foreGroundIm)

            #self.backGroundIm = cv2.imread("src\\../Image/Background.jpg")
            #self.newPixmapCaptured.emit(self.foreGroundIm)
/////////////////////////////////////////////////////////////////////////////////
this is the code where i get the frame and emit the frame through pyqtsignal

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
It appears that you're facing an issue where a window pops up and closes repeatedly when trying to display images processed by YOLOv5 in a PyQt application. This behavior can be disruptive, especially when integrating with a PyQt GUI. The issue likely lies in how the image data is being handled and displayed within your PyQt application.

To resolve this, you should ensure that the YOLOv5's output image is correctly processed and then passed to the PyQt GUI without opening an additional window. Here's a step-by-step guide to troubleshoot and potentially fix this issue:

1. **Disable OpenCV Windows**: Ensure that no OpenCV functions like `cv2.imshow()` are being called in your code or in the YOLOv5 `run` function that you are using. Such calls can create additional windows outside of your PyQt application.

2. **Verify YOLOv5 Output**: Make sure that the `run` function from `test_seg_2.py` (or any other script you're using) returns only the processed image frame and does not include any code that might create additional windows or display frames.

3. **Check PyQt Image Handling**: In your PyQt thread (`capture_video` class), you're capturing the frame emitted by YOLOv5 and converting it to a QImage for display in PyQt. Ensure that this conversion is done correctly. The `cvMatToQImage` method appears to be correct, but ensure it's used properly in the context of your PyQt application.

4. **Update PyQt GUI Properly**: Make sure that the signal (`newPixmapCaptured`) is connected to an appropriate slot in your main PyQt application that updates the GUI with the new image. This update should be done in a way that integrates seamlessly with the Qt event loop.

5. **Remove Redundant cv2.waitKey()**: The line `if cv2.waitKey(1) == ord('q'):` in your thread run method is unnecessary for a PyQt application and might interfere with the event loop. PyQt has its own event handling system, and this OpenCV function is typically used in standalone OpenCV applications.

6. **Thread Management**: Ensure that the PyQt thread handling the video capture and processing is well-managed and does not conflict with the main PyQt event loop. Mismanagement of threads can lead to unexpected GUI behavior.

By following these steps, you should be able to pinpoint the source of the problem. If the issue persists, consider creating a minimal, reproducible example that isolates the problem, which can be shared for further assistance. Additionally, since you are willing to submit a PR, you might want to look into how the integration of YOLOv5 and PyQt is managed in the broader context of the application to ensure compatibility and efficiency.
