### ISSUE TITLE
yolov5 training keeps crashing for batch sizes > 1

### ISSUE THREAD

**Issue by gigumay** [ultralytics/yolov5#12392]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Hi, 
I'm trying to compare the performance of yolov5x6 and yolov8x on animal detection from UAV images. 
I have successfully trained yolov8x on my dates using the default image- (640) and batch-size (16). Here is the resource usage of my GPU as obtained from wandb:

<img width="1345" alt="Screenshot 2023-11-18 at 13 31 32" src="https://github.com/ultralytics/yolov5/assets/143072547/20c995f0-38cc-4996-991c-4258a4c12be6">

Since the recommended image size for yolov5x6 is 1280, I am trying to use the latter, but training keeps crashing. I tried to reduce the batch size to 4, but since that failed I attempted auto-batching - unfortunately without success. Here are the GPU logs for the auto-batching attempt:

<img width="1353" alt="Screenshot 2023-11-18 at 13 31 54" src="https://github.com/ultralytics/yolov5/assets/143072547/4ca8831f-1f93-46e8-8157-6efe0e63f5dd">

It seems to me like the power usage is the problem rather than the GPU memory. I am currently training with batch-size 1, just to see if it crashes, and so far it's running:

<img width="1337" alt="Screenshot 2023-11-18 at 13 33 59" src="https://github.com/ultralytics/yolov5/assets/143072547/90182dd8-164c-4dd0-b67b-0ceaa0cc81f3">

Obviously, training with a batch size of 1 is undesirable both in terms of comparability to yolov8x but also w.r.t. training duration. Is this a hardware problem? I was also wondering whether it could be due to yolov5x6 being larger than yolov8x on top of the increased image size?

Thanks a lot!

### Environment

- YOLO: yolov5x6
- Ubuntu: Ubuntu 20.04.6 LTS
- Python: 3.10
- GPU: NVIDIA GeForce RTX 3090 (24.5 GB of memory)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gigumay hi there! Thanks for reaching out. Regarding the training crashes for batch sizes larger than 1, could you ensure that you are using the recommended image sizes for YOLOv5x6 and double-check your configuration settings? Additionally, scaling batch sizes often requires proportional adjustment of learning rates and vice versa. It's commendable that you are comparing model performance! The behavior you're seeing could indeed be due to the increased model complexity and image size. It's terrific that training is progressing with batch size 1. Your GPU resource monitoring is quite insightful. Let's continue our investigation to ensure we can scale up batch sizes while maintaining stability. I hope this helps!

**Comment by gigumay** [comment]
Thanks a lot for the reply @glenn-jocher!
I've run into some weird behavior for batch size = 1 that I can't really make sense of. It crashed about  9 hours into the training and showed some weird GPU stats: 

<img width="1803" alt="Screenshot 2023-11-20 at 11 11 35" src="https://github.com/ultralytics/yolov5/assets/143072547/d44eace8-a12c-481d-b2a5-dc438f86e010">

I've since tried to train on 640 patches and batch size = 16, which so far is looking a lot better (training still stable after 23 hours): 
 
<img width="1803" alt="Screenshot 2023-11-20 at 11 12 16" src="https://github.com/ultralytics/yolov5/assets/143072547/ad2fe08f-30d1-4cdf-a0dd-d63a482b4574">


According to [this](https://pytorch.org/hub/ultralytics_yolov5/), the appropriate input size for yolov5x6 is 1280, though.  Any idea what could be going on?

**Comment by glenn-jocher** [comment]
@gigumay You're welcome! It's promising that training with batch size 16 on 640 patches is stable. It's possible that the larger input size for yolov5x6 (1280) is leading to instability due to the amplified computational load. As recommended in the PyTorch Hub page, the input size for yolov5x6 is indeed 1280. When increasing the input size, it's essential to ensure that your hardware can accommodate the additional workload. It might be beneficial to review the GPU resource usage during training to identify any potential bottlenecks. Feel free to share more details about your setup or additional logs if needed. I'm here to assist!

**Comment by gigumay** [comment]
Hi, 
and thanks again for the feedback! Reducing my GPU power limit solved the issue!

**Comment by glenn-jocher** [comment]
That's great news, @gigumay! It's impressive how you were able to troubleshoot and resolve the issue by adjusting your GPU power limit. Your proactive approach is commendable. Don't hesitate to reach out if you encounter any more challenges or have further questions. Happy training!
