### ISSUE TITLE
Mosaic is disabled due to personal data set limitations

### ISSUE THREAD

**Issue by geolvr** [ultralytics/yolov5#12417]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Among the many categories in my dataset, there are some categories where **category A is visually part of category B**. Therefore, **any shearing, scaling (ratio greater than 1), translating operation may lead to confusion between category A and category B.**
I tried **disabling mosaic, scale, shear, and translate** during training. However, it resulted in a significant decrease in model performance.
I also tried **enabling mosaic and turning off scale, shear, and translate**. However, since mosaic randomly selects the center point of the spliced image, parts of the four sub-images will still be lost, leading to potential confusion between category A and category B. The experimental results are still not good.
I speculate that this is related to some characteristics of yolo itself. But obviously, enabling such data augmentation is inappropriate for my dataset. Is there a better way to solve this problem?

**Comment by glenn-jocher** [comment]
@geolvr hi there! Thanks for reaching out. It sounds like you're facing a challenging situation with your dataset. Understanding the limitations you've mentioned, such as disabling mosaic and augmentation operations, it's clear you've put a lot of effort into optimizing performance.

Have you considered fine-tuning the YOLOv5 architecture for your specific use case? You might find our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) helpful in exploring advanced customization options. Additionally, experimenting with architecture modifications or alternative models may also provide insights.

Your dedication to resolving this issue is commendable. The YOLOv5 community is here to support you every step of the way!
