### ISSUE TITLE
Cls_loss is 0

### ISSUE THREAD

**Issue by fyy378** [ultralytics/yolov5#12416]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/yolov5/assets/145305135/57ba54f3-8ca5-4744-9470-879974135b3c)
![image](https://github.com/ultralytics/yolov5/assets/145305135/c728d1bd-bba0-4b7c-b23c-b2ba5c434177)
Hello, I trained YOLOv5_5.0and YOLOv5_6.1 version, there is only one class, why is its class loss 0?

**Comment by glenn-jocher** [comment]
@fyy378 hello! It's great to hear that you are using YOLOv5 for your project. The class loss being 0 for a single class is expected behavior, since there is only one class to predict. If you have any further questions or need assistance with anything else, feel free to ask! The YOLOv5 community and our team are here to help. Also, don't forget to check out the YOLOv5 documentation for more information and guidance.
