### ISSUE TITLE
Does yolov5 ignore what is outside the bounding box, or learn that the outside does not belong to an object class?

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/yolov5#12443]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I was wondering if yolov5 when training ignores what is outside the bounding box or if it takes into account and says to itself "this is not any class" and learns that it is not an object. I mean it makes sense to think that when the pixels are being processed there is a decisor that says, "these pixels belong to the class", "those ones do not belong to the class" and learns not only what is inside but what is outside. Does it work like this?
I have other question, lets think hipotetically, in one scenario that i have 1000 images of an object in the woods. In another scenario I have 1000 images of an object in the city. If now I show the object in the city to a model trained in Scenario 1, do I have worse detection results than if I show the object in the city to the model I trained in Scenario 2? 

Thanks!

**Comment by glenn-jocher** [comment]
@Pedro-Leitek yes, YOLOv5 considers both the content inside and outside of the bounding box during training, learning to distinguish between object and non-object pixels. Regarding your hypothetical scenarios, a YOLOv5 model trained on city images will likely perform better on city images and vice versa, due to environmental variations. For details, check our [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Thanks!
