### ISSUE TITLE
yolov5-v7.0 training custom data encounter cpu problem

### ISSUE THREAD

**Issue by jiaminglei-lei** [ultralytics/yolov5#12446]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

when I started training with custom data with following command
`python train.py --data ~/yolov5-7.0/data/custom_data.yaml --weights '' --cfg models/yolov5s.yaml --batch 16 --epochs 300 --hyp data/hyps/hyp.scratch-high.yaml  --device 7`
Have no error. It will start training.
But the key problem is, it just used two cpu core in dataloader. These cpu cores are 100% running, and make the training very slowly.
I think it will use other cpu cores normally.
And I reinstall the environment several times, but it does not work.
In other project, like paddledetection, it uses other cpu core.

Any idea to fix this problem?

### Additional

env: python 3.8, pytorch 1.10.1, cuda 11.3

**Comment by glenn-jocher** [comment]
@jiaminglei-lei thanks for reaching out! This issue might be due to the default `torch.utils.data.DataLoader` settings. You can try setting the `num_workers` option in your data loader to leverage more CPU cores, e.g. `--workers 8`. Also, make sure that your operating system and PyTorch installations are properly configured for multi-threading. The YOLOv5 GitHub Discussions may have related threads that could be helpful. Keep up the great work!

**Comment by jiaminglei-lei** [comment]
@glenn-jocher  thanks for replying. 
I tried the setting of `num_workers`, but it did not work.
I think it might the problem of installed environment. 
So I removed the environment, re-create it with conda and reinstall the `pytorch` with `pip`, it ran normally.

If someone encourter this issue, try to install all the package with `pip install` rather than `conda install`.

**Comment by glenn-jocher** [comment]
@jiaminglei-lei glad to hear you were able to resolve the issue! Thanks for sharing your solution with the community. If you need further assistance, feel free to ask. Keep up the great work!
