### ISSUE TITLE
How can I load a trained model for real-time object detection from a camera? 

### ISSUE THREAD

**Issue by zsc14752** [ultralytics/yolov5#12488]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

My program keeps encountering an error at the line model = torch.hub.load('ultralytics/yolov5', 'yolov5s',force_reload=True, trust_repo=True)
error message:AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'
![錯誤1](https://github.com/ultralytics/yolov5/assets/115033784/4f848405-2538-4610-8d41-2e53349739c2)
![image](https://github.com/ultralytics/yolov5/assets/115033784/237cc1a2-ba66-4846-80af-4067402c6fcd)
I hope you can tell me the reason for the error and provide me with the correct program directly. Thank you!

**Comment by zsc14752** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> My program keeps encountering an error at the line model = torch.hub.load('ultralytics/yolov5', 'yolov5s',force_reload=True, trust_repo=True)
> 
> ### Additional
> _No response_

**Comment by glenn-jocher** [comment]
@zsc14752 hi there! The error seems to be related to a numpy module, not YOLOv5 specifically. This could be due to an incompatible numpy version or environment settings. Could you try updating numpy with `pip install --upgrade numpy` and see if that resolves the issue? For real-time object detection from a camera, you can refer to the `detect.py` example in our [documentation](https://docs.ultralytics.com/yolov5/), which shows how to load a trained model and detect objects from a live camera stream. Let me know if you need further assistance!

**Comment by zsc14752** [comment]
thamks you!

**Comment by glenn-jocher** [comment]
@zsc14752 you're welcome! If you have any more questions or encounter any issues, feel free to ask. Good luck with your project!
