### ISSUE TITLE
why the parameters of YOLOV5S in my experiment are not matched with the official offered ones?

### ISSUE THREAD

**Issue by MengtianLee** [ultralytics/yolov5#12485]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/yolov5/assets/42642078/483b7950-e9ef-474f-8eb9-612ce99bcbf4)
![image](https://github.com/ultralytics/yolov5/assets/42642078/1d118716-2955-42b0-8669-9113ed4b8c7d)
The official offered parameters of yolov5s are 7.2 M, but in my experimental paramters are about 7.0M. Why they are different? 
Could anyone helps me?  I am really confused about this issue. Thank you so much.

**Comment by glenn-jocher** [comment]
@MengtianLee hi there! The reported model parameters for YOLOv5s can vary slightly due to different training setups and configurations, so a 0.2M difference is not unusual. Please verify that the training and inference configurations match the official settings, and feel free to consult the Ultralytics Docs for guidance and best practices. Happy to help!
