### ISSUE TITLE
Get coordinates from Yolov5 segment model

### ISSUE THREAD

**Issue by iskenderkahramanoglu** [ultralytics/yolov5#12483]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I want to get polygon coordinates from the Yolov5 segment model.
Is there an easy way for this like Yolov8?
How can I get the coordinates without manipulating the predict.py file?

**Comment by glenn-jocher** [comment]
@iskenderkahramanoglu you can obtain polygon coordinates from the YOLOv5 segment model with `model.predict(img, augment=True, visualize=False)`. Check out the `model.xyxy` outputs 📦. For more details, visit the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

**Comment by iskenderkahramanoglu** [comment]
> @iskenderkahramanoglu you can obtain polygon coordinates from the YOLOv5 segment model with `model.predict(img, augment=True, visualize=False)`. Check out the `model.xyxy` outputs 📦. For more details, visit the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

Hi Glenn, thanks for your reply.

How should I install the model to use this code?
I tried to load the model with torch.hub.
But I get an error: "AttributeError: 'DetectMultiBackend' object has no attribute 'predict'."

**Comment by glenn-jocher** [comment]
@iskenderkahramanoglu You can install the YOLOv5 models using `torch.hub.load('ultralytics/yolov5', 'yolov5s')`. Make sure you use the appropriate model name ('yolov5s', 'yolov5m', 'yolov5l', 'yolov5x') as per your requirement. The error you encountered might be due to the model not being loaded properly. If you need further assistance with model installation or usage, feel free to ask!

**Comment by iskenderkahramanoglu** [comment]
> @iskenderkahramanoglu You can install the YOLOv5 models using `torch.hub.load('ultralytics/yolov5', 'yolov5s')`. Make sure you use the appropriate model name ('yolov5s', 'yolov5m', 'yolov5l', 'yolov5x') as per your requirement. The error you encountered might be due to the model not being loaded properly. If you need further assistance with model installation or usage, feel free to ask!

@glenn-jocher I can load the object detection models with torch.hub and I don't encounter any problem when taking tests.
However, when I try to load segmentation models and take tests, I get this error.
There is no problem with the yolov5x model, but I cannot get tests with the yolov5x-seg model.

**Comment by glenn-jocher** [comment]
@iskenderkahramanoglu Apologies for any inconvenience. The `yolov5x-seg` model is specific to the segmentation task, and the error you're encountering might be due to differences in model implementation. Since segmentation models have different outputs compared to object detection models, I recommend reviewing the segmentation model usage in the YOLOv5 documentation or seeking assistance from the Ultralytics team for specific guidance. Let me know if you need further help!

**Comment by pinnintipraneethkumar** [comment]
@iskenderkahramanoglu  Hi, can you able to get cordiantes from yolov5 segment model if yes , can you please share your approach?

Thank you.
