### ISSUE TITLE
about vid_strid

### ISSUE THREAD

**Issue by hytxx** [ultralytics/yolov5#12497]
https://github.com/ultralytics/yolov5/blob/f400bba7836c1dbc2771db251984f20009b5fa81/utils/dataloaders.py#L300C20-L300C20
@glenn-jocher Hello, I have a question about vid_strid. After for _ in range(self.vid_stride): , why is it not self.frame += self.vid_strid? If my video has 100 frames and vid_strid=10, then my detection frames are 10, 20, ... but the output still shows 1, 2, ...

**Comment by glenn-jocher** [comment]
@hytxx hi there! 🌟 The `vid_strid` variable in `dataloaders.py` isn't a typo but rather an internal counter for video frame strides. It ensures only every `vid_strid`th frame is used for inference. For your scenario, the output reflects frame numbers as in the original video, but only every 10th frame is inferred upon due to `vid_strid=10`. More details on the video handling can be found in the Ultralytics Docs at https://docs.ultralytics.com/yolov5/. Let me know if you have more questions!

**Comment by hytxx** [comment]
Thank you, I understand your explanation now. This issue can be closed.

**Comment by glenn-jocher** [comment]
@hytxx you're welcome! I'm glad I could help clarify that for you. If you have any more questions in the future, don't hesitate to ask. Happy detecting! 😊🚀
