### ISSUE TITLE
How to print the TP,FP,FN,TN in the terminal?

### ISSUE THREAD

**Issue by ZwNSW** [ultralytics/yolov5#1251]
## ❔Question

I want to get tp to analyze my own data set, but I cannot output it after running test.py？

**Comment by glenn-jocher** [comment]
@ZwNSW TP and FP vectors are computed here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L250-L319

**Comment by ZwNSW** [comment]
@glenn-jocher Hello，thank for your professional answer,but when I run your code,I got an error like this
“    ap[ci, j], mpre, mrec = compute_ap(recall[:, j], precision[:, j])
TypeError: cannot unpack non-iterable numpy.float64 object”。I guess this should be an error caused by the assignment.Looking forward to your reply and correct modification。
`# AP from recall-precision curve 
             for j in range(tp.shape[1]): 
                 ap[ci, j], mpre, mrec = compute_ap(recall[:, j], precision[:, j]) 
                 if j == 0: 
                     py.append(np.interp(px, mrec, mpre))  # precision at mAP@0.5`

I have another question. When I output i, TP, FP to the terminal, the structure is like this. How can I read this list? I don’t know if the data is TP, or FP, or something else.
![微信图片_20201101102528](https://user-images.githubusercontent.com/57338462/97793859-96425380-1c2c-11eb-9c41-70768a9a7868.png)

`            # AP from recall-precision curve
            py.append(np.interp(px, recall[:, 0], precision[:, 0]))  # precision at mAP@0.5
            for j in range(tp.shape[1]):
                ap[ci, j] = compute_ap(recall[:, j], precision[:, j])
    print(i)
    print(i.shape)
    print(tpc)
    print(tpc.shape)
    print(fpc)
    print(fpc.shape)
    print(n_gt)#  Number of ground truth objects
    print(n_p)# Number of predicted objects
    # Compute F1 score (harmonic mean of precision and recall)
    f1 = 2 * p * r / (p + r + 1e-16)
`

**Comment by ZwNSW** [comment]
@glenn-jocher Thanks for your answer.When I run the code you gave, there was an error like this.
"    ap[ci, j], mpre, mrec = compute_ap(recall[:, j], precision[:, j])
TypeError: cannot unpack non-iterable numpy.float64 object"
I guess this should be an error during the assignment. But I don't know how to correct it.

**Comment by ZwNSW** [comment]
When I print i, tpc, fpc, and their types to the terminal, I don't know which part is tpc, fpc, because the output of the terminal is as shown in the figure.I want to get tp, fp, fn for each category, and look forward to your answers and responses.
![image](https://user-images.githubusercontent.com/57338462/97794023-300b0000-1c2f-11eb-8cb7-d15dcd3caf53.png)

**Comment by ZwNSW** [comment]
![Uploading tp.png…]()

**Comment by ZwNSW** [comment]
![Uploading tp.png…]()

**Comment by rita9410** [comment]
@ZwNSW did you manage to find out the values ​​of tp, fp and fn?

**Comment by glenn-jocher** [comment]
@rita9410 TP and FP vectors are computed here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L250-L319

**Comment by rita9410** [comment]
@glenn-jocher ok, but how can I print these variables by each class?

**Comment by glenn-jocher** [comment]
@rita9410 YOLOv5 TP and FP vectors are computed here:
https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L250-L319

They don't print out by default, you'd have to introduce some custom code to see them.

`fpc` and `tpc` are the FP and TP arrays of shape (n,10), for the 10 iou thresholds of 0.5:0.95. If you look at the last row, this is the FP and TP count per iou threshold:

```python
tpc.shape
Out[3]: (3444, 10)
fpc.shape
Out[4]: (3444, 10)
tpc[-1]
Out[5]: array([138, 124, 105,  91,  80,  66,  54,  38,  22,   9])
fpc[-1]
Out[6]: array([3306, 3320, 3339, 3353, 3364, 3378, 3390, 3406, 3422, 3435])
```

So at 0.5 iou and 0.001 confidence threshold, for class 0, dataset inference results in 138 TPs and 3306 FPs.

**Comment by dariogonle** [comment]
> @rita9410 YOLOv5 TP and FP vectors are computed here:
> https://github.com/ultralytics/yolov5/blob/c8c5ef36c9a19c7843993ee8d51aebb685467eca/utils/general.py#L250-L319
> 
> They don't print out by default, you'd have to introduce some custom code to see them.
> 
> `fpc` and `tpc` are the FP and TP arrays of shape (n,10), for the 10 iou thresholds of 0.5:0.95. If you look at the last row, this is the FP and TP count per iou threshold:
> 
> ```python
> tpc.shape
> Out[3]: (3444, 10)
> fpc.shape
> Out[4]: (3444, 10)
> tpc[-1]
> Out[5]: array([138, 124, 105,  91,  80,  66,  54,  38,  22,   9])
> fpc[-1]
> Out[6]: array([3306, 3320, 3339, 3353, 3364, 3378, 3390, 3406, 3422, 3435])
> ```
> 
> So at 0.5 iou and 0.001 confidence threshold, for class 0, dataset inference results in 138 TPs and 3306 FPs.


@glenn-jocher, is it a way to print the TPs and FPs at a certain confidence? I mean I'd like to know the number of TPs and FPs at 0.5 iou and 0.60 confidence. Is it possible?


And what does the 3444 means in the tcp.shape output?

**Comment by glenn-jocher** [comment]
@dariogonle the example you copied already prints them out at 10 different IoUs from 0.5 to 0.95. Results are evaluated at the --conf you supply.

**Comment by dariogonle** [comment]
@glenn-jocher thank you for your response, but I would like the following: When I do a test I get the following Precision and Recall.
![image](https://user-images.githubusercontent.com/80393891/121569348-fac65c00-ca20-11eb-98d4-2ed2c293d8ac.png)


I'd like to know the number of TP and FP used to calculate that Precision and Recall. The precision and recall given are for a certain confidence (the one that maximizes the F1), 0.75 in this case. When I run this test (default conf-thres = 0.001) I get the following TPs and FPs.

![image](https://user-images.githubusercontent.com/80393891/121570280-049c8f00-ca22-11eb-9381-4c43854c5fe1.png)
 
So the supposed precision,  for iou=0.5, should be => P = 262/(262+1984) = 0.11, but in the output the precision is 0.89. If I print the n_l variable in ap_per_class I get 284, so the recall should be R = 262/284 = 0.92, but the output recall is 0.78.

I was wondering how recall and precision is calculated. I guess that the number of TPs and FPs shown in the second image are for all confiances, but the precision and recall shown in the first image is for a certain level of confidence (0.75 in this case, because it is the value that maximizes the F1). That's why I asked you if there is a way to output the TPs and FPs for a certain confidence.

 I'm sure that I'm missing something, but I can't figure it out. Thank you in advance.

**Comment by glenn-jocher** [comment]
@dariogonle see metrics.py for P and R computation.
https://github.com/ultralytics/yolov5/blob/5c32bd3080c8643aed9c167bb2fc655f502facaf/utils/metrics.py#L19-L79

**Comment by dariogonle** [comment]
@glenn-jocher  I understand how precision and recall are calculated but I don't understand the number of TPs and FPs that I get.

If R = TP/Targets then TP = R*Target = 0.78 * 284 = 222. Then if P = TP / (TP + FP) then FP = 27. With this theoretical values for TPs and FPs it is possible to get a precision of 0.89 and a recall of 0.78. But the output of tpc[-1] and fpc[-1] does not match with this values.

**Comment by glenn-jocher** [comment]
@dariogonle FPs and TPs are computed in the code I provided above on L53 and L54

**Comment by glenn-jocher** [comment]
@ZwNSW @dariogonle good news 😃! Your original issue may now be fixed ✅ in PR #5727. This PR explicitly computes TP and FP from the existing Labels, P, and R metrics:

```bash
TP = Recall * Labels
FP = TP / Precision - TP
```

These TP and FP per-class vectors are left in val.py for users to access if they want:
https://github.com/ultralytics/yolov5/blob/36d12a500eae4561d09d4955e1b50b12e57bf6c6/val.py#L240

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by a227799770055** [comment]
@glenn-jocher  
If I want to know which images were FN or FP, can I got the image id or image name by modified the code?
Thanks a lot!

**Comment by glenn-jocher** [comment]
@a227799770055 we're working on better results introspection tools to allow you to see the worst performing images in a validation set. This isn't near to release yet but should be rolled out over the next few months. I'll add a note to allow for sorting by different metrics like FN, FP, mAP etc.

@kalenmike

**Comment by irgipaulius** [comment]
@glenn-jocher is there any progress on this?

**Comment by muhilhamms21** [comment]
Hii, it looks like theres no progress in here, but i want to ask some question because recently i just got this issue and i dont know how to solve it. I already print the TP and FP to the terminal but it looks like the number of TP and FP printed on the terminal doesnt add up with the label in the prediction image. The number of TP and FP is lower than the label present in the prediction image, even theres cases where one of the class i have got soo many FP but the FP number i got in terminal is 0. Is there anyone know about this? Thankyou in Advance

**Comment by glenn-jocher** [comment]
@Rsphyxs hello! It's possible that there's a discrepancy between the TP and FP values you computed and the labels in the prediction images due to differences in how the metrics are computed. It's also possible that your implementation of printing TP and FP is not accounting for all cases.

One way to investigate this further would be to manually compare the labels in the prediction images with the computed TP and FP to see if there are any mismatches. Additionally, you can try checking your implementation of printing TP and FP for any errors or bugs.

Hope this helps! Let us know if you have any more questions.

**Comment by muhilhamms21** [comment]
Thankyou so much for your reply @glenn-jocher . I already check my implementation of printing the TP and FP because i follow your guide for it and i dont think theres issue on it. But i have follow up question, i am newbie in object detection so theres several things i probably didnt know, but i realized that FP value is based on TP and TP got its value from recall * labels right? but i just realized the class that i mention got 0 TP and FP even though theres a label prediction both TP and FP label for its class, and when i checked the corresponding class have 0 Recall, how is that possible? Since what i know is recall is how much TP the class got from all the right label? Below is image i attached to give more information regarding this issue. Thankyou in advance again. For addition information, i test several images with different scenario, and some of it got a right result for TP and FP but the several others dont match up between the labels in prediction images and in the result

Labeled image for validation (Sorry i have to censored the face cause its personal)
![image](https://github.com/ultralytics/yolov5/assets/81289755/f77572d0-ca56-490a-9311-7676b909f2f3)

Predicted image
![image](https://github.com/ultralytics/yolov5/assets/81289755/a71c124c-92d4-4573-ae3b-1f4fe7e49979)

Result i got
![image](https://github.com/ultralytics/yolov5/assets/81289755/48884380-ef7e-4f2c-870c-bced42684210)

**Comment by glenn-jocher** [comment]
@Rsphyxs, it's possible for a class to have a 0 recall value even if there are labels and predictions for that class. Recall is the proportion of true positive predictions out of all the positive ground truth instances, which means that if a class has false negatives (i.e. missed detections), the recall value could be 0 even if there are true positive and false positive detections for that class. 

In your case, it appears that the class you mentioned has false negatives and no true positives, which is resulting in a 0 recall value. This could explain why the computed TP and FP values differ from the labels in some cases.

To investigate this further, you could try comparing the labels and predictions for that class in the validation set to see if there are any missed true positive instances. Additionally, you can try tweaking the model hyperparameters or augmentation strategies to improve the detection performance for that class.

Hope this helps! Let us know if you have any more questions or concerns.

**Comment by muhilhamms21** [comment]
@glenn-jocher , Thanks for the reply again, but i guess theres some mistake since in the RAM class from the image that i given. They have 1 TP (which is in the hand of the person with 0.6 Confidence Score) and 1 FP and 1 FN hence the P and R should be 0.5 right? My first assumption why the ram doesnt detected as an TP is because the IoU threshold is too large so i try to lower the number but still got the same result? am i missing something?

**Comment by glenn-jocher** [comment]
@Rsphyxs, thanks for bringing this to my attention. I apologize for any confusion caused earlier. You're correct that a class with 1 TP and 1 FP should have precision and recall values of 0.5.

It's possible that other factors are affecting the TP values for this class, such as the object's size or the location of the bounding box. Additionally, it's possible that there are bugs or inaccuracies in the TP and FP calculation code that could be contributing to the mismatch between the predicted and computed values.

To investigate this further, you could try manually examining the images and labels to see if there are any mismatches or inaccuracies in the detection results. Additionally, you can try tweaking the model's hyperparameters or adjusting the IoU threshold to see if this improves the detection performance for this class.

Hope this helps! Let us know if you have any more questions or concerns.

**Comment by muhilhamms21** [comment]
Hi @glenn-jocher , Can i ask a question in the Precision Recall formulation, can u explain this line of code cause i dont really get it
![image](https://github.com/ultralytics/yolov5/assets/81289755/0f11f201-0673-4162-a71b-cebb9714f4ab)
I already ask chatGPT regarding this, is this valid?
![image](https://github.com/ultralytics/yolov5/assets/81289755/542d29b9-2e1b-4914-9a78-275a9479e621)

Thankyou in advance!

**Comment by glenn-jocher** [comment]
Hi @Rsphyxs, 

Sure, I'd be happy to explain the line of code you're seeing. The line of code you posted is a thresholding operation that sets predicted bounding boxes as true positives (TPs) or false positives (FPs) based on the Intersection over Union (IoU) overlap with the ground truth bounding boxes.

The `iou > iouv` expression checks if the IoU between the predicted and ground truth boxes is greater than a given IoU threshold `iouv`. If it is, the predicted box is considered a TP. If it isn't, the predicted box is considered a FP.

Regarding the question you asked in the chat, yes the result looks valid based on the values being printed. However, please note that the values depend on many factors such as the chosen IoU threshold and the accuracy of the model's predictions.

Hope this helps! Let me know if you have any more questions or if you need further clarification.

**Comment by muhilhamms21** [comment]
@glenn-jocher Thats really helpful thankyou so much with your answer. But i want to ask again cause i just got this problem when im running test with val.py. Because i want to test one of my class which is named RAM with 10 images with the result like this
![image](https://github.com/ultralytics/yolov5/assets/81289755/e91476ab-a668-4313-9427-8f3b98875143)
But when im trying to add 1 new image where the image label contain another class with no RAM class label in it. The value of Precision and Recall in RAM class got 0 like this
![image](https://github.com/ultralytics/yolov5/assets/81289755/bc3bb74a-2902-4810-bc51-3249d3441535)
I already try to troubleshooting it for a while and still got no idea, but so far i assume its because of the **p[ci]** and **r[ci]** calculation in which i give u the image before that makes the result 0 since the mAP still got the right value cause they do use the same value from precision and recall, do u know what cause it?

**Comment by glenn-jocher** [comment]
@Rsphyxs hello! 

I'm glad that my previous answer was helpful for you. Regarding your recent issue with the RAM class having 0 precision and recall when testing with a mixed image, it's possible that the calculation for precision and recall for the RAM class is being affected by the presence of other classes in the image.

This could be due to:

1. The presence of other classes is causing misclassification of the RAM objects in the image: If other classes in the same image are being mistakenly detected as RAM objects, then the number of false positives (FP) will increase, which affects the precision calculation and could cause it to become 0. Similarly, if true RAM objects in the image are not being detected, then the number of true positives (TP) will be zero, which affects the recall calculation and could also cause it to become 0.

2. The presence of other classes is affecting the calculation of TP and FP values: It's possible that the presence of other classes is affecting the calculation of TP and FP values for the RAM class. This could occur if the calculation of TP and FP values for each class is not being done independently of other classes in the same image. If that's the case, then the TP and FP values for the RAM class could be incorrectly calculated. 

To investigate this issue further, I recommend that you compare the ground truth labels and the predicted labels for each image, and try to identify any misclassifications or missed detections. Additionally, you can try running the test with only those images that contain RAM class objects and see how the precision and recall values change. 

If you're still having trouble, feel free to provide some additional information or share more details about your implementation. I'd be happy to assist you further.

**Comment by muhilhamms21** [comment]
Hi @glenn-jocher , Thanks again for your respond, but i have follow up question. If the Precision and Recall is really 0, should the mAP has the 0 value too? since mAP value come from the Precision Recall? Because in the image i give you before where the Precision and Recall is 0, the mAP still got a value and not 0. So i saw the Precision-Confidence Curve graph between the test where the Precision isnt 0 
![P_curve](https://github.com/ultralytics/yolov5/assets/81289755/1f0c3dd4-71f3-4243-b623-314ecce67098)

And where the Precision is 0
![P_curve](https://github.com/ultralytics/yolov5/assets/81289755/56d5f06e-8f7a-4669-87eb-fb55d316ce1a)

And it looks like the graph is pretty similiar, so i believe the Precision and Recall it got is no 0 but just printed 0 is that possible?

**Comment by glenn-jocher** [comment]
@Rsphyxs hello! 

Regarding your question about the mAP value when the precision and recall are both 0, it is possible for the mAP to have a non-zero value even if the precision and recall for a class are 0. The mAP value is a composite metric that takes into account the precision and recall values for all classes, so the contribution of a single class could be outweighed by the contributions of other classes.

Moreover, the precision-confidence graph you shared for the class where the precision is 0 looks similar to that where the precision is non-zero, which suggests that the precision and recall for the class are not actually zero but rather the values have been truncated to zero. This could be due to a problem with the way the TP and FP values are being calculated or how the precision and recall values are being printed.

If you could provide more details about the implementation, including the code that computes the TP and FP values and how you are printing the precision and recall values, it would be helpful in figuring out the problem.

Hope this helps! Let me know if you have any more questions or concerns.

**Comment by muhilhamms21** [comment]
Hi @glenn-jocher, for the code is actually just like what YOLOv5 use, because im using YOLOv7 which is based from YOLOv5. I already checked and its pretty much the same

[EDIT]
So i just got a glimpse on what happening, so i realized in this line of code 
![image](https://github.com/ultralytics/yolov5/assets/81289755/97193222-5d5e-40ca-83de-066baea39a24)
We will pick the Precision value of each class base on the index of F1 from all class max value right? So the reason of the 0 value in the precision and recall in class RAM is because when im adding a new image with different classes, it affect the F1 max value so it will pick the higher index value from each class in which the ram have 0 value in that index like in this image

Before adding new image the index that it takes from RAM precision is 141
![image](https://github.com/ultralytics/yolov5/assets/81289755/d6d85784-21db-4370-a0f0-6c1108ab1e73)
Here is the F1 Confidence graph
![F1_curve](https://github.com/ultralytics/yolov5/assets/81289755/1ffcfcc5-47a2-4c9a-93f6-ae2873fcbdca)
As we can see theres still value in RAM graph since it still takes the earliest index

But after adding new image, the index is change from 141 to 818
![image](https://github.com/ultralytics/yolov5/assets/81289755/f9181140-7d54-45a4-ab29-da5acdfb1e83)
Here is the F1 graph
![F1_curve](https://github.com/ultralytics/yolov5/assets/81289755/450d4d1c-eb7a-4e06-97e8-69b7431f08a4)
Which is why the F1 max score is shifting heavily to higher index which theres no more value in RAM.

Is there any reason why we used overall F1 score from all class and not from each classes? And is it possible to change the code so it takes the index from each class F1 max score and not from mean of all F1 scores? And if i do that, is the result still valid?

**Comment by glenn-jocher** [comment]
Hi @Rsphyxs, 

I understand that you're facing an issue with the precision and recall values for a particular class in your YOLOv7 implementation, which is based on the YOLOv5 codebase. From the information you've provided, it seems that the max F1 score is being used to pick the precision and recall values for each class. 

You speculated that the 0 value in precision and recall for the RAM class might be due to the fact that the max F1 score has shifted to a higher index after adding a new image. This occurs because the F1 scores and the max F1 score are calculated over all classes and not per class. 

Regarding your question about why the max F1 score is used to pick the precision for each class, instead of taking the max precision value for each class, the reason is that the YOLOv5 and YOLOv7 codebases compute mAP based on max F1 score. The use of F1 score to compute mAP is due to its ability to balance both precision and recall. However, this approach may not be appropriate in all cases, and you may consider using the max precision value for each class instead. 

If you decide to use max precision instead of max F1 score, the results should still be valid, but it may affect the mAP score as it is calculated based on F1 score. Nevertheless, it is important to keep in mind that changing this implementation may also have unintended effects on the model's performance.

Hope this helps! Let me know if you have any more questions or concerns.

**Comment by muhilhamms21** [comment]
Hello @glenn-jocher Thats soo much helpful thankyou, but is there a way i can get my TP and FP without the final Precision Recall value? since i really need TP and FP from each class. Can i get it from TPC and FPC?

**Comment by enesayan** [comment]
> Hello @glenn-jocher Thats soo much helpful thankyou, but is there a way i can get my TP and FP without the final Precision Recall value? since i really need TP and FP from each class. Can i get it from TPC and FPC?

Did you solve the problem? I have the same problem and there is an inconsistency between test results and confusion matrix results.

**Comment by muhilhamms21** [comment]
Sadly no, for now I'm just using mAP 0.5 as a main parameter for my project

**Comment by glenn-jocher** [comment]
@enesayan hello,

We're sorry to hear that you are facing issues with the precision and recall values for your YOLOv5 implementation. We understand that this is an important metric for your project, and we would like to help you resolve this issue.

Regarding your question, you can obtain the TP and FP values for each class by using the TPC and FPC arrays in the confusion matrix. These arrays contain the true positive count and false positive count for each class, respectively.

However, if there is an inconsistency between the test results and the confusion matrix results, this could indicate a problem with how the TP and FP values are being computed. Some common issues that could cause such discrepancies include incorrect ground truth labels, incorrect predicted labels, and inconsistent naming of classes.

To investigate this further, we recommend that you carefully review the ground truth and predicted labels for each image, and compare them with the labels in the confusion matrix. Additionally, you can try running more tests with different images to see if the same issue persists.

If you're still having trouble, please provide more information about your implementation and the specific issues you are facing so that we can assist you better.

Thank you.
