### ISSUE TITLE
why  training  map is  0.9 ,but  validation map is 0.01.

### ISSUE THREAD

**Issue by dongdong2023** [ultralytics/yolov5#12528]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

training map  is abou
![Uploading 1703052497936.png…]()
t 0.9 .  but   Validating  map  is very  small

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dongdong2023** [comment]
The validation process used half precision, resulting in all output data being NaN.
so.change  train.py  423line

model=attempt_load(f, device).float(),
half=False,

**Comment by glenn-jocher** [comment]
@dongdong2023 thanks for your report! 👋 It sounds like the issue might be caused by the validation process using half precision, leading to NaN output. Please try changing the `train.py` file at line 423 to `model = attempt_load(f, device).float(), half=False`. This should resolve the problem. Let me know if you need further assistance!
