### ISSUE TITLE
P2 small target detection layer

### ISSUE THREAD

**Issue by ZCzzzzzz** [ultralytics/yolov5#12541]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I have made improvements for YOLOv5 7.0, because the object I detect is a small target, so I deleted the P5 detection layer and added a P2 detection layer, and I found that the number of parameters has decreased, but the GFLOPs have increased, why is this? Is this situation normal?

**Comment by glenn-jocher** [comment]
@ZCzzzzzz hi there! Thanks for reaching out. The increase in GFLOPs with fewer parameters is likely due to the increased computational workload of the smaller-scale feature map. This behavior is normal when adjusting the network architecture for small target detection. For further details, you can refer to the YOLOv5 documentation at https://docs.ultralytics.com/yolov5/. Let me know if you have any other questions!
