### ISSUE TITLE
Inference/Detection result difference CLI vs. PyTorch

### ISSUE THREAD

**Issue by obreit** [ultralytics/yolov5#12575]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I've noticed that the detection results show a slight discrepancy when running the cli `detect.py` script vs. loading the model from PyTorch. I've tried to break it down to a minimal example. I'm not sure if I've done anything wrong, but nothing obvious sticks out. Maybe it's just about some rounding when the results from `detect.py` are written out (in the end, the difference is quite small after all). 

Any help is appreciated and thank you for providing yolo! Really nice tool. 

### Environment

- YOLOv5 🚀 2024-1-3 Python-3.11.7 torch-2.1.2 CPU
- MacBook Pro Apple M3 Max
- Python 3.11.7
- torch 2.1.2
- pandas 2.1.4

### Minimal Reproducible Example

Inference via pytorch loading 
```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

results_df_code = model('https://ultralytics.com/images/zidane.jpg')

results_df_code = results.pandas().xywhn[0].sort_values(by=['class', 'xcenter']).reset_index(drop=True)
```

Inference via detection script
```
git clone https://github.com/ultralytics/yolov5.git

python yolov5/detect.py --weights yolov5s.pt --source https://ultralytics.com/images/zidane.jpg --save-txt
```

Comparing the results
```python
import pandas as pd

results_df_cli = (pd.read_csv('resources/yolov5/runs/detect/exp/labels/zidane.txt', 
                              delimiter=' ',
                              header=None, 
                              names=['class', 'xcenter', 'ycenter', 'width', 'height'])
                    .sort_values(by=['class', 'xcenter']).reset_index(drop=True))

results_df_code - results_df_cli
```

The output of the difference computation looks like this. 

<img width="937" alt="Screenshot 2024-01-03 at 10 19 14" src="https://github.com/ultralytics/yolov5/assets/6474359/80143acc-4460-498f-943e-2fe085b2b141">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@obreit hello! Thanks for reaching out and for the detailed issue description. 🌟

The slight discrepancies you're observing between the CLI `detect.py` and direct PyTorch inference could be due to a few factors, such as different default settings for preprocessing, postprocessing, or even numerical precision during the operations.

To ensure consistency, please verify that all settings (like confidence thresholds, non-maximum suppression thresholds, image size, etc.) are the same in both methods. Also, ensure that the model weights loaded are identical and that the environment is consistent.

If after checking these factors the discrepancy still exists, it could be due to inherent variances in floating-point computations, which can be sensitive to operation order and hardware specifics.

If you believe there's a deeper issue, please provide a detailed comparison of the settings used in both methods, and we can look into it further. Thanks for your contributions to the YOLOv5 community, and for using the tool! 😊

For more detailed guidance, you can always refer to our documentation at https://docs.ultralytics.com/yolov5/.

**Comment by obreit** [comment]
Thanks for the info @glenn-jocher!

> The slight discrepancies you're observing between the CLI `detect.py` and direct PyTorch inference could be due to a few factors, such as different default settings for preprocessing, postprocessing, or even numerical precision during the operations.

I was under the impression that all settings would be the same for how the methods are called in the minimal reproducible example (I am basically just calling them both without specifying any setting explicitly and pointing to the same standard yolov5 model). But yeah, I guess there could be some small differences in those settings. 

> To ensure consistency, please verify that all settings [...]
If you believe there's a deeper issue, please provide a detailed comparison of the settings used in both methods, and we can look into it further.

Unfortunately, I don't have time to investigate this further at the moment. For my use-case the discrepancy doesn't bother for now. So feel free to close the issue

**Comment by glenn-jocher** [comment]
@obreit, I understand that time constraints can make it challenging to dive deeper into such discrepancies. It's good to hear that the differences are not impacting your use case significantly.

If you or anyone else in the community encounters a similar issue and has the bandwidth to investigate further, we're always here to assist. In the meantime, I'll mark this issue as resolved, but feel free to reopen it or create a new one if anything else comes up.

Thank you for using YOLOv5, and we appreciate your contributions to the community! Happy detecting! 😄🚀

**Comment by obreit** [comment]
closing it, because it's not bothering much for my use case :) as @glenn-jocher mentioned, if someone has the capacity to investigate this further, feel free to pick it up or open a new one

**Comment by glenn-jocher** [comment]
Understood, @obreit! The issue will be closed as per your decision. Should you or anyone else wish to revisit this in the future, the door is always open to further investigation or discussion. Best of luck with your work, and thank you once again for engaging with the YOLOv5 community! 😊👍
