### ISSUE TITLE
model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse) TypeError: attempt_load() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by ly1035327995** [ultralytics/yolov5#12596]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
TypeError: attempt_load() got an unexpected keyword argument 'device'

### Additional

model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
TypeError: attempt_load() got an unexpected keyword argument 'device'

**Comment by glenn-jocher** [comment]
@ly1035327995 hello! It looks like you're encountering an issue with an unexpected keyword argument 'device' in the `attempt_load` function. This could be due to a mismatch between the function definition and the way you're calling it.

To resolve this, please ensure that you're using the latest version of the YOLOv5 repository, as the function signatures may have been updated. If you've recently updated the repository, make sure to restart your runtime if you're using a Jupyter notebook or similar environment to ensure the changes are applied.

If the issue persists, double-check the `attempt_load` function definition in the codebase to confirm if the 'device' argument is indeed part of the function's signature. If it's not, you should remove it from your function call.

For further guidance, you can refer to our documentation at https://docs.ultralytics.com/yolov5/ which provides detailed information on how to use the YOLOv5 models and functions.

If you continue to experience issues, please provide more context or code snippets, and we'll be happy to help you further. 😊
