### ISSUE TITLE
Why training yolov5 use all gpus defaultly ?

### ISSUE THREAD

**Issue by myalos** [ultralytics/yolov5#12602]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Thanks for sharing this code. When I train custom dataset, i find that this training procedure use memory of two gpu not one. The sum of using memory is less than the max memory of one gpu. Why this happened? The default parameter of gpu is '' which is transformed to cuda:0 in the code. Thanks in advance!

**Comment by glenn-jocher** [comment]
@myalos hello! Thanks for reaching out with your question. 😊

YOLOv5 is designed to utilize all available GPUs by default to speed up the training process. This is a common practice in deep learning to parallelize computations and reduce training time. When multiple GPUs are available, PyTorch will automatically distribute the workload across them unless specified otherwise.

If you prefer to use only one GPU, you can set the `--device` flag to the specific GPU you want to use, like `--device 0` for the first GPU. This will restrict the training to that single GPU.

For more details on how to control GPU usage and other training options, please refer to our documentation.

Happy training, and if you have any more questions, feel free to ask! 🚀

**Comment by myalos** [comment]
Thanks for reply! The function of select_device sets the CUDA_VISIBLE_DEVICES, and this environment variable decides whether the model is DataParallel or not.

**Comment by glenn-jocher** [comment]
@myalos you're welcome! That's correct, the `select_device` function in YOLOv5 will set the `CUDA_VISIBLE_DEVICES` environment variable, which controls which GPUs are visible to PyTorch. When multiple GPUs are visible, PyTorch can automatically use `DataParallel` to distribute the workload across the available devices.

If you want to use a specific GPU or set of GPUs, you can set the `CUDA_VISIBLE_DEVICES` environment variable before running your training script or use the `--device` flag as mentioned earlier.

Keep up the great work, and don't hesitate to reach out if you have further questions! 🌟
