### ISSUE TITLE
yolov5s fps

### ISSUE THREAD

**Issue by brfbrfbrf** [ultralytics/yolov5#12615]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I classified the kittii dataset into only three categories and tested it with yolov5s, calculated the fps with val.py [1000/ (inf+pre+NMS)] and found that the fps was as high as 220, but when I trained and tested with BDD100k (10 categories) I found that the fps was only 25. I want to ask is this situation normal? Do you have any guesses as to the cause of this?

**Comment by glenn-jocher** [comment]
@brfbrfbrf hello! Thanks for reaching out. The difference in FPS between the KITTI dataset and BDD100K could be due to several factors:

1. **Dataset Complexity**: BDD100K is a more complex and diverse dataset than KITTI, which could lead to longer inference times.
2. **Number of Categories**: More categories can increase the computational load during inference, especially if there are more detections per image to process.
3. **Image Resolution**: If the BDD100K images are of higher resolution than those in KITTI, it would naturally lead to lower FPS due to the increased amount of data to process.
4. **Hardware Utilization**: Ensure that your hardware resources are being fully utilized during inference. Any bottlenecks could affect FPS.
5. **Software Configuration**: Check if there are any differences in the configuration or the version of the software used for both datasets.

It's normal to see variations in FPS across different datasets due to the reasons above. For a more detailed analysis, you might want to profile your model's inference step by step to pinpoint where the differences lie.

For further guidance on profiling and optimization, you can refer to our documentation. Keep up the great work with YOLOv5, and if you have more questions, feel free to ask! 😊🚀
