### ISSUE TITLE
translucent line for visibility

### ISSUE THREAD

**Issue by mucunwuxian** [ultralytics/yolov5#12612]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

To add an argument to make the bounding box line translucent to improve visibility of results.

### Use case

When there are many bounding boxes etc...

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mucunwuxian hello! Thank you for your suggestion and your willingness to contribute to the YOLOv5 project with a PR. 😊

Adding an argument for translucent bounding box lines could indeed be useful in scenarios with dense detections. If you're ready to work on this, please ensure that the feature is optional and controlled by a command-line argument so that users can toggle the translucency on or off as needed.

Looking forward to your pull request, and if you have any questions or need guidance, feel free to ask. Your contributions help make YOLOv5 better for everyone! 🚀

For guidelines on contributing, please make sure to check our documentation. Happy coding!
