### ISSUE TITLE
About inference time when executing detect.py --source vid.mp4

### ISSUE THREAD

**Issue by Nangsaga** [ultralytics/yolov5#12630]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello everyone,

I did transfer-learning using 4 pre-trained weights of YOLOv5s.pt, YOLOv5m.pt, YOLOv5l.pt, and YOLOv5x.pt, and custom dataset to train 4 corresponding models having weights of best_s.pt (13.8MB, ), best_m.pt (40.3MB), best_l.pt (88.7MB), and best_x.pt (165.2MB). I then investigated the inference time of each trained model using 
`detect.py --source vid.wmv --weight best_s.pt --save-txt --save-conf` 
`detect.py --source vid.wmv --weight best_m.pt --save-txt --save-conf` 
`detect.py --source vid.wmv --weight best_l.pt --save-txt --save-conf` 
`detect.py --source vid.wmv --weight best_x.pt --save-txt --save-conf` 

The inferences were made with a laptop PC (Intel® Core™ i7-11800H CPU, 16GB RAM, NVIDIA GeForce RTX 3070 with 8GB VRAM, Windows 10). I got the corresponding results of inference times as below 

`video 1/1 (2465/2466) ...\vid.wmv: 384x640 1 obj1, 1 obj2, 1 obj3, 1 obj4, 1 obj5, 1 obj6, 18.0ms
Speed: 1.4ms pre-process, 18.0ms inference, 1.4ms NMS per image at shape (1, 3, 640, 640)`

`video 1/1 (2465/2466) ...\vid.wmv: 384x640 1 obj1, 1 obj2, 1 obj3, 1 obj4, 1 obj5, 1 obj6, 18.0ms
Speed: 0.8ms pre-process, 17.8ms inference, 1.1ms NMS per image at shape (1, 3, 640, 640)`

`video 1/1 (2465/2466) ...\vid.wmv: 384x640 1 obj1, 1 obj2, 1 obj3, 1 obj4, 1 obj5, 1 obj6,  20.0ms
Speed: 0.6ms pre-process, 19.7ms inference, 1.1ms NMS per image at shape (1, 3, 640, 640)`

`video 1/1 (2465/2466) ...\vid.wmv: 384x640 1 obj1, 1 obj2, 1 obj3, 1 obj4, 1 obj5, 1 obj6,  21.0ms
Speed: 0.6ms pre-process, 20.6ms inference, 1.0ms NMS per image at shape (1, 3, 640, 640)`

My questions are:
1) What are pre-process, inference, and NMS? "inference" should be used for a comparison of inference time between models or sum of pre-process+inference+NMS?
2) Normally, large difference between inference time of small and extra-large model are obtained. In my case, only 2.6ms. Is there something wrong?

Thank you guys in advance.

**Comment by glenn-jocher** [comment]
@Nangsaga hello!

1) The terms "pre-process," "inference," and "NMS" refer to different stages of the detection pipeline. "Pre-process" is the time taken to prepare the image for the model (resizing, normalization, etc.), "inference" is the time the model takes to process the image and output predictions, and "NMS" stands for Non-Maximum Suppression, which is the time taken to filter overlapping bounding boxes. For comparing model speeds, you should look at the "inference" time, as it directly relates to the model's processing speed.

2) The small difference in inference time between the models could be due to several factors, including GPU utilization, CPU-GPU data transfer overhead, or other system bottlenecks. The larger models are expected to take longer for inference, but if the GPU is not fully utilized, the differences might not be as pronounced. It's also worth noting that the inference time can vary slightly from run to run due to system load and other factors.

If you have further questions or need assistance, feel free to reach out. Happy coding! 😊

**Comment by Nangsaga** [comment]
Thank Glenn for kind explanation. I got it.

**Comment by glenn-jocher** [comment]
@Nangsaga you're welcome! I'm glad I could help. If you have any more questions or need further assistance down the line, don't hesitate to ask. Good luck with your work, and happy detecting! 😄🚀
