### ISSUE TITLE
Export TensorRT engine - Device memory is insufficient to use tactic. - NX2 TX Jetson Platform. 

### ISSUE THREAD

**Issue by nicorl** [ultralytics/yolov5#12637]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have trained a PyTorch model (.pb) and I am looking to optimize it to consume less memory. The attempts to export it to TensorRT are causing issues because the device has limited available memory, and I'm unsure how to achieve a proper export.

Trained through: 
```
python train.py --data data/config_training.yaml --weights yolov5s.pt --img 640 --epochs 300 --device 0 --batch -1 --patience 15
```
Loading model on memory:
Virtual environment with: Python 3.6.9, torch-1.8.0
→ The pytorch model (best.pt) requires approximately ~1.2GB of memory
→ The model's performance is good ✓ ([best.pt](https://drive.google.com/file/d/1WZ-Yzz7SYqqLPvCGfvyzKLdCieDfA3YO/view?usp=drive_link))

Exporting to TensorRT over Jetson TX2 NX with Python 3.6.9, torch-1.8.0, TensorRT 8.0.1.6, ONNX 1.11.0
Export command: 

```
yolov5 export --weights best.pt --include [engine] --device 0 --imgsz [800,608] --data mydata.yaml --half --workspace 1
```

Errors & warning:
```
WARNING: ⚠️ Python 3.7.0 is required by YOLOv5, but Python 3.6.9 is currently installed
```

```
[TensorRT] ERROR: Tactic Device request: 277MB Available: 264MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 277 detected for tactic 5.
[TensorRT] ERROR: Tactic Device request: 356MB Available: 267MB. Device memory is insufficient to use tactic.
[TensorRT] WARNING: Skipping tactic 3 due to oom error on requested size of 356 detected for tactic 4.
```
Full log [here](https://drive.google.com/drive/u/0/folders/19G12tSoRmkNC03joFAosQLxUK5hnmLY4)

The model.engine file is generated, but when i load it, the performance is not good:
![badResults](https://github.com/ultralytics/yolov5/assets/8526514/c0c3ea56-9e92-4e85-b448-fdb5ebbf7544)

On my PC with a larger amount of memory and Python v.3.10, the export process does not yield any warnings and works well. Because I can’t increase the memory of my TX2 NX, I would like to understand how relevant the warnings are and what would be the best way to avoid them. I believe upgrading to Python 3.7 is one option, but I would like to know if there are possibilities to make it works on 3.6.9
![goodResults](https://github.com/ultralytics/yolov5/assets/8526514/98eb72c5-e4d6-4d8f-98d1-2a8f497d9475)

I've also put a [link in the Nvidia forums](https://forums.developer.nvidia.com/t/exporting-a-yolov5s-best-pb-model-to-engine-format-tensorrt/279123), but I think it's more appropriate here than there.

### Environment

**TensorRT Version**: 8.0.1.6
**GPU Type**: NVIDIA® Jetson™ TX2 NX - 4 Core ARM A57 Complex and 2 core NVIDIA Denver2 64-bit CPU - 4GB LPDDR4 - NVIDIA Tegra X2, 3832MiB
**Nvidia Driver Version**: nvidia-smi not installed
**CUDA Version**: cuda_10.2_r440.TC440_70.29663091_0
**Operating System + Version**: Linux aaeon-desktop 4.9.253-tegra  SMP PREEMPT Mon Jul 26 12:19:28 PDT 2021 aarch64 GNU/Linux
**Python Version**: 3.6.9
**PyTorch Version**: 1.8.0
**ONNX Version**: 1.11.0
**yolov5 Version**: 6.2.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nicorl hello! Thanks for the detailed issue report. It seems like you're encountering out-of-memory (OOM) errors when exporting your model to TensorRT on the Jetson TX2 NX platform. Here are a few suggestions that might help:

1. **Reduce Workspace Size**: Try reducing the workspace size during export. Although you've set it to 1GB, you might need to go lower due to the limited memory on the TX2 NX.

2. **Optimize Model**: If possible, optimize your model further before export. This could involve pruning or quantization to reduce the model size and memory requirements.

3. **Python Version**: While upgrading to Python 3.7 might not directly solve the OOM issue, it's recommended to use the Python version that YOLOv5 is tested on for best compatibility.

4. **Batch Size**: If you're using a batch size greater than 1 during inference, try reducing it to 1 to save memory.

5. **Close Other Processes**: Ensure that no other memory-intensive processes are running on the device when exporting the model.

6. **TensorRT Version**: Check if there's a more memory-efficient version of TensorRT available for your platform.

7. **Model Precision**: You're using the `--half` flag which uses FP16 precision. Make sure that your device supports FP16 operations efficiently.

If these suggestions don't resolve the issue, consider posting the full error log and your export command in the issue for further assistance. Remember to check the Ultralytics Docs for more information on exporting models and troubleshooting.

Keep in mind that the Jetson TX2 NX has limited memory, and some models may simply be too large to run efficiently on this platform. You might need to consider a more powerful device if memory constraints continue to be an issue.

Thanks for contributing to the YOLOv5 community, and we appreciate your efforts in making the model work on edge devices! 🚀

**Comment by nicorl** [comment]
Hi again,
I've just tried to install all from the source
- Python 3.7.12 
- Torch 1.8.0
- Torchvision 0.9.0 
- CMake 3.21.4 
- TensorRT 8.2 

But ultimately, generating the TensorRT 8.2 wheel has posed issues for which I cannot find any solution. Below, I provide all the executed commands as information for anyone reading this message. It's worth noting that the next steps will involve trying to use Python version 3.8 and the rest of the software in appropriate versions. As I make significant progress, I will leave further comments. 

[Nvidia forum link](https://forums.developer.nvidia.com/t/exporting-a-yolov5s-best-pb-model-to-engine-format-tensorrt/279123/8) where someone is helping to solve this

**Comment by glenn-jocher** [comment]
Hello again @nicorl,

It sounds like you're making progress, but still encountering some challenges with the TensorRT wheel installation. Here are a few general tips that might help:

1. **Dependencies**: Ensure all dependencies are correctly installed and compatible with each other. Dependency conflicts can often lead to installation issues.

2. **Installation Logs**: Review the installation logs carefully for any specific error messages that could point to the root cause of the issue.

3. **Virtual Environment**: Consider using a virtual environment to avoid conflicts with system-wide packages and to have a clean slate for installation.

4. **Community and Forums**: Continue to engage with the community on the Nvidia forums, as platform-specific issues can often be resolved with the help of users who have faced similar challenges.

5. **Documentation**: Refer to the official TensorRT documentation for guidance on building from source and troubleshooting installation issues.

6. **Alternative Approaches**: If building from source continues to be problematic, consider looking for pre-built wheels that are compatible with your system, if available.

7. **System Resources**: Ensure your system has enough resources (e.g., memory, disk space) to complete the build process, as this can sometimes cause unexpected failures.

Remember to take it one step at a time and isolate each issue as you encounter it. Building complex software from source can be challenging, but with persistence, you'll likely find a solution. Keep up the good work, and thank you for keeping the community updated on your progress! 🛠️

Best of luck with the next steps, and we're looking forward to hearing about your successful export with the updated Python version and software stack.

**Comment by cile98** [comment]
Hey @nicorl, were you able to figure something out?

**Comment by nicorl** [comment]
Hi! Definitely not. All I discovered was that I needed to run TensorRT on the same platform and not on the machine where I did the training. But even then, the results were never good. I abandoned the idea of optimizing models and now I work with Orin Nano. I simply solved the problem by using better hardware.

**Comment by pderrenger** [comment]
Hi there! 👋 Glad to hear you found success with the Orin Nano hardware upgrade. For others facing similar TensorRT memory constraints on Jetson TX2 NX platforms, we recommend:

1. Trying the latest YOLOv5 v6.1 with improved TensorRT support from our [YOLOv5 v6.1 release blog post](https://www.ultralytics.com/blog/yolov5-just-got-stronger-in-v6-1)  
2. Following our optimized [OpenVINO export guide](https://www.ultralytics.com/blog/export-and-optimize-a-yolov8-model-for-inference-on-openvino) for Intel platforms as an alternative

Would you like any specific guidance for optimizing models on your new Orin Nano setup?
