### ISSUE TITLE
png format training error reporting

### ISSUE THREAD

**Issue by wq247726404** [ultralytics/yolov5#12663]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

WARNING  data\images2\999.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: 'data\\images2\\999.jpg'，I use PNG format why the error suffix is JPG format, how to modify it？

**Comment by wq247726404** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> WARNING data\images2\999.jpg: ignoring corrupt image/label: [Errno 2] No such file or directory: 'data\images2\999.jpg'，I use PNG format why the error suffix is JPG format, how to modify it？
> 
> ### Additional
The above problem has been solved, but there are new problems，WARNING  data\images2\0.png: corrupt JPEG restored and saved

**Comment by glenn-jocher** [comment]
@wq247726404 hello! It's great to hear that you've resolved the initial issue with the file format. Regarding the new warning about a "corrupt JPEG" for a PNG file, this could be due to a misinterpretation of the file format by the image loader. 

Make sure that your dataset does not contain any actual JPEG files mislabeled as PNGs. Also, verify that the image files are not corrupted and can be opened normally with an image viewer.

If the issue persists, you might want to check your dataset's integrity and ensure that the image paths and extensions are correctly specified in your label files. For more detailed guidance on preparing your data, please refer to the Ultralytics Docs.

If you continue to encounter problems, please provide more context or error logs, and we'll be happy to help you further. Keep up the good work! 😊👍
