### ISSUE TITLE
Cant understand how does yolov5 work.

### ISSUE THREAD

**Issue by Aflexg** [ultralytics/yolov5#12677]
Hello.I dont understand some basic principles of the yolov5 work and need help.Could you, please, answer my questions?

As far as i am concerned, convolutional neural network always has fully connected layer on its exit to predict the class of the object, but i dont see it on this picture.It seems yolov5 output consists of only 3 conv layers, so i cant get how does it predict the class.Could you explain me, please, how does yolov5 predict the class without fully connected layer ?Maybe this scheme  is not full and doesnt show the fully connected layer ?

What exactly does the BottleNeckCSP layer ? Is it just better version of the convolution layer ?How do they (BottleNeckCSP and conv layers) interract between each other and why do yolov5 needs ordinary convolution layer if c3 is just better ?

![image](https://github.com/ultralytics/yolov5/assets/153363231/b7875851-ea19-42c5-a01a-a8a9666a3265)

I copied this diagram from [here](https://blog.csdn.net/Q1u1NG/article/details/107511465), it is written in Chinese.

Copyright statement: This article is the original article of the blogger and follows the CC 4.0 BY-SA copyright agreement. Please attach the original source link and this statement for reprinting.
Link to this article: https://blog.csdn.net/Q1u1NG/article/details/107511465

**Comment by glenn-jocher** [comment]
@Aflexg hello! I'm glad you're interested in understanding how YOLOv5 works. Let's clarify your questions:

1. **Class Prediction Without Fully Connected Layers**: YOLOv5, like other YOLO models, uses a different approach compared to traditional CNNs. Instead of fully connected layers, it uses convolutional layers to predict bounding boxes and class probabilities directly from feature maps. This is achieved through 1x1 convolutions at the end of the network that output a 3D tensor containing the bounding box coordinates, objectness scores, and class predictions for each grid cell.

2. **BottleneckCSP Layer**: The BottleneckCSP is a type of layer that improves the learning capability of the network by combining Cross Stage Partial (CSP) connections with bottleneck structures. It helps in reducing the computational cost while maintaining or improving the learning capacity. The interaction between BottleneckCSP and regular convolutional layers is that the BottleneckCSP layers are used to enhance feature extraction and learning efficiency, while the conv layers perform the standard convolution operations. YOLOv5 uses both to balance performance and efficiency.

The diagram you've referenced may not fully represent the architecture or the final layers responsible for predictions. For a more detailed and accurate representation of YOLOv5's architecture, I recommend checking out the official documentation at our Ultralytics Docs page.

I hope this helps clarify your questions! If you have more, feel free to ask. 😊

**Comment by Aflexg** [comment]
Thanks a lot for your reply.It seems i got it.Very good and simple explanation.

**Comment by glenn-jocher** [comment]
You're welcome, @Aflexg! I'm thrilled to hear that the explanation was helpful. If you have any more questions in the future or need further clarification, don't hesitate to reach out. Happy coding and best of luck with your YOLOv5 projects! 😄🚀
