### ISSUE TITLE
HTTPS video stream detection encountered stuck frames

### ISSUE THREAD

**Issue by NGIWS830** [ultralytics/yolov5#12709]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The HTTPS video stream can be accessed on the public network. I used YOLOv5 to detect the HTTPS video stream, and then the saved detection video encountered stuck frames and quickly loaded many frames (please refer to the time in the bottom right corner of the attached video for details). I couldn't find out the reason, and I'm not sure if it's caused by the HTTPS protocol.

### Additional

https://github.com/ultralytics/yolov5/assets/93505227/3f812c4b-2a04-492e-941f-467d08553c49

**Comment by glenn-jocher** [comment]
@NGIWS719 hello! Thanks for reaching out. It seems like you're experiencing issues with frame consistency when processing an HTTPS video stream. This could be due to network latency or buffering issues rather than the HTTPS protocol itself.

To address this, you might want to ensure that your network connection is stable and consider reducing the video resolution or frame rate to alleviate the load on the network. Additionally, check if the issue persists with different video streams to rule out source-specific problems.

If the problem continues, please provide more details such as the command you're using to run the detection and any relevant console output. This will help us understand the issue better and assist you more effectively.

For further guidance, you can refer to our documentation at https://docs.ultralytics.com/yolov5/.

Keep us posted on your progress! 🚀

**Comment by NGIWS830** [comment]
@glenn-jocher I feel that it's also due to network issues. Next time, I will go to the internal network for testing. Thank you!

**Comment by glenn-jocher** [comment]
@NGIWS719 You're welcome! Testing on an internal network sounds like a good plan to isolate the issue. If you encounter any further challenges or have questions, don't hesitate to reach out. Best of luck with your testing, and I hope it goes smoothly! 😊👍
