### ISSUE TITLE
Getting YOLOv8 detection output as sigmoid

### ISSUE THREAD

**Issue by Krisequ** [ultralytics/yolov5#12714]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hey,

I am working on a custom training approach for detectional neural networks (using YOLOv8). 
Please correct me if I am wrong, but typically, after finding anchors, the task changes to classification and linear regression of the bounding box size. These typically are done with sigmoid functions.
Using basic Ultralytics functions like predict/train, the framework provides BBOX in pixels, which is perfectly understandable. I was trying to access the values as sigmoid values (0 to 1), but I seem to be unable to find it at any stage of the processing. 

Where can I find a function that translates sigmoids to BBOX coordinates (so I could reverse it at a later stage), or is there a way to access the sigmoid outputs from the network, at best also during the training?

Best regards

**Comment by Krisequ** [comment]
Only now I found this thread: https://github.com/ultralytics/ultralytics/issues/6982 and realized that there's different approach for detection in yolov8 than I expected.

**Comment by glenn-jocher** [comment]
@Krisequ hello!

You're correct that YOLOv8, like its predecessors, uses a different approach for bounding box prediction. The network outputs are typically transformed from raw model outputs to bounding box coordinates through a series of operations, including the application of the sigmoid function to certain outputs to constrain them between 0 and 1.

If you're looking to work with the raw sigmoid outputs, you would need to modify the inference code to intercept these values before they are converted to bounding box coordinates. This would involve diving into the model's forward pass and extracting the relevant tensors.

For reversing the process (i.e., converting bounding box coordinates back to the network's raw outputs), you would need to understand the exact transformations applied and invert them. This can be quite complex due to the nature of the transformations, which include scaling and translating based on anchor boxes.

For more detailed guidance on the model architecture and output transformations, please refer to our documentation at https://docs.ultralytics.com/yolov5/.
