### ISSUE TITLE
imgsz calculation

### ISSUE THREAD

**Issue by KnightInsight** [ultralytics/yolov5#12715]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I would like to ask about the imgsz calculation. For example, I have an image(Dimension=Width 1143pixelsx Height 1499pixels). Based on my calculation, imgsz default as 640, so 1499 converted to 640 and 1143 is 488. Thus, the image shape should be 488x640. However, the input size torch.Size([1,3,640,512]) when I run TensorRT engine model. May I know why and how to calculate correctly? Thanks

**Comment by glenn-jocher** [comment]
@KnightInsight hello! Thanks for reaching out with your question.

The `imgsz` parameter in YOLOv5 is used to resize your images to a consistent size for inference. When you specify an `imgsz` of 640, YOLOv5 will resize the image to have its longest dimension be 640 pixels while maintaining the original aspect ratio. The other dimension is scaled accordingly, and then the image is padded to the nearest stride-multiple rectangle.

In your case, the original image is 1143x1499. When resizing to a longest dimension of 640, the height becomes 640 and the width is scaled down to maintain the aspect ratio, which would be less than 640. However, because YOLOv5 also pads the image to ensure the dimensions are multiples of the model's stride (typically 32), you end up with an input size of 640x512, which is the closest stride-multiple rectangle that fits the aspect ratio of your original image.

For more detailed information on how images are resized and padded in YOLOv5, you can refer to our documentation at https://docs.ultralytics.com/yolov5/.

I hope this clarifies the imgsz calculation for you! If you have any more questions, feel free to ask. 😊
