### ISSUE TITLE
training selectively targeting objects on labeled data 

### ISSUE THREAD

**Issue by timingisnow** [ultralytics/yolov5#12710]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

1. I have label data below of data.yaml
nc: 3 
names: 
  0: apple
  1: banana
  2: carrot

2. After that I add another label like below
nc: 4
names: 
  0: apple
  1: banana
  2: carrot
  3: kiwi
3. and I want train except 1:banana
nc: 3
names: 
  0: apple
  # 1: banana
  2: carrot
  3: kiwi

And I trained with 
"python train.py --weights yolov5s.pt --hyp model.yaml --data data.yaml --epochs 100 --batch 64 --imgsz 640 --name v5s_0205

but got a error message 
"AssertionError: Label class 3 exceeds nc=3 in bucket_dataset.yaml. Possible class labels are 0-2"

I already searched about the error and I knew that if nc=3, class index has to be lower than 3(nc=3)

so, for solving the problem, do I have to change label like below?
If I have to do that, label data have to be changed.. 
names: 
  0: apple
  1: carrot
  2: kiwi

please let me know the efficient method

thanks

### Additional

nope

**Comment by glenn-jocher** [comment]
@timingisnow hello! It looks like you're trying to train a model on a subset of your classes. If you want to exclude 'banana' from your training, you indeed need to adjust both your `data.yaml` and your dataset labels so that the class indices are contiguous and match the `nc` value in your `data.yaml`.

In your case, you should update your `data.yaml` to:
```yaml
nc: 3
names: 
  0: apple
  1: carrot
  2: kiwi
```

And then you'll need to update your dataset so that all 'kiwi' instances are labeled as class 2 instead of class 3. There's no built-in method to exclude a class during training; you have to preprocess your labels to match the classes you want to train on.

Remember to ensure that your annotations reflect this change. All annotations for 'kiwi' should now be labeled as class 2, and any annotations for 'banana' should be removed.

For more details on how to prepare your data, please refer to our documentation. Good luck with your training! 🚀

**Comment by timingisnow** [comment]
@glenn-jocher Thank you for your reply
I was not sure if there is the efficient method to train selective target, but now I clear on that.

**Comment by glenn-jocher** [comment]
@timingisnow you're welcome! I'm glad I could help clarify things for you. If you have any more questions or need further assistance as you adjust your dataset and proceed with training, don't hesitate to reach out. Happy training, and best of luck with your YOLOv5 model! 🌟
