### ISSUE TITLE
OnnxSlim support

### ISSUE THREAD

**Issue by inisis** [ultralytics/yolov5#12747]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Hi, we have developed a tool called [onnxslim](https://github.com/WeLoveAI/OnnxSlim), which can help slim exported onnx model, and it's pure python, and it works well on yolo, should we intergrate it into awesome yolov5.

### Use case

when export to onnx, we can use onnxslim to slim our exported model

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by inisis** [comment]
We can try this
```
pip install onnxslim
onnxslim yolov5s.onnx slim.onnx
```
![image](https://github.com/ultralytics/yolov5/assets/46103969/715fd33e-72d3-4c3c-a613-be793a16063d)

**Comment by glenn-jocher** [comment]
@inisis hello! Thank you for your interest in contributing to the YOLOv5 project and for suggesting the integration of OnnxSlim. It's great to hear that you've developed a tool that can potentially enhance the YOLOv5 ecosystem.

Before we consider integrating a new tool, we typically review its impact on performance, compatibility, and maintenance. Since you're willing to help by submitting a PR, I would recommend the following steps:

1. Ensure that the tool does not introduce any breaking changes to the current export pipeline.
2. Thoroughly test the slimmed ONNX models to confirm that there is no degradation in inference accuracy or speed.
3. Document the changes and update the relevant sections in the Ultralytics Docs to guide users on how to use OnnxSlim with YOLOv5.

Once you have tested the tool and are ready, please submit a PR with a detailed explanation of the benefits, any potential drawbacks, and comprehensive testing results. Our team will review it and provide feedback.

We appreciate your initiative and look forward to your contribution! 😊 Remember to keep the PR concise and focused on the proposed feature for easier review and potential integration.
