### ISSUE TITLE
 common.py cannot import export_formats from export.py

### ISSUE THREAD

**Issue by jacobbreen25** [ultralytics/yolov5#12758]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have been trying to create a ros2 node for yolov5. Using yolov5.7, I have fully created the driver but in running, I get the following error:

```ImportError: cannot import name 'export_formats' from 'export' (/home/jbreen/.local/lib/python3.10/site-packages/export/__init__.py)```

After uninstalling the export library, I got an error saying there is no library named export (I do not want to have to reinstall export so I will not put the error)

### Environment

YOLO: yolov5.7
ROS2: Humble

### Minimal Reproducible Example

python3 detect.py

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jacobbreen25 hello! Thank you for reporting this issue. It seems like there might be a conflict with another package named `export` installed in your environment. YOLOv5's `export.py` should not be installed as a top-level package, so it's possible that Python is trying to import `export_formats` from the wrong `export` package.

To resolve this, please ensure that you are running your script from the root directory of the cloned YOLOv5 repository, and not from the site-packages directory. This way, Python should correctly reference the local `export.py` file rather than an installed package.

If you're still encountering issues, please refer to our documentation for further guidance on setting up your environment and running detection. If the problem persists, feel free to open a new issue with updated details. Thank you for your contribution to the YOLOv5 community! 🚀

**Comment by jacobbreen25** [comment]
Closing because I found the issue. yolov5 library did not get added to python path so adding it fixed the issue immediately

**Comment by glenn-jocher** [comment]
@jacobbreen25 Great to hear that you've resolved the issue! Adding the YOLOv5 library to the Python path is indeed a crucial step. If you have any more questions or run into any other issues, don't hesitate to reach out. Happy coding and best of luck with your ROS2 node development! 🎉

**Comment by sun-rabbit** [comment]
> Closing because I found the issue. yolov5 library did not get added to python path so adding it fixed the issue immediately

Hello,

Could you please let me know how to add the YOLOv5 library to the Python path? Thank you.

**Comment by glenn-jocher** [comment]
Hello @sun-rabbit,

I'm glad to hear you resolved the issue! To add the YOLOv5 library to your Python path, you can follow these steps:

1. **Locate the YOLOv5 Directory**: Ensure you know the path to your cloned YOLOv5 repository. For example, if you cloned it to your home directory, the path might be `/home/your_username/yolov5`.

2. **Modify the Python Path**: You can add the YOLOv5 directory to your Python path in your script or environment. Here are a couple of ways to do this:

   - **Temporarily in a Script**:
     Add the following lines at the beginning of your script:
     ```python
     import sys
     sys.path.append('/path/to/yolov5')
     ```

   - **Permanently in Your Environment**:
     You can add the YOLOv5 directory to your `PYTHONPATH` environment variable. For example, in a Unix-like system, you can add the following line to your `.bashrc` or `.bash_profile`:
     ```sh
     export PYTHONPATH="$PYTHONPATH:/path/to/yolov5"
     ```
     Then, reload your shell configuration:
     ```sh
     source ~/.bashrc
     ```

By following these steps, Python should be able to locate the YOLOv5 library correctly. If you have any further questions or run into any other issues, feel free to ask. The YOLOv5 community and the Ultralytics team are here to help! 😊
