### ISSUE TITLE
Yolov5 classifier ,some training images are being centre cropped

### ISSUE THREAD

**Issue by humairaneha** [ultralytics/yolov5#12756]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I don't want this behaviour. I have resized my image to 224*224,but during training the images are being cropped ,so most information of the images are being lost. what to do?

**Comment by glenn-jocher** [comment]
@humairaneha hello! Thanks for reaching out. If you're observing that your images are being center-cropped during training, it's likely due to the data augmentation settings in the YOLOv5 data pipeline.

To prevent center-cropping, you can adjust the augmentation settings in your dataset's YAML file. Specifically, you'll want to look at the `augment` section and modify the parameters related to cropping, such as `mosaic`, `mixup`, and `random crop` settings. Set these to `false` or adjust their probabilities to `0` to disable them.

For more detailed guidance on how to configure your data augmentations, please refer to the documentation at https://docs.ultralytics.com/yolov5/.

Remember, any changes to the augmentation settings can affect the model's ability to generalize, so it's a good idea to monitor your model's performance on a validation set after making adjustments.

Happy training! 😊
