### ISSUE TITLE
How to load models without pip install?

### ISSUE THREAD

**Issue by useruser2023** [ultralytics/yolov5#12768]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I need to execute this model on a different device as a pytorch model where I can't use pip install and should use the source files only. I discovered an approach to run the model, but it's throwing an error `ModuleNotFoundError: No module named 'ultralytics.yolo'`

```
from models.common import DetectMultiBackend
model = DetectMultiBackend("yolov5nu.pt")
```

I've pinpointed the issue, and it occurs at this file.

https://github.com/ultralytics/yolov5/blob/574331f984c0aa9c26c4ea78dac90133cfe6b2d0/models/experimental.py#L97-L97

I also attempted to execute the code manually, but encountered similar outcomes.

```
from models.experimental import attempt_download
from models.yolo import Detect, Model
import torch

ckpt = torch.load("yolov5nu.pt", map_location="cpu")
```

**Comment by glenn-jocher** [comment]
@useruser2023 hello! 😊

It looks like you're trying to load YOLOv5 models directly from the source without using pip. To do this, you'll need to ensure that your Python environment recognizes the YOLOv5 source directory as a module. Here's a quick guide:

1. Clone the YOLOv5 repository to your local machine or copy the necessary files to your working environment.
2. Navigate to the directory containing the YOLOv5 source code in your terminal or command prompt.
3. Before running your script, set the Python path environment variable to include the YOLOv5 directory. This can be done as follows:
   - On Linux/Mac: `export PYTHONPATH=$PYTHONPATH:$(pwd)`
   - On Windows: `set PYTHONPATH=%PYTHONPATH%;%cd%`

This should allow Python to recognize `ultralytics.yolo` and other modules correctly when you run your script. Make sure all dependencies listed in the `requirements.txt` file are installed in your environment since you're not using pip to install YOLOv5.

For more detailed instructions and troubleshooting, please refer to our documentation at https://docs.ultralytics.com/yolov5/.

If you encounter any further issues or have additional questions, feel free to ask. The YOLO community and the Ultralytics team are here to help!

**Comment by useruser2023** [comment]
@glenn-jocher  Followed above steps 

```
/yolov5$ export PYTHONPATH=$PYTHONPATH:$(pwd)
/yolov5$ python example.py
```

> 
> Traceback (most recent call last):
>   File "/home/linux/yolov5/example.py", line 6, in <module>
>     model = DetectMultiBackend("yolov5nu.pt")
>   File "/home/linux/yolov5/models/common.py", line 434, in __init__
>     model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
>   File "/home/linux/yolov5/models/experimental.py", line 89, in attempt_load
>     ckpt = torch.load(attempt_download(w), map_location="cpu")  # load
>   File "/home/linux/.virtualenvs/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/home/linux/.virtualenvs/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
>     result = unpickler.load()
>   File "/home/linux/.virtualenvs/venv/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
>     return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'ultralytics.yolo'
>

**Comment by glenn-jocher** [comment]
@useruser2023 Hi there! 👋 It seems like the environment is not properly recognizing the YOLOv5 directory as a module. To fix `ModuleNotFoundError: No module named 'ultralytics.yolo'`, you might need to adjust how you're setting the `PYTHONPATH` or how you're structuring your project.

A quick suggestion: Make sure you're running your command from the root of your YOLOv5 directory. If you're in the right directory and still facing issues, you can try adding the YOLOv5 directory to the Python path directly in your script. Add these lines before importing YOLOv5 modules:

```python
import sys
sys.path.append('/path/to/yolov5')

from models.common import DetectMultiBackend
```

Replace `/path/to/yolov5` with the actual path to your YOLOv5 folder. This adjustment tells Python explicitly to include your YOLOv5 directory in its search path for modules.

Hope this helps! Let us know if there's anything else. 😊
