### ISSUE TITLE
Discrepancy between test run results and individual inferences on the same images

### ISSUE THREAD

**Issue by Jhann024** [ultralytics/yolov5#12784]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have been working on a project to use YOLOv5s to make inferences on digital representations which are very static and do not have any sort of occlusions/change in angle/change in lighting etc. I put together a labelled dataset (Which I have gone back and verified that the labels are 100% correct) of 4800 images split into the following:

1. 3200 images for training
2. 800 images for validation
3. 800 images for testing - None of which are ever seen by the model during the training process.

# Training Run Results #

### Confusion Matrix: ###
![confusion_matrix_online](https://github.com/ultralytics/yolov5/assets/100393614/4dd8b5ea-c103-44ac-89c2-d22b01ef7dfe)

### F1 Curve: ###
![F1_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/0f05d128-4f1b-4021-b619-41d29c445a25)

### P_Curve: ###
![P_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/ef067a55-c03e-4357-ae07-51c1a23ef824)

### PR_Curve: ###
![PR_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/a3220d7d-7b1a-40f2-b7d2-ca91a5d3b344)

### R_Curve: ###
![R_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/b673db1f-171a-49bb-91e4-012e22315821)

### Results image: ###
![results](https://github.com/ultralytics/yolov5/assets/100393614/9cb9d3a1-f7d9-4fc2-90fd-1e82fb49d1d0)

### Results csv: ###
[results.csv](https://github.com/ultralytics/yolov5/files/14488606/results.csv)

There may be some concerns over overfitting here due to the obj_loss on val rising slightly towards the later half of the training run, but I dont believe this is my issue when taking into account the following results from my test run:

# Test Run Results #

### Confusion Matrix: ###
![confusion_matrix_online](https://github.com/ultralytics/yolov5/assets/100393614/067011aa-4e8a-4110-9a2c-59786a76bcf8)

### F1 Curve: ###
![F1_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/e90d6f94-5c52-4885-aaac-7273f11f2df7)

### P_Curve: ###
![P_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/6d659631-f13b-4096-b35c-97d58dead911)

### PR_Curve: ###
![PR_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/0005c7ce-304c-49af-ba03-6c5165f58ab8)

### R_Curve: ###
![R_curve_online](https://github.com/ultralytics/yolov5/assets/100393614/a1ae93e8-7a0d-4b90-9fb2-2e15be09b966)

### Results output of test run: ###
![TestResults](https://github.com/ultralytics/yolov5/assets/100393614/3fe067e5-05c5-45a9-929a-5440ca2a80a1)

### Label counts directly from test dataset label files: ###
![LabelCheck](https://github.com/ultralytics/yolov5/assets/100393614/6efcbc0f-6033-45b0-a742-ce976dfc490c)

# Scripts used: #

### Training/Testing Script: ###
```

import subprocess
import os

#Define path to Yolov5 Directory
yolov5_dir = fr'C:\Users\username\Documents\Coding\project\yolov5'

#Define the path to your dataset configuration file
dataset_yaml = fr'C:\Users\username\Documents\Coding\project\dataset.yaml'

test_weights = fr'C:\Users\username\Documents\Coding\project\yolov5\runs\train\yolov5s_results_continuous\weights\best.pt'
test_dataset_yaml = fr'C:\Users\username\Documents\Coding\project\test_dataset.yaml'

#Set the number of classes
num_classes = 13

#Training command
#train_cmd = fr'python train.py --img 1024 --batch 32 --epochs 500 --data {dataset_yaml} --weights yolov5s.pt --cfg ./models/yolov5s.yaml --name yolov5s_results_continuous --cache --resume'

#Resume command
test_cmd = fr'python val.py --weights {test_weights} --data {test_dataset_yaml} --img 1024 --task test --conf-thres 0.7 --iou-thres 0.2 --name test3'

os.chdir(yolov5_dir)
print(f"Executing command: {test_cmd}")
subprocess.run(test_cmd, shell=True) 

```

### Individual Inference Script: ###
```

import torch
from PIL import Image
import cv2
import numpy as np


# Load the model
model = torch.hub.load('/Users/username/Documents/Coding/project/yolov5', 'custom', path='/Users/username/Documents/Coding/project/yolov5/runs/train/yolov5s_results_continuous/weights/best.pt', source='local', trust_repo=True)
model.to('cuda')
model.eval()
model.conf = 0.7
model.iou = 0.2


# Load an Image
img_path = r'C:\Users\username\Documents\Coding\project\LabelledData\test_val\images\1.png'
img = Image.open(img_path)

# Perform inference
results = model(img)

# Parse the results
detected_objects = results.pandas().xyxy[0]
```

# Questions #

With all the above information taken into account, I am struggling to understand why my model appears to be working perfectly given the results of the test run compared against the expected results as found in the labels on my test dataset:

 Is there some error in the way that I am calling the model for the individual image inferences? I have done the individual inference on a number of images - both images not included in any of the labelled datasets, as well as even images within the test dataset and I continue to run into issues where the model will either fail to classify objects, or will classify objects incorrectly. 
 
 I understand that object detection models can have troubles at times with classifying images accurately, and this wouldnt necessarily be a problem if that was reflected in my test results as that would provide me an avenue to go about improving the model. But when the model test run is saying it is recognizing every single instance of each class down to the exact number for each, and I am seeing very different results in my individual inferences (1-3 errors per image at least) it leaves me at a loss for what I should be doing to investigate this.
 
 Also just as a disclaimer - The images being analyzed are very very similar, essentially the only difference between them is the presence of the objects so if the very high performance metrics give the impression that overfitting is to blame -  I would push against this as the nature of the images being used paired with the high performance on test data not seen during model training make me think this is not to blame.
 
 Apologies for such a long question, but I felt that including more information would be preferable over less but any assistance would be greatly appreciated with helping me to resolve this issue.
 
 Thanks in advance.

**Comment by glenn-jocher** [comment]
@Jhann024 hello! Thank you for providing such a detailed overview of your project and the issues you're encountering. It's clear you've put a lot of effort into this, and I'm here to help guide you through some potential steps to address the discrepancy between your test run results and individual inferences.

Firstly, it's important to ensure that the environment and settings used for batch testing and individual inferences are consistent. Differences in preprocessing, model configuration (such as confidence and IoU thresholds), or even the PyTorch and CUDA versions can lead to varied results. Here are a few things to check and try:

1. **Consistency in Preprocessing**: Ensure that the image preprocessing in your individual inference script matches exactly what's done during training and testing. This includes image resizing, normalization, and any other transformations.

2. **Model Configuration**: You've set `model.conf = 0.7` and `model.iou = 0.2` in your individual inference script. Verify these values are consistent with the settings used during your test runs. Small changes in these thresholds can significantly impact the detection results.

3. **Environment Check**: Ensure that the software environment (versions of PyTorch, CUDA, etc.) is the same for both testing and individual inference scenarios. Differences here can sometimes lead to unexpected behavior.

4. **Batch Size Impact**: When running inference on a single image, the batch size is effectively 1, which can sometimes affect the model's performance due to batch normalization layers. Though less likely to be the issue here, it's something to be aware of.

5. **Visual Inspection**: For the images where discrepancies are observed, visually inspect the predictions (perhaps by plotting the bounding boxes on the images) to understand the nature of the errors. Are they false positives, false negatives, or misclassifications? This might give you clues on what to adjust.

6. **Code Review**: Double-check your individual inference script for any potential oversights that might have been missed, such as incorrect image paths or issues with how the results are parsed and displayed.

If after trying these steps, you're still facing issues, I encourage you to share specific examples of the discrepancies you're observing (while ensuring no sensitive data is shared) in our GitHub discussions. This can help the community provide more targeted advice.

Remember, the YOLOv5 community is here to support you, and the collective knowledge and experience can be a great resource. Your detailed approach to explaining the problem is very helpful and appreciated. Keep experimenting, and don't hesitate to reach out with further questions or updates on your progress.

**Comment by Jhann024** [comment]
@glenn-jocher Good afternoon, thank you very much for taking the time to look at my problem. I am new to machine learning and have no formal education on the subject so these steps are greatly appreciated. I have looked into your points and below are my findings:

1. Consistency in Preprocessing: Following your suggestion, I updated my individual inference script to use the same preprocessing as is applied to the images in training/validation/testing (seen below). 

```
import torch
from PIL import Image
import cv2
import numpy as np
import time

def resize_and_pad(img, new_shape=(1024, 1024), color=(114, 114, 114)):
    shape = img.shape[:2]  # current image shape [height, width]
    ratio = min(new_shape[0] / shape[1], new_shape[1] / shape[0])
    new_unpad = (int(round(shape[1] * ratio)), int(round(shape[0] * ratio)))
    dw, dh = new_shape[0] - new_unpad[0], new_shape[1] - new_unpad[1]

    resized = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = dh // 2, dh - (dh // 2)
    left, right = dw // 2, dw - (dw // 2)
    padded = cv2.copyMakeBorder(resized, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)
    return padded

def normalize_image(img, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]):
    img = img.astype(np.float32) / 255.0  # Convert from Ints to Floats and scale from 0-255 to 0-1
    img = (img - mean) / std  # Normalize image
    return img

start = time.time()

# Load the model
model = torch.hub.load('/Users/username/Documents/Coding/project/yolov5', 'custom', path='/Users/jacob/Documents/Coding/BlackjackScannerNEW/yolov5/runs/train/yolov5s_results_continuous/weights/best.pt', source='local', trust_repo=True)
model.to('cuda')
model.eval()
model.conf = 0.7
model.iou = 0.2

# Load an Image
img_path = r'C:\Users\username\Documents\Coding\project\LabelledData\test_val\images\0.png'
img_cv_original = cv2.imread(img_path) 

#Resize the image (Same size as training/testing)
img_cv = resize_and_pad(img_cv_original, new_shape=(1024, 1024))

#Normalize the image (Same as yolov5 default)
img_cv_normalized = normalize_image(img_cv)

#Convert the image back to byte scale for PIL
img_cv_byte = np.clip(img_cv_normalized * 255, 0, 255).astype(np.uint8)

#Convert the image to PIL for inference
img_pil = Image.fromarray(cv2.cvtColor(img_cv_byte, cv2.COLOR_BGR2RGB))
```

2. Model Configuration: I did set the same conf/iou for my test runs and I believe the default iou in the default hyp file is 0.2 for the training run.  

3. Environment Check: I am running the training/testing/individual inferencing all on the same machine, so I dont believe that should be an issue.

4. Batch Size - I ran an additional test run using the batch size = 1 and and still seeing similar results seen below
![TestResults--batch 1](https://github.com/ultralytics/yolov5/assets/100393614/9757842e-530c-4acb-a9b5-30ff5448de9c)

5. Visual Inspection - Findings below

Implementing your suggestions seemed to improve the performance on the images somewhat, however I am still seeing between 0-4 errors per image on average. There is a fairly broad mix of errors that I am seeing when looking at the images and highlighting using bounding boxes which include the following where I have manually tested 100 images from the train/test datasets, along with 100 additional images not included at all in the training or testing. 

[CardRecogVerification.xlsx](https://github.com/ultralytics/yolov5/files/14543393/CardRecogVerification.xlsx)

In the above file contains those findings with the bulk of the findings on sheet 'Confusion Stats' and 'Error Stats' with the inputs to those found on the first three sheets. Based on this analysis (Although not a huge sample) it seems that the bulk of my errors are occurring when dealing with classes 8, 6, 5, 9 and 3, and that the errors are coming up as roughly 3.8%, 4.9% and 0.3% for Misclass, False Negative, and False Positive respectively of all inferences made by the model. Additionally, I also looked at the distribution of errors for each 'Type' of image - the images can be categorized into 8 'Types' based on the background of the images. When sorting by this, I found no significant discrepancy between them so I don't believe the model is learning too much on any one type of image as my dataset is evenly distributed among these.

Based on these findings, my assumption is that some combination of the following, but I'm curious to hear your thoughts.:

1) Using a more powerful model (v5m or v5L) 


2) Creating synthetic data to supplement training for the problem classes
    - If so, how many instances of each type should I shoot for to address their prevalence among the errors?

3) Changing the weighting of the problem labels
    - I've read about this online but not sure if it would be applicable here, though if I can avoid more dataset gathering that would be preferable 

4) Simply training for a greater number of epochs might be the answer
    - I don't believe I am currently at risk for overfitting based on the current model results, although it seems the rate of improvement has slowed dramatically based on my previously posted train run results, I have a feeling that this is probably not the answer.

My hope is to be able to get the sum of these errors from where it is at currently (~9%) down to somewhere in the range of ~0.5% if possible. I'm not sure if this is a reasonable goal or not, but the images I am processing are very very similar with little variance among them with respect to lighting/occlusions/difference in angles/location of objects/resolution etc due to the fact that they are screenshots of a digital representation.

 If you feel it would be helpful to your ability to assist that you be able to see the kinds of images I am attempting to perform inferences on, I would be more than happy to supply some examples and greater clarity on what exactly my project aims to do privately (Through email or whatever else you might prefer). Due to the nature of my project, I wouldn't be comfortable sharing those specifics here where they are publicly accessible, but if this isn't possible due to you wanting all the information publicly available in case someone else runs into a similar issue in the future and might use this thread to find answers - then I totally understand that. 

6. Code Review -  After thoroughly reviewing my individual inference script, I found no oversights  such as path issues or errors with the parsing of results.

Thank you again for your help on this I very much appreciate your guidance and look forward to hearing your thoughts on the information I have gathered above.

**Comment by Jhann024** [comment]
@glenn-jocher Good afternoon, thank you very much for taking the time to look at my problem. I am new to machine learning and have no formal education on the subject so these steps are greatly appreciated. I have looked into your points and below are my findings:

1. Consistency in Preprocessing: Following your suggestion, I updated my individual inference script to use the same preprocessing as is applied to the images in training/validation/testing (seen below). 

```
import torch
from PIL import Image
import cv2
import numpy as np
import time

def resize_and_pad(img, new_shape=(1024, 1024), color=(114, 114, 114)):
    shape = img.shape[:2]  # current image shape [height, width]
    ratio = min(new_shape[0] / shape[1], new_shape[1] / shape[0])
    new_unpad = (int(round(shape[1] * ratio)), int(round(shape[0] * ratio)))
    dw, dh = new_shape[0] - new_unpad[0], new_shape[1] - new_unpad[1]

    resized = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
    top, bottom = dh // 2, dh - (dh // 2)
    left, right = dw // 2, dw - (dw // 2)
    padded = cv2.copyMakeBorder(resized, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)
    return padded

def normalize_image(img, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]):
    img = img.astype(np.float32) / 255.0  # Convert from Ints to Floats and scale from 0-255 to 0-1
    img = (img - mean) / std  # Normalize image
    return img

start = time.time()

# Load the model
model = torch.hub.load('/Users/username/Documents/Coding/project/yolov5', 'custom', path='/Users/username/Documents/Coding/project/yolov5/runs/train/yolov5s_results_continuous/weights/best.pt', source='local', trust_repo=True)
model.to('cuda')
model.eval()
model.conf = 0.7
model.iou = 0.2

# Load an Image
img_path = r'C:\Users\username\Documents\Coding\project\LabelledData\test_val\images\0.png'
img_cv_original = cv2.imread(img_path) 

#Resize the image (Same size as training/testing)
img_cv = resize_and_pad(img_cv_original, new_shape=(1024, 1024))

#Normalize the image (Same as yolov5 default)
img_cv_normalized = normalize_image(img_cv)

#Convert the image back to byte scale for PIL
img_cv_byte = np.clip(img_cv_normalized * 255, 0, 255).astype(np.uint8)

#Convert the image to PIL for inference
img_pil = Image.fromarray(cv2.cvtColor(img_cv_byte, cv2.COLOR_BGR2RGB))
```

2. Model Configuration: I did set the same conf/iou for my test runs and I believe the default iou in the default hyp file is 0.2 for the training run.  

3. Environment Check: I am running the training/testing/individual inferencing all on the same machine, so I dont believe that should be an issue.

4. Batch Size - I ran an additional test run using the batch size = 1 and and still seeing similar results seen below
![TestResults--batch 1](https://github.com/ultralytics/yolov5/assets/100393614/9882b81b-014e-49be-b029-382755e30f56)


5. Visual Inspection - Findings below

Implementing your suggestions seemed to improve the performance on the images somewhat, however I am still seeing between 0-4 errors per image on average. There is a fairly broad mix of errors that I am seeing when looking at the images and highlighting using bounding boxes which include the following where I have manually tested 100 images from the train/test datasets, along with 100 additional images not included at all in the training or testing. 

[CardRecogVerification.xlsx](https://github.com/ultralytics/yolov5/files/14543457/CardRecogVerification.xlsx)

In the above file contains those findings with the bulk of the findings on sheet 'Confusion Stats' and 'Error Stats' with the inputs to those found on the first three sheets. Based on this analysis (Although not a huge sample) it seems that the bulk of my errors are occurring when dealing with classes 8, 6, 5, 9 and 3, and that the errors are coming up as roughly 3.8%, 4.9% and 0.3% for Misclass, False Negative, and False Positive respectively of all inferences made by the model. Additionally, I also looked at the distribution of errors for each 'Type' of image - the images can be categorized into 8 'Types' based on the background of the images. When sorting by this, I found no significant discrepancy between them so I don't believe the model is learning too much on any one type of image as my dataset is evenly distributed among these.

Based on these findings, my assumption is that some combination of the following should be the steps I take, but I'm curious to hear your thoughts:

1) Using a more powerful model (v5m or v5L)

2) Creating synthetic data to supplement training for the problem classes 
    - If so, how many instances of each type should I shoot for to address their prevalence among the errors?

3) Adjusting the weighting of the problem classes for training
    - I dont have much knowledge on how I might do this, but this was one of the things I stumbled across while online, and if I can avoid having to gather more data that would definitely be preferable.
 
4) Simply training for a greater number of epochs
    - While I dont believe my model is currently at risk of overfitting, im not sure this is very likely to be the solution as the rate of improvement seems to have slowed dramatically based on my previously mentioned training run details.

My hope is to be able to get the sum of these errors from where it is at currently (~9%) down to somewhere in the range of ~0.5% if possible. I'm not sure if this is a reasonable goal or not, but the images I am processing are very very similar with little variance among them with respect to lighting/occlusions/difference in angles/location of objects/resolution etc due to the fact that they are screenshots of a digital representation.

 If you feel it would be helpful to your ability to assist that you be able to see the kinds of images I am attempting to perform inferences on, I would be more than happy to supply some examples and greater clarity on what exactly my project aims to do privately (Through email or whatever else you might prefer). Due to the nature of my project, I wouldn't be comfortable sharing those specifics here where they are publicly accessible, but if this isn't possible due to you wanting all the information publicly available in case someone else runs into a similar issue in the future and might use this thread to find answers - then I totally understand that. 

6. Code Review -  After thoroughly reviewing my individual inference script, I found no oversights  such as path issues or errors with the parsing of results.

Thank you again for your help on this I very much appreciate your guidance and look forward to hearing your thoughts on the information I have gathered above.

**Comment by glenn-jocher** [comment]
@Jhann024 Good evening! I'm thrilled to see the depth of analysis and thoughtful experimentation you've conducted based on the initial guidance. Your detailed approach and the steps you've taken to diagnose and address the discrepancies in your model's performance are commendable. Let's dive into the insights you've gathered and outline some next steps which may help improve your model's accuracy.

1. **Using a More Powerful Model (v5m or v5l)**: This is a logical step. Larger YOLOv5 models have more capacity and potentially offer better accuracy, especially in complex or difficult-to-differentiate scenarios. Given your goal of reducing the error rate to ~0.5%, moving to `v5m` or `v5l` models could make a significant difference, albeit at the cost of increased computational resources.

2. **Creating Synthetic Data for Problem Classes**: Augmenting your dataset with synthetic data can be a very effective way to improve performance, particularly for underrepresented or challenging classes. The exact number of instances needed varies widely based on the specific task, but a good starting point would be to at least double the representation of those classes in your training data. Monitor the model's performance as you incrementally increase the synthetic data to avoid overfitting.

3. **Adjusting Class Weights**: This strategy can help the model pay more attention to certain classes during training. Unfortunately, an out-of-the-box solution for class weighting is not directly available in YOLOv5's training pipeline, and implementing this would require custom modifications to the loss calculation. Before diving into this more complex approach, I'd recommend exploring the first two options, as they are more straightforward and could yield desired results.

4. **Training for More Epochs**: Given your model is not overfitting, training for more epochs could potentially improve performance. However, since you've observed a slowdown in the rate of improvement, this might offer diminishing returns. Consider this as a complementary strategy alongside the use of a more powerful model and dataset augmentation.

Regarding your project's specifics and the highly similar nature of your images, the strategies you've proposed are spot on. Achieving a sub-1% error rate is ambitious but not outside the realm of possibility, especially given the controlled variability of your dataset.

Should you wish to discuss further, my priority is to keep our conversation accessible to the community, fostering a transparent environment where everyone can learn. While specific project details might require discretion, I encourage sharing as much as you comfortably can in this forum. This approach ensures that knowledge is freely available, benefiting the broader YOLO community.

Finally, your rigorous testing and documentation, including error analysis and class-specific challenges, set a fantastic example for conducting machine learning experiments. Continue along this path, iteratively refining your model and dataset as you've been doing. The journey to ML excellence is often filled with trial, error, and continuous learning. Keep up the outstanding work, and please keep us updated on your progress!

**Comment by glenn-jocher** [comment]
@Jhann024, it's great to see your dedication to improving your model's performance and your thorough follow-up on the suggested steps. Based on the findings and results you've shared, it seems there are a few avenues that might further alleviate the discrepancy between test results and individual inferences and enhance overall detection accuracy.

1. **More Powerful Model**: Upgrading to a more capable version of YOLOv5, such as YOLOv5m or YOLOv5l, can potentially improve detection accuracy due to their increased capacity to learn from complex data. However, keep in mind this might come with increased computational costs.

2. **Synthetic Data**: Generating synthetic data to augment your training set could help, especially for underperforming classes. For the quantity, aim for a balanced dataset that proportionally enhances the representation of those classes without introducing bias. A good starting point could be doubling the amount for underrepresented classes and monitoring the impact.

3. **Class Weighting**: Adjusting class weights can be tricky but can help focus the model’s learning efforts on classes that are problematic. This usually involves modifying the loss function to give more importance to certain classes. Unfortunately, YOLOv5 does not directly support class weights in the most straightforward manner, but modifying the source code for custom loss calculation might be an option for advanced users.

4. **Longer Training**: While additional epochs could potentially improve performance, diminishing returns and overfitting risks are valid concerns. Monitoring validation loss closely as you increase epochs will be crucial to avoid overfitting.

Given the relatively low variance in your data, achieving an error rate reduction down to ~0.5% might be ambitious but not impossible. Fine-tuning and potentially ensembling models (running multiple models and aggregating their predictions) could be another strategy to consider for incremental improvements.

On sharing images privately, while we appreciate your offer, it's essential to keep discussions open so the community benefits. Instead, anonymizing data or creating similar representative examples that don't compromise your project's privacy could be a way to share more details publicly.

Lastly, since you've thoroughly analyzed errors by class, focusing efforts on creating additional, high-quality annotations for underperforming classes might yield the most significant improvements. This includes not only augmenting data but also revisiting existing annotations to ensure quality and consistency.

Keep iterating and experimenting, as model performance improvements often come from persistent refinement. Your systematic approach and willingness to explore various solutions are commendable, and we're here to support your journey.
