### ISSUE TITLE
let say we have train a custom model from yolov8 on low resolution images if i give that model to do inference on a high resolution image how the model will handle it in background and is there any information loss in the scaling process

### ISSUE THREAD

**Issue by dharakpatel** [ultralytics/yolov5#12833]
let say we have train a custom model from yolov8 on low resolution images if i give that model to do inference on a high resolution image how the model will handle it in background and is there any information loss in the scaling process

_Originally posted by @dharakpatel in https://github.com/ultralytics/yolov5/issues/2660#issuecomment-2011680043_

**Comment by glenn-jocher** [comment]
@dharakpatel hello! Great question, and happy to clarify 🙌.

When you train a model on low-resolution images and then perform inference on higher resolution images, the model will automatically resize the high-resolution input images to the dimensions it was trained on. This resizing is part of the pre-processing step in the inference pipeline. 

It's important to note that during this resizing process, some information loss is inevitable due to the decrease in resolution, which may reduce the model's accuracy or ability to detect smaller objects in the high-resolution image. However, the model attempts to retain critical features during the resize, optimizing for detection performance.

For optimal results, training and inference on similar resolutions or experimenting with different input sizes could help assess the impact on your specific use case. Also, exploring our documentation might provide some additional insights into handling various resolutions: https://docs.ultralytics.com/yolov5/.

Hope this helps! If you have further questions, feel free to ask.
