### ISSUE TITLE
YOLOV5 no longer works on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by gilmotta3** [ultralytics/yolov5#12875]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

YOLOV5 no longer works on NVIDIA Jetson Nano, don't waste your time until the ultralytics dependency is fixed or removed.

I am encountering a module import error related to the ultralytics package when attempting to run YOLOv5 on an NVIDIA Jetson Nano. This issue arises when executing the detect.py script, specifically at the import statement for ultralytics modules within YOLOv5's code.

Environment:
Device: NVIDIA Jetson Nano
Python Version: 3.6.9
Operating System: Ubuntu 18.04 (compatible with Jetson Nano)
PyTorch Version: 1.10.0 (installed from NVIDIA's recommended wheels for Jetson)
Torchvision Version: 0.11.1 (installed from NVIDIA's recommended wheels for Jetson)
YOLOv5 Version: Latest from main branch as of [Date]
CUDA Version: Compatible with installed PyTorch/torchvision versions
Issue Description:
Upon running the detect.py script with a basic test (either images or video stream), the script fails with the following error message:

`Traceback (most recent call last):
  File "detect.py", line 47, in <module>
    from utils.plots import Annotator, colors, save_one_box
  File "/home/[username]/yolov5/utils/plots.py", line 19, in <module>
    from ultralytics.utils.plotting import Annotator
ModuleNotFoundError: No module named 'ultralytics'
`

This suggests that the script is unable to import the ultralytics module, despite following all installation and setup instructions closely, including setting up the environment as recommended for the Jetson Nano platform.

Steps to Reproduce:
Set up the Jetson Nano with NVIDIA-recommended versions of PyTorch and torchvision.
Clone the YOLOv5 repository and install dependencies (excluding PyTorch and torchvision to avoid conflicts with NVIDIA's versions).
Attempt to run detect.py with any input source.

deleting the line will not solve the problem because YOLOv5 is trying to use ultralytics stuff deep unde the hood.

So until this ticket gets a RESOLVED status, don't waste your time with YOLOv5 on Jetson Nano.

### Environment

Device: NVIDIA Jetson Nano
Python Version: 3.6.9
Operating System: Ubuntu 18.04 (compatible with Jetson Nano)
PyTorch Version: 1.10.0 (installed from NVIDIA's recommended wheels for Jetson)
Torchvision Version: 0.11.1 (installed from NVIDIA's recommended wheels for Jetson)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gilmotta3 hello! I'm sorry to hear you're experiencing issues running YOLOv5 on the NVIDIA Jetson Nano. 🙁

The error message you're seeing indicates a problem with importing a module from the Ultralytics package. This sounds like there might be an issue with the package installation or a compatibility issue with the setup on the Jetson Nano.

To help solve this, please ensure that you've followed all the steps for installation as listed in our documentation, and all dependencies are correctly installed in your environment. Since you're using specific versions of PyTorch and torchvision recommended for the Jetson Nano, please double-check that these versions are fully compatible with the latest YOLOv5 code from our main branch. Sometimes, updates or changes in YOLOv5 might require newer versions of these libraries.

If after checking the compatibility and ensuring all installations are correct the issue persists, it might be beneficial to try installing YOLOv5 in a fresh virtual environment to rule out any conflicts with other installed packages. 

We're continually working to improve compatibility and ease of use on a wide range of devices, including the NVIDIA Jetson series. Your feedback is valuable to us in this process.

If the problem continues, please provide additional details including any error messages or logs, and we'll do our best to assist you further.

👍 Thank you for your support and patience.

**Comment by gilmotta3** [comment]
@glenn-jocher I have followed the instructions and tried to install new virtual environments. I have been doing this for the last three days and I deviated my focus from the actual business because YOLO does not work and the repo is broken and I am trying to see the issue. I have watched dozens of videos on YouTube from a year ago or so to find out that I am doing the same exact things but now they don't work. I came across other developers who are having the same issue but for some reason they did not open a bug ticket.

I am telling categorically that YOLOv5 is broken for Nvidia Jetson Nano. Unless you have the hardware yourself you aren't going to see the issue. I am now trying to switch to a Docker Container solution but even Docker is now failing to install.

from: https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

(video) video@video-desktop:~/development/docker$ sudo docker pull ultralytics/yolov5:latest
[sudo] password for video:
latest: Pulling from ultralytics/yolov5
no matching manifest for linux/arm64/v8 in the manifest list entries
(video) video@video-desktop:~/development/docker$

only to find out tha there is no support for ARM

if you would like to solve this problem I can make myself available in whatever time zone you are but I ran out of options and I will start looking for other options. Maybe Jetson Nano is old and I made a mistake picking up this board.

I can make this board available to anyone willing to help via SSH.

Anyone reading this ticket if there is no update here, I would suggest you not waste your time.

Good Luck!

**Comment by glenn-jocher** [comment]
@gilmotta3, I'm genuinely sorry to hear about the troubles you've been experiencing with getting YOLOv5 up and running on the NVIDIA Jetson Nano. It's clear you've invested a lot of effort into this, and it's frustrating when things don't go as planned. 🙁

The error you're encountering with Docker and the ARM architecture is unfortunately a known compatibility issue due to the lack of an ARM build for our Docker image. This is indeed a limitation for users on ARM-based devices like the Jetson Nano.

While we currently don't have a ready-made solution for ARM devices in our Docker images, I appreciate your offer to make the board available for testing. This could be beneficial for community-driven solutions, though our capacity to personally dive into hardware-specific issues is limited.

For now, I would suggest:

- Cross-verifying all software versions (Python, PyTorch, etc.) are within the compatibility range of the YOLOv5 version you're using.
- Considering a manual setup outside of Docker, ensuring all dependencies are correctly installed for your platform. Sometimes, installation from source rather than pre-built wheels (where possible) can resolve unexpected issues.

Your situation also highlights a gap in our support for ARM architectures, which we'll take as valuable feedback for our roadmap.

Though I understand if this situation necessitated exploring alternatives, I hope you'll stay connected to future updates. The YOLOv5 community is continually growing, with improvements and solutions contributed regularly.

Thank you for your patience and your detailed feedback. 🙏
