### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by M0ki1** [ultralytics/yolov5#12870]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Im currently working in a CCTV image detection, after a while runing the model, it starts using 160% of CPU and the GPU only marks a 4% of usage, this is what i use in the main function Compatibilidad CUDA. torch: 2.1 ; cuda: cu121 , device: cuda:0 GPU: GRID T4-16Q. I can't understand why is getting this absurdly amount of CPU usage if is specifically told to use GPU. Please help

**Comment by glenn-jocher** [comment]
@M0ki1 hello! Thanks for reaching out and detailing your issue. 😊 High CPU usage in a GPU-enabled environment can stem from several factors, but let’s focus on a few key points to help diagnose and potentially reduce the CPU load:

1. **Data Loading:** The DataLoader can be CPU-intensive, especially if you're preprocessing images on the fly. Adjust the `num_workers` in your DataLoader to optimize CPU usage. A good starting point could be `num_workers=4` and adjust based on your system's capabilities.

2. **Batch Size:** A small batch size might cause the GPU to be underutilized, leading to higher relative CPU usage. If your GPU memory allows, try increasing the batch size.

3. **Tensor Operations:** Ensure any tensor operations (resizing, normalization) are being performed on the GPU. Check that all tensors are being sent to the same device as the model (`cuda:0` in your case).

Remember, monitoring tools may sometimes show high CPU usage for brief moments due to data loading or other non-model operations. If the problem persists even after trying the above suggestions, consider profiling your code to identify the exact operations causing the high CPU usage.

For further performance optimization tips, check our documentation. If after trying these steps you're still encountering issues, please provide us with detailed profiling information so we can assist better.

Keep innovating, and thanks for being part of the YOLOv5 community! 🚀
