### ISSUE TITLE
ImportError: cannot import name 'check_requirements' from 'utils.general'

### ISSUE THREAD

**Issue by RileyMccon** [ultralytics/yolov5#12887]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I have been trying to run inference on a custom yolov5 model. I have cloned the repo and installed according to the instructions, yet keep running into this error. Very recent, as it worked up until a couple days ago.

 ImportError: cannot import name 'check_requirements' from 'utils.general'

### Minimal Reproducible Example

weight = #path to model
model = torch.hub.load("ultralytics/yolov5", "custom", path=weight)  # custom model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RileyMccon hello! It seems like you're facing an import issue with `check_requirements` from `utils.general`. This is often due to a mismatch between the codebase and the dependencies installed, or potentially a path issue. 🙂

Here are a few steps to try and resolve this:
1. Ensure your local repository is up to date with the latest changes from the Ultralytics YOLOv5 GitHub repository. A recent update could have altered paths or dependencies.
2. Check your Python environment to make sure it's correctly set up and activated. Sometimes, environmental issues can cause these import errors.
3. Run `pip install -r requirements.txt` from the root of the cloned YOLOv5 repository to ensure all dependencies are correctly installed and up to date.

If these steps don't resolve the issue, consider deleting the YOLOv5 directory, cloning the repository again, and following the installation instructions afresh. This can sometimes fix unanticipated issues caused by changes or corruption in the local setup.

Feel free to share any updates or additional information after trying these steps. The YOLO community and the Ultralytics team are here to help!
