### ISSUE TITLE
warning: plotting  error for ......exp\resulte.csv :  \'value'must be an instance of str or bytes,not a float

### ISSUE THREAD

**Issue by zhangsanliisi** [ultralytics/yolov5#12889]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

when i run(yolov5-seg) end, results tellde:
warning: plotting  error for ......exp\resulte.csv :  \'value'must be an instance of str or bytes,not a float

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zhangsanliisi hey there!

Thank you for reaching out and for your interest in contributing a PR! 😊 It sounds like you encountered a plotting error related to the type of data being passed.

A common cause for this issue is when a non-string value is expected to be a string during plotting operations. Please ensure that when you are attempting to plot or output values that require string-type values, you explicitly convert or format these values as strings. For instance, if you're directly using values from a CSV file, you might want to cast them to strings using `str(value)` before plotting.

Without seeing the precise context of your code, a general example to fix such an issue could look something like this:

```python
value = str(your_float_value)  # Ensure the value is a string
plot_function(value)  # Continue with plotting
```

Feel free to submit the PR with the fix, and don't hesitate to ask if you need further clarification or assistance. The YOLO community and the Ultralytics team are here to support each other. Good luck with your PR!
