### ISSUE TITLE
very small size image train problem

### ISSUE THREAD

**Issue by Hank-lu-88** [ultralytics/yolov5#12892]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello:
My project is to make a thermal image detector to detect people using thermal images. I use yolov5s to train the model. My lens uses a 32x24 pixel thermal image camera, so I use 32x24 Pictures are used for training.Here is my command：

`python train.py --weights v5lite-s.pt --cfg models/v5Lite-s.yaml --img-size  32 24 --rect --batch-size 64 --data data/mydata.yaml --device 0 --epochs 300`

but the model produces weird results.
![test_batch0_pred](https://github.com/ultralytics/yolov5/assets/151129805/addfaa5d-479a-4c70-b702-f4a3030fefcc)
![P_curve](https://github.com/ultralytics/yolov5/assets/151129805/c1ef0155-ebe6-45b4-8166-d55967f52a65)

The picture below is my label. I expected this result like that
![test_batch0_labels](https://github.com/ultralytics/yolov5/assets/151129805/02b19b4d-5a20-4673-bcac-e8c0cd1f060c)

I'm wondering if yolov5 has a minimum image size limit, please help me, thank you.

**Comment by glenn-jocher** [comment]
@Hank-lu-88 hello there! 😊

Training YOLOv5 on such small images (32x24 pixels) is indeed challenging due to the limited amount of detail each image can convey. YOLOv5 models typically perform best with larger images (e.g., 640x640 pixels) as the architecture is designed to detect objects across various scales, but it relies on having sufficient resolution to identify features accurately.

One approach to tackle this is to upscale your thermal images to a larger size before training while keeping in mind this may introduce some artifacts. Additionally, adjusting the `--img-size` to a larger dimension that's still divisible by 32 might help (e.g., `--img-size 640`). This won't change the native resolution of your thermal images but will provide the model with a resized input that's more in line with its optimal operating conditions. Here's the adjusted command, considering the upscaling:

```bash
python train.py --weights v5lite-s.pt --cfg models/v5Lite-s.yaml --img-size 640 640 --rect --batch-size 16 --data data/mydata.yaml --device 0 --epochs 300
```

Remember, upscaling and adjusting `--img-size` requires you to balance between model performance and the computational cost. You might need to experiment with different sizes to find the sweet spot for your specific use case.

If performance issues persist, consider exploring custom model adjustments or consulting with our team for further guidance by checking the Ultralytics Docs.

Keep up the great work, and we're here to support every step of the way in your YOLOv5 journey!
