### ISSUE TITLE
Please update vyolov5.6.2 to support numpy1.20 or higher.

### ISSUE THREAD

**Issue by FN4321** [ultralytics/yolov5#12902]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

**### Bug details**

I am training a yolov5.6.2 model with google colab. 
At that time, an error occurred in the attached image.

<img width="934" alt="2024-04-10 135135" src="https://github.com/ultralytics/yolov5/assets/158559530/b65efd40-5f76-42d1-9ef3-0fb85b250a28">

The contents are "AttributeError: module 'numpy' has no attribute 'int'." in the directory "/content/drive/MyDrive/ncom-pj/myfolder/code_main_valid7/yolov5/utils/dataloaders.py". 
The error is that the method int is not applied to numpy.
This is happening in the content of the file, so I would appreciate it if you could fix it.

### Environment

YOLOv5 🚀 v6.2-0-gd3ea0df8 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 29.0/201.2 GB disk)

### Minimal Reproducible Example

１
`!git clone https://github.com/ultralytics/yolov5.git -b v6.2`
２
`!pip install -qr yolov5/requirements.txt`
３
`%cd yolov5`
４
```import torch
import utils
display = utils.notebook_init()
```
５ ← Error location
`!python train.py --img 416 --batch 16 --epochs 1 --weights yolov5s.pt --data data/data.yaml --cfg models/yolov5s.yaml --patience 50`

### Additional

Before code 2, I installed numpy==1.19.5, which supports numpy.int(). However, it was automatically updated during training.
Also, with the git clone `!git clone https://github.com/ultralytics/yolov5.git`, I was able to successfully training and predicting.
If you like, configure the model with `!git clone https://github.com/ultralytics/yolov5.git -b v6.2` and `!git clone https://github.com/ultralytics/yolov5.git` I would be happy if I knew if it didn't change.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for the detailed report! 👍

It seems you've encountered a compatibility issue with numpy versions. The `numpy.int` attribute error is known to occur with numpy 1.20 and above due to deprecation of certain aliases for Python built-in types.

To prevent numpy from automatically updating, you can try pinning its version right after installing YOLOv5's requirements. Here's a modified step to include after your step 2:

```python
!pip install numpy==1.19.5
```

This ensures numpy remains at version 1.19.5 throughout your training session. If you still encounter issues, consider creating a virtual environment specifically for your YOLOv5 project to better manage dependency versions.

We appreciate your willingness to submit a PR. Enhancements for compatibility with newer numpy versions can certainly benefit the community. For further guidance on contributing, refer to our documentation at https://docs.ultralytics.com/yolov5/. 

Your collaboration helps us all! 🌟
