### ISSUE TITLE
Change images produced by segment/predict.py

### ISSUE THREAD

**Issue by osamamer** [ultralytics/yolov5#12908]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I'm trying to change the segment/predict,py file in order to make it produce a black-and-white image, the white portion of which is the detections, and everything else is black. This requires me to change the opacity of the image to be fully opaque, which I'm having trouble figuring out. I tried changing the alpha parameter in the Annotator's masks function, but that raises a tensor dimension mismatch error. What changes do I need to make to the predict file to get the required output?

**Comment by glenn-jocher** [comment]
@osamamer hello! 👋 It sounds like you're working on a custom output for your segmentation tasks using YOLOv5. To achieve a black-and-white image where detections are white and the rest is black, you indeed need to modify how the mask is applied and how the final image is constructed.

Here's a simplified approach:

1. After detection, instead of using the Annotator's mask function to overlay colored masks, you'll directly work with the detection results to create a binary mask. For each detected object, fill the corresponding area with white (value = 255) on a black (value = 0) background.
2. Ensure the image you're starting with is a black numpy array of the same dimensions as your input image, but single channel for BW.

Here is a conceptual snippet:

```python
import numpy as np

# Assuming 'results' is your detection output from model
img_bw = np.zeros((results.imgs[0].shape[0], results.imgs[0].shape[1]), dtype=np.uint8)  # Creating BW base

for det in results.xyxy[0]:  # Loop through detections
    bbox = [int(x) for x in det[:4]]  # Convert to int
    img_bw[bbox[1]:bbox[3], bbox[0]:bbox[2]] = 255  # Fill detected areas with white

# 'img_bw' now is your black-white image as desired
```

This code snippet assumes that your model's detections are stored in `results` and that `results.xyxy[0]` contains the bounding boxes for the detections in the format `[x1, y1, x2, y2, confidence, class]`. Adjust your array indexing as necessary depending on your output structure. This will provide a simplistic start towards generating a B&W mask where detections are highlighted.

Feel free to tweak this further based on your project's specific requirements. Happy coding! 🚀
