### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by khrb** [ultralytics/yolov5#12907]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

  File "/Users/jiasecha/Documents/代码/分词系统/gradio_yolov5_det/gradio_yolov5_det_v6.py", line 719, in main
    inputs_img = gr.Image(image_mode="RGB", source=source, tool=img_tool, type="pil", label="原始图片")
  File "/Users/jiasecha/Library/Python/3.9/lib/python/site-packages/gradio/component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@khrb hello! Thanks for reaching out. It looks like the issue you're encountering is related to the use of an unexpected keyword argument 'source' when initializing the `gr.Image` component.

From your code snippet, it appears you're trying to pass a 'source' argument to `gr.Image`, which is likely causing the error because 'source' is not a recognized parameter for initializing `gr.Image`. If your goal is to define the source of the image, you might want to double-check the Gradio documentation or usage examples to find the correct way to specify an image source.

For working with YOLOv5 and if your task is about image input for detection, you typically won't need to specify a 'source' at this point in your code. If you're trying to load an image for detection with YOLOv5, consider using the appropriate method to load your image into a PIL Image or a NumPy array before processing.

Here's a simple correction without the 'source' argument:

```python
inputs_img = gr.Image(image_mode="RGB", tool=img_tool, type="pil", label="原始图片")
```

Make sure to adjust your function parameters according to what's accepted by `gr.Image`.

If your issue persists or this doesn't solve your problem, it might be helpful to provide more context on what 'source' is intended for in your application. Remember, the YOLOv5 community is always here to help out. Happy coding! 😊
