### ISSUE TITLE
Exploring Data Augmentation in YOLO-based Networks

### ISSUE THREAD

**Issue by BehdadSDP** [ultralytics/yolov5#12910]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello friends,
In the training of this yolo, as you know, there is a series of parameters for set data augmentation method. One of the methods is _mosaic_, which greatly slows down the learning process. Because the DataLoader must select 4 random images in each iteration and put these four images together. The question I have is, is it possible to perform  the Data Augmentation Process once for  dataset and then do the training without the data augmentation methods?

**Comment by glenn-jocher** [comment]
Hello!

Great question about data augmentation in YOLOv5! Indeed, the _mosaic_ augmentation can be computationally intensive due to its process. However, performing data augmentation once and then using the augmented dataset for training isn't directly supported within the current YOLOv5 framework. This approach would require manually generating and storing the augmented images before training, which might not be as efficient or easy to manage, especially with dynamic augmentations like _mosaic_.

A practical alternative to reduce computational overhead without turning off _mosaic_ could be to adjust the `mosaic` setting in your `*.yaml` configuration file under the augmentation options to a lower frequency if you're finding it too slow.

Always ensure you're using the latest version of YOLOv5 for the best performance and features. And remember, experimenting with different configurations can often lead to the best balance between speed and model performance for your specific dataset. 🚀

Happy training!

**Comment by BehdadSDP** [comment]
thanks for you answer.

**Comment by BehdadSDP** [comment]
> thanks for you answer.



> Hello!
> 
> Great question about data augmentation in YOLOv5! Indeed, the _mosaic_ augmentation can be computationally intensive due to its process. However, performing data augmentation once and then using the augmented dataset for training isn't directly supported within the current YOLOv5 framework. This approach would require manually generating and storing the augmented images before training, which might not be as efficient or easy to manage, especially with dynamic augmentations like _mosaic_.
> 
> A practical alternative to reduce computational overhead without turning off _mosaic_ could be to adjust the `mosaic` setting in your `*.yaml` configuration file under the augmentation options to a lower frequency if you're finding it too slow.
> 
> Always ensure you're using the latest version of YOLOv5 for the best performance and features. And remember, experimenting with different configurations can often lead to the best balance between speed and model performance for your specific dataset. 🚀
> 
> Happy training!

many thanks.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance as you proceed, feel free to ask. Happy training and best of luck with your projects! 🚀
