### ISSUE TITLE
How to do  instance segmention on video or streaming data 

### ISSUE THREAD

**Issue by klein1213811** [ultralytics/yolov5#12924]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to do instance segmention on video or streaming data ,like yolov8

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-seg.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(['im1.jpg', 'im2.jpg'], stream=True)  # return a generator of Results objects

# Process results generator
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    result.show()  # display to screen
    result.save(filename='result.jpg')  # save to disk
```

**Comment by glenn-jocher** [comment]
Hello there! 🌟

To adapt instance segmentation for video or streaming data similar to your YOLOv8 example but focusing on YOLOv5, please note that YOLOv5 primarily focuses on object detection tasks, evolving from bounding box predictions rather than instance segmentation. 

For video or streaming data, you would typically pass frames one by one into the model in a loop, similar to processing a list of images but iterating over video frames. However, for instance segmentation specifically, you might want to explore integrating YOLOv5 with additional tools or libraries specialized in segmentation tasks, as YOLOv5 does not directly support this out-of-the-box.

Here's a generic snippet for processing video frames with YOLOv5, although this is focused on detection tasks:

```python
from ultralytics import YOLO
import cv2

# Load the model
model = YOLO('yolov5s.pt')  # Adjust the model as per your requirements

# Open video
cap = cv2.VideoCapture('path/to/your/video.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Inference
    results = model(frame)

    # For displaying, replace or add your custom code to process instance segmentation
    results.show()
    
    # Press Q on keyboard to exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# When everything done, release the video capture object
cap.release()
```
Note: This code is focused on detection. For instance segmentation, YOLOv5 would require additional method integrations.

Unfortunately, direct instance segmentation as per your question isn't a feature in YOLOv5. For cutting-edge tasks like instance segmentation, I recommend checking the latest updates or discussing within the YOLOv5 community for potential custom solutions or recommendations.

Keep innovating! 😊
