### ISSUE TITLE
Add ghost modules into tf.py for exporting yolov5s-ghost.pt to tensorflow saved_model or tflite

### ISSUE THREAD

**Issue by lexxxx-cmd** [ultralytics/yolov5#12930]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

To solve this https://github.com/ultralytics/yolov5/issues/9489#issue-1377645244 add TFGhostConv,TFC3Ghost, TFGhostBottleneck into tf.py and export yolov5s-ghost.pt to .tflite successfully

### Use case

# Train a model with models/hub/yolov5s-ghost.yaml

`!python train.py --weights ''   --cfg models/hub/yolov5s-ghost.yaml`

# Add classes in tf.py 
```
class TFGhostConv(keras.layers.Layer):
    # Ghost Convolution https://github.com/huawei-noah/ghostnet
    def __init__(self, c1, c2, k=1, s=1, g=1, act=True,w=None):
        """Initializes GhostConv with in/out channels, kernel size, stride, groups, and activation; halves out channels
        for efficiency.
        """
        super().__init__()
        c_ = c2 // 2  # hidden channels
        self.cv1 = TFConv(c1, c_, k, s, None, g, act=act,w=w.cv1)
        self.cv2 = TFDWConv(c_, c_, 5, 1, None, act=act,w=w.cv2)

    def call(self, inputs):
        """Performs forward pass, concatenating outputs of two convolutions on input `x`: shape (B,C,H,W)."""
        y = self.cv1(inputs)
        return tf.concat((y, self.cv2(y)), axis=3)
```
```
class TFGhostBottleneck(keras.layers.Layer):
   # Ghost Bottleneck https://github.com/huawei-noah/ghostnet
   #w has w.conv and w.shortcut
    def __init__(self, c1, c2, k=3, s=1,w=None):
        """Initializes GhostBottleneck with ch_in `c1`, ch_out `c2`, kernel size `k`, stride `s`; see https://github.com/huawei-noah/ghostnet."""
        super().__init__()
        
        w1 = w.conv
        sc1 = w.shortcut
        wGConv = w1[0]
        wDWConv = w1[1]
        wGConv2 = w1[2]

        
        c_ = c2 // 2
        self.conv = keras.Sequential(
            [TFGhostConv(c1, c_, 1, 1,w=wGConv),  # pw
            TFDWConv(c_,c_,k,s,act=False) if s == 2 else  keras.layers.Lambda(tf.identity),  # dw
            TFGhostConv(c_, c2, 1, 1, act=False,w=wGConv2),
        ])  # pw-linear
        self.shortcut = (
            keras.Sequential(TFDWConv(c1, c1, k, s, act=False,w=sc1), TFConv(c1, c2, 1, 1, act=False,w=sc1)) if s == 2 else tf.identity
        )

    def call(self, inputs):
        """Processes input through conv and shortcut layers, returning their summed output."""
        return self.conv(inputs) + self.shortcut(inputs)
```
```
class TFC3Ghost(keras.layers.Layer):
    def __init__(self, c1, c2, n=1, shortcut=True, g=1, e=0.5, w=None):
        """
        Initializes CSP Bottleneck with 3 convolutions, supporting optional shortcuts and group convolutions.

        Inputs are ch_in, ch_out, number, shortcut, groups, expansion.
        """
        super().__init__()
        c_ = int(c2 * e)  # hidden channels
        self.cv1 = TFConv(c1, c_, 1, 1, w=w.cv1)
        self.cv2 = TFConv(c1, c_, 1, 1, w=w.cv2)
        self.cv3 = TFConv(2 * c_, c2, 1, 1, w=w.cv3)
        self.m = keras.Sequential(
            [TFGhostBottleneck(c_, c_,w=w.m[j]) for j in range(n)]
            )
    def call(self, inputs):
        """
        Processes input through a sequence of transformations for object detection (YOLOv5).

        See https://github.com/ultralytics/yolov5.
        """
        return self.cv3(tf.concat((self.m(self.cv1(inputs)), self.cv2(inputs)), axis=3))
```
## make sure being imported and used in function parse_model()
```
from models.common import (
    C3,
    ...
    C3Ghost,
    GhostConv,
    GhostBottleneck,
    ...
    SPP,
    ...
)
```
```
if m in [
            ...
            C3,
            ...
            C3Ghost,
            GhostConv,
            GhostBottleneck,
            ...
            C3x,
            ...
        ]:
```
```
if m in [BottleneckCSP, C3, C3x,C3Ghost]:
                args.insert(2, n)
                n = 1
```
# export
`!python export.py --weights "your_yolov5s-ghost.pt " --data your_data.yaml --include tflite `

# My result
![image](https://github.com/ultralytics/yolov5/assets/75561591/09eeb22b-7280-4fb6-b3e7-97eb44c08103)
![image](https://github.com/ultralytics/yolov5/assets/75561591/9a442283-1f65-4783-bec4-9d6a7c995d51)

### Additional

# it works correctly,and im willing to submit a PR! However,in my TFC3GhostBottlenecj class,i can not be absolutely sure if and how the "w" argument to  be passed in
## like this position (''<------")
```
class TFGhostBottleneck(keras.layers.Layer):
   # Ghost Bottleneck https://github.com/huawei-noah/ghostnet
   # w has w.conv and w.shortcut
    def __init__(self, c1, c2, k=3, s=1,w=None):
        """Initializes GhostBottleneck with ch_in `c1`, ch_out `c2`, kernel size `k`, stride `s`; see https://github.com/huawei-noah/ghostnet."""
        super().__init__()
        
        w1 = w.conv
        sc1 = w.shortcut
        wGConv = w1[0]
        wDWConv = w1[1]
        wGConv2 = w1[2]

        
        c_ = c2 // 2
        self.conv = keras.Sequential(
            [TFGhostConv(c1, c_, 1, 1,w=wGConv),  # pw
            TFDWConv(c_,c_,k,s,act=False) if s == 2 else  keras.layers.Lambda(tf.identity),  # dw   <-------
            TFGhostConv(c_, c2, 1, 1, act=False,w=wGConv2),
        ])  # pw-linear
        self.shortcut = (  <---------
            keras.Sequential(TFDWConv(c1, c1, k, s, act=False,w=sc1), TFConv(c1, c2, 1, 1, act=False,w=sc1)) if s == 2 else tf.identity
        )
```
# Can anyone have idea?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! 👋 It's fantastic to see your enthusiasm and willingness to contribute to the YOLOv5 project, especially with such an innovative approach integrating Ghost modules into TensorFlow export. Your detailed implementation and positive results are impressive!

Regarding your question on handling the "w" argument for weight passing in classes like `TFGhostBottleneck`, it's crucial to ensure that `w` is correctly structured and passed to accommodate the weights for each corresponding layer within the bottleneck.

The "w" parameter should represent the preloaded weights to be assigned to each layer within the `TFGhostBottleneck`. Its structure needs to mirror the architecture of your bottleneck, with `w.conv` and `w.shortcut` being dictionaries or containers themselves, holding the weights for the convolutional and shortcut paths respectively. 

Here’s a simplified approach:

1. Ensure `w` is a well-structured object with attributes or keys matching the layers it's meant for – in your case, `w.conv` for convolutional path weights and `w.shortcut` for shortcut path weights.

2. Each sub-attribute or key (e.g., `wGConv`, `wDWConv`, `wGConv2` for the conv path, and `sc1` for the shortcut path) should hold the specific weights for its corresponding layer.

3. When initializing each layer (e.g., `TFGhostConv`, `TFDWConv`), pass the relevant section of `w` directly. It seems you are already doing this, which is great!

In terms of ensuring correctness, extensive testing is key. Consider creating a small script to load weights into a model defined with your Ghost modules, perform a forward pass, and verify the output against expected results or the equivalence of the original model if applicable. This can help in identifying any mismatches or issues in weight passing.

Since you're willing to submit a PR, make sure to include comprehensive testing details to demonstrate the reliability and impact of your feature. The community greatly values contributions that are backed by solid testing and documentation. 🚀

It's contributions like yours that help push YOLOv5 and the whole community forward. Looking forward to seeing your PR; let's make YOLOv5 even better together! If you have any more questions or need further assistance, feel free to ask.
