### ISSUE TITLE
FP16推理TensorRT报错，使用python export.py --weights yolov5s.onnx --include engine --half --device 0

### ISSUE THREAD

**Issue by zmtttt** [ultralytics/yolov5#12932]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "/home/zhaomt/com/yolov5/export.py", line 652, in <module>
    main(opt)
  File "/home/zhaomt/com/yolov5/export.py", line 647, in main
    run(**vars(opt))
  File "/home/zhaomt/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaomt/com/yolov5/export.py", line 528, in run
    model = attempt_load(weights, device=device, inplace=True, fuse=True)  # load FP32 model
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaomt/com/yolov5/models/experimental.py", line 79, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaomt/anaconda3/lib/python3.11/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhaomt/anaconda3/lib/python3.11/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\x08'.

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you're encountering an issue with FP16 inference using TensorRT and encountered a `_pickle.UnpicklingError`. This error typically happens when there is an issue with the file being loaded, such as the file being corrupted or not fully downloaded.

In your case, the error during loading the `.onnx` model file suggests that the file might be corrupted or incomplete. 

Here's a quick suggestion to try:
1. Double-check if the `.onnx` model file is completely downloaded and is not corrupted. You might want to re-download the file or ensure it was correctly generated.
2. Ensure your environment is properly set up for exporting models with TensorRT and your PyTorch, and TensorRT installations are compatible and up to date.

If the issue persists after trying these steps, please provide more details, including the exact command you're using to generate the `.onnx` file, and we'll be happy to take another look. 🚀

For more guidance, the Ultralytics Docs have additional info and troubleshooting tips that might help.
