### ISSUE TITLE
augmentation in validation

### ISSUE THREAD

**Issue by BehdadSDP** [ultralytics/yolov5#12952]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello friends, 
I have a question about data augmentation. I know that in training phase, we may augment images and control these methods with some hyper parameters. but I want to know, Are these methods apply in validation phase, too? in my opinion the answer is negative.  maybe resize might apply on images. 
Thanks.

**Comment by glenn-jocher** [comment]
Hello! 🌟

You're right; typically, data augmentation methods are applied only during the training phase to help the model generalize better by providing a diverse set of samples. In the validation (and testing) phase, we generally do not apply these augmentations because we want to evaluate the model on the data as close to the original distribution as possible. Resize might be the only common transformation applied to validation data to match the input size expected by the model.

In YOLOv5, the validation phase does not use the extensive augmentation techniques applied during training, adhering to the standard practice of evaluating on unaltered data, aside from necessary resizing or scaling.

If you need to adjust validation transformations, you might look into the dataset configuration files but keep in mind the goal of validation is to assess performance under standard conditions.

Happy coding!
