### ISSUE TITLE
ModuleNotFoundError: No module named 'models.yolo' on custom trained weight. Is it a bug?

### ISSUE THREAD

**Issue by dilwolf** [ultralytics/yolov5#12999]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

After training the Yolov5 model on a custom dataset with `yolov5/train.py` in the repository for multi-gpu and loss_weight purposes, I am able to do inference with `yolov5/detect.py` in the repository. However, when I use the fine tuned weight with short code for customization, model is returning `ModuleNotFoundError:`. Below is my short Python script and error logging:

inference.py:
> from ultralytics import YOLO
model = YOLO("models/best.pt")
results = model.predict(source="videos/video.mp4", show=True, save=True)

**Error>>>>>:**

> WARNING ⚠️ models/best.pt appears to require 'models.yolo', which is not in ultralytics requirements.
AutoInstall will run now for 'models.yolo' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['models.yolo'] not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none)
ERROR: No matching distribution found for models.yolo
Retry 1/2 failed: Command 'pip install --no-cache "models.yolo" ' returned non-zero exit status 1.
requirements: AutoUpdate success ✅ 2.7s, installed 1 package: ['models.yolo']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

> Traceback (most recent call last):
   File "/home/imes-server2/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):

>  File "/home/user/Dilwolf/football_analysis/inference.py", line 3, in <module>
     model = YOLO('models/best_weighted.pt')
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/engine/model.py", line 151, in __init__
    self._load(model, task=task)
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/engine/model.py", line 240, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 806, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 752, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/home/user/anaconda3/envs/dilwolf/lib/python3.10/site-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

Tried restarting runtime and other installations, did not work....

### Additional

When I trained with `!yolo task=detect mode=train model=yolov5x.pt data=data.yaml epochs=100 imgsz=640` command on jupyter notebook, I am able to run fine tuned weight with my `inference.py`. Current `ultralystics==8.2.11` I also tried with little bit previous version of ultralytics but it did not help.

Furthermore, is it possible use mult-gpu, when I train with `!yolo task=detect .....` on jupter notebook? I tried `!yolo -m torch.distributed.run nproc_per_node=2 train.py batch=64 data=data.yaml --weights yolov5s.pt --device 0,1` but did not work?

Thanks in advance !!!

**Comment by glenn-jocher** [comment]
Hi there! 👋 It looks like you're encountering issues related to model package dependencies. From the error logs, it appears that the `models.yolo` module is being mistakenly required, which shouldn't be the case with the standard setup.

Please ensure you are using the latest version of YOLOv5 from the Ultralytics GitHub repository. If you've trained your model with a custom setup or modified version of YOLO, make sure all your imports and custom modules are correctly aligned with the Ultralytics library structures. 

For the multi-GPU training query, ensure you’re using the latest updates of YOLOv5 and PyTorch with correct syntax:

```bash
python -m torch.distributed.run --nproc_per_node=2 train.py --img 640 --batch 32 --epochs 100 --data data.yaml --weights yolov5s.pt --device 0,1
```

If issues persist, try retracing your steps or consider training a fresh model with the official scripts to see if the issue is ongoing. For further detailed guidance, please check the [docs](https://docs.ultralytics.com/yolov5/).

**Comment by dilwolf** [comment]
Hey there! Thank you so much for your help and effort on this. 

Today, I retrained my model again with fresh source code by cloning it after getting your response. I reinstalled `requirements.txt` in the official Yolov5 repository, which includes `ultralytics==8.2.13`. Again, it is returning the same error. 

It may seem very childish, but being meticulous may solve our error. Let me briefly explain what I did again today. 

I started cloning the official repo and fine tuned the pre-trained `yolov5x` model on my dataset. I trained using `yolov5/train.py` from yolov5 official repository. However,  when I use the trained weight with my short inference.py script, it's giving `ModuleNotFoundError`. I am curious it should work normally with the `YOLO` module when I call  `from ultralytics import YOLO`. Below is my inference script:

inference.py:

> from ultralytics import YOLO
model = YOLO("models/best.pt")
results = model.predict(source="videos/video.mp4", show=True, save=True)

Any help or suggestion are really appreciated !!!

**Comment by glenn-jocher** [comment]
Hello! 👋 Thank you for your detailed follow-up and the efforts you’ve put into resolving this issue.

The error you're encountering is quite peculiar, especially after following all the correct steps. Just to ensure that we're on the exact same page, the `YOLO` class is intended to work directly with the pre-trained models provided or ones trained using Ultralytics official scripts without modification.

Given your situation, here's a simple thing you can try:

- Make sure that you are importing everything correctly and from the expected directories. Occasionally, if there are nested directories or misspellings, Python can get tripped up on imports.

Here's a slightly modified script that makes sure the weights are being pointed to from the correct relative path:

```python
from ultralytics import YOLO

# Assuming your 'best.pt' is in the 'models' directory relative to your script
model = YOLO("./models/best.pt")
results = model.predict(source="videos/video.mp4", show=True, save=True)
```

Additionally, if this continues to fail, could you check the version of YOLOv5 directly in your environment to make certain it aligns with your operations? Sometimes, discrepancies in versioning can lead to unexpected issues.

If the problem persists, feel free to consult our [docs](https://docs.ultralytics.com/yolov5/) or respond here with any updates or further details. We'll find a solution together! 🚀

**Comment by dilwolf** [comment]
Thank you so much for your help on this issue!

As I mentioned earlier, I am using yolov5/train.py by customizing `cls_pw: [15, 0.1, 2]` in [data/hyps/hyp.scratch-low.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml) file for weighting loss for imbalanced dataset. I can easily use my fine-tuned weight with `predict.py`. However, I can not use my fine-tuned weight with `YOLO` class. The `YOLO` class just works fine with default pre-trained weight in the original repository. 

Today, I tried with latest version `ultralytics==8.2.16` but today it has got newtype of Error:

> Traceback (most recent call last):
  File "/home/dilwolf/my_projects/yolov5/inference.py", line 5, in <module>
    results = model.predict(source="input_videos/video.mp4", save=True)
  File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 446, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 297, in setup_model
    self.model = AutoBackend(
  File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 144, in __init__
    model = model.fuse(verbose=verbose)
TypeError: BaseModel.fuse() got an unexpected keyword argument 'verbose'


I am not using any kind of verbose function. 

inference.py:

```
from ultralytics import YOLO

# Assuming your 'best.pt' is in the 'models' directory relative to your script
model = YOLO("./models/best.pt")
results = model.predict(source="input_videos/video.mp4", save=True)
```

**Comment by dilwolf** [comment]
> Thank you so much for your help on this issue!
> 
> As I mentioned earlier, I am using yolov5/train.py by customizing `cls_pw: [15, 0.1, 2]` in [data/hyps/hyp.scratch-low.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml) file for weighting loss for imbalanced dataset. I can easily use my fine-tuned weight with `predict.py`. However, I can not use my fine-tuned weight with `YOLO` class. The `YOLO` class just works fine with default pre-trained weight in the original repository.
> 
> Today, I tried with latest version `ultralytics==8.2.16` but today it has got newtype of Error:
> 
> > Traceback (most recent call last):
> > File "/home/dilwolf/my_projects/yolov5/inference.py", line 5, in 
> > results = model.predict(source="input_videos/video.mp4", save=True)
> > File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 446, in predict
> > self.predictor.setup_model(model=self.model, verbose=is_cli)
> > File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 297, in setup_model
> > self.model = AutoBackend(
> > File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> > return func(*args, **kwargs)
> > File "/home/dilwolf/anaconda3/envs/yolo/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 144, in **init**
> > model = model.fuse(verbose=verbose)
> > TypeError: BaseModel.fuse() got an unexpected keyword argument 'verbose'
> 
> I am not using any kind of verbose function.
> 
> inference.py:
> 
> ```
> from ultralytics import YOLO
> 
> # Assuming your 'best.pt' is in the 'models' directory relative to your script
> model = YOLO("./models/best.pt")
> results = model.predict(source="input_videos/video.mp4", save=True)
> ```

I checked that I can not do this customization using yolo CLI. Because I can use fine-tuned weights using yolo CLI. Or is there a way to do the above `weighted_loss` custimization using YOLO CLI?

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like you're running into a fairly specific error after customizing and training your model. The error being thrown when using your custom-trained model with the `YOLO` class might indicate an incompatibility or an issue with how the custom weights were saved or loaded.

Since the issue arises specifically with customized training configurations and not with the default pre-trained weights, this suggests that the customization itself (i.e., weighting in the loss) might be modifying the model architecture or saved state in a way that isn't fully compatible with the current `YOLO` class handling.

Regarding the error with `unexpected keyword argument 'verbose'`, it seems like there might have been changes in the Ultralytics library that are causing this issue. Our team continuously updates the library, so checking the compatibility of different versions might help.

A temporary solution would be to use `predict.py` as it works without issues. However, pointing out these discrepancies is crucial for us to update and fix potential bugs in future releases.

For now, unfortunately, there isn't a direct way to implement this specific `weighted_loss` customization using the YOLO CLI without diving into the code and modifying the requisite parts as you have done.

Thanks for bringing this to attention, and we appreciate your input as it helps improve the tool! Let us know if there are any further details or changes, and we'll try to assist further! 🚀

**Comment by PrateekAbbi** [comment]
I am getting the same error but with YOLOv8. 

`WARNING ⚠️ models/flir_yolo.pt appears to require 'models.yolo', which is not in Ultralytics requirements.
AutoInstall will run now for 'models.yolo' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official Ultralytics model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['models.yolo'] not found, attempting AutoUpdate...`

**Comment by fardinabbasi** [comment]
### Description

I have trained a custom object detection model using the original YOLOv5 repository (`https://github.com/ultralytics/yolov5`). The training was successful and produced a `best.pt` file.

When I attempt to load and use this `best.pt` file within the newer `ultralytics` framework (specifically using `from ultralytics import YOLO`), I encounter an error. The error message indicates that the model requires a component or format that is not found in the `ultralytics` package.

### Steps to Reproduce

1.  **Clone and set up YOLOv5 repository:**
    ```bash
    git clone https://github.com/ultralytics/yolov5
    cd yolov5
    pip install -r requirements.txt
    ```

2.  **Train a custom model with YOLOv5:**
    ```bash
    python train.py --img 640 --batch 16 --epochs 50 --data custom_data.yaml --weights yolov5s.pt --name my_yolov5_model
    ```
    This successfully generates `runs/train/my_yolov5_model/weights/best.pt`.

3.  **Attempt to load the model using the `ultralytics` package:**
    ```python
    from ultralytics import YOLO

    # This assumes 'best.pt' is the path to the trained model
    model = YOLO('path/to/my_yolov5_model/weights/best.pt') 
    ```

### Expected Behavior

I expected the `ultralytics` package to be able to load and run inference on a `best.pt` model file trained by the original YOLOv5 repository, as `ultralytics` is a successor and provides support for various YOLO versions.

### Current Behavior

The attempt to load the model results in a `ModuleNotFoundError` and a warning about missing requirements:
`WARNING models/best.pt appears to require 'models.yolo', which is not in Ultralytics requirements.
AutoInstall will run now for 'models.yolo' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official Ultralytics model, i.e. 'yolo predict model=yolo11n.pt'`

`requirements: Ultralytics requirement ['models.yolo'] not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none)
ERROR: No matching distribution found for models.yolo
WARNING Retry 1/2 failed: Command 'pip install --no-cache-dir "models.yolo" ' returned non-zero exit status 1.`

### Possible Solutions/Suggestions

* Could there be a converter or an official method to migrate `best.pt` files from the original YOLOv5 repo to be compatible with the `ultralytics` framework?

Thank you for your help.

**Comment by pderrenger** [comment]
@fardinabbasi Thanks for the clear repro. YOLOv5 repo checkpoints (.pt) are Python pickles that reference YOLOv5 modules (e.g., models.yolo), so loading them with the ultralytics package isn’t guaranteed and can raise ModuleNotFoundError. Use the same repo for inference, or export from YOLOv5 and load the exported artifact in ultralytics, for example: in yolov5 run `python export.py --weights runs/train/my_yolov5_model/weights/best.pt --include onnx` then in ultralytics `from ultralytics import YOLO; model = YOLO('runs/train/my_yolov5_model/weights/best.onnx'); model.predict(...)`. There’s no official converter from YOLOv5 .pt to ultralytics PyTorch; for a unified API going forward, train directly with the ultralytics package (YOLO11 recommended).

**Comment by fardinabbasi** [comment]
Thanks for the clear explanation! However, the whole point is to do detection tracking. I want to use results = model.track(frame, **tracking_params) task from ultralytics. 
My finetuned YOLOv5 model cannot be replaced. I don't know what is the best way to do detection tracking considering that the model is finetuned on the old YOLOv5 repo.

**Comment by pderrenger** [comment]
@fardinabbasi You can use Ultralytics tracking with your YOLOv5 weights by exporting to ONNX, then calling track in ultralytics (your detector stays the same, only the runtime changes): in yolov5 run `python export.py --weights runs/train/my_yolov5_model/weights/best.pt --include onnx --simplify`, then in ultralytics use:
```python
from ultralytics import YOLO
model = YOLO('runs/train/my_yolov5_model/weights/best.onnx')  # requires onnxruntime(-gpu)
model.track(source='video.mp4', tracker='bytetrack.yaml', persist=True, save=True)
# per-frame: model.track(source=[frame], stream=True, tracker='bytetrack.yaml', persist=True)
```
See the Ultralytics tracking docs for details on ByteTrack/BoT-SORT settings and usage.
