### ISSUE TITLE
MESSES MY SYSTEM

### ISSUE THREAD

**Issue by Sequential-circuits** [ultralytics/yolov5#13038]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I cannot use this with a jetson xavier running jet pack 5.1 because it simply replaces the installed versions of torch and torchvision with the ones it wants

I cannot simply install torch and torchvision with pip in a jetson: I need to install especial packages from nvidia

I tried to remove those 2 in the requirements.txt and still installs them automatically, and it takes me a long time to fix the mess it does in my system!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 😊

It sounds like you're facing a challenge with the automatic installation of incompatible PyTorch versions on your Jetson Xavier. To prevent YOLOv5 from automatically installing or upgrading PyTorch and torchvision, you can modify the installation process slightly.

Instead of running the standard installation command, you can skip the automatic dependencies installation by using:

```bash
pip install --no-deps -e .
```

This command installs YOLOv5 without any dependencies. After that, you can manually install the necessary packages that are compatible with your system, as specified by NVIDIA for Jetson platforms.

If you need further customization, consider adjusting the `requirements.txt` file to better fit your environment before running any install commands.

Hope this helps you set up YOLOv5 on your Jetson Xavier without further issues! If you have more questions, feel free to ask. 🚀

**Comment by Sequential-circuits** [comment]
The problem is not during INSTALLATION, is during EXECUTION

As soon as it loads ultralytics, it starts to change torch and torchvision, among other things

And in jetson torchvision has to be compiled, so it ends up wasting a lot of time spent compiling it

It says for example:
_WARNING: Ignoring invalid distribution -orch (/usr/local/lib/python3.8/dist-packages)
Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0a0+41361538.nv23.6
[Info] [DepthPacketStreamParser] 20 packets were lost
    Uninstalling torch-2.1.0a0+41361538.nv23.6:
[Info] [DepthPacketStreamParser] 31 packets were lost
      Successfully uninstalled torch-2.1.0a0+41361538.nv23.6_

**Comment by glenn-jocher** [comment]
Hey there! 😊

It sounds like the issue arises due to the environment setup during the execution of YOLOv5, which triggers unwanted updates to `torch` and `torchvision`. This is likely due to dependency checks in the code.

To prevent this, you can try setting up a virtual environment specifically for running YOLOv5. This way, any changes or installations won't affect your global packages. Here’s how you can set it up:

1. Create a new virtual environment:
   ```bash
   python -m venv yolov5-env
   ```
2. Activate the environment:
   ```bash
   source yolov5-env/bin/activate
   ```
3. Install the specific versions of `torch` and `torchvision` that you compiled for Jetson:
   ```bash
   pip install <your-torch-wheel>
   pip install <your-torchvision-wheel>
   ```
4. Run YOLOv5 within this environment.

This should isolate the execution environment and prevent the automatic uninstallation and reinstallation of these packages. Let me know if this helps or if you encounter any other issues! 🚀

**Comment by Sequential-circuits** [comment]
That solved the problem thanks!

**Comment by glenn-jocher** [comment]
Hi there! 😊

I'm glad to hear that the solution worked for you! If you have any more questions or run into any other issues, feel free to reach out. The YOLO community and the Ultralytics team are always here to help.

Happy coding and best of luck with your projects! 🚀

Warm
