### ISSUE TITLE
Model size is doubled when exporting model to onnx/torchscript

### ISSUE THREAD

**Issue by nkhlS141** [ultralytics/yolov5#13065]
### Bug

My yolov5 model size was 92 mb. After exporting to onnx the onnx model file is of size 184mb. Why is that?

**Comment by glenn-jocher** [comment]
Hello,

The increase in file size when exporting YOLOv5 models to ONNX or TorchScript formats is expected due to the way these formats handle model serialization and include additional metadata for compatibility across different platforms and frameworks. ONNX and TorchScript often encapsulate more comprehensive graph representations and can include elements like fused operations and optimization data, which contribute to the larger file size.

If file size is a critical factor for your application, you might consider using the `--half` flag during export to convert the model weights to FP16, which can help reduce the file size significantly.

Feel free to explore further optimizations or reach out if you have more questions! 🚀
