### ISSUE TITLE
Add support for MLProgram 

### ISSUE THREAD

**Issue by Harryjeffs** [ultralytics/yolov5#13076]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Currently, converting a YOLOv5 model to CoreML with NMS results in a neural network. However, CoreMLTools v6.0 introduces a more performant and streamlined MLProgram type, used in YOLOv8. Can we backport MLProgram support for YOLOv5 models? This enhancement could provide significant performance improvements.

### Use case

With WWDC around the corner and an increased focus on AI/ML, having quicker access to more efficient models can enhance developer and user experience.

### Additional

https://apple.github.io/coremltools/docs-guides/source/comparing-ml-programs-and-neural-networks.html

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your suggestion and for your willingness to contribute to the YOLOv5 project! The introduction of MLProgram support in CoreMLTools v6.0 indeed presents an exciting opportunity for performance improvements.

To proceed effectively, here are a few steps we can take:

1. **Reproducible Example**: If you have a minimum reproducible code example that demonstrates the current conversion process and highlights any limitations or issues, please share it. This will help us understand the context better and ensure we can reproduce and address any potential bugs. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

2. **Version Check**: Ensure you are using the latest versions of `torch` and the YOLOv5 repository. This helps us confirm that any issues or enhancements are based on the most current codebase. If you haven't updated recently, please do so and try the conversion again.

3. **PR Submission**: Since you are interested in submitting a PR, we encourage you to start by forking the repository and creating a new branch for your changes. Once you have a working implementation, you can submit a PR for review. Make sure to include detailed documentation and any necessary tests to validate the new functionality.

Here is a basic outline to get you started with the conversion process using CoreMLTools v6.0:

```python
import coremltools as ct
import torch
from models.common import DetectMultiBackend

# Load YOLOv5 model
model = DetectMultiBackend('yolov5s.pt', device='cpu')

# Convert to CoreML
input_shape = (1, 3, 640, 640)  # Example input shape
dummy_input = torch.zeros(input_shape)
traced_model = torch.jit.trace(model, dummy_input)

# Convert to CoreML with MLProgram
mlmodel = ct.convert(
    traced_model,
    inputs=[ct.TensorType(shape=input_shape)],
    convert_to="mlprogram"
)

# Save the CoreML model
mlmodel.save("yolov5s_mlprogram.mlmodel")
```

Feel free to adjust the code as needed and share any findings or improvements you make. The YOLO community and the Ultralytics team are here to support you throughout the process.

Looking forward to your contribution!
