### ISSUE TITLE
'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by HouNAiL** [ultralytics/yolov5#13125]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Traceback (most recent call last):
  File "/home/hounl/Data/yolov5/train.py", line 848, in <module>
    main(opt)
  File "/home/hounl/Data/yolov5/train.py", line 623, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/hounl/Data/yolov5/train.py", line 383, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/data1/hounl/yolov5/utils/loss.py", line 139, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/data1/hounl/yolov5/utils/loss.py", line 218, in build_targets
    anchors, shape = self.anchors[i], p[i].shape
AttributeError: 'list' object has no attribute 'shape'

### Minimal Reproducible Example

   for i in range(self.nl):
            anchors, shape = self.anchors[i], p[i].shape
            gain[2:6] = torch.tensor(shape)[[3, 2, 3, 2]]  # xyxy gain

            # Match targets to anchors
            t = targets * gain  # shape(3,n,7)
            if nt:
                # Matches
                r = t[..., 4:6] / anchors[:, None]  # wh ratio
                j = torch.max(r, 1 / r).max(2)[0] < self.hyp["anchor_t"]  # compare
                # j = wh_iou(anchors, t[:, 4:6]) > model.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))
                t = t[j]  # filter

                # Offsets
                gxy = t[:, 2:4]  # grid xy
                gxi = gain[[2, 3]] - gxy  # inverse
                j, k = ((gxy % 1 < g) & (gxy > 1)).T
                l, m = ((gxi % 1 < g) & (gxi > 1)).T
                j = torch.stack((torch.ones_like(j), j, k, l, m))
                t = t.repeat((5, 1, 1))[j]
                offsets = (torch.zeros_like(gxy)[None] + off[:, None])[j]
            else:
                t = targets[0]
                offsets = 0

            # Define
            bc, gxy, gwh, a = t.chunk(4, 1)  # (image, class), grid xy, grid wh, anchors
            a, (b, c) = a.long().view(-1), bc.long().T  # anchors, image, class
            gij = (gxy - offsets).long()
            gi, gj = gij.T  # grid indices

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @HouNAiL,

Thank you for your detailed bug report and for your willingness to contribute a PR! The error you're encountering, `'list' object has no attribute 'shape'`, suggests that one of the elements in your list `p` is not a tensor, which is causing the issue when trying to access the `shape` attribute.

To help us investigate further, could you please provide a minimal reproducible example? This will allow us to replicate the issue on our end and identify the root cause more effectively. You can find guidelines for creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and the YOLOv5 repository. Sometimes, issues are resolved in newer releases, and updating might resolve your problem.

Here's a quick checklist to help us move forward:
1. **Minimal Reproducible Example**: Provide a snippet of code that reproduces the issue.
2. **Environment Details**: Share the versions of `torch`, YOLOv5, and any other relevant libraries.
3. **Latest Versions**: Confirm that you have tested with the latest versions of `torch` and YOLOv5.

Once we have this information, we can dive deeper into the issue. Thank you for your cooperation and for being a part of the YOLO community!
