### ISSUE TITLE
Setting up confidence threshold while training

### ISSUE THREAD

**Issue by prasen832** [ultralytics/yolov5#13166]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to setup confidence threshold while training yolov5 for segmentation ?

**Comment by glenn-jocher** [comment]
@prasen832 hello,

Thank you for your question and for checking the existing issues and discussions! Setting up the confidence threshold is typically done during inference rather than training. However, if you want to adjust the confidence threshold for evaluating your model during training, you can modify the `conf` parameter in the YOLOv5 configuration.

Here's how you can set the confidence threshold during inference:

```python
import torch

# Load the model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Set the confidence threshold
model.conf = 0.25  # NMS confidence threshold

# Perform inference
results = model('path/to/your/image.jpg')
```

For segmentation tasks, you can follow a similar approach. If you are training a segmentation model, you might want to ensure that your evaluation metrics reflect the desired confidence threshold. 

If you are encountering issues or have specific requirements during training, please provide a minimum reproducible example so we can better assist you. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, make sure you are using the latest versions of `torch` and the YOLOv5 repository to avoid any outdated issues.

Feel free to reach out if you have any more questions or need further assistance. 😊
