### ISSUE TITLE
image size argument question

### ISSUE THREAD

**Issue by berkantay** [ultralytics/yolov5#1326]
## ❔Question

Hi, in the yaml file we provided for the train labels and test labels  and their ratio is 0.7 to 0.3 but when I run the train script i see

```
Analyzing anchors... anchors/target = 5.26, Best Possible Recall (BPR) = 1.0000
Image sizes 1024 train, 1024 test
Using 4 dataloader workers
Logging results to runs/train/exp3
Starting training for 100 epochs...


```
image sizes 1024 train,1024 test what does this mean

## Additional context

I do not have even 1024 test images just 964? I need some enlighting description

**Comment by nanometer34688** [comment]
1024 is the size of the input to your model. E.g. 1024x1024.

You can change the input size by using 

`python3 train.py --img-size 640`

This will resize images to 640x640

**Comment by berkantay** [comment]
Oh I see, thats how i understood  at first but then I confused. Maybe this output can be clarified.

**Comment by berkantay** [comment]
Yes it is. Input image size in pixels.

**Comment by Mrinh212375** [comment]
@berkantay ,hey bro I'm getting confused between Image size and image resolution, like suppose during both training and testing in the --img-size argument whatever value I'll give, it'll resize the image accordingly, but is it safe to tell resolution of the image, because it's more like dimension(in pixel), resolution will be like 96dpi,......something in dpi.

416 * 416 is image size in pixels(dimension), Can we say this as image resolution, please share ur thought on this, I'll be really appreciate.

**Comment by berkantay** [comment]
@Mrinh212375 my experience with yolov5 is a bit rusty but as far as I remember `--img-size` stands for the input size of the model, which means it will also scale down your image according to the value. Let's say you have 1920 x 1080 sized labeled data to fed to the model when you pass `--img-size = 640` for train command it will resize the images into 640x640 pixels. However it may not be the same for resolution. 

To clarify, basically you can check it by saving the resized image and comparing on training loop.

Hope this answer helps you? 

Note for myself: I think I should edit the response below. Because you were asked if it is the resolution or not. Nope it is the size of the image which will be resized.



> Yes it is. Input image size in pixels.

**Comment by Mrinh212375** [comment]
@berkantay so, it would be safe to call this image size rather than image resolution ??

actually I've trained a dataset by 416*416, Now my guide told me to find out the lowest resolution of detection(before No detection), I've got 64*64, after that there is no detection, My target is 16*16 as per instructed by my guide, Now this is size but then why is it being called resolution, I can't understand.

**Comment by berkantay** [comment]
Your guide may mean size of the image by resolution, I think you should clarify this issue with him/her.

**Comment by glenn-jocher** [comment]
--imgsz is the image size in pixels, i.e. --imgsz 640
