### ISSUE TITLE
Silicon Mac GPU Support for training

### ISSUE THREAD

**Issue by oliver408i** [ultralytics/yolov5#13279]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello. I have set up and trained my first model with Yolov5s (object detection) and I'm enjoying it so far. However, my training is quite slow on my macbook pro (m2 cpu/gpu). Logs says
`YOLOv5 🚀 v7.0-358-gc07b9a8b Python-3.12.3 torch-2.4.0 CPU`

I saw other posts regarding gpu acceleration on mac, but I didn't find any related to the training process. Currently, only my CPU is hitting <90% usage (total) while my GPU is pretty much idle. Training 30 epochs of a ~100 image dataset takes almost an hour. I used to use mediapipe and tflite, which trains the same dataset (30 epochs) in about 5 minutes. The `train.py` code only has options for `cuda` and `cpu`. I know that metal gpus is `mps`, but I'm not sure if I can just replace the device type with mps and call it a day.

**Comment by glenn-jocher** [comment]
@oliver408i hello! Currently, YOLOv5 does not natively support GPU acceleration on macOS using the M1/M2 chips with Metal Performance Shaders (MPS). The training process defaults to CPU on macOS, which is why you're experiencing slower training times. For faster training, consider using a Linux-based system with CUDA-enabled GPUs or leveraging cloud-based solutions like Google Cloud or AWS. For more details, you can refer to our [Multi-GPU Training documentation](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/).
