### ISSUE TITLE
live streaming video

### ISSUE THREAD

**Issue by tabarkarajab** [ultralytics/yolov5#1330]
how we can use live streaming video with this code? I'm getting issue with live streaming

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/yolov5#inference

```bash 
$ python detect.py --source http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8

Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, name='', save_conf=False, save_dir='runs/detect', save_txt=False, source='http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8', update=False, view_img=False, weights='yolov5s.pt')
Using torch 1.6.0 CPU

Fusing layers... 
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients, 17.5 GFLOPS
1/1: http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8...  success (1280x720 at 25.00 FPS).

0: 384x640 1 persons, 1 ties, Done. (0.211s)
0: 384x640 1 persons, 1 ties, Done. (0.198s)
0: 384x640 1 persons, 1 ties, Done. (0.192s)
0: 384x640 1 persons, 1 ties, Done. (0.191s)
0: 384x640 1 persons, 1 ties, Done. (0.192s)
0: 384x640 1 persons, 1 ties, Done. (0.192s)
0: 384x640 1 persons, 1 ties, Done. (0.193s)
0: 384x640 1 persons, 1 ties, Done. (0.189s)
0: 384x640 1 persons, 1 ties, Done. (0.189s)
0: 384x640 1 persons, 1 ties, Done. (0.188s)
0: 384x640 1 persons, 1 ties, Done. (0.189s)
...
```

**Comment by tabarkarajab** [comment]
hi, I'm getting this error now, looks like the object isn't supporting here?


 dataset = LoadStreams(webcam, img_size=imgsz)
  File "/home/lg/Downloads/yolov5-3.1/utils/datasets.py", line 272, in __init__
    cap = cv2.VideoCapture(eval(s) if s.isnumeric() else s)
AttributeError: 'bool' object has no attribute 'isnumeric'

**Comment by glenn-jocher** [comment]
@tabarkarajab Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and then install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by skyprince999** [comment]
@tabarkarajab - were you able to solve it.

**Comment by tabarkarajab** [comment]
Yes @skyprince999
