### ISSUE TITLE
Adding tracker after detection

### ISSUE THREAD

**Issue by berkantay** [ultralytics/yolov5#1331]
## ❔Question

First of all thanks for this repository, it is completely useful. I have reached the accuracy and the performance of detection for my specific case. Now my aim is to embed some tracking algorithm just after detection. How can I get the bounding box coordinates. I am planning to pass those coordinates to the tracker when detection is occured.

**Comment by glenn-jocher** [comment]
See https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading

```python
import torch
from PIL import Image

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).fuse().eval()  # yolov5s.pt
model = model.autoshape()  # for autoshaping of PIL/cv2/np inputs and NMS

# Images
img = Image.open('data/images/zidane.jpg')  # PIL image

# Inference
prediction = model(img)
```

**Comment by shashi7679** [comment]
@glenn-jocher Hi... I am trying to do inference in my own way, using the torchscript file trained on my custom dataset.
When I am using the method for inference, I am getting prediction as a tuple consisting of a tensor of size (1 X 25200 X 85).

Now how to get xmin, xmax, ymin, ymax from this point.

I have been following this (https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading#issuecomment-695146444) approach for inference.

Please help me out.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@shashi7679 sorry for the confusion. PyTorch Hub YOLOv5 models treat torch inputs as pass-throughs, so no pre or post processing is performed on torch inputs.

If you want a results object then please pass numpy arrays, PIL, cv2, file paths, etc.

**Comment by shashi7679** [comment]
@glenn-jocher But when I am passing array/PIL/cv2.. I am getting this error.

RuntimeError: forward() Expected a value of type 'Tensor' for argument 'x' but instead found type 'JpegImageFile'.
Position: 1
Value: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1796x2717 at 0x21D086F19A0>
Declaration: forward(__torch__.models.yolo.Model self, Tensor x) -> ((Tensor))
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

**Comment by glenn-jocher** [comment]
@shashi7679 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
