### ISSUE TITLE
when i train my datasets how to prepared the data.now the error is cant find labels

### ISSUE THREAD

**Issue by yunchangxiaoguan** [ultralytics/yolov5#145]
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    train(hyp)
  File "train.py", line 163, in train
    single_cls=opt.single_cls)
  File "/home/guanxiao/project/yolov5/utils/datasets.py", line 405, in __init__
    assert nf > 0 or n == 20288, 'No labels found in %s. See %s' % (os.path.dirname(file) + os.sep, help_url)
AssertionError: No labels found in data/labels/. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

I have try many way to prepare the data,like same as the https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data write place my floder,but all error

**Comment by glenn-jocher** [comment]
@yunchangxiaoguan perhaps this blog might help you:
https://blog.roboflow.ai/how-to-train-yolov5-on-a-custom-dataset/

**Comment by shaoxiang** [comment]
@yunchangxiaoguan You need to check your label format carefully!
I also encountered the same problem, and finally I found that my label format was like this
0,0.5590995,0.108125,0.02814300000000003,0.474421
But it should be
0 0.5590995 0.108125 0.02814300000000003 0.474421

**Comment by weilanShi** [comment]
> Traceback (most recent call last):
> File "train.py", line 405, in
> train(hyp)
> File "train.py", line 163, in train
> single_cls=opt.single_cls)
> File "/home/guanxiao/project/yolov5/utils/datasets.py", line 405, in **init**
> assert nf > 0 or n == 20288, 'No labels found in %s. See %s' % (os.path.dirname(file) + os.sep, help_url)
> AssertionError: No labels found in data/labels/. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
> 
> I have try many way to prepare the data,like same as the https://docs.ultralytics.com/yolov5/tutorials/train_custom_data write place my floder,but all error

如果在生成train.txt时，生成的是相对路径，如：images/1102.jpg，则在训练时应把labels 和 images文件夹拷贝至yolov5-master 文件夹下，否则报错：nf > 0 or n == 20288, 'No labels found in %s. See %s' % (os.path.dirname(file) + os.sep, help_url)，意思为找不到labels；如果在生成train.txt时，生成的是绝对路径，如：home/yolov5-master/data/Voc2017/images/1102.jpg,则需将utils/datasets.py 第271行处 f = [x.replace('./', parent)更改为f = [x.replace(parent, parent)，这样改就不需要将labels 和images文件夹拷贝至yolov5-master 文件夹下

**Comment by ghost** [comment]
after the update, I'm facing the same problem.
Followed the Train-custom-data instruction but didn't work.
everything was working on previously built any solutions?
my error is:
 line 463, in __init__
    assert not augment, '%s. Can not train without labels.' % s
AssertionError: WARNING: No labels found in ..\train\labels\. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data. Can not train without labels.
WARNING: No labels found in ..\train\labels\. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by glenn-jocher** [comment]
@asim266 this issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and then install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by ghost** [comment]
@glenn-jocher  I used coco128.yaml and it worked perfectly fine but when I use a custom dataset and with the same format as coco128. It shows an error.
![image](https://user-images.githubusercontent.com/74567784/99399951-30cab400-2908-11eb-995f-23da4b002ad0.png)
Please let me know if I'm missing anything. Because coco128 and coco are working fine but on a custom dataset I'm facing this error.
Thanks

**Comment by glenn-jocher** [comment]
@asim266 you have a dataset issue. You should ensure your dataset matches the layout of COCO and COCO128. This is explained in the Custom Training Tutorial:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by ghost** [comment]
@glenn-jocher I have use this dataset for previous built and that works fine.
I'm using roboflow to generate yolov5 pytorch dataset.

**Comment by glenn-jocher** [comment]
@asim266 you may want to git pull and try everything again, there was a recent Roboflow-related PR here:
https://github.com/ultralytics/yolov5/pull/1414

**Comment by ghost** [comment]
@glenn-jocher issue has been solved thank you

**Comment by shivagur** [comment]
> @glenn-jocher issue has been solved thank you

Bro i am also facing same issue .. can you help me with this
