### ISSUE TITLE
ERROR When ensemble yolov3 and yolov5x

### ISSUE THREAD

**Issue by PromiseXu1** [ultralytics/yolov5#1476]
## ❔Question
**The first best.pt is yolov5x and the second is yolov3-spp , when i only use yolov5x to detect it runs normally, but error encounter when ensemble the two models , can you tell me the reason please? thanks very much.**

python detect.py --weights runs/train/exp13/weights/best.pt /home/work/pretrained_weights/best.pt --source /home/work/data

Fusing layers... 
Model Summary: 484 layers, 88390614 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 172, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/work/xunuo/yolov5/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'float'

**Comment by glenn-jocher** [comment]
@PromiseXu1 your YOLOv3-SPP model seems to be of a different structure than the official ultralytics models. For a quick fix I would simply ensemble YOLOvl instead.

I answered this on a different thread, but these two are not ensemble-able due to different head shapes without modifying the ensemble type in models.experimental.Ensemble() to 'nms method'.

**Comment by PromiseXu1** [comment]
@glenn-jocher  I will try , thank you very much!
