### ISSUE TITLE
Increasing dataset size with augmentation

### ISSUE THREAD

**Issue by ilyalasy** [ultralytics/yolov5#1486]
## ❔Question
Is it possible to increase input dataset size by using augmentation? As far as I understand the code, all images are augmented according to hyperparameters, but is it possible to use unaugmented dataset as well as augmented copy of it for model training?

## Additional context
I think, it is an easy way to artificially increase a dataset size and I wonder why it is not implemented (or maybe I haven't found this option)

**Comment by glenn-jocher** [comment]
@Misterion777 I've answered this question multiple times here before so I'll be very clear:

**It is impossible to increase your data without collecting new data.** If I show you a 10 euro bill, and then rotate it 90 degrees and show it to you again, I have not shown you 20 euros.

Some platforms pretend to offer you gimmicks such as offline dataset augmentation to 'increase your data' because they either don't understand augmentation or their customers don't or both. YOLOv5, and all other competent training architectures use online augmentation of images that produce an **infinite combination of randomly augmented images**. Images are augmented randomly over uniformly sampled hyperparameter distributions inside the dataloader at runtime. This means that **the same image is never seen twice during training**, irrespective of how long you train. Ergo, you gain nothing by augmenting it offline and adding it to your dataset. The correct way to implement augmentation is online randomly sampled, never saving images offline.

**Comment by ZJU-lishuang** [comment]
I'm interesting in the sentence "the same image is never seen twice during training".
Can you explain it in detail?

**Comment by ilyalasy** [comment]
@glenn-jocher I am sorry for my lack of knowledge, but isn't a 10 euro bill and 90 degrees rotated bill is not the same for neural network? Yes, the same image is never seen twice, but if we will use original dataset and an augmented copy of it (or even augment the same image twice), will there twice as more unique samples for network?
I am sorry again for maybe silly questions, but it really clashes with my knowledge on augmentation.

**Comment by glenn-jocher** [comment]
The dataset is never seen during training. Augmented **views** of the dataset are created on demand in the YOLOv5 dataloader and used for training **once**. These augmented views are never repeated twice, even if you train for a million years. The dataset does not grow in size, **there is no new data**. This is dataloader/augmentation 101, it's very simple.

![Screenshot 2020-11-25 at 13 14 14](https://user-images.githubusercontent.com/26833433/100226555-346dc480-2f20-11eb-9e8e-9c552b19f7d5.jpg)

**Comment by hissaanscorecarts** [comment]
@glenn-jocher what if we want to include the original and the augmented samples in the dataset ?

**Comment by CHEBATERIO** [comment]
> The dataset is never seen during training. Augmented **views** of the dataset are created on demand in the YOLOv5 dataloader and used for training **once**. These augmented views are never repeated twice, even if you train for a million years. The dataset does not grow in size, **there is no new data**. This is dataloader/augmentation 101, it's very simple.
> 
> ![Screenshot 2020-11-25 at 13 14 14](https://user-images.githubusercontent.com/26833433/100226555-346dc480-2f20-11eb-9e8e-9c552b19f7d5.jpg)

so i hope im not bein annoying but this means, that if i have 100 pictures for every class in my data set, and i need 1000 pictures for every class, i still need to find 900 for every class? or i can hope o configure if its possible the training so evrery picture in my dataset is morphed in 10 different ways?

**Comment by pderrenger** [comment]
YOLOv5 already does what you’re describing: each time an image is loaded it’s randomly augmented on-the-fly (so across epochs your 100 originals are seen in many different “morphed” views without you generating 900 extra files), and if you want stronger/weaker effects you can tune the augmentation hyperparameters in the `data/hyps/hyp.scratch-*.yaml` you train with, but augmentation still can’t fully substitute for collecting more truly diverse real images; see the [Ultralytics Data Augmentation glossary](https://www.ultralytics.com/glossary/data-augmentation) for context.
