### ISSUE TITLE
Multi GPU RuntimeError: Expected device cuda:0 but got device cuda:7

### ISSUE THREAD

**Issue by zidanexu** [ultralytics/yolov5#15]
hi @glenn-jocher  
I try to reproduce training result. 
![image](https://user-images.githubusercontent.com/54395639/83750664-3143fb00-a698-11ea-9c5e-f320c9a0bed8.png)
using command above ,     8 GPU Tela P40.  
when finish 1 epoch training., The test process  broken.
![image](https://user-images.githubusercontent.com/54395639/83750823-7405d300-a698-11ea-8e33-e9d2cd9e32a2.png)

**Comment by glenn-jocher** [comment]
@zidanexu thank you for your bug report. We can successfully reproduce this issue. It appears to be caused by self.grid, a Detect() layer list, which is sent to a device during training. It is not transferred like normal parameters/buffers because it is not in the layer buffer list as it is a list rather than a tensor. We will look into this.

**Comment by glenn-jocher** [comment]
Fix complete. git pull to receive fix.
<img width="1169" alt="Screen Shot 2020-06-04 at 3 19 41 PM" src="https://user-images.githubusercontent.com/26833433/83816545-802d6880-a677-11ea-8db8-d2f9140df5f5.png">

**Comment by lucasjinreal** [comment]
this error still exists on multi GPU training. on pytorch 1.5

```
RuntimeError: Model replicas must have an equal number of parameters.

```

it seems not fix yet, any ideas?
