### ISSUE TITLE
Resume training with custom dataset with yolov5

### ISSUE THREAD

**Issue by nisarggandhewar** [ultralytics/yolov5#1560]
Suppose I want to train my model for 4000 epoch but after executing 500 epoch, I want to resume training from 501, how to resume training again. 
As in Yolov4, weights are saved after every 100 epoch, and in configuration file number of epochs are mention, So using saved weight we can continue training from 501 iteration.

**Comment by glenn-jocher** [comment]
@nisarggandhewar 

```bash
cd yolov5
python train.py --resume
```

**Comment by yarazakii** [comment]
> @nisarggandhewar
> 
> ```shell
> cd yolov5
> python train.py --resume
> ```

I have tried to use it but it gives me this error
 File "train.py", line 456, in <module>
    opt = argparse.Namespace(**yaml.load(f, Loader=yaml.FullLoader))  # replace
AttributeError: module 'yaml' has no attribute 'FullLoader'
Can you help me with it please?

**Comment by glenn-jocher** [comment]
@yarazakii you are not meeting dependency requirements.

**Comment by RoyCopter** [comment]
> @nisarggandhewar
> 
> ```shell
> cd yolov5
> python train.py --resume
> ```

is the resume know how much batchsize I was setting and it takes the best.pt/last.pt ? 
because when it loads the model it writes the default paramaters as batchsize=16 and weights=yolov5m.pt for example instead what I did in practice when the train begin.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by hamid-mp** [comment]
Hi, I wanted to resume my training with multi-gpu (5 GPU) and I am receiving this error.
I ran:
`python -m torch.distributed.run --nproc_per_node 5 train.py --resume`
here is the error:

Traceback (most recent call last):
  File "train.py", line 515, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 158, in train
    assert start_epoch > 0, '%s training to %g epochs is finished, nothing to resume.' % (weights, epochs)
AssertionError: ./runs/train/exp/weights/last.pt training to 250 epochs is finished, nothing to resume.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2942341 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2942342 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2942343 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2942344 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 4 (pid: 2942345) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 


============================================================


train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-11_13:13:29
  host      : user-SYS-4029GP-TRT2
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2942345)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by glenn-jocher** [comment]
@hamid-mp 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/train.py#L175-L181) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="Screenshot 2022-04-10 at 11 11 51" src="https://user-images.githubusercontent.com/26833433/162611202-4e0b611f-6cca-4e43-94fc-bbc44e6447f8.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by karl-gardner** [comment]
Hello @glenn-jocher When you use the learning rate scheduler to resume training does this also take into account the patience level where it stops after a certain amount of epochs past after the best epoch?

Thanks,

Karl Gardner

**Comment by glenn-jocher** [comment]
@karl-gardner no, the patience stopper is not saved in each checkpoint, so if you resume patience resets from that epoch.

**Comment by glenn-jocher** [comment]
@zy597337447 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/train.py#L175-L181) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="Screenshot 2022-04-10 at 11 11 51" src="https://user-images.githubusercontent.com/26833433/162611202-4e0b611f-6cca-4e43-94fc-bbc44e6447f8.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by TheArmbreaker** [comment]
Hello @glenn-jocher ,

when starting training from a fully trained model, will a best.pt be generated even if the originally trained model is better?

We use [P ,R ,mAP50 ,mAP50-95] with [0,0,0.1,0.9] standard weights.
We **start from a model** with [0.837, 0.628, 0.653, 0.383] --> 0.41
And we **get a best.pt** for [0.878, 0.568, 0.621, 0.378] --> 0.4023

According to [Issue #582](https://github.com/ultralytics/yolov5/issues/582) "What's the difference between last.pt&best.pt", I would expect that there won't be a best.pt.

However, a best.pt is generated. Probably because of missing epoch information?

Your support is hugely appreciated.

**Further context from other tests**
best.pt is also generated when forcing a ridiculously terrible model with epoch 1, batch 1 and reducing the img size from 1280 to 224.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/aa542ce6a65658ff931fee9bbab77c0145c152f0/train.py#L175-L181) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="Screenshot 2022-04-10 at 11 11 51" src="https://user-images.githubusercontent.com/26833433/162611202-4e0b611f-6cca-4e43-94fc-bbc44e6447f8.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck 🍀 and let us know if you have any other questions!

**Comment by yithong1216** [comment]
Hello glenn-jocher, I am working on training a custom dataset for 100 epochs on yolov7 on google colabs (All dataset and weights stored in Google Drive). The training process was somehow interrupted and stopped at epoch 86. I tried to resume the training but it gives me the error below:

google colab prompt: !python train.py --weights ./runs/train/yolov7_epoch_200_1005/weights/last.pt --resume 

error:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/yolov7/train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "/content/gdrive/MyDrive/yolov7/train.py", line 71, in train
    run_id = torch.load(weights, map_location=device).get('wandb_id') if weights.endswith('.pt') and os.path.isfile(weights) else None
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: PytorchStreamReader failed locating file data/2: file not found.

**Comment by yithong1216** [comment]
> Hello glenn-jocher, I am working on training a custom dataset for 100 epochs on yolov7 on google colabs (All dataset and weights stored in Google Drive). The training process was somehow interrupted and stopped at epoch 86. I tried to resume the training but it gives me the error below:
> 
> google colab prompt: !python train.py --weights ./runs/train/yolov7_epoch_200_1005/weights/last.pt --resume
> 
> error: Traceback (most recent call last): File "/content/gdrive/MyDrive/yolov7/train.py", line 616, in train(hyp, opt, device, tb_writer) File "/content/gdrive/MyDrive/yolov7/train.py", line 71, in train run_id = torch.load(weights, map_location=device).get('wandb_id') if weights.endswith('.pt') and os.path.isfile(weights) else None File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 789, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1131, in _load result = unpickler.load() File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1101, in persistent_load load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location)) File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1079, in load_tensor storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped() RuntimeError: PytorchStreamReader failed locating file data/2: file not found.

I just trained on the saved pretrained model epoch_075.pt, and not using '--resume' prompt, I just trained another 25 epoch to finish 100 epochs, 
!python train.py --weights ./runs/train/yolov7_epoch_200_1005/weights/epoch_074.pt --epochs 25, 

the training works fine and I found the 'results.txt' file containing the training result data of previous 75 training epochs, is it fine to just train on the epoch_075.pt model instead epoch_last.pt model.

**Comment by glenn-jocher** [comment]
@yithong1216 hi there! Resuming training without using the `--resume` flag can lead to problems, such as the one you encountered with the missing data file. Using `--resume` ensures proper continuation of training from the last checkpoint.

You've successfully trained for an additional 25 epochs starting from `epoch_074.pt` and obtained the training results. It's absolutely fine to proceed with training from `epoch_074.pt` instead of `last.pt`. The `results.txt` file contains the training results from the previous 75 epochs, so using `epoch_075.pt` as a starting point for the next 25 epochs is a valid approach.

If you encounter any issues or have further questions, feel free to ask. Good luck with your training!
