### ISSUE TITLE
Inference Yolo using ONNX

### ISSUE THREAD

**Issue by duongvvuet** [ultralytics/yolov5#1651]
## ❔Question
I trained a yolo model and convert to ONNX using the command:
```bash
$ export PYTHONPATH="$PWD" && python models/export.py --weights ./weights/yolov5s.pt --img 480 --batch 1
```
I inference with `.pt` and `.onnx` model. But the output of 2 models is different. Type of `.pt` model `<class 'torch.Tensor'>` and shape `torch.Size([1, 9450, 6])`, with `.onnx` model is are `<class 'numpy.ndarray'>` and `(1, 3, 60, 60, 6)`.

**Am I doing it wrong?**

**Comment by souviksv** [comment]
Facing same problem..

**Comment by s-nesterov** [comment]
I'm facing the same problem now. This problem was partially solved here https://github.com/ultralytics/yolov5/issues/343#issuecomment-662156461. This is a working script, but you will have to configure some parameters for your task: the number class + class names, the size of the input image, and I had to have only small anchors in the predictions (because there were a lot of false positives). And be careful with imports - in begin demo_onnx.py: from utils.utils import non_max_suppression - I copypast this function from release Yolov5 - utils.general.py, function - non_max_suppression.
