### ISSUE TITLE
gbk error. How can I solve it?

### ISSUE THREAD

**Issue by Krasjet-Yu** [ultralytics/yolov5#1669]
Traceback (most recent call last):
  File "train.py", line 504, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 70, in train
    data_dict = yaml.load(f, Loader=yaml.FullLoader)  # data dict
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Anaconda3\envs\pytorch-gpu\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 429: illegal multibyte sequence

**Comment by wudashuo** [comment]
Looks like your yaml file is encoding with gbk, use utf-8 instead.
编程一定要注意编码格式，gbk和gb2312要避免使用，统一使用utf-8

**Comment by ilem777** [comment]
Just don't have Chinese in the yaml file

**Comment by helloworldbyqiqi** [comment]
I have the same problem, change to the source code format is also a problem.Have you solved the problem?

**Comment by glenn-jocher** [comment]
@helloworldbyqiqi hello! Thank you for bringing up this issue. The error you are encountering seems to be related to the encoding format of your YAML file. It is recommended to use UTF-8 encoding instead of GBK or GB2312. 

Fortunately, the YOLOv5 repository supports UTF-8 encoding, which is the default encoding for most programming languages and text editors. You can change the encoding format of your YAML file by saving it with UTF-8 encoding. 

If you are still facing any issues after changing the encoding format, please provide more details about your problem, such as specific error messages or code snippets. This will help us in assisting you further.

**Comment by helloworldbyqiqi** [comment]
@glenn-jocher Thank you very much for your answer. My problem has been solved. As you said is the file encoding format problem, after the change of the problem the code can run normally!

**Comment by glenn-jocher** [comment]
@helloworldbyqiqi you're welcome! I'm glad to hear that your issue has been resolved. If you have any further questions or need any assistance in the future, feel free to ask. The YOLOv5 community and the Ultralytics team are always here to help. Happy coding!
