### ISSUE TITLE
Inference time vs. img_size

### ISSUE THREAD

**Issue by yueli822ms** [ultralytics/yolov5#1704]
## ❔Question
During my verification, I found the when the image size is larger than 600, reducing the image size can significantly reduce the inference time, but this is not the case for image size smaller than 600. 
For example, the inference time is 16.9ms for img_size=640 and 15.5ms for img_size=64. Although the size difference is 10x, the inference time differs little. 
Could you please kindly provide me some information on why this happens?
Thank you!

**Comment by glenn-jocher** [comment]
@yueli822ms not all operations scale with size. This is an open ended computer science questions, but in general do not expect zero inference time as your image size trends to zero.

**Comment by JoJoliking** [comment]
@glenn-jocher 
Dear Author:
Hello! I have a question about the image input size.
Yolov5 uses a square image as network input by default. When I am switching to rectangular image for training, the length and width of the input image will be automatically read, but the length and width of the image will be different due to different image sizes.
So can I use fixed image length and width for training? (for example: 640 * 480 for all images)

**Comment by glenn-jocher** [comment]
@JoJoliking you can train with --rect to train on minimum batch rectangle sizes, or use default settings to train with --img-size square mosaics.
