### ISSUE TITLE
Yolov5 docker not detecting when using GPUs 

### ISSUE THREAD

**Issue by hqmf8104** [ultralytics/yolov5#1809]
Hi guys,

I'm having the same issue as #1088 insofar as I cannot detect objects within the YOLOv5 container IF I enable my GPU. It works absolutely fine when I'm not using my GPU...

The following:
docker run --ipc=host --shm-size 8G -it \
-v /mnt/c/Users/patm2/Projects/sat_im_obj_detect/phase3.0:/usr/src/python_scripts \
ultralytics/yolov5

Happily produces:
image 1/3 /usr/src/python_scripts/bus.jpg: 640x480 4 persons, 1 buss, 1 skateboards, Done. (0.241s)
image 2/3 /usr/src/python_scripts/people.jpg: 384x640 18 persons, 4 handbags, 1 potted plants, Done. (0.176s)
image 3/3 /usr/src/python_scripts/zidane.jpg: 384x640 2 persons, 2 ties, Done. (0.153s)

However, this:

docker run --ipc=host --gpus all --shm-size 8G -it \
-v /mnt/c/Users/patm2/Projects/sat_im_obj_detect/phase3.0:/usr/src/python_scripts \
ultralytics/yolov5

Produces this:

image 1/3 /usr/src/python_scripts/bus.jpg: 640x480 Done. (0.074s)
image 2/3 /usr/src/python_scripts/people.jpg: 384x640 Done. (0.037s)
image 3/3 /usr/src/python_scripts/zidane.jpg: 384x640 Done. (0.033s)

Any help would be greatly appreciated!

**Comment by glenn-jocher** [comment]
@hqmf8104 your issue is not reproducible. Docker image is operating correctly. See https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/

```bash
sudo docker run --ipc=host --gpus all ultralytics/yolov5:latest python detect.py
```

<img width="1106" alt="Screen Shot 2020-12-30 at 9 54 05 AM" src="https://user-images.githubusercontent.com/26833433/103371691-f87cd080-4a84-11eb-8700-8314b4ad321a.png">

**Comment by hqmf8104** [comment]
Glenn, thanks for responding! I am running docker on a WSL2. I suspect the issue is something to do with how docker is accessing the GPUs, and so is likely an Nvidia issue (not a yolov5 issues, however there may be others who have had the same issue and have a work around).

**Comment by glenn-jocher** [comment]
@hqmf8104 follow the docker quickstart directions, including installing the minimum requirements:
https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/#1-install-docker-and-nvidia-docker

## 1. Install Docker and Nvidia-Docker

Docker images come with all dependencies preinstalled, however Docker itself requires installation, and relies of nvidia driver installations in order to interact properly with local GPU resources. The requirements are: 
- Nvidia Driver >= 455.23 https://www.nvidia.com/Download/index.aspx
- Nvidia-Docker https://github.com/NVIDIA/nvidia-docker
- Docker Engine - CE >= 19.03 https://docs.docker.com/install/

**Comment by hqmf8104** [comment]
Yep, tracking those requirements and are already installed and setup. There are known issues with WSL2 and Nvidia-docker which could be causing the issue.
