### ISSUE TITLE
Question about Android Deploymeny

### ISSUE THREAD

**Issue by lujiazho** [ultralytics/yolov5#1847]
## ❔Question
does anybody why would this problem come out?
when I detect the image with the int8 tflite model by detect.py, it looks like this
image
![image](https://user-images.githubusercontent.com/68451409/103676648-4da46f00-4fbc-11eb-9377-d49a7d5354a7.png)

it can detect every wheat head correctly without any wrong box

But when I deploy the same model file on Android, it looks like this all the time, how could that be ?
image
![image](https://user-images.githubusercontent.com/68451409/103676665-5301b980-4fbc-11eb-83aa-1917b19e3e88.png)

does anybody have the same problem?

## Additional context
I used the way of zldrobit, and the link is [https://github.com/zldrobit/yolov5/tree/tf-android](zldrobit)

**Comment by glenn-jocher** [comment]
@leaving-voider can you show results on the same image? There's really no point in showing model A on image 1 vs model B on image 2.

**Comment by lujiazho** [comment]
> @leaving-voider can you show results on the same image? There's really no point in showing model A on image 1 vs model B on image 2.

thanks for reply, actually they are the same model.
And the model deployed on Android cannot have any meanful detection, no matter what image I put it on/(ㄒoㄒ)/

**Comment by jeenhyung** [comment]
@leaving-voider
Hi, I faced the same essue. 
And I solved.

If you used tf.py for convert .pt to .tflite,
You just need to modify all source code from numClasss+5 to numClass.

Example, 
float[][][] out = new float[1][output_box][numClass + 5];
to
float[][][] out = new float[1][output_box][numClass];

Because, You have already calculated it when you convert tflite.

Good luck!

**Comment by zldrobit** [comment]
@jeenhyung Thanks for pointing out the problem.
I forgot to subtract 5 (xywh and confidence of bounding boxes) from the last dimension of the output-tensor shape.

This problem is fixed by changing:
https://github.com/zldrobit/yolov5/commit/021345e4d4ed5484c9ed7525b4c447e8f40c0129#diff-a26b4f7400b6abfb58aa58de11ddb26a87e70312b2df009ca7d9043d405dfeb2L134-R134
in the new [tf-android branch](https://github.com/zldrobit/yolov5/tree/tf-android).
