### ISSUE TITLE
different image size w/ torchscript windows c++

### ISSUE THREAD

**Issue by alexyuisme** [ultralytics/yolov5#1920]
Hi, all:

I am running into an issue while testing different images under c++ windows environment. The following is my windows program: (windows 10, visual studio 2017 w/ torchscript) :

`       
       int main()
       {		        
        torch::jit::script::Module module;
	try {
		// Deserialize the ScriptModule from a file using torch::jit::load().
		module = torch::jit::load("F:/yolov5s.torchscript.pt");

		string img_path = "F:/image.jpg";
		Mat img = imread(img_path);
		cvtColor(img, img, CV_BGR2RGB);// bgr->rgb
		img.convertTo(img, CV_32FC3, 1.0f / 255.0f);// 1/255
		auto tensor_img = torch::from_blob(img.data, { img.rows, img.cols, img.channels() });
		tensor_img = tensor_img.permute({ 2, 0, 1 });
		tensor_img = tensor_img.unsqueeze(0);

		std::vector<torch::jit::IValue> inputs;
		inputs.push_back(tensor_img);
		torch::jit::IValue output = module.forward(inputs);
		auto op = output.toList().get(0).toTensor();
	}
	catch (const c10::Error& e) {
		
		//std::cerr << "error loading the model\n";
		std::cerr << e.what() << std::endl;
		return -1;
	}
}`

testing image.jpg with size 384x640 is ok; but testing image.jpg with 640x360 gives me the following error:

> Unhandled exception at 0x00007FFEDA1FF218 in test_libtorch.exe: Microsoft C++ exception: std::runtime_error at memory location 0x000000E5255E9C58.

Any ideas?  Thanks!

**Comment by zhiqwang** [comment]
Hi,

It seems that `torch.jit.trace` mechanism doesn't support inferring with dynamic variable input sizes. In other words, your image size must equal to the sizes when you generate the torchscript model.

I think that one way to address the dynamic size inference issue is through the `torch.jit.script` mechanism.

**Comment by alexyuisme** [comment]
> Hi,
> 
> It seems that `torch.jit.trace` mechanism doesn't support inferring with dynamic variable input sizes. In other words, your image size must equal to the sizes when you generate the torchscript model.
> 
> I think that one way to address the dynamic size inference issue is through the `torch.jit.script` mechanism.

Hi, zhiqwang:

Thanks for your reply. I am very new to Pytorch and still figuring out what is the diff btw `torch.jit.trace` and `torch.jit.script`. I am wondering how do you know I am using `torch.jit.trace` mechanism?  The way that I generated  "yolov5s.torchscript.pt" is by running: 

python models/export.py --weights yolov5s.pt --img 640 --batch 1

Thanks.

**Comment by zhiqwang** [comment]
Hi @alexyuisme 

Because the author use `torch.jit.trace` as default as following:

https://github.com/ultralytics/yolov5/blob/051e9e80def4c8bc28e4241df2a801c6aa6a8d33/models/export.py#L58-L62

Besides, the dynamic variable batch inference limitations is very common with `torch.jit.trace`, so I guess that you are using `torch.jit.trace`.

**Comment by alexyuisme** [comment]
Hi, @zhiqwang:

Haha, I see. Is that possible to specify different width and height rather than simply using --img 640? 

Thanks,

**Comment by zhiqwang** [comment]
Hi, @alexyuisme 

The `torch.jit.trace` mechanism only support determined image sizes, if the sizes of your dataset is determined, you can just set (suppose the size is `(640, 360)`)

```
python models/export.py --weights yolov5s.pt --img 640 360 --batch 1
```

If the size is dynamic, the author also provide a `letterbox` function to auto-pad the images to the sizes you are determined (when the image is smaller than (640, 360)), because CNN is local sensitive, it doesn't influence the inference results, you can refer the function as following:

https://github.com/ultralytics/yolov5/blob/dd03b20ba5024a2a4e35e81eb04fe466d4b9bc9f/utils/datasets.py#L795-L825

Another more flexible method is through `torch.jit.script` as I mentioned, you can refer to my [repo](https://github.com/zhiqwang/yolov5-rt-stack).

**Comment by alexyuisme** [comment]
You saved my life, bro! I'll definitely check your yolo5rt stack.

Thanks!
