### ISSUE TITLE
Why "run once" in detect.py?

### ISSUE THREAD

**Issue by asfarley** [ultralytics/yolov5#1955]
What is the purpose of line 61 in detect.py?

`    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once`

**Comment by glenn-jocher** [comment]
@asfarley this line runs a forward pass once.

**Comment by asfarley** [comment]
I still don't quite understand - what's the motivation for running a forward pass once outside of the main loop?

**Comment by glenn-jocher** [comment]
@asfarley this is a low level forward method, which is callable by higher level methods like forward() once or multiple times to satisfy the specific inference requirements of a given call.

I created this structure specifically for YOLOv5, I doubt you've seen it elsewhere, which is why you may not recognize it. This powers inference options like TTA and model ensembling.
