### ISSUE TITLE
yolov5如何启动单机多卡训练？

### ISSUE THREAD

**Issue by zcswdt** [ultralytics/yolov5#1973]
## ❔Question

您好，我看到代码里面有DDP模式，这个如何启动单机多卡训练呢？

**Comment by zcswdt** [comment]
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

Thank you for your reply. There are two cards in my environment. I used method one: `python train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt`. This method can also achieve single-machine multi-card training.
But there is also training method two: `python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --weights yolov5l.pt`, is there any difference between these two methods? ?

**Comment by glenn-jocher** [comment]
@zcswdt use `python -m torch.distributed.launch` method for all multi-GPU training. See Multi-GPU Tutorial for details:
https://docs.ultralytics.com/yolov5

**Comment by zcswdt** [comment]
> @zcswdt use `python -m torch.distributed.launch` method for all multi-GPU training. See Multi-GPU Tutorial for details:
> https://docs.ultralytics.com/yolov5

The problem has been solved, thank you very much for your help and patient answers.

**Comment by GuitarYourself** [comment]
> > @zcswdt use `python -m torch.distributed.launch` method for all multi-GPU training. See Multi-GPU Tutorial for details:
> > https://docs.ultralytics.com/yolov5
> 
> The problem has been solved, thank you very much for your help and patient answers.

hi, i also has this problem, can u share how did you solve this problem?

**Comment by jcluo1994** [comment]
0%|          | 0/79 [00:00<?, ?it/s]Traceback (most recent call last):   File "train.py", line 641, in <module>     main(opt)   File "train.py", line 530, in main     train(opt.hyp, opt, device, callbacks)   File "train.py", line 310, in train     pred = model(imgs)  # forward   File `"/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py",` line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward     output = self._run_ddp_forward(*inputs, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward     return module_to_run(*inputs[0], **kwargs[0])   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/yolo.py", line 209, in forward     return self._forward_once(x, profile, visualize)  # single-scale inference, train   File "/home/dell/deeplearn/yolov5/models/yolo.py", line 121, in _forward_once     x = m(x)  # run   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/common.py", line 167, in forward     return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), 1))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward     input = module(input)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl   0%|          | 0/79 [00:00<?, ?it/s]     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/common.py", line 120, in forward Traceback (most recent call last):   File "train.py", line 641, in <module>     return x + self.cv2(self.cv1(x)) if self.add else self.cv2(self.cv1(x))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/common.py", line 56, in forward     main(opt)   File "train.py", line 530, in main     return self.act(self.bn(self.conv(x)))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     train(opt.hyp, opt, device, callbacks)   File "train.py", line 310, in train     return forward_call(*input, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 463, in forward     pred = model(imgs)  # forward   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return self._conv_forward(input, self.weight, self.bias)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 460, in _conv_forward     self.padding, self.dilation, self.groups) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 1; 10.91 GiB total capacity; 10.18 GiB already allocated; 10.06 MiB free; 10.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF     return forward_call(*input, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward     output = self._run_ddp_forward(*inputs, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward     return module_to_run(*inputs[0], **kwargs[0])   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/yolo.py", line 209, in forward     return self._forward_once(x, profile, visualize)  # single-scale inference, train   File "/home/dell/deeplearn/yolov5/models/yolo.py", line 121, in _forward_once     x = m(x)  # run   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/common.py", line 167, in forward     return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), 1))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/deeplearn/yolov5/models/common.py", line 56, in forward     return self.act(self.bn(self.conv(x)))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 182, in forward     self.eps,   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/nn/functional.py", line 2451, in batch_norm     input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 10.91 GiB total capacity; 10.14 GiB already allocated; 48.06 MiB free; 10.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 45072) of binary: /home/dell/anaconda3/envs/train/bin/python Traceback (most recent call last):   File "/home/dell/anaconda3/envs/train/lib/python3.7/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "/home/dell/anaconda3/envs/train/lib/python3.7/runpy.py", line 85, in _run_code     exec(code, run_globals)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/run.py", line 766, in <module>     main()   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper     return f(*args, **kwargs)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/run.py", line 762, in main     run(args)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run     )(*cmd_args)   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__     return launch_agent(self._config, self._entrypoint, list(args))   File "/home/dell/anaconda3/envs/train/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent     failures=result.failures, torch.distributed.elastic.multiprocessing.errors.ChildFailedError:  ============================================================ train.py FAILED ------------------------------------------------------------ Failures: [1]:   time      : 2023-09-13_15:59:19   host      : dell-PowerEdge-T630   rank      : 1 (local_rank: 1)   exitcode  : 1 (pid: 45073)   error_file: <N/A>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html ------------------------------------------------------------ Root Cause (first observed failure): [0]:   time      : 2023-09-13_15:59:19   host      : dell-PowerEdge-T630   rank      : 0 (local_rank: 0)   exitcode  : 1 (pid: 45072)   error_file: <N/A>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html ============================================================

**Comment by glenn-jocher** [comment]
@jcluo1994 it seems that you are encountering a CUDA out of memory error while running YOLOv5. This error occurs when the GPU memory is insufficient to allocate the required tensors during training.

Here are a few suggestions to solve this issue:
1. Reduce the batch size: Decrease the batch size in your training configuration (`opt.batch_size`). This will reduce the memory usage per iteration and might resolve the out-of-memory error.
2. Resize images: Try resizing the input images to a smaller size. This can be done by modifying the `img_size` parameter in the configuration file (`opt.img_size`).
3. Limit GPU memory growth: Set the `torch.backends.cudnn.benchmark` flag to `True`. This will enable dynamic memory allocation and reduce the overall memory usage. You can add the following line of code at the beginning of your script:

   ```
   import torch
   torch.backends.cudnn.benchmark = True
   ```
   
4. Use a larger GPU: If possible, try training on a GPU with higher memory capacity. This will provide more memory for the model and reduce the likelihood of running out of memory.

I hope one of these solutions helps you resolve the issue. Let me know if you have any further questions.
