### ISSUE TITLE
How to use it with Python 2? For ROS integration

### ISSUE THREAD

**Issue by ubicray** [ultralytics/yolov5#1974]
I'm working on modifying this to make it work with ROS Melodic, which uses Python 2.
Problem is, it's a headache to get it working with Python 3 as other packages for ROS Melodic use Python 2
If anybody got this working with Python 2 or ROS it'd be a great help to know how

**Comment by glenn-jocher** [comment]
@ubicray my recommendation would be to find a python-3 capable hardware endpoint to use, not just for your current task but for future tasks for improved maintainability and interoperability going forward.

**Comment by nhatleminh1997** [comment]
You can take a look at this repository for YOLOv5 with ROS Noetic https://github.com/mats-robotics/yolov5_ros

**Comment by syrine06** [comment]
@[ubicray](https://github.com/ubicray) ubicray 
Hello ubicray, 
did you find a solution for using yolov5 with ros melodic? because I'm also facing the same problem.
Thanks in advance!

**Comment by 0xNOY** [comment]
Although a bit of a heavy-handed approach, YOLOv5 can be used as a Web API from Python2 scripts by wrapping it with a web framework such as Flask.
I actually did this. If you have any questions about the details I will answer them.

**Comment by glenn-jocher** [comment]
@0xNOY great initiative! However, since Python 2 reached its end of life in 2020, we highly recommend migrating to Python 3 for your long-term development and maintenance. This not only ensures better compatibility with the latest libraries and frameworks but also aligns with industry best practices. If any queries arise during the transition, feel free to reach out – we're here to help!
