### ISSUE TITLE
Can't YOLOV5 be detected with multithreading?

### ISSUE THREAD

**Issue by bulingda** [ultralytics/yolov5#1979]
Environment:
Python 3.7
Pytorch 1.5.1
Yolov5 v1.0

Bug:
RuntimeError: The expanded size of the tensor (50) must match the existing size (25) at non-singleton dimension 3. Target sizes: [1, 3, 28, 50, 2]. Tensor sizes: [3, 14, 25, 2]
The detailed error information is shown in the figure below:
![image](https://user-images.githubusercontent.com/55130106/104985112-2ed9ba00-5a4b-11eb-901e-04a68471b597.png)

Description:
I use ThreadPoolExecutor in Python concurrent-future to implement multithreading detection, and the above error occurs whenever my number of tasks (detection) is greater than and 1.
The error occurred [here](https://github.com/ultralytics/yolov5/blob/b1cf25dd9a7ba6a47703457bc04b8b77e469803b/models/yolo.py#L53) 
I was doing two detection tasks at the same time when the error occurred, and I wondered if the shapes didn't match because of information confusion between threads.

Thank you very much for helping me solve this problem.

**Comment by bulingda** [comment]
I don't know whether my question belongs to this tag or not. If not, I can modify it.Thanks

**Comment by glenn-jocher** [comment]
@bulingda we don't generally assist in debugging code modifications.

You can see an example of a multithreaded _dataloader_ here, though this is only used for multiple webcam streams at the moment:
https://github.com/ultralytics/yolov5/blob/b1cf25dd9a7ba6a47703457bc04b8b77e469803b/utils/datasets.py#L258

If you want finer control over your inference you might want to build your own code around the YOLOv5 PyTorch Hub autoshape models:
https://github.com/ultralytics/yolov5#pytorch-hub

**Comment by bulingda** [comment]
> @bulingda we don't generally assist in debugging code modifications.
> 
> You can see an example of a multithreaded _dataloader_ here, though this is only used for multiple webcam streams at the moment:
> https://github.com/ultralytics/yolov5/blob/b1cf25dd9a7ba6a47703457bc04b8b77e469803b/utils/datasets.py#L258
> 
> If you want finer control over your inference you might want to build your own code around the YOLOv5 PyTorch Hub autoshape models:
> https://github.com/ultralytics/yolov5#pytorch-hub

Thank you very much for your tips

**Comment by olehb** [comment]
@bulingda check out this PR https://github.com/ultralytics/yolov5/pull/2120/files 
I removed mutable state from Detect class and it made the model thread-safe in my service. Hope it helps.

**Comment by glenn-jocher** [comment]
@olehb @bulingda ah I see the problem here. I wonder if there's a different way to solve this that doesn't require grid recomputation on every image? It's not just that it adds additional pytorch inference overhead, but it also makes export more complicated if the grid computation is included in the export (for this reason the export code runs inference once (to capture grids as constants) before actually tracing the model (using the grid constants) to produce a simplified export.

**Comment by bulingda** [comment]
![image](https://user-images.githubusercontent.com/55130106/107110686-ead91880-6884-11eb-817a-0f60b3035fa1.png)
Thank you very much for your attention. I have also solved this problem. Here is my solution. @olehb @glenn-jocher

**Comment by glenn-jocher** [comment]
@bulingda @olehb perhaps another option is to create a single large grid on init (rather than 3 smaller ones), and then simply slice the large grid to what's required for each output, i.e.:
`grid = self.grid[:, :, :nx, :ny]`

I profiled this to be about 3x faster than creating a grid with self._make_grid(), and this would avoid redefining the grid, so theoretically thread safe?

**Comment by Simon717** [comment]
I encountered the same problem, the core is that different threads have made different modifications to `self.grid`

**Comment by glenn-jocher** [comment]
@Simon717 see PR https://github.com/ultralytics/yolov5/pull/2120 for an inference thread-safe version which handles Detect() grid layer differently.
