### ISSUE TITLE
detect.py image size  and export script model size

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#1980]
## ❔Question

Thank you for your excellent work@glenn-jocher. I am now having a problem with the scale parameter '--img-size' set in the training model, nargs='+', type=int, default=[640, 640], and the image scale in detect.py is

Image 1/86 E:\ Yolov5-master \ Data \ Samples \000000.jpg: 352x640 95 rebars, Done. (0.024s)

Image 2/86 E:\ Yolov5-master \ Data \ Samples \000001.jpg: 352x640 95 rebars, Done. (0.022s)

Image 3/86 E:\ Yolov5-master \ Data \ Samples \000002.jpg: 320x640 95 rebars, Done. (0.023s)

Image 4/86 E:\ Yolov5-master \ Data \ Samples \000003.jpg: 352x640 95 rebars, Done. (0.023s)

Image 5/86 E:\ Yolov5-master \ Data \ Samples \000004.jpg: 352x640 95 rebars, Done. (0.025s)

Image 6/86 E:\ Yolov5-master \ Data \ Samples \000005.jpg: 288x640 95 rebars, Done. (0.021s)

Image 7/86 E:\ Yolov5-master \ Data \ Samples \000120.jpg: 320x640 290 rebars, Done. (0.029s)
The results are accurate。
However, in the export model of export.py, img--size was set as default=[640, 640]. The detection accuracy was not correct in the LibTorch prediction, and the detection box size was not accurate. How should I set the export size?
## Additional context
![图片](https://user-images.githubusercontent.com/51087601/105005285-116b1700-5a70-11eb-9624-dd346769a96a.png)
![图片](https://user-images.githubusercontent.com/51087601/105005251-06b08200-5a70-11eb-903f-205431c48d38.png)
img1 is detect.py result ; img2 is libtorch result;

**Comment by WANGCHAO1996** [comment]
When I put export.py When the fixed size of is changed to 352 × 640, the exported model is called libtorch to get the image result
![图片](https://user-images.githubusercontent.com/51087601/105006396-960a6500-5a71-11eb-9b3d-06843e8eb475.png)

How to select the size of the exported model when the input image size is different？@glenn-jocher

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 you can export to any fixed size using the --img command, i.e.:
`python export.py --weights yolov5s.pt --img 352 640`

You want the exported --img aspect ratio (i.e. height / width) to match your input image aspect ratio (that you will use during deployment) as closely as possible to minimize distortions.

Detect.py handles all of this automatically, as do the YOLOv5 PyTorch Hub autoshape models during inference (both use rectangular inference with minimum padding to meet stride constraints).

**Comment by WANGCHAO1996** [comment]
How to select the size of the exported model when the input image size is different

> 
> 
> @WANGCHAO1996 you can export to any fixed size using the --img command, i.e.:
> `python export.py --weights yolov5s.pt --img 352 640`
> 
> You want the exported --img aspect ratio (i.e. height / width) to match your input image aspect ratio (that you will use during deployment) as closely as possible to minimize distortions.
> 
> Detect.py handles all of this automatically, as do the YOLOv5 PyTorch Hub autoshape models during inference (both use rectangular inference with minimum padding to meet stride constraints).

Optimizer groups: 134 .bias, 142 conv.weight, 131 other
Traceback (most recent call last):
  File "E:/yolov5-master/train.py", line 514, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "E:/yolov5-master/train.py", line 188, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "E:\yolov5-master\utils\datasets.py", line 61, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "E:\yolov5-master\utils\datasets.py", line 370, in __init__
    cache = torch.load(cache_path)  # load
  File "D:\d\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 596, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\d\Anaconda3\envs\yolov5\lib\site-packages\torch\serialization.py", line 765, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Process finished with exit code 1


OK, it has been used. However, some mistakes were reported during training？@glenn-jocher

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 👋 Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
