### ISSUE TITLE
how to export the ensembled model to onnx?

### ISSUE THREAD

**Issue by freitaucher** [ultralytics/yolov5#1989]
I have trained several partial yolov5m binary classifier models. The detection by using their ensemble, i.e.:

python detect.py --source inp --output out  --weights 0.pt 1.pt  2.pt  3.pt

works fine. Also I can export each of those models to onnx. But now I would like to get a single onnx-model out of the ensemble:

In detect.py, once the model is loaded: 

 model = attempt_load(weights, map_location=device)

I'm trying to onnx export it:

    # ONNX export
    try:
        import onnx     
        img = torch.zeros((1, 3, 640,640)).cuda()
        y = model(img) 
        torch.onnx.export(model, img, 'ensemble.onnx', verbose=True, opset_version=12, input_names=['images'],
                          output_names=['classes', 'boxes'] if y is None else ['output'])
    except Exception as e:
        print('ONNX export failure: %s' % e)

But here I get a warning and export failure:

models/yolo.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:

**ONNX export failure: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type NoneType**

Could you give any hints?

## ❔Question

how to correctly export the ensembled model to onnx?

## Additional context
python3.8, torch==1.6.0, onnx==1.8.0

**Comment by glenn-jocher** [comment]
@Stancoo interesting question. YOLOv5 is somewhat unique in that we offer built-in model ensembling via our Ensemble() class, but I've not tried to export such a class before, so I would not expect this to work out of the box. You'd likely need some changes to allow this to work, if it's possible at all. 

In any case, if you succeed please consider submitting a PR to help others down the line benefit from your developments!

**Comment by freitaucher** [comment]
@glenn-jocher  definitely, it is not trivial.  But I got a bit forward with this. If shortly: in the definition of the _Ensemble class_ (file _models/experimental.py_)  one needs to change the output:   _return y, None -> return y_. With this, I get a correct onnx-file out of the ensembled model in a way shown above.  

There still remains some work to do, since the ensembled onnx model delivers the expected results only partially (not all the  bboxes, which are known to be produced by the single onnx-submodels do appear). I guess, it has to deal with the way, how one exactly does interpret the onnx-model output, i.e. depends on the specific code.  In my case, I adapted the [code](https://github.com/ultralytics/yolov5/issues/343#issuecomment-662156461)  provided for yolov5-onnx inference.  It seems to be far not perfect, but I didn't find anything else..

**Comment by zhiqwang** [comment]
Hi @glenn-jocher @Stancoo

I've done some experiments to export the ensembled model to onnx in my repo [`yolov5rt`](https://github.com/zhiqwang/yolov5-rt-stack). The whole process can now run successfully, but due to the difference in interpolation mode, there are minor difference in the inference result between Ultralytics original and mine, but I think that it could be set a reference now.

And [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/release/v0.2.0/notebooks/export-onnx-inference-onnxruntime.ipynb) is a notebook to show the onnx inference of the whole ensemble model.

**Comment by glenn-jocher** [comment]
@zhiqwang oh great, thanks for the references!

@Stancoo you may want to take a look at the links above from @zhiqwang. 

Also note that ensembling has been modified slightly in the most recent release to use 'NMS' ensembling instead of 'mean' ensembling. This allows differently shaped models to ensemble together (i.e. a P3-P5 model can now ensemble with a P3-P6 model), so should make the ensemble more robust than before.
https://github.com/ultralytics/yolov5/blob/046c37e465d60b9047ff0e91f44594817e5a935c/models/experimental.py#L98-L111

**Comment by freitaucher** [comment]
Thank you, @zhiqwang  great work!  I will definitely follow you asI need to pass the ensembled onnx-model to  to the tensorrt optimizer anyway. 

@glenn-jocher Exactly)  I have a sequence of submodels, each being trained on its specific data: this means, that one needs to collect all results they catch (via concatenation) instead of selecting the most probable one (max) or their average (mean). The NMS should be applied for the ensembled onnx-model then just at the end, in a submodel-specific way..

**Comment by zhiqwang** [comment]
Hi @Stancoo @glenn-jocher ,

Oops, I think I misunderstood part of this issue, I've only assembled the **pre-process**, **model inference** and **post-process** (containing `NMS`) within one model.

Ensemble of two or more models should do more experiments.

**Comment by glenn-jocher** [comment]
@zhiqwang ah I see. This sort of vertical integration is typically called a 'pipeline'. i.e. you can pipeline a model together with an NMS module for greater utility.
