### ISSUE TITLE
Query on anchor counts

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [ultralytics/yolov5#2005]
## ❔Question
Afternoon @glenn-jocher. 

First off, amazing work with this repo. I've recently migrated from using Darknet, and I must thank you for improving my overall quality of life (C/C++ gives me nightmares).

I've (somewhat) successfully implemented a tiled dataloader to train/detect the xview dataset using yolov5. It's working remarkably well, (0.64 mAP@0.5 single class, will report on actual mAP once finished). While perusing your xview-yolov3 repo, I did see that you were using [30 anchors in your model](https://github.com/ultralytics/xview-yolov3/blob/bc22baa2e4d20cf3a94af7055bf7154bce320571/cfg/c60_a30symmetric.cfg#L611). 

Could you please expand upon why that decision was made, and do you believe increasing the anchor count would help with yolov5 trained on xview?

**Comment by glenn-jocher** [comment]
@decent-engineer-decent-datascientist yes we experimented with higher anchor counts in xView due to the wide variety of object sizes in the dataset. Anchor counts effects will likely vary by dataset, so its best to test yourself on your data. You can set anchor counts by passing a number in your model.yaml anchor field. This is the number of anchors you are requesting per output layer. Example below would create 15 anchors on a P3-P5 model. 

<img width="1862" alt="Screen Shot 2021-01-20 at 12 33 30 PM" src="https://user-images.githubusercontent.com/26833433/105407866-13a1b280-5be3-11eb-9b6b-59b3bf3e7cd2.png">

**Comment by decent-engineer-decent-datascientist** [comment]
@glenn-jocher That makes sense. I didn't realize it was that simple to modify anchor counts. I'll experiment with larger anchor counts and reply back with the results. Thank you for the fast reply!

**Comment by gregrutkowski13** [comment]
> That makes sense. I didn't realize it was that simple to modify anchor counts. I'll experiment with larger anchor counts and reply back with the results. Thank you for the fast reply!

Curious about your results?

**Comment by decent-engineer-decent-datascientist** [comment]
@gregrutkowski13 Didn't make a difference. AutoAnchor does a good job finding what it needs with just 9 anchors.
