### ISSUE TITLE
How --rect command works?

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#2009]
Hi,

I have a video which is 1920 x 1080 and I'm training a yolov5x model in order to detect object in this video.
Model resizes the video to 640x384 (or something like that)
In this case, I cannot use the models all inputs

I looked for solution to this problem, people say use --rect.

How --rect works?
does it change models input res.?
how does it changes?
how to use it?

I need more information about --rect command that in the train.py

**Comment by glenn-jocher** [comment]
@sezer-muhammed --rect argument forces rectangular image training (rectangular inference is used by default during inference). --img argument modifies image size.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed --rect argument forces rectangular image training (rectangular inference is used by default during inference). --img argument modifies image size.

as I know img takes only 1 argument how can I create and train a model with shape (360, 720, 3) for example?

**Comment by glenn-jocher** [comment]
@sezer-muhammed if your images correspond to a 360:720 (i.e. 1:2) aspect ratio then your training command would be:
`python train.py --img 720 --rect`

**Comment by matbord** [comment]
But what is the main reason I should use --rect? only to have faster training or also to have better performance in the model?

**Comment by mysteryjeans** [comment]
> @sezer-muhammed if your images correspond to a 360:720 (i.e. 1:2) aspect ratio then your training command would be: `python train.py --img 720 --rect`

Thanks, exports should also be 1:2 ratio, depending on whatever image size used in training for best results?

**Comment by glenn-jocher** [comment]
@mysteryjeans you should train and deploy at similar object sizes for best results. Ratio does not matter.

**Comment by mysteryjeans** [comment]
I notice train_batch0.jpg to be 384 in height 1280 in width; with --img 1280 --rect parameters, 

This isn't exactly 1:2; rather seems 9:16x2 aspect ratio which calculates to 360:1280, since 360 isn't multiple of 32 so round of to 384. Is this correct?

PS: I am training dual screens.

**Comment by glenn-jocher** [comment]
@mysteryjeans all input images are subject to minimum stride constraints: 32 pixels for P5 models or 64 pixels for P6 models.

**Comment by bryanbocao** [comment]
@glenn-jocher 
> @sezer-muhammed if your images correspond to a 360:720 (i.e. 1:2) aspect ratio then your training command would be: `python train.py --img 720 --rect`

Could you further clarify how to decide the parameter of ```--img``` when my aspect ratio is not 1:1? Is it by the largest side or width?
Suppose I have ```720 x 360```  (rows x cols) and ```360 x 720``` (rows x cols) images, which one should I use for ```--image``` when using ```--rect```? 720 or 360?

Thanks!

**Comment by bryanbocao** [comment]
> @glenn-jocher
> 
> > @sezer-muhammed if your images correspond to a 360:720 (i.e. 1:2) aspect ratio then your training command would be: `python train.py --img 720 --rect`
> 
> Could you further clarify how to decide the parameter of `--img` when my aspect ratio is not 1:1? Is it by the largest side or width? Suppose I have `720 x 360` (rows x cols) and `360 x 720` (rows x cols) images, which one should I use for `--image` when using `--rect`? 720 or 360?
> 
> Thanks!

OK, it is ```--img 720 --rect``` in either case, answered in https://github.com/ultralytics/yolov5/discussions/2916
> @glenn-jocher YOLOv5 you specify the size of the **largest** image dimension only

**Comment by glenn-jocher** [comment]
@bryanbocao Exactly, it's --img 720 --rect for both cases. You specify the size of the largest image dimension only.

**Comment by Kuchchi12** [comment]
should i use rectangular training if all of the images in my train dataset are of different dimensions varying between and also how yolov7 make changes to annotation when it resizes the data when rectangular training is not been used

**Comment by glenn-jocher** [comment]
@Kuchchi12 you can use rectangular training with images of different dimensions. YOLOv5 resizes images but doesn't change annotations when rectangular training is not used.

**Comment by CurrencySH** [comment]
What does rect do, does it increase model perofrmance if all your images have the same aspect ratio or does it speed up training

**Comment by glenn-jocher** [comment]
@CurrencySH the `--rect` flag in YOLOv5 training is used to enable rectangular training, which can speed up the training process when your dataset contains images of varying aspect ratios. It allows the model to process batches of images that are more closely aligned in shape, reducing the amount of padding needed and making more efficient use of the GPU. If all your images already have the same aspect ratio, using `--rect` won't significantly impact model performance but can still offer slight training speed improvements by optimizing batch shapes.

**Comment by songsonglin487** [comment]
Should I adjust hyperparameters, such as mosaic, because I'm using --rect, or does it not matter?

**Comment by timingisnow** [comment]
@glenn-jocher Hi,

My size of image dataset is 720x1280(h, w).
I was training yolov5 like python train.py --img 832--rect, and actual input resolution is 448x832 in training.
Actuall, I want to export the model trained to int8 tflite and after that validate the test dataset.

Q1. After model trained like above, 
      Is below img size of command right to export ? 
      python export.py --img 448 832 --data data.yaml --weights best.pt --int8 --include tflite

Q2. python val.py --img 448 832 --data data.yaml --weights best.tflite is right for adapting image size?

**Comment by glenn-jocher** [comment]
@timingisnow hi there! 😊

For your scenario, when exporting the model and validating the test dataset, you should match the image sizes used during training for consistency. So, let's break down your questions:

Q1: Yes, your command for exporting looks correct. Just make sure the `--img` dimensions match what you used during training or are suitable for the input dimensions your network expects.

```bash
python export.py --img 448 832 --data data.yaml --weights best.pt --int8 --include tflite
```

Q2: Similarly, when you validate, ensure the image size is consistent. If you trained with `--img 448 832`, you should validate with the same dimensions.

```bash
python val.py --img 448 832 --data data.yaml --weights best.tflite
```

This approach maintains consistency across training, exporting, and validation phases. Good luck with your model! 🌟

**Comment by timingisnow** [comment]
@glenn-jocher 
Thank you for your quick reply.

I'm little bit confused yet about mentioning image size on Q2 answer.
1. input image size is 720x1280(h,w) on both training and validation dataset
2. training input resolution is 448x832 by training --rect 832
3. export --img 448x832
4. validation --img consistent with 448x832(input resolution) or 720x1280(input size)??

I understood until 3, my question is 4 above.
Please, let me know for clearance about this subject. Thanks

**Comment by glenn-jocher** [comment]
Hi @timingisnow!

For clarity, during validation you should use the same image resolution as you did during training. Since you trained with an input resolution of 448x832 (achieved by using `--rect 832`), you'll want to validate with the same resolution for consistency. So, in your case, you should validate with `--img 448 832`.

```bash
python val.py --img 448 832 --data data.yaml --weights best.tflite
```

This ensures the validation phase uses the same image processing as during training. Hope that clears it up! 😊

**Comment by timingisnow** [comment]
@glenn-jocher  

When I tried
`python val.py --img 448 832 --data data.yaml --weights best.tflite`

met this error: val.py: error: unrecognized arguments: 832

 after this, I tried due to long side input resolution
`python val.py --img 832 --data data.yaml --weights best.tflite`

and  below is showed
Forcing --batch-size 1 square inference (1,3,832,832) for non-PyTorch models
ValueError: Cannot set tensor: Dimension mismatch. Got 832 but expected 448 for dimension 1 of input 0.

**Comment by glenn-jocher** [comment]
@timingisnow hi there! It looks like there's a bit of confusion with the `--img` flag usage for `val.py`. The `--img` flag expects a single integer, defining the longer side of the image while the other side will be scaled accordingly to maintain the aspect ratio. Since your model was trained with an input resolution of 448x832, you should use:

```bash
python val.py --img 832 --data data.yaml --weights best.tflite
```

However, the error you're encountering suggests an issue with the expected input size for your `.tflite` model. The `.tflite` model is expecting a square input, hence the error. 

Please ensure the export was done correctly with the intended dimensions. Unfortunately, TFLite models often expect square inputs, and additional steps might be needed for non-square inputs. 

For now, try validating with PyTorch weights (`.pt`) if possible, or explore adjusting your model to accept square inputs. 

Hope that helps! Keep up the great work 😊

**Comment by timingisnow** [comment]
@glenn-jocher 

> Unfortunately, TFLite models often expect square inputs, and additional steps might be needed for non-square inputs.

it means, non-square output of tflite is additionally needed, right? by modifying export.py ?

**Comment by glenn-jocher** [comment]
@timingisnow hi! 😊 Yes, TFLite models typically expect square inputs. For non-square inputs, you'd need to adapt the `export.py` script or preprocess your inputs to fit the model's requirements. This might involve adjusting how the input images are resized or padded. It's a fine balancing act between maintaining the aspect ratio and meeting the model's input dimension expectations. Remember to handle both the width and height dimensions carefully to avoid distorting your input images. Good luck!

**Comment by yjseok** [comment]
Hi @glenn-jocher 

Could rectangular training be activated?
Even though I didn’t use —rect parameter when training, self.rect is True in dataloader.py file.

**Comment by glenn-jocher** [comment]
Hi @yjseok,

It sounds like there might be an issue with the `dataloader.py` configuration. The `--rect` parameter should control whether rectangular training is activated. If `self.rect` is `True` without specifying `--rect`, it could be due to a default setting or an unintended modification.

To ensure rectangular training is only activated when intended, double-check your training command and any custom modifications to the codebase. If the issue persists, you might want to review the `dataloader.py` logic to ensure it aligns with your training parameters.

Feel free to reach out if you need further assistance! 😊
