### ISSUE TITLE
How to set up a proper balance loss in ComputeLoss Class for a custom model with det.nl is 2 or other?

### ISSUE THREAD

**Issue by LZHgrla** [ultralytics/yolov5#2026]
## ❔Question
In yolov5 v4.0, I find that u set up a proper balance loss for each scale.

`self.balance = {3: [3.67, 1.0, 0.43], 4: [3.78, 1.0, 0.39, 0.22], 5: [3.88, 1.0, 0.37, 0.17, 0.10]}[det.nl]`

If I use a custom model which `det.nl == 2`, how to set up a proper balance loss and what is the reason for that?

**Comment by glenn-jocher** [comment]
@LZHgrla yes we implemented some loss balancing values from the mean COCO losses. It seems that larger output layers may overfit earlier, so those numbers may need a bit of adjustment. They correspond to P3-P7 on COCO. 

If you are using alternate outputs you may want to collect your own loss data per layer to balance with, but very rough guidance is that a good loss balancing may simply correspond to the pixels present in each output layer (so rather than summing losses, you are effectively taking a mean loss of each layer), before summing layers.
