### ISSUE TITLE
class  confident when there is only one class

### ISSUE THREAD

**Issue by Egolee0713** [ultralytics/yolov5#2036]
## ❔Question
class  confident calculate when there is only one class

## Additional context
Compute conf  in non_max_suppression is : x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
But when there is only one class, cls loss is not calcultate when training and set to 0, so it means that x[:, 5:] is random when inference? And it would be better to directly set conf = obj_conf when there is only one class？ @glenn-jocher

**Comment by glenn-jocher** [comment]
@yongjingli don't worry this is all handled correctly. If you put a breakpoint in NMS you should see that x[:, 5:] is all at or near 1.0. This is because the classification output neurons have their biases set very high (prior to sigmoiding) during model bias init before training starts. Since these neurons never incur loss (during single-class training), they will retain their near 1.0 outputs no matter how long you train.

https://github.com/ultralytics/yolov5/blob/a41d910c5d7e2eb3e5998ff53222936f6cea0fc9/models/yolo.py#L142-L151

**Comment by Egolee0713** [comment]
okay, I got this, it is really a smart trick, thank you for your quickly answer.  @glenn-jocher

**Comment by wmcnally** [comment]
@glenn-jocher I have a quick question somewhat related to this issue but also related to transfer learning: if you change the number of classes of the default model (e.g., from 85 to 1), load the default weights (e.g., yolov5s.pt), and then predict, will the model make resonable predictions? E.g., when changing nc from 85 to 1 without retraining, will the model detect people? If retraining is required, would it learn to detect people faster than training from scratch? Thanks!

**Comment by glenn-jocher** [comment]
@wmcnally the model must naturally be trained on the data you want to be able to predict.
