### ISSUE TITLE
[Pytorch Hub] Hub CI is broken with latest master of yolo5 example. 

### ISSUE THREAD

**Issue by ailzhang** [ultralytics/yolov5#2050]
Hi! I've temporarily disabled yolo5 in Pytorch Hub CI due to an error showed up a few weeks ago. https://github.com/pytorch/hub/blob/master/scripts/run_pytorch.sh#L18 
Would you mind help tracking down the issue? Once it's fixed please let me know and I'll reenable it in CI. Thanks a lot!

**Comment by glenn-jocher** [comment]
@ailzhang by definition if this badge is green then all CI checks are passing, including hub CI:

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by glenn-jocher** [comment]
@ailzhang ah, sorry you mean the pytorch/hub repo! I was referring to the yolov5 CI checks that include hub functionality. I'll head over to the pytorch/hub repo to see what's going on.

**Comment by glenn-jocher** [comment]
@ailzhang ok I see the problem. I will submit a PR with a fix today. Thanks for letting us know!

**Comment by glenn-jocher** [comment]
@ailzhang I've updated the YOLOv5 Hub page with current metrics, an improved simplified demo, and a fix for the CI errors you were seeing. I've submitted https://github.com/pytorch/hub/pull/183 with these changes. I will close this issue here and we can move the convo over to the PR. 

Thank you for spotting this error and for notifying us of this problem. If you have any future problem please let us know and we will do our best to address them quickly.
