### ISSUE TITLE
Anchor update customization 

### ISSUE THREAD

**Issue by fahimnawaz7** [ultralytics/yolov5#2092]
## 
May I know how to update anchor boxes according to object size( width*height ) for custom dataset?

**Comment by glenn-jocher** [comment]
@fahimnawaz7 autoanchor will update anchors as necessary based on your dataset and training settings, no action is required on your part.

**Comment by bobbilichandu** [comment]
How to get the anchor boxes that are updated? If we are using the weights to convert to onnx or other formats, then we need to know the updates anchor boxes right?

Is there a way to find them?

**Comment by glenn-jocher** [comment]
@chandu1263 YOLOv5 anchors are saved as [Detect()](https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L22) layer attributes on model creation, and updated as necessary by  autoanchor evolution before training starts. Their exact location is here:
https://github.com/ultralytics/yolov5/blob/fab5085674f7748dc16d7ca25afb225fa441bc9d/models/yolo.py#L34-L35

You can examine the anchors of any trained YOLOv5 model like this:

### Input
```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True, autoshape=False)  # hub model
# -- or --
model = torch.load('yolov5s.pt')['model']  # local model

# Anchors
m = model.model[-1]  # Detect() layer
print(m.anchor_grid.squeeze())  # print anchors
```

### Output
```python
#           x     y
tensor([[[ 10.,  13.],
         [ 16.,  30.],
         [ 33.,  23.]],  # P3/8-small

        [[ 30.,  61.],
         [ 62.,  45.],
         [ 59., 119.]],  # P4/16-medium

        [[116.,  90.],
         [156., 198.],
         [373., 326.]]], dtype=torch.float16)  # P5/32-large
```

**Comment by loucif01** [comment]
@glenn-jocher i just have one question about anchor boxes in yolov5 : i have a set of regions of interests witch i got theme with some ML methods, now i want to feed theme to yolov5, i.e instead of using the predefined anchor boxes , can i modify these anchors and replace theme with the regions of interests that i have? If yes, can i use the pretrained weights or i have to train yolov5 from scratch again?

Thank you for your help :)

**Comment by glenn-jocher** [comment]
@loucif01 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.

Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e. 
```yaml
# Specify anchor count (per layer)
anchors: 3

# --OR-- Specify anchor values manually
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a Genetic Evolution (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with Best Possible Recall (BPR) as its fitness function.

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

<img width="1200" alt="AutoAnchor Screenshot" src="https://user-images.githubusercontent.com/26833433/141797929-0c8e1e88-f8d6-4caa-8ac6-785bfc675b37.png">

**No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
```shell
python train.py --noautoanchor
```

**Comment by loucif01** [comment]
@glenn-jocher thank you for your response. Ok i understand but do you think there's an other way to control yolo about the regions that it uses for prediction? because as i said i want to train it only on some regions that i have already. Do you think we can doing this for example by controlling the cells that it uses for prediction?

Thanks.

**Comment by glenn-jocher** [comment]
@loucif01 I'm not sure what you mean by cells that are used for prediction, but  if you want to train or detect on regions then I would just crop those regions first before passing them to the model.

**Comment by loucif01** [comment]
@glenn-jocher celles that the image is devided into by yolo....yeah cropping the regions is a solution but it's more useful if we can integrate that inside yolo and just redirect yolo to scan theses regions.
Thanks anyway 😊

**Comment by lakshaydulani** [comment]
> @glenn-jocher celles that the image is devided into by yolo....yeah cropping the regions is a solution but it's more useful if we can integrate that inside yolo and just redirect yolo to scan theses regions. Thanks anyway 😊

If I understand Glenn corrrectly, I want to ask the same thing.

In my use case, I want to detect only standing people in my image. So I was thinking if I can specify the anchors so that the YOLO inference works better. Please suggest as so how can we do that?

**Comment by glenn-jocher** [comment]
@lakshaydulani AutoAnchor will handle all anchors automatically, no action is required on your part. Just label your dataset accordingly (people standing) and start training. See **Train Custom Data** tutorial to get started.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by MLDavies** [comment]
I'd like to experiment with changing the anchor boxes. (I still have a lot to learn here) Is it simply done by swapping out the default anchor boxes in the yaml for my alternate boxes? Are other changes needed - particularly if my alternate boxes have 4 rather than the default 3? And what is the relationship with this process and the anchors in the hyperparameter yaml.

**Comment by glenn-jocher** [comment]
@MLDavies 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.

Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e. 
```yaml
# Specify anchor count (per layer)
anchors: 3

# --OR-- Specify anchor values manually
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a [Genetic Evolution](https://en.wikipedia.org/wiki/Genetic_algorithm) (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with [Best Possible Recall](https://en.wikipedia.org/wiki/Precision_and_recall) (BPR) as its fitness function.

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

<img width="1200" alt="Screenshot 2022-03-24 at 10 58 28" src="https://user-images.githubusercontent.com/26833433/159891298-8b15f80b-f5b0-4fa9-8824-7380bae32a76.png">

**No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
```shell
python train.py --noautoanchor
```

For more details on AutoAnchor see:
https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py

Good luck 🍀 and let us know if you have any other questions!

**Comment by lchunleo** [comment]
hi ,

 i had tried to attempt to add in additional 1 custom box to test out (yolov5l.yaml) but i got error     
"raise IndexError('index {} is out of range'.format(idx)) IndexError: index 3 is out of range". is it being hard coded that i can't extend it?

  - [12,18, 20,38, 40,28]  # Additional anchor box for P3/8

And is it correct that assuming i have not indicated any autoanchor flag, the program will use the anchors set define in the yaml file?

**Comment by glenn-jocher** [comment]
@lchunleo 👋 The error message you're seeing is caused by an incomplete or malformed `anchors` list. Each `<class 'torch.Tensor'>` within `model.yaml` should contain exactly 6 values defining 3 anchor boxes, like so:

```
anchors: [[10,13, 16,30, 33,23],
          [30,61, 62,45, 59,119],
          [116,90, 156,198, 373,326]]
```

You can see this initial anchor list in your `yolov5l.yaml` file or use this command to print your existing model anchors to console:

```shell
# show anchors for yolov5x.yml model
python -c "from models.yolo import Model; print(Model().yaml['anchors'])"
```

> And is it correct that assuming i have not indicated any autoanchor flag, the program will use the anchors set define in the yaml file?

Yes – if you do not add `--noautoanchor` flag, YOLOv5 will use AutoAnchor to automatically generate new anchors that are likely more representative of your data. During training, AutoAnchor will automatically update your anchor list after the number of epochs set by `--anchor-period`.
