### ISSUE TITLE
GPU memory can not be fully used

### ISSUE THREAD

**Issue by lsd1994** [ultralytics/yolov5#2101]
I train my custom dataset on RTX2070, 8GB. The image size is 1920 x 1080, when I use:
python train.py --data data.yaml --hyp v5s_hyp.yaml --cfg yolov5s.yaml --weights yolov5s.pt --img-size 1664 --rect --batch-size 2
It can run normally and use 2.69G GPU memory during training.
But when I increase the image size to 1696:
python train.py --data data.yaml --hyp v5s_hyp.yaml --cfg yolov5s.yaml --weights yolov5s.pt --img-size 1696 --rect --batch-size 2
The result is:
CUDA out of memory. Tried to allocate 2.96 GiB (GPU 0; 8.00 GiB total capacity; 1.34 GiB already allocated; 3.58 GiB free; 2.75 GiB reserved in total by PyTorch)

So I want to know why GPU usage have huge difference between img size 1664 and 1696, thanks.

**Comment by wudashuo** [comment]
GPU usage is not always the same, it's changing during the training process. According to my observation, usually GPU usage is higher during pre-processing. Maybe training didn't run too much memory, but it's processing the high-resolution image that occupied a lot of GPU memory?
BTW, I wonder why you raise the `img-size` so high, and batch-size is only 2? It would be very slow. If you want a higher mAP, maybe you can use yolov5m/l/x, rather than raise the `img-size` while using yolov5s.

**Comment by lsd1994** [comment]
@wudashuo Hi, thanks for quick reply.

> GPU usage is not always the same, it's changing during the training process. According to my observation, usually GPU usage is higher during pre-processing. Maybe training didn't run too much memory, but it's processing the high-resolution image that occupied a lot of GPU memory?

I see, pre-processing uses the highest GPU memory when I check GPU-Z, then memory decreases to normal.

> BTW, I wonder why you raise the `img-size` so high, and batch-size is only 2? It would be very slow. If you want a higher mAP, maybe you can use yolov5m/l/x, rather than raise the `img-size` while using yolov5s.

Thank you for advise, for now I just test different models on my computer.

**Comment by lsd1994** [comment]
It seems my pycharm problem. I run the command in pycharm and when I restart pychram I can run
python train.py --data data.yaml --hyp v5s_hyp.yaml --cfg yolov5s.yaml --weights yolov5s.pt --img-size 1920 --rect --batch-size 2
and use 3.5G GPU memory during training.
