### ISSUE TITLE
How to decrease inference video size

### ISSUE THREAD

**Issue by kaushalchapaneri-intellica** [ultralytics/yolov5#2116]
## ❔Question
Hello,

I trained on my custom dataset and it is giving good results in inference too, but the resultant video saved under runs/detect/exp(no) is of very high size. My input video is of size 279.3 MB and the output video is of size 1 GB.

## Additional context
input video details 

![Screenshot from 2021-02-02 10-37-36](https://user-images.githubusercontent.com/65006959/106555261-39b04680-6543-11eb-9c7a-9df50938666a.png)

and video after inference 

![Screenshot from 2021-02-02 10-44-57](https://user-images.githubusercontent.com/65006959/106555533-c4914100-6543-11eb-888b-5e2d8313a433.png)

One thing i noticed is Higher bit rate and different codec in output video. Can you provide any suggestion on how to control it?

please let me know if additional details required. 

Thanks a lot.

**Comment by glenn-jocher** [comment]
@kaushalchapaneri-intellica ah interesting. We used to encode outputs using the same codecs as the input video, but at some point along the line we hardcoded this codec for saving video, perhaps for cross-platform compatibility or speed. 
https://github.com/ultralytics/yolov5/blob/73a066993051339f6adfe5095a7852a2b9184c16/detect.py#L132-L136

In any case you can try to modify the fourcc code to a different codec, or perhaps alter the save_path to a different extension to indicate a different filetype to cv2, or both.

From https://docs.opencv.org/master/dd/d43/tutorial_py_video_display.html

## Saving a Video
So we capture a video and process it frame-by-frame, and we want to save that video. For images, it is very simple: just use cv.imwrite(). Here, a little more work is required.

This time we create a VideoWriter object. We should specify the output file name (eg: output.avi). Then we should specify the FourCC code (details in next paragraph). Then number of frames per second (fps) and frame size should be passed. And the last one is the isColor flag. If it is True, the encoder expect color frame, otherwise it works with grayscale frame.

FourCC is a 4-byte code used to specify the video codec. The list of available codes can be found in fourcc.org. It is platform dependent. The following codecs work fine for me.

In Fedora: DIVX, XVID, MJPG, X264, WMV1, WMV2. (XVID is more preferable. MJPG results in high size video. X264 gives very small size video)
In Windows: DIVX (More to be tested and added)
In OSX: MJPG (.mp4), DIVX (.avi), X264 (.mkv).
FourCC code is passed as `cv.VideoWriter_fourcc('M','J','P','G')or cv.VideoWriter_fourcc(*'MJPG')` for MJPG.

**Comment by glenn-jocher** [comment]
Maybe fourcc = 'X264' would be best, though I'm unclear on windows support for the codec. 

We have standardized videos for testing we use here, if we find a codec that works best on linux, macos and windows and profiles better than the current (filesize and speed both) then we can switch.
https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_landscape.mov
https://github.com/ultralytics/yolov5/releases/download/v1.0/decelera_portrait.mov

**Comment by glenn-jocher** [comment]
Nevermind, tried X264 on macos and produced errors:
```bash
OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 27 and format 'mov / QuickTime / MOV'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
```

**Comment by kaushalchapaneri-intellica** [comment]
@glenn-jocher Thanks for the detailed response. 

I tried many combinations of fourcc and video file extensions, in some of them it produced even larger file and in some, it didn't saved file with no error on terminal. With "DIVX" and ".avi" it is producing file of 967 MB, which is lesser. This is the only combination i found which generated smaller size of file. I tried this on Ubuntu 18.04
