### ISSUE TITLE
In yolov3.onnx converted from yolov3.pt, in layer ID 371, 391, output, which are boxes and which are classes?

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2131]
## ❔Question
Hello,
Thank you for sharing a great project.

The following figure shows the downloaded yolov3.pt converted to onnx using export.py and then confirmed in graph form with netron.
![image](https://user-images.githubusercontent.com/59910227/106939727-fb45a200-6763-11eb-9d2c-bbfa7a4d041d.png)

python models/export.py --weights ./weights/yolov3.pt --img 640 --batch 1

torch.onnx.export(model, img, f, verbose=False, opset_version=12, input_names=['images'],
                          output_names=['classes', 'boxes'] if y is None else ['output'])
The above function converts the downloaded yolov3.pt in export.py to onnx. Here, when y is none, output_names are classes and boxes. In the converted onnx, classes and boxes cannot be found. There are only names 371 and 391. Which of 371 and 391 are classes and which are boxes? And what is the output?

Thank you.

**Comment by zhiqwang** [comment]
Hi @leeyunhome 

All three of them seem to be **feature maps**. If you want to get the `boxes`, `scores` and `labels`, there is one procedure left to deal with, namely **post-processing**, which containing the `nms`. And now there are different ways to process this. (You could just search it on GitHub, especially in the issues of YOLOv5.)

One option is [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) in my own repo, maybe you could check it.

**Comment by leeyunhome** [comment]
> Hi @leeyunhome
> 
> All three of them seem to be **feature maps**. If you want to get the `boxes`, `scores` and `labels`, there is one procedure left to deal with, namely **post-processing**, which containing the `nms`. And now there are different ways to process this. (You could just search it on GitHub, especially in the issues of YOLOv5.)
> 
> One option is [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) in my own repo, maybe you could check it.

Hello?

Thank you so much for the answer.

With the help of @glenn-jocher:

https://github.com/ultralytics/yolov3/issues/1679#issuecomment-773573191

I modified the line and converted it back to onnx.
Here is the result:

https://github.com/ultralytics/yolov3/issues/1679#issuecomment-773640685

But I don't see the box and class explicitly, how can I check it?

In the next post of another person, the layer ID in numbers appears at first,
After that, it changed to class and box.
I don't know how to do this.
https://github.com/ultralytics/yolov3/issues/1109
![image](https://user-images.githubusercontent.com/59910227/107089141-79c44180-6841-11eb-852c-c1f980201a7f.png)
![image](https://user-images.githubusercontent.com/59910227/107089219-9ceef100-6841-11eb-8834-0ff74d980ee1.png)


Thank you.

**Comment by zhiqwang** [comment]
Also here, seems that it's a reorganization of the **feature maps**, and its meaning is also **feature maps**, there is one procedure left to deal with, namely **post-processing**, which containing the `nms`. (if it make senses, `12348` here should be the number of anchors.)

EDIT: The graph you quoted is a little weird, I'm not sure how they reorder the **feature maps** to this shape.

And the meaning of `107` in [here](https://github.com/ultralytics/yolov3/issues/1109#issuecomment-772096404) should be `102 + 4 + 1`, `4` is the meaning of `box`, `1` is `score`.

With my limited knowledge, there are two options to process the **post-process** procedure.

- As @BobLd mentioned in <https://github.com/BobLd/YOLOv3MLNet/issues/2#issuecomment-773872366>, they rewrite the **post-process** object in C#, and that's why they cited the [ops](https://github.com/BobLd/YOLOv4MLNet/blob/374faa03640ade9d3992655a7d1d978faa3f5096/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L137-L167). This adds a bit more complexity on the C# sides of things, and you can just follow this scheme.
- The second option is that we could merge the **post-process** procedure to the models as I do in my [repo](https://github.com/zhiqwang/yolov5-rt-stack), if you try [this](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) notebook, you can find the outputs are the `boxes`, `scores` and `labels` respectively.

BTW, if you want to have an impression of the **post-process**, you can check [this](https://github.com/zhiqwang/yolov5-rt-stack/blob/38bdf06e219e71f883ded4a27999c7328ca9ea58/models/box_head.py#L294) object in Python. I've refactored the **post-process** to make it more visible.
