### ISSUE TITLE
Multi-class NMS

### ISSUE THREAD

**Issue by PareshKamble** [ultralytics/yolov5#2162]
## 🚀 Feature
 Can we have multi-class NMS so that we can assign only one class per object?

## Motivation
While detecting more than one classes, most of the times, one object is detected as class A as well as class B with same or almost similar bounding box values. Ideally, one object should be labelled as only one class. Due to similar inter-class features, such multiple labelling occur.

**Comment by glenn-jocher** [comment]
@PareshKamble you are referring to single-label NMS, not single-class NMS. Multi-label NMS is enabled by default as it increases mAP. You can disable it by setting this line to False:
https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L356

You can enable agnostic NMS here, to apply NMS across all classes rather than per class:
https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L340

**Comment by PareshKamble** [comment]
Thank you @glenn-jocher 
I shall try that out right away.

**Comment by glenn-jocher** [comment]
BTW agnostic NMS can be used like this:
`python detect.py --agnostic`
https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/detect.py#L159

**Comment by iceisfun** [comment]
@glenn-jocher We have been having issues with non_max_suppression multi class trying to constrain nms to a group of classes. It seems like there is a bug in the non_max_suppression and we have been trying to hunt it down with only partial success.

I've been trying to get a full test case that exposes the issue

One useful thing here is using pickle to serialize the full pre nms data to help run minimal test cases. We just have not come up with enough concrete data for a issue report.

**Comment by glenn-jocher** [comment]
@iceisfun yes if you can spot a reproducible issue please let us know. There are two main settings in NMS, agnostic (default False) and multi-label (default True). Agnostic runs NMS on all boxes togethor rather than per class, multi-class can assign multiple classes of detection per box. You can modify these two settings below. 

> @PareshKamble you are referring to single-label NMS, not single-class NMS. Multi-label NMS is enabled by default as it increases mAP. You can disable it by setting this line to False:
> https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L356
> 
> You can enable agnostic NMS here, to apply NMS across all classes rather than per class:
> https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L340

**Comment by alucor-it** [comment]
> @iceisfun yes if you can spot a reproducible issue please let us know. There are two main settings in NMS, agnostic (default False) and multi-label (default True). Agnostic runs NMS on all boxes togethor rather than per class, multi-class can assign multiple classes of detection per box. You can modify these two settings below.
> 
> > @PareshKamble you are referring to single-label NMS, not single-class NMS. Multi-label NMS is enabled by default as it increases mAP. You can disable it by setting this line to False:
> > https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L356
> > 
> > You can enable agnostic NMS here, to apply NMS across all classes rather than per class:
> > https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L340

Hi,
Should I change "multi_label &= nc > 1" to multi_label &= False ?

Thanks

**Comment by abhiagwl4262** [comment]
> @glenn-jocher We have been having issues with non_max_suppression multi class trying to constrain nms to a group of classes. It seems like there is a bug in the non_max_suppression and we have been trying to hunt it down with only partial success.
> 
> I've been trying to get a full test case that exposes the issue
> 
> One useful thing here is using pickle to serialize the full pre nms data to help run minimal test cases. We just have not come up with enough concrete data for a issue report.



I am also facing the issues with nms - 
[OP_ERROR] <class 'RuntimeError'> : Trying to create tensor with negative dimension -1905798436: [-1905798436]
when I call torchvision.ops.nms

**Comment by glenn-jocher** [comment]
@abhiagwl4262 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by DoSquared** [comment]
> @iceisfun yes if you can spot a reproducible issue please let us know. There are two main settings in NMS, agnostic (default False) and multi-label (default True). Agnostic runs NMS on all boxes togethor rather than per class, multi-class can assign multiple classes of detection per box. You can modify these two settings below.
> 
> > @PareshKamble you are referring to single-label NMS, not single-class NMS. Multi-label NMS is enabled by default as it increases mAP. You can disable it by setting this line to False:
> > https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L356
> > 
> > You can enable agnostic NMS here, to apply NMS across all classes rather than per class:
> > https://github.com/ultralytics/yolov5/blob/ace3e02e406307ed0cebc25aebe15835767107b2/utils/general.py#L340

Where can i disable the multi label please? in which script?
