### ISSUE TITLE
Multi channel images

### ISSUE THREAD

**Issue by tntrela** [ultralytics/yolov5#2177]
## ❔Question
Hello everyone!
I would like to ask if there is a way to use images with more than 3 channels as inputs? Of course training of such models will start from zero.
Thank you!

**Comment by glenn-jocher** [comment]
@tntrela you can construct a model with any input channel count using pytorch hub, and populate it with any other trained weights you want for matching shape layers. 

The issue is that you'd need to modify the dataloader to accept and process hyperspectral images. It's not too complicated, but not part of the default dataloader as the addressable market for this workflow is small.

**Comment by FATMACEYDAGOKCE** [comment]
hello everyone I just want to make my image have 5 channels and then start to training how can I handle this parameters

**Comment by ElMahdiAboulmanadel** [comment]
I have the same question, how can I use a 5 channels images dataset?

**Comment by adiren7** [comment]
@tntrela  have you succeeded to train your model with multispectral images ? if yes , can you please provide me with the changes of the dataloader
