### ISSUE TITLE
dataset in a google bucket

### ISSUE THREAD

**Issue by kimalaacer** [ultralytics/yolov5#2183]
Q: 
Is there a way to reference the dataset for train/val located in a google bucket. 
it seems that the loadImagesandLabels module adds a local pwd to the links in data.yaml.
I am trying to find a way to get dataset from a google bucket during training, and set save_dir as a google bucket.
my current approach is to copy the dataset in another layer within the container image - but did not test it and need to find a way to save the results back to the bucket.

Additional context
1. trained locally (jupyter with 4 T4 GPU) on a custom dataset with good results. 
2. now attempting to train the same dataset using google ai-platform(with 2 V100).

**Comment by glenn-jocher** [comment]
@kimalaacer yes, you can mount a GCP bucket for example to a GCP VM instance, but this is not recommended, as this is a network connection that acts as a local storage medium rather than an actual local storage medium. The only time this is recommended is if you are training with `--cache` option enabled, meaning that your dataset is read only once before training starts and stored in system RAM for all training. See https://cloud.google.com/compute/docs/disks/gcs-buckets for bucket mounting directions.

For all other use cases it's recommended you copy your remote data to local storage first before training, i.e. with a gsutil command like `gsutil cp -r gs://bucket/dataset .`

**Comment by kimalaacer** [comment]
@glenn-jocher 
Thanks for your prompt answer.  I've always used --cache-images flag.
 
I've modified train.py and tested it locally and was able to use local inputs and gsutil to copy runs/ to my bucket. 

I am trying to  build a container to run yolov5 on ai-platform. 
I am trying to find a way to run the container with inputs from a local bucket, such as if opt.bucket="my-bucket" 
data= my-bucket/data  instead of yolov5/data \
weights= my-bucket/runs/train/exp0_*/weights/last.pth.
it seems pytorch does not have (that I could find) a built-in module like in tensorflow where you can use tf.io.gfile. 
I will keep trying?

I also found reference in your docker to copy output to bucket, 
may-be i can use that to copy inputs to tmp/ in docker, and save output in out-put_tmp, copy out-put_tmp bucket, then remove it at end of training.

**Comment by glenn-jocher** [comment]
@kimalaacer yes we have an optional --bucket argument in train.py that will log and upload artifacts (trained models) to a GCP bucket. This uses gsutil commands though. A _mounted_ bucket should behave identically to a local directory, so once mounted you can use normal bash commands to move files back and forth, i.e. `cp -r dir/* mounted_dir/`

**Comment by glenn-jocher** [comment]
@kimalaacer also note the docker container commands allow for local directory access. We use this for training COCO without actually having COCO in the container:
https://github.com/ultralytics/yolov5/blob/3e560e2faeeaba00adbb2c8e72716c0a133dd917/Dockerfile#L35-L37

**Comment by mbenami** [comment]
Hi @kimalaacer 
did you succeed in training yolov5 on ai-platform ? 
can you share some insight on the process? 
thanks
