### ISSUE TITLE
Does YOLOv5 now support automatic Multi GPU?

### ISSUE THREAD

**Issue by wiseyoungbuck** [ultralytics/yolov5#2197]
## ❔Question
When I run the standard training script, all four of my GPUs are showing data being loaded into memory in nvidia-smi even without the `-m torch.distributed.launch --nproc_per_node 4` parameter. Does YOLOv5 now automatically detect and support multi-gpu? If not I'm trying to understand the behavior.

**Comment by glenn-jocher** [comment]
@wiseyoungbuck yes, YOLOv5 will use all available devices by default. You can specify individual devices with --device 3, or groups of devices with --device 0,1,2,3 or CPU inference with --device cpu. 

For best Multi-GPU performance though it is highly recommended you use `torch.distributed.launch` rather than using the default train command. See Multi-GPU tutorial for details:
https://docs.ultralytics.com/yolov5

**Comment by wiseyoungbuck** [comment]
Okay thank you @glenn-jocher
