### ISSUE TITLE
Deploy yolov5 on lattepanda or jetson ? (for inference)

### ISSUE THREAD

**Issue by constantinfite** [ultralytics/yolov5#2229]
## ❔Question
I would like to deploy yolov5 on an hardware but I don't know which one the optimal.

Does the GPU integrated in the lattepanda is powerful enough to run inference ?
It is a : Intel HD Graphics, 12 EUs @200-500 Mhz, single-channel memory.

**Comment by glenn-jocher** [comment]
@constantinfite if you'd like to run inference on a device, I would highly recommend a unix device over a windows device. Nvidia has some good solutions, like the jetson device you mentioned, and Google makes the Coral Edge TPU which works well also. Both of these work well with YOLOv5.

**Comment by constantinfite** [comment]
@glenn-jocher 
Thank you, is there a favorite between both ? 
In term of consumption, installation, performance ? (from what you've heard)

**Comment by glenn-jocher** [comment]
@constantinfite that's a good question! We are aiming to bring on a more dedicated hardware engineer to better support these use cases, but in the meantime we don't have experience with these, most of our work is on iOS and Android devices, and in that field iOS devices are much easier to develop for and are more performant due to their close hardware/software/firmware coupling.
