### ISSUE TITLE
New mAP record achieved!

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#226]
After merged this commit: https://github.com/ultralytics/yolov5/commit/37e13f88467d29bfb5461ae041fa88e211fbc7ca

which add a mosia border, now the model trains more faster to high mAP, highest score I got on custom data achieved 0.96 now (previously maxium 0.85).

Can u elabrate what exactly this updates does and what's the insight behind it?

**Comment by glenn-jocher** [comment]
@jinfagang that exciting, but I'm afraid that the mAP increase must be due to another cause than the mosaic border update commit. 

The commit reorganizes the code to allow for changing the mosaic shape at different epochs (see below), but it does not actually change the training unless the added lines in train.py are uncommented. The idea was that hopefully this might allow for learning larger boxes occasionally, for improved large-object results at higher img_sizes, but that's just a theory at the moment, we've not actually had time to test this fully.

The change may also be due to autoanchor, or a change in settings/hyps, or the last remote possibility is that it may simply be randomly different (due to possible lack of full determinism in the training).


![train_batch10](https://user-images.githubusercontent.com/26833433/85977260-1f046680-b991-11ea-93ab-c5c3c09a8b74.jpg)


![train_batch0](https://user-images.githubusercontent.com/26833433/85977262-20ce2a00-b991-11ea-89be-09b3bdcbedfd.jpg)

**Comment by lucasjinreal** [comment]
@glenn-jocher  new updated mosiac seems randomly use mosiac not all training samples using it. this might helped keep original size of my small targets.

the final mAP really surprised me and this dataset actually tested with many other models such as fastercnn, centernet, fcos, this is just the best version for now.

**Comment by glenn-jocher** [comment]
@jinfagang hmm that's strange. Mosaic mainly benefits large objects, so you might simply want to try training without it. You can do this using `python train.py --rect`
