### ISSUE TITLE
How to combine tiled inference results?

### ISSUE THREAD

**Issue by ok4d4** [ultralytics/yolov5#2301]
## ❔Question
Hello, I read #1772 and found out that cropping is necessary when run inference on high resolution images. However, I don't know how to write the code after read detect.py in the [xview-yolov3](https://github.com/ultralytics/xview-yolov3). Please help me.

## Additional context
In particular, I don't know what to do when the border of an object crosses the area to be cropped.

**Comment by glenn-jocher** [comment]
@ok4d4 YOLOv5 does not supply or support tiled (or 'sliding window') inference. 

You can find working examples of this in https://github.com/ultralytics/xview-yolov3, where it has been implemented for inference of high resolution satellite imagery.

**Comment by ok4d4** [comment]
Thanks for replying.
I read the code, but unfortunately I couldn't understand some parts of it, so I would like to know.
I understood the clipping and inference methods, but did not understand how to combine them.
If I combine them as they are, I think they will be out of alignment. 
![cropandmerge](https://user-images.githubusercontent.com/75909342/109306508-9cff7100-7882-11eb-9ea1-7b424dfc3411.jpg)
Thanks for the nice project.... Please help me!

**Comment by glenn-jocher** [comment]
@ok4d4 large object merging would be an additional step, which I would say is not necessary because if you have large objects there no point in running inference very high resolutions.

The sliding window inference system in ultralytics/xview-yolov3 automatically merges small objects during NMS and through the use of overlapping windows.

**Comment by ok4d4** [comment]
Thanks for the reply!
Where is the sliding window inference system implemented? In the detect.py, I could found a code that 
```
# forward scan
y2 = min((i + 1) * length, img.shape[1])
y1 = y2 - length
x2 = min((j + 1) * length, img.shape[2])
x1 = x2 - length
```
but this doesn't seem to be overlapping.
I would appreciate it if you could point me to it.

**Comment by glenn-jocher** [comment]
@ok4d4 it's not implemented anywhere in this repo.

**Comment by ok4d4** [comment]
I'm sorry, can I make an issue in [https://github.com/ultralytics/xview-yolov3/](https://github.com/ultralytics/xview-yolov3/) ?

**Comment by glenn-jocher** [comment]
@ok4d4 yes if you have questions regarding other repos you should raise them there.

**Comment by HissaanAli** [comment]
> Thanks for replying.
> I read the code, but unfortunately I couldn't understand some parts of it, so I would like to know.
> I understood the clipping and inference methods, but did not understand how to combine them.
> If I combine them as they are, I think they will be out of alignment.
> ![cropandmerge](https://user-images.githubusercontent.com/75909342/109306508-9cff7100-7882-11eb-9ea1-7b424dfc3411.jpg)
> Thanks for the nice project.... Please help me!

Hi, Did you find any solution yet or made your own ? I'm stuck with the same problem

**Comment by glenn-jocher** [comment]
@HissaanAli I'd try to avoid tiling inference, i.e. simply run detect.py at batch-size 1 with a higher resolution: python detect.py --img 1920 or --img 3840 etc.

If you absolutely need tiled inference SAHI might be a good option.

**Comment by ch-hristov** [comment]
@glenn-jocher I've been trying to avoid tile inference but can't seem to understand how to avoid it properly. 

Here's the setup - original image 7000 x 4000, tiling with 50% overlap each tile is 1280x1280, padded with black pixels if over this. After running what you suggested on Sep 11 with img size 1920 or much larger (tried even 7000) I get results which have very large labels. Also what happens if you run it with very small images for example my input can be 7k by 4k but then next one can be 1k x 1k?

The results with tiling look better and also then I don't need to guess the img size parameter I could be wrong tho. How do you merge duplicate annotations across tiled predictions in that repository? In DarkHelp there's: [this](https://www.ccoderun.ca/darkhelp/api/classDarkHelp_1_1Config.html#add15d57a384c7eb827078b4b3a279b79). Is there an equivalent?

**Comment by ahmadSum1** [comment]
> @HissaanAli I'd try to avoid tiling inference, i.e. simply run detect.py at batch-size 1 with a higher resolution: python detect.py --img 1920 or --img 3840 etc.
> 
> If you absolutely need tiled inference SAHI might be a good option.

@HissaanAli Thank you for suggesting SAHI, it makes tiling inference seamless.
Btw, why would you be against tailing and prefer inference at a higher resolution? Is there any major drawback in tiling other than a longer run time?

**Comment by glenn-jocher** [comment]
@ahmadSum1 In general, tiling inference can lead to accuracy loss due to the potential object detection errors and false negatives introduced during tile boundary processing. Running detect.py at a higher resolution can mitigate some of these issues while retaining the accuracy. However, if tiling is necessary due to hardware constraints or other reasons, SAHI can be a helpful option to enable easy implementation of tiling inference.

**Comment by samyuh** [comment]
@glenn-jocher Hello! 

I have a model trained on 640x640 images. Can I run inference on 2000x2000 images using detect? How is the upscale handled? Shouldn't the model and the inference be on the same resolution?

**Comment by glenn-jocher** [comment]
@samyuh Typically, the input resolution during inference should match the resolution used during training for optimal results. Nevertheless, YOLOv5 can handle upscaling during inference, but it might lead to reduced accuracy due to scaling artifacts. It's recommended to evaluate the model on larger images by retraining it on a larger dataset.

**Comment by kyra-smith** [comment]
Hello! Thanks for your answers here, @glenn-jocher. I have a question similar to @samyuh: 

I have 2 aerial images (19072x17600) which I split into several hundred input images of size 640 with a spatial resolution (pixel size) of 4 cm (I need the model to be able to detect trees at various spatial resolutions). I trained, validated, and tested a custom object detection model using these images and the pre-weighted model yolov8m.pt. 
The custom model performs well on the test images (size 640, spatial resolution 4cm), but when I try to run inference on a complete aerial image (size 19072x17600, spatial resolution 4 cm) it is unable to detect any trees. Why is this the case, if both the training images and the inference image have the same spatial resolution?

I used the pre-weighted model yolov8m.pt to train my custom model. 
Unfortunately, I cannot train my model on larger images due to lack of available data. 

I would appreciate very much any suggestions you can provide!

**Comment by glenn-jocher** [comment]
@kyra-smith It seems like the model may struggle with detecting objects at the larger scale due to the discrepancy in image size between the training and inference. While the spatial resolution is consistent, the model might not be robust enough to generalize to the larger image. Upscaling the model isn't recommended due to potential loss of accuracy. However, if additional data isn't available, you might consider applying image preprocessing techniques such as super-resolution or tiling the larger images into smaller segments for inference.
