### ISSUE TITLE
The "fitness" function  in train.py.

### ISSUE THREAD

**Issue by snop222** [ultralytics/yolov5#2303]
In the train.py, line 29, as folowing:

_from utils.general import labels_to_class_weights, increment_path, labels_to_image_weights, init_seeds, \\
    fitness, strip_optimizer, get_latest_run, check_dataset, check_file, check_git_status, check_img_size, \\
    check_requirements, print_mutation, set_logging, one_cycle, colorstr_

The "fitness" actually is a function defined in "utils/metrics.py".
Why it is imported "from" by "utils.general" ?
But, the train.py could be running with no error report ?

**Comment by glenn-jocher** [comment]
@snop222 fitness() defines a model fitness based on a weighted combination of metrics. We use fitness for hyperparameter evolution and to decide when to save a new best.pt checkpoint. 
https://github.com/ultralytics/yolov5/blob/efa4946d158f4042890b243cf9314aa62dac83e4/utils/metrics.py#L12-L16

The function itself is in metrics.py as you noted. In train.py it could be imported directly from metrics.py, it is imported from general.py since it is already available there due to a previous import:
https://github.com/ultralytics/yolov5/blob/efa4946d158f4042890b243cf9314aa62dac83e4/utils/general.py#L21

**Comment by snop222** [comment]
Thank you vrey much.

**Comment by patel-zeel** [comment]
@glenn-jocher Is there any option to manually set the weights for the fitness function or define our own fitness function? We are working on a project with a constraint like "Maximize recall where precision is at least 50%". If you think this can be useful to a broader community, I'd be happy to contribute to the `ultralytics` library to make this possible.
