### ISSUE TITLE
Let's talk about the design concept of FCOS structure？

### ISSUE THREAD

**Issue by TAOSHss** [ultralytics/yolov5#2306]
## ❔Question

Let's talk about the design concept of FCOS structure in YOLOV5

**Comment by glenn-jocher** [comment]
@TAOSHss hi there! FCOS is a very interesting paper, I especially liked the left-right-top-bottom interpretation of the regression space. 

It would be an interesting experiment replacing the existing xywh boxes with lrtb boxes.

**Comment by TAOSHss** [comment]
What I said is that in the YOLOV5 network structure, the initial input part is called FCOS, but the function of this structure is to slice a large image into 4 small size and thin inputs




---Original---

**Comment by TAOSHss** [comment]
Focus not FCOS，im so sorry



---Original---

**Comment by glenn-jocher** [comment]
@TAOSHss Oh, yes FCOS is a separate architecture that was quite performant: https://arxiv.org/abs/1904.01355

Focus() module in YOLOv5 is a space-to-channel conversion that helps speed up the the first convolution operations, which are otherwise quite slow due to the very large grids in the first convolution (i.e. native resolution image).
