### ISSUE TITLE
Improve Validation Visualization

### ISSUE THREAD

**Issue by thhart** [ultralytics/yolov5#2384]
## 🚀 Feature
Improve validation output during training.

## Motivation

IMHO it could be very helpful to improve the visualization output during training already. Either by distributing into Wandb/Tensorboard or by output image results of validation since these are calculated anyway. Of course this would increase storage consumption during training but the advantages are very big.

Beside of simple monitor the training process this would also help to isolate hardest training examples at earliest possible.

Is there such a mechanism switch already available which would enhance the training output already?
Do you have any hints what might be further beneficial to achieve the same goals other than post evaluating the model?

**Comment by glenn-jocher** [comment]
@thhart there is a W&B PR which more formally implements your suggestions, and also the validation labels and predictions are plotted for the first and last epochs by default and stored in your runs/train/exp directory. You can modify this very simply here to print these jpgs every epoch, and every batch if you'd like.

We will not enable this by default however due to the much slower performance and the much large storage requirement it would introduce on all users compared to the current implementation.

https://github.com/ultralytics/yolov5/blob/cd8ed3521d98ea120d07f57ea5372c4b375241ca/test.py#L208-L214
