### ISSUE TITLE
Get COCO metrics?

### ISSUE THREAD

**Issue by a-esp-1** [ultralytics/yolov5#2390]
## ❔Question

Hi,

 I just cloned the repo and i was asking myself how to see COCO metrics on my own dataset when test.py is used.

Thank you.

**Comment by glenn-jocher** [comment]
@a-esp-1 generally the COCO metrics are only run on the COCO dataset. 

If you have a COCO-format annotations JSON file for your custom dataset you can try passing it here:
https://github.com/ultralytics/yolov5/blob/ba18528b4737a4b08b55653c54f3d3e830f8e151/test.py#L249

**Comment by FAIRMLSAT** [comment]
@glenn-jocher I have an annotations file for my custom dataset that I add the path to in test.py. However, I recieve this "Evaluating pycocotools mAP... saving test/OneAxisRotation/best_TM2_TM1NF41_predictions.json...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
pycocotools unable to run: Results do not correspond to current coco set"

Has the cocoeval integration been verified for custom dataset?

@a-esp-1 did you get it to work?

**Comment by glenn-jocher** [comment]
@FAIRMLSAT use the latest code and define your annotations file here:
https://github.com/ultralytics/yolov5/blob/fafab8405d63b95ce103fffb2cd70d31a888e04e/val.py#L266

**Comment by FAIRMLSAT** [comment]
@glenn-jocher new issue. Thought he annotations are for custom dataset, the algorithm starts unzipping the coco dataset. Do you have any implementations to tackle this?

**Comment by glenn-jocher** [comment]
@FAIRMLSAT 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by engrjav** [comment]
any solution to it?

**Comment by engrjav** [comment]
@FAIRMLSAT  did you find any solution

**Comment by 1757525671** [comment]
i meet the same problem,

>

**Comment by imadgohar** [comment]
@FAIRMLSAT  did you got coco metric on custom dataset?
If yes, can you please share your experience.
