### ISSUE TITLE
Pretraining weights to do additional transfer learning

### ISSUE THREAD

**Issue by oclerc** [ultralytics/yolov5#2413]
Hi everyone,

I'm using yolov5m to do some transfer learning on my own. I'm pretraining the images with the FLIR thermal images dataset which has 3 classes. For which I trained where in the cfg file I wrote nc=3. After this training, I'm trying to train the model on a smaller thermal images dataset which only has one class, i.e. nc=1. When training using as initial weights the ones obtained from the pretraining stated above I get the following error:

  File "train.py", line 532, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 154, in train
    ema.ema.load_state_dict(ckpt['ema'][0].float().state_dict())
  File "/home/loulive/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for model.24.m.0.weight: copying a param with shape torch.Size([24, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 192, 1, 1]).
	size mismatch for model.24.m.0.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for model.24.m.1.weight: copying a param with shape torch.Size([24, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 384, 1, 1]).
	size mismatch for model.24.m.1.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for model.24.m.2.weight: copying a param with shape torch.Size([24, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 768, 1, 1]).
	size mismatch for model.24.m.2.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([18]).

I understand that since I don't have the same number of classes, this could be the reason for such an error. But as far as I know, I can use weights trained on the coco dataset which has nc=80. So why can't I do it there? Is there a way to still do what I'm trying?

Thanks!

**Comment by glenn-jocher** [comment]
Resuming an interrupted training run is simple. There are two options:
```bash
python train.py --resume  # resume latest training
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

If you started the training with a multi-GPU command then you must resume it with the same exact configuration (and vice versa). Multi-GPU resume commands are here, assuming you are using 8 GPUs:
```bash
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume  # resume latest training
python -m torch.distributed.launch --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

Note that you may not change any settings when resuming, **you must resume with the same exact settings** (`--epochs`, `--batch`, `--data`, etc).

Your problem is caused by attempting to change settings when resuming. You should instead start a new training using your pretrained last.pt checkpoint:
```bash
python train.py --weights path/to/last.pt --data any_dataset.yaml
```

**Comment by oclerc** [comment]
Hi, I'm sorry I think I wasn't really clear in my explanations. I'm not trying to resume but I'm training with a dataset with 3 classes. Extracting the best weights of it and then using them to train a different dataset with only one class. I think that's why I have a problem with the size of the weights as the first has (3+5)*3 = 24 filters and the second has (1+5)*3 = 18 filters. The commands I'm using are the following:

#First train with FLIR that has three classes
python3 train.py  --batch 16 --epochs 300 --img-size 640 --data data/flir.yaml --cfg yolov5m_flir.yaml --weights yolov5m.pt

#Then train from those FLIR trained weights the puddle dataset that has one class
python3 train.py  --batch 16 --epochs 300 --img-size 640 --data data/puddle.yaml --cfg yolov5m_puddle.yaml --weights runs/train/exp/weights/best.pt

where I have nc = 3 in yolov5m_flir.yaml and nc = 1 in yolov5m_puddle.yaml.

Why does transfer learning works when using --weights yolov5m.pt but not when using --weights runs/train/exp/weights/best.pt ?

Thanks

**Comment by glenn-jocher** [comment]
@oclerc the workflow you are describing is a standard workflow, you should be able to run this without issue. If you are running into issues your code or your models may be out of date or out of sync with each other. I would git pull or simply clone again and start from there.

You can verify this very easily (i.e. 10 minutes in the colab notebook) by training 10 class VOC model starting from a 80 class COCO128 model:

```
python train.py --weights yolov5s.pt --data coco128.yaml --epochs 3
python train.py --weights runs/train/exp/weights/best.pt --data voc.yaml --epochs 3
```

**Comment by glenn-jocher** [comment]
@oclerc also the --cfg argument is not required in your commands. See Train Custom Data for best practices regarding training commands:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [ONNX and TorchScript Export](https://docs.ultralytics.com/yolov5/tutorials/model_export)
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by PPZPPZ** [comment]
when I run python train.py --resume runs/train/yolov3-Focus/weights/last.pt ,the following error occurred
28      [27, 22, 15]  1    179500  models.yolo.Detect                      [20, [[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]], [256, 512, 1024]]
Model Summary: 334 layers, 61673516 parameters, 61673516 gradients, 39.4 GFLOPS

Transferred 432/440 items from runs/train/yolov3-Focus/weights/last.pt
Scaled weight_decay = 0.00036
Optimizer groups: 75 .bias, 75 conv.weight, 72 other
Traceback (most recent call last):
  File "train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 156, in train
    ema.ema.load_state_dict(ckpt['ema'].float().state_dict())
  File "/home/ubuntu/.conda/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for model.28.anchors: copying a param with shape torch.Size([3, 3, 2]) from checkpoint, the shape in current model is torch.Size([3, 4, 2]).
        size mismatch for model.28.anchor_grid: copying a param with shape torch.Size([3, 1, 3, 1, 1, 2]) from checkpoint, the shape in current model is torch.Size([3, 1, 4, 1, 1, 2]).
        size mismatch for model.28.m.0.weight: copying a param with shape torch.Size([75, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([100, 256, 1, 1]).
        size mismatch for model.28.m.0.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([100]).
        size mismatch for model.28.m.1.weight: copying a param with shape torch.Size([75, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([100, 512, 1, 1]).
        size mismatch for model.28.m.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([100]).
        size mismatch for model.28.m.2.weight: copying a param with shape torch.Size([75, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([100, 1024, 1, 1]).
        size mismatch for model.28.m.2.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([100]).
I did not modify any parameters，but the printed anchors have changed. This problem also occurs when I run evolve

**Comment by glenn-jocher** [comment]
@PPZPPZ 👋 Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your issue. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by isomatical** [comment]
Hi, I met the same problem, did you finally solve it?

**Comment by shining-love** [comment]
> Hi, I met the same problem, did you finally solve it?

hello, have you solved this problem?

**Comment by glenn-jocher** [comment]
@isomatical @yang-gis transfer learning is super easy. You just train one model and then point to it using --weights path/to/best.pt to start training another model. Datasets can be completely different. Nothing special is needed.

You can verify this very easily (i.e. 10 minutes in the colab notebook) by training 10 class VOC model starting from a 80 class COCO128 model:

```
python train.py --weights yolov5s.pt --data coco128.yaml --epochs 3
python train.py --weights runs/train/exp/weights/best.pt --data voc.yaml --epochs 3
```

**Comment by shining-love** [comment]
> @isomatical @yang-gis transfer learning is super easy. You just train one model and then point to it using --weights path/to/best.pt to start training another model. Datasets can be completely different. Nothing special is needed.
> 
> You can verify this very easily (i.e. 10 minutes in the colab notebook) by training 10 class VOC model starting from a 80 class COCO128 model:
> 
> ```
> python train.py --weights yolov5s.pt --data coco128.yaml --epochs 3
> python train.py --weights runs/train/exp/weights/best.pt --data voc.yaml --epochs 3
> ```

Thank you very much. At that time, the problem seemed not as simple as you described, but I have solved it.It is important to note that when loading your own trained model as a migration model, it is important to reload the model and set ema to NONE so that the pre-training parameters of the Detect layer are not used at load time.Why do authors always say that 80 Coco128 models can be migrated? That's because 80 Coco128 models don't have EMA as a key value pair at all.

**Comment by glenn-jocher** [comment]
@yang-gis no, no extra steps are required. EMA is set to None upon training completion automatically. 

Just follow my steps above, nothing else.

**Comment by shining-love** [comment]
> @yang-gis no, no extra steps are required. EMA is set to None upon training completion automatically.
> 
> Just follow my steps above, nothing else.

import glob
import math
import os
import random
import shutil
import subprocess
import time
from copy import copy
from pathlib import Path
from sys import platform

import cv2
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torchvision
import yaml
from scipy.signal import butter, filtfilt
from tqdm import tqdm

from . import torch_utils  #  torch_utils, google_utils




def create_pretrained(f='weights/best.pt', s='weights/pretrained.pt'):  # from utils.utils import *; create_pretrained()
    # create pretrained checkpoint 's' from 'f' (create_pretrained(x, x) for x in glob.glob('./*.pt'))
    x = torch.load(f, map_location=torch.device('cpu'))
    x['optimizer'] = None
    x['training_results'] = None
    x['epoch'] = -1
    x['model'].half()  # to FP16
    x['ema'] = None
    for p in x['model'].parameters():
        p.requires_grad = True
    torch.save(x, s)
    print('%s saved as pretrained checkpoint %s, %.1fMB' % (f, s, os.path.getsize(s) / 1E6))

**Comment by shining-love** [comment]
> @yang-gis no, no extra steps are required. EMA is set to None upon training completion automatically.
> 
> Just follow my steps above, nothing else.

This will solve the problem.

**Comment by shining-love** [comment]
> @yang-gis no, no extra steps are required. EMA is set to None upon training completion automatically.
> 
> Just follow my steps above, nothing else.

For your yolov5-5.0, x['ema'] = None is very important

**Comment by shining-love** [comment]
> @yang-gis no, no extra steps are required. EMA is set to None upon training completion automatically.
> 
> Just follow my steps above, nothing else.

As you can see, your YOLOV5S, YOLOV5M, YOLOV5L models do not have EMA as a key value pair.So you can transfer learning directly.

**Comment by glenn-jocher** [comment]
@yang-gis there you are not understanding. EVERY single fully trained YOLOv5 model will have EMA=None, no matter if it is an official model or your own custom model.

As I said before 
> @isomatical @yang-gis transfer learning is super easy. You just train one model and then point to it using --weights path/to/best.pt to start training another model. Datasets can be completely different. Nothing special is needed.

**Comment by yang-gis** [comment]
> n

That's embarrassing. I don't know why I saved Best. pt with EMA.

**Comment by shining-love** [comment]
> @yang-gis there you are not understanding. EVERY single fully trained YOLOv5 model will have EMA=None, no matter if it is an official model or your own custom model.
> 
> As I said before
> 
> > @isomatical @yang-gis transfer learning is super easy. You just train one model and then point to it using --weights path/to/best.pt to start training another model. Datasets can be completely different. Nothing special is needed.

That's embarrassing. I don't know why I saved Best. pt with EMA.

**Comment by glenn-jocher** [comment]
@yang-gis if your checkpoint has an EMA then it has not completed training. 

You can strip it's training attributes manually if you want using the strip_optimizer() function, though then you will not be able to --resume training with it.
https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/utils/general.py#L566-L580

**Comment by glenn-jocher** [comment]
@yang-gis strip_optimizer() is called automatically after training completes:
https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/train.py#L469-L472

**Comment by shining-love** [comment]
> @yang-gis strip_optimizer() is called automatically after training completes:
> https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/train.py#L469-L472
Thank you. That's very clear.I should have looked at the code more closely.

**Comment by David-19940718** [comment]
Today, I met the same problem and solved it.
The key point that how to solve this problem is the `optimizer` setting.
Obviously, the author did not explain clearly.
Actually, the solution is very simple which you keep resume your custom task utill the training phase completely, and then you can retry transfer again!  This time you might success without surprisingly.
A `magic` code line you can look this [train.py]

`
        # Strip optimizers
        final = best if best.exists() else last  # final model
        for f in last, best:
            if f.exists():
                **strip_optimizer(f)**  # strip optimizers
`

The optimizer will be stripped when the train process ending. Therefore, if the model is not fully trained, this line of code will not take effect. Hope for help u!

**Comment by glenn-jocher** [comment]
@David-19940718 thank you for sharing your solution! Your observation about the optimizer setting is insightful. Indeed, the `strip_optimizer()` function is automatically called after the training process completes, ensuring the model is prepared for transfer learning. Your input is valuable for the community. If you have any further questions or insights, feel free to share them.

**Comment by seed3201** [comment]
您好，我也在使用YOLOv5和FLIR的ADAS热图像数据集做迁移学习。我在使用YOLOv5s预训练权重训练FLIR的仅热图像时，所有参数都未调整，mAP50达到0.81，mAP达到0.42。即使不做训练，用预训练的权重直接测试验证集，mAP50也可以达到0.62。参考github上其他人训练出的mAP50仅0.58，我训练的值似乎过高了。请问您当时是否训练出这样高的值？

**Comment by pderrenger** [comment]
您好，这样的数值并不罕见：COCO 预训练在 FLIR 的 person/bicycle/car 上常能直接得到 mAP50≈0.6，微调到 ~0.8 也可能；为排除虚高，请确保无数据泄漏（按序列/视频分割 train/val）、data.yaml 类别顺序与名称与标注一致（若直接评估 yolov5s.pt，请确认0/1/2正对应person/bicycle/car），并用统一评估命令复现：python val.py --weights runs/train/exp/weights/best.pt --data flir.yaml --img 640 --conf 0.001 --iou 0.6 --task val；如仍异常，请贴出你的评估命令、data.yaml 和划分方式我们再看。
