### ISSUE TITLE
When i give image size other than model (416) to test.py my anchors misplace on test labels & test predict:

### ISSUE THREAD

**Issue by maheshmechengg** [ultralytics/yolov5#2464]
When i give image size other than model (416) to test.py my anchors misplace on test labels & test predict:
![image](https://user-images.githubusercontent.com/49720282/110890400-f9986c80-8315-11eb-8225-5dcc53b5e5fe.png)

_Originally posted by @maheshmechengg in https://github.com/ultralytics/yolov5/issues/2437#issuecomment-797219123_

**Comment by maheshmechengg** [comment]
Glen i created as new issue. Labels are correct but those are with respect to image size 1000x1000. So issue i am getting is when i test with other image size than 416x416 my labels misplaced.
![image](https://user-images.githubusercontent.com/49720282/111062474-03190480-84cf-11eb-9972-ea203551599f.png)

**Comment by glenn-jocher** [comment]
@maheshmechengg YOLO labels are normalized, they are independent of image size.

If you are seeing incorrect train*.jpg or test*.jpg labels then it is because your labels are incorrect. See Train Custom Data Tutorial for guidance on creating labels in YOLO format:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

### 2. Create Labels

After using a tool like [CVAT](https://github.com/opencv/cvat), [makesense.ai](https://www.makesense.ai/) or [Labelbox](https://labelbox.com/)  to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="450" src="https://user-images.githubusercontent.com/26833433/98809572-0bc4d580-241e-11eb-844e-eee756f878c2.png"></p>

**Comment by maheshmechengg** [comment]
Thanks Glen, 
Yes we are following the labelling format & process correctly. What i had reported is only true for 'test.py' & so i am concerned & felt that i must report that.
Please find here predicted results with detect.py here:
![image](https://user-images.githubusercontent.com/49720282/111096300-36a66e00-8565-11eb-917a-a3355c3ea378.png)

**Comment by glenn-jocher** [comment]
@maheshmechengg ah, great, it seems you are getting good results with detect.py. 

If only your test.py results are incorrect, I'm not sure what could be the cause. Perhaps this may be caused by out of date or modified code. If I run the basic COCO128 3 epoch training in our Colab notebook all test*.jpg boxes are correct (box labels and predictions):
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

![image](https://user-images.githubusercontent.com/26833433/111097723-4e4b0b80-84ff-11eb-8260-b9c4d64b8490.png)
