### ISSUE TITLE
GeForce RTX 3070: Cuda out of memory

### ISSUE THREAD

**Issue by buimanhlinh96** [ultralytics/yolov5#2510]
Hi @glenn-jocher ,
I am training yolov5l on GeForce RTX 3070. My command line:
python3 train.py --img 512 --batch-size 16 --epochs 50 --data coco_custom.yaml --cfg yolov5l_china.yaml --weights model_23012021.pt --name yolov5l_results --cache --nosave --hyp hyp.finetune.yaml --device 0

_But i met : RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 7.79 GiB total capacity; 6.12 GiB already allocated; 12.31 MiB free; 6.17 GiB reserved in total by PyTorch)_

When i check, VRAM is full. I only train with batch-size = 4 but too slow. Before it, i can train with batch-size = 16
How can i solve it?

**Comment by adamhrv** [comment]
You could try using yolov5m (51.3 GFLOPS) instead of yolov5l (115.4 GFLOPS). That would also reduce your mAP though. Or you could try using smaller image size. The previous weight's image size should not have any effect on your current training session. 

"the size of images a model is trained on has no relation to it's architecture or capacity to serve as a pretrained model for further trainings." (See https://github.com/ultralytics/yolov5/issues/2434#issuecomment-797117413)

But then during inference you'll want to run at your trained image size or smaller (See https://github.com/ultralytics/yolov5/issues/2304#issuecomment-786847407)

**Comment by buimanhlinh96** [comment]
Thanks @adamhrv 
But we need to train model at image size we inference to keep accuracy, so i think  i cannot decrease image size :(

**Comment by glenn-jocher** [comment]
@buimanhlinh96 CUDA OOM indicates your GPU memory is insufficient for the task you've attempted. You can reduce your --img-size or --batch-size, use a smaller model as indicated by @adamhrv, or train on a larger GPU. You may be able to train on free T4 and P100 instances in Colab with 16 GB of memory:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, I encountered the same ```Can't allocate memory error``` but in the ```detect.py``` instead of ```train.py``` after running a few inferences (Running on the Raspberry Pi) instead of reducing the ```--img-size``` what other approaches could I take to be able to reduce the memory usage and successfully run the ```detect.py```?

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="987" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by abuelgasimsaadeldin** [comment]
Hi @glenn-jocher, thank you for the reply but as I mentioned what are the steps that would be taken if this error is encountered in the ```detect.py``` instead of ```train.py``` thank you. Attached is the error message obtained. 

![image](https://user-images.githubusercontent.com/68045710/121333934-d2206280-c94b-11eb-8499-37bee9a214ce.png)

**Comment by glenn-jocher** [comment]
@abuelgasimsaadeldin we've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
