### ISSUE TITLE
Can you tell me more about how to run yolov5 on jetson nano?

### ISSUE THREAD

**Issue by sinano1107** [ultralytics/yolov5#2524]
## ❔Question
I've been checking this repository's issues and website for the past few days, but I can't run yolov5 with jetsonnano.
Please tell me how to run it 🙇️.

## Additional context
Don't want to use docker

**Comment by hcakmak7** [comment]
@sinano1107 can you tell us what error you get while you try to run yolov5 on jetson nano?

Here what I did to run yolov5 in jetson nano.

First go to [https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048](url) and download pytorch and torchvision. Then install opencv by using this script.[https://github.com/AastaNV/JEP/blob/master/script/install_opencv4.5.0_Jetson.sh](url)
Do not install requirements via pip3 install -r requirements.txt, do it manually and delete these lines : numpy>=1.18.5,
opencv-python>=4.1.2, torch>=1.7.0, torchvision>=0.8.1 from requirements.txt. Before you install scipy, you need to install libblas3 liblapack3 liblapack-dev libblas-dev and gfortran . 
```
sudo apt install libblas3 liblapack3 liblapack-dev libblas-dev
sudoo apt install gfortran
sudo apt install libatlas-base-dev
```
use above code to install libraries. It will take more than 3 hours to install opencv and 3 more hours to install other dependencies.  Let me know if you cant run it.

**Comment by sinano1107** [comment]
@hcakmak7 
Thanks!!!
I was able to get yolov5 working according to another article, but the live screen is all green so I'll try your suggestion!

**Comment by glenn-jocher** [comment]
@hcakmak7 thanks for the steps! Would running the docker image on a nano be a possibility to avoid the long install times for opencv etc?

**Comment by sinano1107** [comment]
@hcakmak7 
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048
The last command here
`python3 setup.py bdist_wheel`
If you are running this, you will get an error in the middle

↓error message
`subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.`

You can restart the process by typing the command again, but it's annoying.
Did you have the same problem?

**Comment by hcakmak7** [comment]
@sinano1107 
Where did you try to run 
`python3 setup.pt bdist_wheel`. It should be `python3 setup.py install` I think.

@glenn-jocher to use cuda support ,opencv need to be installed from strach thats why I dont use docker image, but it seems using docker is the easiest way. I will prepare a docker image with installations I did. Thanks

**Comment by sinano1107** [comment]
@hcakmak7

<img width="896" alt="スクリーンショット 2021-03-21 11 55 02" src="https://user-images.githubusercontent.com/45984123/111892165-4679f280-8a3c-11eb-9fe6-4545b077ff50.png">
This is what it said.

`python3 setup.py install`.
It worked as well, but I got the same error.

**Comment by hcakmak7** [comment]
@sinano1107
you need to run these commands to install pytorch.
 
`wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.8.0-cp36-cp36m-linux_aarch64.whl \
sudo apt-get install python3-pip libopenblas-base libopenmpi-dev \ 
pip3 install Cython \
pip3 install numpy torch-1.8.0-cp36-cp36m-linux_aarch64.whl`

for torchvision 
`$ sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
$ git clone --branch <v0.9.0> https://github.com/pytorch/vision torchvision   # see below for version of torchvision to download
$ cd torchvision
$ export BUILD_VERSION=0.x.0  # where 0.x.0 is the torchvision version  
$ python3 setup.py install --user
$ cd ../`
If you didn't use Virtual Environments, I suggest you to make a clean installation.

**Comment by sinano1107** [comment]
@hcakmak7 
Thanks, once I initialized the SD card and started over, it worked!
I'm up to installing opencv.

**Comment by sinano1107** [comment]
@hcakmak7 
I was able to execute it. Thank you!

**Comment by JOSHUAWENJZ** [comment]
Hi，how to install matplotlib on nano? I use sudo apt-get install matplotlib. But when I installed seaborn, the environments shows that there is no dependency. When I installed matplotlib with pip, it always failed with no matching distribution.

**Comment by glenn-jocher** [comment]
@JOSHUAWENJZ hey there. We are working on better supporting nano and the other array of deployment options, but so far we don't have any official tutorials or examples. 

I think you may be running into issues due to the dependency checks and autoinstalls. If you are just running inference, I think you might be able to strip away many of the packages in requirements.txt. Could try simply commenting matplotlib and seaborn in requirements.txt and see what happens?

**Comment by glenn-jocher** [comment]
@JOSHUAWENJZ perhaps a better long term solution might be to add these packages to the exclude list when checking dependencies in detect.py (and hubconf.py):
https://github.com/ultralytics/yolov5/blob/fca5e2a48fb526b57bda0c66be6b7ac1aaa8d83d/detect.py#L170

**Comment by fcakyon** [comment]
@glenn-jocher is it possible to create a single exclude list in a file somewhere and use the same list on every check_requirements call? Writing down the list to every check_requirements line is not practical (i need it in yolov5-pip).

**Comment by glenn-jocher** [comment]
@fcakyon I think if there was a global exclude list then it might make more sense for those excluded requirements to simply be commented in requirements.txt. Maybe we could do that with pycocotools.

I think in the the pip package check_requirements may be redundant though, because aren't the dependencies also installed at the same time as yolov5?

**Comment by fcakyon** [comment]
@glenn-jocher you are right, it is redundant. Currently I comment out the lines that contain check_requirements. Just thought if there is a better way of handling it.

**Comment by glenn-jocher** [comment]
@fcakyon maybe there is a better way, I'm not sure. With a setup.py file you can specify requirements like [export] or [inference] etc for more fine-grained control, but inside a single requirements.txt file its not possible, and we don't want multiple requirements.txt files so as not to confuse users. If you have any ideas let me know!

**Comment by middleprince** [comment]
@sinano1107 hi, may i ask what python version do you use? is that python3.6.9? I using python3.6.9 with torch1.8.0 and torchvision0.9.1, but i can't inference my models, which program stuck at Fusing layers.

**Comment by LingBlopdreame** [comment]
@middleprince hi, I also get the problem with python3.6.9, do you solve the problem?

**Comment by ghost** [comment]
> Do not install requirements via pip3 install -r requirements.txt, do it manually 
> and delete these lines : numpy>=1.18.5,
> opencv-python>=4.1.2, torch>=1.7.0, torchvision>=0.8.1 from requirements.txt.

Is it necessary to delete from requirements.txt? Does requirements.txt work like Gemfile in Ruby?

Update: It does not matter here, since you're not going to use requirements.txt in the first place. This just makes it convenient for future deployment.

**Comment by ghost** [comment]
@glenn-jocher Can you pin this issue under `README.md`? I have been struggling for four days, but by chance, I was able to make my board work properly, albeit with other errors.

If anyone else is curious on how you can fix those issues, I've simply added these to `.bashrc` file:
```
# related to ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
# Not sure about what causes this problem, but exporting the environmental variable has fixed my problem
# https://github.com/keras-team/keras-tuner/issues/317

export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

# Illegal instruction (core dumped)
# This might be related to OpenBLAS not being able to detect the CPU properly, more at
# https://forums.developer.nvidia.com/t/illegal-instruction-core-dumped-xavier/166278/4

export OPENBLAS_CORETYPE=ARMV8
```

Btw, @hcakmak7 is it possible to build OpenCV using a different powerful device (x86/64)?

**Comment by italianconcerto** [comment]
I tried the suggestions but I can't find a way to make torch, torchvision and opencv work together with CUDA. the only way seems to be using this: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml

This contain the instruction to download the dockerized libraries already working on jetson nano (with CUDA support).
Unfortunately that doesn't seem to be working with the last version of YOLOv5 since I tried cloning it and run `detect.py` but it didn't work.

Manually compiling everything is a huge waste of time, is there a way to make YOLOv5 work on that container?

Thanks

**Comment by martinerk0** [comment]
@italianconcerto Hi, I successfully used [this SD card image](https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image) on nano with torch hub inference.

**Comment by Hehko** [comment]
@sinano1107 Heyyy, can you help me please, what is the best way to install yolov5 on jetson nano using docker? I'm using Jetson Nano 4.5.1 and I really don't know what to do.
If someone else wants to help me, I really really appreciate it :(

**Comment by iamananthu-s** [comment]
@hcakmak7 
hey
while running  nvidia@jetson-nano:~/yolov5$ pip install ultralytics>=8.0.100

im getting 
ERROR: Could not find a version that satisfies the requirement ultralytics (from versions: none)
ERROR: No matching distribution found for ultralytics


everyone is welcome to help me
thank you

**Comment by glenn-jocher** [comment]
Hello @iamananthu-s,

It seems like you might be having difficulty finding the Ultralytics package through pip. Can you please try running `pip install git+https://github.com/ultralytics/yolov5` in your terminal to directly install the YOLOv5 package from the Ultralytics repository on GitHub? This should install the necessary dependencies as well, and then you should be able to use the package.

Let me know if this helps!

**Comment by iamananthu-s** [comment]
thank you @glenn-jocher

I tried running pip3 install git+https://github.com/ultralytics/yolov5
and the output i got was 
nvidia@jetson-nano:~$ pip3 install git+https://github.com/ultralytics/yolov5
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/ultralytics/yolov5
  Cloning https://github.com/ultralytics/yolov5 to /tmp/pip-req-build-3fj69oxi
  Running command git clone --filter=blob:none -q https://github.com/ultralytics/yolov5 /tmp/pip-req-build-3fj69oxi
  Resolved https://github.com/ultralytics/yolov5 to commit 5f11555e0796f9471185a16dc79860c236f656f8
ERROR: git+https://github.com/ultralytics/yolov5 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by glenn-jocher** [comment]
Hello @iamananthu-s,

This error message indicates that pip3 is failing to find a valid Python package within the YOLOv5 repository for installation. As a workaround, you can try cloning the repository manually and installing the package through Python. Here are the steps you can follow:

1. Clone the YOLOv5 repository using this command in your preferred directory. 
   `git clone https://github.com/ultralytics/yolov5`

2. Navigate to the cloned repository. 
   `cd yolov5`

3. Install the package using Python. 
   `pip3 install -r requirements.txt`

4. Try running a demo script, such as `python3 detect.py --source 0` to verify that everything is working as expected.

I hope this helps! Let me know if you have any other questions or concerns.

**Comment by iamananthu-s** [comment]
hey @glenn-jocher 
Thanks for your reply,
this is what  I'm getting 

(yolov5-env) nvidia@jetson-nano:~/yolov5$ pip3 install -r requirements.txt
Collecting gitpython>=3.1.30 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement gitpython>=3.1.30 (from -r requirements.txt (line 5)) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18, 3.1.19, 3.1.20)
No matching distribution found for gitpython>=3.1.30 (from -r requirements.txt (line 5))
(yolov5-env) nvidia@jetson-nano:~/yolov5$

**Comment by glenn-jocher** [comment]
Hello @iamananthu-s,

Thank you for reaching out to us with your question.

This message suggests that pip is unable to find a suitable version of `gitpython`. This may be due to a number of reasons, including conflicts with other packages or an outdated package index.

I would recommend trying the following steps:

1. Ensure your package index list is up-to-date by running the command `sudo apt-get update` in your terminal.
2. Try manually installing `gitpython` using the command `pip install gitpython`. This may resolve any package conflicts.
3. If that doesn't work, try installing a specific version of `gitpython` using the command `pip install gitpython==<version>`. For example, if you want version 3.1.13, you would run `pip install gitpython==3.1.13`.

Let me know if that helps!

**Comment by TechArcanist** [comment]
solution :- https://github.com/TechArcanist/Jetson-Nano-Yolo-v5

**Comment by glenn-jocher** [comment]
@ghost thank you for sharing your solution. Pinning issues isn't typically done, but your insights are valuable for others facing similar challenges. As for building OpenCV on a different device, cross-compilation is possible but can be complex. You might want to explore guides specific to cross-compiling for ARM architectures.
