### ISSUE TITLE
train_batch*.jpg error

### ISSUE THREAD

**Issue by BUAAtao** [ultralytics/yolov5#271]
When  training my own dataset, I found that gt boxes didn't match labels. 
![train_batch0](https://user-images.githubusercontent.com/35003533/86425256-3b006300-bd17-11ea-8a4a-541f081504a3.jpg)

if added "--rect" when training my own dataset, train_batch*.jpg were correct. I don't know why this happened? I have the same problem in yolov3. And I found if used the yolov3 from three months ago, there are no problems.
![train_batch1](https://user-images.githubusercontent.com/35003533/86425201-14dac300-bd17-11ea-8d52-5b6873df6e95.jpg)

**Comment by glenn-jocher** [comment]
@BUAAtao  follow the formatting of coco128 and everything should work fine. See https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

**Comment by glenn-jocher** [comment]
@BUAAtao did you get this resolved? This may occur if you have extra images in your images folder or if you change your data after it has been cached into *.npy files. See https://github.com/ultralytics/yolov5/issues/306

**Comment by scientificCommunity** [comment]
same issue

**Comment by ahmedbingol-cy** [comment]
Same issue started after more than 100 different training on same dataset using yolov5. Can this issue be related with version difference on packages? I upgrade the some of the packages on the conda environment and now I am facing with same issue

**Comment by glenn-jocher** [comment]
@ahmedbingol-cy thank you for reporting the issue. Upgrading packages in the conda environment could potentially lead to compatibility issues. Please ensure that you have the correct versions of all the required packages to avoid any conflicts. Additionally, it would be helpful to provide more details about the specific issue you are facing, such as error messages or logs, so that we can assist you better.
