### ISSUE TITLE
non_max_suppression

### ISSUE THREAD

**Issue by jayyoung23** [ultralytics/yolov5#2726]
## ❔Question
Hello,i am wondering what is the non-maximum suppression method used by default in YOLOv5，is it normal nms or merge nms or batched nms？
i find that in general.py L421：merge = False  # use merge-NMS
So it means that the program does not apply merge-nms by default, 
if i want to use it，just modify it to true is enough，is that right？（i think merge-nms is better，so i will try it）

BTW，yolov4 uses Giou-nms，have you ever try it，will its performance be better.

Thanks so much！

**Comment by glenn-jocher** [comment]
@jayyoung23 YOLOv5 uses standard NMS. To enable Merge NMS you can set `merge=True` in the NMS function.
https://github.com/ultralytics/yolov5/blob/c8c8da60792e37e2941fc27ee4d0594fcdcee34a/utils/general.py#L415-L434

We've tried a lot of alternatives and have not found any that improves on the current implementation. If you find areas for improvement please let us know and even better consider submitting a PR to help everyone else out as well :)

**Comment by PussyCat0700** [comment]
> @jayyoung23 YOLOv5 uses standard NMS. To enable Merge NMS you can set `merge=True` in the NMS function.
> 
> https://github.com/ultralytics/yolov5/blob/c8c8da60792e37e2941fc27ee4d0594fcdcee34a/utils/general.py#L415-L434
> 
> We've tried a lot of alternatives and have not found any that improves on the current implementation. If you find areas for improvement please let us know and even better consider submitting a PR to help everyone else out as well :)

Hello Glenn, could you please tell me why merge was set to False by default in function non_max_suppression at utils/general.py? Does that mean the implementation of merge-NMS in Yolo-v5 will drive the location of boxes too far away from where it should be for some reason, or that it could undermine network detection in any other way from your experience? Thank you!

**Comment by glenn-jocher** [comment]
@PussyCat0700 merge NMS is disabled by default, but you can enable it manually. Merge will do as it says, merge boxes weighted by their confidences rather than simply remove lower confidence boxes. 

One drawback is that it requires more computation and time than normal NMS.

**Comment by chenyang-a** [comment]
> @jayyoung23YOLOv5 使用标准 NMS。要启用合并 NMS，您可以在 NMS 功能中进行设置。`merge=True`
> 
> https://github.com/ultralytics/yolov5/blob/c8c8da60792e37e2941fc27ee4d0594fcdcee34a/utils/general.py#L415-L434
> 
> 我们已经尝试了很多替代方案，但没有发现任何改进当前实现的替代方案。如果您发现需要改进的地方，请告诉我们，甚至最好考虑提交PR以帮助其他人:)

Hello Glenn, i have set merge=True,but it returned an error
![image](https://user-images.githubusercontent.com/59553011/144782433-78b74244-5ef2-4b5f-a572-1d5ea7ba2e4f.png)

**Comment by glenn-jocher** [comment]
@chenyang-a 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your error is not reproducible. If I run detect.py with merge=True I get correct detections and no errors:

<img width="1508" alt="Screenshot 2021-12-06 at 21 16 56" src="https://user-images.githubusercontent.com/26833433/144916105-fecef41b-f25d-47d3-8164-95715edc9ad0.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by chenyang-a** [comment]
> @chenyang-a 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your error is not reproducible. If I run detect.py with merge=True I get correct detections and no errors:
> 
> <img alt="Screenshot 2021-12-06 at 21 16 56" width="1508" src="https://user-images.githubusercontent.com/26833433/144916105-fecef41b-f25d-47d3-8164-95715edc9ad0.png">
> 
> We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

Thanks for your reply, I have found the reason, but I have another question.Do I need to retrain if I want to compare the results before and after merge

**Comment by glenn-jocher** [comment]
@chenyang-a no

**Comment by IoannisDem** [comment]
Hello, I am using Gooogle Colab.
Why when I make some changes or try to print some values in the python files of utils folders, I see no change in the output. I am trying to get all the confidence values of the image and whilst making some changes in the files and adding some print statements to understand the code it seems that it doesn't change anything
