### ISSUE TITLE
Unable to log and visualize in  wandb.ai when training from scratch

### ISSUE THREAD

**Issue by joyjeni** [ultralytics/yolov5#2735]
## ❔Question
I used Google cobab pro to train COCO dataset using YOLO V5 just to get hands on experience. It took 1063 Minutes to train in 'Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16280MB, multi_processor_count=56' machine. But wandb crashed after 14 hrs I was unable to visualize and metrics not computed mAP. Are the metrics stored in any file format so that I can plot and visualize

<a href="https://imgur.com/myUyDXu"><img src="https://i.imgur.com/myUyDXu.png" title="source: imgur.com" /></a>

But logs written in Wandb. Can I use those logs to see visualization again and compute metrics.

**Comment by glenn-jocher** [comment]
@joyjeni sorry to hear about that! Yes, all results are always logged locally to your project/name directory, usually `yolov5/runs/train/` by default, so you should have all your training results there, as well as a results.png with your metrics plotted.

If you have screenshots of the wandb error messages please share them with us and @AyushExel can pass them to the W&B team for help.

**Comment by AyushExel** [comment]
@joyjeni I'm not sure what happened there. Can you please share the run link? and maybe the exact commands that you used to train?
Also, I think runs not syncing can be an internet issue, you can always run `wand sync` in your terminal to sync the unsynced runs.

**Comment by joyjeni** [comment]
File "train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 365, in train
    is_coco=is_coco)
  File "/content/drive/My Drive/yolov5/test.py", line 121, in test
    out = non_max_suppression(out, conf_thres=conf_thres, iou_thres=iou_thres, labels=lb, multi_label=True)
  File "/content/drive/My Drive/yolov5/utils/general.py", line 424, in non_max_suppression
    xc = prediction[..., 4] > conf_thres  # candidates
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3196) is killed by signal: Killed. 
               Class      Images      Labels           P           R      mAP@.5

wandb: Waiting for W&B process to finish, PID 603
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Find user logs for this run at: /content/drive/My Drive/yolov5/wandb/run-20210407_164204-3feh1znt/logs/debug.log
wandb: Find internal logs for this run at: /content/drive/My Drive/yolov5/wandb/run-20210407_164204-3feh1znt/logs/debug-internal.log
wandb: Run summary:
wandb:                 train/box_loss 0.03694
wandb:                 train/obj_loss 0.04075
wandb:                 train/cls_loss 0.00926
wandb:              metrics/precision 0.0
wandb:                 metrics/recall 0.0
wandb:                metrics/mAP_0.5 0.0
wandb:           metrics/mAP_0.5:0.95 0.0
wandb:                   val/box_loss 0.0
wandb:                   val/obj_loss 0.01815
wandb:                   val/cls_loss 0.0
wandb:                          x/lr0 0.002
wandb:                          x/lr1 0.002
wandb:                          x/lr2 0.002
wandb:                       _runtime 63195
wandb:                     _timestamp 1617876919
wandb:                          _step 298
wandb: Run history:
wandb:         train/box_loss █▇▆▅▅▅▅▅▄▄▄▄▄▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁
wandb:         train/obj_loss █▇▆▆▆▅▅▅▅▄▄▄▄▄▄▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁
wandb:         train/cls_loss █▆▅▄▄▄▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      metrics/precision ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         metrics/recall ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:        metrics/mAP_0.5 ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:   metrics/mAP_0.5:0.95 ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/box_loss ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:           val/obj_loss ▁▂█▄▄▄▄▅▅▄▄▅▅▅▅▅▆▆▅▅▅▅▅▅▅▄▄▄▄▄▄▄▃▃▃▃▃▃▃▃
wandb:           val/cls_loss ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                  x/lr0 ███████▇▇▇▇▇▇▆▆▆▆▅▅▅▄▄▄▄▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr1 ███████▇▇▇▇▇▇▆▆▆▆▅▅▅▄▄▄▄▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁
wandb:                  x/lr2 ███████▇▇▇▇▇▇▆▆▆▆▅▅▅▄▄▄▄▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁
wandb:               _runtime ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:             _timestamp ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                  _step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb: 
wandb: Synced 6 W&B file(s), 293 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: 
wandb: Synced exp2: [](https://wandb.ai/joyjeni/YOLOv5/runs/3feh1znt)
63742.699169622 seconds
1062.3783248756833 Minutes

**Comment by AyushExel** [comment]
Can you also share the run link ?

**Comment by glenn-jocher** [comment]
@joyjeni your error message appears unrelated to logging, as it originates in the NMS function:

`RuntimeError: DataLoader worker (pid 3196) is killed by signal: Killed.` is likely due to insufficient system resources (low RAM or free CPU threads).

**Comment by joyjeni** [comment]
[results.txt](https://github.com/ultralytics/yolov5/files/6286558/results.txt)
My result file saved in runs/train/exp2 

> @joyjeni your error message appears unrelated to logging, as it originates in the NMS function:
> 
> `RuntimeError: DataLoader worker (pid 3196) is killed by signal: Killed.` is likely due to insufficient system resources (low RAM or free CPU threads).

If its insufficient system resource then execution will not complete. I m using Google Colab pro. The resource grow dynamically I believe.

**Comment by joyjeni** [comment]
> Can you also share the run link ?

https://wandb.ai/joyjeni/YOLOv5/runs/3feh1znt

**Comment by AyushExel** [comment]
I can see the metrics recorded in the run links that you shared. Although most precision and recall values are 0 which suggest something's wrong with training but the values are logged.
The logges values in wandb dashboard seem consistent with the results.txt file that you shared. @glenn-jocher do you have any insights on this ?

**Comment by glenn-jocher** [comment]
@AyushExel @joyjeni it's hard to debug 'dataloader worker killed' events as the root cause is usually something else and the dataloader worker being killed is just a symptom. If at all possible I would recommend one of our verified environments below. If you want to train locally, the docker container is a great option.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
