### ISSUE TITLE
How view detection video stream output in browser? Like other yolo version (-json_port  -mjpeg_port ) 

### ISSUE THREAD

**Issue by sachinmorabada** [ultralytics/yolov5#2800]

**Comment by glenn-jocher** [comment]
@sachinmorabada I'm not sure what you mean by in the browser, but you can view streaming sources or youtube videos in realtime with detect.py:

## Inference

`detect.py` runs inference on a variety of sources, downloading models automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases) and saving results to `runs/detect`.
```bash
$ python detect.py --source 0  # webcam
                            file.jpg  # image 
                            file.mp4  # video
                            path/  # directory
                            path/*.jpg  # glob
                            'https://youtu.be/NUsoVlDFqZg'  # YouTube video
                            'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by uxfion** [comment]
I have the same question
How to make output video streaming and view it in the browser in real time?

**Comment by glenn-jocher** [comment]
@uxfion to view the detection output in a web browser in real-time, you can use the `--mjpeg` flag with `detect.py`. This will serve the output frames as an MJPEG stream, which can be accessed in your web browser using the provided address and port.

```bash
$ python detect.py --source your_input.mp4 --mjpeg
```

You can then access the MJPEG stream in your web browser by navigating to the provided address and port, for example, `http://0.0.0.0:8080/`. Note that this feature requires OpenCV-compatible Python installations and will not work on Windows.

For more details and options, please refer to the official YOLOv5 documentation: [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

**Comment by vidyaprasanna77** [comment]
Hi Team , I want to view the real time detection outpout in a url while running the code python detect.py --source 0 --weights ../../section6/yolov5weights/weights/custom_dataset/best.pt --conf-thres 0.5 --save-txt --line-thickness 4 --device 0 . Iam runnin the code on a ubuntu server with ssh connection, virtual env conda. I am using headless server no virtual display configured. how to connect with my local machine webcam and visualize the real time detections

**Comment by glenn-jocher** [comment]
@vidyaprasanna77 hello! To view real-time detection output on a headless server and stream it to a browser, you can use the `--mjpeg` flag with `detect.py` to create an MJPEG stream served over HTTP. However, since you're using a headless server and want to connect to your local machine's webcam, you'll need to set up a streaming solution that sends your webcam feed to the server.

Here's a high-level overview of the steps:

1. Stream your local webcam to the server using a tool like FFmpeg or GStreamer.
2. On the server, run `detect.py` with the `--mjpeg` flag, using the stream URL from step 1 as the `--source`.
3. Access the MJPEG stream from the server in your local machine's web browser.

For example, on your server, you would run:

```bash
$ python detect.py --source <stream-URL-from-local-webcam> --weights best.pt --conf-thres 0.5 --save-txt --line-thickness 4 --device 0 --mjpeg
```

Replace `<stream-URL-from-local-webcam>` with the actual URL of the stream from your local webcam.

Then, on your local machine, open a web browser and navigate to `http://<server-ip>:8080/` to view the real-time detections.

Please note that setting up the webcam stream to the server can be complex and depends on your network configuration. You'll need to ensure that the necessary ports are open and that you have the correct permissions to stream the video feed.

For more detailed instructions and options, please refer to the official YOLOv5 documentation: [Ultralytics Docs](https://docs.ultralytics.com/yolov5/).

**Comment by anirudhjbabu1** [comment]
i tried this in yolov5, but it is giving error.
detect.py: error: unrecognized argument: --mjpeg

**Comment by glenn-jocher** [comment]
@anirudhjbabu1 i apologize for the confusion earlier. The YOLOv5 repository does not directly support an `--mjpeg` argument for streaming video output to a browser in real time as part of the `detect.py` script. The information provided was incorrect, and I appreciate your patience.

For real-time detection streaming in a browser from a headless server, you will need to implement a custom solution. One approach involves modifying the `detect.py` script to use a streaming protocol or a web framework like Flask to serve the video frames as a web page. Here's a broad overview of how you might approach it with Flask:

1. **Set up Flask:** Install Flask in your virtual environment.

2. **Modify detect.py:** Integrate Flask into `detect.py` to capture each frame's output and send it as a response to a web client. 

3. **Stream the Webcam to the Server:** As mentioned before, use tools like FFmpeg or GStreamer to send your local webcam feed to the server. This step remains complex and network-dependent.

4. **View in a Browser:** Set up Flask to run on a public IP or a local network IP accessible by your local machine. You can then access the Flask-served web page to see the real-time detections.

Due to the complexity of Flask integration and streaming setup, I recommend referring to the Flask documentation and examples of Flask video streaming applications. These examples often include streaming video through an HTML5 `<video>` tag in a web browser, which you can adapt to stream your detection output.

Remember, any significant modifications or integration with other frameworks like Flask will require a good understanding of both Python and web development principles. 

For the most current and official YOLOv5 usage instructions, always check the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Our community and documentation are continuously evolving, and we encourage contributions and feedback.
