### ISSUE TITLE
W&B Bug: module 'wandb' has no attribute 'run'

### ISSUE THREAD

**Issue by 1993cathyzhao1993** [ultralytics/yolov5#2845]
## ❔Question
when I was runing ,module 'wandb' has no attribute 'run' occurred,I don't know why？

**Comment by glenn-jocher** [comment]
@1993cathyzhao1993 thanks for the W&B bug report. This is probably a known issue that I've informed W&B about but which it seems they've not taken action on so far. I've had the same problem in the past myself.

@AyushExel I believe this is caused by wandb creating a self-named directory that then fails to import as a package on pip package uninstall. I warned W&B about this a while ago but did not receive any solution.

**Comment by AyushExel** [comment]
@glenn-jocher this was fixed in the new integration. @1993cathyzhao1993 are you sure you're on the latest version of YOLOv5 ? If not, just run `git pull` inside YOLOv5 directory. Can you also share the console traceback of this error ?

**Comment by AyushExel** [comment]
See this #1958 . This was reported as fixed

**Comment by glenn-jocher** [comment]
@AyushExel oh awesome, didn't realize this had been fixed!

@1993cathyzhao1993 yes then your code may be out of date. Please `git pull` or `git clone` again to receive the latest updates which should solve the problem.
