### ISSUE TITLE
cuda memory explosion in the first backward

### ISSUE THREAD

**Issue by Laughing-q** [ultralytics/yolov5#2874]
## 🐛 Bug
RuntimeError: CUDA out of memory. Tried to allocate 52.00 MiB (GPU 0; 7.79 GiB total capacity; 6.27 GiB already allocated; 60.75 MiB free; 6.36 GiB reserved in total by PyTorch)

cuda memory explosion(about 7G) in the first epoch, then go back to normal(about 3G);
actually this would not bother me before, cause the peak did not go beyond my memory. but recetly I am trying to adding some layers to the architecture, so the peak exceed my device memory.

![res](https://user-images.githubusercontent.com/61612323/115534735-a75e4a00-a2ca-11eb-860f-ef70f6d32791.gif)

## command
python train.py batch-size 2 epochs 50 data/coins.yaml --img-size 640 --weights weights/yolov5l.pt

this setting should not increase memory to 7000M+

## Environment
torch==1.7.1, torchvision==0.8.2
a small datasets(coins)
I tested four versions(yolov5-5.0, yolov5-4.0, yolov5-2.0 and the latest version) of code, all have this problem for me.
rtx2070super

**Comment by Laughing-q** [comment]
then I did the same experiment on my laptop which the device is gtx1660ti with 6G memory, I clone the latest version of code, same environment and same setting, but the memory peak become about 5G. It seems that the memory peak  varies from different device. I'm so confused about this situation.

**Comment by glenn-jocher** [comment]
@Laughing-q this may depend on your CUDA and PyTorch installations. It seems to me like this may also simply be due to a very slow dataloader, as your utilization numbers fall to 19% sometimes. If the GPU has nothing to do the memory requirements and utilization will drop.

**Comment by Laughing-q** [comment]
> @Laughing-q this may depend on your CUDA and PyTorch installations. It seems to me like this may also simply be due to a very slow dataloader, as your utilization numbers fall to 19% sometimes. If the GPU has nothing to do the memory requirements and utilization will drop.

@glenn-jocher this explosion occurred only in the first epoch.
In the first epoch, with the memory explosion, gpu utilization also goes explosion, but both of them go to normal(memory fall to about 3G, gpu utilization fall to about 25%) after the first epoch. so I don't think this is due to a slow dataloader(cause the dataloader keep slow and gpu memory keep normal after first epoch).
This is a strange phenomenon, it seems like the model test my GPU computing power first.....then go training.
maybe this is about cuda and pytorch installations? could you tell about your verson of pytorch and cuda?

**Comment by glenn-jocher** [comment]
@Laughing-q I think you're misunderstanding the nvidia-smi outputs. You want very high utilization and memory consumption, otherwise you are not exploiting your hardware well, and you are leaving significant performance on the table.

It's not that memory increases in your situation, it's that the GPU has nothing to do, and thus your memory and utilization are falling.

**Comment by Laughing-q** [comment]
> @Laughing-q I think you're misunderstanding the nvidia-smi outputs. You want very high utilization and memory consumption, otherwise you are not exploiting your hardware well, and you are leaving significant performance on the table.
> 
> It's not that memory increases in your situation, it's that the GPU has nothing to do, and thus your memory and utilization are falling.

I know what you mean, but that's another thing. Maybe I didn't make it clear. It's just because in my experiment, the batch size is 2 and the device is rtx2070, so it's normal that my GPU memory and GPU utilization are relatively low during training(memory 3G, utilization 25%). If I increase the batch number, they will also increase and i will exploit my device well, but that's not what I want to say. The problem is that in the first epoch of training, GPU memory and utilization rate will increase sharply, and then decrease to the normal memory and utilization rate for batch size 2.

Another strange phenomenon is that when I increase the number of batches to 8, which the memory is about 6G, and the utilization rate is about 65% after the first epoch. In the first epoch, the GPU memory will also increase sharply, and the memory will increase to 7g, and the utilization rate will also increase. The peak value is the same as the experiment with batch size 2, so no matter how many the batch size I set(2 or 8), the memory and utilization will increase sharply at the first epoch then go to normal according to the batch size I set.

**Comment by glenn-jocher** [comment]
@Laughing-q I don't think there's anything to worry about, especially if you're running at artificially small batch-sizes (--batch-size 2 is much smaller than recommended) to try to observe GPU effects.

In our own public runs (8x A100 instances training multiple VOC models here for 50 epochs) you can see that there's no additional GPU memory used in the first epoch vs later epochs.
https://wandb.ai/glenn-jocher/VOC/runs/33a48d47/system?workspace=user-glenn-jocher
<img width="1559" alt="Screenshot 2021-04-22 at 17 21 46" src="https://user-images.githubusercontent.com/26833433/115740643-52d0d280-a38f-11eb-9b64-0a3928bc7658.png">

**Comment by Laughing-q** [comment]
> @Laughing-q I don't think there's anything to worry about, especially if you're running at artificially small batch-sizes (--batch-size 2 is much smaller than recommended) to try to observe GPU effects.
> 
> In our own public runs (8x A100 instances training multiple VOC models here for 50 epochs) you can see that there's no additional GPU memory used in the first epoch vs later epochs.
> https://wandb.ai/glenn-jocher/VOC/runs/33a48d47/system?workspace=user-glenn-jocher
> <img alt="Screenshot 2021-04-22 at 17 21 46" width="1559" src="https://user-images.githubusercontent.com/26833433/115740643-52d0d280-a38f-11eb-9b64-0a3928bc7658.png">

I see, thanks for your patient reply

**Comment by jeannotes** [comment]
how did you figure this out, I encounter same issue. @Laughing-q

**Comment by Laughing-q** [comment]
> how did you figure this out, I encounter same issue. @Laughing-q

not yet....., it didn't cause me much trouble, so I didn't follow up on it later...
Cause glenn did't get additional GPU memory in his environment,  this may depend on the cuda and pytorch installations.
if you figure this out later, please tell me.

**Comment by glenn-jocher** [comment]
@jeannotes @Laughing-q if you can document any abnormal memory usage in a reproducible experiment using W&B, we could get started investigating. If we can not reproduce what you are seeing, there is no action for us to take.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by XDynames** [comment]
I have also been seeing this when using this repo to train
On my A6000s the memory peaks at 46GB on the first epoch then drops to 13GB for the rest of training - this makes it impossible to set larger batch sizes than what my VRAM can absorb during the peak
I also tried checkpointing the training after the peak and reloading it with a different batch size to no avail

**Comment by glenn-jocher** [comment]
@XDynames 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. If you can document any abnormal memory usage in a reproducible experiment using W&B, we could get started investigating. If we can not reproduce what you are seeing, there is no action for us to take.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
