### ISSUE TITLE
How to find those images which have been classified wrongly?

### ISSUE THREAD

**Issue by akshat-suwalka** [ultralytics/yolov5#2895]
## ❔Question
Hi @glenn-jocher 
Hope you are doing well!

Can you please help me to know that Is there any way to find those images which have been wrongly classified?

**Comment by glenn-jocher** [comment]
@akshat-suwalka that's an interesting question. I'm assuming you want a list of AP per image rather than per class?

The current metrics are not retained on a per-image basis since mAP is computed across all images together, though are instead computed as AP per-class, with these results averaged for mAP. test.py would need significant restructuring to retain metrics per image.
