### ISSUE TITLE
configurable wandb project name

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/yolov5#2988]
Currently the [project name is hardcoded as YoloV5](https://github.com/ultralytics/yolov5/blob/f7bc685c2c0f57005b83355715cb7282e61416eb/utils/wandb_logging/wandb_utils.py#L97) but someone might want to log the results under an existing project. What changes are needed for that?

**Comment by glenn-jocher** [comment]
@fcakyon you can adjust project and run name with the `--project` and `--name` arguments. This will affect both local and W&B logging:
```shell
python train.py --project activations_study --name SiLU
```

**Comment by fcakyon** [comment]
@glenn-jocher OK, now i see. Thanks for the fast response!

**Comment by glenn-jocher** [comment]
@fcakyon no problem. These two arguments are also shared by test.py and detect.py and also include an --exist-ok argument to overwrite existing contents, otherwise by default project will be i.e. 'runs/detect' and project will be 'exp', incremented each run:
https://github.com/ultralytics/yolov5/blob/d08575ee5e5259b65e1f39ac6880cd33804c4d1a/detect.py#L167-L169

**Comment by glenn-jocher** [comment]
The idea is all YOLOv5 generated content is organized and deposited by default to run/source/exp, with auto-incrementing names, i.e. exp, exp2, exp3 etc.

<img width="352" alt="Screenshot 2021-04-30 at 16 18 02" src="https://user-images.githubusercontent.com/26833433/116708285-d6ae3e80-a9cf-11eb-8df9-260eaf482f4a.png">
