### ISSUE TITLE
Expected all tensors to be on the same device -- forward method in models/yolo.py

### ISSUE THREAD

**Issue by kozlovskia** [ultralytics/yolov5#3040]
I have tried to load custom trained yolov5s model via torch.hub and error below appeared:
![image](https://user-images.githubusercontent.com/62251653/117154561-42235200-adbc-11eb-9c71-b14b17d1e370.png)
Changing `onnx_dynamic` to True in `Detect` class seems to fix this, but i am not sure if it is a desired fix to this problem.
Funny thing is that weights that i have trained earlier (few months ago) work flawlessly. It is worth mentioning that both weights were trained by the same forked repository (without getting any updates).

**Comment by glenn-jocher** [comment]
@kozlovskia your error is not reproducible (screenshot below). If you believe you have a reproducible issue, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!


<img width="1399" alt="Screenshot 2021-05-05 at 17 05 49" src="https://user-images.githubusercontent.com/26833433/117163773-46ec0400-adc4-11eb-9804-3389e35b9daf.png">

**Comment by eldarkurtic** [comment]
@kozlovskia I had the same issue when I disabled the EMA training. Basically it happens because (in the case of DataParallel/DDP models) `self.grid` and `y` are not on the same device when this line is executed: https://github.com/ultralytics/yolov5/blob/417a2f425cd553c1f2a41374a6cd2710aa91d5f0/models/yolo.py#L62
(`y` is on `cuda` and `self.grid` has some elements that are on the `cpu` and some that are on the other `cuda` devices)

I have solved this by adding `self.grid[i].to(x[i]).device` in this line: https://github.com/ultralytics/yolov5/blob/417a2f425cd553c1f2a41374a6cd2710aa91d5f0/models/yolo.py#L62

@glenn-jocher to reproduce this issue, just pass the DataParallel or DDP `model` to the `test.run` call, instead of the current `ema.ema`.
