### ISSUE TITLE
New version of the YoloV5 has much slower speed on caching the images and labels

### ISSUE THREAD

**Issue by ljjsfe** [ultralytics/yolov5#309]
I clone the new updated code today. Looks like the performance has some improvements. However, the training process takes much longer time on caching the images and labels. Is it normal?

**Comment by glenn-jocher** [comment]
@ljjsfe you might have a slower or older spinning hard drive if this is happening to you. You should load datasets always from solid state drives.

**Comment by aryan51k** [comment]
Hi, I am also trying to train yolov5 the updated version it is much slower I performed the training on same dataset earlier it was working just fine please help me. When I cache the images it is slower. when I do not cache the images it takes much less time. For example 22168 images on yolov5x takes 1hr 18 min to complete 1 epoch but if I do not cache the data it takes 20 mins to complete an epoch

**Comment by glenn-jocher** [comment]
@aryan51k keep in mind the OP comment is a year old and has no relation to the current state of the repo. 

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by aryan51k** [comment]
Hi thanks for the quick reply I am training yolov5x for the following details
classes: 22
images: 21686
GPU: tesla K80 

When I am caching the data my training time is much more than when I do not cache the data please tell me the possible solution for this. thanks. in advance

**Comment by glenn-jocher** [comment]
@aryan51k that probably just indicates that your system is out of RAM and using a swap file on a slow local storage medium. 

--caching uses up significant RAM, it's your responsibility to ensure you have the available resources for it.

**Comment by aryan51k** [comment]
Thanks for the quick reply, Yes I think you are right I just noticed that after caching all the images I have only 0.5 GB RAM available so according to you how much RAM should I leave empty after caching the images. if my cached file size is 8.3 GB
