### ISSUE TITLE
I don't understand these two lines. Who can help?

### ISSUE THREAD

**Issue by xinxin342** [ultralytics/yolov5#3098]

**Comment by xinxin342** [comment]
![屏幕截图 2021-05-10 205317](https://user-images.githubusercontent.com/70836998/117662432-206a0680-b1d2-11eb-99cb-e59f6268002a.png)

**Comment by glenn-jocher** [comment]
@xinxin342 pxy and pwh are the predicted xy and predicted width-height values, in grid units.

**Comment by xinxin342** [comment]
@glenn-jocher I know what they stand for, and what puzzles me is: why use this formula to calculate them

**Comment by glenn-jocher** [comment]
@xinxin342 this is the YOLOv5 box computation formula.

**Comment by pocketvision** [comment]
When anchor_t: 4.0

why not use pwh = (ps[:, 2:4].sigmoid() * 4) * anchors[i]
![4](https://user-images.githubusercontent.com/20749514/117748012-d7519b00-b241-11eb-8343-b2b272646409.png)

instead of pwh = (ps[:, 2:4].sigmoid() * 2) ** 2 * anchors[i] ?
![2](https://user-images.githubusercontent.com/20749514/117748021-dc164f00-b241-11eb-97ef-41a430aa7676.png)

@glenn-jocher

**Comment by glenn-jocher** [comment]
@daikankan hi, great analysis!

In ML you always want a reference input to return a nominal output. The anchor gains are one way to normalize the output (to a reference input) to unity mean and variance, which the original equation satisfies, `y(x) = 1`, but which the proposed equation does not satisfy, `y(x) = 2`. Therefore the width-height output would begin training in a state of stress with a large gradient, whereas the current width-height output is stably initialized with around zero gradient.
