### ISSUE TITLE
OSError: [WinError 1455]

### ISSUE THREAD

**Issue by sezer-muhammed** [ultralytics/yolov5#3182]
Hi,

I have RTX3070 with 8gb vram.

When I run this command "python train.py --img 640 --batch 4 --weights yolov5x.pt --epochs 30 --data coco128.yaml"
there is no problem, and model uses 5gb of vram.
![image](https://user-images.githubusercontent.com/74321576/118402143-547d7580-b671-11eb-940e-fca1d23bd255.png)

but, when I increased batch size 4 to 5 it gave error named OsError 1455 and says "The disk memory is too small for this process to complete."

![image](https://user-images.githubusercontent.com/74321576/118402198-8e4e7c00-b671-11eb-824f-e52d6a75186a.png)

there might be a translation error. because I have 1TB SSD and 450 GB free space. 
my ram is 16gb. but it is not "disk memory"

What is the reason of this problem?

**Comment by glenn-jocher** [comment]
@sezer-muhammed if increasing the batch size leads to memory errors I would stick with your current batch size.

Alternatively you can train a smaller model, reduce image size, or use a larger GPU.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed if increasing the batch size leads to memory errors I would stick with your current batch size.
> 
> Alternatively you can train a smaller model, reduce image size, or use a larger GPU.

This is what I'm doing right now, but I want to use all of my GPU. I cannot use 3 GB of my RAM
Why I cannot increase batch size?

Btw, I can increase image size with constant batch size, in this way I can use more GPU memory.
![image](https://user-images.githubusercontent.com/74321576/118402662-8c85b800-b673-11eb-8f8f-21b92ff43cfe.png)
as you can see here

If I cannot find the problem, I will use the biggest image size that can be trained with 4 batch size.

**Comment by SpongeBab** [comment]
> @sezer-muhammed if increasing the batch size leads to memory errors I would stick with your current batch size.
> 
> Alternatively you can train a smaller model, reduce image size, or use a larger GPU.

I meet this question,too.Can you improve this error output？I think there should give some guide,like` change your batch-size to 4 or smaller `.
Mistakes like this can obscure what's going on.

**Comment by glenn-jocher** [comment]
@SpongeBab in general if you are seeing CUDA OOM (Out Of Memory) errors your GPU memory is full. You must either reduce batch-size, reduce image size, train a smaller model, or use a larger GPU.

**Comment by PonyPC** [comment]
same issue. Win10 96G memory, 1080Ti with 11G.
yolov5 v3.0 works fine, but v5.0 and master branch will meet this.
I believe this is a bug.

**Comment by PonyPC** [comment]
#3038

**Comment by PonyPC** [comment]
#2207

**Comment by glenn-jocher** [comment]
@PonyPC 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="987" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by PonyPC** [comment]
@glenn-jocher I have set Windows page files to 500Gb and nothing else changed. Now everything works well.

**Comment by PonyPC** [comment]
And I got the Windows page files not enough instead of CUDA OOM before.
