### ISSUE TITLE
Detections from .txt file 

### ISSUE THREAD

**Issue by Yassine-Fak** [ultralytics/yolov5#3229]
## ❔Question

Hi @glenn-jocher ! I have a question please: Is it possible to make detections (using the detect.py file) from a `.txt` file that contains the paths to images ? 

Thanks in advance for your response.

**Comment by glenn-jocher** [comment]
@Yassine-Fak you can run inference on a path or glob object:
```shell
$ python detect.py --source 0  # webcam
                            file.jpg  # image 
                            file.mp4  # video
                            path/  # directory
                            path/*.jpg  # glob
                            'https://youtu.be/NUsoVlDFqZg'  # YouTube video
                            'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by kimcon7775** [comment]
Hi @glenn-jocher ! I have a question please: 
when i try that 
         parser.add_argument('--source', type=str, default='**rtsp://admin:password@192.168.1.64:554/h264/ch1/sub/**', 
         help='source')  # file/folder, 0 for webcam

i found a error message
         \yolov5\utils\datasets.py", line 298, in __init__ self.threads[i] = Thread(target=self.update, args=([i, cap]), daemon=True)       
        AttributeError: 'LoadStreams' object has no attribute 'update'

how i can solve to the error
Thanks in advance for your response.

**Comment by glenn-jocher** [comment]
@kimcon7775 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by mrwu-mac** [comment]
> ## ❔Question
> Hi @glenn-jocher ! I have a question please: Is it possible to make detections (using the detect.py file) from a `.txt` file that contains the paths to images ?
> 
> Thanks in advance for your response.
> 
> ## Additional context

you can add a dataset class in utils/datasets.py, and add it to detect.py.
`class LoadImagesTxt: 

    def __init__(self, path, img_size=640, stride=32):
        p = Path(path)  # os-agnostic absolute path
        files = []
        if p.is_file():  # file
            with open(p, 'r') as t:
                t = t.read().strip().splitlines()
                parent = str(p.parent) + os.sep
                files += [x.replace('./', parent) if x.startswith('./') else x for x in t]  # local to global path

        images = [x for x in files if x.split('.')[-1].lower() in img_formats]
        videos = [x for x in files if x.split('.')[-1].lower() in vid_formats]
        ni, nv = len(images), len(videos)
        self.img_size = img_size
        self.stride = stride
        self.files = images + videos
        self.nf = ni + nv  # number of files
        self.video_flag = [False] * ni + [True] * nv
        self.mode = 'image'
        if any(videos):
            self.new_video(videos[0])  # new video
        else:
            self.cap = None
        assert self.nf > 0, f'No images or videos found in {p}. ' \
                            f'Supported formats are:\nimages: {img_formats}\nvideos: {vid_formats}'

    def __iter__(self):
        self.count = 0
        return self

    def __next__(self):
        if self.count == self.nf:
            raise StopIteration
        path = self.files[self.count]

        if self.video_flag[self.count]:
            # Read video
            self.mode = 'video'
            ret_val, img0 = self.cap.read()
            if not ret_val:
                self.count += 1
                self.cap.release()
                if self.count == self.nf:  # last video
                    raise StopIteration
                else:
                    path = self.files[self.count]
                    self.new_video(path)
                    ret_val, img0 = self.cap.read()

            self.frame += 1
            print(f'video {self.count + 1}/{self.nf} ({self.frame}/{self.frames}) {path}: ', end='')

        else:
            # Read image
            self.count += 1
            img0 = cv2.imread(path)  # BGR
            assert img0 is not None, 'Image Not Found ' + path
            print(f'image {self.count}/{self.nf} {path}: ', end='')

        # Padded resize
        img = letterbox(img0, self.img_size, stride=self.stride)[0]

        # Convert
        img = img[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
        img = np.ascontiguousarray(img)

        return path, img, img0, self.cap

    def new_video(self, path):
        self.frame = 0
        self.cap = cv2.VideoCapture(path)
        self.frames = int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT))

    def __len__(self):
        return self.nf  # number of files`

**Comment by glenn-jocher** [comment]
@mrwu-mac interesting solution, though it would be better to not duplicate code in datasets.py, i.e. a modification to the existing images and videos dataloader to detect a txt file in the init function.
