### ISSUE TITLE
Wide RTSP Stream Analysis Problem

### ISSUE THREAD

**Issue by philippneugebauer** [ultralytics/yolov5#3290]
## 🐛 Bug

I am not sure if that's a bug. I have a very large output I am trying to analyze (2560x720) but it works with a smaller one (1920x1080)

## To Reproduce (REQUIRED)

Input:
```
python3 detect.py --source rtsp://host.docker.internal:8554/analysis
```

Output:
```
Fusing layers...
Model Summary: 291 layers, 12353140 parameters, 0 gradients, 16.7 GFLOPS
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
cv2.imshow() is disabled in Docker environments
1/1: rtsp://host.docker.internal:8554/analysis...  success (-307445734561826 frames 2560x720 at 3.00 FPS)

Traceback (most recent call last):
  File "detect.py", line 184, in <module>
    detect(opt=opt)
  File "detect.py", line 51, in detect
    dataset = LoadStreams(source, img_size=imgsz, stride=stride)
  File "/usr/src/app/utils/datasets.py", line 297, in __init__
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/usr/src/app/utils/datasets.py", line 297, in <listcomp>
    s = np.stack([letterbox(x, self.img_size, stride=self.stride)[0].shape for x in self.imgs], 0)  # shapes
  File "/usr/src/app/utils/datasets.py", line 823, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'
```

Any ideas how I can resolve this?

Edit: Hm, sometimes it work. Or maybe it's also connected to the low fps rate? I feel like I am only guessing about it

**Comment by glenn-jocher** [comment]
@philippneugebauer hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* **Minimal** – Use as little code as possible that still produces the same problem
* **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for Ultralytics to attempt to reproduce your problem, the code that produces the problem must be:

* **Current** – Verify that your code is up-to-date with current GitHub master, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. Ultralytics does not provide support for customized code.

If you believe your problem meets all of the above criteria, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by philippneugebauer** [comment]
I think that problem was caused by a later starting stream

**Comment by lizituo12** [comment]
> I think that problem was caused by a later starting stream

how to solve this,i Note this line 
![image](https://user-images.githubusercontent.com/38873975/130737620-3c258604-5c40-4cd9-af02-78ee0ea49a71.png)
and use queue to get the frame,but the imgs still None
