### ISSUE TITLE
CoreML: export failure: Unsupported numpy type: float32

### ISSUE THREAD

**Issue by a794133319** [ultralytics/yolov5#3296]
## Additional context

CoreML: export failure: Unsupported numpy type: float32

![image](https://user-images.githubusercontent.com/55074811/119262138-c1ae7f00-bc0c-11eb-912c-409beacec391.png)

**Comment by glenn-jocher** [comment]
@a794133319 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* **Minimal** – Use as little code as possible that still produces the same problem
* **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for Ultralytics to attempt to reproduce your problem, the code that produces the problem must be:

* **Current** – Verify that your code is up-to-date with current GitHub master, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. Ultralytics does not provide support for customized code.

If you believe your problem meets all of the above criteria, we suggest you close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. Thank you!

**Comment by dbickson** [comment]
We had the same bug, switching to numpy 1.19.5 from 1.20.0 solved the issue

**Comment by a794133319** [comment]
thanks

**Comment by a794133319** [comment]
> We had the same bug, switching to numpy 1.19.5 from 1.20.0 solved the issue

thanks

**Comment by AlvinZheng** [comment]
> We had the same bug, switching to numpy 1.19.5 from 1.20.0 solved the issue

caused another problem 
" module compiled against API version 0xe but this version of numpy is 0xd"
