### ISSUE TITLE
WANDB PNG storage gives error every 50-100 epochs

### ISSUE THREAD

**Issue by dk-teknologisk-mlnn** [ultralytics/yolov5#3321]
I'm trying to do 1000 epochs with COCO which takes a long time so I just leave it be on a remote computer during the weekend. Every day I remote login to check that it is done, but it keeps stopping the training process with the following error having done only 50-100 epochs. 

Traceback (most recent call last):
  File "train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 354, in train
    results, maps, times = test.test(data_dict,
  File "D:\DTIDetectNet\test.py", line 162, in test
    wandb_images.append(wandb_logger.wandb.Image(img[si], boxes=boxes, caption=path.name))
  File "C:\local\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\data_types.py", line 1587, in __init__
    self._initialize_from_data(data_or_path, mode)
  File "C:\local\Anaconda3\envs\pytorch\lib\site-packages\wandb\sdk\data_types.py", line 1700, in _initialize_from_data
    self._image.save(tmp_path, transparency=None)
  File "C:\local\Anaconda3\envs\pytorch\lib\site-packages\PIL\Image.py", line 2169, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpyu_lezoywandb-media\\flm8fqel.png'

**Comment by glenn-jocher** [comment]
@sequoiagrove I'm not sure what the cause of your error could be. In general we require a reproducible example to debug (directions below). The only thing that comes to mind is I see you have multiple drives showing, i.e. C:\, D:\, if some of your data is on a network or remote drive this is bad practice, as outages or delays may lead to training errors.

👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by dk-teknologisk-mlnn** [comment]
Im more wondering why is it even trying to find 'C:\Users\User\AppData\Local\Temp\tmpyu_lezoywandb-media\flm8fqel.png'"
wandb is OFF (option 3). C and D are harddrives in the same computer.
I now uninstalled wandb to see if I can get through an entire training session for tomorrow. Otherwise I have to delete all lines of code that has to do with wandb starting with "test.py", line 162, in test
wandb_images.append(wandb_logger.wandb.Image(img[si], boxes=boxes, caption=path.name))"

**Comment by glenn-jocher** [comment]
@sequoiagrove well there's a few workarounds you can use:

```bash
$ python test.py --notest  # only test final epoch
# or
$ wandb disabled
```

**Comment by dk-teknologisk-mlnn** [comment]
It is still running since yesterday after uninstalling wandb :)

**Comment by glenn-jocher** [comment]
@AyushExel though I should ping you here. New error on test.py L162, not sure what the cause might be.

**Comment by dk-teknologisk-mlnn** [comment]
Could it be an access rights thing? does it use the temp folder every epoch or only after a while?

Each time it stopped I continued form the last *.pt under runs/train/exp#.

The metrics and losses almost flatlined though. would it have been better to start over? Or maybe I just reached the capability of my smaller than yolov5s model (training full coco). Or is it normal that it hits a plateau and then it will rise a bit after a long time?

![image](https://user-images.githubusercontent.com/30144796/119464979-8e224080-bd43-11eb-8bad-a769cd2f6862.png)

**Comment by AyushExel** [comment]
@glenn-jocher thanks for the heads up.
@sequoiagrove I'll try to reproduce this problem on my end. It might be an access thing on windows. And it only uses the temp folder after every once a while. Because the bounding box images are logged only 10 times, i.e, every `epochs//10` epoch, which in your case should be `1000//10=100`.

**Comment by dk-teknologisk-mlnn** [comment]
ok, then to reproduce, try:
default fresh yolov5 on an internal harddrive (don't think it matters if its on C: or a 2nd drive D:). 
Running python 3.8 in an anaconda env. CMD.exe started not as admin. But logged in user is local admin. UAC is set to minimum.
wandb is installed, but not used ( chosen 3 when prompted). using tensor board on localhost.
Train (full) coco  with yolov5s.yaml from scratch for 1000 epochs.

**Comment by AyushExel** [comment]
@sequoiagrove thanks I'll try to reproduce it and let you know

**Comment by AyushExel** [comment]
@sequoiagrove I tried this on windows on cmd without admin access. [Here's](https://wandb.ai/cayush/yoloV5/runs/1o51krkt?workspace=user-cayush) the run. The images are being logged without errors. Maybe there's some other UAC stuff that's messing it up in your case

**Comment by dk-teknologisk-mlnn** [comment]
I looked into my temp folder and there is nothing there from wandb, but tensorboard managed to access it fine as there is a folder called .tensorboard-info with a bunch of pid files.

wandb git has some similar report on linux and windows:
https://github.com/wandb/client/issues/1252
https://github.com/wandb/client/issues/1869

**Comment by AyushExel** [comment]
Ahh okay. Seems like that 2nd issue is fresh and still open. I'll keep you posted if we have any update there
