### ISSUE TITLE
Should optimizer be initialized after DDP(model) ？Some report said it is used to guarantee the multi-gpu’s consistency for training ?

### ISSUE THREAD

**Issue by pocketvision** [ultralytics/yolov5#3369]
https://zhuanlan.zhihu.com/p/187610959

**Comment by glenn-jocher** [comment]
@MagicFrogSJTU we got a recent question from @daikankan about our DDP training, I see you wrote a good blog post on the topic! Do you think we should init our optimizer after DDP? Currently we do this in reverse:

Optimizer:
https://github.com/ultralytics/yolov5/blob/bb131238aabf94fe619199bc2bee81be70989776/train.py#L109-L132

DDP:
https://github.com/ultralytics/yolov5/blob/bb131238aabf94fe619199bc2bee81be70989776/train.py#L219-L224

**Comment by MagicFrogSJTU** [comment]
Actually, the order doesn't matter in this case. Because initializations of optim.SGD and optim.Adam don't utilize the actual value of model parameters. Not until training steps.

But still, it would be more reasonable to put optimizer initialization after DDP initialization, considering that we may add other optimizers in the future.

**Comment by MagicFrogSJTU** [comment]
@glenn-jocher 
Wow, can you read Chinese? did you read my blog?

**Comment by glenn-jocher** [comment]
@MagicFrogSJTU haha no, but I managed to understand a bit what the blog post was about by seeing the images etc.
