### ISSUE TITLE
Use torch.hub.load with local saved weights for real time object tracking.

### ISSUE THREAD

**Issue by OleksiiYeromenko** [ultralytics/yolov5#3439]
## ❔Question
Is it possible to use torch-hub loaded model with custom-saved weights use to track a few classes and output stream with their coordinates in real time?

## Additional context
There is no internet connection.
As  I understand I can try to do it only with local Yolo version via detect.py.  Any suggestions?

**Comment by WongKinYiu** [comment]
model = torch.hub.load('/your/weights/dir/', your_model_name, pretrained=True, autoshape=False, source='local')

**Comment by OleksiiYeromenko** [comment]
> model = torch.hub.load('/your/weights/dir/', your_model_name, pretrained=True, autoshape=False, source='local')

I'm receiving Error: `FileNotFoundError: [Errno 2] No such file or directory: './yolov5x.pt\\hubconf.py'`
Path to weights and name `yolov5x.pt` is correct.  What is hubconf.py?

**Comment by WongKinYiu** [comment]
model name should be `yolov5x` not `yolov5x.pt`.

**Comment by OleksiiYeromenko** [comment]
Ok, what supposed to be in weights folder?  (*.pt?)  What's 'hubconf.py'?
` model = torch.hub.load('./weights', 'yolov5x', pretrained=True, autoshape=False, source='local') `

**Comment by WongKinYiu** [comment]
https://github.com/ultralytics/yolov5/blob/develop/hubconf.py

**Comment by OleksiiYeromenko** [comment]
Ok, thanks. So, I made it working using following line:  
`model = torch.hub.load('dir/to/yolov5', 'custom', path='./weights/yolov5s.pt', source='local')`

**Comment by glenn-jocher** [comment]
@WongKinYiu @OleksiiYeromenko sounds good, thanks guys, I'll add this local example to the PyTorch Hub tutorial.

**Comment by glenn-jocher** [comment]
All done, I've added a new line to the Custom Models section:

## Custom Models
This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'best.pt'` with PyTorch Hub.
```python
model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default
model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
```

**Comment by GGDRriedel** [comment]
> 
> 
> All done, I've added a new line to the Custom Models section:
> ## Custom Models
> 
> This example loads a custom 20-class [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)-trained YOLOv5s model `'best.pt'` with PyTorch Hub.
> 
> ```python
> model = torch.hub.load('ultralytics/yolov5', 'custom', path='path/to/best.pt')  # default
> model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/best.pt', source='local')  # local repo
> ```

Sitting on the same problem here, I tried this and got 
```
TypeError: custom() got an unexpected keyword argument 'path'
```

**Comment by glenn-jocher** [comment]
@GGDRriedel path argument is valid and correct:
<img width="1493" alt="Screenshot 2021-06-07 at 12 28 02" src="https://user-images.githubusercontent.com/26833433/121001705-d867e080-c78b-11eb-8032-a894667a7fe6.png">


## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by GGDRriedel** [comment]
Yeah, turns out I was a few commits behind, pulling fixed it. 

Nevertheless, now I get a "Cache may be out of date " error. 
Followed the adress to ussue 36 but that 
'firce_reload=True' is for downloading models, not for local ones. 

Would be glad for a hint, maybe delete some chache?

cheers

**Comment by glenn-jocher** [comment]
@GGDRriedel 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by GGDRriedel** [comment]
```python
import torch

model=torch.hub.load(r'~\Projekte\Radspot\ultralyt\yolov5','custom',path=r'\remote_results\exp17\weights\best.pt', source='local')
```
I am training on a different machine, "remote results" is just the results coppied. 


Error thrown: 

```
~\.conda\envs\ultralyt\lib\site-packages\torch\hub.py in load(repo_or_dir, model, *args, **kwargs)
    368         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
    369
--> 370     model = _load_local(repo_or_dir, model, *args, **kwargs)
    371     return model
    372

~\.conda\envs\ultralyt\lib\site-packages\torch\hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    397
    398     entry = _load_entry_from_hubconf(hub_module, model)
--> 399     model = entry(*args, **kwargs)
    400
    401     sys.path.remove(hubconf_dir)

~\Projekte\Radspot\ultralyt\yolov5\hubconf.py in custom(path, autoshape, verbose, device)
     63 def custom(path='path/to/model.pt', autoshape=True, verbose=True, device=None):
     64     # YOLOv5 custom or local model
---> 65     return _create(path, autoshape=autoshape, verbose=verbose, device=device)
     66
     67

~\Projekte\Radspot\ultralyt\yolov5\hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     58         help_url = 'https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading'
     59         s = 'Cache may be out of date, try `force_reload=True`. See %s for help.' % help_url
---> 60         raise Exception(s) from e
     61
     62
```
Adding `force_reload=True` results in 

```
 custom() got an unexpected keyword argument 'force_reaload'
```

**Comment by glenn-jocher** [comment]
@GGDRriedel I'm not able to reproduce this error, as in the example I've shown you previously local model loading operates correctly for us. If we can not reproduce the error then there is no action for us to take.

<img width="1493" alt="Screenshot 2021-06-07 at 12 28 02" src="https://user-images.githubusercontent.com/26833433/121001705-d867e080-c78b-11eb-8032-a894667a7fe6.png">

**Comment by GGDRriedel** [comment]
> 
> 
> @GGDRriedel I'm not able to reproduce this error, as in the example I've shown you previously local model loading operates correctly for us. If we can not reproduce the error then there is no action for us to take.
> 
> <img alt="Screenshot 2021-06-07 at 12 28 02" width="1493" src="https://user-images.githubusercontent.com/26833433/121001705-d867e080-c78b-11eb-8032-a894667a7fe6.png">

Using that '.' example  it works fine here as well.

My suspicion  is that it could be because of my custom model being trained on a different machine/repo-version, so I tried with a locally trained experiment run: 

```
 model = torch.hub.load(r'~\Projekte\Radspot\ultralyt\yolov5', 'custom', path=r'\runs\exp15\weigh
    ...: ts\best.pt', source='local')  # local repo

```

Same error about cache. 
 The run is a custom trained yolo5s, trained with an earlier git repo version

**Comment by GGDRriedel** [comment]
I created a new issue to not further hijack this one 

https://github.com/ultralytics/yolov5/issues/3504
