### ISSUE TITLE
autoanchor complaining about scipy.cluster.vq.kmeans requested 9 points but returned only 4

### ISSUE THREAD

**Issue by KMint1819** [ultralytics/yolov5#3482]
## ❔Question
Hi, I was trying to apply yolov5 to my custom dataset which has only 480 images(far from sufficient, but that's all I've got). In fact, the baseline model works quite descent. Yet when I try to increase the accuracy, since most of the objects are relatively small, it was mentioned [here](https://github.com/ultralytics/yolov5/issues/2734#issuecomment-815690427) that yolo-p2 is suitable for this kind of case. 

However when using it, probably because of the limited amount of data I have, it starts complaining about "scipy.cluster.vq.kmeans requested 9 points but returned only 4" at autonanchor.py. Is there any way I can deal with this issue other than adding more data? Or should I just copy the predefined anchor to yolov5-p2.yaml?  Thanks!

## Additional context
```
autoanchor: Analyzing anchors... anchors/target = 0.00, Best Possible Recall (BPR) = 0.0000. Attempting to improve anchors, please wait...
autoanchor: Running kmeans for 9 anchors on 41145 points...
autoanchor: ERROR: scipy.cluster.vq.kmeans requested 9 points but returned only 4
autoanchor: ERROR: None
autoanchor: Original anchors better than new anchors. Proceeding with original anchors.
```

**Comment by glenn-jocher** [comment]
@KMint1819 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **autoanchor** for anchor verification and generation before training starts.

Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e. 
```yaml
# Specify anchor count (per layer)
anchors: 3

# --OR-- Specify anchor values manually
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and then uses these kmeans centroids as initial conditions for a Genetic Evolution (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using the CIoU loss (same one used during training) combined with Best Possible Recall (BPR) as its fitness function.

No action is required on your part to use autoanchor. If you would like to force manual anchors for any reason, **you can skip autoanchor** with the `--noautoanchor` flag:
```shell
python train.py --noautoanchor
```

**Comment by yun9993** [comment]
@glenn-jocher Hello,Can I set the number of anchor  to 6?

**Comment by glenn-jocher** [comment]
@yun9993 👋 Hello! Thanks for asking about model anchors. YOLOv5 🚀 uses a new [Ultralytics](https://ultralytics.com/) algorithm called **AutoAnchor** for anchor verification and generation before training starts.

Autoanchor will analyse your anchors against your dataset and training settings (like `--img-size`), and will adjust your anchors as necessary if it determines the original anchors are a poor fit, or if an **anchor count** was specified in your model.yaml rather than **anchor values**, i.e. 
```yaml
# Specify anchor count (per layer)
anchors: 3

# --OR-- Specify anchor values manually
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```

When generating new anchors, autoanchor first applies a kmeans function against your dataset labels (scaled to your training `--img-size`), and uses kmeans centroids as initial conditions for a [Genetic Evolution](https://en.wikipedia.org/wiki/Genetic_algorithm) (GE) algorithm. The GE algorithm will evolve all anchors for 1000 generations under default settings, using CIoU loss (same regression loss used during training) combined with [Best Possible Recall](https://en.wikipedia.org/wiki/Precision_and_recall) (BPR) as its fitness function.

Notebook example: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

<img width="1200" alt="Screenshot 2022-03-24 at 10 58 28" src="https://user-images.githubusercontent.com/26833433/159891298-8b15f80b-f5b0-4fa9-8824-7380bae32a76.png">

**No action is required on your part** to use autoanchor. If you would like to force manual anchors for any reason, you can skip autoanchor with the `--noautoanchor` flag:
```shell
python train.py --noautoanchor
```

For more details on AutoAnchor see:
https://github.com/ultralytics/yolov5/blob/master/utils/autoanchor.py

Good luck 🍀 and let us know if you have any other questions!
