### ISSUE TITLE
YoloV5 RuntimeError: No such operator torchvision:nms

### ISSUE THREAD

**Issue by zentorno365** [ultralytics/yolov5#352]
I am getting the following error when trying to train using my custom dataset.
![Screenshot from 2020-07-10 19-18-40](https://user-images.githubusercontent.com/68109767/87149102-31ac6300-c2e2-11ea-9a5f-b410171608f1.png)

**Comment by glenn-jocher** [comment]
@krishnam3065 it appears you have environment problems. In order to run YOLOv5 correctly your environment must meet  the minimum version requirements for the dependencies described in https://github.com/ultralytics/yolov5#requirements. You can either update your local environment to bring it into compliance or you can use one of our verified environment options below.

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by chengjiun** [comment]
I met the same problem. And it seems to be a problem of pytorch/torchvision.  See their issues like: https://github.com/pytorch/vision/issues/1405 ... 
The environment I have: 
```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 440.100
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] pytorch                   1.5.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.1                    pypi_0    pypi
```
I also tried to compiled pytorch and torchvision from source, but no luck.

**Comment by glenn-jocher** [comment]
@chengjiun seems like a conda issue. You can try one of the 4 working environments above, they are all verified working correctly.

**Comment by chengjiun** [comment]
@glenn-jocher yeah. Docker works fine. I need to run it locally, so the other solutions don't help at all. And, I am not used to project development in docker, so it is better if I can solve the issue in native environment.
I am not sure if it is caused by conda. I have tried compiled pytorch, torchvision from source, but problem is the same. Anyway, it is related to some inconsistency among installed libraries of pytorch, torchvision, cuda, and perhaps cudnn.  Anyway, I have wasted half day to track this issue, and will stay in docker for now.

**Comment by chengjiun** [comment]
[update] 
it is strange. I used docker to run yolov5 (train.py) successfully. But, I got the identical error message, if I directly run "torch.ops.torchvision.nms" in yolov5 docker. Somehow, the docker version of yolov5 bypass the torch.ops.torchvision.nms?

p.s. torch.ops.torchvision.nms works fine in colab tutorial code.

**Comment by xandyxor** [comment]
@chengjiun @glenn-jocher 
I found a solution

first
```
conda uninstall pytorch torchvision cudatoolkit=10.1 -c pytorch
pip uninstall numpy
```
then 

```
pip install numpy==1.17.0
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

```




我找到解決的方法了
先執行
```
conda uninstall pytorch torchvision cudatoolkit=10.1 -c pytorch
pip uninstall numpy
```

再執行
```
pip install numpy==1.17.0
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

```

**Comment by zentorno365** [comment]
Thanks  everyone this issue is resolved when torch and torchvision was re installed

**Comment by harleych** [comment]
@xandyxor your solution works well.
I use numpy 1.17.3 and scipy 1.4.1 instead of the latest numpy 1.19.2 and scipy 1.6.1. The problem has been solved.

**Comment by Roshnee** [comment]
@xandyxor thanks!! your solution works.. it was probably because of the incompatible versions

**Comment by glenn-jocher** [comment]
Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.6`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by JavierClearImageAI** [comment]
> @xandyxor your solution works well.
> I use numpy 1.17.3 and scipy 1.4.1 instead of the latest numpy 1.19.2 and scipy 1.6.1. The problem has been solved.

This solved the issue!
