### ISSUE TITLE
As I begin to train on the coco set, or even on a smaller coco128 set, the training crashes with an error about dataloader workers running out of shared memory. This also happens with 1 dataloader worker

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#3589]
I've seen several online issues about pytorch running out of shared memory.

I've also seen several closed issues in the ultralytics/yolov5 issue database.

 I am trying to run yolov5/train.py and I see this problem:

`RuntimeError: DataLoader worker (pid 905551) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.`

I even see this with coco128. 

I have also set the number of workers (--workers) to 1, and to 0. I still see the training crash.

I am running on a Fedora linux virtual machine. 

Is there something I can do at the app tier to request more shared memory?

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/121701101-8f22d400-ca9e-11eb-8d70-0dbbe7cb3d0b.png)

**Comment by davesargrad** [comment]
It doesnt always complain about shared memory when it crashes. Sometimes it just terminates. Here is the view with a single worker.
![image](https://user-images.githubusercontent.com/48793689/121705870-16724680-caa3-11eb-907d-46cd7cbf3550.png)

**Comment by davesargrad** [comment]
I've verified that it crashes inside forward_once .. on the first C3 layer.

![image](https://user-images.githubusercontent.com/48793689/121716360-ee3c1500-caad-11eb-93dd-78ba1e70580f.png)

**Comment by davesargrad** [comment]
So.. the call to model here:
```
                with amp.autocast(enabled=cuda):
                    pred = model(imgs)  # forward
                    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
                    if rank != -1:
                        loss *= opt.world_size  # gradient averaged between devices in DDP mode
                    if opt.quad:
                        loss *= 4.
```

descends into C3 forward and crashes on the following line:

![image](https://user-images.githubusercontent.com/48793689/121717433-2859e680-caaf-11eb-9815-471acb9a7260.png)



I descended further into the debugger, and found that the exact line where a crash occurs is the call to return F.conv2d (inside Pytorches conv.py):

```
    def _conv_forward(self, input, weight):
        if self.padding_mode != 'zeros':
            return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
                            weight, self.bias, self.stride,
                            _pair(0), self.dilation, self.groups)
        return F.conv2d(input, weight, self.bias, self.stride,
                        self.padding, self.dilation, self.groups)
```

I also noticed that for some reason self.Bias is None. I dont know if this is correct. Though I think thats ok since I also see it as None when we get to this point from the Focus layer.

Finally, when it crashes at this point, I can't actually step into the F.conv2d function. I do see a SIGTERM with signal 15.

**Comment by glenn-jocher** [comment]
@davesargrad Conv2d layers have no bias because the BatchNorm2d layers after them serve this purpose. This is standard practice.

It seems like you are out of memory on your local system. All I can recommend is that if you are having issues locally you may want to try a verified environment from the list below:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


For us to investigate an issue we would need to be able to reproduce it ourselves first. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by davesargrad** [comment]
Hi. This information helps.  I will try adding memory to my machine. I think you may be right. I need more resources.

**Comment by GiorgioSgl** [comment]
Try to low the batch size I was having the same problem

**Comment by davesargrad** [comment]
Hi @GiorgioSgl 

It seems that the batch size fixed my problem. I had a batch size of 64.  I've now changed it to 8, and am running .. so far without a crash.. 

Fingers crossed.

**Comment by davesargrad** [comment]
Hi @glenn-jocher 

I'm running train.py as follows:
`python train.py --data coco128.yaml --cfg yolov5s.yaml --weights /assets/zzz/weights/yolov5s.pt --batch-size 8`

![image](https://user-images.githubusercontent.com/48793689/122093793-6f124e00-cdd9-11eb-85fb-1bd6292ae9b7.png)

I'm not crashing now.. I do see that the app seems to simply hang at the following point. Its been in this state for about 50 minutes.

![image](https://user-images.githubusercontent.com/48793689/122093222-d8de2800-cdd8-11eb-9afb-54e9c81f98b6.png)


Is this expected?

Dave

**Comment by davesargrad** [comment]
Hmm.. killed pycharm and am running from command line instead.. 


Its getting further....

![image](https://user-images.githubusercontent.com/48793689/122094767-86057000-cdda-11eb-97aa-cd56e3623930.png)


![image](https://user-images.githubusercontent.com/48793689/122094841-9cabc700-cdda-11eb-8ef1-c3aa0f33e24d.png)

Not sure why it doesnt train properly in pycharm..  but ok.. i can live with that.

**Comment by glenn-jocher** [comment]
@davesargrad no it's not supposed to hang, none of the ops anywhere take more than a few seconds without displaying an update on the console.

The torch jit UserWarning has been addressed in the latest code BTW.

**Comment by GiorgioSgl** [comment]
> Hi @GiorgioSgl
> 
> It seems that the batch size fixed my problem. I had a batch size of 64. I've now changed it to 8, and am running .. so far without a crash..
> 
> Fingers crossed.

Happy it helps😀

**Comment by davesargrad** [comment]
@glenn-jocher  @GiorgioSgl 

Thanks both for your feedback. I will close this issue. I managed to get the train.py to complete with the appropriate parameters, outside the debugger, and with a more capable VM.

I only wish the program ended more gracefully than it does, when it is parameterized in a fashion that is not achievable. I imagine this is really an issue with pytorch. I've seen the code for ultralytics yolov5. Its clean. Its sensible.


Thanks again. I enjoy working with this technology, and I enjoy the feedback I get. It shows a group of people that care.
