### ISSUE TITLE
 RuntimeError: Sizes of tensors must match except in dimension 2. Got 25 and 26 (The offending index is 0)

### ISSUE THREAD

**Issue by xiaowanzizz** [ultralytics/yolov5#3621]
# YOLOv5 head
head:
  [[-1, 3, BottleneckCSP, [1024, False]],  # 9       # 19*19*1024

   [-1, 1, Conv, [512, 1, 1]],                       # 19*19*512
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],       # 38*38*512
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4       38*38*512 concat with 38*38*512 ->38*38*1024
   [-1, 3, BottleneckCSP, [512, False]],  # 13         38*38*512

   [-1, 1, Conv, [256, 1, 1]],                       # 38*38*256
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],       # 76*76*256
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3     # 76*76*512
   [-1, 3, BottleneckCSP, [256, False]],  #          # 76*76*256

   [-1, 1, Conv, [128, 1, 1]],                       # 76*76*128
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],       # 152*152*128
   [[-1, 2], 1, Concat, [1]],  # cat backbone P3     # 152*152*256
   [-1, 3, BottleneckCSP, [128, False]],  #          # 152*152*128
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 18 (P3/8-small)

   [-2, 1, Conv, [128, 3, 2]],                       # downsample 76*76*128
   [[-1, 18], 1, Concat, [1]],  # cat head P4        # 76*76*256
   [-1, 3, BottleneckCSP, [256, False]],             # 76*76*256
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 22 (P4/16-medium)

   [-2, 1, Conv, [256, 3, 2]],                       # 38*38*256
   [[-1, 14], 1, Concat, [1]],  # cat head P5        # 38*38*512
   [-1, 3, BottleneckCSP, [512, False]],             # 38*38*512
   [-1, 1, nn.Conv2d, [na * (nc + 5), 1, 1]],  # 26 (P5/32-large)

   [[], 1, Detect, [nc, anchors]],  # Detect(P5, P4, P3)
  ]

**Comment by glenn-jocher** [comment]
@xiaowanzizz #👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
