### ISSUE TITLE
PyTorch Hub with custom model gives different results than when i run detect.py with same model

### ISSUE THREAD

**Issue by NikoStein96** [ultralytics/yolov5#3632]
## ❔Question
Basically the title. When i run inference with detect.py for detecting cards i get the perfect results ex. 6 of spades. But then when i try to run it with pytorch hub with the same model, all of a sudden it says there is 6 of spades and 6 of diamonds with 0.88 conf for both, which is wrong. How can i  make pytorch hub inference more accurate like detect.py ? 
Any help is appreaciated

**Comment by glenn-jocher** [comment]
@NikoStein96 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀.  I am unable to reproduce this. My own tests show near-identical results as expected:

### detect.py
<img width="1202" alt="Screenshot 2021-06-16 at 11 49 21" src="https://user-images.githubusercontent.com/26833433/122198023-0d191d80-ce99-11eb-9ca3-0cf7f43efce2.png">

### PyTorch Hub
<img width="1202" alt="Screenshot 2021-06-16 at 11 49 09" src="https://user-images.githubusercontent.com/26833433/122198047-14d8c200-ce99-11eb-81e4-0a5ab70dae32.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by NikoStein96** [comment]
Hello and thank you for helping! 

I just cloned the newest repo of yolov5 to make sure everything was up to date, and i still get the same problem. 

If you want to try and reproduce the problem:
You can download our weight for our project on this link: https://easyupload.io/8trg0k 
password is:edited out

Here is the image we are running inference on
![testImage](https://user-images.githubusercontent.com/33083536/122204174-1ad1a180-ce9f-11eb-85fd-45756a29f2d9.png)

The command i run with yolov5 repo in cmd:
python3 detect.py --source testImage.png --weights thebest.pt --conf 0.7
Output is 2 6hs

The code i run with pytorch hub:

```
import torch
import pandas
import json
import cv2

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='thebest.pt')
model.conf = 0.7

img = cv2.imread('testImage.png')
results = model(img, size=640)
resultsPanda = results.pandas().xyxy[0].to_json(orient="records")
resultsJSON = json.loads(resultsPanda)
print(resultsJSON)
```

result is: [{'xmin': 440.0706787109, 'ymin': 646.4710693359, 'xmax': 467.1304321289, 'ymax': 708.1239624023, 'confidence': 0.8905023336, 'class': 47, 'name': '6s'}, {'xmin': 289.4304199219, 'ymin': 449.9571838379, 'xmax': 316.2368469238, 'ymax': 509.1347045898, 'confidence': 0.8768323064, 'class': 34, 'name': '6c'}]

This is our full project repo: https://github.com/CATOS15/cdio_backend
We are trying to build a project, that has to recognize all the cards in a full solitaire game and give the next best possible move based on the findings of the model.

Again thank you for the help. :-)

**Comment by glenn-jocher** [comment]
@NikoStein96 your cv2 usage is not correct. See **YOLOv5 PyTorch Hub** tutorial to get started:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by NikoStein96** [comment]
Oh yikes.. I see
img2 = cv2.imread('bus.jpg')[:, :, ::-1] # OpenCV image (BGR to RGB) Adding the BGR to RGB fixed it.

Thank you for your time and help :-)

**Comment by mattpopovich** [comment]
Thanks for asking this question, @NikoStein96. 

Your question helped remind me that I trained my model with the flag `--img-size 512`. When I ran `results = model(imgs)` with the model from PyTorch Hub, I was getting slightly different results vs `detect.py`. I think that is because the default `size` argument is `640` with PyTorch Hub.
When I ran `results = model(imgs, size=512)`, the PyTorch Hub results matched `detect.py`

**Comment by glenn-jocher** [comment]
@mattpopovich I've seen a few comments to this effect. Maybe it would be useful to retain training metadata with the models to automatically use during inference (like we do with class names). Though image-size is really the main setting that comes to mind.
