### ISSUE TITLE
Running yolov5 on CPU

### ISSUE THREAD

**Issue by riadsouissi** [ultralytics/yolov5#37]
Hi. 
With such high fps with the small yolov5 model, would it run decently on a cpu configuration (xeon processor for instance)?

**Comment by glenn-jocher** [comment]
@riadsouissi yes absolutely! I do all my development on a 2018 MacBook Pro (no CUDA devices), and if I run the webcam demo at the default --img-size 640 I get about 5 FPS on CPU:

```bash
(env1) glennjocher@Glenns-MBP yolov5 % python detect.py --source 0
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='0', view_img=False, weights='weights/yolov5s.pt')
Using CPU

1/1: 0...  success (1280x720 at 29.00 FPS).

0: 384x640 Done. (0.266s)
0: 384x640 1 persons, Done. (0.217s)
0: 384x640 1 persons, Done. (0.218s)
0: 384x640 1 persons, Done. (0.207s)
0: 384x640 1 persons, Done. (0.209s)
0: 384x640 1 persons, Done. (0.209s)
0: 384x640 1 persons, Done. (0.208s)
0: 384x640 1 persons, Done. (0.210s)
0: 384x640 1 persons, Done. (0.210s)
0: 384x640 1 persons, Done. (0.207s)
```

If I reduce to --img-size 320 I get about 15-20 FPS on CPU:
```bash
(env1) glennjocher@Glenns-MBP yolov5 % python detect.py --source 0 --img 320
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', fourcc='mp4v', half=False, img_size=320, iou_thres=0.5, output='inference/output', save_txt=False, source='0', view_img=False, weights='weights/yolov5s.pt')
Using CPU

1/1: 0...  success (1280x720 at 29.00 FPS).

0: 192x320 1 persons, Done. (0.096s)
0: 192x320 1 persons, Done. (0.064s)
0: 192x320 1 persons, Done. (0.064s)
0: 192x320 1 persons, Done. (0.058s)
0: 192x320 1 persons, Done. (0.062s)
0: 192x320 1 persons, Done. (0.063s)
0: 192x320 1 persons, Done. (0.062s)
0: 192x320 1 persons, Done. (0.061s)
```

If you download our iDetection app, you will get 30+ FPS also on the latest iPhones. All of Apple's recent mobile devices (iPads, iPhones, etc) actually run YOLOv5 much faster than Intel CPU devices like MacBooks. This is due to the ANE, which for the last two years has had about 5 TOPS of power, and is likely due for a significant boost with the fab process reduction this year to 5nm.

**Comment by riadsouissi** [comment]
Thanks for the prompt feedback!

**Comment by rkinas** [comment]
Hi,
BTW does iDetection app support y5? I just downloaded it on iPad Pro and can see only y4.

**Comment by glenn-jocher** [comment]
@rkinas ah, yes. This is on our TODO list. Unfortunately we are stretched pretty thin, but probably by next week we will have new y5 models exported to iDetection.

**Comment by themrmax** [comment]
If anyone ends up here because `train.py` is hanging, I had to use `--workers 0` to get it to run on my 2017 Macbook Pro, I thinks it's related to this issue https://github.com/pytorch/pytorch/issues/1355
