### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.datasets'; 'utils' is not a package in colab

### ISSUE THREAD

**Issue by aliencaocao** [ultralytics/yolov5#3711]
Running on colab GPU with latest pytorch installed
```!pip uninstall utils
!pip3 uninstall utils
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False, classes=6, force_reload=True)
```
give:

```
WARNING: Skipping utils as it is not installed.
WARNING: Skipping utils as it is not installed.
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-1b786d00b284> in <module>()
     10 get_ipython().system('pip uninstall utils')
     11 get_ipython().system('pip3 uninstall utils')
---> 12 model = torch.hub.load('ultralytics/yolov5', 'yolov5s', autoshape=False, classes=6, force_reload=True)  # load pretrained

5 frames
/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in <module>()
     13 from torch.cuda import amp
     14 
---> 15 from utils.datasets import letterbox
     16 from utils.general import non_max_suppression, make_divisible, scale_coords, increment_path, xyxy2xywh, save_one_box
     17 from utils.plots import colors, plot_one_box

ModuleNotFoundError: No module named 'utils.datasets'; 'utils' is not a package
```

I installed all requirements already by running` !pip install -r https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt`

**Comment by SpongeBab** [comment]
I meet the same error.

**Comment by glenn-jocher** [comment]
@SpongeBab @aliencaocao your error is not reproducible:
<img width="1210" alt="Screenshot 2021-06-21 at 14 07 18" src="https://user-images.githubusercontent.com/26833433/122759250-06741700-d29a-11eb-97bf-27edcbe138bf.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by aliencaocao** [comment]
Hi, sorry for the late reply. I have managed to solve the issue by resetting the runtime and reinstalling the package.
