### ISSUE TITLE
Saving model error

### ISSUE THREAD

**Issue by edwardnguyen1705** [ultralytics/yolov5#372]
Hi,
Thank you for sharing your code.

Before I made a pull, I have successfully trained and saved models. But now, after 1 epoch, the `torch.save` function fails to save the model (`path/to/last.pt`).

```
Traceback (most recent call last):
  File "/home/thanhnv/.conda/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 328, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/thanhnv/.conda/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 396, in _legacy_save
    pickle_module.dump(MAGIC_NUMBER, f, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 447, in <module>
    train(hyp)
  File "train.py", line 358, in train
    torch.save(ckpt, last)
  File "/home/thanhnv/.conda/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 328, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/thanhnv/.conda/envs/yolo5/lib/python3.7/site-packages/torch/serialization.py", line 207, in __exit__
    self.file_like.flush()
AttributeError: 'bool' object has no attribute 'flush'
```

Do you have any suggestions?

**Comment by glenn-jocher** [comment]
@edwardnguyen1705 it appears you may have environment problems. In order to run YOLOv5 correctly your environment must meet  the minimum version requirements for the dependencies described in https://github.com/ultralytics/yolov5#requirements. You can either try updating your local environment to bring it into compliance or you can use one of our verified environment options below.

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by edwardnguyen1705** [comment]
Hi @glenn-jocher ,

Thanks for your suggestions. Everything goes smooth now.
