### ISSUE TITLE
RTSP stream restart

### ISSUE THREAD

**Issue by pentadotddot** [ultralytics/yolov5#3721]
Hi!

Is it possible to restart the rtsp stream inside the detection loop if stream crashes? So I would like to come up with a solution, to restart the rtsp stream without restarting the whole program.

I don't know why, but sometimes randomly all the frames get black after a certain number of frames coming from an rtsp stream (does not happen with videos), so I am thinking about a workaround with the restarting.

Thank you in advance!

**Comment by glenn-jocher** [comment]
@pentadotddot there's some logic in the streamloader to fill crashed streams with zeros to allow them to keep running, you may want to take a look here:

https://github.com/ultralytics/yolov5/blob/b83e1a4adcf77ccafa72b22ade6cb3898ccb0e05/utils/datasets.py#L309-L320

**Comment by pentadotddot** [comment]
Thank you!
Now I understand where the black screen is coming from, but I still don't understand why the stream does not recover after a few broken frames, and why it remains black. If I restart detect.py the stream works perfectly fine, until some frames where it is just becomes broken. So please, could you point out where and how I could implement in the code, that if success variable is false, then I restart the whole stream?

**Comment by ou525** [comment]
I also encountered the same problem

**Comment by glenn-jocher** [comment]
@pentadotddot stream disconnects may be due to a variety of sources, such as your specific stream, your internet connection, etc., but these are not in our control, so the success flag will supply zeros for any dropped frames to create a streamloader robust to dropped frames and streams.

Streams are only initialized in the streamloader init method, so you would need to add new logic for stream restart to the streamloader update() function. Also bear in mind the streamloader is multistream capable out of the box, so whatever modifications you make should only restart a single stream and not affect neighboring streams.

If you have success with this please consider submitting a PR to help other users also! See https://github.com/ultralytics/yolov5#contribute

**Comment by pentadotddot** [comment]
Ok I solved it with an ugly but working solution:

First I detect if there is broken frame via if `im0` only contains 0-s (screen is plain black), then I break the whole detect() function if this happens: 
```python
if not np.any(im0) == True:
    break
```

I run the detect() in a while() loop: 

``` python	
with torch.no_grad():
    while(True):
		  
    if opt.update:  # update all models (to fix SourceChangeWarning)
        for opt.weights in ['yolov5s.pt', 'yolov5m.pt', 'yolov5l.pt', 'yolov5x.pt']:
	    detect()
	    strip_optimizer(opt.weights)
    else:
            detect()
```

**Comment by ergosumdre** [comment]
> Ok I solved it with an ugly but working solution:
> 
> First I detect if there is broken frame via if `im0` only contains 0-s (screen is plain black), then I break the whole detect() function if this happens:
> 
> ```python
> if not np.any(im0) == True:
>     break
> ```
> 
> I run the detect() in a while() loop:
> 
> ```python
> with torch.no_grad():
>     while(True):
> 		  
>     if opt.update:  # update all models (to fix SourceChangeWarning)
>         for opt.weights in ['yolov5s.pt', 'yolov5m.pt', 'yolov5l.pt', 'yolov5x.pt']:
> 	    detect()
> 	    strip_optimizer(opt.weights)
>     else:
>             detect()
> ```

Hey, I'm experiencing the same issue with black frames. Where should I add this chunk?

**Comment by glenn-jocher** [comment]
@ergosumdre it looks like you've found a workaround to address the problem of black frames. This solution appears functional, but it may not be the most efficient. You could integrate your logic directly into the streamloader class instead of looping in the detect function. 

For instance, inside the streamloader's `update()` method, you might check for black frames and restart the stream if necessary before passing it to the detect function. This would keep the logic neatly encapsulated within the appropriate class.

Feel free to share your findings with the community, as it could help others facing a similar issue!

If you need further explanation, please refer to the documentation: https://docs.ultralytics.com/yolov5/

**Comment by mateuszraczkiewicz** [comment]
For me works this code:

    # Checking if the frame was read correctly
    if not ret:
        print("The frame wasn't read correctly")
        cap = cv2.VideoCapture(rtsp_url)
        continue

Put this if inside your loop

**Comment by glenn-jocher** [comment]
@killerpanku2137 great to hear you found a solution that works for you! Implementing a conditional check to restart the video capture when a frame isn't read correctly is indeed a practical approach. Thanks for sharing your code snippet; it might help others facing similar issues. Keep up the good work! 👍
