### ISSUE TITLE
How about ATSS on YOLOv5？

### ISSUE THREAD

**Issue by JustWeZero** [ultralytics/yolov5#3740]
## ❔Question
Does anyone do experiments with/without ATSS on YOLOv5?And If I wang to implement myself,where should I add this module?

**Comment by glenn-jocher** [comment]
@JustWeZero none that I know of.

You can add custom modules in https://github.com/ultralytics/yolov5/blob/master/models/experimental.py and then place them in a model.yaml file wherever you want:
https://github.com/ultralytics/yolov5/blob/ae4261c7749ff644f45c66b79ecb1fff06437052/models/yolov5s.yaml#L12-L48

**Comment by LitChi-bit** [comment]
Hello, I have recently been trying to research running ATSS on Yolov5, but there is no progress so far. May I ask what the author thinks will be the result, or do you have any suggestions? thanks

**Comment by glenn-jocher** [comment]
@sakkios sorry, I don't have experience with ATSS.

**Comment by tongchangD** [comment]
> Hello, I have recently been trying to research running ATSS on Yolov5, but there is no progress so far. May I ask what the author thinks will be the result, or do you have any suggestions? thanks

请问结果如下

**Comment by pderrenger** [comment]
@tongchangD I don’t see any results attached; if you’re experimenting with ATSS in YOLOv5, start by replacing the positive-sample assignment in build_targets inside utils/loss.py and keep the Detect head’s anchor/grid mapping in models/yolo.py consistent, or switch the head to anchor‑free if you fully adopt ATSS; please share mAP50–95, your training command, dataset summary, and the commit hash so we can reproduce, and since this thread is closed, open a new issue with those details; if you prefer a maintained baseline with modern assigners, consider upgrading to Ultralytics YOLO (YOLO11)—see the Ultralytics Docs for details.
