### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by sangeethkumar1997** [ultralytics/yolov5#3743]
## 🐛 Bug

When doing batch prediction with pytorch hub, gpu memory usage is constant but running out of ram and session crashes

## To Reproduce (REQUIRED)

import torch
from PIL import Image
import pandas as pd
import json
import os
device = torch.device('cuda:0')
model = torch.hub.load('ultralytics/yolov5', 'custom', path='runs/train/exp9/weights/best.pt').to(device)
images=os.listdir('yt')
temp1=[]
for i in range(0, len(images)//32):
    ll=i*32
    ul=(i+1)*32
    batchlist=images[ll:ul]
    batchpath=list(map(lambda x :'yt/'+x, batchlist))
    temp1.append(batchpath)

results=[]
a=0
for i in temp1:
    a=a+1
    print(a)
    batchresult=model(i)
    results.append(batchresult.xyxy)

Output:
no error. session crash.

## Additional context
![Screenshot from 2021-06-23 13-29-25](https://user-images.githubusercontent.com/61541017/123059683-a612e000-d427-11eb-93d3-219a816d30f6.png)
![Screenshot from 2021-06-23 13-30-14](https://user-images.githubusercontent.com/61541017/123059774-bc20a080-d427-11eb-9290-3177c52dfce3.png)
![Screenshot from 2021-06-23 13-31-00](https://user-images.githubusercontent.com/61541017/123059787-c0e55480-d427-11eb-8d12-0226b6d0cb68.png)

**Comment by glenn-jocher** [comment]
@sangeethkumar1997 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
