### ISSUE TITLE
GPU temperature and memory

### ISSUE THREAD

**Issue by Laudarisd** [ultralytics/yolov5#3802]
## Additional context
Hi @glenn-jocher , Sorry for bothering you again.
I am running training on my custom dataset. I have 5 classes and more than 10k images. image size is used as 640 with default training parameters for custom dataset. When I run training it goes well, but it doesn't use all gpu memory. I am using batch size 4. When I use 8, it throws cuda memory problem.
Currently, I am using GeForce RTX 3060, 12 gb. Whenever I run training with batch size 4, gpu temperature goes around 80c. Is it normal? Is there any hint to control gpu tem and memory while running training? Well this might be a silly question. sorry.

**Comment by glenn-jocher** [comment]
@Laudarisd 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="987" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by Laudarisd** [comment]
Thanks a lot @glenn-jocher .

**Comment by Laudarisd** [comment]
Now I don't have any problem regarding memory but gpu temperature goes high whenever I run training. Is there any idea to control gpu temperature? 

Thank you.
