### ISSUE TITLE
How to add text to image frame? 

### ISSUE THREAD

**Issue by ramen-ctrl** [ultralytics/yolov5#381]
I want to add a counter that says the class and the number of objects detected on the top left hand corner of the image. In detect.py, the number of boxes detected is returned but I am not sure how to reflect the number on the top left hand corner of the image with the specific class.

**Comment by dlawrences** [comment]
Hi @ramen-ctrl 

As far as I understand, you want to display in the top left hand corner of each image the number of objects detected by class. If there is more than 1 class, would you expect multiple lines to be added to the left hand corner of the image?

Anyhow, here is where it is determined how many detections are per class **per image**:

https://github.com/ultralytics/yolov5/blob/140d84cca12bc2b4cc2b0c563c42ac8b2cb7c0b4/detect.py#L87-L90

You should create a new function in `utils/utils.py` that handles the plot of the text at a certain place in the image. You should call this function as part of the for loop iteration together with some label (i.e. `person(s): 3`) and the top left position of label (see [cv2.putText()](https://www.geeksforgeeks.org/python-opencv-cv2-puttext-method/) for this).

This should be a more trimmed down and simpler version of the `plot_one_box` function:

https://github.com/ultralytics/yolov5/blob/140d84cca12bc2b4cc2b0c563c42ac8b2cb7c0b4/utils/utils.py#L925-L936

In order to handle the case where you're detecting for more than 1 class, you should probably increase the value of the **y coordinate** of the top left point from which the text is going to be plotted with some pre-determined number of pixels to account for multi-lines.

**Tip**: Be sure to check whether you are breaking out of the overall image bounds. I would imagine for a dataset like COCO that has 80 classes, you will certainly experience this issue.

Hope this was useful. Good luck!

**Comment by ramen-ctrl** [comment]
@dlawrences Thank you so much for your help! I've managed to add a new function so that my counter appears on the top left hand corner. However, I do have some problems regarding more than one class... I'm having trouble identifying where to increase the y value inside the loop when there is a second class. 
my function in utils is: 
![image](https://user-images.githubusercontent.com/67885168/87553782-e9c47c00-c6e5-11ea-9dff-2fb19cc81b58.png)
and I call it in detect.py: 
![image](https://user-images.githubusercontent.com/67885168/87553835-fb0d8880-c6e5-11ea-973f-45973d3ead55.png)

When I run this with multiple classes, the second class will just overwrite the first one, so I will only have one class and number reflected.

**Comment by dlawrences** [comment]
Hi @ramen-ctrl 

Glad that was useful. I would do the following changes to the **detect.py** script considering the function you have defined. Please check in the response above to understand where the modified `for` loop starts.

```python
# initialize coordinates of the first total class label
org = (50, 50)

 # Print results
 for c in det[:, -1].unique(): 
     n = (det[:, -1] == c).sum()  # detections per class
     total_det_per_class = '%g %ss, ' % (n, names[int(c)])  # add to string
     s += total_det_per_class + ', '
     
     # plot total number of detections per current class on img to account for possible multiple classes
     plot_counter(im0, total_det_per_class, org)
     
     # increase y axis coordinate by 10 px
     org = org[0], org[0] + 10
```

You would also have to tweak your function a bit to accept a point from which the text will be drawn.
```python
def plot_counter(img, label, org):
     ...
```

Please be mindful to remove the declaration of the point in the function body
```python
...
org = (50, 50)
...
```

I don't have the chance to test this, but it should work.

Good luck!

**Comment by ramen-ctrl** [comment]
@dlawrences Thank you so much for your help!!! I have successfully managed to do it 👍

**Comment by PraveenGit3** [comment]
Hi @ramen-ctrl  Could you  help how did you acheived  detetction per class is left corner of image or video  like
Detection per class A:10
Detection per class B:15
