### ISSUE TITLE
Training becomes much slower than before.

### ISSUE THREAD

**Issue by lity** [ultralytics/yolov5#3817]
I updated the project to the latest commit of https://github.com/ultralytics/yolov5/commit/02719dde52a99f28603be383334028a7ab9f1e06 and found that training becomes much slower than before https://github.com/ultralytics/yolov5/commit/63060910a68bfde238872d629ab88e2e7bc736e8

63060910a68bfde238872d629ab88e2e7bc736e8 version is about 4x faster than 02719dde52a99f28603be383334028a7ab9f1e06.

This is not a feature,  right?

**Comment by lity** [comment]
My machine has 1 GPU and I just simply run command:

python train.py --img 768 --batch 6 --epochs 600 --workers 0 --data D:/Workspace/waterdrop-2/dataset/patterns.yaml --weights yolov5m6.pt

**Comment by glenn-jocher** [comment]
@lity 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by lity** [comment]
> @lity 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible that still produces the same problem
> * ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
> * ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

I know minimal reproducible example is important for developers to locate the problem. But I don't have any code in this case, I just crreated my own dataset by labling images and then run train command.

Serveral days before (https://github.com/ultralytics/yolov5/commit/63060910a68bfde238872d629ab88e2e7bc736e8), it cost 36s to train 1 epoch, while it costs more than 2 minutes to train 1 epoch after I updated project to https://github.com/ultralytics/yolov5/commit/02719dde52a99f28603be383334028a7ab9f1e06 .

I guess some latest changes cause this.

**Comment by glenn-jocher** [comment]
@lity our Colab tutorial training runs in 0.007 hours normally. I just tested again and observe the same result. Since I am not able to reproduce your issue there is no action for Ultralytics to take.
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1450" alt="Screen Shot 2021-06-29 at 12 13 40 PM" src="https://user-images.githubusercontent.com/26833433/123780489-8a01b980-d8d3-11eb-820e-abffe8cbbd79.png">

**Comment by lity** [comment]
OK, let me try it again. If I find sth, I'll open a new issue.
