### ISSUE TITLE
why I get this error?

### ISSUE THREAD

**Issue by Mahsa-Nobakht** [ultralytics/yolov5#3823]
## 
Hi, I installed requirments and cloned it on colab but  I got this error
can you please help me?
thank u

## Additional context
Optimizer groups: 61 .bias, 61 conv.weight, 57 other
Traceback (most recent call last):
  File "train.py", line 659, in <module>
    main(opt)
  File "train.py", line 560, in main
    train(opt.hyp, opt, device)
  File "train.py", line 208, in train
    gs = max(int(model.stride.max()), 32)  # grid size (max stride)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'stride'

**Comment by glenn-jocher** [comment]
@mahsant 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Mahsa-Nobakht** [comment]
Hi
who knows why I get this error?
I still couldn't solve it.
Thank u.
