### ISSUE TITLE
The boxes information predicted in `Detect` layer is not coordinated

### ISSUE THREAD

**Issue by seekFire** [ultralytics/yolov5#3836]
## ❔Question
[These lines](https://github.com/ultralytics/yolov5/blob/02719dde52a99f28603be383334028a7ab9f1e06/models/yolo.py#L62-L68) show that the coordinates of center-points corresponds to input image, while the length of width & height corresponds to the feature map of output. Do you think is it right? You know after prediction, the boxes information will be applied to NMS. In NMS, I think the [transform](https://github.com/ultralytics/yolov5/blob/02719dde52a99f28603be383334028a7ab9f1e06/utils/general.py#L597) operation will generate error when using the boxes as mentioned above.

**Comment by glenn-jocher** [comment]
@seekFire Detect() layer and NMS are implemented correctly. If you believe otherwise please produce a minimum reproducible example of an error so that we can investigate.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by seekFire** [comment]
@glenn-jocher 
[These lines](https://github.com/ultralytics/yolov5/blob/02719dde52a99f28603be383334028a7ab9f1e06/models/yolo.py#L105-L109) in class **Model** shows that the member variable of class **Detect** —— **anchor_grid** has magnitude of size corresponds to the size of features in outputs, so the center-points ( **y[..., 0:2]**) & wh (**y[..., 2:4]**) do not have the same magnitude.
In contrast, [these code](https://github.com/ultralytics/yolov5/blob/02719dde52a99f28603be383334028a7ab9f1e06/utils/loss.py#L130-L131) in loss.py has the same magnitude of size. The center-points & wh are both under the magnitude of size of features.

**Comment by glenn-jocher** [comment]
@seekFire I don't really understand what you are saying. If you have a proposed change to the codebase the simplest way to evaluate it is to create a PR, check it out, and train a new model on it to evaluate the effect of your proposed modifications vs the baseline results in the README.

**Comment by seekFire** [comment]
@glenn-jocher It's my mistake. The member variable **anchors** & **anchor_grid** have been initialized to the same value in function **parse_model**. In class **Model** only **anchors** is changed. Thank u very much!
