### ISSUE TITLE
How to find out the maximum batch size that my machine can handle?

### ISSUE THREAD

**Issue by joneswilliam1** [ultralytics/yolov5#3847]
## ❔Question
Hi everyone, I'm sorry if this is a basic question but I have an RTX 2070 machine and while training a Yolov5 model on around 3500 images I first set batch size to 32 and got memory error, then switched to 16 and the run started successfully. So is it like a trial and error or is there a way to actually determine the maximum batch size that you machine is able to handle. Thank you.

**Comment by wudashuo** [comment]
CUDA memory error is related to your image size, batch size, and model size.
You can try batch size between 16 and 32 to determine the maximum batch size that your machine capable of.
`--workers` also affect memory to some extent.

**Comment by glenn-jocher** [comment]
@joneswilliam1 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="987" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by ajay78123** [comment]
I have Nvidia GTX 3090 with 16GB graphic card and i am able to train yolov5 with batch size if i want to increase batch size then i am getting OOM error. what should i do, i have tried to change paging file with maximum  values but nothing is chnaging.

**Comment by glenn-jocher** [comment]
@ajay78123 hello! With an Nvidia GTX 3090 and 16GB of VRAM, you should be able to train with a reasonably large batch size, but this also depends on the model size (s, m, l, x) and the input image resolution. If you're encountering OOM errors when increasing the batch size, here are a few suggestions:

1. **Reduce Image Size**: If you're using a large `--img-size`, consider reducing it. This will decrease the memory required per batch.
2. **Model Size**: If you're using a larger model variant like YOLOv5x, you might switch to YOLOv5l or YOLOv5m to reduce memory usage.
3. **Gradual Batch Size Increase**: Incrementally increase the batch size from the last known good configuration until you find the limit.
4. **Accumulate Gradients**: Use the `--accumulate` argument to accumulate gradients over multiple forward passes before performing a backward pass.
5. **Check for Other Processes**: Ensure no other memory-intensive processes are running on your GPU that could be consuming VRAM.
6. **System Monitor**: Use system monitoring tools to check real-time GPU memory usage.

Remember, the paging file (swap space) is used by the system when RAM is full, and it's much slower than VRAM. Adjusting the paging file size won't help with GPU memory (VRAM) limitations.

If you continue to have issues, consider training with a smaller model or reducing the image size further. Keep an eye on the memory usage with `nvidia-smi` to find the sweet spot for your setup. 🧐 Happy training!

**Comment by FraidOfWater** [comment]
> got memory error

I ran into this too, but on docker. It was a low shared memory issue.

```
docker run -it --gpus all --shm-size=16g ultralytics/ultralytics:latest
```

**Comment by pderrenger** [comment]
Thanks for sharing your Docker solution! For others facing memory errors, adjusting `--shm-size` can indeed help in containerized environments. Additional optimizations include reducing batch size with `--batch`, lowering image resolution with `--imgsz`, or using smaller models like YOLOv5s. For Docker configurations, see our [Ultralytics Docker Quickstart Guide](https://docs.ultralytics.com/guides/docker-quickstart).
