### ISSUE TITLE
Memory Leak in yolov5

### ISSUE THREAD

**Issue by m-vaibhav** [ultralytics/yolov5#3855]
## ❔Question
yolov5: Memory is increasing till GPU got out of memory (during inference).

## Additional context
Tensorrt: 7.2.2
PyTorch: 1.6
OS: ubuntu 20.04.2 LTS

Logs:
* **cuda-memcheck --leak-check full**:  got 0 errors 0 leaks [cuda-memcheck.log](https://github.com/ultralytics/yolov5/files/6749058/cuda-memcheck.log)
* **valgrind -v --tool=memcheck --leak-check=full --log-file=valgrind.log**: 16 bytes in 1 blocks are possibly lost in loss record 90 of 16,971 [valgrind.log](https://github.com/ultralytics/yolov5/files/6749057/valgrind.1.log)

**Comment by glenn-jocher** [comment]
@m-vaibhav 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by m-vaibhav** [comment]
The model is yolov5m finetuned on custom data with 3 object classes. Due to official reasons, I won't be able to share the entire code or the model but I hope the following details would help:

The model is ported to ONNX to be used in TensosrRT using the official code provided in this repository.

### Relevant code snippets:
**Model Initialization:**
```cpp
{
    auto builder = TRTUniquePTR<nvinfer1::IBuilder>(nvinfer1::createInferBuilder(common::gLogger.getTRTLogger()));
    if (!builder) {
        return false;
    }
    const auto explicitBatch = 1U << static_cast<uint32_t>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);
    auto network = TRTUniquePTR<nvinfer1::INetworkDefinition>(builder->createNetworkV2(explicitBatch));
    if (!network) {
        return false;
    }
    auto parser = TRTUniquePTR<nvonnxparser::IParser>(
            nvonnxparser::createParser(*network, common::gLogger.getTRTLogger()));
    if (!parser) {
        return false;
    }
    auto config = TRTUniquePTR<nvinfer1::IBuilderConfig>(builder->createBuilderConfig());
    if (!config) {
        return false;
    }

    auto constructed = constructNetwork(builder, network, config, parser);
    if (!constructed) {
        return false;
    }
    engine = std::shared_ptr<nvinfer1::ICudaEngine>(builder->buildEngineWithConfig(*network, *config),
                                                    common::InferDeleter());
    if (!engine) {
        return false;
    }
    context = std::shared_ptr<nvinfer1::IExecutionContext>(engine->createExecutionContext(), common::InferDeleter());

    // ... other code
}
```

**Preprocess Images:**
```cpp
{
    // ... other code
    batchTensor = torch::zeros({batchSize, 3,  640,  640}, options);

    Loop over batch size {
    // <Pre-process image in OpenCV>
    batchTensor[batchIndex] = torch::from_blob(FinalOutput, {640, 640, 3}, torch::kFloat32).contiguous().permute({2, 0, 1});
}

    if (!batchTensor.is_contiguous())
    {
        batchTensor = batchTensor.contiguous();
    }
    buffers.copyInputToDeviceAsync(inputNames[0], batchTensor.data_ptr(), cuStream);
}
```

**Forward Pass:**
```cpp
{
    // ... other code

    context->enqueue(batchSize, buffers.getDeviceBindings().data(), cuStream, nullptr);

    // ... other code
}
```

**Comment by glenn-jocher** [comment]
@m-vaibhav as noted above:

* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

Also your pipeline does not follow recommended practices. See **TensorRT Deployment** tutorial:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)
