### ISSUE TITLE
it is wrong when calculate box_iou

### ISSUE THREAD

**Issue by jack155861** [ultralytics/yolov5#3861]
## ❔Question
![image](https://user-images.githubusercontent.com/45505414/124308653-2c53c280-db9c-11eb-91c1-3097cbec1edc.png)

why it is show the error?
i have the wrong label?

  File "/home/jack155861/yolov5/test.py", line 194, in test
    ious, i = box_iou(predn[pi, :4], tbox[ti]).max(1)  # best ious, indices
IndexError: max(): Expected reduction dim 1 to have non-zero size.

**Comment by glenn-jocher** [comment]
@jack155861 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by annsonic** [comment]
I ran into the same bug after I integrate the random_perspective() funtion into SSD model. Maybe my setting makes the transformation do too much distortion so the box variable xy becomes an empty list.

I worked around: if xy is empty, annotate xy as background and the box size is the same as the whole image size. Hope this helps you.
