### ISSUE TITLE
TypeError: isinstance() arg 2 must be a type or tuple of types on Python 3.6

### ISSUE THREAD

**Issue by philippneugebauer** [ultralytics/yolov5#3899]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug

I'm trying to analyze a video on my Jetson NX inside a docker container with Python 3.6 environment.
Upgrading that seems to be a hassle and since Yolo states in the readme, it's supposed to run on Python 3.6, I'm opening a bug ticket.

## To Reproduce (REQUIRED)

Python 3.6 environment, linux/arm64

Input:
```
python3 detect.py --source  video.mp4
```

Output:
```
Traceback (most recent call last):
  File "detect.py", line 223, in <module>
    main(opt)
  File "detect.py", line 218, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 164, in run
    if isinstance(vid_writer[i], cv2.VideoWriter):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

## Expected behavior

I expect the analysis to run. Video analysis seems to work fine but the video saving crashes

## Environment

Jetson NX with nvcr.io/nvidia/l4t-ml:r32.5.0-py3 inside docker container
linux/arm64

**Comment by glenn-jocher** [comment]
@philippneugebauer we have a PR that we routinely use to check YOLOv5 python compatibility on the following combinations (all OS's tested on all python versions).

```yaml
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        model: [ 'yolov5s' ]  # models to test
```

The latest checks are all green:
https://github.com/ultralytics/yolov5/actions/runs/1002462921

The problem may be due to your Docker image or other aspect of your environment, perhaps your cv2 installation. Unfortunately we don't currently have Jetson NX devices nor official export pipelines, but hopefully the EXPORT Competition can help with this as Jetson Nano is one of the categories:

<p align="center">
  <a href="https://github.com/ultralytics/yolov5/discussions/3213">
  <img width="850" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/banner-export-competition.png"></a>
</p>

**Comment by philippneugebauer** [comment]
damit, I was hoping for a quick solution for that :(

**Comment by lonngxiang** [comment]
same problem，so how to solve it？

**Comment by glenn-jocher** [comment]
@lonngxiang 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by lonngxiang** [comment]
when run python3 detect.py --source 0

![image](https://user-images.githubusercontent.com/40717349/167962002-c572c966-08c1-45ba-8312-3adeea66ad05.png)


i have solve it,  change "detect.py", line 186, 
    if isinstance(vid_writer[i], cv2.VideoWriter) to  if isinstance(vid_writer[i], type(cv2.VideoWriter))

**Comment by glenn-jocher** [comment]
@lonngxiang great to hear that you were able to resolve the issue by modifying the code! Thank you for sharing the solution. Your contribution is appreciated by the YOLO community and the Ultralytics team. If you encounter any further difficulties or have additional insights to share, please do not hesitate to let us know. Happy coding!
