### ISSUE TITLE
zip argument #1 must support iteration

### ISSUE THREAD

**Issue by lcyhub** [ultralytics/yolov5#4007]
## Additional contex
![BW%95D{%_(PM}F1JEVCK_TI](https://user-images.githubusercontent.com/87465336/125741045-5eefe128-1b12-428f-840c-646df5b0ff05.png)

**Comment by glenn-jocher** [comment]
@lcyhub your code is out of date, please upgrade.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by gotsring** [comment]
For what it's worth, I had the same issue. Solution was to delete the labels.cache and val_labels.cache files (or similar, whatever your label directories are named).

**Comment by zixuxu000** [comment]
> For what it's worth, I had the same issue. Solution was to delete the labels.cache and val_labels.cache files (or similar, whatever your label directories are named).

It works,tks

**Comment by glenn-jocher** [comment]
@zixuxu000 i'm glad to hear the solution worked for you! If you encounter any more issues or have further questions, feel free to reach out. Happy coding! 😊
