### ISSUE TITLE
Question about training yolov5x6/yolov5l6 model on Tesla V100

### ISSUE THREAD

**Issue by winterfell2021** [ultralytics/yolov5#4013]
## ❔Question
Hi there, I use V100-32GB to train models. When I try to train yolov5 with the default config yolov5x6.yaml or yolov5l6.yaml and batch size 16, it gives me the Error:
```
  File "/data/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
Images sizes do not match. This will causes images to be display incorrectly in the UI.

```
Here is the train command
`python train.py --img 1280 --batch 16 --epochs 1000 --data js.yaml --cfg yolov5x6.yaml --device 0`
It works with yolov5m6.yaml. I find the error refer to the leak of gpu memory, but i only have V100. Is it possible or I need some tricks to train yolov5x6 or yolov5l6 on V100?

**Comment by glenn-jocher** [comment]
@winterfell2021 you can train any model with any GPU, there's no relation really.

If you think you have a reproducible bug we've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by winterfell2021** [comment]
@glenn-jocher 

Thanks for reply! I know its about gpu memory, not device. My dataset has 20k images and 5 categories. When i use batch size 16 and image size 1280 on yolov5m6, it costs 26757MiB. I trained 100 epoch, but the map doesnt well enough for my goal. I dont know if it is a wise choice to use batch size 8 and image size 1280 on yolov5x6 or yolov5l6, while training P6 model really takes long time. Can you give me some advice about setting the hyperparameter to train yolov5x6 or yolov5l6?

**Comment by glenn-jocher** [comment]
@winterfell2021 the P6 models in this repo were trained with 
https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-p6.yaml

See batch-size study for effects of batch size on training.
https://github.com/ultralytics/yolov5/discussions/2452
