### ISSUE TITLE
Ensemble Issue

### ISSUE THREAD

**Issue by Muhammad4hmed** [ultralytics/yolov5#4050]
When ensembling two models, I'm getting following error:

> fatal: not a git repository (or any parent up to mount point /kaggle)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
detect: weights=['/kaggle/input/weights-of-yolov5-150-epochs/best.pt', '/kaggle/input/siim-cov19-yolov5-train/yolov5/runs/train/exp/weights/best.pt'], source=/kaggle/tmp/test/image, imgsz=512, conf_thres=0.005, iou_thres=0.5, max_det=1000, device=, view_img=False, save_txt=True, save_conf=True, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=True, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=True, line_thickness=3, hide_labels=False, hide_conf=False, half=False
Ensemble created with ['/kaggle/input/weights-of-yolov5-150-epochs/best.pt', '/kaggle/input/siim-cov19-yolov5-train/yolov5/runs/train/exp/weights/best.pt']
image 1/2 /kaggle/tmp/test/image/51759b5579bc_image.png: Traceback (most recent call last):
  File "detect.py", line 228, in <module>
    main(opt)
  File "detect.py", line 223, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 106, in run
    visualize=increment_path(save_dir / 'features', mkdir=True) if visualize else False)[0]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'visualize'

and code is:
```
weights_dir = '/kaggle/input/weights-of-yolov5-150-epochs/best.pt'
weights_dir_1 = '/kaggle/input/siim-cov19-yolov5-train/yolov5/runs/train/exp/weights/best.pt'
!python detect.py --weights $weights_dir $weights_dir_1\
--img 512\
--conf 0.005\
--iou 0.5\
--source $test_dir\
--augment\
--save-txt --save-conf --exist-ok 
```

works fine when I use either of the model.

**Comment by glenn-jocher** [comment]
@Muhammad4hmed your code is out of date.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
