### ISSUE TITLE
GPU memory cost after eavlution mode

### ISSUE THREAD

**Issue by widerwew** [ultralytics/yolov5#4057]
## ❔Question
GPU takes up a lot of memory after evaluation

## Additional context
![image](https://user-images.githubusercontent.com/23101204/126092592-dc1cd0ab-35d6-448a-acfc-bbe9664c169f.png)
I found that the GPU takes up a lot of memory after evaluation. And it not be released while the train mode. Are there some variables not are released and cause it， which can cause that when the amount of data becomes larger, the batchsize becomes smaller. Can help improve it？

**Comment by wudashuo** [comment]
Can't understand your meaning, do you mean it still occupied GPU memory after training?  
You can use `kill -9` to kill it.

**Comment by glenn-jocher** [comment]
@EdisionWew 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="987" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by widerwew** [comment]
> Can't understand your meaning, do you mean it still occupied GPU memory after training?
> You can use `kill -9` to kill it.

The evalution will cost some GPU memory, and the costed memory will be released after evalution. But I found that Gpu0 takes up a lot of memory in evaluate while training, and which can not be released after the epoch evalution, the Gpu0 memory keeps it steady. The batchsize can reach 128 and not cause OOM, when the data size is 50,000. But the batchsize can only set 8 and cause OOM, when the data size is 50,0000. Which is bothering me...

**Comment by widerwew** [comment]
> @EdisionWew 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:
> 
> <img alt="Screenshot 2021-05-28 at 12 19 51" width="987" src="https://user-images.githubusercontent.com/26833433/119969671-22dca680-bfaf-11eb-92af-5908f9743229.png">
> 
> If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:
> 
> * Reduce `--batch-size`
> * Reduce `--img-size`
> * Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
> * Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
> * Upgrade your hardware to a larger GPU
> * Train on free GPU backends with up to 16GB of CUDA memory: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)

@glenn-jocher Hello, Thanks for your reply. I am training yolov5 by a large data size. But facing that when the amount of data becomes larger, the batchsize becomes smaller. I found that the Gpu0 costed memory in evalution cause the smller batchsize, and the smaller batchsize will cause the  longer training period. Can it be better if the evalutions also use multi-gpu？Which is bothering me...

**Comment by glenn-jocher** [comment]
@EdisionWew dataset size and CUDA memory are unrelated. 

If you have a reproducible issue that meets all of the below criteria then please let us know, otherwise your issue is non-actionable by Ultralytics.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
