### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by yiwangde** [ultralytics/yolov5#406]
## ❔Question
I want to train in my two servers, but error. Is there anyone like me?
I tried to resize the picture but it didn't work

RuntimeError: Caught RuntimeError in DataLoader worker process 0.                                    Original Traceback (most recent call last):                                                            
File "/home/luguangjian/.conda/envs/yolov5/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop                                                                   
data = fetcher.fetch(index)                                                                        
File "/home/luguangjian/.conda/envs/yolov5/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch                                                                                 
return self.collate_fn(data)                                                                       
File "/home/luguangjian/yolov5-master/utils/datasets.py", line 548, in collate_fn                      
return torch.stack(img, 0), torch.cat(label, 0), path, shapes                                      
File "/home/luguangjian/.conda/envs/yolov5/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/wrap.py",line 81, in wrapper                                                               
return orig_fn(seq, *args, **kwargs)        
                                                    

 RuntimeError: stack expects each tensor to be equal size, but got [3, 448, 640] at entry 0 and [3, 640, 480] at entry 1

**Comment by glenn-jocher** [comment]
@yiwangde I don't understand your question. To detect at a specific size:
`python detect.py --img 768`

**Comment by yiwangde** [comment]
I have solved this

**Comment by zfli-xdu** [comment]
> I have solved this

hi, in training, when the model proceed test process, i met this issue too. can you tell me how to solve this?

**Comment by zfli-xdu** [comment]
> @yiwangde I don't understand your question. To detect at a specific size:
> `python detect.py --img 768`

in training, when the model proceed test process, i met this issue 'RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 480] at entry 0 and [3, 640, 640] at entry 1' too. (did not set --notest in training)
the training process is fine, but the test one seems dont resize image to the same shape. can you help me to solve this?

**Comment by Pluto1314** [comment]
@yiwangde I also have some question, can you tell me how to solve it ? Thanks

**Comment by glenn-jocher** [comment]
@Pluto1314 Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a new `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible with [COCO](https://cocodataset.org/#home) or [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, ensure your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
