### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by KKKKQF** [ultralytics/yolov5#4094]
## ❔Question
I use my own custom.yaml to train.But it don't work?
![image](https://user-images.githubusercontent.com/87752678/126453297-63417abb-02a0-4e9f-9d75-1aad82c9b8ad.png)

![image](https://user-images.githubusercontent.com/87752678/126453053-63f7f689-3447-48f7-b774-3bf7c98c8a1f.png)

**Comment by KKKKQF** [comment]
this is my label 
![image](https://user-images.githubusercontent.com/87752678/126453467-2a567541-3858-4c7a-a3cd-b0e9c458033b.png)

**Comment by glenn-jocher** [comment]
@KKKKQF duplicate labels mean your *.txt files have multiple duplicate rows, i.e. you've labelled the same object multiple times

**Comment by KKKKQF** [comment]
> @KKKKQF duplicate labels mean your *.txt files have multiple duplicate rows, i.e. you've labelled the same object multiple times

oh thanks,I check my labels again,it does have this problem,I will try to improve it

**Comment by glenn-jocher** [comment]
@KKKKQF we have the option to correct these incidences automatically of course also but I'm not sure if that's the best approach, because then users may be left unaware that they have duplicate labels. 

In any case, if duplicate labels are found an image is ignored, but training still proceeds with the rest of the dataset. In your case maybe your whole dataset is made up of images with duplicate labels.

**Comment by KKKKQF** [comment]
> @KKKKQF我们当然也可以选择自动更正这些事件，但我不确定这是否是最好的方法，因为这样用户可能不知道他们有重复的标签。
> 
> 在任何情况下，如果发现重复标签，图像将被忽略，但训练仍继续处理数据集的其余部分。在您的情况下，您的整个数据集可能由具有重复标签的图像组成。

you are right ,when I batch convert JSON files into XML files, I use an extra for ,It leads to a lot of duplicate data

**Comment by no-ask-star** [comment]
hello, i miss the same problem when i want to train a model to detect face of human, and i have no idea about how to solue this problem

**Comment by glenn-jocher** [comment]
@no-ask-star 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
