### ISSUE TITLE
Convert  yolov5s.pt to ONNX ?

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#412]
## ❔Question
**When i use the command " python models/export.py --weights yolov5s.pt --img 640 --batch 1" to convert yolov5s.pt to ONNX,it can generate yolov5s.torchscript ,but can not to generate ONNX file,and the error show below:**

Namespace(batch_size=1, img_size=[640, 640], weights='yolov5s.pt')

curl: (7) Failed to connect to drive.google.com port 443: 拒绝连接
Downloading https://drive.google.com/uc?export=download&id=1R5T6rIyy3lLwgFXNms8whc-387H0tMQO as yolov5s.pt... Download error 

/home/.local/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/.local/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
TorchScript export success, saved as yolov5s.torchscript
ONNX export failed: No module named 'onnx'
**How can i solve this problem ?**

**Comment by xevolesi** [comment]
Hi @china56321 

I managed to successfully export the model to ONNX by doing the following:

1. Be sure you have ONNX installed (i just run `pip install onnx` on my venv);
2. Go to your yolov5 directory: `cd /home/username/yolov5`;
3. Run command: `export PYTHONPATH="$PWD" && python models/export.py --weights pretrained/yolov5s.pt --img 640 --batch 1`

Note: I download weights by myself from google drive and put them into yolov5/pretrained directory.
Hope it will help you!

**Comment by china56321** [comment]
> Hi @china56321
> 
> I managed to successfully export the model to ONNX by doing the following:
> 
> 1. Be sure you have ONNX installed (i just run `pip install onnx` on my venv);
> 2. Go to your yolov5 directory: `cd /home/username/yolov5`;
> 3. Run command: `export PYTHONPATH="$PWD" && python models/export.py --weights pretrained/yolov5s.pt --img 640 --batch 1`
> 
> Note: I download weights by myself from google drive and put them into yolov5/pretrained directory.
> Hope it will help you!

Thanks , I successfully convert yolov5s.pt to onnx, I didn't install onnx .

**Comment by demi543** [comment]
> Hi @china56321
> 
> I managed to successfully export the model to ONNX by doing the following:
> 
> 1. Be sure you have ONNX installed (i just run `pip install onnx` on my venv);
> 2. Go to your yolov5 directory: `cd /home/username/yolov5`;
> 3. Run command: `export PYTHONPATH="$PWD" && python models/export.py --weights pretrained/yolov5s.pt --img 640 --batch 1`
> 
> Note: I download weights by myself from google drive and put them into yolov5/pretrained directory.
> Hope it will help you!

I exported the model to ONNX successfully. But I got different confidence scores when I used ONNX and PT to detect the same picture. I really don't know why?

**Comment by kanak8278** [comment]
`File "export.py", line 489, in run
model = attempt_load(weights, device=device, inplace=True, fuse=True)  # load FP32 model
File "/home/edgeneural/artifacts/yolov5/models/experimental.py", line 81, in attempt_load
ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'to'`

Trying to convert custom yolov5s.pt to ONNX but getting this error.

**Comment by glenn-jocher** [comment]
@kanak8278 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
