### ISSUE TITLE
Reboot when train launched

### ISSUE THREAD

**Issue by fnando1995** [ultralytics/yolov5#416]
## ❔Question
Is there anything in the train.py execution that can lead to reboot the machine?.

## Additional context

I have tried to train the model using the tutorial, but when using the following command the machines reboot after some messages (I can't put the messages displayed due to the reboot):

`python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --cfg yolov5s.yaml --weights yolov5s.pt --nosave --cache`

Any advice will be really appreciated.

I am using:

- Ubuntu 20.04.
- python3.8.2.
- an environment with the requirements as stated except numpy==1.19.0.
- GPU GForce 1080Ti.
- No Apex (at least to my knowledge in the machine)

**Comment by glenn-jocher** [comment]
@fnando1995 no, there's no code to reboot in the repo. Another issue is open on the subject as well. Is this reproducible in one of the 4 environments below? If you can can create a reproducible event in one of the environments below we can get started debugging it. If not the problem is non-actionable by us (there is nothing for us to do).

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by fnando1995** [comment]
@glenn-jocher There were some Cuda-python-ubu20 incompatibilities. I guess. All normal now.
