### ISSUE TITLE
True Divide Error with Reproducible Code

### ISSUE THREAD

**Issue by JINO-ROHIT** [ultralytics/yolov5#4237]
Im trying to train images of size 680 * 720 and run inference on videos of the same dimension.
This is the error that i receive

![yolov5](https://user-images.githubusercontent.com/63234112/127664381-62f09798-ac0f-4cdc-92b3-a22c9d6a34b1.png)

Steps to reproduce 
the training runs fine and below is the code i use 
!python train.py --batch 32 --epochs 10 --data data.yaml --cfg models/yolov5s.yaml --name wm  --img 720

for inference, i use this code(this is what throws the error)
!python detect.py --source '/content/data/test_videos/0.mp4' --weights MODEL_PATH --img 720

Thanks

**Comment by JINO-ROHIT** [comment]
https://colab.research.google.com/drive/1s2357c2qd5xDs_AS3U5LM3NnQjpcSXfb?usp=sharing
In case the colab notebook helps to see better

**Comment by glenn-jocher** [comment]
@JINO-ROHIT 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. Your issue is **not reproducible** and thus non-actionable by Ultralytics. Training with your command and running video inference operates correctly:

Reproduce with https://ultralytics.com/assets/decelera_landscape.mov

<img width="1379" alt="Screenshot 2021-07-30 at 18 21 06" src="https://user-images.githubusercontent.com/26833433/127682509-18ebefeb-f4ff-4aac-a54d-6fad397682b9.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
