### ISSUE TITLE
W&B: Step count is doubled

### ISSUE THREAD

**Issue by AyushExel** [ultralytics/yolov5#4248]
W&B plots step count is double what it's supposed to be. Multiple users have reported this on [wandb github](https://github.com/wandb/client/issues/2444).
@glenn-jocher I think this has something to do with the revamp of new logger API. I'll investigate and fix it this week. I'm raising this issue so we don't forget. 

## To Reproduce (REQUIRED)
run `python train.py` with wandb installed

## Expected behavior
The number of steps of panels should be equal to epochs

**Comment by glenn-jocher** [comment]
@AyushExel thanks for spotting this! I tested W&B logging in the initial loggers refactor PR https://github.com/ultralytics/yolov5/pull/4137 and made sure the steps were equal to the epochs, but have not tested since then, so I think if you do a diff from that commit to master the issue should in the diff.

**Comment by glenn-jocher** [comment]
@AyushExel just trained notebook with master for 10 epochs and everything logs correctly:
https://wandb.ai/glenn-jocher/YOLOv5/runs/i0eat7vt?workspace=user-glenn-jocher

**Comment by AyushExel** [comment]
@glenn-jocher awesome. Thanks, I'll close this issue

**Comment by glenn-jocher** [comment]
@AyushExel ok! I've got 8 models training currently and epochs log correctly as far as I can tell, so this might be a false alarm.

**Comment by AyushExel** [comment]
@glenn-jocher Great! that's good to know
