### ISSUE TITLE
Attribute error problem -> 'Model' object has no attribute 'md'

### ISSUE THREAD

**Issue by John12Reaper** [ultralytics/yolov5#427]
Traceback (most recent call last):
  File "train.py", line 385, in <module>
    train(hyp)
  File "train.py", line 83, in train
    assert model.md['nc'] == nc, '%s nc=%g classes but %s nc=%g classes' % (opt.data, nc, opt.cfg, model.md['nc'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'md'

I have trained my custom dataset and it worked previously.
but now when I tried to train MSCOCO set then it is saying this. 
I also used a write code to save the result as last.pt but now when i run the resume train.py code its not working
and the main thing says that source code 

/usr/local/lib/python3.6/dist-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)

What to do? please help...

**Comment by glenn-jocher** [comment]
Your model, your code, or both are likely out of date.

**Comment by John12Reaper** [comment]
Then what to do?
Isn't there a way to solve this?


> Your model, your code, or both are likely out of date.

Then What to do?

**Comment by John12Reaper** [comment]
> Your model, your code, or both are likely out of date.

**Comment by glenn-jocher** [comment]
Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a fresh `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
python train.py  # verify training (a few batches only)
# CODE TO REPRODUCE YOUR ISSUE HERE
```
- **Your custom data.** If your issue is not reproducible with COCO data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
- **Your environment.** If your issue is not reproducible in our [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) VM or Jupyter Notebook we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, PyTorch >= 1.5 etc. You can also use our [Jupyter Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> and our [Docker Image](https://hub.docker.com/r/ultralytics/yolov5) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker) to test your code in a working environment.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!

**Comment by John12Reaper** [comment]
@glenn-jocher  Yes My problem or issue occurred when I started to train MS COCO data.

**Comment by glenn-jocher** [comment]
@John12Reaper training on COCO is easy:

```bash
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
bash data/get_coco2017.sh && mv coco ..
python train.py --data coco.yaml
```

**Comment by John12Reaper** [comment]
@glenn-jocher Could you please give me the original source code before the recent update. That could help me a lot...

**Comment by John12Reaper** [comment]
@glenn-jocher this is the message it's giving before error
"source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True`"
