### ISSUE TITLE
Trouble starting training - keeps crashing

### ISSUE THREAD

**Issue by robotaiguy** [ultralytics/yolov5#4306]
I don't understand what's going on. I'm using the same train commands and dataset preparation that I always used with yolov5 (at least I think I am). But I"m having the same issue on 2 different computers. Linux machines (18.04 and 20), both with 2 gpus, but I"m just trying with single gpu for now. I'm using a python3 venv and pip installed all requirements.

command:
python3 train.py --img 640 --batch 16 --epochs 300 --data ./data/tally.yaml --cfg ./models/tally5s.yaml --name v5s-tally-640 --hyp ./data/tally_hyp_scratch.yaml --cache

My -tally.yaml file simply has the paths for train, test, and valid, as well as number of classes: 7 and the class names
train: /media/suneberg/Data2/yolov5-tally/train.txt  # 118287 images
val: /media/suneberg/Data2/yolov5-tally/valid.txt  # 5000 images
test: /media/suneberg/Data2/yolov5-tally/test.txt  # 20288 of 40670 images

My tally5s.yaml file simply has the number of classes change. My hyp file has the hyperparameters configured (I like to rotate my images 5%, etc).

It "appears" to be able to find my dataset properly because it creates the cache files. But then it crashes on the first iteration.

train: Scanning '/media/suneberg/Data2/yolov5-tally/train' images and labels...11115 found, 0 missing, 0 empty, 0 corrupted: 100%|███████████████████████| 11115/11115 [00:04<00:00, 2692.77it/s]
train: New cache created: /media/suneberg/Data2/yolov5-tally/train.cache
train: Caching images (11.4GB ram): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11115/11115 [00:59<00:00, 187.90it/s]
val: Scanning '/media/suneberg/Data2/yolov5-tally/valid' images and labels...2084 found, 0 missing, 0 empty, 0 corrupted: 100%|████████████████████████████| 2084/2084 [00:00<00:00, 2541.84it/s]
val: New cache created: /media/suneberg/Data2/yolov5-tally/valid.cache
val: Caching images (2.1GB ram): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2084/2084 [00:15<00:00, 137.23it/s]
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 4.76, Best Possible Recall (BPR) = 0.9889
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/train/v5s-tally-64011
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|                                                                                                                                                                     | 0/87 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 596, in <module>
    main(opt)
  File "train.py", line 495, in main
    train(opt.hyp, opt, device)
  File "train.py", line 290, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/suneberg/Git/yolov5/utils/datasets.py", line 136, in __iter__
    yield next(self.iterator)
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/suneberg/Venvs/venv-yolov5/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/suneberg/Git/yolov5/utils/datasets.py", line 531, in __getitem__
    img, labels = load_mosaic(self, index)
  File "/home/suneberg/Git/yolov5/utils/datasets.py", line 696, in load_mosaic
    img4, labels4, segments4 = copy_paste(img4, labels4, segments4, p=self.hyp['copy_paste'])
KeyError: 'copy_paste'

wandb: Waiting for W&B process to finish, PID 1138857
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Find user logs for this run at: /home/suneberg/Git/yolov5/wandb/run-20210804_090908-2unihus1/logs/debug.log
wandb: Find internal logs for this run at: /home/suneberg/Git/yolov5/wandb/run-20210804_090908-2unihus1/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced v5s-tally-640: https://wandb.ai/suneberg/YOLOv5/runs/2unihus1## Additional context

**Comment by glenn-jocher** [comment]
@robotwhispering your code and hyps are out of date.

**Comment by lllan1000** [comment]
how to deal with it

**Comment by glenn-jocher** [comment]
@llan1000 we've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
