### ISSUE TITLE
Cache directory ../datasets/my_data/labels is not writeable

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [ultralytics/yolov5#4348]
- Error: Cache directory ../datasets/my_data/labels is not writeable: [Errno 2] No such file or directory: '../datasets/my_data/labels/all.cache.npy' -> '../datasets/my_data/labels/all'
- my_data.yaml (similiar as coco128.yaml)

## 🐛 Bug

I'm usnig my own dataset, but the image type is in '.dat' form. So I changed the  image acceptable suffixes by adding 'dat' into the list. But once I did that, it cannot search the labels file(the label files are already in form)

## To Reproduce (REQUIRED)

Input:

```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:

```
Traceback (most recent call last):
  File "train.py", line 600, in <module>
    main(opt)
  File "train.py", line 498, in main
    train(opt.hyp, opt, device)
  File "train.py", line 206, in train
    prefix=colorstr('train: '))
  File "/home/jude/CHIEF/桌面/yolov5/yolov5-master/utils/datasets.py", line 104, in create_dataloader
    prefix=prefix)
  File "/home/jude/CHIEF/桌面/yolov5/yolov5-master/utils/datasets.py", line 414, in __init__
    assert nf > 0 or not augment, f'{prefix}No labels in {cache_path}. Can not train without labels. See {HELP_URL}'

RuntimeError: ZeroDivisionError
```

## Expected behavior

support the image (in .dat format) training

**Comment by LIUZIJING-CHN** [comment]
ignore the 'input' section, I forgot to change that part

**Comment by archg2021** [comment]
@LIUZIJING-CHN I get the same error. Were yu able to solve it??

**Comment by glenn-jocher** [comment]
@archg2021 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
