### ISSUE TITLE
autoanchor: WARNING: Extremely small objects found. 5669 of 8075 labels are < 3 pixels in size. How about using yolov5 for small target detection? Any suggestions?

### ISSUE THREAD

**Issue by ts19970816** [ultralytics/yolov5#4350]
autoanchor: Analyzing anchors... anchors/target = 0.79, Best Possible Recall (BPR) = 0.2972. Attempting to improve anchors, please wait...
autoanchor: WARNING: Extremely small objects found. 5669 of 8075 labels are < 3 pixels in size.
autoanchor: Running kmeans for 9 anchors on 4646 points...
autoanchor: thr=0.25: 0.9022 best possible recall, 2.18 anchors past thr
autoanchor: n=9, img_size=640, metric_all=0.157/0.503-mean/best, past_thr=0.456-mean: 4,2,  2,4,  9,7,  9,16,  24,18,  32,46,  70,76,  93,172,  401,213
autoanchor: Evolving anchors with Genetic Algorithm: fitness = 0.6721: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 1446.72it/s]
autoanchor: thr=0.25: 0.9020 best possible recall, 2.61 anchors past thr
autoanchor: n=9, img_size=640, metric_all=0.183/0.529-mean/best, past_thr=0.464-mean: 2,3,  3,2,  4,4,  8,9,  15,15,  25,31,  65,57,  73,190,  411,204
autoanchor: New anchors saved to model. Update model *.yaml to use these anchors in the future.

**Comment by z430** [comment]
you could use high image resolution as mentioned in here https://docs.ultralytics.com/guides/model-training-tips/

**Comment by ts19970816** [comment]
Thank you, it seems that your suggestion can't help much

**Comment by mxy5201314** [comment]
The effect of using yolov5 to detect small objects is good. If it is automatically detected that your best possible recall (BPR) is less than 0.98, it will automatically calculate the anchor for you.
It is recommended to cut the picture before detecting small objects

**Comment by guyiyifeurach** [comment]
> The effect of using yolov5 to detect small objects is good. If it is automatically detected that your best possible recall (BPR) is less than 0.98, it will automatically calculate the anchor for you.
> It is recommended to cut the picture before detecting small objects

cut the picture? Can you support more detailed information? Thank you a lot!

**Comment by pedropcamellon** [comment]
I'm using PenFuddanPedestrian dataset and I'm getting the same error. It could be due to the labels?
This is the corresponding to "FudanPed00001.png"
FudanPed00001.txt :
0 0.41323792486583183 0.0007709662777347609 0.25402504472271914 0.000473927322243879 
0 0.853309481216458 0.001591995300776974 0.20572450805008943 0.0003838143806904654

**Comment by pderrenger** [comment]
The issue you're encountering is likely due to the extremely small bounding boxes in your labels. Consider increasing the image resolution or adjusting the dataset to ensure objects are larger than a few pixels. You might also try preprocessing the images by cropping or resizing to better capture small objects. For more tips, visit [YOLOv5 Training Tips](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/).
