### ISSUE TITLE
How to use GHM Loss?

### ISSUE THREAD

**Issue by zhangwei-swpu** [ultralytics/yolov5#4397]
I want to introduce GHM Loss in YOLOv5 to solve the problem of outliers samples
The paper addresses：https://arxiv.org/abs/1811.05181v1

github：https://github.com/libuyu/GHM_Detection

**Comment by glenn-jocher** [comment]
@zhangwei-swpu I don't know what GHM is. You might want to include references, citations etc. for feature requests if you expect a useful community response.

**Comment by DimplesL** [comment]
Same question, does anyone have any idea? 
ghm loss like: https://github.com/libuyu/GHM_Detection

**Comment by glenn-jocher** [comment]
@DimplesL @zhangwei-swpu thanks for the references! You may want to reach out the GHM author @libuyu to see if he'd consider a PR for YOLOv5.

Since GHM was introduced 2-3 years ago YOLOv5 didn't exist back then, but in the meantime we've gotten more popular than MMDetection, so it would be awesome if they could consider a PR to help interested users.
