### ISSUE TITLE
There is a problem with real time detection

### ISSUE THREAD

**Issue by ccm516** [ultralytics/yolov5#4427]
## ❔Question
Thank you for your project

when i run detect.py for real time detection in my desktop, I used 'python detect.py --weights C:\\Users\\best.pt  --source 0'
but it's not working.

when i connected cam by USB 3.0, below error occurred
---------------------------------------------
1/1: 0...  success (640x480 at 1.00 FPS).
Traceback (most recent call last):
  File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 52, in detect
    dataset = LoadStreams(source, img_size=imgsz)
  File "C:\Users\yolov5\utils\datasets.py", line 250, in __init__
    s = np.stack([letterbox(x, new_shape=self.img_size)[0].shape for x in self.imgs], 0)  # inference shapes
  File "C:\Users\yolov5\utils\datasets.py", line 250, in <listcomp>
    s = np.stack([letterbox(x, new_shape=self.img_size)[0].shape for x in self.imgs], 0)  # inference shapes
  File "C:\Users\yolov5\utils\datasets.py", line 689, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'
----------------------------------------------

but when i connected same cam by USB 2.0 and same code used, it's working.....
----------------------------------------------
1/1: 0...  success (640x480 at 30.00 FPS).
0: 512x640 1 class, Done. (0.636s)
0: 512x640 1 class, Done. (0.066s)
----------------------------------------------

Q.1
Is it just because of the difference in connection method?

Q.2
I wonder how to connect multiple cameras at the same time for real time detection

please help me.

**Comment by glenn-jocher** [comment]
@ccm516 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ccm516** [comment]
Thanks for the answer

Could you answer about Q.2?

**Comment by glenn-jocher** [comment]
@ccm516 place camera addresses in a text file with one per line:
```
python detect.py --source streams.txt
```

**Comment by ccm516** [comment]
ex) when two cameras are connected

in cams.txt
------
0
1
------
right??
