### ISSUE TITLE
diff result with similar images

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#4444]
## ❔Question
Sometime, the similar images have different result.
General deep learning have the status.
Do you know the reason?

![image](https://user-images.githubusercontent.com/59388989/129655110-a684adf8-df4c-4293-8a8e-9de9356ad680.png)

![image](https://user-images.githubusercontent.com/59388989/129655138-7beb149b-2554-43e6-b26f-f6b3c02bb9ea.png)

**Comment by glenn-jocher** [comment]
@alicera 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by alicera** [comment]
For example
```
python detect.py --source 'https://www.youtube.com/watch?v=4PDgWAXD6Os'
```
This is from the first of video
![image](https://user-images.githubusercontent.com/59388989/129706868-a97c1638-ad02-4356-bad6-aced35260ab8.png)

![image](https://user-images.githubusercontent.com/59388989/129706930-df7c7d58-80bd-454e-b9a5-103a3edbb966.png)

**Comment by glenn-jocher** [comment]
@alicera I think in these sorts of cases a detection slightly below confidence threshold = 0.25 will not generate a detection, whereas if the confidence increases slightly, i.e. to 0.35 then you will see a box. So the differences are small, some simply fall on either side of the confidence threshold.

**Comment by alicera** [comment]
Asume the second image train conf is 0.85.
So the deep learning cant avoid the status.

**Comment by glenn-jocher** [comment]
@alicera it's 0.35, which is very close to threshold.
