### ISSUE TITLE
custom train of yolov5m with --img 640 fails in CPU

### ISSUE THREAD

**Issue by baleris** [ultralytics/yolov5#4453]
I am trying to train my custom dataset with yolov5m with image size of --img 640 in CPU power. The training process gets "Killed". Is this expected behavior in CPU power ? I can train yolov5s --img 640 --batch 16, yolov5m --img 416 --batch 16 without any interruption but when i tries to increase the image size or batch size it terminates saying "Killed".

Do we need GPU power to train these configurations ? or something else i have missed here ....

<img width="485" alt="Capture" src="https://user-images.githubusercontent.com/71070130/129729042-21580fad-64f8-4837-b413-46990ac1f156.PNG">

**Comment by glenn-jocher** [comment]
@baleris all models can train on CPU. It appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by baleris** [comment]
@glenn-jocher I have created new environment in local with python 3.8.5 and cloned repo and installed requirement.txt. Still i see a same error...

**Comment by glenn-jocher** [comment]
@baleris all models train correctly on CPU, as I've already told you above.

<img width="1277" alt="Screenshot 2021-08-18 at 11 57 41" src="https://user-images.githubusercontent.com/26833433/129878806-0a5bc9f3-3183-4692-8e8e-0cbcc816f942.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by baleris** [comment]
@glenn-jocher in above case you are fine tuning the yolov5m by specifying --weight yolov5m.pt. If i want to train it from scratch like in place of weight i specify --weight ' ' and --cfg ./models/yolov5s.yaml in that case it will be an error.

my cmd is : python train.py --img 640 --batch 16 --epochs 100 --data ./data.yaml --cfg ./models/yolov5m.yaml --weights '' --name yolov5m_results  --cache

**Comment by glenn-jocher** [comment]
@baleris you are incorrect. All training setups operate correctly, CI checks run every 24 hours and on every commit as above messages already state. Again I can reproduce your command perfectly well. Please do not waste our time with non-reproducible issues. 

<img width="1304" alt="Screenshot 2021-08-18 at 17 29 39" src="https://user-images.githubusercontent.com/26833433/129926932-46db6b1c-ee0b-435b-9f2b-fb9f12710d2a.png">
