### ISSUE TITLE
RTSP stream error

### ISSUE THREAD

**Issue by lavrenkov-sketch** [ultralytics/yolov5#4469]
hello @glenn-jocher help me please with problem
when use rstp source i got h264 errors: `[h264 @ 0x8ac6b940] left block unavailable for requested intra mode` 
and the picture just falls apart
How can this be fixed? do you have any ideas?

**Comment by lavrenkov-sketch** [comment]
```python
import cv2
import io
from PIL import Image
import numpy as np
import base64
import requests
# import os
import logging
import json
import queue
import time
import threading

q = queue.Queue()
q_api = queue.Queue()

url_cam = "rtsp://1.1.1.1:554/Streaming/Channels/01/"
read_every_frame = 1

def Receive():
    print("start Reveive")
    vcap = cv2.VideoCapture(url_cam)

    ct = 0
    while (1):
        ct += 1
        ret = vcap.grab()
        if ct % read_every_frame == 0:  # skip some frames
            ret, frame = vcap.retrieve()
            if not ret: break
            q_api.put(frame)
            q.put(frame)


def Display():
    print("Start Displaying")
    while True:
        if q.empty() != True:
            frame = q.get()
            cv2.imshow("frame1", frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

if __name__ == '__main__':
    p1 = threading.Thread(target=Receive)
    p2 = threading.Thread(target=Display)
    p1.start()
    p2.start()


```

this code completely solves the problem how could we inject it into the library?

**Comment by glenn-jocher** [comment]
@lavrenkov-sketch 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
