### ISSUE TITLE
makesense.ai labeled data cp950 codec error

### ISSUE THREAD

**Issue by eecmyang** [ultralytics/yolov5#4475]
## ❔Question

I used makesense.ai to labeled and exported in YOLO format text files,

but somehow when I executed training, it just kept telling me codec error.

`UnicodeDecodeError: 'cp950' codec can't decode byte 0xf0 in position 9: illegal multibyte sequence`

Anyone knows why and how to resolve it?

Thanks.

## Additional context
Error command line information screenshot
[https://i.imgur.com/c8A4CsS.jpg](url)

**Comment by eecmyang** [comment]
### Supplements

Supplementing my dataset download link:

[https://bit.ly/3k6Wlj6](url) # (Shared through Google Drive)

**Comment by glenn-jocher** [comment]
@eecmyang 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

@SkalskiP we have a makesense fan!

**Comment by eecmyang** [comment]
I have tested with my peers previous download versions of yolov5s and it can successfully load, and train the data. Going to wrap everything with current git version that cause encode decode cp950 errors to make a bug report soon.

Thanks.
