### ISSUE TITLE
onnxruntime  has error in detect.py

### ISSUE THREAD

**Issue by henbucuoshanghai** [ultralytics/yolov5#4484]
I  change nothing about the detect.py!!

File "detect.py", line 118, in run
    pred = torch.tensor(session.run([session.get_outputs()[0].name], {session.get_inputs()[0].name: img}))
  File "anaconda3/envs/yolov5/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 3 Got: 512 Expected: 640
 Please fix either the inputs or the model.

**Comment by glenn-jocher** [comment]
@henbucuoshanghai 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Guttappa1238** [comment]
i got this error while running `detect.py `using `best.onnx` model

please help me with this

onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 1216 Expected: 1280
 Please fix either the inputs or the model

**Comment by glenn-jocher** [comment]
@Guttappa1238 for best ONNX inference results use `--dynamic` option at export time:

```bash
# Export
python export.py --weights yolov5s.pt --include onnx --dynamic

# Inference
python detect.py --weights yolov5s.onnx
```

**Comment by droukd** [comment]
I am surprised, no-one helped.
Just set `--imgsz` and you are set. Not a bug.

**Comment by vigneshrk29** [comment]
Hi @droukd :

Can you please let me know how to use --imgsz when you are trying to infer using an onnx model?

Thanks

**Comment by glenn-jocher** [comment]
Hello @vigneshrk29

You can use the `--imgsz` option while running the `detect.py` script to specify the input size of your images. For example:

```bash
python detect.py --weights weights/best.onnx --imgsz 640 --conf 0.4 --source data/images/
```

Please note that `--imgsz` must be a multiple of 32. Also make sure that the `--imgsz` you specify matches the size of the images that your model was trained on.

Hope that helps! Let us know if you have any other questions or issues.

**Comment by DoctorSlimm** [comment]
> @Guttappa1238 for best ONNX inference results use `--dynamic` option at export time:
> 
> ```shell
> # Export
> python export.py --weights yolov5s.pt --include onnx --dynamic
> 
> # Inference
> python detect.py --weights yolov5s.onnx
> ```

this solves the problem very well!

**Comment by glenn-jocher** [comment]
@DoctorSlimm Thank you for confirming that using the `--dynamic` option at export time resolved the issue for you. We're glad to hear that it solved the problem effectively. If you have any further questions or need additional assistance, please don't hesitate to ask.
