### ISSUE TITLE
How about using einops package for Detect layer?

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/yolov5#4485]
https://github.com/ultralytics/yolov5/blob/d1182c4f29e2141be856b85c5d613480a2fffc5d/models/yolo.py#L50-L56

@glenn-jocher 

Hi, jocher!

Have you ever heard of [einops](https://github.com/arogozhnikov/einops) package?

I think it can make `reshape process` more intuitive than native implementation based on PyTorch operation.

![image](https://user-images.githubusercontent.com/35001605/130015784-a116534b-a6c7-4f35-b8f9-f8d04995dfde.png)

However, it can be considered as inefficient thing to add the package into project for modifying one line code.

I am curious about your opinion for this issue.

It is also related to the pr #4340.

**Comment by glenn-jocher** [comment]
@developer0hye thanks for the idea! In general we work hard to minimize the number of dependencies in YOLOv5, as each additional package brings maintenance and possible version conflict issues, so what's in requirements.txt is usually there because it provides excellent value that we can't easily replicate ourselves. For reshaping tensors numpy and torch already provide good out of the box functionality.

**Comment by developer0hye** [comment]
@glenn-jocher 
Thanks for your review! I agree with you!
