### ISSUE TITLE
Training and test image size issues

### ISSUE THREAD

**Issue by zcswdt** [ultralytics/yolov5#4500]
Hello, the picture size is the default when I train, which is 640*640 in your code. I also set the picture to this size when I tested it, but I used 50 pictures to test and found that when the picture is set to At 960 or even 1280, 3-6 more pictures can be recalled, but when I set the picture size to 224, 26 more pictures can be recalled. Why is the detection effect better when the picture size is reduced? Please solve my doubts, thank you.

**Comment by iceisfun** [comment]
Your data set size is too small for normal results

https://docs.ultralytics.com/guides/model-training-tips/

**Comment by pderrenger** [comment]
@iceisfun the image size can affect detection performance due to how features are extracted at different scales. Smaller sizes might enhance certain features, improving recall. Experiment with various sizes to find the best balance for your dataset. For more tips, check out [our guide](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/).
