### ISSUE TITLE
train.py with --resume flag throws: AttributeError: 'NoneType' object has no attribute 'get' 

### ISSUE THREAD

**Issue by callmeFilip** [ultralytics/yolov5#4519]
## 🐛 Bug

I am trying to use resume my training and the following exception occurs:

## To Reproduce (REQUIRED)

Input to console:

```
python train.py --batch 1 --epochs 3 --data coco128.yaml
```
Then after the first epoch ends completely I abandon with ctrl-c

```
python train.py --resume
```

Output:

```
Traceback (most recent call last):
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\train.py", line 700, in <module>
    main(opt)
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\train.py", line 585, in main
    train(opt.hyp, opt, device)
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\train.py", line 84, in train
    loggers = Loggers(save_dir, weights, opt, hyp,
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\utils\loggers\__init__.py", line 58, in __init__
    self.wandb = WandbLogger(self.opt, run_id)
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 170, in __init__
    self.setup_training(opt)
  File "C:\Users\Usr\Desktop\YOLO\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 226, in setup_training
    self.train_artifact_path, self.train_artifact = self.download_dataset_artifact(data_dict.get('train'),
AttributeError: 'NoneType' object has no attribute 'get'
```

## Environment

- OS: Windows 10
- GPU: 1070Ti

## Additional context

I tracked the problem to wandb_utils.py, row 168 and I changed the if statement a bit. That solved the problem, but I am not sure that it is an adequate solution.

**Comment by glenn-jocher** [comment]
@callmeFilip I'm not able to reproduce your issue. 

Break training after 1 epoch completes:
<img width="1406" alt="Screen Shot 2021-08-23 at 6 37 29 PM" src="https://user-images.githubusercontent.com/26833433/130484593-bdb3952c-e094-42b0-ace1-231c2d297b90.png">

Resume correctly with no problems:
<img width="1406" alt="Screen Shot 2021-08-23 at 6 37 36 PM" src="https://user-images.githubusercontent.com/26833433/130484615-7002e082-a4fc-4e7b-844d-facf7df19876.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by callmeFilip** [comment]
I guess I was running a one or two-month-old version of the code and now it is fixed. Thanks for the fast reply!
