### ISSUE TITLE
Detect specific person from a lot of persons

### ISSUE THREAD

**Issue by ysfmani** [ultralytics/yolov5#4522]
Hello , please i want to detect and track only 2 persons from a lot of persons , for exemple i want to track and detect 2 tennis players but python detect.py detect all the persons in the video .. thank you
![Inkedimage_LI](https://user-images.githubusercontent.com/60297855/130537900-31626d9f-8eb4-43c8-9478-932b8f69e9ed.jpg)

**Comment by shreyasvedpathak** [comment]
The first thing that comes to my mind is, instead of using the given (detect.py) script, you can use the Torch Hub method of loading model and gain full control over the detection pipeline. This you can find in the tutorials mentioned in the README.md at [Inference using a loaded model from Torch Hub](https://github.com/ultralytics/yolov5#quick-start-examples) or check this https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading. Then you can restrict by only drawing the boxes in that specified area. Like, if xmin and ymin are less than some threshold don't draw or something like that.

The second method, I can think of is, read the video footage as it is, but while passing the image for detection, pass the cropped area (your Region of Interest) only using NumPy array slicing [[1]](https://www.analyticsvidhya.com/blog/2021/05/image-processing-using-numpy-with-practical-implementation-and-code/#h2_11) [[2]](https://www.geeksforgeeks.org/how-to-crop-an-image-using-the-numpy-module/). As the image is a NumPy array, any change in the sliced array (which is the cropped video frame) which is bounding boxes that we drew, will be reflected in the original array as well (that is the original full video frame which is uncropped and can be directly showed as output). 

References
[1]"Image Processing Using Numpy | Numpy For Image Processing", Analytics Vidhya, 2021. [Online]. Available: https://www.analyticsvidhya.com/blog/2021/05/image-processing-using-numpy-with-practical-implementation-and-code/#h2_11. [Accessed: 24- Aug- 2021].

[2]"How to Crop an Image using the Numpy Module? - GeeksforGeeks", GeeksforGeeks, 2021. [Online]. Available: https://www.geeksforgeeks.org/how-to-crop-an-image-using-the-numpy-module/. [Accessed: 24- Aug- 2021].

**Comment by ysfmani** [comment]
Thank You @shreyasvedpathak i got an idea , maybe I can create and train custom dataset of the player from the video .. what do you think ? 
PS : my project is a real-time tennis players detecting and tracking using yolo

**Comment by glenn-jocher** [comment]
@shreyasvedpathak good ideas!

**Comment by ysfmani** [comment]
@shreyasvedpathak can you help me more please what should i change or the part of code to add ... I am stuck

**Comment by shreyasvedpathak** [comment]
@ysfmani yeah, happy to help.

**Comment by ysfmani** [comment]
thank you very much , do you prefer any way to contact you ?

**Comment by shreyasvedpathak** [comment]
Discord: fakeperalta 
Skype: https://join.skype.com/invite/wLplrWCosQg3

**Comment by zaghdoud2019** [comment]
please what can i do for detecting a specific text in image like i should detect text localisation for traffic sign in road only, not drug store or pub..Any idea please
