### ISSUE TITLE
auto anchor unable to fit anchors: array must nog contain infs or NaNs

### ISSUE THREAD

**Issue by VincentDecospan** [ultralytics/yolov5#4528]
## ❔Question
Hello, 

I have a question about the k-means autoanchor. Yesterday I tried training on a custom dataset and noticed the autoanchor returned an error (see below). Does anybody have any idea as to why this error happens?

I used following command to start training: 

python train.py --img 1280 --rect --batch 16 --epochs 200 --data dataset_crowncuthalf_temp.yaml --weights yolov5s6.pt --device 1

## Additional context
![autoanchor error](https://user-images.githubusercontent.com/54405386/130579294-abe6f7ab-3b63-4905-bc9b-2e4b518fc44a.PNG)

Thank you

**Comment by glenn-jocher** [comment]
@VincentDecospan 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by realElMartino** [comment]
I have the same issue - just using the current code from the repo and running training with --eval on a custom dataset:

```
autoanchor: Analyzing anchors... anchors/target = 0.00, Best Possible Recall (BPR) = 0.0000. Attempting to improve anchors, please wait...
autoanchor: Running kmeans for 12 anchors on 31520 points...
E:\repos\yolov5\utils\autoanchor.py:129: RuntimeWarning: divide by zero encountered in true_divide
  k, dist = kmeans(wh / s, n, iter=30)  # points, mean distance
autoanchor: ERROR: array must not contain infs or NaNs
autoanchor: Original anchors better than new anchors. Proceeding with original anchors.
```

What could cause this?

**Comment by glenn-jocher** [comment]
@realElMartino 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Autoanchor may fail if your labels are all the same size, or if you lack sufficient labels. You can always skip autoanchor with `python train.py --noautoanchor` and supply your own manual anchors in your model.yaml instead:
https://github.com/ultralytics/yolov5/blob/a18b0c36cd4df0d3b9c2623c5dda009c5f281ac9/models/yolov5s.yaml#L7-L11


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
