### ISSUE TITLE
Val statistics with area sizes: mAP@.5 for area small, medium, large

### ISSUE THREAD

**Issue by Michelvl92** [ultralytics/yolov5#4535]
## ❔Question

How can I evaluate my custom dataset in a similar way as coco/pycocotools 
I need especially the following metrics:

Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | 
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | 
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large |

Ultimately I also want the following metrics:
Average Precision  (AP) @[ IoU=0.50 | area= small | 
Average Precision  (AP) @[ IoU=0.50 | area=medium | 
Average Precision  (AP) @[ IoU=0.50 | area= large |

**Comment by glenn-jocher** [comment]
@Michelvl92 you need your labels in pycocotools JSON format first, and then you evaluate your custom data identically to COCO, updating val.py as necessary.

**Comment by Michelvl92** [comment]
I converted my annotations to COCO annotations with: [Yolo-to-COCO-format-converter](https://github.com/Taeyoung96/Yolo-to-COCO-format-converter)

But now I get the following error: `Results do not correspond to current coco set`

**Comment by glenn-jocher** [comment]
@Michelvl92 got it. This will require a bit of customization. These lines are causing your error, they are filtering the results by results that correspond to the COCO dataset. You might try commenting them:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/val.py#L275-L276

@SkalskiP this is an interesting use-case to be aware of that we can enable with the upcoming COCO JSON dataloader: users would like to use pycocotools on their own custom datasets.

**Comment by SamSamhuns** [comment]
@Michelvl92 , did you solve your issue? I had a similar issue and wanted to get the small, medium, and large mAP metrics. I used the pycocotools eval in val.py after converting my dataset into the coco format.
But now my coco mAP values are extremely low compared to the yolov5 val.py values.

![Screenshot 2023-01-12 at 11 51 15 AM](https://user-images.githubusercontent.com/13418507/212030680-372b80c5-2422-41db-818e-76631aebbb29.png)

*Edit: Solved it. THe problem was the converted coco annotations had 1-indexed class ids while val.py generates 0 indexed class ids in the json file.

Created my own converter to help anyone in the future https://github.com/SamSamhuns/ml_data_processing/tree/master/annotation_format_conv
