### ISSUE TITLE
AP calculation in metrics.py

### ISSUE THREAD

**Issue by yusiyoh** [ultralytics/yolov5#4546]
## ❔Question
Why do not you use mrec = np.concatenate(([0.], recall, [1.])) instead of https://github.com/ultralytics/yolov5/blob/2da6444c9251f77cfd3e410369cd067245d961b5/utils/metrics.py#L94 ? It changes the mAP results. I could not get the idea behind it.

**Comment by glenn-jocher** [comment]
@yusiyoh hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by yusiyoh** [comment]
Actually, I was asking why you changed the default code for pascal voc ap calculation as in https://github.com/rbgirshick/py-faster-rcnn/blob/781a917b378dbfdedb45b6a56189a31982da1b43/lib/datasets/voc_eval.py#L49-L50 or in https://github.com/facebookresearch/detectron2/blob/11528ce083dc9ff83ee3a8f9086a1ef54d2a402f/detectron2/evaluation/pascal_voc_evaluation.py#L171-L172 and also in https://github.com/open-mmlab/mmdetection/blob/3545915bf14f2acbb5def6355873f7a773149e62/mmdet/core/evaluation/mean_ap.py#L37-L38 . Is there a specific reason for the change that I mentioned?

**Comment by glenn-jocher** [comment]
@yusiyoh thanks for the links! Yes your 3 (reputable) sources are certainly in alignment on the P and R arrays. Given this I think we should align with your examples. The main reason for the change was that after we started producing P-R curves by default I noticed that this last point connects the curves to the bottom right corner of the plot in all cases, which results in some odd looking curves on occasion, so the current practices terminates the curve shortly after the last data point on the x axis rather than extending it to the x axis maximum.
