### ISSUE TITLE
CUDA is out of memory runtime error 

### ISSUE THREAD

**Issue by sonyta29** [ultralytics/yolov5#4562]
## ❔Question
I'm trying to evaluate the performance of yolov5s trained on costum dataset using val.py but i'm getting this error : CUDA out of memory ( when evaluating the yolov5s trained on the coco dataset i'm not getting this error) 
I tried this solution https://stackoverflow.com/questions/59129812/how-to-avoid-cuda-out-of-memory-in-pytorch but it didn't work 

I'll be grateful for anyone who can help or suggests a working solution for this issue

**Comment by glenn-jocher** [comment]
@sonyta29 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">


If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by sonyta29** [comment]
@glenn-jocher Thank you for replying and explaining this issue... I already trained the yolov5s on Google Colab and then i have just downloaded the trained weights... by running the val.py with -- weights (my_custom_weights).pt make this problem.

I'm going to follow the reducing memory usage steps that you've mentioned. Thank you !

**Comment by twn29004** [comment]
hello, have you slove your problem?
