### ISSUE TITLE
Continue training yolov5 with checkpoint crowdhuman_yolov5m.pt

### ISSUE THREAD

**Issue by viethoang303** [ultralytics/yolov5#4585]
Hi everyone,
I have just built a dataset from MOT17 Challenge dataset, and its format is similar the format that for training yolov5. I tried to training yolov5 with checkpoint yolov5m.pt on google colab and it worked. But when I trained with checkpoint crowdhuman_yolov5m.pt:

!python train.py --img 640  --batch 16 --epochs 10 --data data.yaml --weights crowdhuman_yolov5m.pt --cache

 I received an error: 

"RuntimeError: The size of tensor a (21) must match the size of tensor b (18) at non-singleton dimension 0"

Anyone can help me to fix this error. Thank you

**Comment by glenn-jocher** [comment]
@viethoang303 👋 Hello! Thanks for asking about **resuming training**. YOLOv5 🚀 Learning Rate (LR) [schedulers](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/train.py#L109-L142) follow predefined LR curves for the fixed number of `--epochs` defined at training start (`default=300`), and are designed to fall to a minimum LR on the final epoch for best training results. For this reason you can not modify the number of epochs once training has started.

<img width="850" alt="LR Curves" src="https://user-images.githubusercontent.com/26833433/119332195-8e113a80-bc88-11eb-8eb7-7494ff1d5c01.png">

If your training was **interrupted** for any reason you may continue where you left off using the `--resume` argument. If your training fully completed, you can start a **new** training from any model using the `--weights` argument. Examples:

## Resume Single-GPU

You may not change settings when resuming, and **no additional arguments** other than `--resume` should be passed, with an optional path to the checkpoint you'd like to resume from. If no checkpoint is passed the most recently updated `last.pt` in your `yolov5/` directory is automatically found and used:
```bash
python train.py --resume  # automatically find latest checkpoint (searches yolov5/ directory)
python train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Resume Multi-GPU

[Multi-GPU DDP trainings](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) must be resumed with the same GPUs and DDP command, i.e. assuming 8 GPUs:
```bash
python -m torch.distributed.run --nproc_per_node 8 train.py --resume  # resume latest checkpoint
python -m torch.distributed.run --nproc_per_node 8 train.py --resume path/to/last.pt  # specify resume checkpoint
```

## Start from Pretrained

If you would like to **start training** from a fully trained model, use the `--weights` argument, not the `--resume` argument:
```bash
python train.py --weights path/to/best.pt  # start from pretrained model
```

Good luck and let us know if you have any other questions!

**Comment by HeChengHui** [comment]
@glenn-jocher 
I also encountered the same problem when trying to train using `crowdhuman_yolov5m.pt` using the visdrone dataset on windows10.
cmd:
`python train.py --data VisDrone.yaml --weights crowdhuman_yolov5m.pt --batch-size -1`
error msg:
```
module 'signal' has no attribute 'SIGALRM'

AutoAnchor: 3.29 anchors/target, 0.998 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs\train\exp3
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/540 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 627, in <module>
    main(opt)
  File "train.py", line 524, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 332, in train
    scaler.step(optimizer)  # optimizer.step
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\optim\sgd.py", line 136, in step
    F.sgd(params_with_grad,
  File "D:\STUDIES\Anaconda\envs\YoloV5\lib\site-packages\torch\optim\_functional.py", line 173, in sgd
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (21) must match the size of tensor b (45) at non-singleton dimension 0
```

**Comment by glenn-jocher** [comment]
@HeChengHui 3rd party weights are your responsibility. VisDrone trains correctly from official weights (our responsibility):

<img width="1451" alt="Screen Shot 2021-12-30 at 1 33 21 PM" src="https://user-images.githubusercontent.com/26833433/147789401-e901c0ab-0219-46ee-b90c-ef4167471912.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by HeChengHui** [comment]
So the crowdhuman model might contain some error?

**Comment by youonlytrackonce** [comment]
> So the crowdhuman model might contain some error?

Hello,

did you find any solution?
