### ISSUE TITLE
What is the difference between yolov5 v3.1 and v5

### ISSUE THREAD

**Issue by besmaguesmi** [ultralytics/yolov5#4607]
## Additional context
Hello

Does anyone here can explain to me the difference between the yolov5 version 3.1 and the latest version in terms of architecture/ results, I checked the architecture with Netron and I found that there's a difference in the output format.
Here's the output of yolov5 version 3.1:
![image](https://user-images.githubusercontent.com/36562278/131346733-66b82df7-9cf7-47ac-9a0d-73636d2dd0fb.png)

**Comment by glenn-jocher** [comment]
@besmaGuesmi see release notes and changelog:
https://github.com/ultralytics/yolov5/releases/tag/v5.0

## Changelog

Changes between **previous release and this release**: https://github.com/ultralytics/yolov5/compare/v4.0...v5.0
Changes **since this release**: https://github.com/ultralytics/yolov5/compare/v5.0...HEAD
