### ISSUE TITLE
Reduce dependencies for model only usage

### ISSUE THREAD

**Issue by maxstrobel** [ultralytics/yolov5#4664]
## 🚀 Feature

If I just want to use your models for inference, I don't need all additional features like:

- visualizations
- profiling
- type conversions to pandas
- ...

However, those useful features are (partially) built-in to the model architecture. Therefore I need to install additional libraries like

- matplotlib
- seaborn
- pandas

even if I don't use them at all. Also downloading the additional font (Arial.ttf) can be a problem in restricted environments.

I think it would be nice to have an operable core model that runs with only a subset of required dependencies.

## Motivation

Less dependencies & simpler integration in other projects.

## Pitch

I'd suggest to disentangle the core model (inference only) and the additional features (plotting, profiling, ...).

## Alternatives

Leave it as it is and require all dependencies

**Comment by glenn-jocher** [comment]
@maxstrobel hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!

We already use a semi-requirements method of auto-installing dependencies on demand depending on purpose, i.e. when using YOLOv5 with PyTorch Hub we omit all unnecessary packages we can from requirements checks:
https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/hubconf.py#L37

But we are always open to improvements! The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by mohammad69h94** [comment]
> check_requirements



> @maxstrobel hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!
> 
> We already use a semi-requirements method of auto-installing dependencies on demand depending on purpose, i.e. when using YOLOv5 with PyTorch Hub we omit all unnecessary packages we can from requirements checks:
> 
> https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/hubconf.py#L37
> 
> But we are always open to improvements! The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.
> 
> Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

How to disable arial.ttf font downloading? 
Because i get error: urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> when downloading font.

**Comment by glenn-jocher** [comment]
@mohammad69h94 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀 and Arial.ttf. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by maxstrobel** [comment]
> > check_requirements
> 
> > @maxstrobel hi, thank you for your feature suggestion on how to improve YOLOv5 🚀!
> > We already use a semi-requirements method of auto-installing dependencies on demand depending on purpose, i.e. when using YOLOv5 with PyTorch Hub we omit all unnecessary packages we can from requirements checks:
> > https://github.com/ultralytics/yolov5/blob/fad57c29cd27c0fcbc0038b7b7312b9b6ef922a8/hubconf.py#L37
> > 
> > But we are always open to improvements! The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.
> > Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
> 
> How to disable arial.ttf font downloading? Because i get error: urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> when downloading font.

Sorry for the late replay, you can download the file manually & place it in `~/.config/Ultralytics`
