### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by lifanhanhan** [ultralytics/yolov5#4669]
## Additional context
The random seed is set, and the two results of the same code are inconsistent. What is the reason
![QQ图片](https://user-images.githubusercontent.com/62056271/132078734-5c7704fc-8ab5-4827-9f65-d10753299c1a.png)

**Comment by glenn-jocher** [comment]
@lifanhanhan 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by lifanhanhan** [comment]
For example, I use mixed precision to run 200 epochs, and run the same code in the same environment for the second time. Normally, random seeds are set. Each epoch of the two results will ensure the same or approximation, but in fact, each epoch of the two results fluctuates greatly. Which module is affecting the random seeds? Thank you for your reply.

**Comment by glenn-jocher** [comment]
@lifanhanhan see https://pytorch.org/docs/stable/notes/randomness.html
