### ISSUE TITLE
multi-scale argument and scale parameter

### ISSUE THREAD

**Issue by tino926** [ultralytics/yolov5#4682]
## ❔Question
The argument "multi-scale" for train.py seems a redundant setting of the "scale" setting in hyperparameter setting file?  
If I set "multi-scale" as "true" and set "scale" as 0.5,  
it's almost the same to set "multi-scale" as "false" and set "scale" to 0.25.  
Is that correct?  
  
Another question related to size: is there a way to set the training process such that the model only detects object larger than a predefined size?

**Comment by glenn-jocher** [comment]
@tino926 multi-scale varies image size. scale hyperparameter applies scale jitter to the image contents, size remains unchanged.

**Comment by glenn-jocher** [comment]
@tino926 you can update detection size candidate criteria in the NMS function:
https://github.com/ultralytics/yolov5/blob/548745181a4d30db3d4fe81a952ca6dbb54c7578/utils/general.py#L547-L554

**Comment by SyGoing** [comment]
When I set multi-scale=True and train the model with multi-gpus ,there is some trouble .  the log is like this :
Epoch   gpu_mem        lr      loss       box       obj       cls  img_size

      1/20     2.71G  0.001667     46.66     30.48     3.936     12.25       224:   0%|          | 0/15 [00:00<?, ?it/s]
      1/20     2.71G  0.001667     46.66     30.48     3.936     12.25       224:   7%|▋         | 1/15 [00:02<00:30,  2.17s/it]Reducer buckets have been rebuilt in this iteration.
Reducer buckets have been rebuilt in this iteration.

      1/20     2.74G  0.001666     43.77     29.67     2.172     11.93       448:   7%|▋         | 1/15 [00:03<00:30,  2.17s/it]
      1/20     2.74G  0.001666     43.77     29.67     2.172     11.93       448:  13%|█▎        | 2/15 [00:03<00:23,  1.79s/it]
      1/20     2.75G  0.001665      47.8     31.65     3.917     12.24       192:  13%|█▎        | 2/15 [00:03<00:23,  1.79s/it]
      1/20     2.75G  0.001665      47.8     31.65     3.917     12.24       192:  20%|██        | 3/15 [00:03<00:17,  1.42s/it]
      1/20     3.99G  0.001665     45.15     29.89     3.174     12.09       288:  20%|██        | 3/15 [00:04<00:17,  1.42s/it]
      1/20     3.99G  0.001665     45.15     29.89     3.174     12.09       288:  27%|██▋       | 4/15 [00:04<00:12,  1.17s/it]
      1/20     4.01G  0.001664     47.62     31.08     4.204     12.33       192:  27%|██▋       | 4/15 [00:04<00:12,  1.17s/it]
      1/20     4.01G  0.001664     47.62     31.08     4.204     12.33       192:  33%|███▎      | 5/15 [00:04<00:09,  1.02it/s]
      1/20      7.1G  0.001663     43.68     29.43     2.498     11.75       384:  33%|███▎      | 5/15 [00:05<00:09,  1.02it/s]
      1/20      7.1G  0.001663     43.68     29.43     2.498     11.75       384:  40%|████      | 6/15 [00:05<00:08,  1.07it/s]
      1/20      7.1G  0.001663      43.4      29.1     2.445     11.86       384:  40%|████      | 6/15 [00:06<00:08,  1.07it/s]
      1/20      7.1G  0.001663      43.4      29.1     2.445     11.86       384:  47%|████▋     | 7/15 [00:06<00:06,  1.19it/s]
      1/20      7.1G  0.001662     43.78      29.3     2.623     11.85       384:  47%|████▋     | 7/15 [00:07<00:06,  1.19it/s]
      1/20      7.1G  0.001662     43.78      29.3     2.623     11.85       384:  53%|█████▎    | 8/15 [00:07<00:05,  1.21it/s]Traceback (most recent call last):
  File "train.py", line 657, in <module>
    main(opt)
  File "train.py", line 556, in main
    train(opt.hyp, opt, device)
  File "train.py", line 359, in train
    pred = model(imgs)  # forward
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/rock_yolov5/models/yolo.py", line 129, in forward
    return self.forward_once(x, profile, visualize, tocaffe=tocaffe)  # single-scale inference, train
  File "/workspace/rock_yolov5/models/yolo.py", line 162, in forward_once
    x = m(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/rock_yolov5/models/common.py", line 142, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), dim=1))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/rock_yolov5/models/common.py", line 48, in forward
    x = self.bn(self.conv(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by glenn-jocher** [comment]
@SyGoing 👋 hi, thanks for letting us know about a possible problem with YOLOv5 🚀. For most use cases I'm aware of there's no need to use the `--multi-scale` argument, as YOLOv5 already uses automatic 0.5 scale jitter (controlled by the `scale` hyperparameter in your hyp.yaml).

If you believe you have a reproducible bug, we've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
