### ISSUE TITLE
Error       ^C

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#4685]
the training is running < and then >  **^C** and stopped.
i am running on colab.

`python train.py --img 280 --batch 130 --e=pochs 100 --data /content/data.yaml --weights '' --cfg yolov5l.yaml --cache`
```

     Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/99     14.7G   0.07821   0.02172   0.04832        62       288: 100% 420/420 [08:24<00:00,  1.20s/it]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 91/91 [02:32<00:00,  1.67s/it]
^C
```

**Comment by VYRION-Ai** [comment]
I don not press any thing .

**Comment by wudashuo** [comment]
`Ctrl + C` means kill the current process in Linux. That's a basic command in Linux.

**Comment by VYRION-Ai** [comment]
Sir , as i said, i don't press any thing , 
I know what Ctrl+c means

**Comment by glenn-jocher** [comment]
CTRL+C is a keyboard shortcut to kill a process. You pressed these keys and your process was killed as expected. Closing this issue.

**Comment by VYRION-Ai** [comment]
Sorry sir , i am sure i don't press any thing,i try it twice,  and thanks you for closing the bug, and don't answering me

**Comment by glenn-jocher** [comment]
@totoadel 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by VYRION-Ai** [comment]
Sir , if i use pretreating bet , the code running , but if i do training using 

`python train.py --img 280 --batch 130 --e=pochs 100 --data /content/data.yaml --weights '' --cfg yolov5l.yaml --cache


The bug happened, you can try
