### ISSUE TITLE
AttributeError: 'WandbLogger' object has no attribute 'bbox_interval'

### ISSUE THREAD

**Issue by GalSang17** [ultralytics/yolov5#4700]
Hi, when I set wandb=None and go to training, an exception will be thrown, just like the title shows

**Comment by glenn-jocher** [comment]
@GalSang17 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Seperendity** [comment]
> Hi, when I set wandb=None and go to training, an exception will be thrown, just like the title shows

How did you solve this problem？I meet the same problem.

**Comment by XinghuaJi** [comment]
> 
> 
> > Hi, when I set wandb=None and go to training, an exception will be thrown, just like the title shows
> 
> How did you solve this problem？I meet the same problem.

oh !   I meet too  the same problem.

**Comment by Seperendity** [comment]
> > > Hi, when I set wandb=None and go to training, an exception will be thrown, just like the title shows
> > 
> > 
> > How did you solve this problem？I meet the same problem.
> 
> oh ! I meet too the same problem.

who can help us solve this.

**Comment by glenn-jocher** [comment]
@Seperendity @XinghuaJi @GalSang17 thanks for reporting this problem! Can you please provide steps to help us reproduce this?

@AyushExel can you help these users out with their W&B issue?

**Comment by AyushExel** [comment]
I'll try to reproduce this and push a fix. But exact steps or the traceback would be helpful

**Comment by AyushExel** [comment]
@Seperendity @XinghuaJi @GalSang17 can you guys provide the exact steps to reproduce or share the traceback?

**Comment by XinghuaJi** [comment]
@AyushExel  The steps to reproduce are as follows ：
(mypytorch) xxx@xxx-System-Product-Name:~/yolov5_org$ python train.py --data data/voc_ball.yaml --cfg models/yolov5s_ball.yaml --weights weights/yolov5s.pt --batch-size 32 --epochs 50 --workers 16 --name ball_yolov5s
Downloading https://ultralytics.com/assets/Arial.ttf to /tmp/Ultralytics/Arial.ttf...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 755k/755k [00:00<00:00, 1.67MB/s]
train: weights=weights/yolov5s.pt, cfg=models/yolov5s_ball.yaml, data=data/voc_ball.yaml, hyp=data/hyps/hyp.scratch.yaml, epochs=50, batch_size=32, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=16, project=runs/train, entity=None, name=ball_yolov5s, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0, patience=100
github: Command 'git fetch && git config --get remote.origin.url' timed out after 5 seconds
YOLOv5 🚀 v5.0-420-g7af1b4c torch 1.8.0 CUDA:0 (GeForce RTX 3070, 7981.0MB)

hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  3    156928  models.common.C3                        [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7063542 parameters, 7063542 gradients, 16.4 GFLOPs

Transferred 354/362 items from weights/yolov5s.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 59 weight, 62 weight (no decay), 62 bias
train: Scanning '../yolov5_org/VOCdevkit/labels/train' images and labels...1048 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 1048/1048 [00:00<00:00, 17706.90it/s
train: New cache created: ../yolov5_org/VOCdevkit/labels/train.cache
val: Scanning '../yolov5_org/VOCdevkit/labels/val' images and labels...240 found, 0 missing, 0 empty, 0 corrupted: 100%|████████| 240/240 [00:00<00:00, 1331.46it/s]
val: New cache created: ../yolov5_org/VOCdevkit/labels/val.cache
Plotting labels... 

autoanchor: Analyzing anchors... anchors/target = 5.46, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 val
Using 16 dataloader workers
Logging results to runs/train/ball_yolov5s
Starting training for 50 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/49     2.26G    0.1256   0.01743         0        33       640: 100%|███████████████████████████████████████████████████████| 33/33 [00:15<00:00,  2.16it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|                                                 | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 611, in <module>
    main(opt)
  File "train.py", line 509, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 350, in train
    results, maps, _ = val.run(data_dict,
  File "/home/xhji/anaconda3/envs/mypytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xhji/yolov5_org/val.py", line 221, in run
    callbacks.run('on_val_image_end', pred, predn, path, names, img[si])
  File "/home/xhji/yolov5_org/utils/callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "/home/xhji/yolov5_org/utils/loggers/__init__.py", line 95, in on_val_image_end
    self.wandb.val_one_image(pred, predn, path, names, im)
  File "/home/xhji/yolov5_org/utils/loggers/wandb/wandb_utils.py", line 454, in val_one_image
    if self.current_epoch % self.bbox_interval == 0:
AttributeError: 'WandbLogger' object has no attribute 'bbox_interval'

**Comment by AyushExel** [comment]
@XinghuaJi It seems you're not on the latest version of the repo. Can you run `git pull` and see if the problem exists?

**Comment by XinghuaJi** [comment]
@AyushExel 
I will try it, thank you !

**Comment by XinghuaJi** [comment]
@AyushExel 
I have tried run ”git pull“, but the problem is still not resolved

**Comment by XinghuaJi** [comment]
@AyushExel 
I think it should be the problem of ”wandb“，thank you !

**Comment by Seperendity** [comment]
So,how can we fix it,thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月21日(星期二) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] AttributeError: 'WandbLogger' object has no attribute 'bbox_interval' (#4700)





 
@AyushExel
 I think it should be the problem of ”wandb“，thank you !
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AyushExel** [comment]
@XinghuaJi what log are you getting when you run "git pull" ? I think there are some conflicts because based on your error log, you're files are not up to date with master branch. As an alternate (but dangerous) fix, try to replace the contents of your wandb_utils.py file with the one in the current master branch

**Comment by XinghuaJi** [comment]
@AyushExel
 I disabled the wandb function in "wandb_utils.py" due to the network link.

**Comment by AyushExel** [comment]
Try replacing your wandb_utils.py file with the wandb_utils.py found in the master branch of yolov5 repo

**Comment by AyushExel** [comment]
@XinghuaJi were you able to fix this?

**Comment by SSHtoyourheart** [comment]
i have meet same iissue but i have not use wandb , why?

**Comment by AyushExel** [comment]
@SSHtoyourheart are you using the latest version of YOLOv5? Please paste the entire error trace. Try cloning the repo again and let me know if you still see this error

**Comment by SSHtoyourheart** [comment]
@AyushExel I have registered the wandb and success trained ,thank you .
