### ISSUE TITLE
AssertionError: CUDA unavailable, invalid device 0 requested

### ISSUE THREAD

**Issue by yancccc** [ultralytics/yolov5#474]
~/yolov5-master$ python detect.py --source ./inference/images/ --weights yolov5s.pt --conf 0.4 --device 0 
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='0', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', update=False, view_img=False, weights=['yolov5s.pt'])
False
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 16, in detect
    device = torch_utils.select_device(opt.device)
  File "/home/ycc/yolov5-master/utils/torch_utils.py", line 33, in select_device
    assert torch.cuda.is_available(), 'CUDA unavailable, invalid device %s requested' % device  # check availablity
AssertionError: CUDA unavailable, invalid device 0 requested

**Comment by NanoCode012** [comment]
Check that you have CUDA installed
“nvcc -V”

**Comment by yancccc** [comment]
> Check that you have CUDA installed
> “nvcc -V”
The environment is configured, and yolov4 can work normally

**Comment by yancccc** [comment]
ycc@ycc:~/yolov5-master$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by glenn-jocher** [comment]
@yancccc it appears you have environment problems. In order to run YOLOv5 correctly your environment must meet  the minimum version requirements for the dependencies described in https://github.com/ultralytics/yolov5#requirements. You can either update your local environment to bring it into compliance or you can use one of our verified environment options below.

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by dddj969** [comment]
@yancccc do you solve the problem ? i meet the same problem

**Comment by XiaoXiLe2023** [comment]
I meet the same problem. I used:
print(torch.cuda.device_count())
print(torch.version.cuda)
print(torch.__version__) 
print(torch.cuda.is_available())
to check.

got
0
10.2
1.5.1
False

**Comment by XiaoXiLe2023** [comment]
> ycc@ycc:~/yolov5-master$ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130

maybe you can try
pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by NanoCode012** [comment]
Hello, I think I recall this problem I used to have. I believe that I had to install torch via conda. https://pytorch.org/ Choose your cuda version. I'm not sure why the pip version doesn't work for me.

Also, make sure to remove the previous torch that was installed first.

**Comment by rohanbanerjee** [comment]
@Myhuang1996 's solution solved the issue in my case!

**Comment by DeepAndy** [comment]
try the latest pytorch + correct version of cuda:
`pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by zwcao12** [comment]
Pytorch1.6 supports CUDA 9.2, 10.1 and 10.2. I update the version of CUDA,yolov5 can work.

**Comment by nTnZone** [comment]
> ~/yolov5-master$ python detect.py --source ./inference/images/ --weights yolov5s.pt --conf 0.4 --device 0
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='0', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='./inference/images/', update=False, view_img=False, weights=['yolov5s.pt'])
> False
> Traceback (most recent call last):
> File "detect.py", line 161, in
> detect()
> File "detect.py", line 16, in detect
> device = torch_utils.select_device(opt.device)
> File "/home/ycc/yolov5-master/utils/torch_utils.py", line 33, in select_device
> assert torch.cuda.is_available(), 'CUDA unavailable, invalid device %s requested' % device # check availablity
> AssertionError: CUDA unavailable, invalid device 0 requested

same problem, only happen in yolo5

**Comment by AxleCode** [comment]
> > ycc@ycc:~/yolov5-master$ nvcc -V
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2018 NVIDIA Corporation
> > Built on Sat_Aug_25_21:08:01_CDT_2018
> > Cuda compilation tools, release 10.0, V10.0.130
> 
> maybe you can try pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

PS D:\Kuliah\Yolov5\yolov5-master> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

i used cuda 11.6 what version torch and torchvision must im install?

**Comment by shubhambagwari** [comment]
@DeepAndy 


> try the latest pytorch + correct version of cuda: `pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

Throwing this error now.

Error:
```
requirements: torch>=1.7.0 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install torch>=1.7.0' skipped (offline)
requirements: torchvision>=0.8.1 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install torchvision>=0.8.1' skipped (offline)
YOLOv5  2022-7-20 Python-3.7.6 torch-1.6.0+cu101 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6144MiB)
```

@Myhuang1996 facing the same issue. I tried your solution as well.

**Comment by glenn-jocher** [comment]
@shubhambagwari you are not meeting requirements and your machine is not online for auto-update to work
