### ISSUE TITLE
export to onnx error

### ISSUE THREAD

**Issue by guyiyifeurach** [ultralytics/yolov5#4778]
I run the question when I try to exchange pt model to onnx model use the script of export.py. 
And the error is "ONNX: export failure: expected scalar type long but found float", 
error logs shown below:
![image](https://user-images.githubusercontent.com/32059046/133101976-f8214dc5-790a-4e39-8fba-c47159a22c11.png)

And the model trained by me is used by cfg yolov5s-transformer.cfg, so its yolo.py has changed.
How can I fix the problem? @glenn-jocher 
Thank you very much!

**Comment by glenn-jocher** [comment]
@guyiyifeurach 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by guyiyifeurach** [comment]
Well, in order to get associated links between pixels, I used transformer module to train model like:
``python train.py --weights yolov5s.pt --cfg models/hub/yolov5s-transformer.yaml --epochs 120  --multi-scale --freeze 10 --evolve --img-size 1280``;
after it produced the best model hyperparameters, I got the best model, here I rename it as best.pt.
As I need use the model to run in C# project, so I changed it from .pt model to .onnx model by:
``python export.py --weights address/best.pt --img-size 1280 --include 'onnx'``, but I run the mistake below:
To solve the mistake, I change export.py by fixing
``torch.onnx.export(....,
                               do_constant_folding=False,
                               ...)``,
and get best.onnx
But amazing result occurs, the inference results by best.pt and best.onnx are different, which fluctuates large. So I want to know why.
Thank you very much!

**Comment by glenn-jocher** [comment]
@guyiyifeurach that's interesting. yolov5s-transformer hasn't been export verified so it's possible there may be issues there. Have you tried any of the onnx options like --dynamic?

**Comment by glenn-jocher** [comment]
@guyiyifeurach also I'm not sure what you mean by different results, can you elaborate?

**Comment by guyiyifeurach** [comment]
I have tried input same iouv_thres and conf_thres into inference, and inference doesn't have pre_operations.Other parameters don't be inputed.



---Original---
From: "Glenn ***@***.***&gt;
Date: Tue, Sep 14, 2021 19:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/yolov5] export to onnx error (#4778)




 
@guyiyifeurach that's interesting. yolov5s-transformer hasn't been export verified so it's possible there may be issues there. Have you tried any of the onnx options like --dynamic?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guyiyifeurach** [comment]
Inference with these two models have different confidences to same images' same targets.



---Original---
From: "Glenn ***@***.***&gt;
Date: Tue, Sep 14, 2021 19:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/yolov5] export to onnx error (#4778)




 
@guyiyifeurach also I'm not sure what you mean by different results, can you elaborate?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by glenn-jocher** [comment]
@guyiyifeurach I understand there are differences, but we need quantitative comparisons here for any meaningful discussion.

**Comment by guyiyifeurach** [comment]
Output results of inference, onnx model produced less targets than pt model. For example, onnx found 7 targets, while pt found 8 targets, and the targets' confidence found by onnx are smaller than those by pt, the differences are about 8%.
And when I used ``export.py`` change file, I got the mistake of "ComputeConstantFolding" of Pytorch. To process it, I changed parameter of ``export_onnx`` function in ``export.py`` from ``do_constant_folding = not train`` to ```do_constant_folding = False``。
So I wonder, is it possible the reason of inferencing difference?
Thank you for your attention.

**Comment by glenn-jocher** [comment]
@guyiyifeurach 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
