### ISSUE TITLE
反向传播的相关问题

### ISSUE THREAD

**Issue by isJunCheng** [ultralytics/yolov5#4784]
## Additional context
1、在训练过程中，遇到了’RuntimeError: Function 'BroadcastBackward' returned nan values in its 0th output.‘这个问题，然后调试产生了相关疑问
2、在调试过程中，执行至scaler.scale(loss).backward()时，会显示‘bound method Tensor.backward of tensor([479351.37500]....‘，请问这个tensor代表什么？

**Comment by isJunCheng** [comment]
1, during the training process, we encountered the problem of "RuntimeError: Function'BroadcastBackward'returned Nan values in its 0th output.", and then debugging related questions.
2. During debugging, when you execute scaler.scale (loss).backward(), it will display 'bound method tensor. Backward of tensor ([479351.37500]...'. What does this tensor stand for?

**Comment by glenn-jocher** [comment]
@isJunCheng training instabilities may be caused by problems with your dataset or hyperparameters. I would recommend you first train a common dataset like COCO128 and then proceed to your custom dataset to isolate the source of errors. See Train Custom Data tutorial to get started. backward() return values are loss gradients.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by isJunCheng** [comment]
After debugging, I found that:
1. It seems that the scale factor of gradscaler is too large, resulting in Nan or Inf values when the amplified loss propagates backward. After I reduce the scale factor, the problem of explosion is solved;
2. The value returned by scaler. scale (loss). backward() is the value after gradscaler enlarges loss in scale.
Is that right?

**Comment by glenn-jocher** [comment]
@isJunCheng the gradscaler is part of the pytorch AMP package. You can remove it if you'd rather not use it and use the more traditional loss.backward()

**Comment by isJunCheng** [comment]
@glenn-jocher thank you very much for your reply!
