### ISSUE TITLE
How to export .ptl model?

### ISSUE THREAD

**Issue by CensorKo** [ultralytics/yolov5#4806]
## ❔Question
export.py can only export to pytorch .pt format models. We want to deploy it on android, and now org.pytorch:pytorch_android_lite:1.9.0 is available. refer to https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection  so how to generate .ptl format models? I tried using ts._save_for_lite_interpreter(f) instead of ts.save(f). It works, but needs 1 second more. I also convert to tensorflow lite model with --int8, unfortunately crashed. and now i am confused for mobile apps.

**Comment by glenn-jocher** [comment]
@CensorKao 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by CensorKo** [comment]
> * modifications

I can't export to pytorch lite model file.

**Comment by kalkun** [comment]
In the README of the repository you link to they state that: 
> The Python script export.py in the models folder of the YOLOv5 repo is used to generate a TorchScript-formatted YOLOv5 model named yolov5s.torchscript.pt for mobile apps.

Followed by examples/instructions, did that not work for you?

**Comment by CensorKo** [comment]
> In the README of the repository you link to they state that:
> 
> > The Python script export.py in the models folder of the YOLOv5 repo is used to generate a TorchScript-formatted YOLOv5 model named yolov5s.torchscript.pt for mobile apps.
> 
> Followed by examples/instructions, did that not work for you?

Not working for me.  Should using ts._save_for_lite_interpreter() instead of ts.save().

Refer to https://pytorch.org/tutorials/prototype/lite_interpreter.html
