### ISSUE TITLE
None

### ISSUE THREAD

**Issue by Jack-Wang-Anker** [ultralytics/yolov5#4821]
## ❔Question
I have tried to modify the Yolo detect out layers to 2, and, it raised the following issue:
`Traceback (most recent call last):
  File "yolov5s_4bit.py", line 414, in <module>
    train(hyp, opt, opt.cfg, device, tb_writer)
  File "yolov5s_4bit.py", line 265, in train
    loss, loss_items = compute_loss(pred, targets.to(device), model)
  File "/home/***/utils/utils.py", line 300, in compute_loss
    tcls, tbox, indices, anchors = build_targets(p, targets, model)
  File "/home/utils/utils.py", line 391, in build_targets
    r = t[:, :, 4:6] / anchors[:, None]
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0`
where:          
print(anchors[:, None].shape)  # torch.Size([3, 1, 2])
print(t[:, :, 4:6].shape)  # torch.Size([2, m, 2])  # m is the number of targets in batch.

## Additional context
How can i match it? I am looking forward to your reply.
thank you very much, best wishes to you.

**Comment by glenn-jocher** [comment]
@Jack-Wang-Anker 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
