### ISSUE TITLE
Label problems when train on multiple datasets

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#4844]
## ❔Question

I have a dataset comprised of:

 - My custom dataset comprised of 3 classes
 - Persons extracted from COCO

The classes in the first dataset are labeled [0, 1, 2]
The class in the second dataset is labeled [3]
 
My ./data/custom.yaml file looks like this

```
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco  # dataset root dir
train: # train images (relative to 'path') 3422 images
  - images/custom_train
  - images/person_train2017
val: # val images (relative to 'path') 748 images (WARNING: train set contains ethz_1)
  - images/custom_val
  - images/person_val2017
test: # test images (optional) 1276 images
  - images/custom_val
  - images/person_val2017

# Classes
nc: 4  # number of classes
names: [ 'my_class_1', 'my_class_2', 'my_class_3', 'person' ]  # class names
```

The person class is being labeled as '0' for some reason when it should be labeled as '3'?
Maybe I am using this functionality in the wrong way?

**Comment by glenn-jocher** [comment]
@mikel-brostrom if you combine multiple datasets you must make sure that the dataset labels are not in conflict, i.e. to train custom data in addition to coco you would label your custom data starting at class 80 onward:

```yaml
train: # train images (relative to 'path')
  - images/coco  # classes 0-79
  - images/custom  # classes 80, 81, 82, ... etc.
```

**Comment by mikel-brostrom** [comment]
I extracted all the person annotations with their corresponding images from COCO. That makes `images/person_train2017` a single class dataset

```python
train: # train images (relative to 'path')
  - images/custom_train # classes 0-2
  - images/person_train2017 # class 3
```

**Comment by mikel-brostrom** [comment]
The labels in the txts associated to `images/custom_train` are: [0, 1, 2]
The label in the txts associated to `images/person_train2017` is: [3]

**Comment by glenn-jocher** [comment]
@mikel-brostrom everything should work correctly then. If you are having issues a minimal reproducible example is what we need to examine. 

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by mikel-brostrom** [comment]
I had some old `.cache` files, that were created when my annotations were incorrect. I deleted the old `.cache` in order to create them from scratch and now everything looks like it should. The issue is that the `.cache` files creation process is not aware of changes in the original datasets.

**Comment by glenn-jocher** [comment]
@mikel-brostrom cache files are automatically recreated on any changes in the dataset. If this is not the case for you then your code is very out of date and you should update to latest.
