### ISSUE TITLE
KeyError: "yolov5x.pt is not compatible with ./models/yolov5x.yaml. Specify --weights '' or specify a --cfg compatible with yolov5x.pt."

### ISSUE THREAD

**Issue by kulkarnikeerti** [ultralytics/yolov5#4871]
I have been trying to use this pre-trained model for my custom dataset with 5 classes. I changed yaml files based on the number of classes in the dataset. But I end up with this error. 

initially I had the problem with downloading the weights but I could solve that by [60](https://github.com/ultralytics/yolov5/issues/60). But now I have this problem of not compatible. 

I am using:
Linux
Python 3.9.6
PyTorch 1.9.0

Is there already fix for this issue?

**Comment by glenn-jocher** [comment]
@kulkarnikeerti no changes are needed to the model yamls, you can train any number of classes with the default yamls (classes are inherited from your data.yaml). 

But in any case you don't need a yaml to train:
```
python train.py --data coco128.yaml --weights yolov5x.pt
```

**Comment by kulkarnikeerti** [comment]
@glenn-jocher I did try above solution and also followed [this](https://curiousily.com/posts/object-detection-on-custom-dataset-with-yolo-v5-using-pytorch-and-python/) fresh from beginning. But I end up with this similar error again. 

KeyError: "yolov5x.pt is not compatible with models/yolov5s.yaml. Specify --weights '' or specify a --cfg compatible with yolov5x.pt."

**Comment by glenn-jocher** [comment]
@kulkarnikeerti 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by kulkarnikeerti** [comment]
Thanks @glenn-jocher I was able to resolve the issue by pulling the latest commit
