### ISSUE TITLE
Label crowded images for custom training

### ISSUE THREAD

**Issue by aaganaie** [ultralytics/yolov5#4887]
## ❔Question
Hi ,
I am trying to train a custom dataset using yolov5 model . My dataset has many images where there is low/ medium size crowd .
While looking at the labelling of openimages dataset or MS coco dataset , they label few people and rest whole crowd is labelled person with a single bounding box [ multiple bounding boxes are used when crowd is segregated ].
My question is , should I label  my custom dataset in a similar way , to match my custom dataset labelling and open source datasets labelling ? 
If yes , how effective is this technique ? What is the logic behind doing this thing ? 

Or  should I label each and every person visible which will take a lot of time for labelling and features extracted from far away and blurred people may mess with my weights and in turn accuracy of model 

## Additional context
This maybe a basic object detection question so please bear with me .

**Comment by glenn-jocher** [comment]
@aaganaie the details of what you should do depend on your specific use case. In general the model will act the way you train it, so if you label every person it will detect every person, if you don't label far people it won't detect far people.

For crowd counting there may be more specialized solutions however that rely on heatmaps rather than detection. If you want to use a detection solution for crowd counting, labelling each head rather than each person may reduce occlusion/NMS issues.
