### ISSUE TITLE
self.hyp['iou_t'] for anchor selection is wrong

### ISSUE THREAD

**Issue by AIpakchoi** [ultralytics/yolov5#4910]
Hi, I use the following code for anchor selection, but it was wrong
-------------------------------------------------------------------------------

Code
-----------
 if nt:
                # Matches
                r = t[:, :, 4:6] / anchors[:, None]  # wh ratio
                #j = torch.max(r, 1. / r).max(2)[0] < self.hyp['anchor_t']  # compare
                j = wh_iou(anchors, t[:, 4:6]) > self.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))
                t = t[j]  # filter
------------------------------------------------------------------------------------
Problem
-------------
Traceback (most recent call last):
  File "train.py", line 540, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 302, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/project_YOLOv5/utils/loss.py", line 118, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/project_YOLOv5/utils/loss.py", line 199, in build_targets
    j = wh_iou(anchors, t[:, 4:6]) > self.hyp['iou_t']  # iou(3,n)=wh_iou(anchors(3,2), gwh(n,2))
  File "/home/project_YOLOv5/utils/general.py", line 425, in wh_iou
    inter = torch.min(wh1, wh2).prod(2)  # [N,M]
RuntimeError: The size of tensor a (2) must match the size of tensor b (7) at non-singleton dimension 3
Images sizes do not match. This will causes images to be display incorrectly in the UI.

**Comment by glenn-jocher** [comment]
@AIpakchoi  👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
