### ISSUE TITLE
AssertionError: '' acceptable suffix is ['.pt'] (Before running train.py)

### ISSUE THREAD

**Issue by XJTUXYC** [ultralytics/yolov5#4948]
## ❔Question
When I was editing configurations in configurations window, I wrote --weights '' in Parameters column to train a  model without pre-training. Then, PyCharm returned me an AssertionError: '' acceptable suffix is ['.pt']. But, when I changed the default value of --weights from 'yolov5s.pt' to '', train.py worked successfully. What is the reason?

**Comment by glenn-jocher** [comment]
good news 😃! Your original issue may now be fixed ✅ in master. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by beebrain** [comment]
Dear @glenn-jocher 

I have the same problem. I would like to initial weight without any transfer weight parameters. 
Follow the instruction,  They told me if I don't want to use sample weight. I can put the argument with "--weights '' ".
This is my error message.
![image](https://user-images.githubusercontent.com/10016227/135044734-afaa6ac2-a965-4cfd-afa0-ed5da4e40f17.png)

I got this message after I updated the yolo5 folder from github.

This is my command to train the coco dataset with yolov5s config.
![image](https://user-images.githubusercontent.com/10016227/135045083-0e394134-9fca-44be-8646-cbad9638dcb9.png)

**Comment by glenn-jocher** [comment]
@beebrain @XJTUXYC your code is out of date, this issue has been resolved already in master a while back.

To update your code:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@beebrain @XJTUXYC to verify I've added a `python train.py --weights ''` test to our CI testing in PR https://github.com/ultralytics/yolov5/pull/4980 and all tests are passing.

**Comment by beebrain** [comment]
@glenn-jocher  Thanks for your response. I already update my yolo5 folder and run the same command. I got the same error.

**Comment by glenn-jocher** [comment]
@beebrain 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Karol-G** [comment]
I still have this issue in the latest master branch.

```
Traceback (most recent call last):
  File "/home/k539i/Documents/projects/yolov5/train.py", line 620, in <module>
    main(opt)
  File "/home/k539i/Documents/projects/yolov5/train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/k539i/Documents/projects/yolov5/train.py", line 111, in train
    check_suffix(weights, '.pt')  # check weights
  File "/home/k539i/Documents/projects/yolov5/utils/general.py", line 301, in check_suffix
    assert Path(f).suffix.lower() in suffix, f"{msg}{f} acceptable suffix is {suffix}"
AssertionError: '' acceptable suffix is ['.pt']
```

**Comment by glenn-jocher** [comment]
@Karol-G 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Karol-G** [comment]
Created a bug issue #5094.
This one can be closed.

**Comment by glenn-jocher** [comment]
@XJTUXYC @beebrain @Karol-G good news 😃! Your original issue may now be fixed ✅ in PR #5192. This PR allows empty strings to pass through `check_suffix()` without error, which multiple windows users had reported was causing issues.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by Ashritv** [comment]
Traceback (most recent call last):
  File "D:\Techgium\Model_parameters\yolov5\detect.py", line 317, in <module>
    main(opt)
  File "D:\Techgium\Model_parameters\yolov5\detect.py", line 312, in main
    run(**vars(opt))
  File "C:\Users\Admin\miniconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Techgium\Model_parameters\yolov5\detect.py", line 120, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Techgium\Model_parameters\yolov5\models\common.py", line 425, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
                                                                                                 ^^^^^^^^^^^^^^^^^^^
  File "D:\Techgium\Model_parameters\yolov5\models\common.py", line 715, in _model_type
    check_suffix(p, sf)  # checks
    ^^^^^^^^^^^^^^^^^^^
  File "D:\Techgium\Model_parameters\yolov5\utils\general.py", line 474, in check_suffix
    assert (s in suffix) or (len(s) == 0), f"{msg}{f} acceptable suffix is {suffix}"
                             ^^^^^^^^^^^
AssertionError: ['D:\\Techgium\\Model_parameters\\yolov5\\best.pt'] acceptable suffix is ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '_paddle_model'] i have this issue wherein my weights file is already in .pt file still facing problem

**Comment by glenn-jocher** [comment]
@Ashritv it appears that you've encountered an issue with specifying the weights file for detection. The error message you see is part of a check to ensure that the weights file or model file you are using has an acceptable file format suffix. Your path seems correct, but let's ensure everything else is in order too.

1. **Verify the File Exists**: Double-check that the file `D:\Techgium\Model_parameters\yolov5\best.pt` does indeed exist and is not corrupted. Try opening it with a text editor to see if the file isn't empty or corrupted.

2. **Path Formats**: Ensure there's no issue with the way the path is formatted. Sometimes, path format or special characters in the path can cause issues. Though your path looks fine, it's something to consider if everything else fails.

3. **Latest Code**: Make sure you're using the latest version of the YOLOv5 repository. If you haven't already, pull the latest changes from GitHub. There might be updates or bug fixes addressing this very issue.

4. **Command Format**: Ensure the command you're using to invoke the detection script is correctly formatted. An example command structure for running detection with a pretrained model looks like this (make sure to adjust paths according to your setup):
   ```plaintext
   python detect.py --weights D:\Techgium\Model_parameters\yolov5\best.pt --img 640 --conf 0.25 --source data/images
   ```
   Make sure there are no extra quotes or characters around the file path that might be interpreted incorrectly by the script.

5. **Script Modifications**: If you've made any modifications to the detect.py script or any other scripts in the repository, consider reverting those changes or testing with an unmodified version of the YOLOv5 repository to rule out custom code as the source of the problem.

If after going through these steps, you still face the issue, it might be helpful to create a detailed bug report on the YOLOv5 GitHub page, including the exact command you're using, the full error message, and any additional context that might help diagnose the problem. This will allow the community to provide more targeted assistance.
