### ISSUE TITLE
boxes resizing advise

### ISSUE THREAD

**Issue by sekisek** [ultralytics/yolov5#4952]
Hi,
I have a stream  3480x2160.
I use a letterbox with a size 1280 function to resize it.
I get back an image of 1280*768  (1280x720 before the added stripes)

when I try to recalculate the boxes of the detection to the original frame size I get an offset that I can't overcome. 
I attached the image of the detections on the resized and original frame.

I need someone smart advice :)

![letterboxed](https://user-images.githubusercontent.com/29840960/134981845-dc62afc8-f5db-4e87-8934-7454868ce889.jpg)

this is the original resized after the recalculated box was added so it can be screenshot (u can see the offset here):

![original_resized_after](https://user-images.githubusercontent.com/29840960/134982048-81f9aeb8-849d-44c1-a34a-2e399bb8a4f7.jpg)

**Comment by glenn-jocher** [comment]
@sekisek YOLOv5 resizes/letterboxes automatically, no action is required on your part. You simply pass images for inference and get detections back in original image coordinates.

**Comment by sekisek** [comment]
@glenn-jocher 
I think I am maybe doing somethiing wrong because when I get the:
ret, frame = cap.read() from the stream

if I don't do the letterbox function and the following few line of codes I get errors, and when I resize it to a smaller size I get better FPS, what am I missing? 

```
img2= letterbox(frame, new_shape=(imgsz), scaleup=False)[0]
img2 = img2.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
img2 = np.ascontiguousarray(img2)
img2 = torch.from_numpy(img2).to(device)      
            img2 = img2.half() if half else img2.float()  # uint8 to fp16/32
            img2 /= 255.0  # 0 - 255 to 0.0 - 1.0
            if img2.ndimension() == 3:
                img2 = img2.unsqueeze(0)

pred = model(img2, augment=False)[0]
pred = non_max_suppression(pred, 0.2, 0.45, classes=None)#, agnostic=opt.agnostic_nms)
```

**Comment by glenn-jocher** [comment]
@sekisek I don't know what that code is. detect.py is a fully managed inference solution, no changes to any code are required on your part, actually to the contrary we do not assist in debugging custom code.

If you believe you have a reproducible bug, we've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
