### ISSUE TITLE
Please try to raise your shared memory limit when start training

### ISSUE THREAD

**Issue by nqthai309** [ultralytics/yolov5#4964]
i train with dataset 200000 images (13 classes), but face to face this error when start trainin. i trained on 4 GPUs Tesla K80 (11GB/gpu) :(. Help mee!!
![11111](https://user-images.githubusercontent.com/61822545/135041551-16b061e4-d762-46d8-97b8-d26dae4b599a.jpg)
g

**Comment by glenn-jocher** [comment]
@nqthai309 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by ohsai** [comment]
99% sure adding the --ipc=host option on _docker run_ command will solve this.

**Comment by Hasipasi** [comment]
@ohsai thanks!

**Comment by glenn-jocher** [comment]
@Hasipasi Thank you for your suggestion! Adding the `--ipc=host` option to the `docker run` command can indeed help resolve CUDA memory errors when training with YOLOv5. This option allows the Docker container to access the host's shared memory, which can increase the available memory for your training process. Please give it a try and let us know if it resolves the issue for you. Feel free to reach out if you have any more questions or concerns. Happy training!

**Comment by Hasipasi** [comment]
@glenn-jocher, resolved my issue, thanks!

**Comment by glenn-jocher** [comment]
@Hasipasi you're welcome! I'm glad to hear that your issue has been resolved. If you have any more questions or need further assistance, feel free to ask. The YOLOv5 community and the Ultralytics team are always here to help. Happy coding!
