### ISSUE TITLE
Redundant parameter leads to ValueError

### ISSUE THREAD

**Issue by Foooder** [ultralytics/yolov5#4966]
## 🐛 Bug

Redundant parameter leads to ValueError

## To Reproduce (REQUIRED)

Input:

```
model = torch.hub.load('ultralytics/yolov5', 'custom', path=weight_path,force_reload=True)
```

Output:

```
...
~/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py in <module>
     16 if str(ROOT) not in sys.path:
     17     sys.path.append(str(ROOT))  # add ROOT to PATH
---> 18 ROOT = ROOT.relative_to(Path.cwd())  # relative
     19 
     20 from models.common import *

/pathA/python3.7/pathlib.py in relative_to(self, *other)
    898             formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
    899             raise ValueError("{!r} does not start with {!r}"
--> 900                              .format(str(self), str(formatted)))
    901         return self._from_parsed_parts('', root if n == 1 else '',
    902                                        abs_parts[n:])

ValueError: '~/.cache/torch/hub/ultralytics_yolov5_master' does not start with '/pathB/tools/data_process_tools'
```

## Expected behavior

Return the model.

## Environment

- OS: [Ubuntu]
- GPU [V100]

## Additional context

The  parameter `ROOT` is no more used after line17 in `ultralytics_yolov5_master/models/yolo.py` , I think the line18 should be removed.

**Comment by glenn-jocher** [comment]
@Foooder good news 😃! Your original issue may now be fixed ✅ in PR #4974. This PR comments out relative ROOT attempts in yolo.py and tf.py which may be imported by PyTorch Hub. We did not revert to using Path().is_relative() anymore because this was only introduced in python 3.8 and we want python >3.6 compatability.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
