### ISSUE TITLE
Cannot load the model

### ISSUE THREAD

**Issue by pnama** [ultralytics/yolov5#4970]
I get an error when I run this code torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/path/last.pt', force_reload=True)
It was working until yesterday and now I receive an error "raise ValueError("{!r} does not start with {!r}"
ValueError: 'C:\\Users\\aaa\\.cache\\torch\\hub\\ultralytics_yolov5_master' does not start with 'C:\\Users\\aaa\\PycharmProjects\\project\\proejct1'". I have removed the files inside the cache folder but it doesn't fix the error...
Any suggestions will be appreciated. Thank you

**Comment by Basti110** [comment]
I have the same error. Two days ago, the code worked for me.

**Comment by chainyo** [comment]
It seems linked to these recent commits: 5ed28603cf94185c28da02b3d8bb433118ac33d4 and 938b39b3308247e5c46abd76c9dd203467404ec9

**Comment by pnama** [comment]
I've tried both the old version and new version, but still having the same error :(

**Comment by yuriikulish** [comment]
The problem is here https://github.com/ultralytics/yolov5/commit/5ed28603cf94185c28da02b3d8bb433118ac33d4#diff-2cd118cbb69c9ca7b5544f4187b11335fc3addbaf2c3c5bb45435cac648c957bR18

It fails to create relative path to two paths with no common root path

**Comment by chainyo** [comment]
> It fails to create relative path to two paths with no common root path

yes, the condition statement `if... else...` was removed.

```diff
- ROOT = ROOT.relative_to(Path.cwd()) if ROOT.is_relative_to(Path.cwd()) else ROOT # relative

+ ROOT = ROOT.relative_to(Path.cwd())
```

Check this commit: 938b39b3308247e5c46abd76c9dd203467404ec9

**Comment by pnama** [comment]
Is there a way to fix it? I tried to edit but hub.load keeps removing my fix and runs with the newest version...

**Comment by chainyo** [comment]
> Is there a way to fix it? I tried to edit but hub.load keeps removing my fix and runs with the newest version...

You can specify a local link to the repository when loading the model via `torch.hub.load()`
Check: https://pytorch.org/docs/stable/hub.html#torch.hub.load
I think you have to git clone yourself the repo of yolov5 and fill the path to find it in your loading function.

You can also fork the version you want of the YoloV5 repo and change `ultralytics/yolov5` by `your_github/yolov5`.

**Comment by pnama** [comment]
Ok. It seems like it's working for now. Thank you so much everyone. Amazing help

**Comment by chainyo** [comment]
@pnama Could you describe what worked for you ?

**Edit:** This is what worked for me.
- Fork YoloV5 repository
- I cloned the new forked repo on local `git clone https://github.com/ChainYo/yolov5`
- `cd yolov5` to enter in the cloned repo
- `git reset --hard a820b43aca3816c9552e9beaf14a77955742b0ec` to restore the repo before the path change
- `git push -f` to make a forced push of the restored repo on my own github
- Replace `ultralytics/yolov5` by `ChainYo/yolov5` in my `torch.hub.load()` function.

This is what my loading function looks like:
```python
model = torch.hub.load("ChainYo/yolov5", "custom", path="path/to/yolov5.pt", force_reload=True)
```

**Comment by pnama** [comment]
Yeap. Looks like you have the perfect answer. In my case, I've already had the yolo model so I just changed the path to the local folder and it worked :)

**Comment by glenn-jocher** [comment]
@pnama @Basti110 @ChainYo good news 😃! Your original issue may now be fixed ✅ in PR #4974. This PR comments out relative ROOT attempts in yolo.py and tf.py which may be imported by PyTorch Hub. We did not revert to using Path().is_relative() anymore because this was only introduced in python 3.8 and we want python >3.6 compatability.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
TODO: Add import custom model with PyTorch Hub to CI tests.

**Comment by glenn-jocher** [comment]
@pnama @Basti110 @ChainYo CI tests have been updated in PR #4978 to include PyTorch Hub custom model loading as part of CI. This should hopefully help us catch any bugs of this type going forward before merging PRs.

Removing TODO, task complete.
