### ISSUE TITLE
`Torch.hub.load()` broken because of a recent commit

### ISSUE THREAD

**Issue by chainyo** [ultralytics/yolov5#4973]
## 🐛 Bug

Since this commit 5ed28603cf94185c28da02b3d8bb433118ac33d4 we can't load a custom model via `torch.hub.load()` function, because the yolov5 repo is by default cached and isn't downloaded in the project repository.

These are the lines that changed in multiple files
```diff
- ROOT = ROOT.relative_to(Path.cwd()) if ROOT.is_relative_to(Path.cwd()) else ROOT # relative

+ ROOT = ROOT.relative_to(Path.cwd()) # relative
```

## To Reproduce (REQUIRED)

Input:

```python
import torch

model = torch.hub.load("ultralytics/yolov5", "custom", path="path/to/yolov5.pt", force_reload=True)
```
(I can't include my custom model because it's my company property, but any `.pt` will do the job!)

Output:

```
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/Thomas.Chaigneau/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "/home/Thomas.Chaigneau/miniconda3/envs/project/lib/python3.8/site-packages/project/services/yolov5service.py", line 23, in __init__
    model = torch.hub.load(
  File "/home/Thomas.Chaigneau/.local/lib/python3.8/site-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/Thomas.Chaigneau/.local/lib/python3.8/site-packages/torch/hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
  File "/home/Thomas.Chaigneau/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 70, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "/home/Thomas.Chaigneau/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 30, in _create
    from models.yolo import Model
  File "/home/Thomas.Chaigneau/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 18, in <module>
    ROOT = ROOT.relative_to(Path.cwd())  # relative
  File "/home/Thomas.Chaigneau/miniconda3/envs/project/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/Thomas.Chaigneau/.cache/torch/hub/ultralytics_yolov5_master' does not start with '/home/Thomas.Chaigneau/code/project'
```

## Expected behavior

This worked the day before.  
I found a workaround here #4970 but it's only temporary :)

**Comment by glenn-jocher** [comment]
@ChainYo good news 😃! Your original issue may now be fixed ✅ in PR #4974. This PR comments out relative ROOT attempts in yolo.py and tf.py which may be imported by PyTorch Hub. We did not revert to using Path().is_relative() anymore because this was only introduced in python 3.8 and we want python >3.6 compatability.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by chainyo** [comment]
> Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 rocket!

Yes problem fixed! Hope you will find a way to make it work without commenting the line you wanted to implement
Thanks for the fast answer, have a nice day ☀️ !

**Comment by glenn-jocher** [comment]
@ChainYo thanks for the confirmation!

Yes there is an alternate os.path-based solution that we can implement later. The only reason for updating ROOT to a relative path is to reduce screen printout on long paths, but these updates are not critical to functionality.
