### ISSUE TITLE
Training changes?

### ISSUE THREAD

**Issue by matpy1** [ultralytics/yolov5#4976]
Hey,

was there a change to YoloV5 in the last 24 hours? I was running trainings on YoloV5 (on Google Colab) according to the tutorial in the last days and it worked perfectly. Since today I get problems with training, to be specific the images for the training can no be found by YoloV5 even though the paths which were working perfectly the last days/weeks have NOT changed.

**Comment by glenn-jocher** [comment]
@matpy1 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. To answer your question, yes there are constant changes to YOLOv5 every day.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by iceisfun** [comment]
@matpy1 I just verified the latest repo trains just as well as one from a few weeks ago.

Also my input data structure conforms to

https://docs.ultralytics.com/yolov5/tutorials/train_custom_data section 1.1

**Comment by glenn-jocher** [comment]
@matpy1 if dataset availability is an issue you should ensure it is present on a local drive and you are not accessing it over a network or mounted google drive etc.
