### ISSUE TITLE
use formatting Isort/YAPF/Black

### ISSUE THREAD

**Issue by Borda** [ultralytics/yolov5#4983]
## 🚀 Feature

Lets standartize the code formating:
- Isort for import cleaning
- YAPF for custom code formating
- Black is just one strong one

## Motivation

Improve the code readability

## Alternatives

could be integrated with pre-commit, see #4982

## Additional context

[Thoughts on Why Code Formatting is even more important for Open-Source](https://medium.com/geekculture/thought-on-why-code-formatting-is-important-even-more-for-open-source-476829b54eaf)

**Comment by glenn-jocher** [comment]
@Borda yes I think this is a good idea! 

I've been manually sorting imports alphabetically (when I have time) since I couldn't find a formatter to do this. 

I looked at black previously but decided against it as it was a bit too aggressive. Maybe Flake8 or YAPF would be a better start.

Nice article!

**Comment by Borda** [comment]
> I've been manually sorting imports alphabetically (when I have time) since I couldn't find a formatter to do this.

Isort does it
https://github.com/Borda/BIRL/blob/cae694f52434e74386a9f1fd2007a218e3a3d670/setup.cfg#L57-L67

> I looked at black previously but decided against it as it was a bit too aggressive. Maybe Flake8 or YAPF would be a better start.

yes, you can have look at
https://github.com/Borda/BIRL/blob/cae694f52434e74386a9f1fd2007a218e3a3d670/setup.cfg#L45-L54
