### ISSUE TITLE
Small object detection

### ISSUE THREAD

**Issue by tfpb** [ultralytics/yolov5#5011]
Hello, 
first thanks for you great work, it's an amazing project.

The object hight in my inference is around 30-50% of the object hight from my dataset because I have a camera with a 2 times bigger view than the dataset. 

I know i can increase pixel size for inference but this cost a lost of performance. Is there a way to make the dataset smaller. I saw the scale parameter in the hyperfiles, but I don't find any description what it does.

thanks regards

**Comment by glenn-jocher** [comment]
@tfpb `--img-size` argument controls image size for detect.py and train.py.

**Comment by JJrodny** [comment]
Thanks! So setting `--img-size` will resize the COCO images during training to that size, e.g. 4000.

Now say I wanted to create a tiny COCO-type object detector. How can I train a model with a large mosaic of e.g. 10x10 COCO images where each image is 400x400 pixels?

In my hyp.yaml I'd set `mosaic: 1.0` (will that only do a 2x2 grid?).

Can I also set a range or something for the `scale` hyperparameter instead of it being a single value +/- gain in size?
E.g. I'd like to do something like set `scale: -.9` to scale down my COCO images to be 10% of the input size (400 pixels)
Or `scale: [-.95,-.85]` to scale down my COCO images to be between 5% and 15% of the input size of 4000 pixels?

Thanks for your help! This repo is really good! It's pleasently surprised me multiple times when I run it in how it already does what I'd want it to do before I know it does (creating confusion matrix, drawing gts on images, printing output on images, drawing PR curve, labels analysis) Nice job!

**Comment by JJrodny** [comment]
Rubber ducking with this post I've realized I guess in this case I could actually just train a model at 400x400 input size and then just inference at 4000x4000 input size to find the small objects. Are the YOLOv5 models maleable in that sense? Can I train and inference at different sizes without problems?

**Comment by glenn-jocher** [comment]
@JJrodny your image size is irrelevant. For best results your object sizes (in pixels) should be similar during training and deployment. The --img argument sets train and detect image sizes.

`scale` jitter is an augmentation hyperparameter set in your hyp yaml file:
![YOLOv5 augmentation](https://user-images.githubusercontent.com/26833433/135692509-5159ef67-3933-44e8-b3f8-35af3e5e440b.jpg)

**Comment by fcakyon** [comment]
@tfpb @JJrodny you can perform sliced inference with https://github.com/obss/sahi using your yolov5 model for better small object detection.

Check the yolov5+sahi colab demo: https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb

**Comment by JJrodny** [comment]
Thanks @glenn-jocher, @fcakyon, I'll take a look at that repo, but my first glance at the colab and it looks to be exactly what I'm interested in!

For others looking for the answer to modifying mosaic-ing parameters, looking deeper into the code it looks like mosaic-ing is hard-coded as 4 images in a 2x2 grid

https://github.com/ultralytics/yolov5/blob/a64a4c839fa15baf5ea2be933e7034a1607878b2/utils/datasets.py#L661

Thanks y'all!
