### ISSUE TITLE
list index out of range when using results.print()

### ISSUE THREAD

**Issue by shiyongming** [ultralytics/yolov5#5036]
## 🐛 Bug

Got list index out of range ERROR when using `results.print()`

## To Reproduce (REQUIRED)

Input:

```
import torch
from PIL import Image
import numpy as np

image_path = 'zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
image = Image.open(image_path)
image.show()
results = model(np.array(image))
# results = model(image_path)
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
```

Output:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-2e03d48e1ce6> in <module>
      6 # results = model(np.array(image))
      7 results = model(image_path)
----> 8 results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in print(self)
    406 
    407     def print(self):
--> 408         self.display(pprint=True)  # print results
    409         LOGGER.info(f'Speed: %.1fms pre-process, %.1fms inference, %.1fms NMS per image at shape {tuple(self.s)}' %
    410                     self.t)

~/.cache/torch/hub/ultralytics_yolov5_master/models/common.py in display(self, pprint, show, save, crop, render, save_dir)
    373                 for c in pred[:, -1].unique():
    374                     n = (pred[:, -1] == c).sum()  # detections per class
--> 375                     s += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "  # add to string
    376                 if show or save or render or crop:
    377                     annotator = Annotator(im, example=str(self.names))

IndexError: list index out of range
```

## Environment

- OS: Ubuntu18.04
- GPU: T4

**Comment by glenn-jocher** [comment]
@shiyongming see PyTorch Hub tutorial for YOLOv5 inference:

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️ RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Supervisely Ecosystem](https://docs.ultralytics.com/yolov5/tutorials/model_export8)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TorchScript, ONNX, CoreML Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [TensorRT Deployment](https://github.com/wang-xinyu/tensorrtx)

**Comment by MikeMACintosh** [comment]
Hi, did you solve this problem? I have same. Thanks:)

**Comment by glenn-jocher** [comment]
@MikeMACintosh 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by xinyiamazing** [comment]
hello,solve it? i also have this problem

**Comment by glenn-jocher** [comment]
@Chenanxinyi 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
Command works correctly. Issue is not reproducible:

<img width="1082" alt="Screenshot 2022-06-13 at 12 25 52" src="https://user-images.githubusercontent.com/26833433/173334080-bf2718bc-4073-46ce-bc39-44d423abec19.png">
