### ISSUE TITLE
How to add a new category to  a pretrain model?，pretrain model classes is 41 ,but now nedd add to 45。

### ISSUE THREAD

**Issue by yanyubing666** [ultralytics/yolov5#508]

**Comment by glenn-jocher** [comment]
@yanyubing666 I've just pushed recent updates so that once your training completes your weights (last.pt and best.pt) are fully finalized (same as the official pretrained weights) and can be used as pretrained weights for new datasets with any number of classes.

If you'd like to apply this to older pretrained weights then git pull or reclone yolov5 to receive the latest updates, then  simply run this for example to apply to last.pt: `from utils.utils import *; strip_optimizer('path_to/last.pt')`

Related PR is https://github.com/ultralytics/yolov5/pull/509
