### ISSUE TITLE
Export .tflite

### ISSUE THREAD

**Issue by alexiej** [ultralytics/yolov5#5133]
## ❔Question

How to export the trained model to .tflite ? 

## Additional context

I've tried this instruction:

`python export.py --weights yolo5/best_yolo5s.pt --include tflite`

But I've got error:

```
export: data=yolo5/data/coco128.yaml, weights=yolo5/best_yolo5s.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=13, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['tflite']
YOLOv5 🚀 ca30934 torch 1.7.1 CPU

[2021-10-11 14:38:48.066 MacBook-Pro-Arkadiusz.local:96894 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2021-10-11 14:38:48.162 MacBook-Pro-Arkadiusz.local:96894 INFO profiler_config_parser.py:111] Unable to find config at /opt/ml/input/config/profilerconfig.json. Profiler is disabled.
Fusing layers... 
Model Summary: 275 layers, 7064511 parameters, 0 gradients


TensorFlow saved_model: export failure: no matching TensorFlow activation found for SiLU()

TensorFlow Lite: starting export with tensorflow 2.6.0...

TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'
```

I tried found what SiLU() is, and it should work properly, but I've got errror.

**Comment by glenn-jocher** [comment]
@alexiej it seems like your TensorFlow version may be out of date. You should update TensorFlow, or you can also run YOLOv5 exports in a verified environment like Colab where everything works well.

**Comment by alexiej** [comment]
@glenn-jocher I've got the same error on Colab  (GPU and CPU version). :/. In MAC, and COLAB I use the same version `2.6.0` of tensorflow.

![image](https://user-images.githubusercontent.com/12593751/136953985-88ed882c-7358-4750-bdf8-a3a57799a41d.png)

```
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
export: data=yolo5/data/coco128.yaml, weights=yolo5/best_yolo5s.pt, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=13, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['tflite']
YOLOv5 🚀 732439b torch 1.9.0+cu111 CPU

[2021-10-12 12:12:25.539 5e560cd0409f:190 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2021-10-12 12:12:25.590 5e560cd0409f:190 INFO profiler_config_parser.py:111] Unable to find config at /opt/ml/input/config/profilerconfig.json. Profiler is disabled.
Fusing layers... 
Model Summary: 275 layers, 7064511 parameters, 0 gradients

PyTorch: starting from yolo5/best_yolo5s.pt (14.4 MB)

TensorFlow saved_model: starting export with tensorflow 2.6.0...

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]                    
2021-10-12 12:12:29.578868: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-10-12 12:12:29.578937: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5e560cd0409f): /proc/driver/nvidia/version does not exist

TensorFlow saved_model: export failure: no matching TensorFlow activation found for SiLU()

TensorFlow Lite: starting export with tensorflow 2.6.0...

TensorFlow Lite: export failure: 'NoneType' object has no attribute 'call'

Export complete (4.21s)
Results saved to /content/model-training/src/yolo5
Visualize with https://netron.app
```

The SiLU layer I found is: Maybe it should be `torch.nn.SiLU`

```
# SiLU https://arxiv.org/pdf/1606.08415.pdf ---
class SiLU(nn.Module):  # export-friendly version of nn.SiLU()
    @staticmethod
    def forward(x):
        return x * torch.sigmoid(x)
```

**Comment by alexiej** [comment]
When I comment in `export.py` line: 385


```
            if isinstance(m.act, nn.SiLU):
                # m.act = SiLU()
                print("ACTIVATION", m.act)
```

The model was exported without issues. I need to verify if it works as original, but I think this was the problem of the export.

**Comment by glenn-jocher** [comment]
@alexiej Colab export to TFLite works correctly for me, I'm not able to reproduce your issue:
<img width="1450" alt="Screen Shot 2021-10-12 at 12 25 59 PM" src="https://user-images.githubusercontent.com/26833433/137017025-a45ac269-f8fe-4f74-b3bb-78fc2d6c432e.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
