### ISSUE TITLE
ONNX: export failure: input 1 is out of bounds

### ISSUE THREAD

**Issue by erb13020** [ultralytics/yolov5#5139]
## ❔Question

Why am I getting this error when trying to export my model to Onnx?

**Command**
`python3.8 export.py --weights ../runs/train/exp28/weights/best.pt --include onnx --dynamic`

**Output**
```
export: weights=../runs/train/exp28/weights/best.pt, img_size=[640, 640], batch_size=1, device=cpu, include=['onnx'], half=False, inplace=False, train=False, optimize=False, dynamic=True, simplify=False, opset=13
YOLOv5 🚀 d25a0b4 torch 1.8.0a0+52ea372 CPU

Fusing layers... 
Model Summary: 606 layers, 140996152 parameters, 0 gradients, 221.2 GFLOPs

PyTorch: starting from ../runs/train/exp28/weights/best.pt (1130.2 MB)

ONNX: starting export with onnx 1.8.0...
/notebooks/ThurgoodModel/yolov5/models/yolo.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic:
ONNX: export failure: input 1 is out of bounds

Export complete (20.22s)
Results saved to /notebooks/ThurgoodModel/runs/train/exp28/weights
Visualize with https://netron.app
```
## Additional context

The command I used to train my model was

`yolov5/train.py --data ../labelbox/labelbox.yaml --cfg models/hub/yolov5x6.yaml --weights yolov5x6.pt --epochs 600 --patience 600 --img 1280 --batch 12`

My hardware is a VM with an Nvidia A100 40GB vRAM GPU with a 12 core processor running Ubuntu 20.04.

I've also tried appending `--batch 12` and `--img_size 1280` to the command but the results are the same.

This is what my weights directory looks like.

`best.mlmodel  best.pt  best.torchscript.pt  last.pt`

My PyTorch version is 1.8

```
>>> import torch
>>> print(torch.__version__)
1.8.0a0+52ea372
```

Any hints?

**Comment by glenn-jocher** [comment]
@erb13020 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We are not able to reproduce your issue.


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by erb13020** [comment]
@glenn-jocher I was able to run the export using my weights with the official yolov5 Docker image. This means the issue was most likely with my setup.
