### ISSUE TITLE
AttributeError: Can't get attribute 'SPPF' on <module 'models.common'

### ISSUE THREAD

**Issue by zthong-deepsleepinger** [ultralytics/yolov5#5143]
```
Traceback (most recent call last):
  File "/Users/hongzongtao/Desktop/电力机房视频监控项目_v6/yolov5-5.0/detect.py", line 178, in <module>
    detect()
  File "/Users/hongzongtao/Desktop/电力机房视频监控项目_v6/yolov5-5.0/detect.py", line 34, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/Users/hongzongtao/Desktop/电力机房视频监控项目_v6/yolov5-5.0/models/experimental.py", line 118, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/Users/hongzongtao/Desktop/电力机房视频监控项目_v6/yolov5-5.0/models/common.py'>
```

**Comment by YoniChechik** [comment]
Did you manage to get this to work? I'm having the same problem

**Comment by glenn-jocher** [comment]
@zthong-deepsleepinger good news 😃! Your original issue may now be fixed ✅ in PR #5147 by @YoniChechik . To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload with `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by PLXIV** [comment]
Hey @YoniChechik , I had the same issue. My issue was given that I was using yolov5 version 5, and yesterday they released version 6, The issue comes from the repository code. It is hardcoded to download the latest weight version. To solve it, I modified a couple of lines from the script utils/google_utils.py.

In the line 37, I changed:
url = f'https://github.com/{repo}/releases/download/{tag}/{name}' 
to 
url = f'https://github.com/{repo}/releases/download/v5.0/{name}'

I fix this issue by doing this slight modification.

Hope it helps!

**Comment by Lg955** [comment]
@YoniChechik @zthong-deepsleepinger  
I met the same problem.
I found that the cause was a version issue:  I download the yolo5-v4.0, but  the weight downloaded is yolo5-latest, so I get the error `AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from`.  So you can check if have the same wrong.
