### ISSUE TITLE
Optimal hyperparameters for openimages

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#5155]
Wondering if anyone has run evolution on openimages and can share the generated hyperparameter settings?
This is available for Object365 but not openimages.

@glenn-jocher @ferdinandl007 @NanoCode012 @timstokman

**Comment by glenn-jocher** [comment]
@lleye no we don't have open-images hyps, because they will probably depend on the subset of classes you want to train for your particular task. 

Also beware, open images is a huge dataset, but it may not be consistently labelled. For example if you want to pull images with faces and hands, it's possible the images with hands may not have faces labelled and vice versa, so it makes it difficult to use without more complex/custom autolabelling/teacher workflows.
