### ISSUE TITLE
AttributeError,add_graph,callbacks

### ISSUE THREAD

**Issue by chenshiliu** [ultralytics/yolov5#5179]
## ❔Question
This error occurs when training the model
## Additional context
Traceback (most recent call last):
  File "E:/projects/yolov5-master/train.py", line 620, in <module>
    main(opt)
  File "E:/projects/yolov5-master/train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:/projects/yolov5-master/train.py", line 340, in train
    callbacks.run('on_train_batch_end', ni, model, imgs, targets, paths, plots, opt.sync_bn)
  File "E:\projects\yolov5-master\utils\callbacks.py", line 76, in run
    logger['callback'](*args, **kwargs)
  File "E:\projects\yolov5-master\utils\loggers\__init__.py", line 79, in on_train_batch_end
    self.tb.add_graph(torch.jit.trace(de_parallel(model), imgs[0:1], strict=False), [])
AttributeError: 'NoneType' object has no attribute 'add_graph'

**Comment by glenn-jocher** [comment]
@chenshiliu 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
