### ISSUE TITLE
map between train and val are different

### ISSUE THREAD

**Issue by phunix9** [ultralytics/yolov5#5186]
Hello, thank you for your work.

I have a problem that when I finished traing the model, it generated 0.86 map after the final epoch. However, when I used val.py to test data, it got 0.75 map.

I am sure that the data, the image size, the conf-thres and the iou-thres are all the same. I am very comfused and need your advice.

Thanks!

**Comment by glenn-jocher** [comment]
@phunix9 this is likely user error, i.e. different arguments used in train and val. If you believe you see a reproducible bug, then please raise a new bug report issue following guidance below. Thank you!


👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by kingthreestones** [comment]
@phunix9 how do you solve the problem？
