### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

### ISSUE THREAD

**Issue by frensher** [ultralytics/yolov5#5187]
## Additional context
run val.py or detect.py  ，occur the mistakes
who can tell me how to solve it

**Comment by frensher** [comment]
Traceback (most recent call last):
  File "val.py", line 360, in <module>
    main(opt)
  File "val.py", line 334, in main
    run(**vars(opt))
  File "/home/wgj/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 149, in run
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "/home/wgj/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wgj/yolov5/models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/wgj/yolov5/models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/home/wgj/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wgj/yolov5/models/yolo.py", line 55, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/home/wgj/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'm'

**Comment by glenn-jocher** [comment]
@frensher 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. In our tests detect.py and val.py are operating correctly.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by frensher** [comment]
May i ask the version of cuda ?

**Comment by glenn-jocher** [comment]
@frensher you can install pytorch for various versions of CUDA. See https://pytorch.org/get-started/locally/

**Comment by frensher** [comment]
> 
> 
> @frensher you can install pytorch for various versions of CUDA. See https://pytorch.org/get-started/locally/

3q
