### ISSUE TITLE
Sensitivity Effects Near Grid Boundaries

### ISSUE THREAD

**Issue by viplix3** [ultralytics/yolov5#528]
Hi @glenn-jocher,

You opened an issue regarding sensitivity near grid boundaries on AlexyAB's fork of darknet here: [https://github.com/AlexeyAB/darknet/issues/3293](https://github.com/AlexeyAB/darknet/issues/3293)

I am trying to train a YOLOv3 based object detection model and facing a similar issue.
I've gone through the whole thread but couldn't find any conclusive outcomes.

I've posted some follow up questions on that thread. [https://github.com/AlexeyAB/darknet/issues/3293#issuecomment-664154657](https://github.com/AlexeyAB/darknet/issues/3293#issuecomment-664154657)

I was wondering if you were able to solve the said issue.

**Comment by glenn-jocher** [comment]
@viplix3 yes. I discovered this issue a while back after discovering hotspots in pedestrian detection using our iOS app. The issue is resolved in YOLOv5. If you see evidence to the contrary though please let us know.

Single Frame | 2D Histogram over 1 hour
--- | --- 
![IMG_4519](https://user-images.githubusercontent.com/26833433/58729732-7f218580-83ea-11e9-9edb-ebe63c8774ab.jpg) | ![IMG_4519_2](https://user-images.githubusercontent.com/26833433/58729738-8183df80-83ea-11e9-8535-1c87d9e18f94.jpg)

**Comment by viplix3** [comment]
@glenn-jocher 
Thanks for the clarification. Closing.

**Comment by Zubair2019** [comment]
Surely this problem has been addressed  by the authors of YOLO(v4) by calculating the dimensions of bounding box differently.They solved this problem through multiplying the sigmoid by a factor exceeding 1.0, so eliminating the effect of grid on which the object is undetectable.

**Comment by glenn-jocher** [comment]
@Zubair2019 eliminating is a strong word for this. Reduced is more realistic.

I've also never repeated the above experiment, so no fix has ever been verified or observed directly. It's likely all xywh spaces will suffer from this problem to varying degrees.
