### ISSUE TITLE
About the enhanced method of copy and paste

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#5285]
@glenn-jocher 
Can this copy-and-paste enhancement method only be applied to image segmentation? I used it for object detection, but mAP did not rise.
https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/utils/augmentations.py#L214-L235

**Comment by glenn-jocher** [comment]
@Zengyf-CVer yes copy paste is only used if segment labels are present. If `n=0` then this augmentation is not used. Box labels can not be used because they would copy and paste the entire box, the object plus the background around it. the main benefit of copy paste as I understand is that the object can be shown with different backgrounds.

https://github.com/ultralytics/yolov5/blob/15e8c4c15bff0e3c729868e2c31f80f918e31fb2/utils/augmentations.py#L216-L217

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Thank you very much.
