### ISSUE TITLE
i = f1.mean(0).argmax()  # max F1 index

### ISSUE THREAD

**Issue by aimen123** [ultralytics/yolov5#5296]
i = f1.mean(0).argmax()  # max F1 index

i dont understand  it 
i try to change confidence ,but the precison dont change,so  why to do it?
thanks

**Comment by glenn-jocher** [comment]
@aimen123 Precision P and Recall R are displayed at the max F1 confidence level (i.e. typicaly around 0.2-0.8) rather than the --conf 0.001 value. This is because at the default confidence threshold of 0.001, P would be near zero and R would be near 1 in all cases, making them uninformative for real-world results.

**Comment by glenn-jocher** [comment]
Example F1 curve from YOLOv5n. In this case P and R are displayed by val.py at confidence 0.224.

![image](https://user-images.githubusercontent.com/26833433/138486188-afdc101b-386d-428c-84f1-b794148f3f25.png)

**Comment by aimen123** [comment]
@glenn-jocher the result of v3.1 and v6 is deifferent，v6 is better？why not v3.1？

**Comment by glenn-jocher** [comment]
@aimen123 I recommend you use the latest version. As I said above P and R are computed at max F1 confidence because at the default confidence threshold of 0.001, P would be near zero and R would be near 1 in all cases, making them uninformative for real-world results.
