### ISSUE TITLE
androud gpu error 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#5321]
i run the android code , and it works well on my phone on cpu
but when i choose Gpu i got thi error
```

  Process: com.android.animal_cam_alert, PID: 18996
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    526 operations will run on the GPU, and the remaining 5 operations will run on the CPU.
    TfLiteGpuDelegate Init: MUL: Node 299 is already a consumer of the value 300
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 531 (TfLiteGpuDelegateV2) failed to prepare.
    
    tensorflow/lite/kernels/conv.cc:342 bias->type != input_type (FLOAT16 != FLOAT32)
    Node number 7 (CONV_2D) failed to prepar
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:351)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
        at com.android.animal_cam_alert.tflite.YoloV5Classifier.recreateInterpreter(YoloV5Classifier.java:192)
        at com.android.animal_cam_alert.tflite.YoloV5Classifier.useGpu(YoloV5Classifier.java:200)
        at com.android.animal_cam_alert.DetectorActivity.lambda$updateActiveModel$0$DetectorActivity(DetectorActivity.java:201)
```

**Comment by glenn-jocher** [comment]
@totoadel 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by hietalajulius** [comment]
> i run the android code , and it works well on my phone on cpu but when i choose Gpu i got thi error
> 
> ```
> 
>   Process: com.android.animal_cam_alert, PID: 18996
>     java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
>     DEQUANTIZE: 
>     526 operations will run on the GPU, and the remaining 5 operations will run on the CPU.
>     TfLiteGpuDelegate Init: MUL: Node 299 is already a consumer of the value 300
>     TfLiteGpuDelegate Prepare: delegate is not initialized
>     Node number 531 (TfLiteGpuDelegateV2) failed to prepare.
>     
>     tensorflow/lite/kernels/conv.cc:342 bias->type != input_type (FLOAT16 != FLOAT32)
>     Node number 7 (CONV_2D) failed to prepar
>         at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
>         at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:351)
>         at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:82)
>         at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
>         at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:266)
>         at com.android.animal_cam_alert.tflite.YoloV5Classifier.recreateInterpreter(YoloV5Classifier.java:192)
>         at com.android.animal_cam_alert.tflite.YoloV5Classifier.useGpu(YoloV5Classifier.java:200)
>         at com.android.animal_cam_alert.DetectorActivity.lambda$updateActiveModel$0$DetectorActivity(DetectorActivity.java:201)
> ```

@totoadel did you solve your problem? Facing the same 😅

**Comment by VitorHugoAguiar** [comment]
Ya, same problem also.

**Comment by VYRION-Ai** [comment]
@VitorHugoAguiar @hietalajulius I think the problem was in tensorflow lib
