### ISSUE TITLE
Can't export to .pb model to tfjs

### ISSUE THREAD

**Issue by Tomdri** [ultralytics/yolov5#5331]
## 🐛 Bug

I have trained a custom yolov5 model but when using the export script to export my model tfjs, I keep getting this error. I'm confused since isn't the script suppose to generate the model.json file for me? I am also up to date with the master branch. It does generate a model.pb file and both model_saved_model and model_web_model folders, but the web_model folder is empty.

## To Reproduce (REQUIRED)

Here is the line I used:
python ./export.py --weights plateforme.pt --include tfjs

## Expected behavior

Having the exported model.json

![image](https://user-images.githubusercontent.com/36999616/138700305-33e220c5-b3ce-416b-a4be-278400f7adcc.png)

**Comment by glenn-jocher** [comment]
@Tomdri 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm unable to reproduce any errors with TF.js export. The following commands work correctly for me in our Colab notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

```python
!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt --cache
!python export.py --weights runs/train/exp/weights/best.pt --include tfjs
```

<img width="1008" alt="Screen Shot 2021-10-25 at 3 43 37 PM" src="https://user-images.githubusercontent.com/26833433/138706929-014d2d12-72e5-4530-bdda-0716af79596e.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Tomdri** [comment]
Well I just tried in a google collab and it works !! I was running the script in a git bash terminal

**Comment by Tomdri** [comment]
Thanks !
