### ISSUE TITLE
Torch Hub model behaving differently in CPU and GPU

### ISSUE THREAD

**Issue by Ankur-singh** [ultralytics/yolov5#5335]
I tried running the **Pytorch Hub** code from [YOLO Tutorial](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) on my laptop. The same model is returning **0 detections** in my laptop. After playing around a bit, it seems that the model is able to detect correctly when its moved to CPU. For some reason, its working on CPU but not when the model is in GPU.

I am using a windows 10 laptop and here are the library versions:
```
torch==1.10.0
torchvision==0.11.1
```

## To Reproduce (REQUIRED)

Input:

```python
import torch

img = "https://ultralytics.com/images/zidane.jpg"
model = torch.hub.load("ultralytics/yolov5", "yolov5s")

results = model(img)
results.print()

## CPU
print("\n moving the model to CPU . . .")
model = model.cpu()
results = model(img)
results.print()

```

Output:

```
Using cache found in C:\Users\ankur/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2021-10-25 torch 1.10.0 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 6143.6875MB)

Fusing layers...
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
image 1/1: 720x1280 (no detections)
Speed: 661.9ms pre-process, 112.1ms inference, 1.9ms NMS per image at shape (1, 3, 384, 640)

moving the model to CPU . . .
image 1/1: 720x1280 2 persons, 1 tie
Speed: 711.5ms pre-process, 93.0ms inference, 1.0ms NMS per image at shape (1, 3, 384, 640)
```

## Expected behavior

It should give the same predictions, whether in GPU or CPU.

## Environment

- OS: Windows 10
- GPU: GTX 1660 Ti

**Comment by glenn-jocher** [comment]
@Ankur-singh yes this occurs sometimes with Windows/Conda environments, and may be due to your CUDA drivers or other installation issues. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

[**Python>=3.6.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirements.txt
```

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.
