### ISSUE TITLE
Train multi-gpu

### ISSUE THREAD

**Issue by watermellon2018** [ultralytics/yolov5#5375]
## How to monitor learning progress?

I train yolov5m6 on 4 gpu. I run the train of the command:
```python -m torch.distributed.launch --nproc_per_node 4 train.py --img 1280 --batch 16 --epochs 100 --data data/aitrain_dataset.yaml --weights 'yolov5m6.pt' --hyp data/hyps/hyp_aitrain.yaml --name yoloM --save-period 5 --device 0,1,2,3```
But i get just this trace:
```
FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
wandb: Currently logged in as: yurashku (use `wandb login --relogin` to force relogin)
train: weights=yolov5m6.pt, cfg=, data=data/aitrain_dataset.yaml, hyp=data/hyps/hyp_aitrain.yaml, epochs=100, batch_size=16, imgsz=1280, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0,1,2,3, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, name=yoloM, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, patience=100, freeze=0, save_period=5, local_rank=0, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: up to date with https://github.com/ultralytics/yolov5 ✅
YOLOv5 🚀 v6.0-35-ga4fece8 torch 1.10.0+cu102 CUDA:0 (Tesla K80, 11441.1875MB)
                                              CUDA:1 (Tesla K80, 11441.1875MB)
                                              CUDA:2 (Tesla K80, 11441.1875MB)
                                              CUDA:3 (Tesla K80, 11441.1875MB)

Added key: store_based_barrier_key:1 to store for rank: 0
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
hyperparameters: anchor_t=4.0, box=0.05, cls=0.5, cls_pw=1.0, copy_paste=0.0, degrees=0.0, fl_gamma=0.0, fliplr=0.0, flipud=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, iou_t=0.2, lr0=0.01, lrf=0.1, mixup=0.0, momentum=0.937, mosaic=1.0, obj=1.0, obj_pw=1.0, perspective=0.0, scale=0.5, shear=0.0, translate=0.1, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
wandb: Tracking run with wandb version 0.12.6
wandb: Syncing run yoloM
wandb:  View project at ...
wandb:  View run at ...
wandb: Run data is saved locally in ...
wandb: Run `wandb offline` to turn off syncing.
```
When i use single GPU i can to monitor whick epoch now. In case multi GPU: Is the training going on? How do I know how much it will go?

**Comment by glenn-jocher** [comment]
@watermellon2018 training is always displayed to console regardless of GPU count. YOLOv5 logs results to CSV, TensorBoard and Weights & Biases.

**Comment by watermellon2018** [comment]
@glenn-jocher Thank for your answer. But i my train stop in line 105 train.py:
```
with torch_distributed_zero_first(LOCAL_RANK):
        data_dict = data_dict or check_dataset(data)
```
I read the tutorial and did everything the same, but my train not begin

**Comment by watermellon2018** [comment]
I get LOCAL_RANK = 0 for some GPU

**Comment by watermellon2018** [comment]
I can use 2 gpu, but when i want to use 3 or 4 gpu, the training hang

**Comment by glenn-jocher** [comment]
@watermellon2018 you may environment problems. Docker is recommended for Multi-GPU training in a common verified environment.

- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by cenchaojun** [comment]
> @glenn-jocher Thank for your answer. But i my train stop in line 105 train.py:
> 
> ```
> with torch_distributed_zero_first(LOCAL_RANK):
>         data_dict = data_dict or check_dataset(data)
> ```
> 
> I read the tutorial and did everything the same, but my train not begin

same error，how do you deal with it

**Comment by glenn-jocher** [comment]
@cenchaojun 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
