### ISSUE TITLE
when i change input size 640 to 320，anchor still hasn't changed.

### ISSUE THREAD

**Issue by moyans** [ultralytics/yolov5#5458]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

imgsz: 640x640 
auto_anchor get：
 [4,5,  8,10,  13,16]  
 [23,29,  43,55,  73,105]  
 [146,217,  231,300,  335,433]  

when i change imgsz to 320x320
 check_anchors use 640 generate_anchor BPR still > 0.98.

**Comment by glenn-jocher** [comment]
@moyans yes this happens because your existing anchors still have good coverage (BPR) at your new --imgsz. If you want you can reduce the BPR threshold to force recomputation, or you can also specify your own anchors in a custom model yaml that you pass with `python train.py --weights yolov5s.pt --cfg yolov5s_custom.yaml`.
https://github.com/ultralytics/yolov5/blob/042f02ff9b095e402a937b24c6da6d6e83e554b2/utils/autoanchor.py#L46

I would train both ways and find out which produces better results, and report any interesting findings back here!

**Comment by moyans** [comment]
@glenn-jocher  thank you for your patience.
when 640x640 generate anchor p5/32  [146,217, 231,300, 335,433]  on 320x320 still have good coverage (BPR), can we get  P5 is not import on 320x320?

**Comment by glenn-jocher** [comment]
@moyans you can delete output layers like P5 if you want from your model.yaml.

**Comment by moyans** [comment]
@glenn-jocher thanks
