### ISSUE TITLE
About val the data

### ISSUE THREAD

**Issue by 523997931** [ultralytics/yolov5#5463]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I want to know, if I could use the val scripts just for some classes,
for example, I want to val the pretrained model, but I only care about the mAP of person or car.

**Comment by glenn-jocher** [comment]
@523997931 `python val.py --verbose` will display per-class metrics.

**Comment by 523997931** [comment]
> @523997931 `python val.py --verbose` will display per-class metrics.

Thank you for your reply!

**Comment by ZhouBay-TF** [comment]
@glenn-jocher ，hello，I want to get the value of "P   R     mAP@.5 mAP@”， when i use "python val.py --verbose",i get all val is 0;
![image](https://user-images.githubusercontent.com/38548235/142389237-f3208964-3995-4bb0-8c66-42501fd318aa.png)

**Comment by glenn-jocher** [comment]
@xinkangzhou sure, then your mAP is zero.

**Comment by Symbadian** [comment]
> val.py --verbose

Hi @glenn-jocher, 

Forgive my lack of ignorance but I keep getting this error when I try visualizing the new classes that were added in the training when running the validation script as per your direction python val.py --verbose.

None of the new classes are being shown in the validation verbose stage only the 80 classes per the original dataset.
Based on all of the examples provided, I followed such to the best of my knowledge and I cannot seem to get this understanding. 

Can you help me analyze this, please?
I modified all configurations based on my knowledge but this keeps on popping up, please help!!
and I am not sure what this means no matter how much I google??!!??!?

` (base) Symbadian-MacBook-Pro:yolov5 symbadian$ python3 val.py --verbose
val: data=data/coco128.yaml, weights=yolov5s.pt, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, workers=8, single_cls=False, augment=False, verbose=True, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
YOLOv5 🚀 2022-5-7 torch 1.11.0 CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
This is data in the val.py file {'path': '../datasets/coco128', 'train': ['/Users/symbadian/Desktop/LIRIS_new_dataset/datasets/coco128/images/train', '/Users/symbadian/Desktop/LIRIS_new_dataset/datasets/coco128/images/train2017'], 'val': ['/Users/symbadian/Desktop/LIRIS_new_dataset/datasets/coco128/images/val', '/Users/symbadian/Desktop/LIRIS_new_dataset/datasets/coco128/images/train2017'], 'test': None, 'nc': 106, 'names': ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush', 'Beating', 'CuttingInKitchen', 'Discus_Amgst_ppl', 'Discuss_Wr_OnBrd', 'DiscusW_Give_Item', 'Enter_Room', 'Fencing', 'Fighting', 'Gun_wp_Deploy', 'Hand_Shake', 'Knife_Deploy', 'Leaves_Room', 'Make_Answer_Tel', 'Nunchucks', 'Pick_Up_Object', 'Put_Down_Object', 'Put_Item_In_Draw', 'Reading', 'Shooting', 'Stabbing', 'SumoWrestling', 'Typing_On_KeyBrd', 'Unlock_Dr_Leaves', 'Unlock_Rm_Enters', 'Unlock_Rm_Unsucc', 'Walking']}
This is nc from val.py file 106
This is ncm from val.py file 80
Traceback (most recent call last):
  File "/Users/symbadian/Desktop/LIRIS_new_dataset/yolov5/val.py", line 399, in <module>
    main(opt)
  File "/Users/symbadian/Desktop/LIRIS_new_dataset/yolov5/val.py", line 372, in main
    run(**vars(opt))
  File "/Users/symbadian/miniforge3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/symbadian/Desktop/LIRIS_new_dataset/yolov5/val.py", line 170, in run
    assert ncm == nc, f'{weights[0]} ({ncm} classes) trained on different --data than what you passed ({nc} ' \
TypeError: 'PosixPath' object is not subscriptable`

**Comment by glenn-jocher** [comment]
@Symbadian 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
