### ISSUE TITLE
ResNet-50 backbone config

### ISSUE THREAD

**Issue by twangnh** [ultralytics/yolov5#549]
Hi! thanks for sharing the wonderful yolov5 in pytorch, I'm wondering if you could share backbone configuration for resnet50, currently config only has CSP backbone:

backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, BottleneckCSP, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, BottleneckCSP, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, BottleneckCSP, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, BottleneckCSP, [1024, False]],  # 9
  ]

Thank you.

**Comment by glenn-jocher** [comment]
@twangnh I don't have time or motivation to but we are open to PRs so feel free to submit one for this!

**Comment by Shakesbeer333** [comment]
@twangnh did you find a backbone config for resnet50?

**Comment by glenn-jocher** [comment]
@Shakesbeer333 you can build your own resnet50.yaml by using the existing ones as templates. The backbone section you'd modify is here:
https://github.com/ultralytics/yolov5/blob/187f7c2ed16b9eb9754b28e7b0aa397f908155aa/models/yolov5s.yaml#L12-L26

**Comment by Shakesbeer333** [comment]
@glenn-jocher thank you. Any other section I need to change or to be aware of?

**Comment by glenn-jocher** [comment]
@Shakesbeer333 no just the model.yaml. You want to make a resnet50.yaml basically, with a resnet50 backbone and whatever head you want essentially.

You can use standard pytorch modules to create any architecture, i.e.:
```python
# [from, number, module, args] 
[-1, 1, nn.Conv2d, [128, 3, 2]]
[-1, 1, nn.BatchNorm2d, [128]]
...
```

**Comment by Shakesbeer333** [comment]
@glenn-jocher thanks once again. Can you briefly tell me what args[0], args[1], ... is or where I can find a description?

**Comment by glenn-jocher** [comment]
@Shakesbeer333 these are arguments you would pass to the module. i.e. `nn.BatchNorm2d(128)`

**Comment by Shakesbeer333** [comment]
@glenn-jocher my question was a little bit vague. I retry:

`[-1, 1, nn.Conv2d, [128, 3, 2]` becomes `torch.nn.modules.conv.Conv2d(c1=32, c2=64, k=3, s=2)`

I don't understand how args[0] = 128 translates into c1=32, c2=64

**Comment by glenn-jocher** [comment]
@Shakesbeer333 YOLOv5 models are compound scaled in depth and width as shown in yaml comments:
https://github.com/ultralytics/yolov5/blob/187f7c2ed16b9eb9754b28e7b0aa397f908155aa/models/yolov5s.yaml#L1-L5

**Comment by Shakesbeer333** [comment]
@glenn-jocher aweseome! Thank you so much for taking time to answer my questions! I really appreciate it

**Comment by xoryouyou** [comment]
@Shakesbeer333 any success implementing a ResNet backbone ?

**Comment by Shakesbeer333** [comment]
@xoryouyou I'm working on it atm but but due to my inexperience it takes some time. I'll let you know if I got something useful. In the meantime let me know if you got anything.

**Comment by Shakesbeer333** [comment]
@xoryouyou I used see [@FrancescoSaverioZuppichini 's ResNet implementation ](https://github.com/FrancescoSaverioZuppichini/ResNet). ResNet18 runs without error (I didn't check any performance yet) however the other ResNet versions through an error.

**Comment by xoryouyou** [comment]
@Shakesbeer333  No I haven't seen it. Thanks for the link! I'll give it a spin once my machine is finished training my current yolov5x net. 

Edit: looks like pytorch vision already features all we need https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py

**Comment by Shakesbeer333** [comment]
@xoryouyou yes we got all we need! However, I was facing tensor shape problems when connecting it to the head.

**Comment by AsatledFish** [comment]
> @xoryouyou yes we got all we need! However, I was facing tensor shape problems when connecting it to the head.

hello,when i use mobilenet as backbone.RuntimeError: Sizes of tensors must match except in dimension 1. Got 32 and 16 in dimension 2 (The offending index is 1)

**Comment by Radleye** [comment]
> > @xoryouyou yes we got all we need! However, I was facing tensor shape problems when connecting it to the head.
> 
> hello,when i use mobilenet as backbone.RuntimeError: Sizes of tensors must match except in dimension 1. Got 32 and 16 in dimension 2 (The offending index is 1)

hi,I met same problem,do you solve it?

**Comment by AsatledFish** [comment]
> > > @xoryouyou是的，我们得到了我们所需要的！但是，将其连接到头部时，我遇到了张量形状问题。
> > 
> > 
> > 你好，当我使用mobilenet作为骨干网时。RuntimeError：张量的大小必须匹配，但维度1除外。在维度2中得到32和16（有问题的索引为1）
> 
> 嗨，我遇到了同样的问题，你解决了吗？
能训练了 你可以参考这个改一下head  https://mp.weixin.qq.com/s/G-Xeenf6kzdkZYkshL1mrg

**Comment by quhaohao** [comment]
> 用mobilenet作为骨干网时。RuntimeError：张量的大小必须匹配，但维度1除外。在维度2中得到32和16（有问题的索引为1）

我参考这个去做，出现了问题

**Comment by larrywal-express** [comment]
any news about ResNet implementation?

**Comment by jinik21** [comment]
hello,when i use darknet53 as backbone.RuntimeError: Sizes of tensors must match except in dimension 1. Got 32 and 16 in dimension 2 (The offending index is 1)

**Comment by glenn-jocher** [comment]
@jinik21 👋 hi, thanks for letting us know about this problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

* ✅ **Minimal** – Use as little code as possible that still produces the same problem
* ✅ **Complete** – Provide **all** parts someone else needs to reproduce your problem in the question itself
* ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

In addition to the above requirements, for [Ultralytics](https://ultralytics.com/) to provide assistance your code should be:

* ✅ **Current** – Verify that your code is up-to-date with current GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been resolved by previous commits.
* ✅ **Unmodified** – Your problem must be reproducible without any modifications to the codebase in this repository. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all of the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) and providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by lana211191** [comment]
> > > > @xoryouyou yes we got what we needed! However, when connecting it to the head, I'm having issues with the shape of the tensor.
> > > 
> > > 
> > > hello when i use mobilenet as backbone. RuntimeError: Sizes of tensors must match, except for dimension 1. get 32 ​​and 16 in dimension 2 (the index in question is 1)
> > 
> > 
> > Hi, I have the same problem, did you solve it? 
> > After training, you can refer to this to change the head   https://mp.weixin.qq.com/s/G-Xeenf6kzdkZYkshL1mrg

hello did you find a solution for your problem ?

**Comment by mehdi-khalaj** [comment]
Hi Friends,
Do you have any news about ResNet implementation?

The  following link contains some classes which give us the Resnet weights. then how to create a resnet50.yaml file instead of the current yolov5x .yaml (for example) and the use resnet50.yaml in the training process?

can we do this just by creating an object of the related class in the following link?

https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py

Thank you

**Comment by glenn-jocher** [comment]
@mek651 if you are running classify tasks then you should be able to train a torchvision model directly with ultralytics, i.e.:

```
yolo classify train model=resnet50 data=mnist
```

**Comment by mehdi-khalaj** [comment]
> @mek651 if you are running classify tasks then you should be able to train a torchvision model directly with ultralytics, i.e.:
> 
> ```
> yolo classify train model=resnet50 data=mnist
> ```

What about the object detection tasks?

**Comment by glenn-jocher** [comment]
@mek651 object detection models must either be *.pt or *.yaml for training, or any export format (i.e. CoreML, TFLite, ONNX, etc.) for predict and val.

**Comment by MJRcreator** [comment]
can some help me to integrate resnet50 as feature extractor of yolov5 architecture. i am running it in googlecolab with T4 GPU since cant find one that helps me modify the yaml file to integrate resnet50 as feature extractor for yolov5 architechture.

**Comment by pderrenger** [comment]
请检查您的模型配置，确保输出通道与YOLOv5的head部分匹配。您可能需要调整特征图的尺寸。

**Comment by MJRcreator** [comment]
@pderrenger can you please guide me how to integrate resnet50 as feature extractor in yolov5 architechture and i also clone yolov5 github repo. i am a little bit loss on how can i change the backbone of the yolov5 to have better feature extractor. can you please help me specifically on the code if you will. thank you very much.

**Comment by pderrenger** [comment]
@quhaohao 请确保调整网络的输入和输出通道以匹配YOLOv5的head。可以参考YOLOv5的现有结构来解决张量形状不匹配的问题。

**Comment by MJRcreator** [comment]
Can you please provide me an initial yaml file or code for yolo.py to integrate resnet50 as feature extractor for yolov5 architechture?

**Comment by pderrenger** [comment]
请检查您的模型配置，确保输出特征图的尺寸与检测头的输入要求匹配。您可能需要调整特征图的通道或尺寸。

**Comment by MJRcreator** [comment]
can you please show me the integration of resnet50 as feature extractor to yolov5? since i am having a lot of errors

**Comment by pderrenger** [comment]
请确保您的特征图尺寸在连接到头部时匹配。您可能需要调整网络层或使用适当的上采样/下采样方法。查看相关的实现细节可能会有所帮助。

**Comment by pderrenger** [comment]
@quhaohao 请确保调整网络的输入和输出通道以匹配YOLOv5的head。您可能需要修改head的配置以适应MobileNet的输出。

**Comment by pderrenger** [comment]
请确保您的模型配置与MobileNet的输出特征图尺寸匹配。您可能需要调整YOLOv5的head部分以适应不同的输入尺寸。

**Comment by pderrenger** [comment]
It seems like a tensor shape mismatch issue. Ensure that the feature maps from the backbone match the expected input dimensions of the head. You may need to adjust the layers or use an adapter layer to align the dimensions.
