### ISSUE TITLE
Error running python detect.py --visualize

### ISSUE THREAD

**Issue by ys31jp** [ultralytics/yolov5#5503]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

python detect.py --visualize

image 1/1 E:\Documents\yolov5_ver6_no_modify\yolov5-master\data\data_remove\image.jpg: Saving runs\detect\exp6\image\stage0_Conv_features.png... (32/32)
Traceback (most recent call last):
  File "detect.py", line 307, in <module>
    main(opt)
  File "detect.py", line 302, in main
    run(**vars(opt))
  File "E:\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 151, in run
    pred = model(img, augment=augment, visualize=visualize)[0]
  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\models\yolo.py", line 152, in _forward_once
    feature_visualization(x, m.type, m.i, save_dir=visualize)
  File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\utils\plots.py", line 446, in feature_visualization
    plt.savefig(save_dir / f, dpi=300, bbox_inches='tight')
  File "E:\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\matplotlib\figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "E:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "E:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "E:\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "E:\anaconda3\lib\site-packages\matplotlib\image.py", line 1605, in imsave
    image.save(fname, **pil_kwargs)
  File "E:\anaconda3\lib\site-packages\PIL\Image.py", line 2148, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\detect\\exp6\\image\\stage0_Conv_features.png'

Hi, I have this error when I run detect.py --visualize.
Any ideas why I have this error?

**Comment by glenn-jocher** [comment]
@ys31jp 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've tried to reproduce this issue but everything works correctly for us using your commands:

<img width="1737" alt="Screen Shot 2021-11-04 at 3 43 45 PM" src="https://user-images.githubusercontent.com/26833433/140334842-1d73c31d-b982-49b7-86d0-1768e715ed0c.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@ys31jp 
It may be a path problem in the windows operating system, so you should modify it appropriately. This does not exist on Mac and Linux.

**Comment by ys31jp** [comment]
Hi, thanks for prompt response. I test again. If I test with 
python detect.py --visualize --source data/image.jpg
It work and nothing issues.


However if I test with
python detect.py --visualize --source data/image_0123.fr0123.jpg
The error will occurs.

image 1/1 E:\Documents\yolov5_ver6_no_modify\yolov5-master\data\image.jpg: Saving runs\detect\exp6\image_0123.fr0123\stage0_Conv_features.png... (32/32)
Traceback (most recent call last):
File "detect.py", line 307, in
main(opt)
File "detect.py", line 302, in main
run(**vars(opt))
File "E:\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "detect.py", line 151, in run
pred = model(img, augment=augment, visualize=visualize)[0]
File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\models\yolo.py", line 126, in forward
return self._forward_once(x, profile, visualize) # single-scale inference, train
File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\models\yolo.py", line 152, in _forward_once
feature_visualization(x, m.type, m.i, save_dir=visualize)
File "E:\Documents\yolov5_ver6_no_modify\yolov5-master\utils\plots.py", line 446, in feature_visualization
plt.savefig(save_dir / f, dpi=300, bbox_inches='tight')
File "E:\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 859, in savefig
res = fig.savefig(*args, **kwargs)
File "E:\anaconda3\lib\site-packages\matplotlib\figure.py", line 2311, in savefig
self.canvas.print_figure(fname, **kwargs)
File "E:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2210, in print_figure
result = print_method(
File "E:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1639, in wrapper
return func(*args, **kwargs)
File "E:\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 510, in print_png
mpl.image.imsave(
File "E:\anaconda3\lib\site-packages\matplotlib\image.py", line 1605, in imsave
image.save(fname, **pil_kwargs)
File "E:\anaconda3\lib\site-packages\PIL\Image.py", line 2148, in save
fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'runs\detect\exp6\image_0123.fr0123\stage0_Conv_features.png'


#Zengyf-CVer Yes. It was due to the path issues. 
if the image name is image_0123.fr0123.jpg in both Window and Ubuntu, it will generate the same error. 

Because all of image name is somethings like this image_0123.fr0123. I have try to fixed this to check the feature map.
@glenn-jocher  I implement this to fixed the issues. In plots.py, feature_visualization line 446 - 448.
I do test on both image name (image.jpg & image_0123.fr0123.jpg) and it works.

![image](https://user-images.githubusercontent.com/83806490/140444237-c3d3ce6d-5416-4b54-8b6c-1fbef087e33d.png)

**Comment by Zengyf-CVer** [comment]
@ys31jp 
Try to avoid the decimal point "." in the image name:
image_0123.fr0123.jpg

**Comment by ys31jp** [comment]
> @ys31jp Try to avoid the decimal point "." in the image name: image_0123.fr0123.jpg

I cant. I have few k of dataset images with the ".". Which impossible for me to avoid.

**Comment by glenn-jocher** [comment]
@ys31jp can you please submit a Pull Request with your fix to help other users? Thanks!

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by glenn-jocher** [comment]
@ys31jp good news 😃! Your original issue may now be fixed ✅ in PR #5518. This PR updates `increment_path()` to correctly handle multi-suffix filenames.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by ys31jp** [comment]
Hi @glenn-jocher I've pull request for this issues. Not sure am I do it correctly. Thanks for the response. Thanks for your team too.
