### ISSUE TITLE
When use detect.py to detect from video raised exeption

### ISSUE THREAD

**Issue by lavrenkov-sketch** [ultralytics/yolov5#5522]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

 python3 detect.py --source **any video mp4 or avi file**
raized exception:
in yolov5 5 relese this work
>  detect: weights=yolov5s.pt, source=termo1.avi, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
> YOLOv5 🚀 v6.0-60-gbcc085d torch 1.9.0+cu102 CUDA:0 (NVIDIA GeForce GTX 1650, 3878MiB)
> 
> Fusing layers... 
> Model Summary: 213 layers, 7225885 parameters, 0 gradients
> Traceback (most recent call last):
>   File "/home/lavrenkovnv/GITLAB/yolov5/detect.py", line 314, in <module>
>     main(opt)
>   File "/home/lavrenkovnv/GITLAB/yolov5/detect.py", line 309, in main
>     run(**vars(opt))
>   File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/lavrenkovnv/GITLAB/yolov5/detect.py", line 265, in run
>     t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
>   File "/home/lavrenkovnv/GITLAB/yolov5/detect.py", line 265, in <genexpr>
>     t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
> ZeroDivisionError: float division by zero

### Environment

Latest Yolo
ubuntu 21.04
python 3.9

### Minimal Reproducible Example

 python3 detect.py --source **any video mp4 file**

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lavrenkov-sketch 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I am not able to reproduce any video problem with detect.py in our Colab notebook:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb
```python
!python detect.py --source https://ultralytics.com/assets/decelera_landscape.mov
```

<img width="1360" alt="Screenshot 2021-11-05 at 15 53 15" src="https://user-images.githubusercontent.com/26833433/140530745-8f290870-be7a-42ea-9aad-de6eba50c176.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@lavrenkov-sketch 
The reason for your problem is that `seen` has a 0 and the divisor cannot be 0. So the original cause of this problem is this line of code:
https://github.com/ultralytics/yolov5/blob/853505339a789e78791e332c08091fb9333c4b72/detect.py#L265
Then look up and find that this `seen` does not enter the loop, indicating that no object was detected and `pred` is empty.
https://github.com/ultralytics/yolov5/blob/853505339a789e78791e332c08091fb9333c4b72/detect.py#L197-L198

**Comment by Ephil012** [comment]
I am also having this issue. If no object is detected then shouldn't it just try processing the video like normal and say there is no object here? Why does it fail if there is nothing detected? For instance, in my use case some of the detected objects will appear and disappear in my footage. As a result, I cannot run any detection on it simply because of this issue. I think this behavior seems a bit odd.

**Comment by glenn-jocher** [comment]
@Ephil012 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Ephil012** [comment]
I ended up fixing it. Turns out it was just an improper installation of some of the python packages because of package conflicts with Anaconda. Not sure which one specifically though, but using a virtual environment instead of Anaconda fixed it.
