### ISSUE TITLE
fl_gamma validation times

### ISSUE THREAD

**Issue by JiaLim98** [ultralytics/yolov5#553]
Hi @glenn-jocher 

## ❔Question
Previously I can train YOLOv5s with fl_gamma = 1.5 and not much difference in train and validate duration. I am now training YOLOv5x with focal loss of fl_gamma = 2.0 and here is my training console.
![image](https://user-images.githubusercontent.com/66768413/88863463-85510300-d235-11ea-8af4-2c2abfe42f6d.png)
I wonder why it takes 24 minutes for validation at every epoch. Can you explain a little bit or perhaps even better, any ways that can shorten the duration?

Regards,
JiaLim98

**Comment by glenn-jocher** [comment]
@JiaLim98 fl_gamma is a very dangerous parameter, increasing it will drastically push precision down and recall up. Lower precision means many more false positives. Your validation is slow because your model is producing tens of thousands of false positives per image, all of which need to pass through NMS.

"Solution" would be to leave the hyperparameters alone unless you really know what you are doing.

**Comment by glenn-jocher** [comment]
Validation times for this repository for YOLOv5x using a V100 are about 70-80 seconds on COCO for all 5000 val2017 images.

<img width="1574" alt="Screen Shot 2020-07-29 at 4 56 06 PM" src="https://user-images.githubusercontent.com/26833433/88865372-93167200-d1bc-11ea-869e-3fd56dc196c7.png">

**Comment by JiaLim98** [comment]
@glenn-jocher Thank you so much for the clear explanation~

**Comment by Zhangmaopeng88** [comment]
fl_gamma is a very dangerous parameter, thanks for your explain and actually now I am also try to tuning it for my yolov5 to detect the vehicles(cars, drucks, like that)

**Comment by yuyang3478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by glenn-jocher** [comment]
@yuyang3478 感谢您对YOLOv5的兴趣！调整fl_gamma或许可以提高在检测车辆等目标时的性能，但请确保在调整超参数时保持谨慎。希望您过个愉快的假期，期待您的回复后我们继续讨论。
