### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead

### ISSUE THREAD

**Issue by gzy19990617** [ultralytics/yolov5#5550]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead

### Additional

Using yoloV5, train.py, I encountered this problem. I don't know how to solve it. Please ask for help

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by omkarp1013** [comment]
I have also gotten the same error:
RuntimeError: Given groups=1, weight of size [1, 36, 1, 1], expected input[1, 320, 32, 32] to have 36 channels, but got 320 channels instead

**Comment by glenn-jocher** [comment]
@pathmarkoak @gzy19990617 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by omkarp1013** [comment]
@glenn-jocher thank you for the response. I am using a custom dataset and am using this command to run my code: 

`!python train.py --img 640 --batch 2 --epochs 30 --data /content/yolov5/data/data.yaml --cfg /content/yolov5/models/yolov5x.yaml --weights /content/yolov5/weights/yolov5x.pt --name yolov5x_data --cache`

My dataset is in YOLO format (train/val images and labels that are .txt files), I am on Google Colaboratory, and I am using a GPU. I am making a bug report, as I do believe my dataset meets these criteria.

**Comment by glenn-jocher** [comment]
@pathmarkoak thanks! Since we don't have access to your custom data, can you send us a reproducible example on a common dataset like COCO128, COCO, VOC, etc. so we can reproduce the error here?

**Comment by omkarp1013** [comment]
Have done so in the bug report, thank you!

**Comment by omkarp1013** [comment]
@gzy19990617 have you found a solution? Please let me know if you have, I would really appreciate it!

**Comment by gzy19990617** [comment]
> @gzy19990617 have you found a solution? Please let me know if you have, I would really appreciate it!
<img width="1007" alt="截屏2021-11-08 下午5 31 32" src="https://user-images.githubusercontent.com/88373061/140717560-ccf60602-d4cc-4b24-a33b-d456eb478f14.png">
You can modify the default parameters of train.py to solve this problem.This means that a new weight file is trained like the yaml file provided. If the default weigth file is used, an error will be reported

**Comment by gzy19990617** [comment]
> @pathmarkoak @gzy19990617 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

thank you for the response！I have solved.

**Comment by omkarp1013** [comment]
@gzy19990617 thank you! What default parameters in train.py did you modify (was it `help = 'initial weights path'`?) For me, the issue was that I was using an outdated yolov5 configuration file, so I simply downloaded the latest one and used that for training.
