### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead

### ISSUE THREAD

**Issue by omkarp1013** [ultralytics/yolov5#5551]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/43706200/140653929-4367e46a-d694-4b1b-aa4c-16807bbc44b3.png)

Am receiving this error while training.

### Environment

YOLO: YOLOv5 v6.0-67-g60e42e1 torch1.9.0+cu111 CUDA:0 (K80 - 12 GB)
OS: Ubuntu 16.04
Python 3.9.0

### Minimal Reproducible Example

```
!python train.py --img 640 --batch 2 --epochs 30 --data /content/yolov5/data/data.yaml --cfg /content/yolov5/models/yolov5x.yaml --weights /content/yolov5/weights/yolov5x.pt --name yolov5x_data --cache
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pathmarkoak thanks for the bug report. I am not able to reproduce your error using a common dataset (COCO128 in this case). If your error is not reproducible on a common dataset like COCO128, VOC, GlobalWheat2020 etc, then it likely originates in your custom dataset. 

<img width="1937" alt="Screenshot 2021-11-07 at 17 55 16" src="https://user-images.githubusercontent.com/26833433/140654233-88e0239c-fafa-4d7a-80ed-522c53d802b6.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by omkarp1013** [comment]
@glenn-jocher thank you for the reply. I have reproduced this error with the COCO128 dataset as well. The code I used was:

```
!python train.py --img 336 --batch 4 --epochs 30 --data /content/yolov5/data/coco128.yaml --cfg /content/yolov5/models/yolov5x.yaml --weights /content/yolov5/weights/yolov5x.pt --name yolov5x_coco128 --cache
```

![image](https://user-images.githubusercontent.com/43706200/140655818-f42b33cd-65a6-4660-8c7a-0ff4e689ae60.png)

By any chance, does "groups" refer to the number of classes? I am not sure if I should change "groups=1" to the number of groups I have in some file.

**Comment by glenn-jocher** [comment]
@pathmarkoak your error is not reproducible. I ran your command in a Colab notebook after Setup cell, and everything works correctly:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1830" alt="Screenshot 2021-11-07 at 23 00 05" src="https://user-images.githubusercontent.com/26833433/140663378-d8d854d9-eda4-414d-b10c-84c77926d26c.png">

**Comment by Zengyf-CVer** [comment]
@pathmarkoak 
Your question has some shortcomings:
First of all, have you changed the yolov5 configuration file?
Secondly, your Ubuntu system version is too low.
Finally, a very strange thing is that the Python version you wrote is 3.9, but your screenshot is 3.7.
I hope you will make the above points clear.

**Comment by omkarp1013** [comment]
@glenn-jocher @Zengyf-CVer thank you both for your comments. I believe I have resolved the issue by editing the proper YOLOv5 YAML file. Thank you! Just to clarify, I believe my Python is 3.7, after looking at my screenshot. Not sure what my Ubuntu system version is, but I will update if I get a chance and it is necessary.

**Comment by Guorong-He** [comment]
@pathmarkoak  Hello, could you please tell me in detail how to solve this error, because my Yolov5 also has the same error.

**Comment by glenn-jocher** [comment]
@Guorong-He 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by omkarp1013** [comment]
@Guorong-He thank you for reaching out. What I did was create a new .yaml file containing the yolov5 configurations, and I copied/pasted the contents of the .yaml file in this GitHub repository (most updated one) in this file. Using the new file worked for me and solved the issue.

**Comment by Guorong-He** [comment]
@pathmarkoak Thank you so much for your comment, your reply is very helpful to me.

**Comment by omkarp1013** [comment]
@Guorong-He you are welcome. Please feel free to reply if you need any other help with this issue.

**Comment by Red-scarf-0317** [comment]
When I am running Yolo V5 version 5.0, this error occurs. I don't know why? I changed version 5.0 and I won't make mistakes

**Comment by PhilipRS892** [comment]
When I am running Yolo V5 version 5.0, this error occurs. I don't know why? I changed to version 6.0, and this error did not occur again

**Comment by omkarp1013** [comment]
@Red-scarf-0317 yeah, I'm not too sure about that error. I would say in any repository for any model, use the latest version of all files, as that is what the authors will most likely refer to in their documentation.

**Comment by PhilipRS892** [comment]
Thank you for your reply! It's really helpful to me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月21日(星期天) 上午6:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/yolov5] RuntimeError: Given groups=1, weight of size [512, 1024, 1, 1], expected input[1, 512, 8, 8] to have 1024 channels, but got 512 channels instead (Issue #5551)





 
@Red-scarf-0317 yeah, I'm not too sure about that error. I would say in any repository for any model, use the latest version of all files, as that is what the authors will most likely refer to in their documentation.
