### ISSUE TITLE
Train on images with different intensity range

### ISSUE THREAD

**Issue by Karol-G** [ultralytics/yolov5#5566]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I want to use YOLOv5 to train on a medical X-ray dataset (https://node21.grand-challenge.org/Home/).
Medical images have a so called Hounsfield Scaling for the intensities with a range of [-1000, 30000] different to the natural image intensity scaling of [0, 255].

This is largely not a problem and your code was easy to adapt for the most part except for the mosaic functions in dataset.py (load_mosaic and load_mosaic9).
It seems to me that they depend on the [0, 255] scale aka that it is hardcoded into the functions. I don't understand the functions entirely, but it seems that in the line `img4 = np.full((s * 2, s * 2, img.shape[2]), 114, dtype=np.uint8)  # base image with 4 tiles` the number `114` comes from the [0, 255] scale. 

Is that the only dependency to the [0, 255] scale or are there more? 
What would I need to change to generalize both functions?

Best
Karol

**Comment by glenn-jocher** [comment]
@Karol-G it's not so much a scaling as a datatype issue. Imagery dataloaders try to handle all image ops natively as uint8 datatypes, for fastest speeds and lowest memory utilization. uint8 has 256 integers between 0 and 255. 

When utilized for training these inputs are first converted to floats and then rescaled to 0-1 by dividing by 255. If you are looking for more granularity you might create a uint16 dataloader, which will give you 2 ** 16 levels rather than 2 ** 8.

I don't think this is something we'd want to parameterize as larger datatypes would bring speed and memory compromises that most users shouldn't be subject to, and the technical details are murky in my mind, but if you find an easy method please submit a PR for consideration. Thanks!

**Comment by Karol-G** [comment]
Thanks for the clarification! But still, what is the purpose of the fill value 114 here?
Its is not the half of 255, which is 127, but slightly less. How do I generalize this value to a new intensity range?

https://github.com/ultralytics/yolov5/blob/79bca2bf64da04e7e1e74a132eb54171f41638cc/utils/datasets.py#L692

**Comment by glenn-jocher** [comment]
@Karol-G 114 is imagenet mean value. 

See https://numpy.org/doc/stable/user/basics.types.html for details

**Comment by Karol-G** [comment]
Ah, now I understand. Thanks again!
