### ISSUE TITLE
performance when training each class separately, as compared with multi-class

### ISSUE THREAD

**Issue by drorlederman** [ultralytics/yolov5#5601]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I have a dataset of photos with two classes. Around 5,000 images&instances for the first class, and more than 10,000 for the second. 
I've done two experiments: in the first experiment, I train each class separately and got around 94% mAP. 
In the second experiment, I trained both classes together but got around 80% mAP. 
Any idea what could be the reason?
Thanks,
Dror

**Comment by glenn-jocher** [comment]
@drorlederman according to your assumptions, as the number of classes a model has to detect trends towards infinity, the performance on each class should... stay the same?

**Comment by drorlederman** [comment]
> @drorlederman according to your assumptions, as the number of classes a model has to detect trends towards infinity, the performance on each class should... stay the same?

@glenn-jocher
Thanks for the quick reply.
Are you saying the difference in results sounds reasonble? I understand that performance might decrease with the number of models. Still, a such a difference seems too high, and I'm afraid I'm doing something wrong.

**Comment by glenn-jocher** [comment]
@drorlederman well, there's no 'right answer' here. Qualitatively speaking if you double the task count (model has to do 2 things instead of 1) with the same resources the performance on each task will reduce. 

Quantitatively the value of the reduction is impossible to estimate, the empirical results themselves are the answer. Especially across different domains, datasets, models etc, the only sanity check we really have is that you are seeing no errors and your trained models are detecting objects.

**Comment by glenn-jocher** [comment]
@drorlederman BTW this is not unique to AI. If a college student has to study for 2 exams on monday vs 1 exam, he will also likely do worse. How much worse is not a question anyone can answer apriori.
