### ISSUE TITLE
validation result  is error

### ISSUE THREAD

**Issue by mutouoa** [ultralytics/yolov5#5620]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/20034831/141398177-d92597c2-693c-44b5-a29f-cc747b0c96b2.png)

**Comment by mutouoa** [comment]
@cgerum

**Comment by glenn-jocher** [comment]
@mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.

**Comment by mutouoa** [comment]
> @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.

My gpu is RTX3090 and does not support versions below cuda 11.

**Comment by mutouoa** [comment]
> @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.



> @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.



> > @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.
> 
> My gpu is RTX3090 and does not support versions below cuda 11.

@glenn-jocher

**Comment by mutouoa** [comment]
> @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.

@glenn-jocher My gpu is RTX3090 and does not support versions below cuda 11.

**Comment by mutouoa** [comment]
> @mutouoa some CUDA 11 installations cause problems with PyTorch. You should try your command without --half, and if that doesn't work install CUDA 10 and PyTorch again.

@glenn-jocher I got the same error result using CPU

**Comment by glenn-jocher** [comment]
@mutouoa 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ZhouBay-TF** [comment]
hello，Have you solved this problem?
How do I test my accuracy？
![image](https://user-images.githubusercontent.com/38548235/142341937-c004b510-ba53-4115-b1bf-c428f47d315d.png)

**Comment by xinkangzhou** [comment]
When I set task = "train" in val.py
![image](https://user-images.githubusercontent.com/38548235/142345188-0d7d39e1-6d2b-48d4-b9a4-3fc20964814d.png)
This is the result I want

**Comment by glenn-jocher** [comment]
@xinkangzhou you've validated your model correctly, the results are zero mAP.
