### ISSUE TITLE
Low mAP with pycocotools

### ISSUE THREAD

**Issue by GuoQuanhao** [ultralytics/yolov5#5640]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question
```
(pytorch1.9.0) C:\Users\Administrator\Downloads\yolov5-master>python val.py --img 640  --data ./data/coco.yaml --weights yolov5s.pt
val: data=./data/coco.yaml, weights=['yolov5s.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs\val, name=exp, exist_ok=False, half=False
YOLOv5  2021-11-2 torch 1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24576.0MB)

Fusing layers...
Model Summary: 213 layers, 7225885 parameters, 0 gradients
val: Scanning 'E:\YOLOv4\Data\coco\val2017.cache' images and labels... 4952 found, 48 missing, 0 empty, 0 corrupted: 100%|██████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [01:03<00:00,  2.48it/s]
                 all       5000      36335      0.678      0.502      0.557      0.361
Speed: 0.1ms pre-process, 1.7ms inference, 1.5ms NMS per image at shape (32, 3, 640, 640)

Evaluating pycocotools mAP... saving runs\val\exp18\yolov5s_predictions.json...
loading annotations into memory...
Done (t=0.64s)
creating index...
index created!
Loading and preparing results...
DONE (t=4.05s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=23.19s).
Accumulating evaluation results...
DONE (t=10.21s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.093
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.117
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.151
Results saved to runs\val\exp18
```

**Comment by GuoQuanhao** [comment]
It's my fault, I set is_coco=False, I got right mAP

**Comment by wangziren1** [comment]
It is not your fault but a bug.  
"is_coco = isinstance(data.get('val'), str) and data['val'].endswith('coco/val2017.txt')  # COCO dataset" in val.py conflicts with "val: val2017.txt  # val images (relative to 'path') 5000 images" in coco.yaml.

**Comment by glenn-jocher** [comment]
@wangziren1 @GuoQuanhao the processing in check_dataset():
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/val.py#L141-L143

will connect the dataset root to each of the sets so that coco val set:
https://github.com/ultralytics/yolov5/blob/db6ec66a602a0b64a7db1711acd064eda5daf2b3/data/coco.yaml#L10-L15

turns into `data['val'] = '../datasets/coco/val2017.txt'`

**Comment by wangziren1** [comment]
Thank you for fast replay.

**Comment by engrjav** [comment]
@GuoQuanhao  i am still getting same issue with low mAp on COCO. Where did you set is_coco=true?

**Comment by engrjav** [comment]
@glenn-jocher  i am facing same issue on YOLO v5. i have spent nearly two weeks and did every possible thing but still my coco metrics evaluation on custom dataset gives very low AP than the overall mAP on custom dataset 

My input images are 416x416 and YOLOv5 resizes it to 640x640. My coco anotations are also for 416x416 so while testing i even changed the image size and ioU threshold still after pycocotool evaluates, i get mAP not more than 0.006 for APs, APm and APl for all classes where my over all mAP is 0.574 for my custom dataset before save_json command is executed

**Comment by glenn-jocher** [comment]
@engrjav 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by shenhaibb** [comment]
> My input images are 416x416 and YOLOv5 resizes it to 640x640. My coco anotations are also for 416x416 so while testing i even changed the image size and ioU threshold still after pycocotool evaluates, i get mAP not more than 0.006 for APs, APm and APl for all classes where my over all mAP is 0.574 for my custom dataset before save_json command is executed

so do i, did u solve it??

**Comment by glenn-jocher** [comment]
@shenhaibb for accurate troubleshooting support, please follow the guidelines provided above to create a minimal, reproducible example. This will help us to effectively diagnose and assist with the issue. Thank you!
