### ISSUE TITLE
url of downloading font does NOT work

### ISSUE THREAD

**Issue by JiananAlvin** [ultralytics/yolov5#5643]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

url of downloading font 'https://ultralytics.com/assets/' does NOT work.

### Minimal Reproducible Example

def check_font(font='Arial.ttf', size=10):
    # Return a PIL TrueType Font, downloading to CONFIG_DIR if necessary
    font = Path(font)
    font = font if font.exists() else (CONFIG_DIR / font.name)
    try:
        return ImageFont.truetype(str(font) if font.exists() else font.name, size)
    except Exception as e:  # download if missing
        **url = "https://ultralytics.com/assets/" + font.name**
        print(f'Downloading {url} to {font}...')
        torch.hub.download_url_to_file(url, str(font), progress=False)
        try:
            return ImageFont.truetype(str(font), size)
        except TypeError:
            check_requirements('Pillow>=8.4.0')  # known issue https://github.com/ultralytics/yolov5/issues/5374

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JiananAlvin thank you for your bug report! I tried to reproduce but everything seems to be working normally now. I can download manually from https://ultralytics.com/assets/Arial.ttf and the auto-download steps are also able to download correctly. Perhaps there temporary network issues, can you try again to see if the issue remains?

**Comment by ducthinh993** [comment]
Hi guys, sorry to jump in the middle but I have a problem with this function as well. Our service was deployed in no internet allowable so that I would like to download and copy to a suitable path but i don't know where.

Thanks

**Comment by glenn-jocher** [comment]
@ducthinh993 fonts are downloaded to user config /Ultralytics directory. The path is printed to console on download attempt.

**Comment by mohammad69h94** [comment]
> @ducthinh993 fonts are downloaded to user config /Ultralytics directory. The path is printed to console on download attempt.

My Os is windows and while Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...  in consol it shows error :
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

though in windows does not exist /root/.config/

Do you have any idea what should I do?

**Comment by glenn-jocher** [comment]
@mohammad69h94 all Windows operations are correctly working in Github CI tests. See https://github.com/ultralytics/yolov5/runs/4576971073?check_suite_focus=true

<img width="1542" alt="Screen Shot 2021-12-20 at 3 17 23 PM" src="https://user-images.githubusercontent.com/26833433/146781127-18d0c151-61ed-4a18-bcff-ea1376b744ad.png">

**Comment by mohammad69h94** [comment]
> 

But even if I get fresh download with torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True), it shows:
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip

I cannot find /root/.cache/torch/hub/master.zip directory

 Of course, I will add this that I want to use .onnx file same as:
torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s.onnx')

**Comment by glenn-jocher** [comment]
@mohammad69h94 YOLOv5 PyTorch Hub ONNX inference works correctly in my test:

<img width="1281" alt="Screen Shot 2021-12-20 at 4 34 07 PM" src="https://user-images.githubusercontent.com/26833433/146792730-939605b4-1cb0-4799-b602-94b0d0709d8b.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
