### ISSUE TITLE
Multiclass trained model only predicts one class in inference always

### ISSUE THREAD

**Issue by mobassir94** [ultralytics/yolov5#5662]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

i have these 3 classes in my dataset : names: ["name","age","mobile"] 
but during inference it always predics 'name' for all 3 fields for all images, check the last visualized image here for better understanding : https://colab.research.google.com/drive/1Pyz5hCi0fpmQ4lFV9rvAcdMp2yg9KN1P#scrollTo=ogZdrD4OY2Wg
this same question was asked before here : https://github.com/ultralytics/yolov5/issues/3641 but no solution yet for this,so reposting

### Environment

tried both in colab and locally in ubuntu using rtx 3090 and also in kaggle,this same issue persist everywhere.

### Minimal Reproducible Example

i think this code is run able for you : https://colab.research.google.com/drive/1Pyz5hCi0fpmQ4lFV9rvAcdMp2yg9KN1P#scrollTo=ogZdrD4OY2Wg for reproducing this issue,,,here is the dataset : https://www.kaggle.com/riadhossainapsis/apsis-yolo-training-data?select=data   

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mobassir94 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem. We don't provide support for custom code or custom notebooks, but if you find an error with YOLOv5 on a common dataset like COCO128, VOC, Argoverse etc. please let us know.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by iceisfun** [comment]
@mobassir94 I would recommend you review https://docs.ultralytics.com/guides/model-training-tips/

I do a similar thing with yolov5 where I find which check boxes are checked on a form with very good success.

Try to get above 1000 samples per class, a uniform number of samples, background images and a good distribution of input images that represent what you will be seeing in the real world with real cameras.

**Comment by mobassir94** [comment]
@iceisfun my model is already performing well,but the problem is it is always showing name of first class as shown in the last visualized image in this baseline code that i tried : https://colab.research.google.com/drive/1Pyz5hCi0fpmQ4lFV9rvAcdMp2yg9KN1P#scrollTo=ogZdrD4OY2Wg
if you see the last image from that link,you will see that the algorithm is able to detect all 3 text regions with good accuracy but it is treating all those 3 labels as "name" label which is wrong,,i am seeking for a solution of this issue

**Comment by iceisfun** [comment]
@mobassir94 what is showing up in the confusion matrix?

**Comment by mobassir94** [comment]
@iceisfun i can't see the confusion matrix plot image after getting this error

**Comment by radilman** [comment]
In your yaml file try using single quote vs double quote, i.e., names: ['name','age','mobile']

**Comment by mobassir94** [comment]
@radilman yeah tried that too,no luck with ['name','age','mobile']

**Comment by awsaf49** [comment]
@glenn-jocher @mobassir94 Hi, I think I found the problem. While creating the labels for YOLOv5 `classes` column was also got divided by `1024` which created all the classes `~0` hence that error. So I replaced following codes,
```python3
row= mini[['classes', 'x_center','y_center','w','h']].astype(float).values
row= row/1024
```
Here's a simple fix,
```python3
classes = mini[['classes']].values.astype(int)
bboxes  = mini[['x_center','y_center','w','h']].astype(float).values
bboxes  = bboxes/1024
row = np.concatenate([classes, bboxes], axis=1)
row = row.astype(str)
```
Here are the plots after fix,
<img src="https://user-images.githubusercontent.com/36858976/146241121-f6a301d8-2b6f-4724-89e5-5f87570f972d.png" width=500>
<img src="https://user-images.githubusercontent.com/36858976/146241147-8a78ef7f-e0d6-409d-85b0-b33a2419537b.png" width=500>

**Comment by mobassir94** [comment]
apologies for this overlooked silly mistake and thanks a ton brother @awsaf49 for your kind help, it solves the problem, thanks
