### ISSUE TITLE
low GPU-util and high CPU-util

### ISSUE THREAD

**Issue by learncrazy** [ultralytics/yolov5#5681]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have a question about the training process. When I trained, I found that the GPU utilization of my computer was very low, and only in batch training did the gpu utilization increase instantaneously. It looks like the GPU is waiting for data to arrive during periods of low utilization. 
 Is this normal?

**Comment by glenn-jocher** [comment]
@learncrazy 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck and let us know if you have any other questions!

**Comment by learncrazy** [comment]
Thank you for your answer. The program is working properly and there is no problem with cuda out of mem. When I looked at GPU utilization using nvidia-smi, I found that the value of GPU-util was unstable, 90% in a while and 0% in a while. This means that the GPU is not being well utilized. The answer I found was that when the GPU-util value was 0, the program was waiting for training data.

**Comment by glenn-jocher** [comment]
@learncrazy yes that's correct. Low GPU utilization is a symptom of bottlenecks in the dataloader. Your images are not being read from your hard drive fast enough. You can try to cache your dataset:

```bash
python train.py --cache ram
python train.py --cache disk
```

**Comment by learncrazy** [comment]
@glenn-jocher Thank you for your answer. I got it.
