### ISSUE TITLE
Today I updated to last branch (git pull) and the script stopped working.

### ISSUE THREAD

**Issue by superalino** [ultralytics/yolov5#570]
branch is up to date with 'origin/master'.

## 🐛 Bug
It worked until the last update (today). When I launch detect.py the script ends with errors

On yolov3 branch I got no errors.

## To Reproduce (REQUIRED)
python3 detect.py --weights weights/yolov5x.pt --classes 0 --conf-thres 0.70 --img-size=608 --source "/dev/shm/xxx/diolupo2" --output "/dev/shm/xxx/diolupo3" > /tmp/xxx.log

Output:
Unable to init server: Could not connect: Connection refused
Unable to init server: Impossibile connettersi: Connection refused

(detect.py:8350): Gdk-CRITICAL **: 22:05:59.047: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.7/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 52, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scripts/yolov5/models/yolo.py", line 100, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/scripts/yolov5/models/yolo.py", line 120, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scripts/yolov5/models/yolo.py", line 27, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'm'

## Environment
Debian GNU/Linux 10 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    On   | 00000000:08:00.0  On |                  N/A |
| 58%   42C    P8     9W /  75W |     79MiB /  3911MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1138      G   /usr/lib/xorg/Xorg                            46MiB |
|    0      1632      G   /usr/bin/gnome-shell                          30MiB |
+-----------------------------------------------------------------------------+

**Comment by glenn-jocher** [comment]
@superalino it appears you have environment problems. In order to run YOLOv5 correctly your environment must meet  the minimum version requirements for the dependencies described in https://github.com/ultralytics/yolov5#requirements. You can either update your local environment to bring it into compliance or you can use one of our verified environment options below.

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by superalino** [comment]
My fault. 

Script started to work again after a "pip3 install -U -r requirements.txt"

**Comment by superalino** [comment]
pip3 install -U -r requirements.txt
