### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by jzod** [ultralytics/yolov5#5722]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

The following line of code:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
Produces this error in PyCharm:
Process finished with exit code -1073741819 (0xC0000005)

When I run from the command prompt it just exits with no code:
![cmd](https://user-images.githubusercontent.com/31077407/142651121-015ed606-8cf8-448f-b1de-902888a6697e.png)

### Environment

- Yolov5 - No CUDA, CPU only
- Windows 10 Enterprise Ver 20H2, Build 19042.1348
- Python 3.8
- Installed Packages from requirements.txt on GitHub:
- # pip install -r requirements.txt

# Base ----------------------------------------
matplotlib>=3.2.2
numpy>=1.18.5
opencv-python>=4.1.2
Pillow>=7.1.2
PyYAML>=5.3.1
requests>=2.23.0
torch>=1.7.0
torchvision>=0.8.1
tqdm>=4.41.0

# Logging -------------------------------------
# wandb

# Plotting ------------------------------------
pandas>=1.1.4
seaborn>=0.11.0

# Export --------------------------------------
# coremltools>=4.1  # CoreML export
# onnx>=1.9.0  # ONNX export
# onnx-simplifier>=0.3.6  # ONNX simplifier
# scikit-learn==0.19.2  # CoreML quantization
# tensorflow>=2.4.1  # TFLite export
# tensorflowjs>=3.9.0  # TF.js export

# Extras --------------------------------------
# albumentations>=1.0.3
# Cython  # for pycocotools https://github.com/cocodataset/cocoapi/issues/172
# pycocotools>=2.0  # COCO mAP
# roboflow
thop~=0.0.31.post2005241907

pip~=21.3.1
wheel~=0.37.0
setuptools~=59.1.1
Flask~=2.0.2
val~=0.6- 

### Minimal Reproducible Example

Here is the code:
![code](https://user-images.githubusercontent.com/31077407/142649642-6a18fd05-bf3d-4d23-b7ce-3ffdb4a5f384.JPG)

### Additional

I created a clean venv with Python 3.8.0 as it stated in the docs and I use PyCharm so I sync'd with the requirements.txt provided.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jzod 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm not able to reproduce any problems with your command in PyCharm on MacOS. In any case if this is reproducible with other torch hub repos then this may be a torch issue which should be raised at https://github.com/pytorch/pytorch

<img width="1479" alt="Screenshot 2021-11-20 at 12 35 29" src="https://user-images.githubusercontent.com/26833433/142724887-b594b348-e1d4-4991-a6c3-a89b3d6ca2c7.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by jzod** [comment]
I followed the same steps on another machine and it worked fine. I’m looking for some clues on what is causing this only on one machine. What could cause this error? I’m sure it not your code. 

Joe

**Comment by jzod** [comment]
I finally tracked down the problem to the version of Pillow I had in my venv. I had v9.0.1 and when I reverted to 7.1.2 it worked.

I would be interested in knowing why this worked.

**Comment by glenn-jocher** [comment]
@jzod see requirements:
https://github.com/ultralytics/yolov5/blob/3eef80457febcc4934e06b6f9f3e6efc115c66fc/requirements.txt#L7

**Comment by jzod** [comment]
Glenn, the requirements say > or = 7.1.2, not = 7.1.2.

**Comment by glenn-jocher** [comment]
@jzod ah got you, didn't read your message clearly. So you're saying there's a bug in current Pillow package? https://pypi.org/project/Pillow/

Should we exclude 9.0.1? i.e.:
```
Pillow>=7.1.2,<9.0.1
```

**Comment by glenn-jocher** [comment]
@jzod everything works correctly for me in Colab with Pillow==9.0.1. I'm unable to see any errors:
```python
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install Pillow==9.0.1
%pip install -qr requirements.txt  # install
```

**Comment by glenn-jocher** [comment]
@jzod Colab validation of Pillow==9.0.1 (restart runtime for install to take effect).

<img width="1845" alt="Screenshot 2022-02-12 at 14 24 47" src="https://user-images.githubusercontent.com/26833433/153713232-6291c559-ed14-442d-8bc3-437d2b408106.png">

**Comment by jzod** [comment]
Glenn,

Please see the test I ran. detect.py runs successfully with Pillow v7.1.2
and fails with v9.0.1. I only see the exit code -1073741819 when I run
detect.py within PyCharm. At the command prompt it just returns with
nothing. I have another machine and I have v9.0.1 installed with no issues.
There is something weird about this machine. I'm going to make the two
environments the same and see if this problem goes aways. It must be some
interaction with another package. FYI: I started by installing
requirements.txt in a new venv and that didn't work.
[image: Yolov5 Pillow Test.png]

**Comment by bladjiang** [comment]
@jzod thks.
it really works after i reinstalled pillow package!!! it's the pillow packege's problem.

pip uninstall pillow
pip install pillow
