### ISSUE TITLE
train and detect question 

### ISSUE THREAD

**Issue by china56321** [ultralytics/yolov5#575]
Hi, error happend when train and detect, i have tried many times,all eror are same, i don't know why this happend,could you help me solve this problem ? thank you ! ( i recloned the repo )
**training error:**
  File "train.py", line 47
    print(f'Hyperparameters {hyp}')
                                 ^
SyntaxError: invalid syntax

**detect eror :**
Traceback (most recent call last):
  File "detect.py", line 5, in <module>
    from models.experimental import *
  File "/home/make/yolov5/models/experimental.py", line 3, in <module>
    from models.common import *
  File "/home/make/yolov5/models/common.py", line 3, in <module>
    from utils.utils import *
  File "/home/make/yolov5/utils/utils.py", line 55
    last_list = glob.glob(f'{search_dir}/**/last*.pt', recursive=True)
                                                    ^
SyntaxError: invalid syntax

**Comment by china56321** [comment]
> Hi, error happend when train and detect, i have tried many times,all eror are same, i don't know why this happend,could you help me solve this problem ? thank you ! ( i recloned the repo )
> **training error:**
> File "train.py", line 47
> print(f'Hyperparameters {hyp}')
> ^
> SyntaxError: invalid syntax
> 
> **detect eror :**
> Traceback (most recent call last):
> File "detect.py", line 5, in
> from models.experimental import *
> File "/home/make/yolov5/models/experimental.py", line 3, in
> from models.common import *
> File "/home/make/yolov5/models/common.py", line 3, in
> from utils.utils import *
> File "/home/make/yolov5/utils/utils.py", line 55
> last_list = glob.glob(f'{search_dir}/**/last*.pt', recursive=True)
> ^
> SyntaxError: invalid syntax

**Comment by glenn-jocher** [comment]
@china56321 don't know. You could try a different environment:

## Reproduce Our Environment

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by gaasing** [comment]
I have the same question

**Comment by china56321** [comment]
> I have the same question

Have you solved it ?

**Comment by saimanoj18** [comment]
> I have the same question

activate your conda environment
`conda activate ml_env`

**Comment by saimanoj18** [comment]
> > I have the same question
> 
> Have you solved it ?

activate your conda environment
`conda activate ml_env`

**Comment by SantoshAhirrao** [comment]
![image](https://user-images.githubusercontent.com/31290247/102010364-e5a49500-3d3d-11eb-8fc7-9dbdff5e26ad.png)
Can anyone help to find the error

**Comment by glenn-jocher** [comment]
@SantoshAhirrao your command looks fine, error could be due to modified or out of date code. I'll post our default reply here which may help.

Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and then install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.
