### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2.

### ISSUE THREAD

**Issue by majx1997** [ultralytics/yolov5#5799]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi there!
I'm working on an object detection task for small objects, I drop the large object detection in head, The training process works fine, but when I used val.py to test the performance, I encountered the following problems, Could you please tell me how to solve this problem? thanks~
![WX20211126-144908](https://user-images.githubusercontent.com/38154161/143539499-e153c7c0-993f-4320-ad21-7f05046a83b4.png)

**Comment by glenn-jocher** [comment]
@majx1997 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by gayathri81** [comment]
Hello @majx1997 , 
Did you solve this issue? I am facing the same problem, it will be great if you can share your solution here.
Thanks,
Gayathri

**Comment by majx1997** [comment]
> Hello @majx1997 , Did you solve this issue? I am facing the same problem, it will be great if you can share your solution here. Thanks, Gayathri

When verifying, I fixed the stride of the model to 32 and it works.
![image](https://user-images.githubusercontent.com/38154161/145534038-5cb7d719-8f68-4322-b343-257b6b1172da.png)
