### ISSUE TITLE
mutithread to predict for RestAPI

### ISSUE THREAD

**Issue by diaCagri** [ultralytics/yolov5#5803]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi everyone, 

Currently i am creating a web service with fastapi.

When i tried to load balance to my service i got multiple errors like:
"RuntimeError: The size of tensor a (14) must match the size of tensor b (15) at non-singleton dimension 2"

I am loading model with this code in the beginning
```
model = torch.hub.load("ultralytics/yolov5", "yolov5x", pretrained=True)
```

and i predict images like this
```
results = model(img, size=640)
```

as i understand model(image) is not thread-safe,
how can i fix this and run it with multithreading way for microservices (I cant batch multiple images because every single request will send 1 image)

thank you!

**Comment by glenn-jocher** [comment]
@diCagri thread safe operations might be enabled by setting inplace=False on model creation here:
https://github.com/ultralytics/yolov5/blob/7c6bae0ae6711b470ace2587ff7cf313a90cfed0/models/yolo.py#L60-L69

**Comment by glenn-jocher** [comment]
@diCagri BTW we have a YOLOv5 API example here: https://ultralytics.com/yolov5

**Comment by diaCagri** [comment]
@glenn-jocher is there any source code of example api?

this model creation code not gets any inplace (as i understand it is high-level pytorch func)
```
model = torch.hub.load("ultralytics/yolov5", "yolov5x", pretrained=True)
```
or i cant set inplace on model object. How can i use [yolov5/models/yolo.py](https://github.com/ultralytics/yolov5/blob/7c6bae0ae6711b470ace2587ff7cf313a90cfed0/models/yolo.py#L60-L69) this classes? Is there any example code?

Thank you!

**Comment by glenn-jocher** [comment]
@diCagri yes we have an open source Flask API example here:
https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api

Yes you are correct, the inplace argument is not available on hub model creation. You have to trace this attribute from yolo.py down through to hubconf.py, where Hub models are made, and submit a PR to include this model argument. Then we can review and work on merging.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Can you explain this `self.inplace` in detail? I don't understand a bit, what does this `inplace` do? What does it have to do with the `inplace` in the activation function? thanks.
https://github.com/ultralytics/yolov5/blob/7c6bae0ae6711b470ace2587ff7cf313a90cfed0/models/yolo.py#L61

**Comment by glenn-jocher** [comment]
@Zengyf-CVer inplace operations modify a variable directly. Normal operations make a copy of the variable and modify the copy:

```python
x = x + 1  # normal operation, copy of x is made
x += 1  # inplace operation
```

Some parts of YOLOv5 have inplace arguments, like activation functions and the Detect() layer. The model can be constructed with inplace=True or inplace=False here:
https://github.com/ultralytics/yolov5/blob/7c6bae0ae6711b470ace2587ff7cf313a90cfed0/models/experimental.py#L90-L105

**Comment by Zengyf-CVer** [comment]
@glenn-jocher 
Your answer has taught me a lot, thank you very much.

**Comment by fhdbbk** [comment]
@glenn-jocher 
Getting the same error even after setting inplace=False. Loading pytorch weights.

```
class DetectMultiBackend(nn.Module):
    # YOLOv5 MultiBackend class for python inference on various backends
    def __init__(self, weights='yolov5s.pt', device=None, dnn=False):
        # Usage:
        #   PyTorch:      weights = *.pt
        #   TorchScript:            *.torchscript
        #   CoreML:                 *.mlmodel
        #   TensorFlow:             *_saved_model
        #   TensorFlow:             *.pb
        #   TensorFlow Lite:        *.tflite
        #   ONNX Runtime:           *.onnx
        #   OpenCV DNN:             *.onnx with dnn=True
        #   TensorRT:               *.engine
        from models.experimental import attempt_download, attempt_load  # scoped to avoid circular import

        super().__init__()
        w = str(weights[0] if isinstance(weights, list) else weights)
        suffix = Path(w).suffix.lower()
        suffixes = ['.pt', '.torchscript', '.onnx', '.engine', '.tflite', '.pb', '', '.mlmodel']
        check_suffix(w, suffixes)  # check weights have acceptable suffix
        pt, jit, onnx, engine, tflite, pb, saved_model, coreml = (suffix == x for x in suffixes)  # backend booleans
        stride, names = 64, [f'class{i}' for i in range(1000)]  # assign defaults
        attempt_download(w)  # download if not local

        if jit:  # TorchScript
            LOGGER.info(f'Loading {w} for TorchScript inference...')
            extra_files = {'config.txt': ''}  # model metadata
            model = torch.jit.load(w, _extra_files=extra_files)
            if extra_files['config.txt']:
                d = json.loads(extra_files['config.txt'])  # extra_files dict
                stride, names = int(d['stride']), d['names']
        elif pt:  # PyTorch
            model = attempt_load(weights, map_location=device, inplace=False)
            stride = int(model.stride.max())  # model stride
            names = model.module.names if hasattr(model, 'module') else model.names  # get class names
            self.model = model  # explicitly assign for to(), cpu(), cuda(), half()
```

**Comment by glenn-jocher** [comment]
@fhdbbk 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Imtaiyaz-datacorp** [comment]
> @diCagri thread safe operations might be enabled by setting inplace=False on model creation here:
> 
> https://github.com/ultralytics/yolov5/blob/7c6bae0ae6711b470ace2587ff7cf313a90cfed0/models/yolo.py#L60-L69

hy @glenn-jocher , did this block of code changed in recent repo. i cant find this particular line.
how to enable thread safe operations for updated repo.

**Comment by glenn-jocher** [comment]
@Imtaiyaz-datacorp Yes, the code in the YOLOv5 repository has been updated, and the specific line you are referring to may no longer exist. To enable thread-safe operations for the updated repository, you can refer to the official Ultralytics YOLOv5 documentation for guidance on working with multi-threading and microservices: https://docs.ultralytics.com/yolov5/

If you have specific questions about how to enable thread-safe operations in the updated repository, feel free to provide details on your use case, and the community will be happy to assist you further. Thank you!
