### ISSUE TITLE
Yolov5 Torchscript Lite Version

### ISSUE THREAD

**Issue by aseprohman** [ultralytics/yolov5#5809]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello @glenn-jocher  et all,

when I run android demo project for yolov5 on android I see error message below. I have follow any insctruction for save model with _save_for_lite_interpreter() method but it has no change. How to fixed it ? thanks

### Additional

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()

**Comment by glenn-jocher** [comment]
@aseprohman 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by yinrong** [comment]
basic tutorial not working:
android-demo-app/ObjectDetection
replace xxx.pt with  yolov5 exported model.

**Comment by yinrong** [comment]
@aseprohman have you solved this ?

**Comment by zhiqwang** [comment]
FYI, The official torchscript exported by yolov5 only contains the general model inferencing part, one must implement the pre-preprocess (`letterbox`) and post-proprocess (`nms`) if they want to deploy this torchscript.

We did some experiments on [yolort](https://github.com/zhiqwang/yolov5-rt-stack#-introduction) to embed the pre-processing and post-processing into the torchscript graph, so yolort can maintain a similar input and output interface with detr example in torchlive, [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/notebooks/inference-pytorch-export-libtorch.ipynb) is a notebook for intuition of yolort. I think this can be used as the base of the experiment.

(In order to improve the user-friendliness of the interface, we use the pytorch-lightning module, `torch.mobile` does not seem to like this kind of wrapper, here may need to be slightly modified.)

**Comment by yinrong** [comment]
@adrianholovaty you may try again. I run yolov5 demo with my own model successfully on android now. It do need to modify export.py in yolov5 as my merge request below.

![image](https://user-images.githubusercontent.com/4221569/148008710-2b921acd-14fe-4165-a160-97c1ff12df4d.png)

**Comment by glenn-jocher** [comment]
@aseprohman @yinrong good news 😃! Your original issue may now be fixed ✅ in PR #6183. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
