### ISSUE TITLE
About the choice of data set image size

### ISSUE THREAD

**Issue by iscyy** [ultralytics/yolov5#5851]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello author, may I ask how big the photos in the data set are most suitable for the yolo model framework? For example, 640? 1280? 1920? ...For small targets, is it the picture and the larger the resolution, the better

### Additional

Can the author share his experience

**Comment by glenn-jocher** [comment]
@Him-wen 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

Larger image sizes usually lead to better results, but take longer to process, so it's up to the user to find the right compromise between speed and accuracy for their particular application. Default image size for YOLOv5 P5 models is 640, default image size for YOLOv5 P6 models is 1280.

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.

## Dataset

- **Images per class.** ≥ 1500 images per class recommended
- **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
- **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
- **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
- **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

<a href="https://arxiv.org/abs/1405.0312"><img width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png" alt="COCO Analysis"></a>


## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. VOC, VisDrone, GlobalWheat). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
                                             custom_pretrained.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. COCO, Objects365, OIv6). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```


## Training Settings

Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.

- **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
- **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
- **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
- **Hyperparameters.** Default hyperparameters are in [hyp.scratch.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

## Further Reading

If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains:
http://karpathy.github.io/2019/04/25/recipe/](https://github.com/ultralytics/yolov5/issues/2844#issuecomment-851338384)

**Comment by iscyy** [comment]
Thanks for your answer

**Comment by drmuhammadmohsin** [comment]
But what if we have image size of 3264x2464 high resolution then again yolov5 model resize the image to the default setting or will process at the same level during training if we have no time and processing constraints ?

**Comment by glenn-jocher** [comment]
@engineermohsin if you have high resolution images of 3264x2464, YOLOv5 model will resize the images to the default setting during training unless you specify a different image size using the --img argument. Keeping the original high resolution might significantly increase processing time and resource requirements, while potentially adding minimal benefits. It's recommended to find a balance between processing constraints and model performance to achieve efficient detection results.

**Comment by atmadeep** [comment]
Thanks a lot @glenn-jocher for the insight. **Can you please tell me what would be a good resolution for input training images** since I have **5k (5120 x 2880)** resolution videos available (taken from a go-pro). The camera also generates `video_number.LRV` files which are basically low resolution version with frame size **(848x480)**. I think this is too low as the videos are really grainy and the object in far distance loses quite a bit representation.

**Comment by glenn-jocher** [comment]
@atmadeep, for your high-resolution 5k (5120 x 2880) videos, a good starting point for input training image resolution could be in the range of 640 to 1280 pixels on the long edge. This range is a balance between maintaining sufficient detail for object detection and managing computational resources effectively. 

Given the original high resolution of your videos, starting at 1280 pixels might be more appropriate, as it would better preserve the details of distant objects, which could be crucial for your application. However, it's essential to consider the computational cost, as higher resolutions significantly increase processing time and memory requirements.

The low-resolution versions (848x480) you mentioned might indeed be too low for detecting small or distant objects effectively. It's worth experimenting with different resolutions to find the optimal balance for your specific use case. Remember, the best resolution depends on the nature of the objects you're trying to detect and the computational resources at your disposal.

**Comment by navidTerraNova** [comment]
Hello
I have a question regarding the input size of Yolov8 or in general the input to Yolo models, what if my images are (320 x 320), Will yolo resize the image to 640 x 640? and if it does what technique does it use for upsampling? Thank you.

**Comment by glenn-jocher** [comment]
@navidTerraNova hello! Yes, if your images are smaller like (320 x 320), YOLO models, including YOLOv8, will resize them to the model's default input size, such as 640 x 640, to ensure consistency. This resizing uses bilinear interpolation for upsampling, a common technique that's effective at preserving the image's general appearance. You can adjust the input size with the `--img-size` flag during training or inference if needed. Keep in mind, matching the training and inference sizes can help with performance! 😊

**Comment by iwanttograduatepls** [comment]
Hi there @glenn-jocher. I have question. Me and my partner are annotating the images and we are proceeding to training. We used the Roboflow to annotate and all our images are random image ratio which we got from YouTube and Video Recording (live). Our focus is to object detect the vehicles. Since we are assigned to be custom dataset, and we are now proceed to training using google collab. We will use the YOLOv7 (first one) as the model and we confused on which -img will use. The Median Image Ratio based on Roboflow was 1920x1080. Average Image Size was 2.07mp. 

1. Is it good to use the 640 or 1280?

**Comment by glenn-jocher** [comment]
Hello @iwanttograduatepls! Thanks for reaching out with your question.

When deciding on the image size (`--img`) for training your custom dataset, it's important to balance between computational efficiency and the level of detail required for accurate object detection. Here are some considerations:

1. **Default Settings**: Starting with the default image size of 640 is generally a good practice. This helps establish a performance baseline and allows you to identify any potential issues early on.

2. **Higher Resolution**: If your dataset contains many small objects or if the objects are far away, training at a higher resolution like 1280 can help improve detection accuracy. However, this will require more computational resources and longer training times.

3. **Consistency**: Ensure that the image size used during training matches the size used during inference for optimal performance.

Given that your median image ratio is 1920x1080 and the average image size is 2.07MP, starting with 640 and then experimenting with 1280 could be a good approach. Here’s how you can set the image size in your training command:

```bash
python train.py --data custom.yaml --weights yolov7.pt --img 640
```

If you find that the model benefits from higher resolution without significant computational drawbacks, you can switch to:

```bash
python train.py --data custom.yaml --weights yolov7.pt --img 1280
```

Remember to monitor your training results, including metrics like precision, recall, and mAP, to determine the impact of different image sizes.

Good luck with your training, and feel free to share your results or ask further questions! 😊

**Comment by drmuhammadmohsin** [comment]
Thank you for your response. I tried the progressive approach, starting
from the default size of 640 and then increasing the resolution to 1280 and
1920. With higher resolution, the results improved in my case for detecting
small electronic components on PCBs, but at the cost of higher memory usage
and longer training times.

The trained model size is very large in this case, making it very
challenging to perform inference on an edge device (Jetson Nano). Do you
have any suggestions, especially if we divide the image into a grid of
640x640 and train the model on each grid cell? What do you think?
Thanks again!


Best regards,
Mohsin
________________
Muhammad Mohsin
PhD Researcher in Computer Science
DIBRIS - Università degli Studi di Genova - Italy
Email: ***@***.***
Mob. +39 345 5017833

**Comment by glenn-jocher** [comment]
@engineermohsin hi Muhammad,

Thank you for sharing your detailed observations and results. It's great to hear that increasing the resolution has improved your detection accuracy for small electronic components on PCBs. However, I understand the challenge of deploying such a large model on an edge device like the Jetson Nano.

Dividing the image into a grid of 640x640 and training the model on each grid cell is a viable approach. This method can help manage memory usage and reduce the computational load during inference. Here are a few suggestions to implement this strategy effectively:

1. **Sliding Window Technique**: You can use a sliding window approach to divide your high-resolution images into smaller patches (e.g., 640x640). This can be done during both training and inference. Ensure that there is some overlap between the patches to avoid missing objects that lie on the borders.

2. **Model Pruning and Quantization**: To further reduce the model size and improve inference speed on edge devices, consider model pruning and quantization. These techniques can significantly reduce the model's footprint with minimal impact on accuracy. YOLOv5 supports quantization-aware training, which can be beneficial for deployment on devices like the Jetson Nano.

3. **YOLOv5 Nano Models**: For edge devices, you might want to explore smaller YOLOv5 models like YOLOv5s or even YOLOv5n (nano). These models are designed to be lightweight and efficient, making them more suitable for resource-constrained environments.

Here’s an example of how you might implement the sliding window approach in Python:

```python
import cv2
import numpy as np

def sliding_window(image, step_size, window_size):
    for y in range(0, image.shape[0] - window_size[1] + 1, step_size):
        for x in range(0, image.shape[1] - window_size[0] + 1, step_size):
            yield (x, y, image[y:y + window_size[1], x:x + window_size[0]])

image = cv2.imread('high_res_image.jpg')
window_size = (640, 640)
step_size = 320  # 50% overlap

for (x, y, window) in sliding_window(image, step_size, window_size):
    # Process each window (e.g., run inference)
    result = model(window)
    # Handle the result (e.g., aggregate detections)
```

This approach ensures that you can handle high-resolution images without overwhelming your edge device.

I hope these suggestions help! If you have any further questions or need additional assistance, feel free to ask.

**Comment by kyleronc** [comment]
Hello, I am attempting to use yolo for object recognition over a set of tools that are stepwise in nature (for example, I might want to distinguish between two near identical screwdrivers of the same type, one just being used for bolts a gauge larger than the other of them and thus being slightly larger in size). 


1. We are using video feed to further break down into images to label and train. Initially, we were spinning to and angling the camera in different directions when filming our data. Will it make the model more accurate to train the dataset on images in multiple orientations or will it do best to keep them all oriented the same? We should have relative control over the orientation of the instruments used for inference in the field. 

2. We have been testing our model via live feed running at 1920x1080, but we have done training initially on image sizes of 640 and then 720. When doing inference does the input resolution need to match what was used for training to get good results?

**Comment by glenn-jocher** [comment]
Hello @kyleronc,

Thank you for your detailed questions! I'm happy to help you optimize your YOLOv5 model for recognizing tools with subtle differences.

### 1. Image Orientation for Training
Training your dataset on images with multiple orientations can indeed improve the robustness and accuracy of your model. Even if you have control over the orientation during inference, training with varied orientations can help the model generalize better and recognize objects from different angles. This is especially useful for real-world applications where slight variations in orientation are inevitable.

To achieve this, you can use data augmentation techniques such as rotation, flipping, and scaling. YOLOv5 supports these augmentations natively. Here's an example of how you can enable these augmentations in your training configuration:

```yaml
# hyp.scratch-low.yaml (default hyperparameters)
# Increase rotation and flip augmentations
degrees: 10.0  # image rotation (+/- deg)
flipud: 0.5    # image flip up-down (probability)
fliplr: 0.5    # image flip left-right (probability)
```

### 2. Matching Training and Inference Resolutions
For optimal performance, it is generally recommended to match the input resolution during inference to the resolution used during training. This ensures that the model's learned features are appropriately scaled and can lead to better detection accuracy.

However, YOLOv5 is quite flexible and can handle different input sizes to some extent. If you trained your model on 640x640 or 720x720 images, you can still perform inference on 1920x1080 images, but you might need to resize them to the training resolution before feeding them into the model. This can be done using the `--img-size` argument during inference:

```bash
python detect.py --weights best.pt --img-size 640 --source 0  # for webcam
```

If you notice a significant drop in performance, consider retraining your model with images closer to your inference resolution.

### Additional Tips
- **Label Consistency**: Ensure that all instances of the tools are consistently labeled across your dataset. This is crucial for the model to learn the subtle differences between similar objects.
- **Background Variety**: Include a variety of backgrounds in your training images to make the model more robust to different environments.

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. Good luck with your project! 😊

**Comment by kyleronc** [comment]
> Hello @kyleronc,
> 
> Thank you for your detailed questions! I'm happy to help you optimize your YOLOv5 model for recognizing tools with subtle differences.
> 
> ### 1. Image Orientation for Training
> Training your dataset on images with multiple orientations can indeed improve the robustness and accuracy of your model. Even if you have control over the orientation during inference, training with varied orientations can help the model generalize better and recognize objects from different angles. This is especially useful for real-world applications where slight variations in orientation are inevitable.
> 
> To achieve this, you can use data augmentation techniques such as rotation, flipping, and scaling. YOLOv5 supports these augmentations natively. Here's an example of how you can enable these augmentations in your training configuration:
> 
> ```yaml
> # hyp.scratch-low.yaml (default hyperparameters)
> # Increase rotation and flip augmentations
> degrees: 10.0  # image rotation (+/- deg)
> flipud: 0.5    # image flip up-down (probability)
> fliplr: 0.5    # image flip left-right (probability)
> ```
> 
> ### 2. Matching Training and Inference Resolutions
> For optimal performance, it is generally recommended to match the input resolution during inference to the resolution used during training. This ensures that the model's learned features are appropriately scaled and can lead to better detection accuracy.
> 
> However, YOLOv5 is quite flexible and can handle different input sizes to some extent. If you trained your model on 640x640 or 720x720 images, you can still perform inference on 1920x1080 images, but you might need to resize them to the training resolution before feeding them into the model. This can be done using the `--img-size` argument during inference:
> 
> ```shell
> python detect.py --weights best.pt --img-size 640 --source 0  # for webcam
> ```
> 
> If you notice a significant drop in performance, consider retraining your model with images closer to your inference resolution.
> 
> ### Additional Tips
> * **Label Consistency**: Ensure that all instances of the tools are consistently labeled across your dataset. This is crucial for the model to learn the subtle differences between similar objects.
> * **Background Variety**: Include a variety of backgrounds in your training images to make the model more robust to different environments.
> 
> I hope this helps! If you have any further questions or need additional assistance, feel free to ask. Good luck with your project! 😊

Thank you so much! Two more quick questions:

Does the fact that the images are being rezied screw with the label file's coordinates of each class in a particular image? Also if are images are not originally square but follow a portrait aspect ratio, will the labeling be affected in this way once it is reformatted to a square image?

Also we have been adding a little reference rectangle of a vibrant pattern in all of our images with the initial thought to use it as well a reference with which we can do things like calculate size between two tools that are identical outside of scale given we kmow the size of the reference. Can YOLO understand the size difference between the tools naturally with enough data and proper tuning? It would save us a lot of extra code to circumnavigate this in most scenarios

**Comment by drmuhammadmohsin** [comment]
Thank you for your detailed response. I have implemented the patching
strategy, and the accuracy of the model has improved. The next step is to
use the pseudo-labeling technique to increase the model's performance on
new custom data and publicly available datasets to solve the class
imbalance problem.

What do you think about using pseudo-labeling with YOLOv5 or YOLOv8? What
do you suggest for addressing the class imbalance problem?

Thanks for your help!
Best regards,
Mohsin
________________
Muhammad Mohsin
PhD Researcher in Computer Science
DIBRIS - Università degli Studi di Genova - Italy
Email: ***@***.***
Mob. +39 345 5017833

**Comment by glenn-jocher** [comment]
Hello Muhammad,

Thank you for your thoughtful follow-up! I'm glad to hear that the patching strategy has improved your model's accuracy. 

### Pseudo-Labeling with YOLOv5 or YOLOv8
Pseudo-labeling can be a powerful technique to enhance your model's performance, especially when dealing with class imbalance. By leveraging pseudo-labels, you can effectively increase your dataset size and diversity, which can help the model generalize better.

Here's a general approach to implement pseudo-labeling with YOLOv5 or YOLOv8:
1. **Initial Training**: Train your model on the labeled dataset.
2. **Inference on Unlabeled Data**: Use the trained model to predict labels on the unlabeled data.
3. **Filter Predictions**: Filter the predictions based on confidence thresholds to ensure high-quality pseudo-labels.
4. **Combine Datasets**: Combine the original labeled dataset with the pseudo-labeled data.
5. **Retrain**: Retrain the model on the combined dataset.

### Addressing Class Imbalance
Class imbalance can significantly affect model performance. Here are a few strategies to address this issue:

1. **Data Augmentation**: Increase the number of samples for the minority classes using data augmentation techniques such as rotation, flipping, and scaling.
2. **Weighted Loss Function**: Adjust the loss function to give more weight to the minority classes. This can help the model pay more attention to underrepresented classes.
3. **Oversampling**: Duplicate samples from the minority classes to balance the dataset.
4. **Under-sampling**: Reduce the number of samples from the majority classes, though this might lead to loss of valuable information.

### Example of Weighted Loss Function in YOLOv5
You can modify the `hyp.scratch-low.yaml` file to adjust the class weights:

```yaml
# hyp.scratch-low.yaml
cls: 0.5  # class loss gain (original value is 0.5)
cls_pw: 1.0  # class positive weight (original value is 1.0)
```

Experiment with these values to find the optimal balance for your specific dataset.

### Combining Strategies
Combining pseudo-labeling with techniques to address class imbalance can yield significant improvements. For instance, after generating pseudo-labels, you can apply data augmentation to the minority classes in the pseudo-labeled dataset.

I hope these suggestions help you further enhance your model's performance. If you have any more questions or need additional assistance, feel free to ask. Good luck with your research! 😊

**Comment by drmuhammadmohsin** [comment]
Thank you for your valuable feedback on my question. I am currently working
on these ideas and will discuss the achieved outcome with you.

Best regards,
Mohsin
________________
Muhammad Mohsin
PhD Researcher in Computer Science
DIBRIS - Università degli Studi di Genova - Italy
Email: ***@***.***
Mob. +39 345 5017833

**Comment by glenn-jocher** [comment]
@engineermohsin hello Muhammad,

Thank you for your kind words and for keeping us updated on your progress. It's fantastic to hear that you're actively working on these ideas. I'm looking forward to learning about the outcomes of your experiments with pseudo-labeling and class imbalance strategies.

If you encounter any specific challenges or have further questions as you proceed, please don't hesitate to reach out here. The community and I are always here to support you.

Best regards and good luck with your research!

😊

P.S. Please remember to verify any issues with the latest versions of the packages to ensure you're benefiting from the most recent updates and fixes.
