### ISSUE TITLE
check_anchor_order in the utils/autoanchor.py results in some anchors larger than the longest edge of the image

### ISSUE THREAD

**Issue by xiaomao19970819** [ultralytics/yolov5#5855]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I found some problems when I used the following code to generate anchors for my own data set：
check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz) （in tran.py 238L）

I got the output like this, obviously in the red box is the anchor size obtained by the genetic algorithm
![image](https://user-images.githubusercontent.com/45539173/144392448-2a4d4c50-d384-41df-92d0-1cb6021447c5.png)
However, after the model training, I loaded the model and found that the value of anchor stored in the model was not the same as the value printed before.
I have found that this is due to the check_anchor_order function in line 59 of utils/autoanchor.py .I don't understand why we need to divide by stride in line 58 when checking the area order of anchors.
I captured some graphs to show the change in anchor size before and after the check_anchor_order function：
After 57L
![image](https://user-images.githubusercontent.com/45539173/144395515-a911c727-0473-4f45-b556-98dfb9f8077b.png)
After 58L (anchor size divided by strides)
![image](https://user-images.githubusercontent.com/45539173/144395613-b103a597-e070-4817-ae76-401a3d76d953.png)
After 59L
![image](https://user-images.githubusercontent.com/45539173/144395945-7b2a092c-c089-482e-8990-969d83281bd5.png)
Since the Anchors is flipped, the size of Anchor will exceed the maximum edge of the image when the stride is multiplied later

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by xiaomao19970819** [comment]
In addition, I use the model framework of Yolov5n6, so the predefined anchor is 12

**Comment by glenn-jocher** [comment]
@xiaomao19970819 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by xiaomao19970819** [comment]
> @xiaomao19970819 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

Sorry, I'm not sure if the format I submitted is correct. However, I showed some pictures of experimental results and pointed out doubts about the code. I am not sure whether my understanding is correct or not, and whether it is a bug. Therefore, I hope you can answer why the anchor size is divided by the stride before checking the order of the area of anchor. In my experiments, this resulted in an anchor larger than the longest edge of the image.

**Comment by glenn-jocher** [comment]
@xiaomao19970819 well unless we can reproduce your results there's nothing for us to do here.

I would say though that from your screenshot I can see your code is out of date. Before asking anything you should always make sure your issue is caused by current code, not out of date code.
