### ISSUE TITLE
When will you release the paper ?

### ISSUE THREAD

**Issue by fazer125** [ultralytics/yolov5#5859]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

You said you were going to release a paper by the end of last year.
But you didn't release it.
I was sad.

And recently, you said that you will release the paper by December 1.
But you didn't release it.
I am very sad.

When will you release the paper ?
I am looking forward to it.

@glenn-jocher

**Comment by Makki93** [comment]
I don't want to stir up hatred here, but I have the bad feeling that YOLOv5 just doesn't perform as well as wanted to release a paper with results in a general comparison. Or they just don't do anything majorly different to v4 so it would justify a scientific paper.

Me personally, I did countless hours of research about a comparison, since my thesis contains YoloV5 stuff, and I would have loved to write about it and be able to quote a paper. I kind of understand if what I stated above is true, that it's a strategy to not release a paper yet because ultralytics and @glenn-jocher want to make some money with YoloV5 and any bad reputation would harm that. But I don't get the point in making promises that aren't then answered anymore after not being kept. They could just say they're only focussing on being super easy to integrate everywhere, not on the best performance. Btw the Roboflow blog which you may have encountered cannot be taken as an independent vote, because they're working together with Glenn.

**Comment by mapattacker** [comment]
I recalled that glenn mentioned in one of the issue that he will release it at the Pytorch Developer Conference in Dec which has since passed. However, I could not find that particular post anymore.

**Comment by fazer125** [comment]
> I recalled that glenn mentioned in one of the issue that he will release it at the Pytorch Developer Conference in Dec which has since passed. However, I could not find that particular post anymore.

Here.
https://github.com/ultralytics/yolov5/issues/1333#issuecomment-936818045
