### ISSUE TITLE
val.py error

### ISSUE THREAD

**Issue by firsakov** [ultralytics/yolov5#5975]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, please help, what can be the error with val.py?

![image](https://user-images.githubusercontent.com/74253273/145965484-a30796e9-d1ed-477b-906e-7bcba501381a.png)

**Comment by glenn-jocher** [comment]
@firsakov 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@firsakov 
From your error report, I guess that there is wrong bounding box information in the data, such as wrong xyxy or wrong xywh. Please double check that the image annotations in the verification set are correct.

**Comment by firsakov** [comment]
@Zengyf-CVer actually i jus figured out that length of variable ```pred``` from ```out``` is very long for every image and I suppose it detects wrong classes (native coco), but not my classes. that's strange because I provided my classes in .yaml data config file. Maybe you have any ideas why classes are wrong?

**Comment by Zengyf-CVer** [comment]
@firsakov 
Have you modified the `nc` parameter in yaml?

**Comment by firsakov** [comment]
@Zengyf-CVer yes I did
