### ISSUE TITLE
How to train data with Chinese labels?

### ISSUE THREAD

**Issue by QL-AR** [ultralytics/yolov5#6004]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to train data with Chinese labels?

**Comment by glenn-jocher** [comment]
@QL-AR YOLOv5 should be fully compatible with Chinese fonts. We analyze labels with `is_chinese()` and then apply appropriate Unicode fonts if required:

https://github.com/ultralytics/yolov5/blob/c1249a47c7fe19e2067cb25ed8347e67d26ff1f1/utils/plots.py#L72-L80

**Comment by glenn-jocher** [comment]
![image](https://user-images.githubusercontent.com/26833433/146379825-4eddb121-8a0f-4039-8896-c8324be6fd85.png)

**Comment by QL-AR** [comment]
I don’t understand it very well, can you be more specific?

**Comment by QL-AR** [comment]
Unicode fonts if required:

**Comment by QL-AR** [comment]
![val_batch0_labels](https://user-images.githubusercontent.com/39522514/146550643-f3dce5b5-6646-4dda-94ca-af40dc7818ac.jpg)

**Comment by glenn-jocher** [comment]
@QL-AR there is nothing required, chinese fonts should work correctly by default.

**Comment by QL-AR** [comment]
People show this way

**Comment by QL-AR** [comment]
Should the label be trained in Chinese or English?

**Comment by zhiqwang** [comment]
Seems that we don't need the detailed label information when we train a model, for we just need to know they below to different classes.

**Comment by QL-AR** [comment]
Why can't my computer display Chinese?

**Comment by hansoullee20** [comment]
@glenn-jocher just out of curiosity does it support Korean as well?

**Comment by glenn-jocher** [comment]
@hansoullee20 I think so according to https://en.wikipedia.org/wiki/Arial_Unicode_MS

Can you try and report back?

**Comment by QL-AR** [comment]
How can I set the Chinese label to be displayed?

**Comment by QL-AR** [comment]
Concrete realization method

**Comment by glenn-jocher** [comment]
@QL-AR if your class names contain chinese characters they will be displayed automatically.

**Comment by QL-AR** [comment]
Display garbled

**Comment by QL-AR** [comment]
![val_batch0_labels](https://user-images.githubusercontent.com/39522514/147323896-290fe9fe-02a9-498b-bbfe-42d71a50377c.jpg)

**Comment by glenn-jocher** [comment]
@QL-AR 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by RicoSuaveGuapo** [comment]
@glenn-jocher should we type some Chinese character for argument `example` of `Annotator` while instancing it
([here](https://github.com/ultralytics/yolov5/blob/master/utils/plots.py#L73)) to enable automatically downloading font?

Since in my case, it works ><

**Comment by glenn-jocher** [comment]
@RicoSuaveGuapo oh actually you shouldn't need to do anything. The Annotator instances should be created with all of the class names passed in a concatenated `example` string, i.e. in detect.py:
https://github.com/ultralytics/yolov5/blob/0cf932bf6346909189c53b375ef97551bb0c2326/detect.py#L153

**Comment by lonngxiang** [comment]
how to let predict labels display other languages？

**Comment by glenn-jocher** [comment]
@lonngxiang you can display labels in other languages by ensuring that the font used by the visualization tool supports the characters of the language you want to display. You can set the font path in the visualization script to a font file that supports the characters you need.
