### ISSUE TITLE
val.py starts multiple processes when called from Python script

### ISSUE THREAD

**Issue by Denbergvanthijs** [ultralytics/yolov5#6025]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

First of all, thank you for YOLOv5!

My repository has the following structure:

- yolov5/
- data/rs19_person.yaml
- my_script.py

Within `my_script.py` I have the following code:

```python
from yolov5 import val

results, _, timings = val.run(data="./data/rs19_person.yaml",
                              weights=["yolov5n.pt"],
                              batch_size=1,
                              task="val",
                              workers=1,
                              single_cls=True)
```

Sadly, this code will start 8 processes and my computer gets stuck. However changing data="./data/rs19_person.yaml" to data="./yolov5/coco128.yaml" does work and will not start 8 processes.

<details>
  <summary>The logs show the following and then my computer freezes and I have to force-close the console.</summary>

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

Fusing layers... 
Model Summary: 213 layers, 1867405 parameters, 0 gradients
val: Scanning 'data\rs19_person\labels\val' images and labels...:   0%|                                                                       | 0/21 [00:00<?, ?it/s]YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)

Fusing layers... 
Fusing layers... 
Fusing layers... 
Fusing layers... 
Fusing layers... 
Fusing layers... 
</details>

### Environment

- YOLOv5  v6.0-150-g361705d torch 1.10.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1050, 2048MiB)
- OS: Windows 10
- Python 3.9.9

### Minimal Reproducible Example

A folder with the following files and folders inside:

- yolov5/
- data/rs19_person.yaml
- my_script.py

A file `my_script.py` with the following code:

```python
from yolov5 import val

results, _, timings = val.run(data="./data/rs19_person.yaml",
                              weights=["yolov5n.pt"],
                              batch_size=1,
                              task="val",
                              workers=1,
                              single_cls=True)
```

The yaml contains the following:

```yaml
path: ./data/rs19_person # Dataset root dir
train: images/train # Train images
val: images/val # Val images
test: images/test # Test images

# Classes
nc: 1 # Number of classes
names: ["person"] # Class names

```

### Additional

I understand that `val.py` is just a basic script and not meant for production, it does however serve my needs and I would really like to use it. Thank you very much for your time!

P.S. the whole repository can be found at https://github.com/Denbergvanthijs/railsem19_yolov5
This is a W.I.P. still though.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Denbergvanthijs 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Denbergvanthijs** [comment]
Hi @glenn-jocher , is the code I have provided minimal and reproducible enough for you? What can I do to make it better?

**Comment by glenn-jocher** [comment]
@Denbergvanthijs val.py operates correctly for me. If we can't reproduce an error on our side the issue is non-actionable.

<img width="1664" alt="Screen Shot 2021-12-17 at 5 16 55 PM" src="https://user-images.githubusercontent.com/26833433/146575071-454cba6a-6793-4417-bca3-8f395f7adbcc.png">

**Comment by Denbergvanthijs** [comment]
Sorry if I was unclear, the `coco128.yaml` does indeed work for me. The problem is that it doesn't work on my custom dataset. 

I'm in doubt if my custom dataset is incorrect because when I run `python ./yolov5/val.py --data "./data/rs19_person.yaml" --weights "yolov5n.pt" --batch-size 1 --task val --workers 1 --single-cls` it does work. The same goes for training from the command line, that also works for my custom dataset

**Comment by glenn-jocher** [comment]
@Denbergvanthijs if you can demonstrate an issue using any of the autodownload datasets (i.e. COCO, COCO128, VOC, etc.) then please let us know, thanks!

https://github.com/ultralytics/yolov5/tree/master/data

**Comment by Denbergvanthijs** [comment]
I will give it a go, thank you for your fast responses!

**Comment by Denbergvanthijs** [comment]
I have been able to solve my problem by adding `if __name__ == "__main__":` to the script. Its still strange that 8 processes start when I run my script. But for now my problem is solved. Thank you for your assistance Glenn!
