### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.datasets'; 'utils' is not a package

### ISSUE THREAD

**Issue by bl146u** [ultralytics/yolov5#6048]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

I try to load model from a github repo like this
```
model = torch.hub.load("ultralytics/yolov5", "yolov5s", pretrained=True, force_reload=True)
```
But I have `utils.py` in my virtual environment in root, there for I got this exception
```
  File "/home/bl146u/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 25, in <module>
    from utils.datasets import exif_transpose, letterbox
ModuleNotFoundError: No module named 'utils.datasets'; 'utils' is not a package
```
The only one solution is to rename my `utils.py`. Maybe this is not a bug, but just a condition for using this package.

### Environment

- OS: Manjaro
- Python: 3.7.12

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bl146u yes you are correct, torch hub loading may create package conflicts depending on what other files or directories exist in your workspace. This is a byproduct of the torch hub loading scheme more than anything else.

**Comment by bot66** [comment]
> @bl146u yes you are correct, torch hub loading may create package conflicts depending on what other files or directories exist in your workspace. This is a byproduct of the torch hub loading scheme more than anything else.

Hi@ glenn-jocher  Glenn, I want to intergrate yolov5 to my project, but it's really hard to do it when create pretrained yolov5 models:
1. If use `torch.hub.load` create pretrained model,will create package conflicts.
2. If use `torch.load` to load  `attempt_download` function downloaded pretrained checkpoint,because of the checkpoint saved the entire model,  then its weight can't be loaded via `torch.load`.

This is frustrating...
