### ISSUE TITLE
image was frozen when reading rtsp

### ISSUE THREAD

**Issue by Chung-Yi** [ultralytics/yolov5#6070]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I ran the detect.py, cv2.imshow() would stop at specific image, and I wrote message to log file, I got that inference time is 657sec before frozen frame, I didn't know if the larger inference time was related to frozen frame. At the beginning I wondered that if VideoCapture cannot get the frame, but cap.retrieve always returned True.

### Additional

![截圖 2021-12-23 下午2 31 56](https://user-images.githubusercontent.com/26489985/147198635-2334ad93-62d6-4ad0-bda1-5223693b965a.png)

**Comment by glenn-jocher** [comment]
@Chung-Yi YOLOv5 uses cv2 for image and video handling, so you may want to raise an issue directly on the opencv repository. Connection issues may also play a part for RTSP/streaming sources.

**Comment by Chung-Yi** [comment]
But I do not think that opencv causes the problem. Because I can get every different frame, and every  frame spends 0.36sec to inference, only one frame spends 657sec as I said above, and then it was frozen, I can not get different frame anymore.

**Comment by glenn-jocher** [comment]
@Chung-Yi 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Chung-Yi** [comment]
I tested a few times, and I got the result that cap.read() returned False sometimes in the dataset.py in LoadStreams class

**Comment by glenn-jocher** [comment]
@Chung-Yi then this appears to be due to cv2 or your connection. You may want to raise an issue directly on the opencv repository.

**Comment by zamriibr** [comment]
I faced the same problem. Its due to self. fps in LoadStream give 0 fps when run cv2.videocapture in datasets.py in util, so the time delay (1/0) give freeze situation. I have to manually insert time delay (1/30) to fix the problem. 

datasets.py
            #time.sleep(1 / self.fps)  # wait time
            time.sleep(1 / 30)  # wait time

**Comment by glenn-jocher** [comment]
@zamriibr are you using latest code? 0 FPS is not possible with current code, default is 30:

https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/utils/datasets.py#L312-L314

**Comment by Chung-Yi** [comment]
@zamriibr  I have found the reason that caused the problem. Sometime the cap.isOpened is Fasle in while loop, if it is False, I reopend the rtsp stream. I have not study the opencv repository yet, sorry @glenn-jocher 
`
While True:
    if not cap.isOpened():
        cap.release()
        cap = cv2.VideoCapture(s)
        continue
`

**Comment by zamriibr** [comment]
> @zamriibr are you using latest code? 0 FPS is not possible with current code, default is 30:
> 
> https://github.com/ultralytics/yolov5/blob/8efe97719c9b3b77c9db9b5c8592e051b7f0c9a7/utils/datasets.py#L312-L314

**Comment by zamriibr** [comment]
@glenn-jocher as my program in production now, I still use the old version. I just modify it - manual changes to datasets.py based on latest info that you shared. Thanks
