### ISSUE TITLE
train.py: error: argument --weights: expected one argument

### ISSUE THREAD

**Issue by LokedSher** [ultralytics/yolov5#6072]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I want to train a yolov5s on  my own dataset and randomly initialize the weights. I have modified coco128.yaml and run the sh
`python .\train.py --img 640 --batch 16 --data .\data\coco128.yaml --cfg .\models\yolov5s.yaml --weights '' --device 0 ` as the tutorial said,then the error occured:
`train.py: error: argument --weights: expected one argument`
I don't know how to deal with it

**Comment by glenn-jocher** [comment]
@LokedSher some environments might need "" instead of ''

**Comment by tianty** [comment]
> @LokedSher some environments might need "" instead of ''

maybe he wants to kown how to train the yolov5 model from the randomly initialization without pre-trained model. But the default parameters in train.py is 'default=ROOT / 'yolov5s.pt'. How to set the '--weights' in train.py to get the randomly initialization.

**Comment by glenn-jocher** [comment]
@tianty for a randomly initialized yaml: `--cfg yolov5s.yaml --weights ''`

**Comment by wilkinsjle** [comment]
> @tianty for a randomly initialized yaml: `--cfg yolov5s.yaml --weights ''`

This works for my Mac but not on my Windows machine ): 

On Windows the error occurs: `train.py: error: argument --weights: expected one argument`. This is also what the original poster has said.

Using `""` also hasn't worked.

**Comment by wilkinsjle** [comment]
Ok just found the fix:

If you are using Powershell, use `[string]::Empty` instead of `""` or `''` to specify an empty string.

**Comment by glenn-jocher** [comment]
@wilkinsjle great find! Using `[string]::Empty` in Powershell to specify an empty string instead of `""` or `''` should resolve the issue. Let me know if you need further assistance.

**Comment by tomhoq** [comment]
`[string]::Empty` causes a different error for me:

```
Traceback (most recent call last):
  File "E:\Tomaz\Yolov5\yolov5\train.py", line 848, in <module>
    main(opt)
  File "E:\Tomaz\Yolov5\yolov5\train.py", line 623, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:\Tomaz\Yolov5\yolov5\train.py", line 196, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get("anchors")).to(device)  # create
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Tomaz\Yolov5\yolov5\models\yolo.py", line 227, in __init__
    with open(cfg, encoding="ascii", errors="ignore") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
```


while running this:
`python train.py --img 640 --batch 16 --epochs 10 --data custom_data.yaml --weights [string]::Empty`

**Comment by glenn-jocher** [comment]
Hi @tomhoq,

Thank you for your detailed feedback. It looks like using `[string]::Empty` is causing a `FileNotFoundError` because the script is interpreting it as a literal string rather than an empty value.

To train YOLOv5 with randomly initialized weights on a Windows machine using Powershell, you can try the following workaround:

1. **Use a non-existent file path**: This will force the script to initialize weights randomly.
    ```powershell
    python train.py --img 640 --batch 16 --epochs 10 --data custom_data.yaml --weights "path/to/nonexistent/file.pt"
    ```

2. **Modify the script**: Alternatively, you can modify the `train.py` script to handle an empty string correctly. Locate the section where the weights are loaded and add a condition to check for an empty string:
    ```python
    if opt.weights == '[string]::Empty' or opt.weights == '':
        opt.weights = None
    ```

3. **Use a placeholder**: Another approach is to use a placeholder that the script can interpret correctly:
    ```powershell
    python train.py --img 640 --batch 16 --epochs 10 --data custom_data.yaml --weights "None"
    ```

If you continue to experience issues, please ensure you are using the latest version of YOLOv5 by pulling the latest changes from the repository. This can help ensure that any recent bug fixes or improvements are included in your environment.

Feel free to reach out if you have any further questions or need additional assistance. Happy training! 🚀
