### ISSUE TITLE
Trying to run this --> "net = cv2.dnn.readNetFromDarknet(modelConfiguration, modelWeights)" #I get this error 

### ISSUE THREAD

**Issue by gigDevelopment10** [ultralytics/yolov5#6101]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "g:\Second year\SDP project\yolov5\python\file.py", line 17, in <module>
    net = cv2.dnn.readNetFromDarknet(modelConfiguration, modelWeights)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:902: error: (-212:Parsing error) Unknown layer type:  in function 'cv::dnn::darknet::ReadDarknetFromCfgStream'

How do I solve this ??

### Additional

#What I have done ??
I did this -->" YOLO V5 Ultralytics model and config format to Darknet format -->by : Adriano Santos."
and then...
I am running this command !
"net = cv2.dnn.readNetFromDarknet(modelConfiguration, modelWeights)" 
#I get this error

**Comment by gigDevelopment10** [comment]
Any other command I can use to read the cfg and weights file ?

**Comment by glenn-jocher** [comment]
@gigDevelopment10 darknet is an older format that YOLOv5 no longer supports.

YOLOv5 DNN inference is very simple:
```python
# Export
python export.py --weights yolov5s.pt --include onnx

# Inference
python detect.py --weights yolov5s.onnx --dnn
```

**Comment by gigDevelopment10** [comment]
Thanks it was really helpful ...

**Comment by glenn-jocher** [comment]
@gigDevelopment10 no problem. BTW you might get better results just using the default ONNX Runtime inference:

```python
# Export
python export.py --weights yolov5s.pt --include onnx

# Inference
python detect.py --weights yolov5s.onnx  # ONNX Runtime inference
python detect.py --weights yolov5s.onnx --dnn  # OpenCV DNN inference
```

**Comment by gigDevelopment10** [comment]
Nice ill try this ...

**Comment by Jojo942004** [comment]
@gigDevelopment10 @glenn-jocher did you guys ever resolve this issue?

**Comment by glenn-jocher** [comment]
@gigDevelopment10 for cv2 DNN inference:

```python
# Export
python export.py --weights yolov5s.pt --include onnx

# Inference
python detect.py --weights yolov5s.onnx  # ONNX Runtime inference
python detect.py --weights yolov5s.onnx --dnn  # OpenCV DNN inference
```

**Comment by slience-ops** [comment]
@glenn-jocher  python detect.py --weights yolov5s.onnx --dnn ,Execute  this command,throw error:
   model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "C:\code\darknet\yolov5-master\models\common.py", line 350, in __init__
    net = cv2.dnn.readNetFromONNX(w)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Identity@ai.onnx]:(onnx_node!Identity_0) parse error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layer.cpp:246: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20220524::Layer::getMemoryShapes'

**Comment by glenn-jocher** [comment]
@slience-ops DNN inference works correctly in our tests:
<img width="815" alt="Screen Shot 2022-07-11 at 4 05 30 PM" src="https://user-images.githubusercontent.com/26833433/178283192-cca37a8a-14c8-40ea-80d0-579221851b6c.png">
 
We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
