### ISSUE TITLE
Long time between epochs

### ISSUE THREAD

**Issue by amfogor** [ultralytics/yolov5#6128]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

For a particular training set an epoch takes 0 seconds, but the time between each epoch is 6 seconds.

What is taking so long?

### Environment

- YOLO: YOLOv5 🚀 v6.0-155-gdc54ed5 torch 1.9.0 CUDA:0 (A100-SXM4-40GB, 40536MiB)
- OS:  Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
- Python: 3.7.10

### Minimal Reproducible Example

```
d=yolov5

python $d/train.py \
        --epochs 600 \
        --cfg $d/models/yolov5s.yaml \
        --hyp hyp.scratch.yaml \
        --img-size 640 \
        --data ../train/train.yaml \
        --batch-size 180 \
        --noval \
        --cache ram
```

### Additional
the input images are approximately 5000x3000
```
train: Scanning '../train/labels' images and labels...197 found, 0 missing, 0 empty, 0 corrupted:
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@amfogor 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@amfogor you may want to run a profiler like spyder line profiler on train.py to see where the main lines are that are taking the most time. With a cached dataset and infinite dataloader there's not much else to speed up in YOLOv5 that I'm aware of.
