### ISSUE TITLE
datasets.py line:617 (dataset) labels_out[:,0] value is always 0, but train.py line:294 targets[:,0] is between 0 and batch-1

### ISSUE THREAD

**Issue by Kerry678231** [ultralytics/yolov5#6143]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

datasets.py line:617 (dataset) labels_out[:,0] value is always 0, but train.py line:294 targets[:,0] is between 0 and batch-1,
please tell me, when an where label is modifyed, this dataloader do it? but why image tensor is not the modifed index.

**Comment by glenn-jocher** [comment]
@Kerry678231 I printed `labels_out` and everything is operating correctly:
https://github.com/ultralytics/yolov5/blob/affa284352fa6d094d32fe2be69dbffe36bd20f8/utils/datasets.py#L617

<img width="1639" alt="Screen Shot 2021-12-31 at 8 51 17 AM" src="https://user-images.githubusercontent.com/26833433/147833045-baf259a4-694d-4852-b62d-95fa825f18ba.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@Kerry678231 also I think you are misunderstanding the image index. A dataloader worker has no idea what index image it is working on, this is the collate function's job.

**Comment by Kerry678231** [comment]
Thanks, I appreciate your kind help. i find collate function code through your answer.
