### ISSUE TITLE
Why are these pictures created?

### ISSUE THREAD

**Issue by hee100** [ultralytics/yolov5#6210]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I made a "confusion matrix" using "val.py". And i found that the val_batch0_label image was damaged
![val_batch0_labels](https://user-images.githubusercontent.com/95641633/148229150-be2d674c-7abc-4d7a-ab68-5ddda642d95a.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/95641633/148229165-38e55683-6ab9-4b5a-96a5-e6be12b35159.jpg)
.

Some other photos are severely damaged.
![val_batch0_labels](https://user-images.githubusercontent.com/95641633/148229947-53352c17-f56d-4004-a209-b939952511f6.jpg)
![val_batch0_pred](https://user-images.githubusercontent.com/95641633/148230044-7b8ef807-0c35-42d5-90bb-d0cd4b68f9b2.jpg)

### Additional

```
(opencv) gonghuibae@gonghuibaeui-MacBookAir yolov5-6.0 % python val.py --data data/coco128.yaml --weights /Users/gonghuibae/Desktop/Project/models/0103m_/last.pt
val: data=data/coco128.yaml, weights=['/Users/gonghuibae/Desktop/Project/models/0103m_/last.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False
YOLOv5 🚀 2021-10-12 torch 1.10.0 CPU

Fusing layers... 
Model Summary: 290 layers, 20861016 parameters, 0 gradients
val: Scanning '/Users/gonghuibae/Desktop/Project/yolov5-6.0/train_data/labels/te
val: New cache created: /Users/gonghuibae/Desktop/Project/yolov5-6.0/train_data/labels/test.cache
               Class     Images     Labels          P          R     mAP@.5 mAP@/Users/gonghuibae/miniforge3/envs/opencv/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/runner/miniforge3/conda-bld/pytorch-recipe_1635217280611/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
               Class     Images     Labels          P          R     mAP@.5 mAP@
                 all          9         10          1        0.2        0.6      0.568
            Wildboar          9         10          1        0.2        0.6      0.568
Speed: 7.4ms pre-process, 334.5ms inference, 0.7ms NMS per image at shape (32, 3, 640, 640)
Results saved to runs/val/exp
```

**Comment by glenn-jocher** [comment]
@HeeHee100 train and val batch jpgs are created so you can see what your batches look like.

**Comment by hee100** [comment]
I didn't use the damaged picture.
[ Original ]
![snow1](https://user-images.githubusercontent.com/95641633/148324601-f02793ae-dd30-438c-9eda-99a147d5f721.jpeg)
![snow4](https://user-images.githubusercontent.com/95641633/148324633-ec9c8a0b-6f54-4391-ae14-d3a57cb4210b.jpeg)

If i use "val.py," i get a damaged picture.

**Comment by glenn-jocher** [comment]
@HeeHee100 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@HeeHee100 
I suggest you use a picture conversion tool to transcode the picture format again, such as JPG-->JPG or PNG-->JPG.
