### ISSUE TITLE
Command 'edgetpu_compiler --version' returned non-zero

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/yolov5#6215]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I was trying to export yolov5n.pt to edgetpu running the following command:

```
python3 export.py --weights yolov5n.pt --img-size 640 --include edgetpu
```

It exports correctly the model to TF, but at the time of edge tpu I get the following message:

![image](https://user-images.githubusercontent.com/80393891/148286270-1b9f989d-27bc-4ffc-9d61-a36d885a2641.png)

Does anybody exported it correctly?

Thank you in advance.

### Environment

Ubuntu 20.04
Python 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dariogonle Edge TPU export requires edgetpu_compiler installed on your system. See https://coral.ai/docs/edgetpu/compiler/

**Comment by dariogonle** [comment]
Thank you so much @glenn-jocher.

**Comment by glenn-jocher** [comment]
@dariogonle good news 😃! Your original issue may now be fixed ✅ in PR #6223. This PR enables automatic installation of Edge TPU compiler if required during export of Edge TPU models:
```bash
python export.py --weights yolov5s.pt --include edgetpu
```

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by dariogonle** [comment]
Hi @glenn-jocher,
 I've git pulled the repo and I've run:
```
python3 export.py --weights yolov5n.pt --include edgetpu
``` 
Apparently, it works fine but the model yolov5n-int8_edgetpu.tflite is not generated. The log says it is, but it's not. What's more it says that it is 0.0MB.

The only thing I see that was generated is yolov5n-int8.tflite but I suppose that this is a previous model required to generate the edgtpu model.

![image](https://user-images.githubusercontent.com/80393891/148368345-e69c85d1-bc2d-4484-b338-4593095b88b9.png)



Another anomaly I've found is that if I run
```
python3 export.py --weights yolov5n.pt --include edgetpu --img-size 704
``` 

The export script gives the following error:
![image](https://user-images.githubusercontent.com/80393891/148370255-7db3f5da-5064-4985-946b-5a23be27f219.png)


If I use img-size of 416 it works fine (I mean as with 640), but with 704 it seems to be to big. Is there any explication?



EDIT:

I run on a terminal
```
edgetpu_compiler -s yolov5n-int8.tflite
```
And I got the yolov5n-int8_edgetpu.tflite. There might be a problem here, but I don't see it
https://github.com/ultralytics/yolov5/blob/f80c463010101e463670440537662f671cbaaa04/export.py#L308-L332

**Comment by glenn-jocher** [comment]
@dariogonle 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. 

Your Edge TPU export at --img 704 issue is already explained in the error message in your screenshot "Compilation failed due to large activation tensors in model".

Your Edge TPU export for `python3 export.py --weights yolov5n.pt --include edgetpu` produces no errors:
<img width="1325" alt="Screen Shot 2022-01-06 at 9 36 26 AM" src="https://user-images.githubusercontent.com/26833433/148425940-a09c2bde-63fa-4c25-9d50-c242ec6140fe.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
