### ISSUE TITLE
Dimension mismatches occur when moving a yoloV5-trained model into someone else's YoloV5

### ISSUE THREAD

**Issue by smallclass2016** [ultralytics/yolov5#6270]
I used YoloV5 to train a custom model, and then someone else used YoloV5 to test my model best.pt, and a dimension mismatch occurred. How to solve it?

Problem description：File "/home/hit502/project/paoge/yolov5-deepsort/models/yolo.py", line 57, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (84) at non-singleton dimension 3

**Comment by smallclass2016** [comment]
![1 12_0](https://user-images.githubusercontent.com/68237939/149062339-f607204d-c670-4ccc-a400-f127e5965c9c.png)
![1 12_1](https://user-images.githubusercontent.com/68237939/149062363-210254c6-a306-4773-9602-893b6ab29d48.png)

**Comment by glenn-jocher** [comment]
@smallclass2016 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by 948024326** [comment]
> 

I have the same questions...
File "D:\PyQt5-YOLOv5-master\models\yolo.py", line 63, in forward
    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (168) at non-singleton dimension 3

I used others best.pt to detect in my file,but it failed,, wondering how to solve it

**Comment by 948024326** [comment]
> @smallclass2016 👋 嗨，感谢您让我们知道 YOLOv5 可能存在的问题 🚀. 我们在下面创建了一些简短的指南，以帮助用户提供我们需要的内容，以便开始调查可能的问题。
> 
> ## 如何创建一个最小的、可重现的示例
> 在提出问题时，如果您提供他们可以轻松理解并用于**重现问题的****代码**，人们将能够更好地提供帮助。这被社区成员称为创建[最小可重现示例](https://docs.ultralytics.com/help/minimum_reproducible_example/)。重现问题的代码应该是：****[](https://docs.ultralytics.com/help/minimum_reproducible_example/)
> 
> * ✅ **最少**——使用尽可能少的代码来产生问题
> * ✅ **完成**- 提供其他人重现问题所需的所有部分
> * ✅ **可重现**——测试您将要提供的代码以确保它重现问题
> 
> 为了[让 Ultralytics](https://ultralytics.com/)提供帮助，您的代码还应该是：
> 
> * ✅ **当前**- 验证您的代码是否在 GitHub [master](https://github.com/ultralytics/yolov5/tree/master)中是最新的，如有必要，`git pull`或`git clone`新副本以确保您的问题尚未在[master](https://github.com/ultralytics/yolov5/tree/master)中解决。
> * ✅ **未修改**- 您的问题必须可以使用官方 YOLOv5 代码重现而无需更改。[Ultralytics](https://ultralytics.com/)不提供对自定义代码的支持⚠️.
> 
> 如果您认为您的问题符合上述所有标准，请关闭此问题并使用 🐛 **** 带有[最小可重现示例的](https://docs.ultralytics.com/help/minimum_reproducible_example/)**错误报告**[模板](https://github.com/ultralytics/yolov5/issues/new/choose)，可帮助我们更好地理解和诊断您的问题。[](https://docs.ultralytics.com/help/minimum_reproducible_example/)
> 
> 谢谢！ 😃

I have the same questions...
File "D:\PyQt5-YOLOv5-master\models\yolo.py", line 63, in forward
y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i] # wh
RuntimeError: The size of tensor a (80) must match the size of tensor b (168) at non-singleton dimension 3

I used others best.pt to detect in my file,but it failed,, wondering how to solve it

**Comment by glenn-jocher** [comment]
@948024326 any custom model you trained is runnable in any recent copy of YOLOv5. If you're having problems with a checkpoint it may have been trained with outdated code or using a 3rd party fork/clone with modifications.
