### ISSUE TITLE
Inference time degradation in exported ONNX and Torchscript models

### ISSUE THREAD

**Issue by matbun** [ultralytics/yolov5#6279]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I have trained a yolov5 model and I want to export the best model produced by ultralytics framework, `best.pt`, as ONNX and Torchscript. Since these formats should be inference- and performances-oriented I expect their inference time to be at least as good as the pt format.

Unfortunately, despite many trials and much time invested in this task, when I export my best model in ONNX (float32 and float16) and Torchscript (float32 and float16), the inference time reported by `detect.py` is far worse. Best case it's double. Below I report the inference times I have measured (reported by `detect.py`). Time is in milliseconds (ms).

|                  | .pt   | ONNX float32 | ONNX float16 | torchscript Float32 | torchscript Float16 |
|------------------|-------|--------------|--------------|---------------------|---------------------|
| Pre-process (ms) | 0.8   | 1.1          | 2.8          | 1.2                 | 1.7                 |
| Inference (ms)   | 258.4 | 453.2        | 627.3        | 5690.6              | 6100.0              |
| NMS (ms)         | 2.3   | 0.6          | 0.7          | 1.0                 | 0.8                 |

The worse part is that the float32 is always doing better that the float16 version, which makes no sense. Again, float16 should be at least as fast as float32 (if not even better).

**NOTE:** all the export and detect operation have been carried out on GPU.

### Environment

* YOLOv5 🚀 v6.0-187-gf3085ac torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce MX230, 4042MiB)
* OS: Ubuntu 20.04
* Python: Python 3.6.10 :: Anaconda, Inc.

### Minimal Reproducible Example

# Train

```
python3 train.py --img 640  --batch 128 --epochs 200 --data custom_datasets/bosch_trainval_full.yaml --weights yolov5x.pt
```

# Export and detect

### Float32

```
# Export
python export.py --weights best.pt --include onnx --simplify --device 0

# Inference
python detect.py --weights best.onnx  --device 0
```

### Float16

```
# Export
python export.py --weights best.pt --include onnx --simplify --inplace --device 0 --half

# Inference
python detect.py --weights best.onnx --device 0 --half
```

### Float32

```
# Export
python export.py --weights best.pt --include torchscript --simplify --device 0

# Inference
python detect.py --weights best.torchscript --device 0
```

## Float16

```
# Export
python export.py --weights best.pt --include torchscript --simplify --inplace --device 0 --half

# Inference
python detect.py --weights best.torchscript --device 0 --half

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@matbun 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm removing the bug label. Your results are not reproducible. A quick check of ONNX GPU inference is as expected in a common environment, Google Colab.

ONNX FP32 GPU - 17 ms
<img width="1077" alt="Screen Shot 2022-01-12 at 2 20 13 PM" src="https://user-images.githubusercontent.com/26833433/149243684-fad96d36-510d-4bfc-95ec-3a3bb9114070.png">


ONNX FP16 GPU - 12 ms
<img width="1074" alt="Screen Shot 2022-01-12 at 2 20 55 PM" src="https://user-images.githubusercontent.com/26833433/149243767-b6b7aa7b-0eb7-49cc-89c2-9b37da48a66a.png">


We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
