### ISSUE TITLE
branch Classifier train with slow efficiency

### ISSUE THREAD

**Issue by junyuancat1** [ultralytics/yolov5#6283]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Branch classifier runs very well when i try training my small datasets(3000*png(3*128*128));
But when I try with a large dataset(40k*png(3*128*128)), with 8 workers , 128 batch-size, my linux seriously stucked and very strange my cpu usage is not high. 
And gpu usage jumped from 0%->17%->0% 
so that i guess classifier.py may low efficiency when loading such large dataset any way;
Is there any method can help accelerate this?

**Comment by glenn-jocher** [comment]
@junyuancat1 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I just tested classifier.py on CIFAR10, which has 50,000 training PNGs, and everything trains fine, even on a Colab instance with only 2 CPUs. Each epoch trains in 30-40 seconds:

<img width="1459" alt="Screen Shot 2022-01-13 at 1 01 58 PM" src="https://user-images.githubusercontent.com/26833433/149422508-3367ea69-76a2-4768-96c0-7fc5d43faf3b.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by junyuancat1** [comment]
@glenn-jocher Oh I see, it's an IO problem, other person are using the remote as well, so that the IO util rate nearly 100%.
your ex training 391batches which contains totally 50k*pngs in one epoch ,which means your batche-size = 128, and training such efficiency, Which make me jalous~
![image](https://user-images.githubusercontent.com/25675592/149457044-d8a58529-f396-4e1b-a51e-c7a30ec1f9e8.png)
when i fix the IO problem, though I set gpu --device 0,1 , my gpu device still not perform well.  It only used device0 and gpu-util maintain 20%-30%;
Is there any way I can fix this?
thanks for your reply！

**Comment by glenn-jocher** [comment]
@junyuancat1 oh classifier training is only single-GPU at the moment. You can try to train on Colab also just like my example:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

The T4, P100 and V100 GPUs are pretty fast if you can find them.
