### ISSUE TITLE
Questions About Training on tagged release 6.0

### ISSUE THREAD

**Issue by davesargrad** [ultralytics/yolov5#6321]
We really appreciate all the effort that the Ultralytics team is putting into moving the state of the art forward. We’ve been able to use your work to increase our own understanding of how convolutional neural networks can be used to solve real world problems.

Last year we did quite a bit of work with Yolov5 inferencing. Our work was strictly with the pre-trained models that you generated using the YOLOv5s model.

We would like to do more work with Yolov5 this year, and focus increasingly on the weights and biases training. We would like to train from scratch, and would like to begin with COCO and to use the exact parameterization that you guys used to generate YOLOv5s weights and biases. Once we’ve done that, and verified that we understand how to create a working set of weights and biases, then we will shift our look to alternative image sets.

We picked up the trunk at revision 4174 (the v5.0 tag was made on revision 2762). Though we could continue to work with that, its sort of a moving target revision, and we would far prefer using one of the tested and tagged revisions.

I see that the 6.0 release in October was made at revision 5141. Given our growing comfort with the great work that you guys are doing, I would like to start using a tagged release rather than a trunk. This will help us to ensure that we have a structured look at fixes and enhancements that you guys continue to introduce.

Two Questions:
A] Can you point me to the full set of parameter values that you used in the generation of YOLOv5s?
B] Is v6.0  a good tag for us to experiment with this year? Should we be able to both inference and train with the v6.0 code base?

Thanks for your continued efforts. Your work truly benefits the community.

**Comment by glenn-jocher** [comment]
@davesargrad thanks! You can find W&B logs for the official v6.0 P5 models here. You can find commands to reproduce in the model 'Overview' tab:

https://wandb.ai/glenn-jocher/YOLOv5_v6.0_official
<img width="1301" alt="Screen Shot 2022-01-17 at 3 09 36 PM" src="https://user-images.githubusercontent.com/26833433/149853631-f31b84e0-eff4-47df-b7de-df1b19e1aad4.png">

The hyp files you want to use are -low for YOLOv5n/s, -med for YOLOv5m, -high for YOLOv5l/x:
https://github.com/ultralytics/yolov5/tree/master/data/hyps

Most of the intervening work since v6.0 has been on the export side, so there's no new model updates imminent right now. If we do a new release it will probably be v6.1 with the same models before a v7.0 in Q2. We exhausted our cloud credits at all providers last year and just took delivery of a new A100 server, so we should be able to restart our R&D efforts with this soon, but even so we seem to be shifting more towards maturing other aspects like export, classification, introducing segmentation etc. There's a lot of work to do!

**Comment by davesargrad** [comment]
@glenn-jocher Thanks very much Glenn. That's quite useful. I'll keep you updated relative to our progress with 6.0.
