### ISSUE TITLE
YoloV5 1280 models are not working with OpenCV

### ISSUE THREAD

**Issue by bzisl** [ultralytics/yolov5#6368]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Integrations

### Bug

When you train a model of size 1280x1280, OpenCV loads it but it is not possible to do any inference. A general exception is thrown and the program (release or debug version) crash.
Is there structural differences between 640 and 1280 network sizes? 

### Environment

OpenCV 4.5.4

### Minimal Reproducible Example

Any 1280 model produced with YoloV5 and exported to Onnx format will crash when loading into OpenCV

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bzisl i'm not sure what you mean by a 1280 model. Do you mean the P6 models?

Any model is trainable at any image size, but the P6 models feature improved large object detection. See https://github.com/ultralytics/yolov5/releases/tag/v5.0 for an explanation.

Please provide a minimum reproducible example with exact commands to reproduce your bug.

**Comment by bzisl** [comment]
Hi Glenn. I mean, models image size of 1280x1280 instead 640x640. If I do the model at 640x640, everything works fine, but at 1280x1280, OpenCV generates an exception and crashes

**Comment by glenn-jocher** [comment]
@bzisl 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Zengyf-CVer** [comment]
@bzisl 
Can you upload a screenshot of the error message?

**Comment by UNeedCryDear** [comment]
If you use yolov5 P6 model, you should modify the anchors data,which is different from the P5 model.
At the same time, P6 has one more stripe with size of 64 than P5 model.
`
\#models/yolov5s.yaml
anchors:
  \- [10,13, 16,30, 33,23]  # P3/8
  \- [30,61, 62,45, 59,119]  # P4/16
  \- [116,90, 156,198, 373,326]  # P5/32

\#models/hub/yolov5s6.yaml
anchors:
  \- [19,27,  44,40,  38,94]  # P3/8
  \- [96,68,  86,152,  180,137]  # P4/16
  \- [140,301,  303,264,  238,542]  # P5/32
  \- [436,615,  739,380,  925,792]  # P6/64

`

**Comment by bzisl** [comment]
Once I loaded the model into DNN (no problem here), I tried to forward the input for the inference:
```
    cv::dnn::blobFromImage(subimg,
                           blob, 1 / 255.0,
                           cv::Size(mNetWidth, mNetHeight),
                           cv::Scalar(0, 0,0),
                           true, false);
    mNet.setInput(blob);
    std::vector<cv::Mat> netOutputImg;
    mNet.forward(netOutputImg, mNet.getUnconnectedOutLayersNames());
```

When I arrive to **forward(...)**, an exception is thrown:
```
[ERROR:0] global /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/dnn.cpp (3554) getLayerShapesRecursively OPENCV/DNN: [Reshape]:(589): getMemoryShapes() throws exception. inputs=1 outputs=1/1 blobs=0
[ERROR:0] global /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/dnn.cpp (3557) getLayerShapesRecursively     input[0] = [ 1 21 160 160 ]
[ERROR:0] global /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/dnn.cpp (3561) getLayerShapesRecursively     output[0] = [ ]
[ERROR:0] global /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/dnn.cpp (3567) getLayerShapesRecursively Exception message: OpenCV(4.5.4) /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/layers/reshape_layer.cpp:106: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

libc++abi: terminating with uncaught exception of type cv::Exception: OpenCV(4.5.4) /tmp/opencv-20220113-73143-1pcj13/opencv-4.5.4/modules/dnn/src/layers/reshape_layer.cpp:106: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

```

This only happens is the model is trained with **-img 1280** (using images of 1280x1280 size). If I train it with **-img 640** (with images of 640) there is no problem and it works.

**Comment by bzisl** [comment]
Thanks. I will take into account, but the problem rises before applying the anchors.

> If you use yolov5 P6 model, you should modify the anchors data,which is different from the P5 model. At the same time, P6 has one more stripe with size of 64 than P5 model. ` #models/yolov5s.yaml anchors: - [10,13, 16,30, 33,23] # P3/8 - [30,61, 62,45, 59,119] # P4/16 - [116,90, 156,198, 373,326] # P5/32
> 
> #models/hub/yolov5s6.yaml anchors: - [19,27, 44,40, 38,94] # P3/8 - [96,68, 86,152, 180,137] # P4/16 - [140,301, 303,264, 238,542] # P5/32 - [436,615, 739,380, 925,792] # P6/64
> 
> `

**Comment by UNeedCryDear** [comment]
Maybe you should try to export onnx with --imgsz [1280,1280], and loaded new ONNX-model

**Comment by bzisl** [comment]
> Maybe you should try to export onnx with --imgsz [1280,1280], and loaded new ONNX-model

Worked! I feel silly. :-(
Thanks a lot!
