### ISSUE TITLE
Inference made using detect.py differs than inference made using PyTorch Hub inference

### ISSUE THREAD

**Issue by edwardwang1** [ultralytics/yolov5#6394]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have noticed that the inference obtained through the detect.py script differs than the inference made using PyTorch Hub.  At first, I thought the issue was due to a discrepancy between the model downloaded from PyTorch Hub and the local copy of the model. However, the issue persisted even when loading the local model. The model weights were generated using the train.py script. Essentially, the bounding box is tighter in the PyTorch Hub case than the detect.py case.

I found a similar issue here. https://github.com/ultralytics/yolov5/issues/2224

Inference via detect.py
`!python detect.py --img-size 288 --conf 0.01 --project /content/saveDir2/ --save-conf --save-txt --source /content/temptest/ --weights "./yolo50epoch288V2_best.pt"`
`results = model(image).pandas().xywhn[0]`
Results (x_cent, y_cent, width, height, conf) = (0.13 0.43 0.25 0.27 0.80)

Inference via PyTorch Hub 
`model = torch.hub.load('ultralytics/yolov5', 'custom',  path="./yolo50epoch288V2_best.pt",  force_reload=True)`
`results = model(image).pandas().xywhn[0]`
Inference via PyTorch Hub (Local)
`model = torch.hub.load('.', 'custom', path="./yolo50epoch288V2_best.pt", source="local", force_reload=True)`
`results = model(image).pandas().xywhn[0]`
Results (x_cent, y_cent, width, height, conf) = (0.13, 0.43, 0.15,  0.14,  0.59)

Environment
I am running everything in a Google Colab Environment
`YOLOv5 🚀 2022-1-22 torch 1.10.0+cu111 CUDA:0 (Tesla T4, 15110MiB)`
YOLOv5 install
`!git clone https://github.com/ultralytics/yolov5.git`
`!mv ./yolov5/* ./`
`!pip install -r requirements.txt`

The issue also persists on my local machine.
`YOLOv5  v6.0-205-gbd815d4 torch 1.9.0 CUDA:0 (NVIDIA GeForce RTX 3080, 10240MiB)`

**Comment by glenn-jocher** [comment]
@edwardwang1 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible. Inference with detect.py and PyTorch Hub respectively for bus.jpg are below. If you are comparing both you should ensure all parameters are identical including batch size.

![image](https://user-images.githubusercontent.com/26833433/150663082-89ddb5bc-4431-43f5-9771-6269d76a6751.png)

![image](https://user-images.githubusercontent.com/26833433/150663086-f76ea685-5484-4e57-a398-2600c0af65ec.png)




We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by edwardwang1** [comment]
Hi Glenn,

Thanks for the prompt response. I tried the bus example using default yolov5x weights myself, and indeed found no discrepancy. It appears the issue is with my custom weights and custom classes.

I will update if I am able to resolve this.

**Comment by edwardwang1** [comment]
I've determined that my issue was due to not specifying the image size when using PyTorch Hub inference.
Wrong
`results = model(im,).pandas().xywhn[0]`
Correct
`results = model(im, size=288).pandas().xywhn[0]`

I previously didn't include the `size` flag because I already resize my images to 288x288 prior to inference. 
Thanks again to Glenn for putting me on the right track.
