### ISSUE TITLE
wrong results made by tensorrt(8.2)

### ISSUE THREAD

**Issue by Hust-wayne** [ultralytics/yolov5#6439]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![0](https://user-images.githubusercontent.com/42134717/151196985-7c165874-c631-4803-8827-97c199803936.jpg)

**Comment by glenn-jocher** [comment]
@Hust-wayne 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by zhiqwang** [comment]
Hi, I guess the main reason for these is a wrong inputs images, and a Minimal, Reproducible Example here is important to debug for this problem.

**Comment by Hust-wayne** [comment]
hello, first use "export.py" convert .pt to .engine
senond, I only run  "detect.py  --weights  yolov5s.engine  --source bus.jpg"  (use v6.0 )

**Comment by Hust-wayne** [comment]
hello, first use "export.py" convert .pt to .engine
senond, I only run  "detect.py  --weights  yolov5s.engine  --source bus.jpg"  (use v6.0 )

**Comment by glenn-jocher** [comment]
@Hust-wayne TensorRT export example is shown in Colab notebook and everything works correctly:

```bash
# TensorRT 
# https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip
!pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
!python export.py --weights yolov5s.pt --include engine --imgsz 640 640 --device 0  # export
!python detect.py --weights yolov5s.engine --imgsz 640 640 --device 0  # inference
```

<img width="1777" alt="Screenshot 2022-01-28 at 06 56 02" src="https://user-images.githubusercontent.com/26833433/151494948-1113fe27-df54-4658-8331-5e19bd3f9db7.png">

**Comment by Hust-wayne** [comment]
It may be caused by (ubantu)WSL
