### ISSUE TITLE
增加了P2层，去掉p5层后可训练成功，但运行detect.py不成功，请问还需要更改其他参数吗？

### ISSUE THREAD

**Issue by SLLiu-111** [ultralytics/yolov5#6458]
已将detect.py中的图像改成了自己图像的路径，并将模型问你件改为自己加了P2层后的新的.pt文件；请问还需要更改其他参数吗？

Model Summary: 224 layers, 7003423 parameters, 0 gradients, 15.8 GFLOPs
image 1/2877 /data1/lsl/yolov5/yolov5-master2/data/images/004782.jpg: Traceback (most recent call last):
  File "detect.py", line 204, in <module>
    detect(**vars(opt))
  File "/root/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 91, in detect
    pred = model(img, augment=augment)[0]
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/lsl/yolov5/yolov5-master2/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/data1/lsl/yolov5/yolov5-master2/models/yolo.py", line 155, in forward_once
    x = m(x)  # run
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/lsl/yolov5/yolov5-master2/models/common.py", line 210, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 23 and 24 (The offending index is 0)

**Comment by mrzhuzhe** [comment]
official config has a P2, P3, P4, P5 detector
you can use this
yolov5\models\hub\yolov5-p2.yaml

**Comment by SLLiu-111** [comment]
感谢回复，按照上述的yolov5-p2.yaml，可以训练成功，但是在用训练得到的best.pt文件，在运行detect,py文件时，无法运行成功，并显示错误：
  File "detect.py", line 204, in <module>
    detect(**vars(opt))
  File "/root/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 91, in detect
    pred = model(img, augment=augment)[0]
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/lsl/yolov5/yolov5-master2/models/yolo.py", line 123, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/data1/lsl/yolov5/yolov5-master2/models/yolo.py", line 155, in forward_once
    x = m(x)  # run
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/lsl/yolov5/yolov5-master2/models/common.py", line 210, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 23 and 24 (The offending index is 0)
，请问在添加p2层之后，如何能正确运行detect,py？

**Comment by sandy-0326** [comment]
你解决了吗？

**Comment by SLLiu-111** [comment]
你好，没有解决，我只是简单的增加了检测层，没有其他改动，训练好模型之后，运行detect.py，就会报错，求帮忙，再次感谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ultralytics/yolov5] 增加了P2层，去掉p5层后可训练成功，但运行detect.py不成功，请问还需要更改其他参数吗？ (Issue #6458)




 
你解决了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zephyr69** [comment]
Did you try to detect with augmentation enabled? I had a similar issue, and the error disappeared only after disabling augmentation.

**Comment by SLLiu-111** [comment]
I just call the trained model with the added P2 layer directly, without changing any other code in detec.py, but running detect.py does not work.
Also, when calling the trained model using only P2, P3 and P4 of the original network, detect.py works fine.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ultralytics/yolov5] 增加了P2层，去掉p5层后可训练成功，但运行detect.py不成功，请问还需要更改其他参数吗？ (Issue #6458)




 
Did you try to detect with augmentation enabled? I had a similar issue, and the error disappeared only after disabling augmentation.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wildwolff** [comment]
I meet the same issue too.It seems that the augment step has some error. the program works when i remove --agument.

**Comment by glenn-jocher** [comment]
@wildwolff 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Augmented inference with `--augment` is working correctly:

<img width="947" alt="Screen Shot 2022-04-01 at 3 40 05 PM" src="https://user-images.githubusercontent.com/26833433/161275034-a45d8ca1-17a8-41ac-b793-dbd11513f819.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
