### ISSUE TITLE
How to get mAP values of each class on validation set?

### ISSUE THREAD

**Issue by jpiyu** [ultralytics/yolov5#6459]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to get mAP values of each class on validation set? There is no test.py file which is mentioned in other issues.

**Comment by glenn-jocher** [comment]
@jpiyu test.py was renamed to val.py a long time ago.

**Comment by jpiyu** [comment]
can we infer on rectangular size images?

**Comment by glenn-jocher** [comment]
@jpiyu that's the default workflow

**Comment by jpiyu** [comment]
![Capture1](https://user-images.githubusercontent.com/32515360/151494156-91ae40df-597c-4b14-9b7f-a69913dcf6a3.JPG)
while inferencing i get these values, what does it signify? As its mentioned in val.py that img can be int only while passing image size. So how can i get inference for 640*480 img size?

**Comment by glenn-jocher** [comment]
@jpiyu specify long side only:
```
python val.py --imgsz 640
```

**Comment by jpiyu** [comment]
Thankyou, but what does the values 384*640, 480*640 mean?

**Comment by glenn-jocher** [comment]
Inference shape

**Comment by jpiyu** [comment]
on what basis do we get these different inference shapes?

**Comment by glenn-jocher** [comment]
based on your image shapes with constraints applied

**Comment by Bru-Souza** [comment]
@glenn-jocher I'm trying to run val.py with a custom model, but getting some errors: 

![image](https://user-images.githubusercontent.com/79461679/151639672-76ae349d-630c-4229-a60c-0cf0d23fa726.png)

This is my multiclass.yaml:
![image](https://user-images.githubusercontent.com/79461679/151639771-f6b0439c-a5f8-41c3-aa6c-455c6da1c0ea.png)

Do you know what could be wrong?

**Comment by glenn-jocher** [comment]
@Bru-Souza 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your code is very out of date.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
