### ISSUE TITLE
YOLOv5 support model-parallel training with multi gpu?

### ISSUE THREAD

**Issue by p890040** [ultralytics/yolov5#6523]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi guys!

I have a question about this. 
Does yolov5 provide model-parallel training with multi gpu?
I have checked [Multi-GPU Training](https://github.com/ultralytics/yolov5/issues/475) tutorial and issues.
I found no one was talking about this function.

Because I have two GPU and wanna set img_size larger, and batch size 1 is still OOM.
So I'm trying some way to achieve it.

Thanks!

**Comment by glenn-jocher** [comment]
@p890040 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by chiehpower** [comment]
hi @glenn-jocher 

Thanks for your detailed explanation!

Let me elaborate more on what my friend @p890040 and I encountered problems, and we will be grateful if you can give us some hints!

Recently we got a dataset that the model could get a good performance on it after we adjusted a higher input size.
Hence, we plan to adjust the larger input size to see the results; however, because the input size was very huge (~3360) even we already set the batch size as 1, the training still happens OOM issue. We ask for the best performance, so we have to use the biggest model size for training (i.e., 5x6). Our GPU specifications are two A100 (40GB), and we know there is a way of DistributedDataParallel from YOLO, but it cannot solve the OOM issue if we use a single image (batch size=1) with large input size. 

My train of thought is that suppose training a single image with input size 3360 on YOLOv5x6 weight will account for 50GB GPU memory. I want to allocate 25 GB memory for first A100 GPU, and allocate the rest of 25 GB memory for second A100 GPU. 

As far as I know, PyTorch DDP could combine with **Model Parallelism** [ref](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#combine-ddp-with-model-parallelism). I am wondering does YOLOv5 support this feature? Or is there any tip for us to handle the large input size situation?

Thank you in advance!

Best regards,
Chieh

**Comment by glenn-jocher** [comment]
No there is no model parallelism support currently.

It looks like on a single device YOLOv5x6 at --img 3840 will use about 53GB of CUDA memory, so you should be fine to train at 3360 on a single 40GB device.

<img width="1487" alt="Screenshot 2022-02-03 at 16 19 01" src="https://user-images.githubusercontent.com/26833433/152371698-d827fe92-3fd7-47a9-ade8-e913c0edbabd.png">

**Comment by p890040** [comment]
@glenn-jocher 
Thanks for your kind response!
We will try to figure out the solution, even add the model-parallelism implement. Meanwhile, we're looking to the powerful YOLOv5 team to release this feature ^___^.

**Comment by glenn-jocher** [comment]
@p890040 hi, thank you for your feature suggestion on how to improve YOLOv5 🚀! Yes this might be a useful addition, though I think parallelism is typically more used in language models where the parameter count can run into the billions.

The fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.

**Comment by chiehpower** [comment]
hi @glenn-jocher 

Thanks for your reply and testing!
Sure! We will keep trying and developing on YOLOv5! 

BR,
Chieh
