### ISSUE TITLE
The size of tensor a (60) must match the size of tensor b (56) at non-singleton dimension 2

### ISSUE THREAD

**Issue by OrjwanZaafarani** [ultralytics/yolov5#6555]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm getting the following error while trying to detect. I'm getting it only sometimes when running the same block of code again and again.
```
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/dmmil/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/dmmil/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/dmmil/Desktop/nas/vision/Orjuwan/Abjad/facesearch/modules/logoDetectionModel.py", line 27, in detect
    results = self.logoModel(image)
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "yolov5/models/common.py", line 286, in forward
    y = self.model(x, augment, profile)[0]  # forward
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "yolov5/models/yolo.py", line 121, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "yolov5/models/yolo.py", line 152, in forward_once
    x = m(x)  # run
  File "/home/dmmil/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "yolov5/models/yolo.py", line 60, in forward
    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i]) * self.stride[i]  # xy
RuntimeError: The size of tensor a (60) must match the size of tensor b (56) at non-singleton dimension 2
```

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by develop-productivity** [comment]
I have the same question.Have you solved this problem yet?

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani @develop-productivity are you two running multiple YOLOv5 models, i.e. in a multithreaded environment?

**Comment by OrjwanZaafarani** [comment]
@glenn-jocher yes true

**Comment by glenn-jocher** [comment]
@OrjwanZaafarani see https://github.com/ultralytics/yolov5/issues/5803#issuecomment-979963058

**Comment by develop-productivity** [comment]
No.I download the version tags v5.0 and just modify the weights  from yolov5s.pt to yolov5m.pt in detect.py ,then rerun the detect.py

**Comment by develop-productivity** [comment]
> @OrjwanZaafarani @develop-productivity are you two running multiple YOLOv5 models, i.e. in a multithreaded environment?

No.I download the version tags v5.0 and just modify the weights  from yolov5s.pt to yolov5m.pt in detect.py ,then rerun the detect.py

**Comment by ANUPAMA0221** [comment]
> > @OrjwanZaafarani @develop-productivity are you two running multiple YOLOv5 models, i.e. in a multithreaded environment?
> 
> No.I download the version tags v5.0 and just modify the weights from yolov5s.pt to yolov5m.pt in detect.py ,then rerun the detect.py

Did you solve the problem? Even I am having same problem.. Not able to figure it out ;)

**Comment by glenn-jocher** [comment]
Thanks for sharing the details, @ANUPAMA0221. Modifying the weights from `yolov5s.pt` to `yolov5m.pt` should not cause this error. 

To further investigate the issue, it would be helpful if you could provide a minimal reproducible example by following the guidelines mentioned above. This will assist us in understanding and resolving the problem more effectively. 

Please let us know if you have any further information or if you need any assistance with creating a minimal reproducible example.

**Comment by Xueqian111** [comment]
> > @OrjwanZaafarani @develop-productivity are you two running multiple YOLOv5 models, i.e. in a multithreaded environment?
> 
> No.I download the version tags v5.0 and just modify the weights from yolov5s.pt to yolov5m.pt in detect.py ,then rerun the detect.py

Have you solved this problem? I just run yolov5s.pt and i meet this error too.

**Comment by glenn-jocher** [comment]
@Xueqian111 hi there! Thanks for sharing your experience. It seems that this issue is not related to running multiple YOLOv5 models in a multithreaded environment, as you mentioned.

If you are encountering the same error with `yolov5s.pt`, it indicates that there might be an issue with the code or configuration. To better understand and help resolve the problem, it would be helpful if you could provide more information, such as a minimal reproducible example or any relevant code snippets.

Please let us know if you have any additional information or if you need further assistance.
