### ISSUE TITLE
Thread to update frames coming from RTSP not called 

### ISSUE THREAD

**Issue by ahmedosama9777** [ultralytics/yolov5#6557]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello All.

I am trying to run YOLOv5 on an rtsp stream, I am facing an issue where the update method in "LoadStreams" class isn't called normally, I am not sure why.  I get the output  **"0: 384x640 3 cars, 1 train, 4 trucks, Done. (0.012s)"**, but for the same frame, although the frame is done being processed, and then the software keeps processing the same frame without calling the update method. I added a print in the update function to see if it's called but found out it isn't.

Thanks in advance.

**Comment by glenn-jocher** [comment]
@ahmedosama9777 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ahmedosama9777** [comment]
I discovered the issue, as I was using the Yolov5 repo inside a flask application of my development, I discovered that in the function "update" which is run as a serprate thread it had the line "time.sleep()", which when changed to eventlet.sleep() sorted the issue. Happy coding.

**Comment by glenn-jocher** [comment]
@ahmedosama9777 got it. Is this a change we should make to the repo?

**Comment by ahmedosama9777** [comment]
Yes. I do think so. I can make a pull-request.

**Comment by glenn-jocher** [comment]
@ahmedosama9777 great thanks!

**Comment by ahmedosama9777** [comment]
All done.  Passed all CI tests. Thanks, hope it's a usefull tiny addition.
