### ISSUE TITLE
Script "classifier.py" not working 

### ISSUE THREAD

**Issue by decadance-dance** [ultralytics/yolov5#6597]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

I needed to get with yolo only a part for classification. I cloned the repository from the classification branch and just repeated the recommended code.
After running I get this error:
```
  Traceback (most recent call last):
  File "/home/NIX/dronov/HDD/yolov5/my_.py", line 9, in <module>
    classify(model, size=128, file=f)
  File "/home/NIX/dronov/HDD/yolov5/classifier.py", line 242, in classify
    results = model(im)
  File "/home/NIX/dronov/anaconda3/envs/zero/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/NIX/dronov/HDD/yolov5/models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/NIX/dronov/HDD/yolov5/models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/home/NIX/dronov/anaconda3/envs/zero/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/NIX/dronov/HDD/yolov5/models/yolo.py", line 58, in forward
    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)
RuntimeError: The expanded size of the tensor (1) must match the existing size (16) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 16, 16, 2]
```

Thanks for any help

### Minimal Reproducible Example

    from classifier import *
    
    model = torch.load('path/to/best.pt', map_location=torch.device('cpu'))['model'].float()
    files = Path('../datasets/mnist/test/7').glob('*.png')  # images from dir
    for f in list(files)[:10]:  # first 10 images
        classify(model, size=128, file=f)

This code is run from root dir of yolov5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@decadance-dance👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.  I trained a classifier model and ran inference following Usage examples and everything works correctly, i.e. your issue is not reproducible. It all took about 3 minutes in a Colab notebook. 

<img width="1595" alt="Screenshot 2022-02-10 at 14 59 20" src="https://user-images.githubusercontent.com/26833433/153422856-8e8aadf7-15ae-4d96-8848-a2f10a2c8423.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
