### ISSUE TITLE
Why memory usage is higher when I use RTMP stream?

### ISSUE THREAD

**Issue by iskorini** [ultralytics/yolov5#6616]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I've YoloV5 installed on a Conda environment and I trained a v5s to detect barcodes. 
When I use detect script on a local video (3840 × 2160, 60fps, H265) the model occupies around 1.3gb of GPU memory. 
![photo_2022-02-11_18-34-12](https://user-images.githubusercontent.com/12392097/153640686-937d184a-b92d-4de1-bfa2-8b99e4fe73db.jpg)
But if i try to stream with RTMP protocol (1280*720, 25fps, H264, 2mbps) from my iPhone it occupies more than 5.4gb on my GPU.
![photo_2022-02-11_18-33-56](https://user-images.githubusercontent.com/12392097/153640569-6bd7da47-18ff-4eb8-8ccb-11206946a951.jpg)

I can´t understand why there is this huge difference.

### Additional

- local video: python detect.py --weights pesi.pt --img 640 --conf 0.25 --source IMG_3227.MOV --save-crop --device 0
- RTMP stream: python detect.py --weights pesi.pt --img 640 --conf 0.25 --source rtmp://127.0.0.1/live/test --save-crop --device 0

- OS: PopOS 21.10 (GPU in hybrid graphics)
- RTMP Server: https://hub.docker.com/r/jasonrivers/nginx-rtmp/
- Python: 3.8.5
- GPU: RTX2070 Max-Q (8gb)
- Driver Version: 510.39.01
- CUDA: 11.6

**Comment by glenn-jocher** [comment]
@iskorini 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm unable to reproduce with your stream address:

<img width="678" alt="Screenshot 2022-02-12 at 12 54 41" src="https://user-images.githubusercontent.com/26833433/153710276-d4de54fe-273a-46e7-b1b8-eee1a74fb15f.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by iskorini** [comment]
> @iskorini wave hi, thanks for letting us know about this possible problem with YOLOv5 rocket. I'm unable to reproduce with your stream address:
> 
> <img alt="Screenshot 2022-02-12 at 12 54 41" width="678" src="https://user-images.githubusercontent.com/26833433/153710276-d4de54fe-273a-46e7-b1b8-eee1a74fb15f.png">
> 
> We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * white_check_mark **Minimal** – Use as little code as possible to produce the problem
> * white_check_mark **Complete** – Provide all parts someone else needs to reproduce the problem
> * white_check_mark **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * white_check_mark **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * white_check_mark **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code warning.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the bug **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! smiley

Hi, thanks for your reply.
For my test env I hosted on docker a local Nginx server with rtmp-module (that's why I use localhost address).
`docker run -p 1935:1935 -p 8080:8080 jasonrivers/nginx-rtmp`
After that I installed _Larix_ application on my iPhone, then I configured it with the IP address of the machine with Nginx, in this particular case is my pc.
For test purpose you can use also OBS Studio on your local machine instead of Larix on iOS.

EDIT: Same issue occurs with any youtube videos.

**Comment by Kilroy93** [comment]
I have the same problem with youtube videos
