### ISSUE TITLE
Confusion matrix is not updated when no detections

### ISSUE THREAD

**Issue by sandeepjana** [ultralytics/yolov5#6644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Validation

### Bug

Currently, confusion matrix is not updated when the model makes zero detections for a particular image:
https://github.com/ultralytics/yolov5/blob/ca0a00784d99df3a89bf73c0847016b0d81a8e3e/val.py#L218 

I believe the matrix should be updated to increment the count of ground truth objects in this case. Specifically the following line in `ConfusionMatrix` should be executed for the missed detections:
```
self.matrix[self.nc, gc] += 1 
```

Thanks for the great project!

### Environment

Any environment

### Minimal Reproducible Example

Run `val.py` script in such way the model misses all ground truth objects.
```
python val.py --weights yolov5x.pt --data coco.yaml --img 640 --iou 1.0 --conf 1.0
```
Check the last row in the confusion matrix plot saved in `runs/val/exp<id>` which shows all zeros. However, it should show the number of actual objects in each class.

**Comment by glenn-jocher** [comment]
@sandeepjana hi, thanks for the comprehensive code review! One other user has mentioned this in the past.

In _theory_ this might be problematic, but in _practice_ this is not a problem because val.py should always be run at near-zero confidence thresholds (i.e. default is 0.001 and a Warning is given if this is increased) in order to produce a complete P-R curve for mAP computation. This means that every image that val.py processes will have thousands, or even tens of thousands of detections, most being FPs naturally that fall to the bottom right of the P-R curve.
https://github.com/ultralytics/yolov5/blob/ca0a00784d99df3a89bf73c0847016b0d81a8e3e/val.py#L354-L355

**Comment by sandeepjana** [comment]
@glenn-jocher makes sense! Except that I was not looking for mAP values but the confusion matrix -- as the latter is computed separately. So I conveniently ignored this warning message. Hope another user will not run into this!

**Comment by glenn-jocher** [comment]
@sandeepjana the fastest and easiest way to incorporate your ideas into the official codebase is to submit a Pull Request (PR) implementing your idea, and if applicable providing before and after profiling/inference/training results to help us understand the improvement your feature provides. This allows us to directly see the changes in the code and to understand how they affect workflows and performance.

Please see our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
