### ISSUE TITLE
Not running-Model Ensembling with custom weight and yolov5x6.pt

### ISSUE THREAD

**Issue by Thanossrs** [ultralytics/yolov5#6676]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

**!python detect.py --weights ./yolov5x6.pt ./best_allenduserdataset_notransf.pt --img 1280 --augment --class 0 --conf 0.4 --source ./video2.mp4**

Hello, why am I getting the following problem when I execute the above command?
thanks

**RuntimeError: Sizes of tensors must match except in dimension 2. Got 6 and 85 (The offending index is 0)**

**Comment by glenn-jocher** [comment]
@Thanossrs you can only ensemble models trained on the same classes.

**Comment by Thanossrs** [comment]
Yes, you are correct.
Actually, I detect humans (annotated as 'pedestrian') in my custom model. How could I combine my custom model with yolov5x6.pt that uses a different label ('person')?
Any idea how I could combine them without retraining my custom model?
Thank you

**Comment by glenn-jocher** [comment]
@Thanossrs there's no such thing as 'combining' models. TTA simply runs each and concatenates outputs before NMS.

You can concatenate COCO trained models, i.e. YOLOv5s with YOLOv5m.

**Comment by Thanossrs** [comment]
@glenn-jocher I retrain my model with the same class from yolov5x6.pt (i mean as a 'person') and still got the below error.

**RuntimeError: Sizes of tensors must match except in dimension 2. Got 6 and 85 (The offending index is 0)**

Any idea?
thank you

**Comment by glenn-jocher** [comment]
@Thanossrs 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
