### ISSUE TITLE
val.py output images are inverted

### ISSUE THREAD

**Issue by Roland-Pfeiffer** [ultralytics/yolov5#6697]
When running val.py on a set of annotated images, the resulting output images are inverted. Any ideas why this is happening or what the implications are?

![val_batch1_labels](https://user-images.githubusercontent.com/44983360/154718122-29cc67a8-9801-4db1-b421-8b7170449d2a.jpg)

**Comment by glenn-jocher** [comment]
@Roland-Pfeiffer 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Nacriema** [comment]
I have the same issue, the fact that when we put the same directory path inside `train`, `test` and `val` data's config `yaml` file will raise this bug. So try to split out the data to difference folder to avoid this behavior.

**Comment by glenn-jocher** [comment]
@Nacriema Thanks for sharing your insights on this! Indeed, duplicating the directory path inside the `train`, `test`, and `val` data's config `yaml` file can cause this issue. Splitting the data into different folders can effectively prevent this behavior.

Feel free to reach out if you have any further questions or require assistance with anything else. 👍
