### ISSUE TITLE
Tensorrt export fail when changing default values of fp,imgsize,batchsize.

### ISSUE THREAD

**Issue by fnando1995** [ultralytics/yolov5#6699]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

What is the correct way to export a model for the tensorrt backend when changing arguments (fp,image size, batch size)?

### Additional

I have tested the export.py script to convert the .pt model to a .engine model (tensortrt, trt) but with no changes, this means, image size 640, one image at the time, fp32. And works! (must say that the export.py was executed in a jetson nano of 4gb, since the model should be converted using the especific hardware, as I read in some nvidia forums). But when trying:

`python3 export.py --weights weights/fp32_320/yolov5n.pt --include engine --device 0 --imgsz 320 320 --batch-size 8 --half`

the model compiles as expectef, but when using detect.py from [Bluemirros](https://github.com/BlueMirrors/Yolov5-TensorRT) this problem shows:

```
[CVU-Info] Building and Optimizing TRT-Engine for input_shape=(640, 640). This might take a few minutes for first time.
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +197, GPU +0, now: CPU 241, GPU 2161 (MiB)
[TensorRT] INFO: Loaded engine size: 11 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 253 MiB, GPU 2173 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +248, now: CPU 418, GPU 2428 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +240, GPU +350, now: CPU 658, GPU 2778 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 658, GPU 2778 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 658 MiB, GPU 2778 MiB
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation begin: CPU 646 MiB, GPU 2766 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 646, GPU 2766 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 646, GPU 2766 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 647 MiB, GPU 2766 MiB
Traceback (most recent call last):
  File "detect.py", line 114, in <module>
    output_dir
  File "detect.py", line 34, in detect_batch
    for w in range(warmup):   model(image_warmup)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/core.py", line 96, in __call__
    outputs = self._model(processed_inputs)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 256, in __call__
    outputs = self._inference(inputs)
  File "/usr/local/lib/python3.6/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 278, in _inference
    cuda.memcpy_htod_async(inp['device'], inp['host'], self._stream)
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: invalid argument
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1242, GPU 3369 (MiB)
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
test_all.sh: line 10:  2847 Aborted                 (core dumped)
```

Is there any recommendation you can give me?

**Comment by glenn-jocher** [comment]
@fnando1995👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.  Issues arising from external/3rd party repositories should be raised directly on those repositories.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by fnando1995** [comment]
Will close this, since the problem seems to be not in yolov5 code, but in the other repo used for detections. Thanks.
