### ISSUE TITLE
How can I give bounding box color according to different objects found in image manually?

### ISSUE THREAD

**Issue by ShaileshSarda** [ultralytics/yolov5#670]
## 🚀 Feature
Suppose in a multi-class classification problem, I want to give custom colors like RED for the dog, BLUE for the cat, and GREEN for Horse. How can I make changes in code or can add these color attributes in supportive files to render these features?

**Comment by glenn-jocher** [comment]
@ShaileshSarda colors are defined directly in detect.py:
https://github.com/ultralytics/yolov5/blob/3fcd365ba38613dee17995e9baf2fa5117727d4b/detect.py#L55-L58

**Comment by Ownmarc** [comment]
Look at « colors » In detect.py, its randomly generated using numpy. You can define it there as a list of rgb values where the index of the list matches the index of the class you want the color for.

**Comment by glenn-jocher** [comment]
On this topic I might also add that our train and test images are generated with a fixed color order using a matplotlib dependency:
https://github.com/ultralytics/yolov5/blob/3fcd365ba38613dee17995e9baf2fa5117727d4b/utils/general.py#L1013-L1018

**Comment by rishrajcoder** [comment]
how do I make the colour of bounding box same as the colour of detected object? ex. If im detecting helmets, then bounding box colour should match the colour of helmet

**Comment by glenn-jocher** [comment]
@rishrajcoder there's no simple way to do this.

**Comment by rishrajcoder** [comment]
> @rishrajcoder there's no simple way to do this.

Can you please give any guidance on how to approch this problem, as I couldn't find any resource related to this!

**Comment by glenn-jocher** [comment]
@rishrajcoder colors are assigned per class based on the Ultralytics color palette here:
https://github.com/ultralytics/yolov5/blob/c6c88dc601fbdbe4e3391ba14245ec2740b5d01a/utils/plots.py#L28-L44

**Comment by joicejoseph3198** [comment]
> how do I make the colour of bounding box same as the colour of detected object? ex. If im detecting helmets, then bounding box colour should match the colour of helmet

Did you have any success with that? I'm trying to do something similar

**Comment by xr-dev-saurabh** [comment]
i have the same question. can you help if you finded the solution. My detected image is black car and i want the black boundibg box

**Comment by Aoobi** [comment]
> i have the same question. can you help if you finded the solution. My detected image is black car and i want the black boundibg box

Hi,

You could try getting average pixel values of the area inside the box, and plotting the box using this color. It would not be perfect, but probably close, depending on how much % of box is "occupied" by your object. 
You can also use median, because i guess generally more than 50% of bounding box area should be filled by your object, if it is not a very weird shape.

**Comment by shreyasvedpathak** [comment]
@rishrajcoder @usaurabh02 I was able to fix this, and the results are excellent. We require the coordinates of the bounding box. From there, we can further limit our algorithm to our ROI (in @rishrajcoder's example, a helmet, which I assume would be on the top part of the bbox, so we can just select the top 40% of the suggested bounding box).

1. Find the bounding box (has to be done by you, in step 2 I assume you have xmin, ymin, ymin, ymax).
We get the proposed bounding box like this:
![bbox](https://user-images.githubusercontent.com/68227226/130432974-79a1fe7f-bda2-4f06-bbc8-e1832c2dfb26.png)

2. Crop the bounding box area according to your region of interest (you can play with the `factor` variable to select ROI. Here, I'm taking top 25% of the bounding box).
    ```python
    factor = 4
    y1, x1, y2, x2 = box
     _y2 = y2 - (y2 - y1) // 4
    ```
    After selecting ROI:
    ![ROI](https://user-images.githubusercontent.com/68227226/130433069-1e515038-a57c-47d7-a0e7-65624af05099.png)

3. Use this function to find out which colour is dominant in the given ROI. Credits to [this person on stackoverflow.](https://stackoverflow.com/a/50900143/15226638)
```python
def unique_count_app(a):
    '''
    a: NumPy array i.e. the ROI from your image
    Returns: tuple (r, g, b)
    '''
    colors, count = np.unique(
        a.reshape(-1, a.shape[-1]), axis=0, return_counts=True)
    return colors[count.argmax()]

```
Now, you can use the colour returned by that function which is a tuple (r,g,b) and plot the box. 

4. **(Optional)** I was ecstatic since my last experiment had succeeded, so I proceeded to do the following. We may provide a list of different colours, and the following function will take the colour returned by step 3's function and select the closest colour from our provided list of colours. I just calculate Euclidean distance to determine the nearest colour. You can attempt and experiment with various techniques to get the closest color.
```python
def closest(color):
    '''
    Parameter:
    colour: tuple (r, g, b)
    Returns:
    a list, which has [r, g, b] value for closest color from the passed `color` and name of colour
    '''
    color_map = {0: "blue",
                 1: "yellow",
                 2: "orange",
                 3: "white"}
    
    colors = np.array([[0, 128, 255], 
                       [232, 215, 0], 
                       [255, 145, 0], 
                       [255, 255, 255]])
    color = np.array(color)
    distances = np.sqrt(np.sum((colors-color)**2, axis=1))
    index_of_smallest = np.where(distances == np.amin(distances))
    idx = index_of_smallest[0][0]
    return colors[idx], color_map[idx]

``` 
It will return a list that has to be converted to a tuple (r, g, b), now this can be used to draw the box.
Final result is something like this:

![download](https://user-images.githubusercontent.com/68227226/130432715-d78b82f9-9102-403e-83a4-d474c2b64ac0.png)
![download (1)](https://user-images.githubusercontent.com/68227226/130434502-98db9bd4-8a72-43a6-b160-d141d0266ef8.png)

**Comment by AbinJilson** [comment]
I want to change the color of the bounding box in such a way that if the accuracy is more than 80% it should be green otherwise red. if possible someone give me the code for it please

**Comment by glenn-jocher** [comment]
@AbinJilson you can customize annotation arguments in detect.py here:
https://github.com/ultralytics/yolov5/blob/c13d4ce7ef30acc78e3dbdd9aa4f17e01ed34521/detect.py#L169

**Comment by AbinJilson** [comment]
can you give me the modified version of code according to my requirements??

**Comment by mansi733** [comment]
How can we change the bounding box color of different classes using the torch.hub.load?

**Comment by glenn-jocher** [comment]
> @AbinJilson you can customize annotation arguments in detect.py here:
> 
> https://github.com/ultralytics/yolov5/blob/c13d4ce7ef30acc78e3dbdd9aa4f17e01ed34521/detect.py#L169

**Comment by SyedShoeb22** [comment]
@shreyasvedpathak can you please help with the code
