### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JIAHAO-code-del** [ultralytics/yolov5#6709]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, ultralytics!
I ran into the following problem when I ran the train.py file
When the program runs to this step as shown in the figure, there is no response, neither an error is reported nor continued to run.
The running result is as follows：
train: Scanning 'D:\python_pycharm\yolov5-5.0\yolov5-5.0\mydata\labels\train.cache' images and labels... 400 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 400/400 [00:00<?, ?it/s]
val: Scanning 'D:\python_pycharm\yolov5-5.0\yolov5-5.0\mydata\labels\train.cache' images and labels... 400 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████| 400/400 [00:00<?, ?it/s]
![QQ截图20220220204026](https://user-images.githubusercontent.com/80141587/154842910-2a83412f-b699-4c2f-ae52-b27756699db4.png)
![QQ截图20220220204049](https://user-images.githubusercontent.com/80141587/154842939-bd71d997-a2b2-423d-94dd-8f031a42fe74.png)
Why is this？

**Comment by glenn-jocher** [comment]
@JIAHAO-code-del 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
