### ISSUE TITLE
How to crop images when yolov5 onxx model is loaded?

### ISSUE THREAD

**Issue by karndeepsingh** [ultralytics/yolov5#6727]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I trained a yolov5 model on my dataset and converted into onxx formate. How do I crop the images while doing the prediction? When I was loading the model using .pt file I used to load it using torch.hub.load() function and crop() method was inbuit. How to do similar crop with onxx model loaded? As i want to deploy my yolo model on azure machine, how I can load my model and do the necessary cropping of detected objects?

Your suggestions would be helpful/
Thanks

**Comment by glenn-jocher** [comment]
@karndeepsingh export.py automatically displays Usage examples for exported models. Just follow those.

<img width="1551" alt="Screenshot 2022-02-21 at 12 39 03" src="https://user-images.githubusercontent.com/26833433/154948258-ea686f76-42c4-4793-8cc8-ef66ab98d077.png">

**Comment by karndeepsingh** [comment]
I don't want to download all the files from "ultralytics/yolov5" always in the following code:
```
model = torch.hub.load('ultralytics/yolov5', 'custom', path='./yolov5/runs/train/exp58/weights/best.pt')
```
I have already downloaded the yolov5 files from ultranalytics repository and changed the path in the code:
```
model = torch.hub.load('./yolov5', 'custom', path='./yolov5/runs/train/exp58/weights/best.pt',source="local")
```
And got following error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_32481/4274527046.py in <module>
     17                                 infix_finditer=infix_re.finditer,
     18                                 token_match=None)
---> 19 model = torch.hub.load('./yolov5', 'custom', path='./yolov5/runs/train/exp58/weights/best.pt',source="local")
     20 nlp= spacy.load("./nlp_model/model-best_20",)
     21 nlp.add_pipe('sentencizer')

~/anaconda3/envs/spacy/lib/python3.8/site-packages/torch/hub.py in load(repo_or_dir, model, source, force_reload, verbose, skip_validation, *args, **kwargs)
    397         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
    398 
--> 399     model = _load_local(repo_or_dir, model, *args, **kwargs)
    400     return model
    401 

~/anaconda3/envs/spacy/lib/python3.8/site-packages/torch/hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    426 
    427     entry = _load_entry_from_hubconf(hub_module, model)
--> 428     model = entry(*args, **kwargs)
    429 
    430     sys.path.remove(hubconf_dir)

/media/gsatis/ssdnvme/karndeep/Parties_Project/ner&rel/rel_component_1/yolov5/hubconf.py in custom(path, autoshape, verbose, device)
     63 def custom(path='path/to/model.pt', autoshape=True, verbose=True, device=None):
     64     # YOLOv5 custom or local model
---> 65     return _create(path, autoshape=autoshape, verbose=verbose, device=device)
     66 
     67 

/media/gsatis/ssdnvme/karndeep/Parties_Project/ner&rel/rel_component_1/yolov5/hubconf.py in _create(name, pretrained, channels, classes, autoshape, verbose, device)
     28     from models.yolo import Model, attempt_load
     29     from utils.general import check_requirements, set_logging
---> 30     from utils.google_utils import attempt_download
     31     from utils.torch_utils import select_device
     32 

ModuleNotFoundError: No module named 'utils.google_utils'

```
But utils folder has googl_utils.py file. I don't know why it is showing such error even though files are present.
Any suggestions on this. Or different way to load the model/

**Comment by glenn-jocher** [comment]
@karndeepsingh 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
