### ISSUE TITLE
Syntax Error Issue when running train.py

### ISSUE THREAD

**Issue by edehino** [ultralytics/yolov5#6816]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi, I added this as a question a few days ago but I think it should be added as a bug.

I tried running yolov5 using Ubuntu 20.04 and it works well. Then I used another device with Kubuntu 18.04 and I am having issues. The first error is

`SyntaxError: Non-ASCII character '\xf0' in file train.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Then I read what was written on the link provided so I added:
`# -*- coding: utf-8 -*-`

at line 1 of train.py.

But now it shows another error:
`File "train.py", line 85 LOGGER.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@edehino sorry I'm not familiar with Kubuntu. We run daily CI on Ubuntu, MacOS and Windows. Other operating systems are not officially tested. The line in train.py L85 is just printing the hyperparameters in your hyp yaml file. You can comment it if you need to, but it should not be generating any errors. If you can help us recreate your issue in Google Colab or any other common environment we can get started debugging, but if we can't reproduce we can't work on this.

**Comment by glenn-jocher** [comment]
@edehino I've inlined our reproducibility guidelines below to help users provide what we need.

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by rustynothappy** [comment]
im facing issue in running train.py and detect.py in jupyternotebook  ,the .py file is full of errors
I am totally confused why the behavior in Jupyter Labs and Colab are so different, would appreciate any context/explanations from the community!

**Comment by glenn-jocher** [comment]
@rustynothappy 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by christophbrosch** [comment]
Hi we just ran into the same issue, caused by accidentally running the train.py script with python2.7 instead of python3. Running it with python3 solved the issue.

**Comment by glenn-jocher** [comment]
@christophbrosch glad to hear you were able to resolve the issue by running the train.py script with python3. Thanks for sharing the solution with the community! Let us know if you encounter any other issues. Happy coding!
