### ISSUE TITLE
fuse not defined.

### ISSUE THREAD

**Issue by mad-fogs** [ultralytics/yolov5#7]
when export_onnx is set to be true, error will be outcome:
AttributeError: 'Model' object has no attribute 'fuse'

**Comment by glenn-jocher** [comment]
@mad-fogs thank you for the bug report! This should be fixed in df7988d8d0909b76bef79660b14ac9d7b548a13f. We've moved onnx export functionality from detect.py into it's own file at ./models/onnx_export.py:
https://github.com/ultralytics/yolov5/blob/master/models/onnx_export.py 

Example usage of the new file:
```bash
$ export PYTHONPATH="$PWD"
$ python models/onnx_export.py --weights ./weights/yolov5s.pt --img 640 --batch 1
```

.fuse() functionality is not available yet, so we've commented out this part in the new file and marked it as TODO.
