### ISSUE TITLE
Dependencies on Colab

### ISSUE THREAD

**Issue by MyGHName** [ultralytics/yolov5#7014]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm getting getting the following error in Colab. I'm new to this and do not know how to address these issues. Any help would be appreciated.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

**Comment by glenn-jocher** [comment]
@MyGHName 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I see zero errors on YOLOv5 requirements install:

<img width="1986" alt="Screenshot 2022-03-17 at 12 12 27" src="https://user-images.githubusercontent.com/26833433/158797160-0d1bb3a3-e018-4b01-a5cf-cc89753018ba.png">

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by MyGHName** [comment]
Glenn, this is the specific error msg I'm asking about:

albumentations: version 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed

Could this be why it can't read my image file? How do I install the correct version of albumentations?
Transferred 739/745 items from yolov5x.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 123 weight (no decay), 126 weight, 126 bias
albumentations: version 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 405, in __init__
    t = t.read().strip().splitlines()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by glenn-jocher** [comment]
@MyGHName this is an albumentations error unrelated to YOLOv5 with Colab. See https://github.com/albumentations-team/albumentations/issues/949#issuecomment-1066818932, you might want to comment there.
