### ISSUE TITLE
    model.warmup(imgsz=(1 if pt else bs, 3, *imgsz))  # warmup                                                                   ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/yolov5#7042]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

 i run the code in rassarry pi and got this error 

 File "detect.py", line 108
    model.warmup(imgsz=(1 if pt else bs, 3, *imgsz))  # warmup
                                                                  ^
SyntaxError: invalid syntax

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by totoadel** [comment]
the error is in the * befor the *`imgsz`

**Comment by glenn-jocher** [comment]
@totoadel 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by gl94** [comment]
![image](https://user-images.githubusercontent.com/26252750/161389252-c01b2fc4-f971-48c4-abe8-634a70f0ddc3.png)
wrong python environment

**Comment by VYRION-Ai** [comment]
@gl94 thank you
When I shut down the raspberry and open it again the problem solved, thank you
