### ISSUE TITLE
modify kernel and stride on yolov5 network architecture

### ISSUE THREAD

**Issue by Fel26** [ultralytics/yolov5#7057]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Excuse me, I want to ask about the location of the kernel and stride on the yolov5 network architecture can anyone explain to me how to modify the kernel and stride on the yolov5 network architecture and where is it?

thank you for your attention

**Comment by glenn-jocher** [comment]
@Fel26 see model yamls for architecture updates, i.e.:
https://github.com/ultralytics/yolov5/blob/9f4d11379bb931586c1f51c1d85c6fac9fc37eda/models/yolov5s.yaml#L12-L48

**Comment by glenn-jocher** [comment]
@Fel26 the dataloader class is here, you might want to review to see what's happening:
https://github.com/ultralytics/yolov5/blob/9f4d11379bb931586c1f51c1d85c6fac9fc37eda/utils/datasets.py#L380-L381

*.txt files are parsed here:
https://github.com/ultralytics/yolov5/blob/9f4d11379bb931586c1f51c1d85c6fac9fc37eda/utils/datasets.py#L404-L408

**Comment by Fel26** [comment]
is there any special requirement to modify kernel and stride on yolov5 network architecture? 
because when i want to modify the kernel and stride an error appears like this:

Traceback (most recent call last):
  File "models/yolo.py", line 309, in <module>
    model = Model(opt.cfg).to(device)
  File "models/yolo.py", line 112, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in self.forward(torch.zeros(1, ch, s, s))])  # forward
  File "models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/fruit_detection/yolov5/models/common.py", line 275, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.

**Comment by glenn-jocher** [comment]
@Fel26 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
