### ISSUE TITLE
Why am I getting 'utf-8' codec error when reading image file?

### ISSUE THREAD

**Issue by MyGHName** [ultralytics/yolov5#7092]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm running a yolovv5 custom training notebook on Colab. I was able to set up the datasets directory by copying training data to the working directory. All is well until it tries to read the first training image, at which point it throws the following error:

> Exception: train: Error loading data from /content/datasets/images/im0.jpg: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte. 

Here is the line of code that produces this error:
`!python train.py --img 4000 --batch 16 --epochs 150 --data /content/datasets/annotations/dataset.yaml --weights yolov5x.pt`

I was able to read and print the images using the code below, so I'm pretty certain the .jpg files are not corrupted.
`# Python program to read image using matplotlib
 
# importing matplotlib modules
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
 
# Read Images
img0 = mpimg.imread('/content/datasets/images/im0.jpg')
img1 = mpimg.imread('/content/datasets/images/im1.jpg')

# Plot Images
plt.figure(1, figsize = (8, 4))
plt.subplot(1, 2, 1)
plt.imshow(img0)
plt.subplot(1, 2, 2)
plt.imshow(img1)`

Can anyone think of why this is happening?

Thank you!

**Comment by glenn-jocher** [comment]
@MyGHName 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. YOLOv5 dataloaders use cv2 for image loading, so if your format is in the approved list and cv2 can load your image then everything should be fine:
https://github.com/ultralytics/yolov5/blob/a2d617ece94dcd8c9bc205ea70f1223c84fdbe3a/utils/datasets.py#L37

We've created a few short guidelines below to help users provide what we need in order to get started investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
