### ISSUE TITLE
copy paste use?

### ISSUE THREAD

**Issue by violet2422** [ultralytics/yolov5#7094]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi！I really appreciate your object detection project, it has brought us a lot of convenience. But I don't know how to use copy paste for this data augmentation algorithm, can you give a link to the url of a tutorial！Thank you very much！！！😁

**Comment by glenn-jocher** [comment]
@violet2422 copy-paste augmentation is enabled in your hyperparameter file, i.e. scratch-high has 10% copy paste augmentation implemented:
https://github.com/ultralytics/yolov5/blob/a2d617ece94dcd8c9bc205ea70f1223c84fdbe3a/data/hyps/hyp.scratch-high.yaml#L34

Note this augmentation is **only implemented when segmentation labels are provided**. Since copy-paste will be copying your instances around your image it's important not to also copy the background around the object. Segmentation labels use `class xy1, xy2, xy3, xy4, ...` text file format instead of the `class xywh` bounding box format. For an example of segmentation label COCO128 dataset see:
https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128-segments.zip

**Comment by violet2422** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] copy paste use? (Issue #7094)





 
@violet2422 copy-paste augmentation is enabled in your hyperparameter file, i.e. scratch-high has 10% copy paste augmentation implemented:
 https://github.com/ultralytics/yolov5/blob/a2d617ece94dcd8c9bc205ea70f1223c84fdbe3a/data/hyps/hyp.scratch-high.yaml#L34
 
Though note this augmentation is only implemented when segmentation labels are provided. Since copy-paste will be copying your instances around your image it's important not to also copy the background around the object. Segmentation labels use class xy1, xy2, xy3, xy4, ...  text file format instead of the class xywh bounding box format. For an example of segmentation label COCO128 dataset see:
 https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128-segments.zip
