### ISSUE TITLE
why training custom data use CPU instead of GPU

### ISSUE THREAD

**Issue by amieruddin** [ultralytics/yolov5#7173]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
i have 20k of images and already do data preparation([follow guideline by ultalytics](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)).

I don't make any changes on any yolov5 file/hyp. I just use default setting by yolov5.

When training was started, i noticed that the training use all CPU memory (86%) rather then GPU (6%).

My device spec as below :
OS     : Windows 10
GPU   : NVIDIA RTX 3090
CPU   : i9

Command for training : **python train.py --img 640 --batch 16 --epochs 1500 --data dataset.yaml --weights yolov5s.pt --device 0** 

My question is why my device trained the yolo model using CPU instead of GPU? is that any line i need to make changes?
Need help to train the yolo on gpu..Thank you.

![CPU_GPU Training](https://user-images.githubusercontent.com/58421336/160310054-7902ae2d-0814-44a3-85cd-20e8bde19b03.png)

![training epoch](https://user-images.githubusercontent.com/58421336/160310059-0ed780d1-5eea-409e-a521-556b1e562fed.png)

**Comment by niiita** [comment]
Hi, I have the same question!^^
How can I train on GPU instead of CPU?

**Comment by CCRcmcpe** [comment]
You should use the cuda version of torch.
![image](https://user-images.githubusercontent.com/40241855/160327797-cf7184dc-f1b0-4bee-bda1-8ee9baaeebd6.png)

Uninstall your current version, and follow https://pytorch.org/get-started/locally/

**Comment by amieruddin** [comment]
currently im using latest CUDA,  Version 11.3...is cuda 11.3 not support GPU when training Yolov5?

**Comment by CCRcmcpe** [comment]
@amieruddin I mean torch version. It's not related to the CUDA installed on your system.

**Comment by amieruddin** [comment]
im using both CUDA toolkit v.11.3 and Pytorch v.11.3..

based on my installation before...if i install Pytorch not same version with cuda toolkit...it will get error message when training

**Comment by amieruddin** [comment]
based on your link to  https://pytorch.org/get-started/locally/ , it show latest version of PyTorch is 11.3.

@CCRcmcpe , is current PyTorch version 11.3 not support GPU to training YOLOv5?

**Comment by CCRcmcpe** [comment]
@amieruddin You have a huge misunderstanding. Latest pytorch version is 1.11.0, which uses CUDA 11.3. There's no pytorch 11.3. And you should choose compute platform CUDA and install.

**Comment by amieruddin** [comment]
@CCRcmcpe , I choose Pytorch Build : LTS 1.8.2 and install using the command : 

pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

but it show error like this.

![error install](https://user-images.githubusercontent.com/58421336/160337539-e294a737-f94a-444e-bd38-6e72a4c67830.png)


then when i check **pip freeze** : it show only torch downgrade to **torch==1.8.2+cu111**. 
torchaudio and torchvision unsuccessful to install torchvision==0.9.2+cu111 torchaudio===0.8.2

![torch vision](https://user-images.githubusercontent.com/58421336/160337977-da9d8e8b-3ecd-4850-ac36-dc0cd5a2fc40.png)

**Comment by CCRcmcpe** [comment]
@amieruddin That is strange. It shows you already have the torch version which supports cuda. Maybe torch is not choosing device properly. The error is caused by not running pip using elevated privileges.  
To solve torch installation issue, run this with admin privilege:
```
pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio===0.8.2 -I -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
```
Then in python interactive, run:
```
import torch

torch.cuda.is_available()
torch.cuda.current_device()
torch.cuda.device_count()
```
And post your output.

**Comment by CCRcmcpe** [comment]
Anyway you have torch already installed. You should unintall it first.

> You should use the cuda version of torch. ![image](https://user-images.githubusercontent.com/40241855/160327797-cf7184dc-f1b0-4bee-bda1-8ee9baaeebd6.png)
> 
> **Uninstall** your current version, and follow https://pytorch.org/get-started/locally/

**Comment by CCRcmcpe** [comment]
@amieruddin Updated the instructions as it seems not clear.

**Comment by CCRcmcpe** [comment]
@amieruddin Alright. Seems you are already using GPU to train. My fault. The reason your GPU usage is so low is because your small batch size does not match your GPU performance. Increase your batch size to 32 or higher to solve the problem.

**Comment by amieruddin** [comment]
Thank you @CCRcmcpe, actually there is nothing wrong with my training result/model...because after training, I run the model and it work fine.

I just need help to train the model using GPU instead of CPU. Currently I set the epoch to 1500, and it takes me 5 days to finish the training. I want to speed up the time taken.

I try your suggestion to increase the batch size. I try batch size 32 & 64, it still use CPU, not GPU.
the command : **python train.py --img 640 --batch 64 --epochs 1500 --data dataset.yaml --weights yolov5s.pt --device 0** 

After run this command, task manager show it use 100% of the CPU.
Also i got the error 'out of memory' at terminal

![error100%_0](https://user-images.githubusercontent.com/58421336/160793624-9108c2bd-79d4-462e-ab1e-f18287d606b2.png)
![error100%_1](https://user-images.githubusercontent.com/58421336/160793634-78568b0c-d2ad-4f99-8499-9f02fc51362e.png)

**Comment by glenn-jocher** [comment]
@amieruddin 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by learnergthb** [comment]
> 
Were you able to fix the problem ?

**Comment by Smokedhammer** [comment]
> @amieruddin Were you able to fix the problem ?

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Do this above step. and then try running the train command directly from the command line, this made it work somehow!

There should be a prompt on the command line which shows you using the GPU

**Comment by sila-a0** [comment]
> > @amieruddinSorunu çözebildiniz mi?
> 
> pip kurulumu torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
> 
> Yukarıdaki adımı yapın. ve ardından doğrudan komut satırından tren komutunu çalıştırmayı deneyin, bu bir şekilde çalışmasını sağladı!
> 
> Komut satırında, GPU'yu kullandığınızı gösteren bir bilgi istemi olmalıdır.


Thanks a lot
