### ISSUE TITLE
Error using YouTube address in detect.py

### ISSUE THREAD

**Issue by makino-hashimoto-books** [ultralytics/yolov5#7241]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

If source is set to YouTube address in detect.py, following error is shown.

Error message:
Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 100, in run
    dataset = LoadStreams(source, img_size=imgsz, stride=stride, auto=pt)
  File "/content/yolov5/utils/datasets.py", line 325, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'

Solve:
utils/dataset.py

if urlparse(s).hostname in ('youtube.com', 'youtu.be'):  # if source is YouTube video
->
if urlparse(s).hostname in ('www.youtube.com', 'youtu.be'):  # if source is YouTube video

### Environment

- google colab.

!python detect.py --weights yolov5s.pt --source https://www.youtube.com/watch?v=xxxxxxxx

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@makino-hashimoto-books YouTube inference works correctly for me in Google Colab.

<img width="1293" alt="Screenshot 2022-04-01 at 21 27 23" src="https://user-images.githubusercontent.com/26833433/161329011-6574aa5a-334e-4542-8960-b485b581be27.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@makino-hashimoto-books nevermind, you are correct, there is an error with the URL you supplied. Your fix looks good. I will implement a PR.

**Comment by makino-hashimoto-books** [comment]
Thank you for solving method. 

In the previous version, "www.youtube.com" was permitted. 
Recently, the source file is changed, "www.youtube.com" is not permitted. 

Previous version,
if 'youtube.com/' in s or 'youtu.be/' in s:  # if source is YouTube video

Latest version
if urlparse(s).hostname in ('youtube.com', 'youtu.be'):  # if source is YouTube video

**Comment by glenn-jocher** [comment]
@makino-hashimoto-books good news 😃! Your original issue may now be fixed ✅ in PR #7242. This PR adds `www.youtube.com` to the valid hostname list alongside the existing `youtube.com` and `youtu.be`. This would allow you to pass youtube.com URLs with or without the www, but you always need the https://, i.e. https://www.youtube.com or https://youtube.com or https://youtu.be are all valid now :)

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
