### ISSUE TITLE
ONNX export of YOLOv5 models with dynamic input size?

### ISSUE THREAD

**Issue by sarmientoj24** [ultralytics/yolov5#7268]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

It seems like that ONNX models can only take a fixed input size image. Is there a way for conversion that I can take dynamic input size for the ONNX model?

**Comment by glenn-jocher** [comment]
@sarmientoj24 you might want to review export.py arguments:
https://github.com/ultralytics/yolov5/blob/ea72b84f5e690cb516642ce2d9ae200145b0af34/export.py#L557

**Comment by sarmientoj24** [comment]
I tried that but I am still getting this when trying this input size `1468, 1968` as `(W, H)`

```
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'Concat_168' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis 3 has mismatched dimensions of 1 and 2
```

**Comment by glenn-jocher** [comment]
@sarmientoj24 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by sarmientoj24** [comment]
If I use something like `(640, 768)`, it works.

**Comment by glenn-jocher** [comment]
@sarmientoj24 this works well for me. I'm unable to produce any errors with dynamic ONNX models at ~2000 pix

<img width="1522" alt="Screenshot 2022-04-05 at 14 28 15" src="https://user-images.githubusercontent.com/26833433/161753617-b12a2269-3b20-45eb-8685-849f2c4148e3.png">

**Comment by glenn-jocher** [comment]
@sarmientoj24 please refer to my earlier message about supplying a **reproducible** example.

**Comment by sarmientoj24** [comment]
@glenn-jocher does your script resizes the image into an NxN image?

**Comment by sarmientoj24** [comment]
I have this as my script. I want it to be independent of the YOLOv5 script so I created.

My RGB image is `(3, 1468, 1968)` shape

```
import numpy as np
import onnxruntime
from PIL import Image

device = 'cuda'
model_path = 'model.onnx'
if "cuda" in device:
    providers = ["CUDAExecutionProvider"]
else:
    providers = ["CPUExecutionProvider"]

# Create Session
session = onnxruntime.InferenceSession(model_path, providers=providers)

img = Image.open(img_path)
img = np.array(img)

image_data = np.moveaxis(img, -1, 0)
image_data = image_data[np.newaxis, ...].astype(np.float32)
image_data /= 255

# Run prediction <--------- ERROR
output = session.run(
    [session.get_outputs()[0].name], {session.get_inputs()[0].name: image_data}
)[0]
```

**Comment by glenn-jocher** [comment]
@sarmientoj24 oh, I'm sorry, we don't debug custom code. Refer to https://github.com/ultralytics/yolov5/issues/7268#issuecomment-1088547187 to supply a reproducible example with  unmodified YOLOv5 code.

<img width="890" alt="Screenshot 2022-04-05 at 14 46 10" src="https://user-images.githubusercontent.com/26833433/161756616-dbb131a4-4113-4047-ab84-e40e3f69fd85.png">

**Comment by sarmientoj24** [comment]
@glenn-jocher I think the reason is that the shape should be divisible by 32. I already saw it from the code just now. It does resize by padding to the image. I'll just adapt some parts of the code like the `letterbox`

**Comment by sarmientoj24** [comment]
But if you pad to the image, the bbox coordinates must be realigned after getting the outputs, right?

**Comment by TengliEd** [comment]
> 

@glenn-jocher If export to onnx by below command, there is an exception thrown: ONNX: export failure: Input, output and indices must be on the current device. It means that we can't dynamically export on gpu.
python export.py --include onnx --dynamic --device 0

**Comment by sarmientoj24** [comment]
@TengliEd I think it can still **dynamically** export on GPU. It's just there is a need to preprocess the image for it to be divisible by 32 as seen in `detect.py`.

**Comment by glenn-jocher** [comment]
@TengliEd not all combination of arguments are allowed. If you run into errors when adding argument simply don't use the arguments causing the errors, --device in your case.

**Comment by TengliEd** [comment]
> @glenn-jocher Thx for your reply. Have you ever dynamically exported to onnx on gpu? if you have, plz provide the correct argument combination. In my case, dynamic export is necessary.

**Comment by glenn-jocher** [comment]
@TengliEd if you want --dynamic then pass that and no device.
