### ISSUE TITLE
Converting the pytorch weight to tensorflow lite weights.

### ISSUE THREAD

**Issue by Paras-97** [ultralytics/yolov5#7269]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

export: data=data/coco128.yaml, weights=['CPU_Asset_V01.10_Y5_l6_i1280_b4_M01_All.pt'], imgsz=[1280], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=12, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['tflite']
fatal: cannot change to '/home/paras/Python': No such file or directory
YOLOv5 🚀 2022-4-4 torch 1.9.0+cu111 CPU

/home/paras/.local/lib/python3.8/site-packages/torch/serialization.py:602: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
Traceback (most recent call last):
  File "export.py", line 584, in <module>
    main(opt)
  File "export.py", line 579, in main
    run(**vars(opt))
  File "/home/paras/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 462, in run
    model = attempt_load(weights, map_location=device, inplace=True, fuse=True)  # load FP32 model
  File "/home/paras/Python Projects/yolov5/models/experimental.py", line 97, in attempt_load
    ckpt = (ckpt.get('ema') or ckpt['model']).float()  # FP32 model
  File "/home/paras/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 667, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/paras/.local/lib/python3.8/site-packages/torch/jit/_script.py", line 384, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/paras/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RecursiveScriptModule' object has no attribute 'get'

### Minimal Reproducible Example

python export.py --weights CPU_Asset_V01.10_Y5_l6_i1280_b4_M01_All.pt --img 1280 --include tflite

### Additional

Hi,
I have weights trained on my custom dataset. But when I am trying to convert the pytorch weights to the tensorflow lite weights, it is giving me this error. Can you please tell me why it is returning this error?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Paras-97 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible, TFLite export completes correctly on custom trained models, YOLOv5s on COCO128 in Google Colab in our test right now:

<img width="1247" alt="Screenshot 2022-04-04 at 10 49 20" src="https://user-images.githubusercontent.com/26833433/161508617-7a58121f-d2a2-4b2f-9698-106d557cfcd3.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Paras-97** [comment]
Thanks for the information, was quite insightful :D
