### ISSUE TITLE
I am getting 6 output values from detect.py Can someone tell what the six values indicate?

### ISSUE THREAD

**Issue by adityarajsahu** [ultralytics/yolov5#7403]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am getting 6 output values from detect.py. While training, I provided 5 input values - class, x, y, w, h. What is the sixth value?

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by MiksVasiljevs** [comment]
The 6th value should be the confidence score (0-1).

For further information, you can review the detect.py. In particular, you might be interested in what values non max suppression returns:
https://github.com/ultralytics/yolov5/blob/3752807c0b8af03d42de478fbcbf338ec4546a6c/utils/general.py#L676-L683

**Comment by glenn-jocher** [comment]
@MiksVasiljevs thanks for your input! You're absolutely correct. The 6th value returned by detect.py is indeed the confidence score, which represents the confidence level of the detected object. This information is particularly valuable when filtering out low-confidence detections or when applying post-processing techniques such as non-maximum suppression.

For more detailed insights into non-maximum suppression and its returned values, you can review the specific section of general.py as you've mentioned.

Your expertise and interest in the inner workings of YOLOv5 are greatly appreciated! If you have any further questions or insights, feel free to ask or share.

Thank you!
