### ISSUE TITLE
How to bundle the model for browser based application.

### ISSUE THREAD

**Issue by abhishekhingne** [ultralytics/yolov5#7407]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I have build one YOLO model and I need to deploy it on the browser, for that I used export.py script and the conversion was successful, and the model is running perfectly fine. But, since I'm deploying it over the browser my model goes to the client side. Any mechanism through which I can bundle the model (like wasm) and avoid this (apart from API based solution).

Thanks

**Comment by krushal** [comment]
I am also looking for something similar. Any help is appreciated.

**Comment by glenn-jocher** [comment]
@abhishekhingne @krushal for TF.js Usage examples see export.py:
https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/export.py#L38-L42

**Comment by MasarratY** [comment]
Hi [glenn-jocher](https://github.com/glenn-jocher). Is there a way to generate wasm file from .pt file?

**Comment by Mas-Y** [comment]
Hi [glenn-jocher](https://github.com/glenn-jocher). Is there a way to convert .pt models to wasm format.

**Comment by glenn-jocher** [comment]
@Mas-Y I'm sorry I'm not familiar with wasm, what is that?

**Comment by Mas-Y** [comment]
Thank You @glenn-jocher for the quick response.

WebAssembly (wasm) for deploying the model in browser for faster computation. Usually from the c++ code of yolo we can generate .data,.wasm,.js and these files can be deployed in browser so that the client side processing is faster. The tensorflow js format (.bin and model.json) models are usually slow when implemented in browser for offline processing for inbrowser sdk. 
This is my understanding. I am little premature to this subject trying to understand the fastest way to get the offline client side processing in browser.

one of the reference link which i guess talks the similar subject is: 
[https://github.com/nihui/ncnn-webassembly-yolov5](https://github.com/nihui/ncnn-webassembly-yolov5) 

Any help is appreciated.

**Comment by glenn-jocher** [comment]
@Mas-Y oh interesting! Have you tried to benchmark with the Usage example below? 

If you are deploying to browser probably a YOLOv5n model at 320 image size would work best.

https://github.com/ultralytics/yolov5/blob/1994ad93e431b5b0f7b66cc231511067032732cb/export.py#L38-L42

**Comment by Mas-Y** [comment]
@glenn-jocher Used yolov5n with 320 and 640. But it didn’t work in my usecase (fields detection in a id card) as the fields were not getting detected. Only 640 works.


And regarding js implementation link you shared. Doing the same thing, but in ionic not in react.

**Comment by MasarratY** [comment]
@glenn-jocher Any suggestions around my usecase?

one of the reference link which i guess talks the similar subject is:
https://github.com/nihui/ncnn-webassembly-yolov5

**Comment by glenn-jocher** [comment]
@MasarratY yes the web assembly ncnn demo looks interesting. Certainly very fast, though it's hard to tell what resolution they are running at (any model will be fast at a small enough image size).

**Comment by Mas-Y** [comment]
@glenn-jocher my understanding from the code provided is that they are using 640w*480h resolution.

**Comment by glenn-jocher** [comment]
@Mas-Y Yep, it looks like that. Thank you for pointing that out. If you want to use a larger model with higher resolution, you may need to explore WebAssembly for YOLOv5 on the NCNN framework, or use a remote server API for inference.
