### ISSUE TITLE
the advantages of letterbox?

### ISSUE THREAD

**Issue by YoungjaeDev** [ultralytics/yolov5#7454]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! 
I think it can maintain the ratio by using letterbox, but do I have the advantage of filling the small side with a margin of zero while adjusting the length of the small side to the large side during training

But on the other hand, I don't seem to be padding in inference (detect). I wonder why they're different

Thank you!

**Comment by glenn-jocher** [comment]
@youngjae-avikus there's no advantage, it's a constraint.

**Comment by zxq309** [comment]
@glenn-jocher Dataset samples used letterbox method before input yolov5, why all the metrics of P, R, mAP decline, about 4~5%. Where I can remove or cancel the letterbox method in yolov5.

**Comment by glenn-jocher** [comment]
@zxq309 I don't understand what you are saying. Letterboxing inputs is a requirement, if you remove this inference will not work.

**Comment by YoungjaeDev** [comment]
@glenn-jocher Will it be 1:1 through letterbox input during the inference? In the logger, when the image input is 640, 384x640 is printed, so what is correct?

**Comment by glenn-jocher** [comment]
@youngjae-avikus you pass the long side dimension as `--img 640`. The short side is handled automatically for best results.

**Comment by zxq309** [comment]
@glenn-jocher What I mean is that I pre-processed the samples of the dataset to a fixed size, e.g., 1536x1536 in advance, using the same method letterbox. The reason is that the resolution of our captured images reaches 4000x3000, a single image occupies 10M+ of memory, which is slow to load and very time-consuming to train directly into yolov5. When I feed the fixed size samples into yolov5, do these samples still need to perform letterbox processing? I found that the accuracy decreased by 4~5% after this processing, and why?

**Comment by glenn-jocher** [comment]
@zxq309 we don't recommend any pre-processing anywhere in our documentation, so any effects of this are entirely on you and not something I'm in any position to comment on.
