### ISSUE TITLE
Abnormal memory usage in AWS Lambda environment

### ISSUE THREAD

**Issue by changduckGO** [ultralytics/yolov5#7496]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello.
I am creating inference function using YOLOv5 in AWS Lambda Environment.
Here I faced a strange problem, unlike the local test environment.

I designed this function as follows.
1. Convert video to list of image
2. Inference by putting this list into the input of the model

The problem is that memory spikes when "specific parts" of video are included, and aws lambda signals are killed.

I thought there was so many images sending requests that memory of lambda spiked. However, this problem occurred even in fewer images. patterns could not be found.

- List of 50 images → Successful Request
- List of 10 images → Failed Request

Other reason I thought is as follows.
- High pixels in specific parts

AWS Lambda environment settings are as follows:
- memory : 3008MB(Max)
- temp storage : 512MB

Information on fine-tuned Custom YOLOv5 model is as follows.
- model size : M
- resize : 416
※ Input image sizes vary. (360x640, 1280x720 etc.)

In the local environment, the request is successful.

I don't know exactly whether this problem is because of YOLOv5 or AWS Lambda environment.
Is there a solution to a similar problem?
Thank you for reading.
![aws-lambda-yolov5](https://user-images.githubusercontent.com/62056652/164205449-20fb6058-72a4-4cfe-a5fc-4e8244457916.jpg)

**Comment by glenn-jocher** [comment]
@changduckGO 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. If you can provide code to reproduce this issue in a common environment, i.e. Colab or Docker then we could get started investigating.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Alberto1404** [comment]
> 

@changduckGO could you please let us know deeply how did you do that? I am interested in doing that exactly, but have 0 idea about how it works.
