### ISSUE TITLE
Detected negative coordinates

### ISSUE THREAD

**Issue by gurgenhovsepyan** [ultralytics/yolov5#7521]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have trained YOLOv5 model, when I do detection on single image model gives me negative coordinates (ymin=-1). Why model gives me negative coordinates?

**Comment by glenn-jocher** [comment]
@gurgenhovsepyan 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by sagnik1511** [comment]
Hi, came across the same problem. Also finding some coordinates having higher values than the image size. Any possible fix or analogy to tackle this without using multiple functions from `utils.general`?

**Comment by aff3npirat** [comment]
I am having the same problem. Trained pretrained yolov5n model on custom data, and exported to onnx format using

```
python export.py \
--img 64 \
--weights /path/to/best.pt \
--device cpu \
--simplify \
--include onnx \
--batch-size 6

```

When I run inference I get coordinates which are almost 5 times the image size (the images are 64x64 pixels).

In what format is the model supposed to output the coordinates (normed or absolute values)?

**Comment by glenn-jocher** [comment]
@aff3npirat 👋 Hello! The model outputs bounding box coordinates in normalized format, where (0, 0) is the top-left corner of the image, and (1, 1) is the bottom-right corner. To convert these normalized coordinates to absolute pixel values, you can use `xyxy` format conversion functions from `utils.general`. This ensures bounding boxes are within the image bounds. If you encounter any issues during this process, please provide a minimal reproducible example for us to assist you better 🛠️.
