### ISSUE TITLE
A question about metrics that bothers me

### ISSUE THREAD

**Issue by Zephyr69** [ultralytics/yolov5#7528]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

AFAIK yolov5 uses map to measure the competency of models, which is essentially some defined sort of contrast between true positives and all relevant objects.

But in my previous non-ml experiences, I needed to measure the competency of an algorithm in a different(?) way. I needed to do it by comparing the performance of the algorithm against that of a completely random process, where the metrics normally take the forms like
((Performance_of_the_tested_alg - Performance_of_the_random_alg) / (1 - Performance_of_the_random_alg)).

I guess in a pure classification case this would resolve competency measuring issues when the dataset is largely/extremely biased. But I don't get how the random part should be incorporated when localisation is added to the equation. I don't even know if this measure would provide any additional insight into the competency of a detector model.

What do you think?

**Comment by glenn-jocher** [comment]
@Zephyr69 I'm not sure I understand your question exactly, but in general applicable metrics will vary by tasks. For example accuracy is used as a classification metric but does not exist in detection because it does not account for localization errors etc., which is why different metrics like mAP etc. are used here. It's possible your prior metrics simply don't apply in this space.
