### ISSUE TITLE
When running val.py, the results of coco evaluation criteria are not output correctly

### ISSUE THREAD

**Issue by 567jin** [ultralytics/yolov5#7557]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

# Question.

## When I run val.py, I encounter somroblems.This is what I get when I run val.py：

Evaluating pycocotools mAP... saving runs\val\exp\yolov5s_predictions.json...
loading annotations into memory...
Done (t=0.74s)
creating index...
index created!
Loading and preparing results...
DONE (t=5.78s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=32.61s).
Accumulating evaluation results...
Results saved to runs\val\exp
DONE (t=14.72s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002  # <-- These values are extremely low
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.047
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.093
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.100
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.117
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.151

## This is what I want the val.py output to look like：
val: data=./data/coco.yaml, weights=['yolov5x.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, task=val, device=, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=True, project=runs/val, name=exp, exist_ok=False, half=True
YOLOv5 🚀 v5.0-267-g6a3ee7c torch 1.9.0+cu102 CUDA:0 (Tesla P100-PCIE-16GB, 16280.875MB)

Fusing layers... 
Model Summary: 476 layers, 87730285 parameters, 0 gradients

val: Scanning '../datasets/coco/val2017' images and labels...4952 found, 48 missing, 0 empty, 0 corrupted: 100% 5000/5000 [00:01<00:00, 2846.03it/s]
val: New cache created: ../datasets/coco/val2017.cache
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100% 157/157 [02:30<00:00,  1.05it/s]
                 all       5000      36335      0.746      0.626       0.68       0.49
Speed: 0.1ms pre-process, 22.4ms inference, 1.4ms NMS per image at shape (32, 3, 640, 640)  # <--- baseline speed

Evaluating pycocotools mAP... saving runs/val/exp/yolov5x_predictions.json...
...
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.504  # <--- baseline mAP
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.688
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.546
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.351
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.551
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.644
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.382
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.628
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.681  # <--- baseline mAR
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.524
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.735
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826

### Additional

Thank you very much for your reply！

**Comment by glenn-jocher** [comment]
@567jin 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. val.py with pycocotools operates correctly in our tests:

<img width="1378" alt="Screen Shot 2022-04-24 at 11 50 38 AM" src="https://user-images.githubusercontent.com/26833433/164991839-7d3518aa-e03c-4f1f-8f71-2851fa430172.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by 567jin** [comment]
@glenn-jocher Thank you very much for your reply. 😄
When the above problem occurred. I was using YOLOV5-6.0/6.1🚀. But  when I used YOLOv5-master, the problem was solved!  I didn't change any code, I only used the following command: python val.py --data data/coco.yaml --weights yolov5s.pt.

I don't know why this is happening. Is it possible that this is a problem with pycocotools?  I am using pycocotools version 2.0.2.
When I add the --verbose parameter, the AP values for each category are reported correctly, but the coco unique evaluation criteria are not reported correctly.

**Comment by glenn-jocher** [comment]
@567jin great. master is recommended for all work as it incorporates the latest fixes and features.

**Comment by shenhaibb** [comment]
> @glenn-jocher Thank you very much for your reply. 😄 When the above problem occurred. I was using YOLOV5-6.0/6.1🚀. But when I used YOLOv5-master, the problem was solved! I didn't change any code, I only used the following command: python val.py --data data/coco.yaml --weights yolov5s.pt.
> 
> I don't know why this is happening. Is it possible that this is a problem with pycocotools? I am using pycocotools version 2.0.2. When I add the --verbose parameter, the AP values for each category are reported correctly, but the coco unique evaluation criteria are not reported correctly.

did u solve it? i met the same problem

**Comment by epureanudiana** [comment]
I am also facing the same issues, but I am using a custom dataset. Has anyone managed to fix this?

**Comment by 567jin** [comment]
This is probably just a bug in one version, try it with the master version.

**Comment by 567jin** [comment]
> I am also facing the same issues, but I am using a custom dataset. Has anyone managed to fix this?


This is probably just a bug in one version, try it with the master version.

**Comment by 567jin** [comment]
> I am also facing the same issues, but I am using a custom dataset. Has anyone managed to fix this?


This is probably just a bug in one version, try it with the master version. And the pycocotools can only be used with coco datasets, custom datasets cannot call pycocotools's API.

**Comment by 567jin** [comment]
> 

This is probably just a bug in one version, try it with the master version.

**Comment by 567jin** [comment]
This is probably just a bug in one version, try it with the master version. And the pycocotools can only be used with coco datasets, custom datasets cannot call pycocotools's API.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] When running val.py, the results of coco evaluation criteria are not output correctly (Issue #7557)





 
I am also facing the same issues, but I am using a custom dataset. Has anyone managed to fix this?
