### ISSUE TITLE
Show Video MP4

### ISSUE THREAD

**Issue by bruchpilot123** [ultralytics/yolov5#7566]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 

I used the following command: 

` python detect.py --weights yolov5s.pt --source 'https://youtu.be/Zgi9g1ksQHc'`

Everything works fine and smooth but I can not watch the video output in Runs/ detect. VLC player just closes and the ubuntu default video player does not start. What is the correct approach to watch and open the video?

Kindly regards

**Comment by glenn-jocher** [comment]
@bruchpilot123 on macOS YouTube videos show properly during inference, but not all environments support showing windows. Even if results are not shown live you should still be able to view the saved video file after inference completes in runs/detect/exp...

**Comment by bruchpilot123** [comment]
Hey, actually the problem is not during the inference, the Problem is with the saved video file in runs/detect/exp... 

I can see the video during the inference, but I can not watch the saved video, which is a problem...

Kindly regards

**Comment by glenn-jocher** [comment]
@bruchpilot123 works correctly for me:

<img width="1680" alt="Screen Shot 2022-04-26 at 12 52 46 PM" src="https://user-images.githubusercontent.com/26833433/165381138-be604e51-edb4-4aad-b9ee-b1bb5b6222fa.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
