### ISSUE TITLE
Can't detect with detect.py

### ISSUE THREAD

**Issue by rtm-1dyakonov** [ultralytics/yolov5#7594]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Last week it was ok. I've used detect.py from YoloV5 release 6.0 zip to detect objects on photos with my custom model. But today I can't use detect from both releases 6.0 and 6.1. Here is the issue
![изображение](https://user-images.githubusercontent.com/65365762/165296428-11ddfa9e-d97b-4ffb-83a4-942a75eb7a3b.png)
I've tried provided by the authors yolo5n.pt and yolo5n6.pt. They both are in the same directory where detect.py file is located. 
![изображение](https://user-images.githubusercontent.com/65365762/165296848-122b9119-ac8d-4907-a01b-15953e7b290b.png)
I've installed all requirements
![изображение](https://user-images.githubusercontent.com/65365762/165297068-c804a6ef-d87b-4e0d-a9c8-f1476c4ccfd5.png)
Here is my input image
![изображение](https://user-images.githubusercontent.com/65365762/165302528-7214ac9c-099f-4356-9ebf-0b01b8610853.png)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rtm-1dyakonov 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. YOLOv5n6 Inference works correctly in our test just now.

<img width="1372" alt="Screen Shot 2022-04-26 at 12 50 55 PM" src="https://user-images.githubusercontent.com/26833433/165380847-a7b0127c-2270-46f5-aba9-6d14229573e0.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
