### ISSUE TITLE
warning training is positional arguments and argument "destination" are deprecated.

### ISSUE THREAD

**Issue by gshoanganh** [ultralytics/yolov5#7623]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

i got a warning during training my object. Please see details:
`14/49        0G   0.05292   0.01234   0.01605        23       640:  41%|███/Volumes/DATA/yolo-smoke-training/gshoanganh/lib/python3.8/site-packages/torch/nn/modules/module.py:1402: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.`

**Comment by glenn-jocher** [comment]
@gshoanganh 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by binominerigike** [comment]
I'm getting the same warning, though it doesn't seem to effect training. Just is a bit annoying and causes the progress bar to reprint itself.

I'm running:

- ubuntu 22.04
- RTX 3090 
- CUDA 11.5 
- nvidia-495 drivers
- python 3.8.6
- torch nightly: 1.12.0.dev20220320+cu115 for 3.8
- torchvision nightly: 0.13.0.dev20220320+cu115

I've added the following to train.py but the warning still persists.

```
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)   
``` 

I can try to change everything to 3.9 and update to the newest nightly pytorch that supports 11.5 from here: https://download.pytorch.org/whl/nightly/torch/ Just let me know if that would be useful, though I've noticed the most recently nightly there is from only 22-04-23 for some reason.
  
My RTX 3090 had issues with drivers 510 and cuda 11.6, so I'd like to avoid having to deal with that again.

**Comment by glenn-jocher** [comment]
@binominerigike don't use pytorch nightly, use stable https://pytorch.org/get-started/locally/

**Comment by binominerigike** [comment]
I tried that initially and every time I install a pip install -r requirements.txt which changes it back to stable. When I do, I get the error that this version of torch is not compiled for the sm_86 architecture which my 3090 card requires, hence using nightly.

**Comment by limitz** [comment]
@binominerigike 
If you just want to ignore the error, instead of DeprecationWarning, ignore UserWarning
```
import warnings 
warnings.filterwarnings("ignore", category=UserWarning)   
```
It will also ignore other UserWarnings, not sure if that is what you want. Pytorch should probably change the warning to a DeprecationWarning.
