### ISSUE TITLE
why change from python3.6 to python3.7?

### ISSUE THREAD

**Issue by fei4xu** [ultralytics/yolov5#7631]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,

I have a Jetson Nano with has python 3.6 and its pytorch version for python3.6.

I checked the readme.md and found that the required python version was changed from 3.6 to 3.7 recently ( commit ff8646cdea57a1e81a381de37b881e55ab273777  2022/1/26) and then released as v6.1 tag. I didn't see any python or library upgrade around those commits.

I'd like to check if this is a planned version upgrade or python3.6 is still supported.

Thanks,

Fei

**Comment by glenn-jocher** [comment]
@fei4xu Python 3.6 has reached end of life and is no longer officially supported: https://endoflife.date/python

**Comment by fei4xu** [comment]
Thanks, so I can safely guess that there isn't a technical reason (like library dependency) to drop python 3.6 support.

Actually I just tried, on Jetson Nano (python 3.6.9), with the latest code on master branch, if I ignore this change (a19406b39dbc45db0bbae8d0b7da9d6281f9af1e) and change opencv from 4.1.2 to `4.1.1` which comes default in Jetson, everything works just fine!

Python version itself and the dependent libraries' version are alwasy a headache for new users. I don't want to let new users like me spend lots of time upgrading python versions. so maybe we can still leave a note on the readme page that python3.6 still works but not recommanded?

Thanks again for the great work!

**Comment by glenn-jocher** [comment]
@fei4xu we can try to revert cv2 dependency to 4.1.1, but we can no longer state support for 3.6 as we no longer test for it.

**Comment by glenn-jocher** [comment]
@fei4xu good news 😃! Your original issue may now be fixed ✅ in PR #7645. This PR drops cv2 requirements to >=4.1.1. I think the second change that would be needed for native Jetson support would be to do a soft test of python version (display a warning) rather than a hard test.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@fei4xu unofficial 3.6.9 support seems to work across most operating systems (macos and ubuntu). See https://github.com/ultralytics/yolov5/runs/6234184629?check_suite_focus=true

**Comment by StephenBeirlaen** [comment]
Hi all, sorry for reviving this, but it might help the OP.
I can confirm that Yolov5 is now running with this PR on my Jetson Nano 2GB. Thanks! :)
I used [this image](https://github.com/Qengineering/Jetson-Nano-image) to have all system dependencies installed for me. I also had to run a `pip3 install --upgrade pip` before I could install Yolov5 requirements.

Question though: I had to add a swapfile to make inference run because Yolov5 consumes a lot of memory (1.9/2 GB RAM and 2.1 GB of swap). Are these numbers normal for Yolov5? I am only interested in running inference on this device, no training. Anything I can tune to fit in 2GB RAM? Already switched to lightdm which saves me ~500 MB.
Thanks in advance!

![image](https://user-images.githubusercontent.com/11806615/166555525-7caca179-18b9-4417-9ff5-dcbb2c22d8da.png)

**Comment by glenn-jocher** [comment]
@StephenBeirlaen great, thanks for the confirmation! Most of our focus has been on efficient resource utilization during training, i.e. reducing CUDA memory requirements, and not especially on edge device inference, so I can't provide you specifics there.

But that said, torch is primarily a training framework and you can definitely realize performance gains by exporting to TRT for CUDA deployments, i.e.:

Format                      | `export.py --include`         | Model
:---                        | --:                           | :--
[PyTorch](https://pytorch.org/)                     | -                             | `yolov5s.pt`
[TorchScript](https://pytorch.org/docs/stable/jit.html)                 | `torchscript`                 | `yolov5s.torchscript`
[ONNX](https://onnx.ai/)                        | `onnx`                        | `yolov5s.onnx`
[OpenVINO](https://docs.openvino.ai/latest/index.html)                    | `openvino`                    | `yolov5s_openvino_model/`
[TensorRT](https://developer.nvidia.com/tensorrt)                    | `engine`                      | `yolov5s.engine`
[CoreML](https://github.com/apple/coremltools)                      | `coreml`                      | `yolov5s.mlmodel`
[TensorFlow SavedModel](https://www.tensorflow.org/guide/saved_model)       | `saved_model`                 | `yolov5s_saved_model/`
[TensorFlow GraphDef](https://www.tensorflow.org/api_docs/python/tf/Graph)         | `pb`                          | `yolov5s.pb`
[TensorFlow Lite](https://www.tensorflow.org/lite)             | `tflite`                      | `yolov5s.tflite`
[TensorFlow Edge TPU](https://coral.ai/docs/edgetpu/models-intro/)         | `edgetpu`                     | `yolov5s_edgetpu.tflite`
[TensorFlow.js](https://www.tensorflow.org/js)               | `tfjs`                        | `yolov5s_web_model/`

Usage: 
```python
git clone https://github.com/ultralytics/yolov5 -b update/bench_gpu  # clone
cd yolov5
pip install -qr requirements.txt coremltools onnx onnxruntime-gpu openvino-dev  # install
pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # TensorRT

python utils/benchmarks.py --weights yolov5s.pt --img 640 --device 0
```

### Colab Pro+ V100 High-RAM Results

```
benchmarks: weights=/content/yolov5/yolov5s.pt, imgsz=640, batch_size=1, data=/content/yolov5/data/coco128.yaml, device=0, half=False, test=False
Checking setup...
YOLOv5 🚀 v6.1-135-g7926afc torch 1.10.0+cu111 CUDA:0 (Tesla V100-SXM2-16GB, 16160MiB)
Setup complete ✅ (8 CPUs, 51.0 GB RAM, 46.7/166.8 GB disk)

Benchmarks complete (458.07s)
                   Format  mAP@0.5:0.95  Inference time (ms)
0                 PyTorch        0.4623                10.19
1             TorchScript        0.4623                 6.85
2                    ONNX        0.4623                14.63
3                OpenVINO           NaN                  NaN
4                TensorRT        0.4617                 1.89
5                  CoreML           NaN                  NaN
6   TensorFlow SavedModel        0.4623                21.28
7     TensorFlow GraphDef        0.4623                21.22
8         TensorFlow Lite           NaN                  NaN
9     TensorFlow Edge TPU           NaN                  NaN
10          TensorFlow.js           NaN                  NaN
```
