### ISSUE TITLE
Problems with the --multi-scale option with CUDA

### ISSUE THREAD

**Issue by DP1701** [ultralytics/yolov5#7674]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello all,
I get the following message every time when I activate --image-scale option for training:

```
     Epoch   gpu_mem       box       obj       cls    labels  img_size
     0/299     23.5G    0.1132   0.09077   0.03928        78      1152:   1%|          | 4/464 [00:07<13:49,  1.80s/it]     
Traceback (most recent call last):
  File "train.py", line 668, in <module>
    main(opt)
  File "train.py", line 563, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 349, in train
    pred = model(imgs)  # forward
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/USERDATA/YOLO_detectors/yolov5_new/yolov5/models/yolo.py", line 135, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/raid/USERDATA/YOLO_detectors/yolov5_new/yolov5/models/yolo.py", line 158, in _forward_once
    x = m(x)  # run
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/USERDATA/YOLO_detectors/yolov5_new/yolov5/models/common.py", line 139, in forward
    return self.cv3(torch.cat((self.m(self.cv1(x)), self.cv2(x)), 1))
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/USERDATA/YOLO_detectors/yolov5_new/yolov5/models/common.py", line 47, in forward
    return self.act(self.bn(self.conv(x)))
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/raid/USERDATA/YOLO_detectors/YOLOv5_enviroment/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
```

The message comes right at the beginning.

System environment:
Linux
CUDA 11.3
Pytorch 1.11.0+cu113  
Torchvision 0.12.0+cu113
Latest YOLOv5 version

Does anyone have an idea what this could be? Without --image-scale everything works fine.

**Comment by glenn-jocher** [comment]
@DP1701 there's no such training argument in YOLOv5. See train.py argparser for valid training arguments:
https://github.com/ultralytics/yolov5/blob/bff6e51bc4894ffc4da8b202718023f80d8bdc44/train.py#L475-L510

**Comment by DP1701** [comment]
@glenn-jocher 
Sorry, I meant this option: [--multi-scale](https://github.com/ultralytics/yolov5/blob/bff6e51bc4894ffc4da8b202718023f80d8bdc44/train.py#L495)

**Comment by glenn-jocher** [comment]
@DP1701 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. --multi-scale works correctly in our tests just now in Google Colab:

<img width="1805" alt="Screen Shot 2022-05-02 at 1 11 52 PM" src="https://user-images.githubusercontent.com/26833433/166318704-44eb6f0a-881c-40e8-b946-6163cb372ee6.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
