### ISSUE TITLE
Can not use batch inference on Jetson nano 

### ISSUE THREAD

**Issue by kuonumber** [ultralytics/yolov5#7688]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

When I use command like below

`python detect.py --source ./data/images/ --image-size 320`

Everything works fine.

But use the torch hub batch inference

```
model = torch.hub.load('ultralytics/yolov5', 'yolov5s') 
list_img = glob("./yolov5/data/images/*.jpg")
results = model(list_img, 320)
```

![image](https://user-images.githubusercontent.com/16162246/166610997-74c3cd04-03d8-4c3c-aabb-81d29e64234a.png)

Only first image can be predicted...
I tested different data source and got same situation.
Any suggestions?

### Environment

YOLOv5 🚀 v6.1-161-ge54e758 torch 1.10.0 CUDA:0 (NVIDIA Tegra X1, 1972MiB)
Python 3.6.9
Ubuntu 18.04

### Minimal Reproducible Example

```
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom
list_img = glob("./yolov5/data/images/*")
results = model(list_img, 320)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kuonumber 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I ran your code in Google Colab and observed the correct results, so I'm not able to reproduce any problems. Unfortunately we don't have any edge devices to test locally with:

<img width="1397" alt="Screen Shot 2022-05-03 at 6 38 21 PM" src="https://user-images.githubusercontent.com/26833433/166612623-b611040e-5eed-4630-b282-d2acafec226d.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by kuonumber** [comment]
Thanks for helping.
I still can not find not any solution even on nvidia forum.

**Comment by glenn-jocher** [comment]
@kuonumber you're welcome! I understand how frustrating this situation can be. Unfortunately, we don't have ready access to an NVIDIA Jetson Nano for testing, so we're unable to replicate the issue locally. If you can provide more information or a minimum reproducible example following the guidelines we provided, it will help us greatly in diagnosing the problem and finding a solution. Thank you for your understanding and patience.
