### ISSUE TITLE
warning 

### ISSUE THREAD

**Issue by stein-666** [ultralytics/yolov5#7724]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should cal
l them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`
What should I do to solve it? Thanks!

### Additional

my sets
windows+anaconda3+pytorch 1.11+cuda 11.5

**Comment by glenn-jocher** [comment]
@stein-666 I've seen these in the past but not recently, i.e. within the last 6 months. Can you reproduce this in our Colab notebook?
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb

<img width="1423" alt="Screen Shot 2022-05-07 at 11 51 40 AM" src="https://user-images.githubusercontent.com/26833433/167267990-8bcb1fc8-8c33-4ee4-a33b-c4867c078955.png">

**Comment by stein-666** [comment]
@glenn-jocher  To be honest , I have two problems at present.  Though I can reproduce this, the warning persists. Besides, I have another problem when validating:  AttributeError: ‘NoneType‘ object has no attribute ‘_free_weak_ref‘. 
Some people told me it was a pytorch version(mine: Pytorch 11.1) problem. But I can't judge.

**Comment by glenn-jocher** [comment]
@stein-666 _free_weak_ref is a known pytorch 1.11 issue. It has no effect other than displaying a warning.

**Comment by stein-666** [comment]
@glenn-jocher Thanks! So If I may say so, the following problem can be ignored?
![image](https://user-images.githubusercontent.com/78457819/167297103-fd79e8d7-5270-49d7-8640-82005fff8148.png)
![image](https://user-images.githubusercontent.com/78457819/167297113-b402bdac-75f4-449a-a110-0843ee0dbe38.png)

**Comment by stein-666** [comment]
@glenn-jocher So it means I can ignore it, right? Thanks!
![image](https://user-images.githubusercontent.com/78457819/167297210-42a4b82b-7e42-4ee5-8119-490d446b06fe.png)

**Comment by stein-666** [comment]
@glenn-jocher  err, Can I take up a little more of your time? As the issue shows, how can I solve the warning followed?
Thank you very much!
![image](https://user-images.githubusercontent.com/78457819/167297316-8db70666-5a7b-48ee-90b5-611704f2ec36.png)

**Comment by glenn-jocher** [comment]
@stein-666 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
