### ISSUE TITLE
AttributeError: Can't get attribute 'Hardswish' on <module 'torch.nn.modules.activation' from '/usr/local/lib/python3.6/dist-packages/torch/nn/modules/activation.py'>

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#773]
AttributeError: Can't get attribute 'Hardswish' on <module 'torch.nn.modules.activation' from '/usr/local/lib/python3.6/dist-packages/torch/nn/modules/activation.py'>

**Comment by glenn-jocher** [comment]
@jinfagang thanks for the bug report! Hardswish() will be supported in ONNX 1.8, which is supposed to be officially released in the next few months. See https://github.com/onnx/onnx/issues/2728

In the meantime I believe your best option may be to export v2.0 LeakyReLU(0.1) models with pytorch 1.5.1 and onnx 1.7.

**Comment by Frank1126lin** [comment]
I alse got this issue when I use the model (pt file, trained on my cloud machine ) to detect on my desktop.

**Comment by glenn-jocher** [comment]
@jinfagang @Frank1126lin after reading the error again, I think you simply need to update your pytorch to 1.6 or higher. nn.Hardswish was introduced in 1.6.

**Comment by Frank1126lin** [comment]
> @jinfagang @Frank1126lin after reading the error again, I think you simply need to update your pytorch to 1.6 or higher. nn.Hardswish was introduced in 1.6.

Yeah, after update torch and torchvison to 1.6, It works.
And @glenn-jocher thank you so much.

**Comment by Yoshitsugi** [comment]
I can not still clear the AttributeError MSG by 
python:3.8.5
pytorch:1.7.0

AttributeError: Can't get attribute 'Hardswish' on <module 'torch.nn.modules.activation' from 'C:\\Users\\user\\anaconda3\\envs\\yolov5\\lib\\site-packages\\torch\\nn\\modules\\activation.py'>

**Comment by glenn-jocher** [comment]
@Yoshitsugi , thank you for your interest in YOLOv5! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and then install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by Yoshitsugi** [comment]
Hi Glenn
I have traced your instruction, but failed.
[yolov5new.txt](https://github.com/ultralytics/yolov5/files/5589576/yolov5new.txt)
[yolov5new.txt](https://github.com/ultralytics/yolov5/files/5589579/yolov5new.txt)

**Comment by glenn-jocher** [comment]
@Yoshitsugi use a verified environment, that's why we created them.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by Yoshitsugi** [comment]
Hi Glenn
I have changed from Windows 10 Python, torch environment  to Google Colab, resulted great success!!
Thanks for your greatest support!!!
![jidane](https://user-images.githubusercontent.com/55615101/100093032-4efd5a80-2e9a-11eb-9214-40c1b0e3e911.jpg)

**Comment by glenn-jocher** [comment]
@Yoshitsugi great! Unfortunately windows and conda can both be difficult environments for ML.

**Comment by Yoshitsugi** [comment]
Hi Glenn
your yolov5 is fit to colab, not to windows and conda. I believe some guy will challenge for conda environment for success, since your code is also written for conda environment.

**Comment by glenn-jocher** [comment]
@Yoshitsugi I can't speak for conda, as we don't use it or test on it, but Windows is fully supported. We run daily tests on all 3 operating systems including Windows of all core YOLOv5 functions, see below.

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@Yoshitsugi the latest windows results are here, from about 9 hours ago:
https://github.com/ultralytics/yolov5/runs/1450815198?check_suite_focus=true

**Comment by Yoshitsugi** [comment]
It is great!
Tell me what kind of cpu for your test?
Regards

**Comment by glenn-jocher** [comment]
@Yoshitsugi I'm not sure. This is the `windows-latest` environment described here:
https://github.com/actions/virtual-environments

**Comment by Yoshitsugi** [comment]
For google Colab, I have checked several code by you.  However Test code I have tried and takes time. I understand your program has enormous contents, so  I hesitate to proceed by windows. Maybe after I have got more capability for coding, I would like to try.
I have tried yolov3 and it was successful. yolov4 was hard to run, since it requires visual studio and cmake.
yolov5 looks partly successful supported by you.
Thank you for very much!
Regards

**Comment by glenn-jocher** [comment]
Great, I'm glad you find it useful!

**Comment by Yoshitsugi** [comment]
Hi Glenn
By the way, will you tell me how to recognize different photo other than Jidane.jpg by Colab yolov5?
Since the Colab yolov5 is highly automated, I can not load different photo.
Pls. advise

**Comment by glenn-jocher** [comment]
python detect.py --source anyphoto.jpg

**Comment by Yoshitsugi** [comment]
Hi Glenn
I have tried 'Kaggle Notebook with free GPU: https://www.kaggle.com/models/ultralytics/yolov5', resulting error MSG.
Pls. advise.
[Kaggle_yolov5.txt](https://github.com/ultralytics/yolov5/files/5610393/Kaggle_yolov5.txt)

**Comment by glenn-jocher** [comment]
@Yoshitsugi thanks for spotting this. I will update the kaggle notebook. 

In the meantime the image is in exp/, not exp0.

**Comment by Yoshitsugi** [comment]
Hi Glenn
I am trying to upload a new photo in exp/, but I can not find the folder in the google drive.
Tell me how to upload a photo?
Regards

**Comment by pderrenger** [comment]
Please ensure you're using the latest version of the YOLOv5 repository and check the error message for specific details. If the issue persists, try running the code in a fresh Kaggle environment.

**Comment by pderrenger** [comment]
Please ensure you're using the latest version of the YOLOv5 repository and that all dependencies are installed. If the issue persists, try running the code in a fresh Kaggle environment.
