### ISSUE TITLE
change filter size in yolov5 to be 3D instead of 2D

### ISSUE THREAD

**Issue by Nadayz** [ultralytics/yolov5#7742]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

from which file I can change the filter size to include a 3rd dimension so the kernel size would be NxNxN instead of NxN

**Comment by glenn-jocher** [comment]
@Nadayz there's no such thing as changing a 'filter size' from 2d to 3d. There are 3d convolution modules available torch, refer to the torch docs.

**Comment by frabob2017** [comment]
> @Nadayz there's no such thing as changing a 'filter size' from 2d to 3d. There are 3d convolution modules available torch, refer to the torch docs.

Is it possible for YOLO team to replace nn.conv2d with nn.conv3d in the future because it is very useful for medical imaging which is 3d format?  I believe if it change to 3d level, it would be robust in medical imaging.  I try to understand your code and do it. But it needs tremendous time to do it and it is not guaranteed to work. If YOLO team want to implement it in YOLOv5 or V8, it will be great.
