### ISSUE TITLE
Classes mixed up in onnx file

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#7748]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hello!

I trained my network and then converted the pt file (s model) to onnx using yolo's export script like this:

python export.py --weights EPS_ALL.pt --data EPS_ALL.yaml --include onnx

then I run inference using the onnx file instead of the pt file, as on my pc without GPU its almost 3 times faster. (90 ms instead of 230 ms) The detection works, and the confidence is as high as it was with the pt file, but the classes are all mixed up.

In both cases I pass in the same yaml file as data, ans as seen above it has also been used for the conversion. but If I run inference with the onnx then the output result does not match the listing in the yaml file.
Given that it only outputs a single class on any given location, and with a really high score, I am sure that its a problem related to the order of the classes. so class 5 in the onnx file does not match the class 5 in the yaml file. 

What am I doing wrong?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tanzerlana 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
