### ISSUE TITLE
Conversion to TF

### ISSUE THREAD

**Issue by abhimanyuchadha96** [ultralytics/yolov5#7755]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

I am trying to convert an older version of Yolo to TF/Keras and I am hitting a bug.

The weights of the keras models aren't initialized until it is built but to build it one needs to pass it through a dummy/random input.

The issue is at the layer C3 which happens to have another keras.sequential inside the function and thus it ends up giving me this error
![Screen Shot 2022-05-10 at 4 54 37 PM](https://user-images.githubusercontent.com/37940438/167720187-9574ecb6-a769-
![Screen Shot 2022-05-10 at 4 54 49 PM](https://user-images.githubusercontent.com/37940438/167720217-d0810b8e-abc0-40a1-ac9e-975eff3d6b32.png)
48ea-9993-2bcacd2ac137.png)
.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abhimanyuchadha96 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
