### ISSUE TITLE
How to deploy a custom trained model in AWS?

### ISSUE THREAD

**Issue by Vijay-P1999** [ultralytics/yolov5#7757]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello,
I have trained a yolov5 model in my custom dataset and now i need to deploy it in AWS. I researched about this already. Based on some suggestion, I tried this [AWS EC2 Inf1 instance](https://aws.amazon.com/machine-learning/inferentia/). 
I guess it doesn't have GPU support. 

Can some one suggest a way to deploy it in aws or what instance to use for deploying?

**Comment by glenn-jocher** [comment]
@Vijay-P1999 see [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)

**Comment by SanVlug** [comment]
@glenn-jocher Do you guys have a tutorial for azure ML studio. When i run it i get a syntax error. 
File "train.py", line 80
    LOGGER.info(colorstr('hyperparameters: ') + ', '.join(f'{k}={v}' for k, v in hyp.items()))
                                                                   ^
SyntaxError: invalid syntax

**Comment by glenn-jocher** [comment]
@SanVlug can you provide steps to reproduce, i.e. exactly what website you went to and what you did?

**Comment by SanVlug** [comment]
@glenn-jocher In the Azure portal, open the machine learning tab. create a workspace and open the Azure Machine Learning Studio. Then I opened a notebook. Ive put the MS doc link of the notebook below. 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-run-jupyter-notebooks 

Then i added the cloned Yolov5 map in the notebook files together with the maps with my labels and images. 
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-manage-files

Then i installed tensorflow 2.3.1, tensorboard 2.4.1, torch, and the requirement.txt file and ran 
!python train.py --img 640 --batch 16 --epochs 30 --data datasetyaml.yaml --weights yolov5s.pt --cache

**Comment by glenn-jocher** [comment]
@SanVlug got it. I don't have time to go through the whole Azure setup now, as we don't currently use Azure, even though we are part of their $120k credit program.

Can you start from a clean Azure notebook and use the exact same cells as the Colab notebook and show a screenshot of the result?

Setup
```python
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks
```

Inference
```python
!python detect.py --weights yolov5s.pt --img 640 --conf 0.25 --source data/images
```

**Comment by SanVlug** [comment]
@glenn-jocher Thanks for the quick responses. 

Here is the output of the lines of code. 
![image](https://user-images.githubusercontent.com/97685453/168086713-4418b211-ee6e-4e07-9906-4a60dcb9f809.png)

EDIT: The rocket symbol causes the error in the notebook. 
![image](https://user-images.githubusercontent.com/97685453/168088097-341ee517-f82a-4b9a-a993-4f0b5f28b622.png)

if i delete the rocket symbol from train.py i get the following error msg: 
![image](https://user-images.githubusercontent.com/97685453/168088524-621f8b05-e347-4b26-b41e-ebfff836a208.png)


And here is my map layout
![image](https://user-images.githubusercontent.com/97685453/168087100-92238856-7d42-49a1-ba4d-2f9e84f6eeca.png)

i skipped the roboflow part since i already have my labelled data. with the centreX, centreY, Width and heigth of the bbox.

**Comment by Vijay-P1999** [comment]
@SanVlug Check if this helps - [issue](https://github.com/defaultnamehere/tinder-detective/issues/11#issuecomment-234474125)
