### ISSUE TITLE
How yolov5 calculates map when testing datasets?

### ISSUE THREAD

**Issue by shisenglin** [ultralytics/yolov5#7794]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I'm a novice, and I don't know how yolov5 calculates map when testing datasets. Hope to receive an answer.

**Comment by glenn-jocher** [comment]
@shisenglin mAP is the area under the Precision-Recall curve. See https://en.wikipedia.org/wiki/Precision_and_recall

**Comment by shisenglin** [comment]
> @shisenglin mAP 是精度-召回率曲线下的面积。请参见 https://en.wikipedia.org/wiki/Precision_and_recall
Thank you for your reply！I understand the concept of mAP, but I just can't find the code you wrote to calculate mAP in yolov5, or I don't know if there is any code in YOLOv5 to calculate mAP, and I don't know how to run it to generate an image of mAP.

**Comment by glenn-jocher** [comment]
@shisenglin see utils/metrics.py

**Comment by shisenglin** [comment]
> @shisenglin see utils/metrics.py

Can I run the file metrics.py to generate mAP images?

**Comment by glenn-jocher** [comment]
@shisenglin val.py computes mAP:

```
python val.py --weights yolov5s.pt --data coco128.yaml
```

**Comment by shisenglin** [comment]
> @shisenglin val.py 计算 mAP：
> 
> ```
> python val.py --weights yolov5s.pt --data coco128.yaml
> ```

![f31b1a410387c411f304e2c7c7088ab](https://user-images.githubusercontent.com/101716952/168294567-d9a89694-007f-413f-83bb-e5406160993a.png)
This error occurs after running ： OSError: [WinError 1455] The page file is too small to complete the operation. Error loading "D:\Anaconda3\envs\luoge\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
What is the reason for this error?

**Comment by glenn-jocher** [comment]
@shisenglin this is a windows error unrelated to YOLOv5. See https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows

**Comment by shisenglin** [comment]
> @shisenglin this is a windows error unrelated to YOLOv5. See https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows

![image](https://user-images.githubusercontent.com/101716952/168303638-53254653-109b-40e5-8846-e1cfb1f2298f.png)
Thanks to the author's answer, the problem of reporting errors has been solved, and now the operation has results, but the values of P and R seem to be a little low.

**Comment by glenn-jocher** [comment]
@shisenglin 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.

## Dataset

- **Images per class.** ≥ 1500 images per class recommended
- **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
- **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
- **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
- **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
- **Label verification.** View `train_batch*.jpg` on train start to verify your labels appear correct, i.e. see [example](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#local-logging) mosaic.
- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

<a href="https://arxiv.org/abs/1405.0312"><img width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png" alt="COCO Analysis"></a>


## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. [VOC](https://github.com/ultralytics/yolov5/blob/master/data/VOC.yaml), [VisDrone](https://github.com/ultralytics/yolov5/blob/master/data/VisDrone.yaml), [GlobalWheat](https://github.com/ultralytics/yolov5/blob/master/data/GlobalWheat2020.yaml)). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
                                             custom_pretrained.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. [COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [Objects365](https://github.com/ultralytics/yolov5/blob/master/data/Objects365.yaml), [OIv6](https://storage.googleapis.com/openimages/web/index.html)). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```


## Training Settings

Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.

- **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
- **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
- **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
- **Hyperparameters.** Default hyperparameters are in [hyp.scratch.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyp.scratch.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

## Further Reading

If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains: http://karpathy.github.io/2019/04/25/recipe/

Good luck 🍀 and let us know if you have any other questions!

**Comment by shisenglin** [comment]
@glenn-jocher Thank you very much to the author for helping me so patiently with the problems that arose during the use of yolov5. I think the answers you gave were extremely comprehensive and useful for me as a novice. I will come back to you again if I encounter any other problems in using yolov5, and I hope you would like to give me answers again. Thank you very much!

**Comment by shisenglin** [comment]
@glenn-jocher     I have trained my own dataset using yolov5 to get the training model. I've learned to put the training model to detect images by using detect.py, but I don't know how to detect videos. If I want to detect videos, where do I need to change the code? I hope the author can reply and answer, thanks a lot!

**Comment by glenn-jocher** [comment]
@shisenglin see https://github.com/ultralytics/yolov5#quick-start-examples for inference examples on videos:

<img width="945" alt="Screen Shot 2022-05-13 at 6 26 39 PM" src="https://user-images.githubusercontent.com/26833433/168326775-6c45fbde-5f76-415a-bcf2-591232cd778d.png">

**Comment by shisenglin** [comment]
![1652460656(1)](https://user-images.githubusercontent.com/101716952/168331398-66881913-84d0-43dd-9528-28dff81deeac.jpg)
@glenn-jocher   So in the above image I just need to change the f1.jpg in default = ROOT / 'data/images/f1.jpg' to vid.mp4 and I will be able to detect the video right?

**Comment by glenn-jocher** [comment]
@shisenglin yes, you are correct! Changing the path from `f1.jpg` to `vid.mp4` would allow you to detect the video. Additionally, you may also need to specify the output directory for the video detections by setting the `--save-txt` flag. Good luck with your video detections!
