### ISSUE TITLE
use the trained model for detection

### ISSUE THREAD

**Issue by starsky68** [ultralytics/yolov5#782]
## ❔Question
When I use the trained model for detection, sometimes the following error occurs.

## Additional context
File "detect.py", line 173, in <module>
    detect()
  File "detect.py", line 35, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/-----/code/yolov5/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/----/.local/lib/python3.8/site-packages/torch/serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/----/.local/lib/python3.8/site-packages/torch/serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by yonghui-bluvec** [comment]
same question

**Comment by glenn-jocher** [comment]
Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a new `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible with [COCO](https://cocodataset.org/#home) or [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, ensure your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by yonghui-bluvec** [comment]
I have the model yolov5m trained on my own dataset and the output is stored in `exp6` folder, called last.pt. 
If I move the last.pt out and load it, it will show such error. However, if I keep it in `exp6` and load it, it can work. I also tried to convert it in torchscript type, it also cannot work.

It is no more an issue for my test, but it is still a question to me.

**Comment by xiaomimi3456** [comment]
> I have the model yolov5m trained on my own dataset and the output is stored in `exp6` folder, called last.pt.
> If I move the last.pt out and load it, it will show such error. However, if I keep it in `exp6` and load it, it can work. I also tried to convert it in torchscript type, it also cannot work.
> 
> It is no more an issue for my test, but it is still a question to me.

Maybe it's because last.pt' has been updated when you copy it

**Comment by ShirleyHe2020** [comment]
> Hello, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:
> 
> * **Your changes to the default repository**. If your issue is not reproducible in a new `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
> 
> ```shell
> sudo rm -rf yolov5  # remove existing
> git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
> python detect.py  # verify detection
> # CODE TO REPRODUCE YOUR ISSUE HERE
> ```
> 
> * **Your custom data.** If your issue is not reproducible with [COCO](https://cocodataset.org/#home) or [COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
> * **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, ensure your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below.
> 
> If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!
> 
> ## Requirements
> Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.6`. To install run:
> 
> ```shell
> $ pip install -r requirements.txt
> ```
> 
> ## Environments
> YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Google Colab Notebook** with free GPU: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Kaggle Notebook** with free GPU: https://www.kaggle.com/models/ultralytics/yolov5
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/280faedaf431e4c0c24fdb30ec00a66d627404e5c4c498210d3f014dd58c2c7e/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)
> 
> ## Status
> ![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)
> 
> If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

--------------------
the environment meet requirement ,  still got  same issue.

**Comment by ShirleyHe2020** [comment]
Traceback (most recent call last):
  File "detect.py", line 175, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/qian/YOLOv5/202103yolov5/yolov5-master/models/experimental.py", line 118, in at    tempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "/home/qian/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, i    n load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/qian/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 599, i    n _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f    .name))

**Comment by glenn-jocher** [comment]
@ShirleyHe2020 if your error is reproducible then please submit a minimum reproducible example:
https://docs.ultralytics.com/help/minimum_reproducible_example/

**Comment by ifahim** [comment]
> Traceback (most recent call last):
> File "detect.py", line 175, in
> detect()
> File "detect.py", line 33, in detect
> model = attempt_load(weights, map_location=device) # load FP32 model
> File "/home/qian/YOLOv5/202103yolov5/yolov5-master/models/experimental.py", line 118, in at tempt_load
> ckpt = torch.load(w, map_location=map_location) # load
> File "/home/qian/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, i n load
> return _load(f, map_location, pickle_module, **pickle_load_args)
> File "/home/qian/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 599, i n _load
> raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f .name))

How did you find solve the problem? I am having the same issue. thanks

**Comment by ifahim** [comment]
@ShirleyHe2020 @xiaomimi3456  How did you fix the error? I am having the same issue. 
I trained the model on server where detect.py works w/o any error. But when I move the `runs` folders to my local machine and execute, it has issue. I git checked out the same codebase which is on the server as well. 

thanks

**Comment by musician-k** [comment]
I also encountered this problem, and I solved it. 
The solution is: download the corresponding .pt file at https://github.com/ultralytics/yolov5/releases. The .pt file downloaded by the code is incomplete.

**Comment by pderrenger** [comment]
It sounds like the issue was due to an incomplete download. Ensuring the `.pt` file is fully downloaded from the official releases page should resolve the problem. If you continue to experience issues, verify the file integrity after downloading.
