### ISSUE TITLE
Error loading from torch hub

### ISSUE THREAD

**Issue by myasser63** [ultralytics/yolov5#7968]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am using the code below to import my custom model using torch hub. When I run more than once I get this error. It works for the first time after that it doesn't.
```
import torch
CKPT_PATH = '/content/custom.pt'
model = torch.hub.load('ultralytics/yolov5', 'custom', path=CKPT_PATH)
model.conf = 0.2
model.iou = 0.45
```

Error message:
```
[/root/.cache/torch/hub/ultralytics_yolov5_master/models/common.py](https://localhost:8080/#) in <module>()
     22 from torch.cuda import amp
     23 
---> 24 from utils.dataloaders import exif_transpose, letterbox
     25 from utils.general import (LOGGER, check_requirements, check_suffix, check_version, colorstr, increment_path,
     26                            make_divisible, non_max_suppression, scale_coords, xywh2xyxy, xyxy2xywh)

ModuleNotFoundError: No module named 'utils.dataloaders'

```

**Comment by iresusharma** [comment]
you can try this, worked fine for me :- 
model = torch.hub.load('./yolov5', 'custom', path='path of your trained model', source='local')  # local repo

yolov5 - is your yolov5 api path locally.

**Comment by glenn-jocher** [comment]
@myasser63 your YOLOv5 cache is out of date. To update:

- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`

**Comment by myasser63** [comment]
@glenn-jocher @iresusharma thanks for your help. I will try it

**Comment by myasser63** [comment]
@glenn-jocher I am still getting the same error. I am importing other libraries as below. doesn't it affect the model loading?.

```
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from tqdm.notebook import tqdm
tqdm.pandas()
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm
import glob
import shutil
import sys
import torch
from PIL import Image
import ast
from matplotlib import colors
```

**Comment by glenn-jocher** [comment]
@myasser63 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
