### ISSUE TITLE
Load onnx model with torch.hub.load

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#7982]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

**Hello,
Im trying to load an onnx model in torch.hub.load via GoogleColab but I'm getting this error: 
I tried this locally in my PC and I get the same exact error**

![image](https://user-images.githubusercontent.com/82477000/170340117-1e8b5c1a-a494-4681-a314-bce1514bd28f.png)

**I made this onnx model with my yolov5 model using this argument :**
` python /content/yolov5/export.py --weights /content/yolov5/best.pt --batch-size 16 --include onnx --imgsz 416 416 --data /content/yolov5/Latest/data.yaml`

### Environment

YOLOv5 🚀 v6.1-223-g1dcb774
Python-3.7.13 torch-1.11.0+cu113
Tesla T4, 15110MiB ( google colab )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iHafez user error. You exported a model at batch size 16 img size 416 and you are trying to run inference at batch size 2 image size 640.

**Comment by ghost** [comment]
@glenn-jocher Thanks for your response 
Okay now, how can I run inference at batch size 16 image size 416?

**Comment by glenn-jocher** [comment]
You can use model(im, size=416) to set the image size, which is explained in the PyTorch Hub tutorial, see for details. For 16 images you need to batch 16 images rather than 2.

## YOLOv5 Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
* [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
* [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
* [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
* [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
* [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
* [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)&nbsp; ⭐ NEW
* [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
Thank you so much! , i fixed it with model(im, size=416)

**Comment by ghost** [comment]
@glenn-jocher 
**I have one more question please, how can i set the batch for a live detection window ( im using the onnx model as its live detecting everything shown on my desktop screen) so there is not any images to set batch for ( higher batch gives me more fps on the detection window) **

**Comment by ghost** [comment]
@glenn-jocher ?

**Comment by glenn-jocher** [comment]
@iHafez custom workflows are on you to develop. Obviously the number of images you place into a batch is the batch size.

**Comment by ghost** [comment]
Okay... but how can i make the opencv ( detection window ) appear as 16 batches ? or maybe batch it to 16 in the same opencv window, because it only counts as a 1 batch, doing this will increase fps and performance for me 😁

code example for my opencv window:

```import numpy as np
import cv2
from mss import mss
from PIL import Image
import torch

# Screen capture
sct = mss()

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='last.pt')  # local custom model

while 1:
    #set the capture size
    w, h = 800, 640
    #set the capture position
    monitor = {'top': 0, 'left': 0, 'width': w, 'height': h}
    img = Image.frombytes('RGB', (w,h), sct.grab(monitor).rgb)
    screen = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    #set the model use the screen 
    result = model(screen)
    result.display(render=True) 
    
    #show the result
    cv2.imshow('Screen', result.imgs[0])

    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break```

so the result is only 1 batch, how can i make the opencv 16 batch

Thank You.

**Comment by ghost** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@iHafez workflow customization is up to you and outside the scope of our support.
