### ISSUE TITLE
number labels is not same when i set different confidence

### ISSUE THREAD

**Issue by root12321** [ultralytics/yolov5#8004]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

in my session ,when i test map,precision,recall,the first time i set confidence is 0.001,the result is :
![image](https://user-images.githubusercontent.com/28287748/170645532-fae3332b-863d-4606-826c-9ced7feaf28b.png)
when i set  set confidence is 0.2,the result is :
![image](https://user-images.githubusercontent.com/28287748/170645778-405d843d-6967-4b7a-9441-425562e3a84d.png)
you can see the number of Labels is not same ,what is the reason for that ?
my code is the newest yolov5

**Comment by glenn-jocher** [comment]
@root12321 as the code clearly states results for anything other than the default confidence are invalid:
https://github.com/ultralytics/yolov5/blob/a6e99e4d66dcdffb5782c13150abc29c87801274/val.py#L365-L366

**Comment by root12321** [comment]
> @root12321 as the code clearly states results for anything other than the default confidence are invalid:
> 
> https://github.com/ultralytics/yolov5/blob/a6e99e4d66dcdffb5782c13150abc29c87801274/val.py#L365-L366

it can not solve the question about the different of  Labels number ,but in the code yolov5-6.0 version , diffierent confidence have same labels number, i dont know what changed in the newest code

**Comment by glenn-jocher** [comment]
@root12321 thanks for the feedback! Unfortunately it's hard to narrow down the exact change that causes this difference, as there's about 500 PRs that have been pushed between now and v6.0 release.

**Comment by root12321** [comment]
may be you can not understand what i meaning  
i test a dataset where have 10 images and 10 labels,  one class. 
in code yolov5-6.0 , i run the code val.py and result is :
![微信截图_20220530090910](https://user-images.githubusercontent.com/28287748/170900350-53892310-9d7f-49b2-97ee-81df62b167a4.png)
in code yolov5-6.1 , i run the code val.py and result is :
![微信截图_20220530091008](https://user-images.githubusercontent.com/28287748/170900377-6b61f8bb-abcd-4d55-aef9-d9366a8b8caa.png)
you can see the diffference. in code yolov5-6.0,number of labels is 10,and it is right,but in yolov5-6.1,number of labels is 9, it is wrong , i dont know what happen in the new code of yolov5-6.1 , can you  explain it , thank you !

**Comment by root12321** [comment]
@glenn-jocher  
may be you can not understand what i meaning
i test a dataset where have 10 images and 10 labels, one class.
in code yolov5-6.0 , i run the code val.py and result is :
![微信截图_20220530090910](https://user-images.githubusercontent.com/28287748/170900679-b9970404-6476-4457-997c-ff6235a4583b.png)

in code yolov5-6.1 , i run the code val.py and result is :
![微信截图_20220530091008](https://user-images.githubusercontent.com/28287748/170900689-df8e6d7c-26c0-475c-8f9d-463375628462.png)

you can see the diffference. in code yolov5-6.0,number of labels is 10,and it is right,but in yolov5-6.1,number of labels is 9, it is wrong , i dont know what happen in the new code of yolov5-6.1 , can you explain it , thank you !

**Comment by glenn-jocher** [comment]
@root12321 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
