### ISSUE TITLE
how to put opencv tracker in Yolov5? 

### ISSUE THREAD

**Issue by LimJihu** [ultralytics/yolov5#8075]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi. i have to put opencv-tracker(maybe KCF) in Yolov5. 

 um, if you've used opencv-tracker before, you know about this.

i don't want to selectROI with my mouse. i just want to put detected bbox coordinates from detect.py 
and i want to track every frames in video. 

so this is my code (this is plots.py)
![image](https://user-images.githubusercontent.com/89961242/171547517-34290b39-f0d0-46b9-ad5e-05b6c258a75e.png)

i'm having 
error: (-5:Bad argument) One or more matrix operands are empty. in function 'checkOperandsExist'
error. plz help me. i want how to wirte the code.

**Comment by glenn-jocher** [comment]
@LimJihu 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- [Extended Kalman Filter (EKF)](https://en.wikipedia.org/wiki/Kalman_filter)
- [Kanade-Lukas-Tomasi (KLT) Feature Tracker](https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker): 
- [YOLOv5 DeepSort Tracker](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) 
- [Apple iOS VNTrackObjectRequest](https://developer.apple.com/documentation/vision/tracking_multiple_objects_or_rectangles_in_video)

Good luck 🍀 and let us know if you have any other questions!

**Comment by Hbelief1998** [comment]
I have encountered the same problem. Have you solved it?

**Comment by glenn-jocher** [comment]
@Hbelief1998 I would recommend checking that the output of the YOLOv5 `detect.py` script is not empty when passing the bounding box coordinates to the OpenCV tracker. You might want to ensure that the detected bounding boxes are valid and non-empty before passing them to the tracker. If the issue persists, it might be helpful to share the specific code snippet where you are encountering the error so that the community can better assist you. Good luck with your implementation! Let me know if you need further assistance.
