### ISSUE TITLE
Yolov5 on jupyter notebook

### ISSUE THREAD

**Issue by cyndyNKCM** [ultralytics/yolov5#8078]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When i execute the training code on jupyter notebook, i encounter some problems on the syntax especially on the fstring syntax.
How can i fix this issue please?

**Comment by glenn-jocher** [comment]
@cyndyNKCM 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by cyndyNKCM** [comment]
![Capture d’écran (39)](https://user-images.githubusercontent.com/65983769/171624235-71a29b8b-f1f1-4a95-acdd-3c8d832c8c20.png)

**Comment by cyndyNKCM** [comment]
Here is the problem.
I didn't modify anything in the code.

**Comment by glenn-jocher** [comment]
@cyndyNKCM that's really strange. detect.py is tested every 24 hours and on every commit as part of the YOLOv5 CI here, and everything is green (all tests are passing):
https://github.com/ultralytics/yolov5/actions/runs/2425270312
<img width="1428" alt="Screen Shot 2022-06-02 at 2 16 35 PM" src="https://user-images.githubusercontent.com/26833433/171627230-771769ba-e818-4e43-acde-79e9e1921e26.png">

If you want to use a notebook I'd recommend our Colab notebook, where everything is verified working correctly:
https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb?hl=en

**Comment by cyndyNKCM** [comment]
The code works well on google colab but because of my internship i have to work on a local server and so on jupyter notebook .

**Comment by glenn-jocher** [comment]
@cyndyNKCM what is the OS, Python, torch versions?

**Comment by cyndyNKCM** [comment]
The OS is Windows 
Python 3.8
torch 1.11.0

**Comment by glenn-jocher** [comment]
@cyndyNKCM is there a way we can reproduce this ourselves? i.e. how are you running the notebook?

**Comment by cyndyNKCM** [comment]
I just run the cell python detect.py --img 640 --batch 32 --epochs 20 --data ... --weights ... --nosave --cache
