### ISSUE TITLE
Torch.distributed error 

### ISSUE THREAD

**Issue by noreenanwar** [ultralytics/yolov5#8132]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

 I am facing the following issue.I don't know how to resolve it.

    import torch.distributed as dist
ModuleNotFoundError: No module named 'torch.distributed'

**Comment by glenn-jocher** [comment]
@noreenanwar 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ep5000** [comment]
@noreenanwar fyi I encountered this same issue and downgrading to torch 1.7.1 resolved the issue for me:

```
pip uninstall torch torchvision

pip install torch==1.7.1 torchvision
```

**Comment by codingSoul289** [comment]
torch==1.7.1 doesn't exist apparently

**Comment by glenn-jocher** [comment]
Hello @codingSoul289! It seems there might have been a misunderstanding regarding the PyTorch version. The `torch.distributed` module should be available in all recent PyTorch versions. If you're encountering a `ModuleNotFoundError`, it's possible that your PyTorch installation is incomplete or corrupted.

Here's what you can do:

1. Ensure you have a compatible version of PyTorch installed. You can check the [PyTorch official website](https://pytorch.org) for the command to install the correct version for your system.

2. Try reinstalling PyTorch using the official installation command from the PyTorch website.

3. If you're using a virtual environment, make sure it's activated when you run your code.

4. Verify that your Python environment is set up correctly and that you're using the correct Python interpreter where PyTorch is installed.

If the issue persists after trying these steps, please provide more details about your environment, such as the PyTorch version, the system you're using, and whether you're running the code on a local machine or a remote server. This will help us diagnose the problem more effectively. Thanks! 😊
