### ISSUE TITLE
 I guess the camera won't turn off

### ISSUE THREAD

**Issue by bilalemirgunay** [ultralytics/yolov5#8170]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, 
I am trying to detect an object by calling the run function in the **detect** file. I want to exit the run function after the object is detected. I don't have a problem with this. But when I want to call the function for the second time, the camera gives the following warning: 
**[ WARN:1@87.710] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1752) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821**

When I run it on the computer, I don't have a problem even though I get a warning. But when I run it on raspberry pi I get an error.

import detect
detect.run(source=0, weights="best.pt")
This is how i access the function.

Could you help? (I apologize for my English)

**Comment by glenn-jocher** [comment]
@bilalemirgunay 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by VYRION-Ai** [comment]
Do like that
https://github.com/ultralytics/yolov5/issues/8059

**Comment by bilalemirgunay** [comment]
I will try, thank you

**Comment by glenn-jocher** [comment]
@bilalemirgunay you're welcome! If you have any further questions or need assistance, feel free to ask. Good luck with your tests!
