### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

### ISSUE THREAD

**Issue by tomjerrygithub** [ultralytics/yolov5#82]
When use  yolov5m.yaml and  yolov5m.pt

  File "train.py", line 79, in train
    model = Model(opt.cfg).to(device)
  File "/data1/yolov5/yolov5/models/yolo.py", line 65, in __init__
    m.anchors /= m.stride.view(-1, 1, 1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

**Comment by glenn-jocher** [comment]
@tomjerrygithub this issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a fresh `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov5  # remove existing
git clone https://github.com/ultralytics/yolov5 && cd yolov5 # clone latest
python detect.py  # verify detection
python train.py  # verify training (a few batches only)
# CODE TO REPRODUCE YOUR ISSUE HERE
```
- **Your custom data.** If your issue is not reproducible with COCO data we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
- **Your environment.** If your issue is not reproducible in our [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) VM or Jupyter Notebook we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, PyTorch >= 1.5 etc. You can also use our [Jupyter Notebook](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> and our [Docker Image](https://hub.docker.com/r/ultralytics/yolov5) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker) to test your code in a working environment.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!

**Comment by abczww** [comment]
I had same issue when I was using "yolov5m.yaml", but if I changed the model to "yolov5s.yaml" or "yolov5l.yaml", everything works well. I've no idea why just "yolov5m.yaml" had this issue.
 
The full tracbak like this:

Traceback (most recent call last):
  File "E:/apps/yolov5-master/train.py", line 398, in <module>
    train(hyp)
  File "E:/apps/yolov5-master/train.py", line 78, in train
    model = Model(opt.cfg).to(device)
  File "E:\apps\yolov5-master\models\yolo.py", line 65, in __init__
    m.anchors /= m.stride.view(-1, 1, 1)
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

**Comment by glenn-jocher** [comment]
@tomjerrygithub thanks for the bug report, but you need to supply **minimum viable code to reproduce**. 

Simply saying when you 'use' is insufficient for anyone to have the slightest idea of how to reproduce.

**Comment by abczww** [comment]
I reproduce this issue by this way:
I modified the train.py line 367 to "models/yolov5m.yaml".

I tried "models/yolov5s.yaml", "models/yolov5l.yaml", "models/yolov5x.yaml", all of them could work well. Only "models/yolov5m.yaml" didn't work.

part of my train.py file:

 parser = argparse.ArgumentParser()
    parser.add_argument('--epochs', type=int, default=200)
    parser.add_argument('--batch-size', type=int, default=4)
    parser.add_argument('--cfg', type=str, default='models/yolov5m.yaml', help='*.cfg path')
    parser.add_argument('--data', type=str, default='data/dataset3000.yaml', help='*.data path')
    parser.add_argument('--img-size', nargs='+', type=int, default=[640, 640], help='train,test sizes')

**Comment by glenn-jocher** [comment]
@abczww your issue is not reproducible. Please ensure your issue is reproducible with the default coco128.yaml dataset with a working environment i.e. the colab notebook. 

<img width="1193" alt="Screen Shot 2020-06-17 at 8 37 08 AM" src="https://user-images.githubusercontent.com/26833433/84918671-c3270d00-b075-11ea-9419-f6f6998342ca.png">

**Comment by abczww** [comment]
@glenn-jocher Thank you so much. I think I know why I got this issue(error), I trained the model(by yolov5l) in RTX2070, so I could get and reproduce this issue. Then I tried the same app in a GPU server with 1080Ti, Everything works well. So I think this issue caused by GPU memory, yolov5l and yolov5x models need much more GPU memory.

**Comment by ml5ah** [comment]
@glenn-jocher I am unable to post my custom dataset due to constraints but I can offer share some observations.
As noted by several others, yolov5m crashes with a custom dataset while yolov5l and yolov5s work with the same dataset.
I have noticed that changing the number of classes from 11 to 10 in my dataset (removing one class) solves this issue.
Hope this is helpful in debugging.

**Comment by glenn-jocher** [comment]
@ml5ah if the issue is with a pretrained checkpoint, all checkpoints were replaced yesterday as part of PANet updates. You should delete all of your local models and update your repo and try again.

**Comment by zzff-sys** [comment]
@glenn-jocher 
Hello! When I tried to change the structure of Yolov5, I added a Cat backbone and cat head, as shown below, to detect smaller targets:
![R4ERAZF E5}0J7(P)GNJB96](https://user-images.githubusercontent.com/71440760/144748851-f7c20ff7-bc2e-46df-ace3-9dc6da50bc46.png)
The following error occurs:
Traceback (most recent call last):
  File "/tmp/pycharm_project_509/train.py", line 628, in <module>
    main(opt)
  File "/tmp/pycharm_project_509/train.py", line 525, in main
    train(opt.hyp, opt, device, callbacks)
  File "/tmp/pycharm_project_509/train.py", line 117, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/tmp/pycharm_project_509/models/yolo.py", line 143, in __init__
    m.anchors /= m.stride.view(-1, 1, 1)
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

![UXR )7923MPLCQ_JB(`L}4C](https://user-images.githubusercontent.com/71440760/144748803-ad995188-9827-4dcb-a338-5c8e7348c914.png)

**Comment by glenn-jocher** [comment]
@zzff-sys it looks like you've added an additional output but not defined any anchors for that layer. You probably just want to set `anchors: 3` in your yaml and let AutoAnchor evolve anchors.

**Comment by zzff-sys** [comment]
@glenn-jocher 
Yes, thank you. Later I also understood that I was missing a small target anchor
