### ISSUE TITLE
About imgsize and best.pt

### ISSUE THREAD

**Issue by GreenHandForCoding** [ultralytics/yolov5#8226]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I used yolov5x in our project. The size of my photos is 1328*1168. At the start, I tried imgsize=640 to train, the result is not good. Then I tried 1280 that I found is best(I also tried 1312 or 1024 and so on). 
Then here is another one:
I set epochs 600, and it early stopped at about 360, why the best.pt is the same to the last.pt, which I think is not reasonable. I think the best.pt may appear in 150 or another epoch, anyway the best.pt shouldn't be the last.pt 

Can you explain to me? Thx
![Snipaste_2022-06-16_08-51-43](https://user-images.githubusercontent.com/106043395/173967794-0743f471-91e6-4c2b-8ed3-5dc2903af2c0.png)

**Comment by AyushExel** [comment]
> he best.pt is the same to the last.pt, which I think is not reasonable. I think the best.pt may appear in 150 or another epoch, anyway the best.pt shouldn't be the last.pt

This isn't completely accurate. In fact as long as model is improving even slightly, last.pt and best.pt will be same because the best model is the last saved model( as it improved). 
Which is probably what is happening in your case. When you stopped the training, your model was either still improving or at-least the score of the last epoch was the best. You can take a look at the training logs to see the fitness score

**Comment by GreenHandForCoding** [comment]
Sorry, I ignore something. I change the name of the best.pt when it stops, so ignore the sencond Q.
Here is the new:
I used the same datasets and config to train, but I got two different models, one is better. How to make sure I've got the best result in our future work? Try more?

**Comment by AyushExel** [comment]
@GreenHandForCoding changing config can involve any number of changes in hyperparameters. So, there's there's no way to be absolutely sure if you've got THE best model by randomly changing a few params. But with that said, you should keep there points in mind:
* Stick with the default params wherever possible because those defaults as set after multiple experiments on coco dataset which is a great benchmark for detection.
* Training at higher resolution generally gets you better metrics at the cost of memory and speed. But more than the size of the image as train time, the size of objects in the overall training set matters more in performance of the model.

**Comment by GreenHandForCoding** [comment]
@AyushExel Hey, thank you very much. I know the size of objects has a big effect on model. So I changed the imgsize to fit my photos, then find the best input-size. I mean I train twice when I keep the data and config same, then I got two different pt of courese they are different and in different performances. Is that mean  I should train two or three times or more to get the best pt?

**Comment by AyushExel** [comment]
@GreenHandForCoding you could do that. This process is called hyper-parameter tuning and imgsz is just one hyperparameter. But its not guaranteed that training 2-3 times more will get you the best possible model but you can try. 

Also, I don't know the change in accuracies you're seeing when changing imgsz but I guess with all params being same, the accuracies you'll get will be in the same ballpark. So, I'd suggest trying to apply the model to your use-case and and then come back to tune the hyperparams further if you need more accurate detections.

**Comment by GreenHandForCoding** [comment]
@AyushExel  But the accuracies are different. I mean in the same imgsz,batchsize, epoch and so on. One may earlystop at 200 epoch, another may stop at 300. Can it explain why the accuracies are different.
Let us suppose now the hyperparams are best and can be used in my project, I still need to train some times to find the best best.pt to detect.
Am I right?

**Comment by AyushExel** [comment]
@GreenHandForCoding yes that is correct. But tuning each parameter manually can be an endless task. It preferred to use parameter evolution/ sweeps on a subset of dataset to find the best set of params and then train on those params

**Comment by GreenHandForCoding** [comment]
@AyushExel I find I didn't use evolve module. I'll try next. Thanks a lot.
