### ISSUE TITLE
Inference time changes on same weight file with same image

### ISSUE THREAD

**Issue by devendraswamy** [ultralytics/yolov5#8232]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I was run the API for 100 times for same single image and here i found the inference time was got changed at every API call for same image , I don't know why its happens , Could anyone please tell the problem root cause and solution , Thanking you in advance.

### Additional

The inference time got changed with onnx weight file on same image for 100 API calls.

**Comment by AyushExel** [comment]
@devendraswamy it all depends on a lot of things. Can you provide the time profile of the experiment, i.e, what the avg variation in inference across 100 images? A little variation is always expected and without the exact info it'll be difficult to diagnose the problem.
 I can point to a few things - first, a little latency can be caused by the server design and what API you're using. Almost all serving apis have speed differences. When running inference through a server the total time taken is not just the model execution time but it also includes time taken for the data to be read by the server through a port and related operations

**Comment by devendraswamy** [comment]
[YOLO_LoadTestResult_onnx_woint.txt](https://github.com/ultralytics/yolov5/files/8926393/YOLO_LoadTestResult_onnx_woint.txt) , Results are stored in milliseconds. 
Thank you for the reply @AyushExel ,Please review the above file for time records on 100 API calls , and we are using Flask server in local machine, 
System specs: 16 gb RAM , Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz   2.80 GHz , Windows 10 Pro , 4 cores cpu.

Note: we are inference the model with same image on same weight file for 100 times
