### ISSUE TITLE
Add Jupyterlab functionality in Docker

### ISSUE THREAD

**Issue by NanoCode012** [ultralytics/yolov5#824]
## 🚀 Feature

Add JupyterLab functionality when using Docker.

## Motivation/Pitch

Running in docker is very easy. It allows us to use the latest version without any environment issues, however, right now, we only see CLI. It would be easier to have an interface such as JupyterLab or Jupyter notebook. This could be valuable for new people. I propose JupyterLab as it is said to be "the next generation" for Jupyter.

## Additional context

I wrote a simple DockerFile which uses your current image as base. https://github.com/NanoCode012/yolov5-jupyterlab/blob/master/Dockerfile

![image](https://user-images.githubusercontent.com/9899957/92307103-26ae4000-efbe-11ea-8ac0-6e55d3aabfbb.png)

**Comment by glenn-jocher** [comment]
@NanoCode012 that looks really interesting. I'm not familiar with jupyterlab. I just looked into it now and saw binder as well. I was able to create a binder environment with just a few clicks (I see they build off of the repo Dockerfile), and they even provide you this nice button. 
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ultralytics/yolov5/master)

https://mybinder.org/v2/gh/ultralytics/yolov5/master
or
https://mybinder.org/v2/gh/ultralytics/yolov5/master?filepath=tutorial.ipynb

With respect to the actual Dockerfile, it's a bit behind on updates. We are on 20.03 rather than 20.07 (the latest), because I observed slightly slower (maybe 10%) training on 20.07. I'm waiting for 20.08 at the end of this month to test out.

The good news is that Docker autobuild keeps yolov5:latest always up to date, so this image is always in sync with origin/master.

Could you explain exactly the steps to launch jupyterlab with your updated Dockerfile?

**Comment by NanoCode012** [comment]
Wow! I didn't know about binder. Will check it out.

For my DockerFile, it pulls off Your image, so anytime you change this repo, it will change as well. <- this is the best part

To run mine, they simple have to `docker pull nanobits/yolov5` then `docker run -it -p <port_machine>:8888 nanobits/yolov5` (plus mount, ipc etc). The server will start automatically because of code below in DockerFile. They just have to access via `hostname:port`

```Dockerfile
ENTRYPOINT ["jupyter","lab","--no-browser","--ip=0.0.0.0","--port=8888"]
```

If you want to implement the idea, there are three options I see right now. 

1. Copy mine entirely without the `FROM`. Server will start automatically.
2. Copy mine entirely without the `FROM` and `ENTRYPOINT`, so that users can choose to use CLI and activate jupyter lab via the command above.
3. Add an extra line in your Docker tutorial to pull using my repo for those interested using JupyterLab. Everything is already setup. Only need to pass an extra `-p` argument to your current commands. 

One extra note is that `tensorboard==2.2` because a higher version would cause errors with jupyterlab_tensorbord.

Edit: For GCP, make sure to open firewall to that port.

Edit2: Binder would not fully load for me. It's stuck on the "Starting repository" message..

**Comment by glenn-jocher** [comment]
Submitted bug report to Binder, as I always get an error https://github.com/jupyter/nbviewer/issues/951
