### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by RainyMoring** [ultralytics/yolov5#8240]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, I have some questions about memory leak during training.
I observed that the memory is continued to grow during iter in training, and set workers=0, the memory leak stop
and when I try to train very large datasets, which make the yellow part cached out of memory(with htop), the speed slower.
- [1].Why memory leak? what's locate the new memory? What can I do to stop it?
- [2].What is the relationship between speed and memory? why speed is restricted to memory?
- [3].Why memory leak stop when workers=0?
- [4].How can I training large datasets with original speed?
Thanks for your kindness.
God bless you

**Comment by glenn-jocher** [comment]
@RainyMoring 👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by RainyMoring** [comment]
> @RainyMoring wave Hello! Thanks for asking about **training speed issues**. YOLOv5 rocket can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:
> 
> * Increase `--batch-size`
> * Reduce `--img-size`
> * Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
> * Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
> * Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
> * Train on faster GPUs, i.e.: P100 -> V100 -> A100
> * Train on free GPU backends with up to 16GB of CUDA memory: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> Good luck four_leaf_clover and let us know if you have any other questions!



> @RainyMoring wave Hello! Thanks for asking about **training speed issues**. YOLOv5 rocket can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:
> 
> * Increase `--batch-size`
> * Reduce `--img-size`
> * Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
> * Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
> * Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
> * Train on faster GPUs, i.e.: P100 -> V100 -> A100
> * Train on free GPU backends with up to 16GB of CUDA memory: [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/models/ultralytics/yolov5)
> 
> Good luck four_leaf_clover and let us know if you have any other questions!

thanks for your answer. But my speed is normal at first, and get slower in 5 epoch, when the cached fill memory, and become slower and slower in after epoches. I will draw some pictures to claim this.

**Comment by glenn-jocher** [comment]
@RainyMoring 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
