### ISSUE TITLE
How to use DDP?

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [ultralytics/yolov5#8283]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/75170833/174834132-db1a6df2-9623-4edc-9dfb-b3d5b9a0ec30.png)
I do not know what should I do. When I run train.py without DDP, it can run, but slowly. So I want to use DDP to speed up. Always display this bug. Could you tell me how to solve this problem? Please.
![image](https://user-images.githubusercontent.com/75170833/174835110-c0aef1c7-1c3e-4a6e-b516-abace29d6ba1.png)
![image](https://user-images.githubusercontent.com/75170833/174835182-a6f09374-4cb2-4bcf-b474-bdc86830c6df.png)

**Comment by glenn-jocher** [comment]
@AyushExel it looks like we should disable LOGGER for all RANKs except for RANK in (0, -1) to avoid multiple printouts like the AMP check above:
https://github.com/ultralytics/yolov5/blob/1156a323f8fc221d5c1a36c700e72e129419d187/utils/general.py#L534

I think I can do this here:
https://github.com/ultralytics/yolov5/blob/1156a323f8fc221d5c1a36c700e72e129419d187/utils/general.py#L82-L99

EDIT: Oh, haha I've already done this on L88, this line is just printing out because it's set to warning for non RANK (0, -1) messages. Maybe I should just disable it entirely or set it to logging.ERROR for non RANK(0, -1)?
EDIT2: console output fix implemented in https://github.com/ultralytics/yolov5/pull/8284

**Comment by glenn-jocher** [comment]
@lizhiying-2019 your error doesn't look familiar. For full DDP examples please see our Multi-GPU tutorial below which recommends using our Docker image for all DDP trainings.

If you have a reproducible issue inside our DDP container please let us know with exact commands to reproduce. If we can not reproduce there is no action for us to take.

## YOLOv5 Tutorials

* [Train Custom Data](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data)&nbsp; 🚀 RECOMMENDED
* [Tips for Best Training Results](https://github.com/ultralytics/yolov5/wiki/Tips-for-Best-Training-Results)&nbsp; ☘️  RECOMMENDED
* [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)&nbsp; 🌟 NEW
* [Roboflow for Datasets, Labeling, and Active Learning](https://github.com/ultralytics/yolov5/issues/4975)&nbsp; 🌟 NEW
* [Multi-GPU Training](https://github.com/ultralytics/yolov5/issues/475)
* [PyTorch Hub](https://github.com/ultralytics/yolov5/issues/36)&nbsp; ⭐ NEW
* [TFLite, ONNX, CoreML, TensorRT Export](https://github.com/ultralytics/yolov5/issues/251) 🚀
* [Test-Time Augmentation (TTA)](https://github.com/ultralytics/yolov5/issues/303)
* [Model Ensembling](https://github.com/ultralytics/yolov5/issues/318)
* [Model Pruning/Sparsity](https://github.com/ultralytics/yolov5/issues/304)
* [Hyperparameter Evolution](https://github.com/ultralytics/yolov5/issues/607)
* [Transfer Learning with Frozen Layers](https://github.com/ultralytics/yolov5/issues/1314)&nbsp; ⭐ NEW
* [Architecture Summary](https://github.com/ultralytics/yolov5/issues/6998)&nbsp; ⭐ NEW

Good luck 🍀 and let us know if you have any other questions!
