### ISSUE TITLE
Detection performance: one model for each class vs. one model for severall classes

### ISSUE THREAD

**Issue by gondimjoaom** [ultralytics/yolov5#8289]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi! I'm gathering a dataset that has many different classes and scenarios on it and I'm thinking wether it is better to built one single model with lots of classes or severall models for each class.

**Comment by MasIgor** [comment]
hello! how would "several models for each class work"? you would have to load the model for the correct class to be able to detect it... also what is your definition of "many different classes"? if you have enough data and properly labeled data then you should be able to train a single model..

**Comment by gondimjoaom** [comment]
I'm trying to create a dataset where different images and situations occur deppending on the object being detected. For example: detect fire spots in the woods and detect a cellphone in a living room. My question is: what are the performance impacts if I train a single model with the whole dataset or train two different models for each object being detected?

Training one single model might lead to a faster detection since it is just one model being loaded and used, but is it better when comparing detection metrics? And why? I would be happy if someone could help with directions on where to read more about such subject two :))

**Comment by MasIgor** [comment]
how many classes do you have? I am successfully using a single model with 311 classes..  what is not entireliy clear to me is how you intend do use multiple models. would you load them all in parallel? I never tested it, but i am positive that you would be slower with multiple models. the model itself might get more precise, but that also depends on the data itself.

For example: if you are trying to differentiate a red basketball from a red football, then having one model with both classes will most likely give you better results as the same model knows both situations. if you have two models then both could have false positives as they bot learn to find red spheres, regardless of the minor differences.

but i am fairly new on this topic, so please take this with a grain of salt.

**Comment by gondimjoaom** [comment]
not many, actually. 8 classes. My doubt is due to the fact that a only have 8 classes because I'm joining 8 very different datasets, but I plan to use the detections all together, so I keep wondering that because images for different classes differ so much if I should be training one model for each of these classes...

I really appreciate your help on the discussion :))

**Comment by MasIgor** [comment]
personally I would put them all in a single dataset. especially if they are very different since they will not be interfering with each other.  for example, the balls again, they have minute differences, and it would take longer to reach a higher precision due to the smaller differences. but if you compare a ball with a lawnmower i doubt it will swap them.. :D more important is that you have a good number of pictures for all the situations to train a solid model. thats way more important than having "too many classes".. they reccomend 1500 images per class, i have had success with 500... so in your example it would be around 4000 images. I like to split them in 75% training, 25% validation, and 0 test. I test the network in a real scenario. that way I have more images for training.

**Comment by glenn-jocher** [comment]
@MasIgor hi there! Training one single model with all 8 classes should work well as long as you have enough diverse and properly labeled data. Since the classes are very different, they are unlikely to interfere with each other. Having a good number of images for all classes is crucial for training a robust model, so make sure to focus on that. When structuring your dataset, I'd recommend a split of 75% for training and 25% for validation, reserving the testing for a real-world scenario. You can find more detailed information on dataset structuring and training in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Good luck with your training!

**Comment by scchess** [comment]
> ltiple models. would you load them all in parallel? I never tested it, but i am positive that you would be slower with multiple models. the model itself might get more precise, but that also depends on the data itself.

Correct

**Comment by pderrenger** [comment]
Agree—use one YOLOv5 model for all 8 classes; multiple models multiply inference cost and rarely improve overall mAP. To verify, train once and inspect per-class AP and the confusion matrix: python train.py --data data.yaml --weights yolov5s.pt; then python val.py --weights runs/train/exp/weights/best.pt --data data.yaml. If any class lags, rebalance samples, add background negatives, and strengthen augmentation—see the Albumentations integration docs for options, and this guide on building high‑quality vision datasets for practical tips. See the Albumentations integration docs for details and examples, and read CV Datasets: High Quality Data Matters for data best practices.
