### ISSUE TITLE
RuntimeError: sqrt_vml_cpu not implemented for 'Half'

### ISSUE THREAD

**Issue by lucasjinreal** [ultralytics/yolov5#830]
Got this error when try to onnx export:

```
yolov5/utils/torch_utils.py", line 119, in fuse_conv_and_bn
    w_bn = torch.diag(bn.weight.div(torch.sqrt(bn.eps + bn.running_var)))
RuntimeError: sqrt_vml_cpu not implemented for 'Half'
```

any ideas? I am using pytorch 1.6 on GTX1080ti which might not have fp16 support.

**Comment by glenn-jocher** [comment]
@jinfagang .half() operations are not supported on CPU for pytorch.

Solution would be not to run these ops for .half() models, or to convert model to .float() first.

**Comment by glenn-jocher** [comment]
BTW, this lack of half precision support for CPU ops is a general PyTorch property/issue, not specific to YOLOv5. It would be nice to see these, as it would simplify the code a bit, but as I understand it it is complicated by the various CPU optimized libraries (i.e. Intel vs AMD).

**Comment by Steedalion** [comment]
Does anyone find this error a little cryptic? It does not mention float32 or float16 and I discovered the solution here.

**Comment by captainhalf** [comment]
Hello I am getting ‘log_vml_cpu’ not implemented for ‘half ‘…can you help me what is it saying? *i have installed sd and control net and its other related files, running it on Mac OS 16gb ram . Please help if you can guess what’s stopping it. Thanks

**Comment by glenn-jocher** [comment]
@captainhalf hello! This error typically means that you are trying to perform some operation on half-precision tensor data (float16), but that operation is not supported on the CPU for PyTorch. Did you train your model using half precision? 

A fix for this issue is to either convert your model to use float32 precision or to make sure you are running on a machine with a CPU that supports half precision operations. Note that CPU half precision support can be limited based on the processor used. Additionally, you may want to check the PyTorch version you are using, as newer versions may have better support for half-precision operations. 

Hope this helps!
