### ISSUE TITLE
Inference memory leak

### ISSUE THREAD

**Issue by MikoyChinese** [ultralytics/yolov5#8303]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I run yolov5 to detect images by for loop on my cpu. And for a while, I found my memory will increase by each loop. So I try to find out it. 

If I comment this line, I can run fine:

https://github.com/ultralytics/yolov5/blob/a2a1ed201d150343a4f9912d644be2b210206984/utils/general.py#L828

Any othrer person has found this problem like me? I don't know how to solve this, please help.

### Environment

OS: Ubuntu 20.04
torch: 1.11.0+cpu
Yolo: lastest

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MikoyChinese 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by MikoyChinese** [comment]
Hi, I found that it is my problem. If I use the model state_dict by the following code, I will get the Inference memory leak, But if I change the load model mode to the original code `torch.load('last_ckpt.pt', map_location=device)['model'].float().fuse().eval()`, it is ok.:

```
ckpt = torch.load('last_ckpt.pt', map_location=device)
state_dict = ckpt['model'].float().state_dict()
model = Model(cfg='./models/yolov5s6.yaml', ch=3, nc=1).to(device)
model.load_state_dict(state_dict, strict=False)
model.fuse().eval()
```

It's a very odd problem.

**Comment by glenn-jocher** [comment]
@MikoyChinese got it. Thanks for the confirmation. Removing TODO.

**Comment by michal-kierzynka** [comment]
Hi, I have similar issue. Huge memory leaks, unless I comment out the following line:
```x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf```
Looks like a bug to me. I first create a model and then load the weights by calling `model.load_state_dict`.

**Comment by mmheydari97** [comment]
However expensive, that line is important to report model confidence in nms. You can try `del x` after the code is done with it. Might slightly help

**Comment by glenn-jocher** [comment]
@mmheydari97 thanks for bringing this issue to our attention. Although commenting out that line might prevent the memory leak, it is indeed an important line for calculating the model confidence during non-maximum suppression (NMS).

One potential solution to mitigate the memory leak is to delete the variable `x` after it's no longer needed. You can try adding `del x` after the code that uses `x`. This can potentially help in releasing the memory occupied by `x` and alleviate the memory leak to some extent.

Note that YOLOv5 is a community-driven project, and improvements and bug fixes are made by the collective efforts of the contributors. We appreciate your feedback and encourage you to open a new issue if you have any further questions or encounter any other issues.

Thank you for your support and contribution to the YOLOv5 community!
