### ISSUE TITLE
Engine model different results between toch.hub.load method and console 

### ISSUE THREAD

**Issue by SahinTiryaki** [ultralytics/yolov5#8312]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I converted the yolov5m.pt model to yolov5m.engine and executed them.   But I got different results. For example  when I execute  the engine model with torch.hub.load  method , the engine model did not detect objects on the image.  When I execute the engine model on console, the engine model detected objects on the image.  Can you help me please ?

**Comment by glenn-jocher** [comment]
@SahinTiryaki 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by edaabahar** [comment]
Hi, i have the same problem with .pt files. 
when i load the model with torch.hub as follow and ask the photo below i get nothing (no detections):
`model = torch.hub.load('path/to/yolov5', 'custom', path='path/to/model6_pattern.pt', source='local')`
![xIdRy91cmEm7aKZrZoQFQQ](https://user-images.githubusercontent.com/37348825/176857500-b910e487-c89d-43ab-93de-26e8206c9e90.png)
but when i run the detect.py file in terminal as follow:
`python detect.py --weights 'path/to/model6_pattern.py' --source 'path/to/image' --conf 0.3`
i get this:
![xIdRy91cmEm7aKZrZoQFQQ](https://user-images.githubusercontent.com/37348825/176857456-27166957-03c7-442b-8b8f-6f2817bc413a.png)

**Comment by glenn-jocher** [comment]
@edaabahar PyTorch Hub and detect.py inference on default images with default model produces identical results:

<img width="835" alt="Screen Shot 2022-07-01 at 1 09 52 PM" src="https://user-images.githubusercontent.com/26833433/176883633-245f838d-9257-46e1-9448-28fa8a605554.png">

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by edaabahar** [comment]
@glenn-jocher  Hi, sorry for misunderstanding. The model I use is a custom model not a default one.

**Comment by glenn-jocher** [comment]
@edaabahar No worries! 🙏 To troubleshoot custom model inference discrepancies, it's essential to investigate potential variations between the `torch.hub.load` method and `detect.py` script with custom models.

If you can provide a minimum reproducible example (MRE) including the custom model files, inference images, and the specific command used for both `torch.hub.load` and `detect.py`, it will greatly help in identifying any potential issues.

For assistance with custom model inference discrepancies, please create a new issue following the 🐛 **Bug Report** template and provide the MRE. We'll work to resolve the issue promptly. Thank you! 😊
