### ISSUE TITLE
Dataset without annotation possible to run in YOLOV5?

### ISSUE THREAD

**Issue by PraveenMNaik** [ultralytics/yolov5#8323]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear Sir,
Is it possible to run YOLOV5 model without annotating images. I mean, I have collected images of  fruit, each image has one fruit in it, and i have removed background of it, since the whole of the image is fruit( and no other element exits in the image), i feel why don't the model consider the whole image for training rather than  wasting my time annotating. Pls suggest, if its possible. if so how to proceed with this type of data.
 I have a use case of grading fruits based on quality, and further more i have put each graded fruit in different folder as Grade1, Grdae2...etc(as mentioned above each of the fruit is removed with background)

**Comment by AyushExel** [comment]
@PraveenMNaik If you want to label an entire image then classification is the way to go. Object detection works for detecting and localizing the image. It gives you the position of a particular object or objects in a given frame. This applies even if there's only one object in the frame. So, you cannot train a detector without the proper labels in the supported format.

**Comment by PraveenMNaik** [comment]
How about testing the images with natural condition... i train considering the image of my type(as mentioned above post), then while testing i use any randomly clicked images... which can do localization right?

**Comment by AyushExel** [comment]
To calculate any metrics for training or validation, you'll need labels/annotations. Here I'm assuming that by testing you mean validation

**Comment by glenn-jocher** [comment]
@PraveenMNaik if your entire image contains an object you're probably doing a classification task rather than an object detection task. See classifier branch for usage examples, i.e. MNIST, CIFAR etc.
https://github.com/ultralytics/yolov5/blob/f92e631a3efc7cf5200ed7222cada02328d20bc1/classifier.py#L2-L15

**Comment by dazzafact** [comment]
I have the same Questions. I have images with already white Background (photoshop Cropped)
Is there a way to skip labeling?

**Comment by glenn-jocher** [comment]
@biblekiss 
> @PraveenMNaik if your entire image contains an object you're probably doing a classification task rather than an object detection task. See classifier branch for usage examples, i.e. MNIST, CIFAR etc.
> 
> https://github.com/ultralytics/yolov5/blob/f92e631a3efc7cf5200ed7222cada02328d20bc1/classifier.py#L2-L15

**Comment by codexkunal** [comment]
I have also same kind of question , but In a different way I have aerial images of size 512 * 512 containing residency area then what should I do , my whole image is my subject. here is the example

![image](https://github.com/user-attachments/assets/91ab04f6-72f2-46db-9698-8399578e0017)

**Comment by glenn-jocher** [comment]
Hi @codexkunal,

Thank you for your question! Given that your entire image is your subject, it sounds like you might be more interested in image classification rather than object detection. In image classification, the model learns to classify the entire image into one of several categories, which seems to fit your use case where each image represents a specific type of area.

Here's how you can proceed:

1. **Dataset Preparation**: Organize your images into directories where each directory name represents a class label. For example:
    ```
    dataset/
    ├── class1/
    │   ├── image1.jpg
    │   ├── image2.jpg
    ├── class2/
    │   ├── image1.jpg
    │   ├── image2.jpg
    ```

2. **Training a Classification Model**: You can use the YOLOv5 classifier branch to train a classification model. Here's a basic example of how to set up and train a classifier:

    ```bash
    git clone https://github.com/ultralytics/yolov5
    cd yolov5
    pip install -r requirements.txt
    python train.py --data path/to/your/dataset --img 512 --batch 16 --epochs 50 --weights yolov5s.pt
    ```

3. **Model Evaluation**: After training, you can evaluate your model on a validation set to see how well it performs.

4. **Inference**: Use the trained model to classify new images. Here's an example of how to run inference on a single image:

    ```python
    from yolov5 import YOLOv5

    model = YOLOv5("path/to/your/best.pt")
    results = model.predict("path/to/your/image.jpg")
    print(results)
    ```

For more detailed instructions, you can refer to the [Ultralytics YOLOv5 documentation](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/).

If you have any further questions or run into any issues, feel free to ask. The YOLO community and the Ultralytics team are here to help!

Best of luck with your project! 🚀
