### ISSUE TITLE
Beyond Yolov5 ?? Yolov6 appears 

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/yolov5#8347]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Beyond Yolov5 ?? Yolov6 appears 
I doubt that

`https://github.com/meituan/YOLOv6`

![picture](https://user-images.githubusercontent.com/6490927/175858810-72c1d6b0-960a-40f5-a208-de121694b8d4.png)

**Comment by AyushExel** [comment]
@monkeycc 
I would say that when choosing the best model for your needs, you should also consider the speed Vs accuracy tradeoff. 
Let's take a look at the above comparison, in terms of params.
* YOLOv5n has 1.9M params Vs YOLOv6n which has 4.3M params - more than 2x
* YOLOv5s has 7.2M params vs YOLOv6s which has 17.2M params - more than 10x
* You can look at the speed differences caused by this in the official charts

A better comparison would be to benchmark this with YOLOv5 v6 models. Here's a simple example
* YOLOv5n6 has less params(3.2M vs 4.3M) than YOLOv6n but more accuracy.
* Similarly you can compare other YOLOv5 v6 models as the parameter difference is more comparable here.
Keep in mind that the YOLOv5 v6 models are trained at a higher resolution so that is also a contributing factor.
Here's the charts for easier comparison. Take a loot at params(speed) Vs accuracy

**YOLOv5 V6**

|Model |size<br><sup>(pixels) |mAP<sup>val<br>0.5:0.95 |mAP<sup>val<br>0.5 |Speed<br><sup>CPU b1<br>(ms) |Speed<br><sup>V100 b1<br>(ms) |Speed<br><sup>V100 b32<br>(ms) |params<br><sup>(M) |FLOPs<br><sup>@640 (B)
|---                    |---  |---    |---    |---    |---    |---    |---    |---
|YOLOv5n6     |1280 |36.0   |54.4   |153    |8.1    |2.1    |3.2    |4.6
|YOLOv5s6    |1280 |44.8   |63.7   |385    |8.2    |3.6    |12.6   |16.8
|YOLOv5m6    |1280 |51.3   |69.3   |887    |11.1   |6.8    |35.7   |50.0
|YOLOv5l6     |1280 |53.7   |71.3   |1784   |15.8   |10.5   |76.8   |111.4
|YOLOv5x6<br>+ [TTA][TTA]|1280<br>1536 |55.0<br>**55.8** |72.7<br>**72.7** |3136<br>- |26.2<br>- |19.4<br>- |140.7<br>- |209.8<br>-

**YOLOv6**
<img width="872" alt="Screenshot 2022-06-27 at 10 31 29 AM" src="https://user-images.githubusercontent.com/15766192/175863509-58e814e9-12f2-498b-b337-0bae0fc6b2e8.png">

 **YOLOv5**
<img width="753" alt="Screenshot 2022-06-27 at 10 37 30 AM" src="https://user-images.githubusercontent.com/15766192/175864198-8ae0a4c0-95a3-4dbe-bea7-64453c4a2e86.png">

**Comment by zhiqwang** [comment]
Hi @AyushExel , Thanks for your information here!

There are scenarios where we are not concerned about the number of parameters, as the number of parameters does not have a linear correlation with the actual inference speed.

And that's the power and new insights that `repvgg` has given us.

### More context about repvgg in YOLOv5
- https://github.com/ultralytics/yolov5/issues/1922#issuecomment-760643000
- https://github.com/ultralytics/yolov5/issues/4501#issuecomment-915357137

**Comment by AyushExel** [comment]
@zhiqwang yes definitely agreed. I was just pointing out the data from the charts. I think flops are still the standard way to compare models in the literature. Also when training, the parameter/speed difference is more noticeable.
 But at the end of the day, there are all kinds of tradeoffs in the real world and the end user should always compare multiple models and choose according to the task at hand. 
repvgg looks cool. Will take a look. Thanks for sharing
