### ISSUE TITLE
How to detect in a specific radius? 

### ISSUE THREAD

**Issue by HeitorDC** [ultralytics/yolov5#8379]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, guys!

I'm using YOLOv5 on my master project and I made to detect, identify and locate the object in the real world by distance and angles. Now, I want to identify objects only in a specific radius, like if there a person in the distance < 2 meters, it'll detect but if not, it won't. How can I do that? Can anyone help me with this?

Thanks for the attention and best regards!

**Comment by sarpx** [comment]
Stick a standard size image on each picture and make the maps accordingly. For example money..

**Comment by HeitorDC** [comment]
> Stick a standard size image on each picture and make the maps accordingly. For example money..

I don't get it.

**Comment by sarpx** [comment]
http://emaraic.com/blog/distance-measurement

**Comment by sarpx** [comment]
https://github.com/paul-pias/Object-Detection-and-Distance-Measurement

**Comment by HeitorDC** [comment]
> http://emaraic.com/blog/distance-measurement
Hi, thanks for your reply! I've already have the distance measured and the object's angles in the real world using an Intel RealSense d435i. What I need is where, in the "detect.py" algorithm, the object detection happens to realize how to decrease the range of the detection to a specific range, like < 3m. Like, if there is a person at 4m from the camera, it won't detect but if the person come to 2m, it'll detect. 
I've already realize how to make the drawing of the bounding boxes in this condition, however the object detection keeps happening regardless of the specific distance condition, like the one I want to run.

**Comment by sarpx** [comment]
If you want to capture objects at a distance, you should do it with visuals at that distance in training. So pay attention to the resolution of the pictures you put in the training. You have to decide which one is best for you. The objects you want to recognize are 1 meter ahead in the picture, but if you are looking 4 meters behind while looking, you may probably get worse results than you expect.

**Comment by robotwhispering** [comment]
I'm actually trying to do something like this right now, but without an additional sensor. I started looking at some of the one-off models like yolov5s-p34 and p34567 and p2, etc. I noticed that the most common goal for object detection seems to be to detect smaller and smaller objects in view (ie: detect further distance). However, I have an application currently to detect people only approximately 0.5-20m away from the camera. But people further than that, or off to the sides, I don't want detected. 

So I started with a pixel-wise approach (I use the area of the bounding box to help me determine if they are close or far, and then I also use very sloppy 2D to 3D estimation by pixels and known measurements of features that are constant to the camera view. ). 

I've recently been working on modifying the P output layers of models. For instance, adding in a P5 output, but removing P3, so that it's harder for it to detect further away.

I'm waiting on 2 models to finish training right now to see what I learn. But one thing that I think is going to cause me difficulty up front, is the labeled ground truths. When i labeled my dataset, I labeled every person that the eye could see. So now, when I'm trying to use anchors that are optimal for midrange and closer, the autoanchor is showing me that those are poor anchors for the dataset. So I'm going to take some time and chery pick through my 20,000 and try to label only within range. 
However, I would anticipate this to cause confusion for the model and require more involved fine tuning  because there will clearly be objects that look like people, that aren't being labeled.
