### ISSUE TITLE
PyTorch Hub inference,     raise URLError('unknown url type: %s' % type) urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by shishanyue** [ultralytics/yolov5#8428]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

### Environment

windows,pycharm,cpu

### Minimal Reproducible Example

import torch

# 模型
#model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom
model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.onnx')
# 图像
img = "1.jpg"  # or file, Path, PIL, OpenCV, numpy, list

# 推理
results = model(img)

# 结果
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lizexun 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Everything works correctly when I run your example:
<img width="1251" alt="Screen Shot 2022-07-01 at 1 29 44 PM" src="https://user-images.githubusercontent.com/26833433/176886236-fc715356-d64d-496a-ac39-6d88ede23d23.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by shishanyue** [comment]
close #8428

**Comment by glenn-jocher** [comment]
Thanks for reaching out, @shishanyue! If you encounter any more issues or have further questions, feel free to open a new issue. We're here to help! Thanks for your contribution 🎉.
