### ISSUE TITLE
Test image has no labels

### ISSUE THREAD

**Issue by DoSquared** [ultralytics/yolov5#8429]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi everybody, 

I would appreciate some help with my training and testing on YOLO! 

I am running YOLO v5 on my custom dataset created on roboflow for cell classification and count. 

This is the training output: 
![image](https://user-images.githubusercontent.com/4492013/176870782-b4084ebb-a970-48d5-8343-d9bb66863f86.png)

![image](https://user-images.githubusercontent.com/4492013/176870834-962b2c75-6033-4e57-ab0b-20d67816148e.png)

I run this part of the code in order to see the labels on test image after training has finished: 
![image](https://user-images.githubusercontent.com/4492013/176870665-357cd7f5-a52c-4b2a-ac01-ee31e4e6252f.png)

Detect directory contains an image with no labels, I am not sure what is the problem! 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DaliaMahdy labels are provided by you. YOLO creates **predictions** on an image.

**Comment by yeldarby** [comment]
@DaliaMahdy - we're happy to answer Roboflow & dataset specific questions on the Roboflow discussion forums: https://discuss.roboflow.com

**Comment by DoSquared** [comment]
> 

Thank you for the reply! Any help on how to run inference successfully on test images?

**Comment by glenn-jocher** [comment]
@DaliaMahdy you can get metrics on a labelled test set like this:
```
python val.py --task test
```

**Comment by DoSquared** [comment]
> @DaliaMahdy you can get metrics on a labelled test set like this:
> 
> ```
> python val.py --task test
> ```

"test" is the directory? Do you please have the full code or notebook?

**Comment by glenn-jocher** [comment]
@DaliaMahdy there's no other commands, just what I pasted above. Test is defined in your data.yaml:
https://github.com/ultralytics/yolov5/blob/f8722b4429e80f96be04b36e4efd84ce6583bfa1/data/VOC.yaml#L10-L21

**Comment by DoSquared** [comment]
Thank you for the reply! now the same code is not working, I have been struggling for days with the conflicts of libraries! 
![image](https://user-images.githubusercontent.com/4492013/179220009-00acdae3-f6b2-42cf-861e-62893ddaa5a2.png)


![image](https://user-images.githubusercontent.com/4492013/179220161-4bb33df8-f86a-417d-aa37-1ba43f9581e7.png)


Any help please??

**Comment by glenn-jocher** [comment]
@DaliaMahdy 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by DoSquared** [comment]
Thank you very much! now the training finishes but the test images are completely blank white images! I don't know what is the problem!

**Comment by glenn-jocher** [comment]
@DoSquared We're here to help! If the test images are showing up as blank, there may be an issue with the data or the test script. I recommend checking your data loading and preprocessing to ensure the test images are being read correctly. Additionally, you may want to verify that the test script is functioning as expected.

If you continue to encounter difficulty, providing a minimum reproducible example can help us identify the root cause more effectively. Thank you for your patience and collaboration!
