### ISSUE TITLE
use Quick Start Examples ，errors：urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by shishanyue** [ultralytics/yolov5#8436]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

When I use Quick Start Examples，Errors：
![image](https://user-images.githubusercontent.com/62888460/176913619-7b8cef44-871c-4dac-bdaa-4bfc81ad70c1.png)
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\21553/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "E:/Users/21553/Anaconda3/envs/yolov5/yolov5/AutoPorject/onnxTest.py", line 4, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\site-packages\torch\hub.py", line 337, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\site-packages\torch\hub.py", line 144, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\site-packages\torch\hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "E:\Users\21553\Anaconda3\envs\yolov5\lib\urllib\request.py", line 1420, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

### Environment

YOLO:YOLOv5  v6.1 troch:cpu
OS:Windows
Python:3.7
use pycharm
Normal environment
detect , run,train all can use

### Minimal Reproducible Example

import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # or yolov5n - yolov5x6, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

### Additional

I don't know why，it just errors

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lizexun 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We are not able to reproduce any YOLOv5 issues with PyTorch Hub inference. 

<img width="1076" alt="Screen Shot 2022-07-04 at 3 57 18 PM" src="https://user-images.githubusercontent.com/26833433/177169622-d82f54e6-df10-4cbb-8e93-d76e3afb9ae9.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
