### ISSUE TITLE
How do I save the pruned model

### ISSUE THREAD

**Issue by liu-runsen** [ultralytics/yolov5#8450]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How do I save the pruned model by adding the following code to val.py, but I won't save the pruned model

val.py
```
from utils.torch_utils import  prune
prune(model, 0.3)
```

**Comment by AyushExel** [comment]
I think you should be able to use the same checkpointing code as used in train.py https://github.com/ultralytics/yolov5/blob/master/train.py#L412

**Comment by liu-runsen** [comment]
> 我认为您应该能够使用与 train.py [https://github.com/ultralytics/yolov5/blob/master/train.py#L412中使用的相同的检查点代码](https://github.com/ultralytics/yolov5/blob/master/train.py#L412)
How do I save the pruning model

**Comment by glenn-jocher** [comment]
@MaoliRUNsen yes just use the same saving code from train.py:
https://github.com/ultralytics/yolov5/blob/c7689198bc66023378f71aa80c0829a763a928bd/train.py#L411-L422

@AyushExel it's helpful to paste the code block line number range (i.e. .../train.py#L411-L422) so users can see it inlined in the comment like my example above.

**Comment by Faculty-lclaxton** [comment]
@glenn-jocher regarding your comment "just use the same saving code from train.py:". The neither ema or optimizer is present within val.py and hence the above code will fail. I tried the below, which runs, but cannot be reloaded for training or validating due to the lacking ema key.

`torch.save({'model': model.state_dict()}, project+'/'+name+'/best.pt')`
