### ISSUE TITLE
How to connect Live cctv camera with yolov5 

### ISSUE THREAD

**Issue by sumis2140** [ultralytics/yolov5#8457]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hai, 

If the camera IP is `192.168.0.250/`

and password: `admin123`

How to connect CCTV camera with yolov5 using IP address

I just tried like this but it didn't work

`python3 detect.py --source rtsp://admin:admin123@192.168.0.250 --weights yolov5s.pt --conf 0.25` 

`python3 detect.py --source https://192.168.0.250 --weights yolov5s.pt --conf 0.25`

But these methods not working. how can I connect a CCTV camera for live object detection

Thanks

**Comment by AyushExel** [comment]
@sumis2140 what is the error? I think the syntax you're using has a typo. You'll need to enclose the source address in quotes, like this:
```
python3 detect.py --source "rtsp://admin:admin123@192.168.0.250" --weights yolov5s.pt --conf 0.25

```

**Comment by sumis2140** [comment]
> 

@AyushExel  Thanks for your reply.

 `ssertionError: 1/1: rtsp://admin:admin123192.168.0.250... Failed to open rtsp://admin:south1192.168.0.250`

I got this error when running like this 

`python3 detect.py --source "rtsp://admin:admin123$123$@192.168.0.250" --weights yolov5s.pt --conf 0.25`

The actual problem is I have a `$` symbol in my password so it didn't take after the $ symbol.

**Comment by glenn-jocher** [comment]
@sumis2140 this is a network/address/password issue on the user side.

**Comment by iamharry-dev** [comment]
> 

If `192.168.0.250/` this is my Camera IP address means how can i use those IP with `HTTP` or `RTSP`

**Comment by glenn-jocher** [comment]
i.e. `rtsp://192.168.0.250/`

**Comment by barney2074** [comment]
I suggest testing the address from VLC (open network stream)
Some cameras have a different URL such as rtsp ://192.168.0.1/stream

**Comment by iamharry-dev** [comment]
> I suggest testing the address from VLC (open network stream) Some cameras have a different URL such as rtsp://192.168.0.1/stream

@glenn-jocher  @barney2074  Thanks for your suggestion it's working fine on VLC but I didn't work on the code 

 `python detect.py --weights yolov5s.pt --source rtsp://admin:admin1$admin$@192.168.0.2`

Here is a command I just used but I got an assertion error. can you please help me to resolve this issue?

Thanks

**Comment by glenn-jocher** [comment]
@iamharry-dev use quotes around addresses as in README example:
<img width="944" alt="Screen Shot 2022-07-05 at 11 50 52 AM" src="https://user-images.githubusercontent.com/26833433/177301552-b1e94c46-7291-44f5-84fa-d899f80288d9.png">

**Comment by iamharry-dev** [comment]
@glenn-jocher  is there any way to connect the dynamic IP camera with yolov5 ??  or give any suggestions to connect dynamic IP camera

i got this error :

```
WARNING: Video stream unresponsive, please check your IP camera connection.                   
WARNING: Video stream unresponsive, please check your IP camera connection.
WARNING: Video stream unresponsive, please check your IP camera connection.
WARNING: Video stream unresponsive, please check your IP camera connection.

```

**Comment by barney2074** [comment]
it depends how your network is set up for name resolution- but you could probably use a name rather than the IP address.
However, it is probably better to use either a static IP address for the camera, or a DHCP reservation- i.e the IP address does not change

**Comment by Chuttyboy** [comment]
> 

@barney2074 @glenn-jocher 

Thanks for your suggestion 

Here is my dashboard can you please tell me how to connect the IP camera with a name instead of using the IP address 

![Capture](https://user-images.githubusercontent.com/79959547/179696519-910fa100-b776-4621-8ae6-56afaadf5110.PNG)

```
WARNING: Video stream is unresponsive, please check your IP camera connection.                   
WARNING: Video stream is unresponsive, please check your IP camera connection.
WARNING: Video stream is unresponsive, please check your IP camera connection.
WARNING: Video stream is unresponsive, please check your IP camera connection.
```

For resolve this error how to connect IP camera with name 


Thanks

**Comment by Chuttyboy** [comment]
@glenn-jocher 

Hai @glenn-jocher  

I wanna add one extra feature with this code can you tell me is possible to add Human action detection using YOLO v5. like find shoplifting, theft, and robbery in video surveillance

**Comment by barney2074** [comment]
> > 
> 
> @barney2074 @glenn-jocher
> 
> Thanks for your suggestion
> 
> Here is my dashboard can you please tell me how to connect the IP camera with a name instead of using the IP address
> 
> ![Capture](https://user-images.githubusercontent.com/79959547/179696519-910fa100-b776-4621-8ae6-56afaadf5110.PNG)
> 
> ```
> WARNING: Video stream is unresponsive, please check your IP camera connection.                   
> WARNING: Video stream is unresponsive, please check your IP camera connection.
> WARNING: Video stream is unresponsive, please check your IP camera connection.
> WARNING: Video stream is unresponsive, please check your IP camera connection.
> ```
> 
> For resolve this error how to connect IP camera with name
> 
> Thanks

As I say- it depends how your network is set up
Google 'DNS' or 'DDNS'

It looks like you have 'HIKVision' IP cameras- I'd start there
You can probably use either name or serial number as the 'name'





Andrew

**Comment by ghost** [comment]
> @iamharry-dev use quotes around addresses as in README example: <img alt="Screen Shot 2022-07-05 at 11 50 52 AM" width="944" src="https://user-images.githubusercontent.com/26833433/177301552-b1e94c46-7291-44f5-84fa-d899f80288d9.png">

I have installed IP Webcam in my mobile.  http://192.168.6.69:5000 is the IP address for IP Webcam.
On running similar command:
`python yolov5/detect.py --source "http://192.168.6.69:5000/" --weights best.pt --conf 0.4 --save-crop`

I am getting the following error
Connection to tcp://192.168.6.69:5000 failed: Error number -138 occurred.

**Comment by Ajitkumar563** [comment]
How we use rtsp camera in yolov7 model 
 
User="admin"
Pswrd="admin123"
C_ip="554"
C_channel="1"
C_subtype="1"
How we use in yolov7 model

**Comment by Danjen27** [comment]
> 

can you pls share where did you get this? thanks

**Comment by ShubhamKPBoss** [comment]
How we use rtsp ip camera 

User="admin"
Pswrd="admin123"
Camera SN="01nv1025mn540nb05"
Camera port="34567"

how to connect ip camera live streaming

**Comment by glenn-jocher** [comment]
To connect to an RTSP IP camera for live streaming using the YOLOv5 model, you can use the following command:

```bash
python detect.py --source rtsp://admin:admin123@<camera_ip_address>:<camera_port>/live --weights yolov5s.pt --conf 0.25
```

Make sure to replace `<camera_ip_address>` and `<camera_port>` with the actual IP address and port number of your camera. Additionally, ensure that the necessary login credentials (`User` and `Pswrd`) are correct.

Please note that the successful connection and streaming depend on the compatibility of your camera with the RTSP protocol. If you encounter any issues, please check camera documentation or consult the camera manufacturer for further assistance.

Hope this helps! Let me know if you have any other questions.

**Comment by knowngono** [comment]
I am trying to do this for Yolov7, i am trying to connect to a verdaka camera by using the Standard Resolution URL (RTSP). 

i input: 

python3 detect.py --weights best.pt --source (insert verdaka camera link) 

but i get the error: 

"Can't get attribute 'Conv' on <module 'models.common' from '/path/to/yolov7/models/common.py'> 

despite seeing the attribute Conv in the common.py code. I am not sure why this isn't working, if anyone has any ideas.

**Comment by glenn-jocher** [comment]
@knowngono this issue seems to be related to using YOLOv7 with a Verkada camera. However, please note that the YOLOv7 model is not maintained by the Ultralytics team, and the YOLOv5 repository does not provide support for YOLOv7.

It seems like the error message you mentioned is related to an attribute not being found in the `common.py` code. Without more context or code, it's difficult to pinpoint the exact cause of the issue. 

If you're using a custom version of YOLOv7 with modifications to the codebase, please ensure that the `Conv` attribute is properly defined and accessible in the `common.py` file.

For further assistance with YOLOv7, I recommend reaching out to the original developers or community who maintain the YOLOv7 implementation you are using. They will be better equipped to provide specific guidance on your issue.

Let me know if you have any other questions or if there's anything else I can assist you with.

**Comment by ShubhamKPBoss** [comment]
@glenn-jocher @AyushExel @barney2074 @Chuttyboy @Ajitkumar563  Hello, can you please help me how to connect ip camera using  camera --> serial number ,port , username, password
which type of follow protocol ............... ?

**Comment by glenn-jocher** [comment]
To connect an IP camera using the camera's serial number, port, username, and password, you typically need to use the RTSP (Real-Time Streaming Protocol) URL format that is specific to your camera's brand and model.

The general format for an RTSP URL is:

```
rtsp://username:password @ShubhamKPBoss:port/path
```

However, the exact path (`/path`) can vary greatly between different camera manufacturers and models. You will need to refer to your camera's documentation or the manufacturer's support to find the correct RTSP URL format for your specific camera.

Once you have the correct RTSP URL, you can use it with YOLOv5 like this:

```bash
python detect.py --source rtsp://username:password@camera_address:port/path --weights yolov5s.pt --conf 0.25
```

Make sure to replace `username`, `password`, `camera_address`, `port`, and `/path` with your camera's actual login credentials, IP address, port, and RTSP path.

If you're using the camera's serial number instead of its IP address, your camera system might support a service that maps serial numbers to IP addresses, often through a DDNS (Dynamic Domain Name System). You would need to set this up according to your camera system's instructions.

For further assistance, please consult your camera's user manual or contact the manufacturer's customer support.

Let me know if you need any more help! 😊
