### ISSUE TITLE
detection failed on Apple MPS

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#8459]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

`detect.py` works well when running on CPU but failed on Apple MPS on my computer. 

`python detect.py --source data/images/zidane.jpg `
![zidane](https://user-images.githubusercontent.com/87515266/177115660-ba52d0d8-aa34-4c87-a871-a48daca6667f.jpg)

`python detect.py --source data/images/zidane.jpg --device mps`
![zidane](https://user-images.githubusercontent.com/87515266/177115824-289876a8-7d2d-45a8-9fa6-ab4f37b940e4.jpg)

### Environment

- YOLOv5 master branch (#8446)
- OS: macOS 12.4
- Python: 3.9

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@peihsuanlin5566 yes I was forced to do PR https://github.com/ultralytics/yolov5/pull/8446 because Apple MPS is still not working correctly in torch 1.12. The advice from the torch team is that the features may be in 1.13 nightly: https://github.com/pytorch/pytorch/issues/77886#issuecomment-1173596613

**Comment by ghost** [comment]
thank you so much. I have updated to 1.13 nightly but  it seems that the problem hasn't solved yet. I would wait for the updating.

**Comment by glenn-jocher** [comment]
@peihsuanlin5566 got it, thanks for the update!
