### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'image_weights'

### ISSUE THREAD

**Issue by zzwwr** [ultralytics/yolov5#8460]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

AttributeError: 'Namespace' object has no attribute 'image_weights'
Hello, I encountered an error message while training my dataset in yoloV5 version 6.1 

### Environment

windows10,
cuda10.2,
python3.8

### Minimal Reproducible Example

train_loader, dataset = create_dataloader(train_path,
                                              imgsz,
                                              batch_size // WORLD_SIZE,
                                              gs,
                                              single_cls,
                                              hyp=hyp,
                                              augment=True,
                                              cache=None if opt.cache == 'val' else opt.cache,
                                              rect=opt.rect,
                                              rank=LOCAL_RANK,
                                              workers=workers,
                                              image_weights=opt.image_weights,
                                              quad=opt.quad,
                                              prefix=colorstr('train: '),
                                              shuffle=True)

### Additional

I hopo you can help me,Thank you!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zzwwr** [comment]
After I changed the configuration file of data and the configuration file of the model, I was sure that I had changed it successfully, but the error occurred at runtime.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/yolov5] AttributeError: 'Namespace' object has no attribute 'image_weights' (Issue #8460)





 
👋 Hello @zzwwr, thank you for your interest in YOLOv5 🚀! Please visit our ⭐️ Tutorials to get started, where you can find quickstart guides for simple tasks like Custom Data Training all the way to advanced concepts like Hyperparameter Evolution.
 
If this is a 🐛 Bug Report, please provide screenshots and minimum viable code to reproduce your issue, otherwise we can not help you.
 
If this is a custom training ❓ Question, please provide as much information as possible, including dataset images, training logs, screenshots, and a public link to online W&amp;B logging if available.
 
For business inquiries or professional support requests please visit https://ultralytics.com or email ***@***.***
 
Requirements
 
Python&gt;=3.7.0 with all requirements.txt installed including PyTorch&gt;=1.7. To get started:
 git clone https://github.com/ultralytics/yolov5  # clone cd yolov5 pip install -r requirements.txt  # install
 
Environments
 
YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled):
  
Google Colab and Kaggle notebooks with free GPU:  
 
Google Cloud Deep Learning VM. See GCP Quickstart Guide
 
Amazon Deep Learning AMI. See AWS Quickstart Guide
 
Docker Image. See Docker Quickstart Guide 
  
Status
 

 
If this badge is green, all YOLOv5 GitHub Actions Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training (train.py), validation (val.py), inference (detect.py) and export (export.py) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by glenn-jocher** [comment]
@zzwwr 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by OU1005465816** [comment]
训练时报了  AttributeError: 'Namespace' object has no attribute 'image_weights' 的错误

**Comment by OU1005465816** [comment]
训练时报了AttributeError: 'Namespace' object has no attribute 'image_weights'的错误

**Comment by OU1005465816** [comment]
训练时报了AttributeError: 'Namespace' object has no attribute 'image_weights'的错误，源码里也有'image_weights'的参数，之前训练成功一次 再次训练就出现这个错误，就很不科学 希望大佬们能指点下  谢啦

**Comment by OU1005465816** [comment]
训练时报了AttributeError: 'Namespace' object has no attribute 'image_weights'的错误，源码里也有'image_weights'的参数，之前也训练成功过，再次训练就出现这个错误，就很不科学，希望大佬们能指点下，谢啦

**Comment by BreezeHavana** [comment]
> 训练时报了AttributeError: 'Namespace' object has no attribute 'image_weights'的错误，源码里也有'image_weights'的参数，之前也训练成功过，再次训练就出现这个错误，就很不科学，希望大佬们能指点下，谢啦

there is no image_weights but images_weights in namespace, so change it.

**Comment by glenn-jocher** [comment]
@BreezeHavana hello! 

It looks like the error message is stating that the 'Namespace' object being used does not have an attribute named 'image_weights'. This could mean that the attribute was deleted or renamed, or that there is a typo in the attribute name. Upon checking the source code, it seems that the correct attribute name is 'images_weights', instead of 'image_weights'. Please try changing the attribute name to 'images_weights' and see if that resolves the issue.

I hope this helps! Let us know if you have any further questions.

**Comment by BreezeHavana** [comment]
auto reply

**Comment by BreezeHavana** [comment]
> @BreezeHavana hello!
> 
> It looks like the error message is stating that the 'Namespace' object being used does not have an attribute named 'image_weights'. This could mean that the attribute was deleted or renamed, or that there is a typo in the attribute name. Upon checking the source code, it seems that the correct attribute name is 'images_weights', instead of 'image_weights'. Please try changing the attribute name to 'images_weights' and see if that resolves the issue.
> 
> I hope this helps! Let us know if you have any further questions.

Hi glenn, I noticed that and changed the attribute name. Thanks for your help.

**Comment by glenn-jocher** [comment]
@BreezeHavana you're welcome! Glad to hear that the suggested fix worked for you. Don't hesitate to reach out if you encounter any further issues or have any other questions. Good luck with your YOLOv5 project!
