### ISSUE TITLE
Inconsistent results on val.py --task test

### ISSUE THREAD

**Issue by cnavarrete** [ultralytics/yolov5#8540]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Good evening
First I want to make clear I just cloned the repo to make sure, the problem is the following, everytime I run val.py --task test I get a different result, which is pretty worrying, since as you can see sometimes I get a really low mAP 0.5 (first pic from 0.531 to 0.409) In the following 2 screenshots I used the same exact command, so I wonder if there's some sort of randomness that leads to such different results between each execution.

![Screenshot from 2022-07-10 16-28-20](https://user-images.githubusercontent.com/52293552/178169240-b09b8998-8a43-4ae1-9adb-52fc381dcd93.png)
![Screenshot from 2022-07-10 16-30-33](https://user-images.githubusercontent.com/52293552/178169261-aeb5940e-7642-4743-8aa1-dfb6e93c5e16.png)

**Comment by glenn-jocher** [comment]
@cnavarrete 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. val.py is deterministic and produces the exact same results on repeated runs. We are not able to reproduce any randomness in our tests:

<img width="1369" alt="Screen Shot 2022-07-11 at 3 11 52 PM" src="https://user-images.githubusercontent.com/26833433/178272123-bbae48c8-1299-45bc-9921-b577b184d83e.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by cnavarrete** [comment]
I don't think I could share the dataset since it's company data, but It doesn't really matter what I train the problem persist, be the task val or test the results are inconsistent. I don't know if this is important, but 'm running yolov5 scripts from a docker container, maybe something related to my enviroment or my pip modules? I'm really scratching my head here, btw I'm using the last version so today's commit.

**Comment by glenn-jocher** [comment]
@cnavarrete without a minimum reproducible example there is no action for us to take.
