### ISSUE TITLE
Detect(inplace=True) multithreaded detection RuntimeError

### ISSUE THREAD

**Issue by mynameischaos** [ultralytics/yolov5#8565]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

torch version: 1.9.1

I use this scripts load model:

self.model = torch.hub.load('ultralytics/yolov5', 'custom', path=self.model_path)

then, run model(image) with single thread is ok. 

then, run model(image) with multithread, but report this error:

File models/yolo.py", line 67, in forward
    y[..., 0:2] = (y[..., 0:2] * 2 + self.grid[i]) * self.stride[i]  # xy
RuntimeError: The size of tensor a (48) must match the size of tensor b (60) at non-singleton dimension 3

I follow the similar issues by set self.inplace = False, but it does not work. 

Please help me.

**Comment by glenn-jocher** [comment]
@mynameischaos yes multiple models require inplace=False

**Comment by glenn-jocher** [comment]
@mynameischaos I'm thinking it may make sense to make inplace=False the default. There are speed improvements in the head with inplace=True but several users have raised multithreading issues so it may be worthwhile to improve the compatibility at the expense of a bit of speed. I think the speed improvement is very slight, but I'll add a TODO to quantify this to determine the best course of action here.

**Comment by glenn-jocher** [comment]
@mynameischaos good news 😃! Your original issue may now be fixed ✅ in PR #8801. This PR sets `Detect.inplace=False` for safe multithread inference when loading YOLOv5 AutoShape models with PyTorch Hub.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by fernandoTB** [comment]
Hi @glenn-jocher ! im still getting Runtime Error with multithread, even setting inplace=False manually.
The error:
`line 72, in forward`
   `wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh`
   `RuntimeError: The size of tensor a (80) must match the size of tensor b (60) at non-singleton dimension 3`

**Comment by glenn-jocher** [comment]
@fernandoTB 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by fernandoTB** [comment]
@glenn-jocher I was facing problems when serving Yolov5 with torch hub + FastAPI, I believe is the same problem reported @mynameischaos. When the client sends multiple requests, FastAPI handles it with multithread. Randomly some inferences crash raising runtime error on self.grid multiplication. 

I tried to force reload to the newest version with inplace=False, but the error just change to another line, where multiplies self.anchor_grid[i].

Apparently, I just solved my problem using threading mutex, allowing only one thread to perform inference at a time.

**Comment by glenn-jocher** [comment]
@fernandoTB got it, thanks! Is there any way to reproduce this with torch hub? i.e. maybe loading two models and dispatching inference in daemon threads? If I could reproduce it it would help debug it.

**Comment by boreas-l** [comment]
> @glenn-jocher I was facing problems when serving Yolov5 with torch hub + FastAPI, I believe is the same problem reported @mynameischaos. When the client sends multiple requests, FastAPI handles it with multithread. Randomly some inferences crash raising runtime error on self.grid multiplication.
> 
> I tried to force reload to the newest version with inplace=False, but the error just change to another line, where multiplies self.anchor_grid[i].
> 
> Apparently, I just solved my problem using threading mutex, allowing only one thread to perform inference at a time.

Can you describe in detail how you handled it？？I need your help.  Thankyou.

**Comment by glenn-jocher** [comment]
@boreas-l It's great to hear that you were able to find a workaround by using threading mutex to control the inference thread execution. This approach ensures that only one thread performs the inference at a time, resolving the issue of crashes during concurrent inference. If other users encounter similar problems with concurrent inference in FastAPI, your solution could be helpful to them as well. Thank you for sharing your experience!
