### ISSUE TITLE
Train.py issue

### ISSUE THREAD

**Issue by Aagamshah9** [ultralytics/yolov5#8591]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Traceback (most recent call last):
  File "train.py", line 665, in <module>
    main(opt)
  File "train.py", line 560, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 100, in train
    plots = not evolve and not opt.noplots  # create plots
AttributeError: 'Namespace' object has no attribute 'noplots'
2022-07-15 16:05:06.789337: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aagam/.local/lib/python3.8/site-packages/cv2/../../lib64:
2022-07-15 16:05:06.789364: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 15247 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 15248) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/aagam/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-15_16:05:09
  host      : lambda-dual
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 15248)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

### Environment

YOLOv5 🚀 v6.1-297-g72a81e7 Python-3.8.10 torch-1.10.2+cu113 CUDA:0 (NVIDIA GeForce RTX 3080, 10018MiB)
                                                                                                            CUDA:1 (NVIDIA GeForce RTX 3080, 10010MiB)
OS - Ubuntu 20.04
Python - 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Aagamshah9 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Aagamshah9** [comment]
Hi @glenn-jocher  Thank you for your response. I appreciate it. But I would like to inform that I cloned your latest repo without making any changes to any of the code. I am using 2 GPU cards. So when I train a network using DDP mode for multi GPU for it no longer works. I think the latest update in train.py might have some issues because before this new commit it used to work fine and calculate P and R values after every epoch but now it no longer calculates even for single epoch and the training stops after 1st epoch only. Can you please look into this and help me out to solve this issue ?
![Screenshot from 2022-07-18 11-17-18](https://user-images.githubusercontent.com/61373740/179576457-c9886704-f595-4a78-85fd-f4460a9a5f2b.png)

**Comment by glenn-jocher** [comment]
@Aagamshah9 DDP training in latest Docker is working correctly. We are unable to reproduce any issues on our side.

<img width="1536" alt="Screenshot 2022-07-18 at 21 49 24" src="https://user-images.githubusercontent.com/26833433/179605228-0d5df603-87f8-42dd-a200-52bb632fd512.png">

**Comment by Aagamshah9** [comment]
Thank you so much @glenn-jocher. I was able to solve the issue. It was multiprocessing.Queue issue which was causing a memory issue to my RAM. I solved it by decreasing my training batch size. Thank you so much once again for your prompt response and help. Much appreciated !! :)

**Comment by glenn-jocher** [comment]
You're welcome @Aagamshah9! I'm glad to hear that you were able to identify and resolve the issue. If you have any more questions or encounter any other issues, feel free to ask. Thank you for your kind words, but all credit goes to the YOLO community and the hard work put in by the Ultralytics team. 👍 Happy training!
