### ISSUE TITLE
Conf_thres and iou_thres 

### ISSUE THREAD

**Issue by tdhooghe** [ultralytics/yolov5#8615]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Glenn, others,

I wondered how you arrived at a .25 conf_thres and .45 iou_thres for the detect.py and model_hub implementations. Did you by any chance do a study that I can look into? 

Kind regards,

**Comment by glenn-jocher** [comment]
@tdhooghe these are detection standard values across a few different tools, i.e. CoreML uses the same thresholds by default.

**Comment by tdhooghe** [comment]
Thank you for your quick response! Could you maybe point me into the direction of which other tools use this threshold and why these values are accepted in general?

**Comment by creativesalam** [comment]
@tdhooghe It depends on your application which values work better for you. Default might work for most people but it is not guaranteed that these values are better for all applications. E.g. I use conf_thres=0.6 in my current project because for my problem False Positive is very dangerous. Higher conf_thres will suppress false positive but at the cost of missing some detections and vice versa.  It is up to you to decide what better suits to your business problem. 

P.S. False positive can also be suppressed by adding more background images but it is just for your understanding. You can always tweak these values to get your desirable outcome.

**Comment by Alberto1404** [comment]
> @tdhooghe It depends on your application which values work better for you. Default might work for most people but it is not guaranteed that these values are better for all applications. E.g. I use conf_thres=0.6 in my current project because for my problem False Positive is very dangerous. Higher conf_thres will suppress false positive but at the cost of missing some detections and vice versa. It is up to you to decide what better suits to your business problem.
> 
> P.S. False positive can also be suppressed by adding more background images but it is just for your understanding. You can always tweak these values to get your desirable outcome.

Hello @creativesalam . Let me know if I am wrong. This is an example training results I obtained for a custom dataset.

![results](https://user-images.githubusercontent.com/91409881/203333331-2574716b-b4a5-4981-8c58-b4141a62d23b.png)
![confusion_matrix](https://user-images.githubusercontent.com/91409881/203333349-ab8d512d-325f-4de3-8d2c-450e3931da90.png)
![F1_curve](https://user-images.githubusercontent.com/91409881/203333352-22dea44f-caf7-4c51-ac79-e687c3830e56.png)
![P_curve](https://user-images.githubusercontent.com/91409881/203333355-5dfb442b-6bdb-4116-b4a6-da88f40b7b70.png)
![PR_curve](https://user-images.githubusercontent.com/91409881/203333362-2c9bc6ed-3085-403d-8ee9-2e79b9fd0441.png)
![R_curve](https://user-images.githubusercontent.com/91409881/203333367-7e7d936f-0088-4902-be6f-3f8724f2bff6.png)
Based on these, what conf-thres and iou-thres should I use when running detect.py?
