### ISSUE TITLE
Yolov5 uses 80% of cpu but less then 10% of Cuda.

### ISSUE THREAD

**Issue by DavidHe-2008** [ultralytics/yolov5#8665]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

In windows, I installed the latest yolov5 in the conda environment.

Training is very slow.

My Nvidia card is geforce 3060. I installed cuda 11.3 and cudnn

On training, it uses 10G bytes of gpu memory, but gpu usage is less than 10%, and cpu usage is more than 80 %.

Why?

It's supposed to use mainly gpu to do calculation.

Thanks.

### Environment

Yolov5 latest, pytorch 1.12 cuda 11.3
windows.

### Minimal Reproducible Example

test

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@springile 👋 Hello! Thanks for asking about **training speed issues**. I'd recommend Docker training for maximum compatibility in Windows. Low CUDA utilization is likely due to dataloader bottlenecks.

YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by DavidHe-2008** [comment]
@glenn-jocher 
Hi, thanks for your answer to my question.

I used the parameter for datasets of 500 pictures, it works well and very fast.

But I got Memory error like this, if I use a dataset f 4000 pictures:
![image](https://user-images.githubusercontent.com/50204931/180814537-92f5cc76-d007-493e-ac17-5b702693bd5b.png)

How to fix it?

Please help

Thanks.

**Comment by glenn-jocher** [comment]
@springile it seems you are out of RAM. You can try `--cache disk` or simply don't cache.
