### ISSUE TITLE
Dataset with no Labels, Transparent PNG

### ISSUE THREAD

**Issue by dazzafact** [ultralytics/yolov5#8699]
### Search before asking

- [x] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, i want to use own images which already has a transparent Background. Alternative white (jpeg) 
![image](https://user-images.githubusercontent.com/67874406/180645635-2dda87ce-f718-4b9a-b036-43c057474820.png)

that's why i need no labeling, right? But how can i skip the Label process (annotation)?

getting this Error:
**_No labels in {cache_path}. Can not train without labels. See {HELP_URL}'
AssertionError: train: No labels in C:\Server\htdocs\ml\ai\detect\datasets\train\images2.cache. Can not train without labels. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data_**
```
train: ./train/Images2# train images (relative to 'path') 128 images
val: ./valid/images  # val images (relative to 'path') 128 images
#test:  ./test/images # test images (optional)

# Classes
nc: 0
#names: [] # class names
```

**Comment by glenn-jocher** [comment]
@biblekiss seems like maybe you want to train a classification model instead of a detection model. Classification datasets like MNIST and CIFAR do not require box labels. See classifier.py in classifier branch for usage examples:
https://github.com/ultralytics/yolov5/blob/1782d0c8cff3fdba1d89d38b95396fe002051581/classifier.py#L1-L17
