### ISSUE TITLE
How TensorRT F16 is used in pytorchhub

### ISSUE THREAD

**Issue by shixiuhai** [ultralytics/yolov5#8715]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I use export.py to export TensorRT F16, and then use pytorchhub to load the model and find that the inference results are empty

**Comment by shixiuhai** [comment]
First I use python3 yolov5/export.py --weights yolov5s.pt --include engine --imgsz 640 --device 0 --half , then I use model=torch.hub.load('yolov5', 'custom', path='./yolov5s.pt', source='local',device=0) no error, but no information detected

**Comment by glenn-jocher** [comment]
@shixiuhai 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. TensorRT --half export and inference with PyTorch Hub works correctly in my test just now in Colab:
<img width="1285" alt="Screen Shot 2022-07-25 at 6 35 32 PM" src="https://user-images.githubusercontent.com/26833433/180829613-4057f618-7011-4036-a1eb-24e9893d686b.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by shixiuhai** [comment]
Thanks a lot, I solved the problem by pulling to the latest version

**Comment by glenn-jocher** [comment]
@shixiuhai that's great to hear! 🎉 If you have any more questions or run into any issues in the future, feel free to reach out. We're here to help!
