### ISSUE TITLE
GPU Memory Usage during Tensor Inference 

### ISSUE THREAD

**Issue by K-YLMike** [ultralytics/yolov5#8719]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi Sir, thanks for providing amazing codes! Now I am almost familiar with how to make own dataset, training with all -- commands, inference, and deploy in TensorRT. The question is no matter I use n/s/m model, or edit width_multiple: 0.50 to 0.25 even less in yolov5_custom.yaml, or change --img from 640 to 320,finally I turn these pt models to tensorRT, the GPU memory usages are always larger than 1700 Mib in nvidia-smi (even file size of pt can be 1.6 mb which is far smaller than 14.4 mb yolov5s.engine). Could you tell me how to further decrease GPU memory usage during inference in tensorRT?

**Comment by glenn-jocher** [comment]
@M1keStr0ng 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by K-YLMike** [comment]
@glenn-jocher Thanks for replying. I know this tutorial and it is for training. My issue is about inference GPU memory usage. During inference, I check the batch is 1, model is .pt --> .engine, image is 640, source is Webcam/RTSP/Video, and decrease width_multiple in yolov5.yaml. What I would like to ask is how can I further decrease GPU Memory during inference, because I need to run multiple yolov5 models in one GPU card (cannot upgrade GPU). The thing is I decreased width_multiple and it did decrease the model size, but GPU memory usage is almost kept the same during reference. REALLY needs your generous help, thanks!

**Comment by glenn-jocher** [comment]
@M1keStr0ng I don't have any quantifiable information on inference memory, but I'd assume smaller models, image sizes and batch sizes would correlate to reduced requirements.

**Comment by sohaiblaraba** [comment]
> @glenn-jocher Thanks for replying. I know this tutorial and it is for training. My issue is about inference GPU memory usage. During inference, I check the batch is 1, model is .pt --> .engine, image is 640, source is Webcam/RTSP/Video, and decrease width_multiple in yolov5.yaml. What I would like to ask is how can I further decrease GPU Memory during inference, because I need to run multiple yolov5 models in one GPU card (cannot upgrade GPU). The thing is I decreased width_multiple and it did decrease the model size, but GPU memory usage is almost kept the same during reference. REALLY needs your generous help, thanks!

I'm facing a similar issue. When I run an inference on GPU, the memory usage keeps growing and leads to "RuntimeError: CUDA out of memory. " after only 3 or 4 images being processed.
This is the first time it happens, and only with the latest code update. 
... Any solution?

**Comment by K-YLMike** [comment]
> 

Since you are talking about inference, I will skip training part. Your situation never happens my here, but I might provide some checks:
1. Ensure you are inferencing under fully updated codes, including library.
2. Try s or m model (yolov5s.pt/yolov5m.pt).
3. Try Webcam/IP Cam/Videos. See if it happens again.
4. Set inference batch size as 1.
5. Set image size as default provided by official code.
6. If you write your own codes for inference, I suggest you follow detect.py.

**Comment by glenn-jocher** [comment]
@K-YLMike Those are great suggestions. Have you tried using smaller model sizes, batch sizes, or image sizes for inference to see if there's any change in GPU memory usage? If you're using your own custom inference scripts, I'd recommend comparing your implementation to the standard `detect.py` script to ensure there are no memory leakage issues. If you're still experiencing difficulties, you may want to consider opening an issue on the YOLOv5 GitHub repo with details about your setup and we can investigate it further.
