### ISSUE TITLE
Prunning NoneType error

### ISSUE THREAD

**Issue by arielsolomon** [ultralytics/yolov5#8761]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Hi, not sure it is a bug but looks like,
I am running prunning on custome yolov5 model and get error that basically says there is no model:
TypeError: 'NoneType' object is not callable
I run both using this tutorial: https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html
And ultralytics https://docs.ultralytics.com/tutorials/pruning-sparsity/.
Appreciate help,
Ariel

### Environment

Cuda: 510.73.08
torch 1.10.0a0+3fd9dcf
Docker container: nvcr.io/nvidia/pytorch:21.09-py3
ubuntu 20.04
Nvidia Rtx 3090

### Minimal Reproducible Example

import torch

def main(model_path):

    print('\nRight before loadint\n')
    device = '0'
    model = torch.hub.load('.', 'custom', path=model_path,force_reload=True, source='local',device=device)
    # model1 = prune(model, 0.3)
    print('\nloading went fine\n')
    return model

from local_inference import main as lc
    model = lc(model_path)
    model = prune(model,0.3)
# load any image at size 1101, 300-495
#when run inference: 

model = lc(model_path)
model = prune(model,0.3)
inference = model(img)
#getting the error indicated

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@arielsolomon 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by arielsolomon** [comment]
Hi, it is custom code in the sense I used minimal needed code to load the yolov5 and run prediction, I did not use the full test.py as mentioned in your tutorial. 
I did how ever used needed parts needed to run it. When I use in my custom code the .pt custom trained model, all works fine.
When I add prunned model (and prunning process does not rise error) the problem described, arised. 
So it is for you to decide if it belong to your playground or not. I will also raise question to torch

**Comment by glenn-jocher** [comment]
@arielsolomon i appreciate your understanding and effort in creating a minimal example. However, it seems like the problem might be specific to the pruning process, which is not directly related to the YOLOv5 model itself. 

I would recommend raising your question to the PyTorch community as well, as they might have specific insights into the issue with model pruning. 

If you have any questions related to using the YOLOv5 model itself or incorporating custom trained models, feel free to ask. Good luck with resolving the pruning issue!
