### ISSUE TITLE
PT Yolo5m to TFLite INT8 results in much larger mAP degradation than PT Yolo5s to TFLite INT8 

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#8762]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have four PT Yolo models, s & m, trained on the exact same dataset with image size 640 and 320. I exported all the models to TFLite FP32 & INT8. The mAP results I get are

. | Yolov5m 640 | Yolov5s 640 | Yolov5m 320 | Yolov5s 320
-- | -- | -- | -- | --
PT | 0.831 | 0.809 | 0.78 | 0.751 | 
TFLite FP16 | 0.83 | 0.809 | 0.78 | 0.752 
TFLite INT8 | **0.633** | **0.681** | 0.48 | 0.445 

Almost the same results for FP16 compared to the original PT model, which I suppose is expected. However, the model degradation is much larger for the Yolov5m model trained on 640 size images (-0.197) than for Yolov5s (-0.128) when exporting to TFLite INT8.  Does anybody have a good rationale for this?

**Comment by glenn-jocher** [comment]
@mikel-brostrom yes this is correct. TF INT-8 quantization is very poor compared to some other export formats like CoreML. This seems to be inherent in the TF quantization code and not due to our implementation, though I could always be wrong.

If you spot areas for improvement please let us know. The implementation is here:
https://github.com/ultralytics/yolov5/blob/e309a855860bc3f618c3541909c515a65ffc35b0/export.py#L368-L385

**Comment by mikel-brostrom** [comment]
Yes, when using INT8 quantization, degradation is expected. But why do I see a larger degradation when exporting Yolov5m PT --> TFLite INT8 than Yolov5s? @glenn-jocher

**Comment by glenn-jocher** [comment]
No idea
