### ISSUE TITLE
Allow passing wandb API key into container through env var

### ISSUE THREAD

**Issue by sstainba** [ultralytics/yolov5#8765]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Allow passing wandb API key into container through env var

### Use case

I use a shell script that runs the docker container with the volume mapping and whatnot.  It would be preferable to pass in the wandb API key this way instead of being prompted for it.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sstainba this is outside the scope of YOLOv5 and simply a Docker question:
https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by sstainba** [comment]
So to be clear, you're suggesting that if I pass it in, it will be used by the yolo image?

**Comment by AyushExel** [comment]
@sstainba yes it should work. Let us know if it doesn't work and I can take a look

**Comment by ashrielbrian** [comment]
@AyushExel is this still the case?

When I set `WANDB_PROJECT` through the docker container (`docker run -e WANDB_PROJECT=bla ...`), I see that it defaults to using the `project` variable passed in from the command line:

```python
self.wandb = wandb.init(project=web_project_name(str(opt.project)),
                                    name=None if opt.name == "exp" else opt.name,
                                    config=opt)
```

But wandb's [docs](https://docs.wandb.ai/guides/track/environment-variables) indicate that the env var should override the project name passed into `wandb.init`:

> `WANDB_PROJECT`: The project associated with your run. This can also be set with wandb init, but the environmental variable will override the value.

I want it to use `WANDB_PROJECT`, instead of the `opt.project` variable which it's still using despite `WANDB_PROJECT` being specified.

Is this expected behaviour?

**EDIT**:

Nevermind, just found this at the bottom of the linked `wandb` docs:

> Do environment variables overwrite the parameters passed to wandb.init()?
> *Arguments passed to wandb.init take precedence over the environment. You could call wandb.init(dir=os.getenv("WANDB_DIR", my_default_override)) if you want to have a default other than the system default when the environment variable isn't set.*

Which I find is completely contradictory to the `WANDB_PROJECT` docs. In any case, would this be a better user experience for YOLOv5's repo?

```python
wandb.init(..., project=os.getenv("WANDB_PROJECT", web_project_name(str(opt.project)))
```

That way, it wouldn't be hardcoded to `opt.project`.
