### ISSUE TITLE
during training "ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group " error

### ISSUE THREAD

**Issue by nebiyebln** [ultralytics/yolov5#8777]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I trained my own dataset with yolov5 in google colab many times. but since yesterday i am getting error. i updated my own folder with new repository. but it still continues. @glenn-jocher @CarlChaaya
this is how i do training.
**!python train.py --img 640 --batch 8 --epochs 30 --data data/char.yaml --weights char.pt --cache**
![Screenshot from 2022-07-29 11-24-04](https://user-images.githubusercontent.com/88368651/181717307-68f13495-b157-4f98-9a9d-57bc17c176c9.png)

**Comment by ozicmoi** [comment]
I am also getting the same error. I could not complete the training. Can you help if you can?  @nebiyebln  @glenn-jocher

**Comment by glenn-jocher** [comment]
@nebiyebln @ozlematiz 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
