### ISSUE TITLE
export to  dynamic onnx  is erro.

### ISSUE THREAD

**Issue by 827346462** [ultralytics/yolov5#8833]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I run "python ./export.py --weight yolov5m.pt --include onnx --device 0 --dynamic"
view erros:"export failure: Input, output and indices must be on the current device"
> Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients, 49.0 GFLOPs

PyTorch: starting from yolov5m.pt with output shape (1, 25200, 85) (40.8 MB)

ONNX: starting export with onnx 1.11.0...
ONNX: export failure: Input, output and indices must be on the current device

I chosee run"python ./export.py --weight yolov5m.pt --include onnx --device 0"

it sucess!

please Dispel doubts.thanks

**Comment by glenn-jocher** [comment]
@827346462 I'd export on cpu (the default) if you are having device issues.

**Comment by glenn-jocher** [comment]
@827346462 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible, your command executes correctly:

<img width="733" alt="Screen Shot 2022-08-02 at 3 27 17 PM" src="https://user-images.githubusercontent.com/26833433/182386302-b197ced5-ed00-4630-a8ca-b58c17de06b7.png">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
