### ISSUE TITLE
"__getitem__" in LoadImagesAndLabels class

### ISSUE THREAD

**Issue by smiles724** [ultralytics/yolov5#885]
Hi, YOLOv5 team, I found something weird and unreasonable in the definition of __getitem__ in LoadImagesAndLabels class. Though it's a tiny mistake, I suppose you can mix it and make the code better. The question is that once I turned image_weights=True, the model couldn't be trained as expected. 

## 🐛 Bug
The following part does not work, since "self.indices" is not defined previously. 

        if self.image_weights:
            index = self.indices[index]

## To Reproduce (REQUIRED)

Input:
```
image_weights=True
```

Output:
```
AttributeError: 'LoadImagesAndLabels' object has no attribute 'indices'
```

## Expected behavior
Can we delete these codes immediately or please assign some values to 'indices'?

**Comment by yazeedhasan97** [comment]
I am facing the same issue

**Comment by glenn-jocher** [comment]
@Wufang1997 @yazeedhasan97 thanks for the bug report. An argparser argument for enabling weighted image training appears to have been accidentally deleted in a past PR. Commit 69ff781ca5fa995ce2eeae215a486ab9f7ff566c should resolve this (DDP section may need rework). Please git pull and try again. To enable weighted image training:

`python train.py --img-weights `

This will select image for training according to their image weights rather than randomly or sequentially selecting them in the dataloader. Image weights are computed as the inverse mAPs of the labelled objects they contain. mAPs obtained from previous epoch's testing. The intended effect is selection more often for images containing problematic classes.
