### ISSUE TITLE
Training fails to start due to data augmentation errors (opencv)

### ISSUE THREAD

**Issue by DLumi** [ultralytics/yolov5#8894]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

When I start training on my custom dataset consisting of '.jpg' images it fails with an opencv error, although according to the preliminary check my images are ok. I have no idea what could go wrong there.
Here's my traceback:

```
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/train/exp5
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0% 0/27 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 642, in <module>
    main(opt)
  File "train.py", line 537, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 301, in train
    for i, (imgs, targets, paths, _) in pbar:  # batch -------------------------------------------------------------
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/content/gdrive/MyDrive/repos/utils/dataloaders.py", line 167, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 461, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/gdrive/MyDrive/repos/utils/dataloaders.py", line 640, in __getitem__
    augment_hsv(img, hgain=hyp['hsv_h'], sgain=hyp['hsv_s'], vgain=hyp['hsv_v'])
  File "/content/gdrive/MyDrive/repos/utils/augmentations.py", line 61, in augment_hsv
    cv2.cvtColor(im_hsv, cv2.COLOR_HSV2BGR, dst=im)  # no return needed
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - Layout of the output array dst is incompatible with cv::Mat
>  - Expected Ptr<cv::UMat> for argument 'dst'
```

### Environment

I run notebook in colab, here's what I got today:

YOLOv5 🚀 v6.1-322-gd5116bb Python-3.7.13 torch-1.12.0+cu113 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 37.4/78.2 GB disk)

### Minimal Reproducible Example

```
!python train.py --img 640 --batch 32 --epochs 300 --data gallery.yaml --weights runs/train/exp3/weights/best.pt --freeze 10
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DLumi** [comment]
I've double checked data by running simple opening/conversion to RGB with cv2, and it looks totally fine from my end.
Since I train model on somewhat toy dataset, I'll share it to help investigate the problem.

/the link has been removed by the author/

**Comment by glenn-jocher** [comment]
@DLumi 👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. If your dataset is failing but all of the common datasets (COCO128, COCO, VOC, etc.) are training correctly then the issue lies with your dataset.

To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths), 2) the number of classes `nc` and 3) a list of class `names`:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
nc: 80  # number of classes
names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
         'hair drier', 'toothbrush' ]  # class names
```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<img width="800" alt="Image Labels" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg">

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>


Good luck 🍀 and let us know if you have any other questions!

**Comment by DLumi** [comment]
Thanks for spending less than 10 seconds on reading the issue, and thanks for the tutorial, but I've followed it already.
I'm pretty sure the data is fine, as I exported my labels from Label Studio specifically in YOLO format. My images are also in the exact folders you mentioned, and the script managed to find them on a preliminary check, so the file structure not the cause of the issue.
I double checked the labels, though. And I'm almost certain that I hit some weird and rare augmentation bug, since it seems like this is the place where something goes wrong.

Here you can see that I plotted the de-normalized label on my train image successfully.
![image](https://user-images.githubusercontent.com/69116001/183471448-126eac86-d11a-469e-86ae-ac1ff54424a3.png)

The Y-coordinate is a 0, as seen here:
`[268   0] [1266  720]`


Code for reproduction in case you need it:
```python
import cv2
import numpy as np
import matplotlib.pyplot as plt

image_folder = Path(r'images\train')
label_folder = Path(r'labels\train')

images = [x for x in image_folder.iterdir()]
labels = [x for x in label_folder.iterdir()]

idx = 0

image = cv2.imread(images[idx].as_posix(), cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

with open(labels[idx]) as f:
    label = np.asarray(f.readline().split()[1:]).astype('float32')

h, w = image.shape[:2]

c_x = label[0] * w
c_y = label[1] * h
l_w = label[2] * w
l_h = label[3] * h

half_w = l_w // 2
half_h = l_h // 2

print(np.intp([c_x - half_w, c_y - half_h]), np.intp([c_x + half_w, c_y + half_h]))

cv2.rectangle(image, np.intp([c_x - half_w, c_y - half_h]), np.intp([c_x + half_w, c_y + half_h]), color=(0, 255, 0), thickness=3)

plt.figure(figsize=(8, 8))
plt.imshow(image)
plt.axis('off')
plt.show()
```

**Comment by glenn-jocher** [comment]
@DLumi thanks for the reproduction code, but it seems this is custom python code and not official YOLOv5 code. If cv2 or matplotlib are producing errors please raise them directly on the relevant repositories.

**Comment by DLumi** [comment]
> @DLumi thanks for the reproduction code, but it seems this is custom python code and not official YOLOv5 code. If cv2 or matplotlib are producing errors please raise them directly on the relevant repositories.

It's the reproduction code of me denormalizing my labels and plotting them on the training image (so you could actually see they are ok). 
As I mentioned earlier, I only interact with the repo via CLI, so here's the actual training code I used:
`!python train.py --img 640 --batch 32 --epochs 300 --data gallery.yaml --weights runs/train/exp3/weights/best.pt --freeze 10`

I could dive into this wonderful rabbit hole to find out what exactly went wrong, but I'd rather not. Besides, I'm pretty sure you'll be able to get to the bottom of this much faster than I would, especially having source date on your hand.

**Comment by glenn-jocher** [comment]
@DLumi I'm not able to reproduce any issues using your command with a common dataset.

<img width="1481" alt="Screen Shot 2022-08-08 at 7 17 29 PM" src="https://user-images.githubusercontent.com/26833433/183475827-b1129d19-ef56-493e-8ce9-017bbe6fee95.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by DLumi** [comment]
I decided to take another look at the issue, and tried to pull some recent changes to the repo. 
The thing is that git told me that I have some local changes (!) in the dataloader and some other files. That's pretty weird as I never modified the source code (I guess config files don't count?). 
Anyways, once I reset and updated the repo everything started working again.
Thanks for your help.

**Comment by glenn-jocher** [comment]
@DLumi great, glad to hear it! Let us know if you run into any other issues or think of new useful feature :)
