### ISSUE TITLE
ImportError: cannot import name 'draw_bounding_boxes' from 'torchvision.utils'

### ISSUE THREAD

**Issue by abcsunshine** [ultralytics/yolov5#8898]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![image](https://user-images.githubusercontent.com/68814215/183353020-07a5ae3e-ecd8-4c81-be9d-fd40caea15b2.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@thepycoder can you take a look please? 
@abcsunshine is this error related to clearml logger? Does it work fine without clearml?

**Comment by thepycoder** [comment]
Can you do a pip freeze and make sure you have torchvision installed? Is it the same version as in the requirements.txt?

**Comment by abcsunshine** [comment]
I think this is the right version.
However, when I just  ignore the import code，it can work well.

![image](https://user-images.githubusercontent.com/68814215/183551645-2ae1520d-42c3-4856-aa07-2cadff27d5ba.png)

![image](https://user-images.githubusercontent.com/68814215/183551943-98a3cb6f-847c-4df8-871a-adf4599c849b.png)

**Comment by thepycoder** [comment]
It seems like the `draw_bounding_boxes` functionality was only added to torchvision starting from v0.9.0.
In contrast, the requirements of YOLOv5 specify `torchvision>=0.8.1`, which means if you have 0.8.1 or 0.8.2 installed, it will error because of this import statement.

So the solution for you @abcsunshine is to upgrade torchvision, or (if you don't use ClearML), commenting out the import statement is indeed also fine.

@AyushExel How do you want to solve this? I assume you won't like it to change the whole repo requirements file from `torchvision>=0.8.1` to `torchvision>=0.9.0`. So in that case, we should re-implement the `draw_bounding_boxes` function without using torchvision. Any other ideas?

**Comment by glenn-jocher** [comment]
@thepycoder ah got it. Simplest quick fix is to scope the import to place it within the `try: import clearml` statement. This will reduce the affected userbase. 

A more permanent fix might be to use the YOLOv5 `Annotator` class below. We can't bump the torchvision requirements right now because there are some Jetson Nano tutorials that require torch 1.7.0 torchvision 0.8.1

Annotator class:
https://github.com/ultralytics/yolov5/blob/b551098d59cce7aa9755b711b9cbe49758d3beae/utils/plots.py#L68-L126

detect.py usage example for box annotation:
https://github.com/ultralytics/yolov5/blob/b551098d59cce7aa9755b711b9cbe49758d3beae/detect.py#L170

**Comment by glenn-jocher** [comment]
@abcsunshine @thepycoder good news 😃! Your original issue may now be fixed ✅ in PR #8915. This is not a permanent solution but rather a scoped import quickfix.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by glenn-jocher** [comment]
@abcsunshine @thepycoder I think this shows the need for another CI check at the torch minimum requirement. I'll add this to the YOLOv5 CI to catch these problems earlier in the future. Trying to add in https://github.com/ultralytics/yolov5/pull/8916
