### ISSUE TITLE
is Yolov7 repo violating the GPL 3.0 License?

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/yolov5#8983]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Recently I tried [yolov7](https://github.com/WongKinYiu/yolov7).

I realized they have instance segmentation and I ran the classic `python detect.py` command.

And I got the following ` requirements: onnxruntime==1.10.0 not found and is required by YOLOv5, attempting auto-update...`
![image](https://user-images.githubusercontent.com/17271049/184849198-4167df89-d6e3-4238-9aa7-c5fc290f38e2.png)

Yes, "required by **YOLOv5**"🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️ and also you can see in the logs "YOLOR". The "author" of YOLOR is the same as YOLOv7 so this could be logic, but it would be nice if people use their own code.

I don't know, but I am witness to how hard ultralytics have worked in yolov5 and I dislike and I feel angry when [other repos copy](https://github.com/Megvii-BaseDetection/YOLOX/issues/765) the functions and everything claiming being "authors" of things they are not.

### Additional

On the other hand, I tried the object detection model and it is soooooo slow!!!

![image](https://user-images.githubusercontent.com/17271049/184850772-555c6fcd-3649-43bc-9056-74a7bf71e814.png)

200 ms per frame??? 

Anyway, I think it is just a copy of the Ultralytics repo so I think yolov5 will be with us for a long long time like yolov3 did.

**Comment by MartinPedersenpp** [comment]
![image](https://user-images.githubusercontent.com/24861628/184872317-f77566b9-c000-4e1d-ba85-2bfdc5cb5d14.png)

Without being an expert, it looks like they took the parameters used for Yolov5x and doubled it, which would result in a higher MaP.

I only skimmed the paper, but it is mentioned that they use an improved network structure and things like that.
As long as they don't try to commercialize yolov7 then I don't think there are any infringements to the GPL.

I think that the state that vision tech is in right now is all about "ripping off" each others knowledge gains and seeing if they can be improved further, but I totally get why you would be alarmed by such an obvious blooper where they haven't rewritten the entire code.

**Comment by hdnh2006** [comment]
Hi @MartinPedersenpp , how do you come to that conclusion? That's only possible comparing the architectures. I have not checked the architectures but yolov7 is definitely using functions that belong to @glenn-jocher and this should be violating GP3 License.

**Comment by MartinPedersenpp** [comment]
Taken from the GPL3.0 License:

> When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.
To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights.  Therefore, you have
certain responsibilities if you distribute copies of the software, or if
you modify it: responsibilities to respect the freedom of others.
For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.
Developers that use the GNU GPL protect your rights with two steps:
(1) assert copyright on the software, and (2) offer you this License
giving you legal permission to copy, distribute and/or modify it.
For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software.  For both users' and
authors' sake, the GPL requires that modified versions be marked as
changed, so that their problems will not be attributed erroneously to
authors of previous versions.

I am in no way educated in laws and legal matters, but I interpret this as in the Yolov7 academics are allowed to take pieces of @glenn-jocher code  and use it or modify it.

I looked a bit into the paper and it seems like even if they have used @glenn-jocher's code to create the train / val / detect framework. The network architecture still seems different than that of Yolov5 and in one of the very first phrases they cite that Yolo has been a foundation for many of the SOTA algorithms in the field of object detection.

I will gladly retract everything I have written if any legal authorities says that I am wrong and I in no way want to undermine the tremendous work that @glenn-jocher and his team has done with this repo and all of the work that goes into maintaining such a popular repo after the initial release.

**Comment by glenn-jocher** [comment]
Hi @MartinPedersenpp, thank you for addressing your concerns. Your interpretation of the GPL-3.0 license is accurate. Academics and developers are allowed to use and modify pieces of YOLOv5 code as long as they maintain the same freedoms and responsibilities as per the license.

It's great to see notable progress in the object detection field, and I appreciate your thoughtfulness and support. The YOLOv5 community and the Ultralytics team are continuously contributing to advancements in object detection, and it's heartening to see others build upon this work.

Your diligence and respect for the license are commendable, and I'm grateful for your understanding and support. If you have any further questions or need clarification, feel free to reach out.

Thank you,
Glenn Jocher
