### ISSUE TITLE
How to fix the img size when validatating or testing 

### ISSUE THREAD

**Issue by zhangweida2080** [ultralytics/yolov5#9046]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

The training images will have the same image size (e.g., (32, 3, 640, 640)) when I set the `image size: 640`. 
However, the image size in val_loader will be different, one btach (32, 3, 640, 520), another (32, 3, 640, 490)... 
So,

1. why the image sizes varing in validating ? 
2. How to fix the image size in testing/validating without damaging the performance ?
3.  In this [issue](https://github.com/ultralytics/yolov5/issues/8584), ` rectangular inference: False` for train, while ` rectangular inference: True` for val. Should I set `rectangular inference==False` in val?

**Comment by glenn-jocher** [comment]
@zhangweida2080 hi there! 

1. The variation in image sizes during validation is due to YOLOv5's default behavior of maintaining aspect ratio during inference.
2. You can fix the image size during testing/validation by setting `img_size` directly in the test command line to override the default behavior.
3. If you want to maintain consistency, you can set `rectangular inference: False` in val as well.

For more details, you may refer to our documentation at https://docs.ultralytics.com/yolov5/. Thank you for using YOLOv5!
