### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by shahizat** [ultralytics/yolov5#9063]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi yolov5 community,

Has anyone experienced the below problem, when run detect command using camera source?

```
Fusing layers... 
YOLOv5n summary: 213 layers, 1867405 parameters, 0 gradients
Unable to init server: Could not connect: Connection refused
WARNING: Environment does not support cv2.imshow() or PIL Image.show() image displays
OpenCV(4.5.4) /home/jetson/opencv/modules/highgui/src/window_gtk.cpp:635: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

[ WARN:0] global /home/jetson/opencv/modules/videoio/src/cap_gstreamer.cpp (1100) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
1/1: 2...  Success (inf frames 1280x720 at 30.00 FPS)

Traceback (most recent call last):
  File "detect.py", line 254, in <module>
    main(opt)
  File "detect.py", line 249, in main
    run(**vars(opt))
  File "/home/jetson/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 111, in run
    for path, im, im0s, vid_cap, s in dataset:
  File "/home/jetson/Projects/yolo/yolov5/utils/dataloaders.py", line 396, in __next__
    img = img[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW
ValueError: axes don't match array
terminate called without an active exception
```

**Comment by glenn-jocher** [comment]
@shahizat hi there,

It looks like you're encountering an issue when running the detect command using a camera source. This could be related to the OpenCV, PIL, or system setup. For some users, this error is resolved by ensuring proper environment settings, while others have encountered it due to underlying hardware or software configurations.

To better understand and address this issue, could you provide more information about your environment and setup? This could include details about the hardware, OS, Python version, and any dependencies or custom configurations you've implemented.

Also, feel free to check out our [documentation](https://docs.ultralytics.com/yolov5/) for insights or existing discussions on similar topics.

Looking forward to helping you resolve this!
