### ISSUE TITLE
A question about computing ap value in yolov5

### ISSUE THREAD

**Issue by firrice** [ultralytics/yolov5#9100]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

      Hello, author, I have a question about the definition of Tp(true positive) in Yolov5.  
      For a example, in the following case, all the predict boxes with maxIOU value are the same GT box, and the their maxIOU value all are greater than 0.5(thresold). In this case, how to assign Tp or Fp to these predict boxes? 
      To my understanding, (1) In VOC2010 standard (according to Faster RCNN and other algorithms), it's baesd on confidence(or 'score'), which means the largest one is Tp and the others are Fp; (2)But in YoloV5, I found there is some difference with VOC2010 standard. It's based on maxIOU, which means that for a GT, which predict box has the largest IOU with it will be assigned as TP, and the others are assigned as Fp(according to the code in the red box in the Fig). 
     Is my understanding right? Please give some comment, thank u much!
![demo](https://user-images.githubusercontent.com/26590498/186065089-c600c565-f8cc-4812-aec4-73d1721f5d2c.jpg)

**Comment by quarrying** [comment]
Actually [`process_batch`](https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/val.py#L71) is used in model evalution, not [`ConfusionMatrix.process_batch`](https://github.com/ultralytics/yolov5/blob/c725511bfc14eb86daf6edefa0d257084aa24c85/utils/metrics.py#L132).

And There is inconsistent between `process_batch` and `ConfusionMatrix.process_batch`, the key code snippet is as follows:

In `process_batch`

<https://github.com/ultralytics/yolov5/blob/c725511bfc14eb86daf6edefa0d257084aa24c85/utils/metrics.py#L157-L160>

In `ConfusionMatrix.process_batch`

<https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/val.py#L88-L91>

I think the implementation in `process_batch` is just the same as the one of faster rcnn (the order must be different), because `detections` from [`non_max_suppression`](https://github.com/ultralytics/yolov5/blob/c725511bfc14eb86daf6edefa0d257084aa24c85/utils/general.py#L819) is sorted according to class confidence.

**Comment by firrice** [comment]
> Actually [`process_batch`](https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/val.py#L71) is used in model evalution, not [`ConfusionMatrix.process_batch`](https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/utils/metrics.py#L132).
> 
> And There is inconsistent between `process_batch` and `ConfusionMatrix.process_batch`, the key code snippet is as follows:
> 
> In `ConfusionMatrix.process_batch`
> 
> https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/utils/metrics.py#L157-L160
> 
> In `process_batch`
> 
> https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/val.py#L88-L91
> 
> I think the implementation in `process_batch` is just the same as the one of faster rcnn (the order may be different), because `detections` from [`non_max_suppression`](https://github.com/ultralytics/yolov5/blob/06831aa9e905e0fa703958f6b3f3db443cf477f3/utils/general.py#L819) is sorted according to class confidence.
> 
> The following codes may be helpful to understand it.
> 
> ```python
> import numpy as np
> 
> if __name__ == '__main__':
>     np.random.seed(666)
>     overlaps = np.random.randn(4, 4)
>     num_gts, num_dets = overlaps.shape
>     indices = np.where(overlaps > 0)
> 
>     matches = np.concatenate((np.stack(indices, 1), overlaps[indices[0], indices[1]][:, None]), 1)
>     print(matches)
>     print('============================')
>     matches = matches[matches[:, 2].argsort()[::-1]]
>     print(matches)
>     print('============================')
>     matches = matches[np.unique(matches[:, 1], return_index=True)[1]]
>     print(matches)
>     print('============================')
>     
>     matches = matches[matches[:, 2].argsort()[::-1]]
>     print(matches)
>     print('============================')
>     matches = matches[np.unique(matches[:, 0], return_index=True)[1]]
>     print(matches)
>     print('============================')
> ```

Thanks so much! It helps me adjust my understanding!

**Comment by glenn-jocher** [comment]
@firrice you're welcome! I'm glad the information was helpful to you. If you have any more questions or need further clarification, feel free to ask. Thank you for your support and contributions to the YOLO community!
