### ISSUE TITLE
Yolov5 with Human pose Estimator model

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/yolov5#9113]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hi @glenn-jocher 
I need to combine Yolov5 with a human estimator model to recognize a certain human position for carrying a gun 
and give an alarm for it 
I need to understand how to combine the pose model with yolo
please if you have an example or any idea or explanation  i would appreciate that
thank you

**Comment by glenn-jocher** [comment]
@moahaimen see https://github.com/TexasInstruments/edgeai-yolov5

**Comment by ryouchinsa** [comment]
We improved the JSON2YOLO script so that it converts the COCO keypoints format to YOLOv8 pose format.
https://github.com/ultralytics/JSON2YOLO/issues/45

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can label polygons and keypoints in the YOLO format.
```
class_index center_x center_y width height x1 y1 v1 x2 y2 v2 x3 y3 v3 ...
0 0.545230 0.616880 0.298794 0.766239 0.522073 0.309332 2 0.540170 0.293193 2 0.499589 0.296503 2 ...
```

A visibility flag v defined as v=0: not labeled, v=1: labeled but not visible, and v=2: labeled and visible.
https://cocodataset.org/#format-data

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209942647-fa9565e0-d4cf-42c2-a382-a8043465765b.jpg)

**Comment by glenn-jocher** [comment]
@ryouchinsa that's great to hear! Thank you for sharing the information. If you have any questions or need further assistance related to the YOLOv5 repo, feel free to ask. Good luck with your project!
