### ISSUE TITLE
Question about uploading background image on Roboflow

### ISSUE THREAD

**Issue by jiam9700** [ultralytics/yolov5#9177]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Dear Team,

I try to upload background images on Roboflow as recommended, and since my background is fixed (in a simulation scene) so the background images are the same. The problem is that Roboflow will automatically merge the same images into one. Can I ask how could I fix this problem? Many thanks!

**Comment by glenn-jocher** [comment]
@jiam9700 hi there,

Since the background images are the same in your simulation scene, it seems Roboflow is automatically merging them into one. You can fix this by providing each background image with a unique identifier or filename. This should prevent them from being merged together. Let me know if you need further assistance with this.

Best regards
