### ISSUE TITLE
validate my model's accuracy on my testing set

### ISSUE THREAD

**Issue by CoderManar** [ultralytics/yolov5#9181]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

hey, I have divided my dataset into (train, val, test) in **my data.yaml** file. my question is how to **validate the accuracy** of the trained model on **my data.yaml** file. I have used **val.py** to validate the model's accuracy, but unfortunately, val.py runs on **coco.yaml** file **not** my custom file with its custom labels. what to do in this case?  your help is highly appreciated.

1. screenshot of my code when using **detect.py** on my test set (it worked): 
<img width="1070" alt="Screen Shot 1444-02-01 at 9 22 08 AM" src="https://user-images.githubusercontent.com/70074305/187060646-0ebc0c3b-b625-436a-a93f-6dc15163555f.png">

2. screenshot of my code when using **val.py** on my test set (it did not work) it was referring to coco.yaml not my data.yaml!
<img width="1061" alt="Screen Shot 1444-02-01 at 9 22 45 AM" src="https://user-images.githubusercontent.com/70074305/187060715-4e4f86dc-6c3d-4ec7-8bf9-0057cb39d0ee.png">

**Comment by SanjayGhanagiri** [comment]
@CoderManar From the screenshot it clearly looks like you have not specified your trained weights. Please provide the path to the weights folder. 

`!python  val.py --data data.yaml --weights yolov5/runs/train/exp/weights/best.pt`


In the above case, since you have not provided any weights, YOLOV5 by default is downloading and using weights trained on COCO dataset with 80 classes and the data.yaml file has only 6 classes, hence the error.

YOLOV5 and its community is so beautiful. Hope this solves your issue.

**Comment by CoderManar** [comment]
> @CoderManar From the screenshot it clearly looks like you have not specified your trained weights. Please provide the path to the weights folder.
> 
> `!python val.py --data data.yaml --weights runs/train/exp/weights/best.pt`
> 
> In the above case, since you have not provided any weights, YOLOV5 by default is downloading and using weights trained on COCO dataset with 80 classes and the data.yaml file has only 6 classes, hence the error.
> 
> YOLOV5 and its community is so beautiful. Hope this solves your issue.

Thanks a lot Sanjay. Indeed, your comment about specifying my weights has solved my issue. Highly appreciated.
