### ISSUE TITLE
Consistent and Efficient Preprocessing for Classification and Detection Model

### ISSUE THREAD

**Issue by paradigmn** [ultralytics/yolov5#9192]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

The new classification model utilizes a different preprocessing pipeline as the detection model. For object detection, the image is normalized, resized with constant aspect ratio and padded to size. In comparison, the new classification models utilizes normalization, resizing, center crop and standardization by ImageNet mean and std.

### Use case

We use YOLOv5 models for embedded applications with our own performance optimized software framework. Due to the two pipelines, the models are not easily interchangeable. Furthermore, the classification preprocessing pipeline is more performance intensive and therefore not well suited for low power environments.

Would it be possible to introduce a compatibility flag or some other solution to export classification models which expect the same normalized rgb image input?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@paradigmn that's a good question, we've had another source inquire as well. This first ClassficiationModel release is simply intended as a starting point for future releases, so this kind of feedback is valuable. 

The current preprocessing was meant to mirror the typical standard like ResNet, but I agree we should work on harmonizing the two. 

The good news is v6.3 supports instance SegmentationModels using the same preprocessing as the DetectionModels, so at least those two are equal. 

WRT to ImageNet normalization, I have not observed it to produce any improvements in YOLOv5 which is why I left it out. I doubt it's helping Classification either, the high number of BN modules are already doing this at every layer.

We'll experiment with similar preprocessing in the future. @AyushExel

**Comment by glenn-jocher** [comment]
@paradigmn opened https://github.com/ultralytics/yolov5/pull/9213 to experiment with detection-like preprocessing for cls.

**Comment by paradigmn** [comment]
@glenn-jocher cool, thanks for the fast response! I am excited about the new changes :)

**Comment by glenn-jocher** [comment]
@paradigmn have you guys done any studies on the effects of different pre-processing techniques or is this just something you noticed recently?

**Comment by paradigmn** [comment]
@glenn-jocher no, we just tried to use the classification model with our existing pipeline and noticed a steep decline in accuracy. With your LetterBox preprocessing from #9213 everything works as expected, good work!

**Comment by glenn-jocher** [comment]
@paradigmn ok I've merged #9213 into master. This replaced the Torch transforms with faster ones I wrote myself, should be about 3X faster preprocessing. It's still using the same series of operations, but this will give us a good baseline to start testing the effect of using detection preprocessing on the classification models.

**Comment by paradigmn** [comment]
@glenn-jocher sounds good. Did you update the pretrained classification model weights as well?

**Comment by glenn-jocher** [comment]
@paradigmn no, no. Retraining the models is a significant undertaking. The current PR replaces the existing transforms with faster ones that do the same thing, and adds a LetterBox transform that is currently unused but that we can experiment with.

**Comment by paradigmn** [comment]
ah ok, thank you for clarifying.

**Comment by glenn-jocher** [comment]
@paradigmn you're welcome! Let me know if you have any more questions.
