### ISSUE TITLE
Video is not showing up while using detect.py.

### ISSUE THREAD

**Issue by yakhyo** [ultralytics/yolov5#9219]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, I am facing an error which I have never faced before when I use YOLOv, I am trying to use the `detect.py` to inference on a video file. When I run the `detect.py` the video is not showing up and there is no any sign that it's working in the background. But it's utilizing the GPU. I am wondering is it a problem of Ubuntu or OpenCV . . .
Looking forward answers . . . 

- OS: Linux Ubuntu 22.04
- CUDA: 11.7
- CUDA Driver:  515.65.01
- GPU: RTX 3090
- requirements.txt has been installed 

### Additional

![image](https://user-images.githubusercontent.com/28424328/187381056-44899ffc-9dc4-499d-83c8-aaf6ec44bcfc.jpg)

**Comment by AyushExel** [comment]
@yakhyo you need to pass `--show-img` flag. Example:
```
python detect.py --weights .... --show-img
```

**Comment by AyushExel** [comment]
@yakhyo oh yes I meant `--view-img` ..Hmm its strange it not working and not throwing any errors too. Is the video result being saved in the runs/ folder?

**Comment by glenn-jocher** [comment]
@yakhyo YouTube inference works correctly for me in Colab:
<img width="1289" alt="Screenshot 2022-08-30 at 13 54 12" src="https://user-images.githubusercontent.com/26833433/187430148-e38c179e-d8af-4c62-90c3-9b4e39125f25.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by yakhyo** [comment]
I could not solve this issue happening with my code and I don't think this problem associated with this code I guess. So I am closing this. Thank you all for your kind replies, peace.

**Comment by glenn-jocher** [comment]
@yakhyo you're welcome! Please feel free to reach out if you encounter any other issues or need further assistance in the future. Thank you for reaching out, and have a great day!
