### ISSUE TITLE
KeyError: 'lrf'

### ISSUE THREAD

**Issue by klock18** [ultralytics/yolov5#922]
## 🐛 Bug
I was having the same issues as  #736, after about 10 epochs (where the model was performing well) all my training and validation curves were getting NaNs. After pulling from Github today I am getting the following error:

![image](https://user-images.githubusercontent.com/43727102/92366911-1c648100-f139-11ea-9f17-33254cf9c570.png)

Appreciate your help in fixing this.

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/cab36f72a852ef00e8b42d3283ba9b2fc757b17f/data/hyp.scratch.yaml#L1-L7

**Comment by klock18** [comment]
Thanks again Glenn!

**Comment by YileAllenChen1** [comment]
I was running yolov5 on a custom dataset, and I came over the same issue with KeyError: "lrf". I checked the file "yolov5/data/hyp.scratch.yaml" and it already head the two lines that Glenn added, I would appreciate some help on this. 
![image](https://user-images.githubusercontent.com/43359545/103722095-d7d8dd00-4f94-11eb-96b6-49b76011dd3d.png)

**Comment by glenn-jocher** [comment]
👋 Hello @YileAllenChen1, thank you for your interest in our work! This issue seems to lack the minimum requirements for a proper response, or is insufficiently detailed for us to help you. Please note that most technical problems are due to:

- **Your modified or out-of-date code**. If your issue is not reproducible in a new `git clone` version of this repo we can not debug it. Before going further run this code and verify your issue persists:
```bash
$ git clone https://github.com/ultralytics/yolov5 yolov5_new  # clone latest
$ cd yolov5_new
$ python detect.py  # verify detection

# CODE TO REPRODUCE YOUR ISSUE HERE
```

- **Your custom data.** If your issue is not reproducible in one of our 3 common datasets ([COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [COCO128](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), or [VOC](https://github.com/ultralytics/yolov5/blob/master/data/voc.yaml)) we can not debug it. Visit our [Custom Training Tutorial](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data) for guidelines on training your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of your labels and images.

- **Your environment.** If your issue is not reproducible in one of the verified environments below we can not debug it. If you are running YOLOv5 locally, verify your environment meets all of the [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies specified below. If in doubt, download Python 3.8.0 from https://www.python.org/, create a new [venv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/), and install requirements.

If none of these apply to you, we suggest you close this issue and raise a new one using the 🐛 **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!


## Requirements

Python 3.8 or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including `torch>=1.7`. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by RAHUL-KAD** [comment]
> I was running yolov5 on a custom dataset, and I came over the same issue with KeyError: "lrf". I checked the file "yolov5/data/hyp.scratch.yaml" and it already head the two lines that Glenn added, I would appreciate some help on this.
> ![image](https://user-images.githubusercontent.com/43359545/103722095-d7d8dd00-4f94-11eb-96b6-49b76011dd3d.png)

@YileAllenChen1, error is coming because in hyp.scratch.yaml file there is no variable named as lrf. I also had the same issue. I just added **lrf** in my .yaml file.

**Comment by PrashantDixit0** [comment]
Go into data/hyp.scratch.yaml and add *lrf* argument. It is missing in it
