### ISSUE TITLE
doesn't work with proxy and youtube source

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [ultralytics/yolov5#9248]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Other

### Bug

Hello, I can't make the detection work when **connecting to a youtube source**. 
It **doesn't download new weights** either, when behind a proxy.

I'm behind a proxy. 

Every command in the powershell works without the need for setting a proxy (ping, ftp etc). Even pip seems to work.

I've tried
> set https_proxy=ip:3128
> set http_proxy=ip:3128

### Environment

- yolo v5
- windows 10
- python 3.10

### Minimal Reproducible Example

python detect.py --weights yolov5m.pt --source https://www.youtube.com/watch?v=u8Vvws69Fso

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GianniGi hi there! To use YOLOv5 with YouTube sources behind a proxy, consider adding `--source http://youtube.com/watch?v=u8Vvws69Fso` instead of `https`. We don't currently download new weights during the detection process, but you can manually download them from our repository. As for proxy configurations, ensure you've set the environmental variables correctly as mentioned. If issues persist, refer to our Ultralytics Docs for further troubleshooting. Appreciate your patience and understanding!
