### ISSUE TITLE
best.pt is always  last.pt

### ISSUE THREAD

**Issue by xiaocheng2333** [ultralytics/yolov5#925]
## Additional context
![image](https://user-images.githubusercontent.com/62132324/92426228-faf8a900-f1bb-11ea-8312-88e6f24968d7.png)
why my best.pt is always last.pt when i finish my training?

**Comment by xiaocheng2333** [comment]
Optimizer stripped from runs/exp0/weights/last.pt, 177.5MB
Optimizer stripped from runs/exp0/weights/best.pt, 177.5MB

**Comment by Ownmarc** [comment]
You probably think they are the same because they have the same datetime right ? If its the case, they are most likely not the same, its just that after the training is completed, the last.pt and best.pt both get stripped. Thats why you see them created at the same time. 
You can test that by loading the model both models, making them predict on the same image and compare results. If results are different, they are different, if they are not, then they are the same.
