### ISSUE TITLE
How to save cropped images without bounding boxes using custom trained yolov5 pytorch hub

### ISSUE THREAD

**Issue by Abrar-04** [ultralytics/yolov5#9296]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

How to save cropped images without bounding boxes using custom trained yolov5 inference

Code:
```
model = torch.hub.load('.', 'custom', path='best.pt', source='local')
img_path=  'test_img/g8.jpg'
results = model(img_path, size=640)
results.show()
crops = results.crop(save=True)
```

It saves the crops in runs\detect\exp8\crops\
as 
![g8](https://user-images.githubusercontent.com/59110866/188574391-7675337f-5604-4361-9794-ead284b743ac.jpg)

How to save cropped images without these bounding boxes using custom model pytorch hub

It works fine when i use 
`python detect.py --weights best.pt --source test_img/g8.jpg' --save-txt --save-crop `
But not with the inference using custom yolov5 model pytorch hub

**Comment by RizwanMunawar** [comment]
@Abrar-04! You will need to comment the code line in the [detect.py](https://github.com/ultralytics/yolov5/blob/1aea74cddbc78e7f79dac07090cb157dfc24dbcc/detect.py#L166), then you will be able to get the cropped part without a bounding box. YOLOv5 with Pytorch hub directly does not provide this functionality directly until now.

**Comment by Abrar-04** [comment]
> @Abrar-04! You will need to comment the code line [[166](https://github.com/ultralytics/yolov5/blob/master/detect.py#L166) and [171](https://github.com/ultralytics/yolov5/blob/master/detect.py)] in the [detect.py](https://github.com/ultralytics/yolov5/blob/1aea74cddbc78e7f79dac07090cb157dfc24dbcc/detect.py#L166) file, then you will be able to get the cropped part without a bounding box. YOLOv5 with Pytorch hub directly does not provide this functionality until now.

Thanks for quick response

When I run this in terminal it saves all the crops without bounding boxes even without commenting the lines [166 and 171]
```
python detect.py --weights best.pt --source test_img/g8.jpg' --save-txt --save-crop
```

But I want to detect it inside a separate script main.py
```
model = torch.hub.load('.', 'custom', path='best.pt', source='local')
img_path=  'test_img/g8.jpg'
results = model(img_path, size=640)
results.show()
crops = results.crop(save=True)
```
Is there any alternative to load custom trained yolov5 model and run detections on multiple images within a script on not directly from the terminal

Thanks

**Comment by RizwanMunawar** [comment]
@Abrar-04! Please take a look at the code [https://github.com/hpc203/yolov5-dnn-cpp-python-v2](https://github.com/hpc203/yolov5-dnn-cpp-python-v2) 
You can also use official YOLOv5 code with sub-module command for integration in your existing code.

**Comment by glenn-jocher** [comment]
@Abrar-04 this is a bug if you are seeing crops with boxes. Is this reproducible in the latest master code?

**Comment by glenn-jocher** [comment]
@Abrar-04 your issue is not reproducible. results.crop() works correctly:

<img width="1673" alt="Screenshot 2022-09-06 at 14 02 12" src="https://user-images.githubusercontent.com/26833433/188619159-a67321bf-69db-467d-93b3-887ef7132b61.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Abrar-04** [comment]
> @Abrar-04 your issue is not reproducible. results.crop() works correctly:
> 
> <img alt="Screenshot 2022-09-06 at 14 02 12" width="1673" src="https://user-images.githubusercontent.com/26833433/188619159-a67321bf-69db-467d-93b3-887ef7132b61.png">
> 
> We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃


I am on the latest master,
it works fine with official yolov5 saved model but not with my custom trained best.pt 
my yolov5 custom model detects topwear,bottomwear,footwear 
best.pt can be found here:
https://drive.google.com/file/d/1eQWo77FmG7cuPLaE9RI0a9wHO5lRaE_8/view?usp=sharing 
the cropped images are saved without bounding boxes when i run this in terminal
```
python detect.py --weights best.pt --source test_img/g8.jpg' --save-txt --save-crop
```

But when i run this script(main.py)  , the cropped images are saved with the bounding boxes
```
model = torch.hub.load('.', 'custom', path='best.pt', source='local')
img_path=  'test_img/g8.jpg'
results = model(img_path, size=640)
results.show()
crops = results.crop(save=True)
```
