### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by zxq309** [ultralytics/yolov5#9301]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

ClearML Hyperparameter Optimization: python utils/loggers/clearml/hpo.py error, how to solve it.
![微信截图_20220906194359](https://user-images.githubusercontent.com/22740766/188630436-5ddc304f-3880-4e21-8a04-b9a854877c8e.png)

**Comment by glenn-jocher** [comment]
@zxq309 you might have a pip package named models installed, i.e. `pip uninstall models` and try again

**Comment by zxq309** [comment]
@glenn-jocher It still doesn't work. Iit seems can't find the path to these packages, which are defined in "train.py". 
![image](https://user-images.githubusercontent.com/22740766/188766977-f5304cc8-af39-4005-8ee4-86a6c976e941.png)
"python utils/loggers/clearml/hpo.py" need to use a training task ID has been saved in  ClearML manager,  "train.py" script will be run from CleraML. I wonder if that is the reason？
![image](https://user-images.githubusercontent.com/22740766/188767213-7c54cfcf-f664-41fe-89ae-d0b1000d7e83.png)

**Comment by glenn-jocher** [comment]
@zxq309 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by zxq309** [comment]
@glenn-jocher this issue has solved?

**Comment by glenn-jocher** [comment]
@zxq309 Thank you for bringing this to our attention! If you have any further questions or encounter any issues, feel free to reach out. We're here to help. 🚀
