### ISSUE TITLE
PermissionError when running train.py 

### ISSUE THREAD

**Issue by seenthestars** [ultralytics/yolov5#9302]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "D:\PycharmProjects\project4\yolov5-6.2\train.py", line 635, in <module>
    main(opt)
  File "D:\PycharmProjects\project4\yolov5-6.2\train.py", line 499, in main
    d = torch.load(last, map_location='cpu')['opt']
  File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '.'

**Comment by glenn-jocher** [comment]
@seenthestars 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Crawy9** [comment]
> 

hi Have you solved this problem yet？

**Comment by Crawy9** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Traceback (most recent call last): File "D:\PycharmProjects\project4\yolov5-6.2\train.py", line 635, in main(opt) File "D:\PycharmProjects\project4\yolov5-6.2\train.py", line 499, in main d = torch.load(last, map_location='cpu')['opt'] File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "E:\Program Files\conda_data\envs\yolov5_7.0\lib\site-packages\torch\serialization.py", line 211, in **init** super(_open_file, self).**init**(open(name, mode)) PermissionError: [Errno 13] Permission denied: '.'
> 
> ### Additional
> _No response_

hi Have you solved this problem yet？

**Comment by glenn-jocher** [comment]
@Crawy9 So sorry to hear you're still facing this problem. This error usually occurs due to a file permission issue or when trying to access a file or directory without the necessary permissions. Please ensure that your program has the required permissions to access the file or directory in question. If you are running the script from a command line, ensure that your current working directory is set correctly.

If the issue persists, please provide a minimal, reproducible example following the guidelines shared earlier. This will allow us to better understand and diagnose the problem.

Thank you!
