### ISSUE TITLE
Training starts on all GPUs no matter what `--device` is selected when multiple GPU available

### ISSUE THREAD

**Issue by mikel-brostrom** [ultralytics/yolov5#9306]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Previous versions let you chose a specific GPU for training. The current behavior is that

```
python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320
```

spawns a training on the number of available GPUs. This can be seen when checking `nvtop`, after running the command above, which results in:

```bash     
    PID  USER DEV    TYPE  GPU        GPU MEM    CPU  HOST MEM Command                                                                                                                                                                        
  24608 mikel   0 Compute  20%  10981MiB  68%    55%   5967MiB python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320                                                                                  
  24608 mikel   1 Compute  18%   1383MiB   9%     0%   5967MiB python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320
  24608 mikel   2 Compute  20%   1383MiB   9%     0%   5967MiB python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320
  24608 mikel   3 Compute  18%   1383MiB   9%     0%   5967MiB python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320
```

### Environment

YOLOv5 🚀 v6.2-94-g1aea74cd Python-3.8.0 torch-1.12.0+cu102 CUDA:2 (Tesla T4, 16128MiB)

### Minimal Reproducible Example

```
python train.py --data custom_split.yaml --cfg yolov5m.yaml --weights yolov5m.pt --batch-size 16 --device 2 --img 320  # on a multi GPU machine
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mikel-brostrom https://github.com/ultralytics/yolov5/blob/32794c130bc0de9cbd1fe34819b7032138bbd81d/utils/torch_utils.py#L54-L58

**Comment by glenn-jocher** [comment]
@mikel-brostrom multi-GPU single-device training operates correctly in master with torch 1.12.1:

<img width="1277" alt="Screenshot 2022-09-06 at 19 21 34" src="https://user-images.githubusercontent.com/26833433/188686581-da2e2e08-b7ea-4e04-b8e9-a00b5f0f44e8.png">

<img width="1277" alt="Screenshot 2022-09-06 at 19 21 15" src="https://user-images.githubusercontent.com/26833433/188686616-a6fd06cf-b2d8-4b95-818c-8254c7e3e8f8.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by mikel-brostrom** [comment]
Thank again for your rapid response! I just cloned a new repo and installed `requirements.txt` in a new environment. Still getting this behavior

**Comment by glenn-jocher** [comment]
@mikel-brostrom I'd recommend training in our Docker image for environment issues.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by mikel-brostrom** [comment]
Weird. I restarted my machine and pulled the latest and the issue vanished. Thank you anyways :smile:

**Comment by glenn-jocher** [comment]
@mikel-brostrom glad to hear that the issue is resolved! Sometimes a fresh start and pulling the latest code can work wonders. If you encounter any other issues or have further questions, feel free to reach out. Happy training! 😊
