### ISSUE TITLE
evolve does not use the default value

### ISSUE THREAD

**Issue by emillundh** [ultralytics/yolov5#9316]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Evolution

### Bug

The tutorial suggests that one can append the flag --evolve without a numeric argument with it, and it will run for 300 generations. However, when I do that, it evolves for 1 generation. The relevant piece of output is
```
Hyperparameter evolution finished True generations
```

### Environment

- YOLO: yolov5==6.1.8 pip installed
- OS: Ubuntu 20.04, also WIndows 10

### Minimal Reproducible Example

```
yolov5 train --imgsz 640 --batch-size 16 --epochs 2 --data train.yaml --weights yolov5s.pt --evolve
```
which is suggested in the tutorial (issue #607)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@emillundh 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible, I'm removing the bug label. I ran the default Colab notebook training with --evolve appended and it's so far run 5 generations:

<img width="1758" alt="Screenshot 2022-09-07 at 16 37 12" src="https://user-images.githubusercontent.com/26833433/188892415-dd8790f0-f764-41cc-b2d0-bb17e7b2c141.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
