### ISSUE TITLE
How to save cropped images without bounding boxes using custom trained yolov5 pytorch hub

### ISSUE THREAD

**Issue by Abrar-04** [ultralytics/yolov5#9323]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

I am on the latest master Of Official YOLOv5 main repo with no changes,

it works fine only with official yolov5 saved model 
```
import torch
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
# Image
im = 'https://ultralytics.com/images/zidane.jpg'
# Inference
results = model(im)
results.show()
crops = results.crop(save=True)
```

the cropped images are saved without bounding boxes when i run this in terminal

```
python detect.py --weights best.pt --source test_img/g8.jpg' --save-txt --save-crop
```

But when i run this script with my custom trained best.pt
my yolov5 custom model detects topwear,bottomwear,footwear
best.pt can be found here:
https://drive.google.com/file/d/1eQWo77FmG7cuPLaE9RI0a9wHO5lRaE_8/view?usp=sharing

```
model = torch.hub.load('.', 'custom', path='best.pt', source='local')
img_path=  'test_img/g8.jpg'
results = model(img_path, size=640)
results.show()
crops = results.crop(save=True)
```
 the cropped images are saved with the bounding boxes
![bbox](https://user-images.githubusercontent.com/59110866/188870902-3622b6b1-55b0-458d-b2f7-7e6a278a11ef.jpg)

### Environment

YOLO V5 Latest repo main
Windows 10 Home
Python 3.8.5

### Minimal Reproducible Example

When i run this script with my custom trained best.pt
my yolov5 custom model detects topwear,bottomwear,footwear
best.pt can be found here:
https://drive.google.com/file/d/1eQWo77FmG7cuPLaE9RI0a9wHO5lRaE_8/view?usp=sharing

```
model = torch.hub.load('.', 'custom', path='best.pt', source='local')
img_path=  'test_img/g8.jpg'
results = model(img_path, size=640)
results.show()
crops = results.crop(save=True)
```
 the cropped images are saved with the bounding boxes
![bbox](https://user-images.githubusercontent.com/59110866/188870902-3622b6b1-55b0-458d-b2f7-7e6a278a11ef.jpg)

it works fine when run using official saved model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Abrar-04 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀.

I've run a newly trained model via torch hub for crops (again, this is the second time I'm taking time to do this), and again everything works correctly.

```
model = torch.hub.load('ultralytics/yolov5', 'custom', 'runs/train/exp/weights/best.pt') 
```

![Uploading Screenshot 2022-09-07 at 16.27.14.png…]()

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Abrar-04** [comment]
> Not a bug, user error. Don't show results before you crop if you don't want the results to appear in your crop.

cropping before showing the results works 
Thanks

**Comment by glenn-jocher** [comment]
@Abrar-04 you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your YOLOv5 project!
