### ISSUE TITLE
Tensorrt Export of yolov5x - insufficient memory error

### ISSUE THREAD

**Issue by Guruprasadhegde** [ultralytics/yolov5#9336]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

I can run inference with batch 16 but when I try to export the same model to tensorrt engine with batch size 16 it gives me insufficient memory error. 

### Minimal Reproducible Example

python export.py --weights custom.pt --include engine --device 0 --img 3288 --data custom.yaml --batch 16 --conf-thres=0.01

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Guruprasadhegde 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by Guruprasadhegde** [comment]
@glenn-jocher Thank you for your response! 
I am facing insufficient cuda error not during Training but rather when I am using the export.py script to generate Tensorrt Engine file (of my trained network). While val.py with batch 16 runs as expected (with the same Model) indicating that I have enough memory in the system. But I now wanted to checkout inference using Tensorrt engine file. So I am trying to export the engine file with batch 16 it is failing to even Generate the tensorrt engine file.

**Comment by glenn-jocher** [comment]
@Guruprasadhegde same rules apply to reduce CUDA usage: smaller model, smaller image size, --half, etc. Not very complicated.

**Comment by Guruprasadhegde** [comment]
@glenn-jocher You are absolutely correct that if I reduce the batch size while exporting Tensorrt it does work.  But here is what confuses me (maybe I am thinking about it the wrong way). I can run val.py with batch 16 that would mean that my GPU does fit the model and batch size.
 val.py running as expected 
![image](https://user-images.githubusercontent.com/17193101/189499924-5d164394-0582-4c16-be76-9f4b404789be.png)
cuda usage while it was running
![image](https://user-images.githubusercontent.com/17193101/189499952-427e4336-dfb6-4582-bccb-8cfe3f564ddd.png)

Now if I try to export the same model with the same batch size it errors out. I am not getting why there is CUDA error while exporting a trained model with exact same batch size that fits in my GPU. 
![image](https://user-images.githubusercontent.com/17193101/189500168-3837ec82-2188-40ff-bef4-314c70bb459c.png)

Of course the export works when I chose batch size 4, but doing this means I am not fully utilizing my GPU during inference
![image](https://user-images.githubusercontent.com/17193101/189500518-e873d0f2-587b-47c1-97fe-d0304215df73.png)
cuda usage while it was running
![image](https://user-images.githubusercontent.com/17193101/189500541-5751454e-8ae2-4667-b58f-82b3151f0523.png)

**Comment by glenn-jocher** [comment]
@Guruprasadhegde yeah that is kind of confusing. It appears that TensorRT is using more memory during export to try to run many optimization strategies on the model to find out what works the fastest, so exporting uses more memory than normal inference.
