### ISSUE TITLE
Training Error: IndexError: index 17 is out of bounds for dimension 1 with size 3

### ISSUE THREAD

**Issue by gongmingcn** [ultralytics/yolov5#9342]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am a new guy to YOLOv5, and I would like to train my dataset of images with size of 100px100p, and my training command is constructed as following:
`python train.py --img 96 --batch 50 --epoch 100 --data '../datasets/tof_images_data.yaml' --cfg './models/tof_custom_yolov5n.yaml' --weights ' ' --project '../datasets/runs/ai4tof' --name 'tof_wo_desk'
`
Content of "my_images_data.yaml " is following:
```
path: /usr/src/datasets/tofimg
train: images/train
val: images/valid
test: images/test

nc: 3
names: ['head','body','eyes']
```

For ./models/tof_custom_yolov5n.yaml, I only modified the 1st line from
`nc: 80  # number of classes`
to
`'nc: 3  # number of classes'`
accordingly.

The running results are screen-copied as followings:
![image](https://user-images.githubusercontent.com/107666508/189269753-461beaaf-cc7e-4646-9b64-430cb36bea9f.png)
![image](https://user-images.githubusercontent.com/107666508/189269868-111ad4d5-4d68-4bf2-ac5b-2a017d650597.png)

I checked the existing issues list and found [one suspected similar issue](https://github.com/ultralytics/yolov5/issues/1312), however after reading it, I am afraid that it is one different from my issue.

Any help from anybody is appreciated. : )

### Additional
By the way, the train_batch result:
![image](https://user-images.githubusercontent.com/107666508/189275533-468f815d-6921-4cfc-aee7-c7313008847a.png)
Labels_corrlogram:
![image](https://user-images.githubusercontent.com/107666508/189275637-2bf69a8a-689f-4024-a4ca-197b030c0003.png)
Labels
![image](https://user-images.githubusercontent.com/107666508/189275708-7237f6d1-835c-4f1e-85e4-7045981cbf8c.png)
 
_No response_

**Comment by glenn-jocher** [comment]
@gongmingcn 👋 Hello! Thanks for asking about YOLOv5 🚀 **dataset formatting**. To train correctly your data must be in YOLOv5 format. Please see our [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) tutorial for full documentation on dataset setup and all steps required to start training your first model. A few excerpts from the tutorial:

### 1.1 Create dataset.yaml

[COCO128](https://www.kaggle.com/datasets/ultralytics/coco128) is an example small tutorial dataset composed of the first 128 images in [COCO](http://cocodataset.org/#home) train2017. These same 128 images are used for both training and validation to verify our training pipeline is capable of overfitting. [data/coco128.yaml](https://github.com/ultralytics/yolov5/blob/master/data/coco128.yaml), shown below, is the dataset config file that defines 1) the dataset root directory `path` and relative paths to `train` / `val` / `test` image directories (or *.txt files with image paths) and 2) a class `names` dictionary:
```yaml
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes (80 COCO classes)
names:
  0: person
  1: bicycle
  2: car
  ...
  77: teddy bear
  78: hair drier
  79: toothbrush

```


### 1.2 Create Labels

After using a tool like [Roboflow Annotate](https://roboflow.com/annotate?ref=ultralytics) to label your images, export your labels to **YOLO format**, with one `*.txt` file per image (if no objects in image, no `*.txt` file is required). The `*.txt` file specifications are:

- One row per object
- Each row is `class x_center y_center width height` format.
- Box coordinates must be in **normalized xywh** format (from 0 - 1). If your boxes are in pixels, divide `x_center` and `width` by image width, and `y_center` and `height` by image height.
- Class numbers are zero-indexed (start from 0).

<p align="center"><img width="750" src="https://user-images.githubusercontent.com/26833433/91506361-c7965000-e886-11ea-8291-c72b98c25eec.jpg"></p>

The label file corresponding to the above image contains 2 persons (class `0`) and a tie (class `27`):

<p align="center"><img width="428" src="https://user-images.githubusercontent.com/26833433/112467037-d2568c00-8d66-11eb-8796-55402ac0d62f.png"></p>


### 1.3 Organize Directories

Organize your train and val images and labels according to the example below. YOLOv5 assumes  `/coco128` is inside a `/datasets` directory **next to** the `/yolov5` directory. **YOLOv5 locates labels automatically for each image** by replacing the last instance of `/images/` in each image path with `/labels/`. For example:
```bash
../datasets/coco128/images/im0.jpg  # image
../datasets/coco128/labels/im0.txt  # label
```

<p align="center"><img width="700" src="https://user-images.githubusercontent.com/26833433/134436012-65111ad1-9541-4853-81a6-f19a3468b75f.png"></p>
</details>

Good luck 🍀 and let us know if you have any other questions!

**Comment by gongmingcn** [comment]
Hi [glenn-jocher](https://github.com/glenn-jocher), 

Thanks for your prompt feedback.

Yes, I do follow your tutorial to do the labeling and folder arrangement process, and as you can see in "train_batch result",  the training process should already work, but the error could happen in the validation process somewhere.

From your experience, what kind of issue will result in the error of "index 17 is out of bounds for dimension 1 with size 3"?

Thanks in advance.

B. R.

Gongming

**Comment by glenn-jocher** [comment]
@gongmingcn sounds like a class index issue, i.e. maybe you have some classes labelled as 17 when they should only be labelled 0-2. 

If you can reproduce this issue on a common dataset like VOC or COCO please let us know.

**Comment by lfgogogo** [comment]
@gongmingcn Have you solved the problem？I get almost the same error，but it happens in training process:
<img width="680" alt="image" src="https://github.com/ultralytics/yolov5/assets/42054022/e4d4169b-b319-454d-b85a-b72db518207e">

**Comment by glenn-jocher** [comment]
@lfgogogo hello, 

Thank you for reaching out to us. The error "index is out of bounds" can occur when a network is trying to access an element outside the available indices of an array. This issue can have a variety of causes such as mislabelled class indices, incorrect input size, or improper data formatting.

We recommend reviewing the dataset formatting and ensuring the class indices are correct. You can use the 'check' argument in the train.py function to check both the formatting and class indices of the dataset.

If the problem persists, kindly provide the complete error message and any other details such as your data setup, network type, and model configuration files, so that we can better assist you.

Best Regards, 
YOLOv5 Team

**Comment by GavinLiangSYSU** [comment]
Hello, I also met this problem and can't solve it. I tried to use VOCdevkit dataset with 20 classes to train yolov5s. When I only used 86 samples for training, it blocked at utils/dataloaders.py line 768 (class LoadImagesAndLabels-> getitem), in __getitem__ index = self.indices[index]. I used debug mode and found index was 837, which was much larger than my dataset size 86 samples. I can't find where this index=534 generatered. However, I tried to use 50000 samples to train and it works. I also check my class id is fine. Wish you give me some suggestions.
![微信图片_20240807223151](https://github.com/user-attachments/assets/011944ee-c44d-48d4-bfa1-24d5b1580792)

**Comment by glenn-jocher** [comment]
Hello @GavinLiangSYSU,

Thank you for reaching out and providing detailed information about the issue you're encountering. It sounds like you're experiencing an indexing problem when using a smaller subset of your dataset.

Here are a few suggestions to help diagnose and potentially resolve the issue:

1. **Check Dataset Integrity**: Ensure that all your image and label files are correctly paired and that there are no missing or corrupted files. Each image should have a corresponding label file.

2. **Update to Latest Version**: Make sure you are using the latest version of YOLOv5 and its dependencies. Sometimes, bugs are fixed in newer releases. You can update YOLOv5 by running:
    ```bash
    git pull
    pip install -r requirements.txt
    ```

3. **Verify DataLoader**: The issue might be related to how the DataLoader is handling the smaller dataset. You can try modifying the `batch_size` or `num_workers` parameters in your training script to see if that resolves the issue. For example:
    ```python
    python train.py --batch-size 16 --workers 2 --data voc.yaml --weights yolov5s.pt
    ```

4. **Debugging**: Since you mentioned using debug mode, you might want to add additional print statements or logging to trace where the large index value is being generated. This can help pinpoint the exact location in the code where things go wrong.

5. **Subset Sampling**: If the issue only occurs with a very small dataset, consider using a slightly larger subset for debugging purposes. Sometimes, very small datasets can cause unexpected behavior in data augmentation or batching processes.

6. **Community and Issues**: If the problem persists, consider searching through the [YOLOv5 issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) to see if others have encountered and resolved similar issues. You can also open a new issue with detailed information if needed.

Here's a small code snippet to help you with debugging:
```python
# Add this to utils/dataloaders.py around line 768
print(f"Index: {index}, Dataset Size: {len(self.indices)}")
```

This will print out the index and dataset size each time `__getitem__` is called, helping you trace where the issue might be occurring.

I hope these suggestions help! If you have any further questions or need additional assistance, feel free to ask. 😊
