### ISSUE TITLE
TensorRT: export failure: failed to load ONNX file

### ISSUE THREAD

**Issue by Nuwan1654** [ultralytics/yolov5#9344]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

## Description

Hi, I am trying to convert yolov5m model into tensort model for batch inference (batch size of 4). but I am getting an error while converting.  This error does not happen when I don't use the `--dynamic` parameter. Any help would be appreciated.

Thanks

## files
For exporting yolov5 PyTorch model to ONNX I used 
https://github.com/ultralytics/yolov5/blob/master/export.py

## Steps To Reproduce

1. generate the yolov5 onnx model and convert the yolov5m.pt to ONNX with the `--dynamic` argument
 `python3 export.py --weights yolov5m.pt --include engine --data ./data/coco.yaml --dynamic`

When converting to tensoRT I get the following error.

[09/09/2022-03:38:15] [TRT] [E] ModelImporter.cpp:748: While parsing node number 291 [Range -> "onnx::Reshape_471"]:
[09/09/2022-03:38:15] [TRT] [E] ModelImporter.cpp:749: --- Begin node ---
[09/09/2022-03:38:15] [TRT] [E] ModelImporter.cpp:750: input: "onnx::Range_469"
input: "onnx::Range_468"
input: "onnx::Range_470"
output: "onnx::Reshape_471"
name: "Range_291"
op_type: "Range"

[09/09/2022-03:38:15] [TRT] [E] ModelImporter.cpp:751: --- End node ---
[09/09/2022-03:38:15] [TRT] [E] ModelImporter.cpp:753: ERROR: ModelImporter.cpp:162 In function parseGraph:
[6] Invalid Node - Range_291
All inputs to range should be initializers.
TensorRT: export failure ❌ 9.7s: failed to load ONNX file: yolov5m.onnx

## System Environment
Jetson Orin

TensorRT Version: 8.4.0.11
NVIDIA GPU: 1024-core NVIDIA Ampere architecture GPU (Jetson Orin)
CUDA Version: 11.4
Operating System: Linux ubuntu
Python Version: 3.8.10
PyTorch Version: 1.11.0

### Minimal Reproducible Example

 `python3 export.py --weights yolov5m.pt --include engine --data ./data/coco.yaml --dynamic`

### Additional

I am trying to do the batch inference using yolov5 tensorRT model

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Nuwan1654 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. Your issue is not reproducible. Dynamic TRT export works correctly:

<img width="1460" alt="Screenshot 2022-09-09 at 12 59 36" src="https://user-images.githubusercontent.com/26833433/189325067-12b95b77-a05d-4b51-b26d-dfb6c418d688.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Nuwan1654** [comment]
Interesting, It works well in the colab. but I am trying to export in the Jetson Orin,  

I try to install nvidia-tensorrt in jetson using 

`pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com` but it gives 

ERROR: Could not find a version that satisfies the requirement nvidia-tensorr. 

It seems like a tensoRT issue.

Thanks

**Comment by glenn-jocher** [comment]
@Nuwan1654 see TRT Installation guide:
https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by Nuwan1654** [comment]
@glenn-jocher Thanks for the help, I was able to convert the yolov5 to ONNX and then to tensorRT engine and successfully run the batch inference in the jetson Orin.

**Comment by luvwinnie** [comment]
@Nuwan1654 Hello, I'm having the same problem with jetson agx orin, would you mind to share how did you solved the problem?

**Comment by dinusha94** [comment]
> @Nuwan1654 Hello, I'm having the same problem with jetson agx orin, would you mind to share how did you solved the problem?

Use the following commands to convert to yolov5 pytorch model to trt engine file (in the Orin tensorRT and trtexec should be installed by default if you build it with NVIDIA's SDK MANAGER )
1. python3 export.py --weights yolov5m_shear.pt --include onnx --data coco128.yaml --device 0
2. trtexec --onnx=yolov5m.onnx --fp16 --saveEngine=yolov5m_static.engine --useCudaGraph

**Comment by luvwinnie** [comment]
@dinusha94 Thank you for reply.
I'm trying to export a dynamic yolov5, did you able to export dynamic shape yolov5?
Currently having below errors.


```
[12/16/2022-09:24:07] [E] [TRT] ModelImporter.cpp:748: While parsing node number 264 [Range -> "onnx::Reshape_400"]:
[12/16/2022-09:24:07] [E] [TRT] ModelImporter.cpp:749: --- Begin node ---
[12/16/2022-09:24:07] [E] [TRT] ModelImporter.cpp:750: input: "onnx::Range_398"
input: "onnx::Range_397"
input: "onnx::Range_399"
output: "onnx::Reshape_400"
name: "Range_264"
op_type: "Range"

[12/16/2022-09:24:07] [E] [TRT] ModelImporter.cpp:751: --- End node ---
[12/16/2022-09:24:07] [E] [TRT] ModelImporter.cpp:753: ERROR: ModelImporter.cpp:162 In function parseGraph:
[6] Invalid Node - Range_264
All inputs to range should be initializers.
[12/16/2022-09:24:07] [E] Failed to parse onnx file
[12/16/2022-09:24:07] [I] Finish parsing network model
[12/16/2022-09:24:07] [E] Parsing model failed
[12/16/2022-09:24:07] [E] Failed to create engine from model or file.
[12/16/2022-09:24:07] [E] Engine set up failed
```

**Comment by dinusha94** [comment]
@luvwinnie I used the following steps to create a `.engine` which can be used to do the bach inference.

For input size 640x640 and batch size 4

1. using yolov5 export file, `python3 export.py --weights yolov5m_shear.pt --include onnx --data coco128.yaml --device 0 --batch-size 4`

2. Convert batch parameter to 'b' using dynmic.py.

3. use the following `trtexec` command for conversion (change the input resolution and batch size accordingly)
`trtexec --onnx=dynamic.onnx --fp16 --minShapes=images:1x3x640x640 --optShapes=images:4x3x640x640 --maxShapes=images:8x3x640x640 --useCudaGraph --saveEngine= < output name >_dynamic.engine`


dynamic.py ->

"""
This file converts the explicit batch size to an interchangeable variable
"""
import onnx
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--onnx-model', '-p', help='path to the input onnx model')
args_in = parser.parse_args()

model = onnx.load(args_in.onnx_model)
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = 'b'
onnx.save(model, f'dynamic.onnx')
onnx.checker.check_model(model)
