### ISSUE TITLE
Getting error while training on YOLOv5 colab tutorial

### ISSUE THREAD

**Issue by diya18114021** [ultralytics/yolov5#9365]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

![Screenshot (60)](https://user-images.githubusercontent.com/45495906/189505704-d6648087-2c02-4972-aefe-4b2dd5229a77.png)

### Environment

- YOLOv5 Colab tutorial
- RAM - 16GB

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by diya18114021** [comment]
Minimal Reproducible example
!python train.py --img 640 --batch 16 --epochs 100 --data coco128.yaml --weights yolov5s.pt

**Comment by diya18114021** [comment]
@glenn-jocher I used Google Colab Tutorial on Windows 10, kindly give me any solution.

**Comment by CaptainArmenia** [comment]
I am experiencing the same error since I pulled the last version of master branch.

**Comment by elvinyeoh** [comment]
Same issue !!!

**Comment by StJuan1210** [comment]
For me it was fine about 10hrs ago but now same issue

**Comment by diya18114021** [comment]
It was fine for me also at 11pm yesterday.

**Comment by weepots** [comment]
I have been having issues too, still gives the same error when running locally using jupyter notebook

**Comment by glenn-jocher** [comment]
@diya18114021 I'm able to reproduce. Looking into this

**Comment by glenn-jocher** [comment]
@diya18114021 `--device cpu` works, so it's related to device selection somehow.

**Comment by glenn-jocher** [comment]
@diya18114021 @elvinyeoh @StJuan1210 @weepots good news 😃! Your original issue may now be fixed ✅ in PR #9367. AMP checks were loading the model in AutoShape which was updating the Detect() module export attribute to True. This been resolved now by running AMP checks on a deepcopy() version of the model rather than on the model itself.

PR has been verified in Colab and GPU training now works correctly.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
