### ISSUE TITLE
How Train many models (yolov5) on the same time with different inputs 

### ISSUE THREAD

**Issue by wafa-bouzouita** [ultralytics/yolov5#9374]
I want to train yolov5 separately for different datasets (X1,Y1), (X2,Y2) ..., (X10, Y10) and so on.
 Instead of training each model and save its weights consecutively. I want to train them in parallel to save time.

How I do that please ?

Thank you

**Comment by wafa-bouzouita** [comment]
I look forward to your reply ...

**Comment by glenn-jocher** [comment]
@wafa-bouzouita if you have a multi-GPU machine you can run multiple trainings in parallel, i.e.:
```
python train.py ... --device 0
python train.py ... --device 1
...
```

**Comment by wafa-bouzouita** [comment]
Is it possible to run multiple trainings in parallel with a single GPU ?

**Comment by glenn-jocher** [comment]
@wafa-bouzouita sure

**Comment by wafa-bouzouita** [comment]
Could you please specify me what modifications must I do to the code to let runing multiple trainings in parallel in a single GPU possible ?

**Comment by glenn-jocher** [comment]
use same --device

**Comment by glenn-jocher** [comment]
@wafa-bouzouita I mean in general I wouldn't advise training multiple models on a single device. I doubt you will see a net gain in training throughput, i.e. if you train two models they'll each take about twice as long.

👋 Hello! Thanks for asking about **training speed issues**. YOLOv5 🚀 can be trained on CPU (slowest), [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) (fastest). If you would like to increase your training speed some options are:

- Increase `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) DDP at larger `--batch-size`
- Train on cached data: `python train.py --cache` (RAM caching) or `--cache disk` (disk caching)
- Train on faster GPUs, i.e.: P100 -> V100 -> A100
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

Good luck 🍀 and let us know if you have any other questions!

**Comment by wafa-bouzouita** [comment]
Thank you.
In my application, I need to run multiple trainings in same device.
In fact, I tested training multiple models on a single device and (when it works) I gain much time (for example, the training of two models simultaneously takes 11 minutes instead of 20 minutes...). But, the problem is that sometimes with same models the training stops without generating error... Have you an idea if this problem maybe is due to conflicts between the multiple trainings? In this case, is it tensorflow better to deal with multiple trainings in same device ?

**Comment by glenn-jocher** [comment]
@wafa-bouzouita 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
