### ISSUE TITLE
About the input image size

### ISSUE THREAD

**Issue by OUX-Eulogize** [ultralytics/yolov5#9424]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi!
My question is about the input image size.
I know the network has gone through five downsamples, so the input image size should be an integer multiple of 32. But why 640?
Is this selection of input image size determined based on certain features of the object to be detected in the image?

**Comment by glenn-jocher** [comment]
@OUX-Eulogize hi there!

The input image size of 640 is simply a commonly used default for YOLOv5. It is indeed required to be an integer multiple of 32 due to the network architecture, but the specific choice of 640 is not based on the features of the objects to be detected. Feel free to adjust the input image size based on your specific requirements, keeping it a multiple of 32. 

Hope this helps! Let me know if you have any further questions.

Best regards
