### ISSUE TITLE
Paddle export bug: torch tensor `.clone()` is not supported

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/yolov5#9439]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Export

### Bug

@glenn-jocher 
The problem occurs when I run the command below:
```
python export.py --weights yolov5s.pt --include paddle
```

![ksnip_20220916-163859](https://user-images.githubusercontent.com/41098760/190595487-092ec554-dedf-4111-ad0b-13f8c71cebbb.png)

Model conversion failed.

### Environment

- YOLOv5 🚀 v6.2-117-ga1e5f9a Python-3.8.13 torch-1.11.0+cu113 CPU
- Ubuntu 20.04
- Python 3.8.13

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer thanks for the bug report! 

I'm able to reproduce this as well. It looks like the Detect() update I introduced for segmentation models has broken Paddle export due to lack of support for .clone() here:
https://github.com/ultralytics/yolov5/blob/a1e5f9a97de2a3ace012315208c686744ced2782/models/yolo.py#L67-L68

Also, I should add Paddle export to benchmarks CI so this is error is caught earlier.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer I can confirm that export works up to Segmentation models PR, last working commit is abea53ea5b7d4eba6b58535d31e17336912d0d1f

<img width="1153" alt="Screenshot 2022-09-16 at 13 30 33" src="https://user-images.githubusercontent.com/26833433/190629511-13869f38-fcdf-4324-b445-1711e96bfa9a.png">

I'm going to raise an issue on the Paddle repo as this seems to be a limitation on their side rather than a bug with YOLOv5.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer issue raised in https://github.com/PaddlePaddle/Paddle/issues/46146

**Comment by Zengyf-CVer** [comment]
@glenn-jocher  Thank you very much.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer good news 😃! Your original issue may now be fixed ✅ in PR #9458. This PR updates the YOLOv5 Detect() head to remove the .clone() operation causing issues.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
