### ISSUE TITLE
Dear Glenn Jocher, How are you? training problem

### ISSUE THREAD

**Issue by alkhalisy** [ultralytics/yolov5#9456]
Dear Glenn Jocher, How are you?

Pls I trying to create A new custom dataset that has 4 classes every class has 1200 color images, and the class names eye_movment, move_hand, looking_side, and mobile_use as student behavioral analysis for the online exam. For the training result mentioned below, I used the yolov5s with default values. The testing results with poor accuracy 0.2 or 0.4 in this range, I tested the model with input frames from the webcam in real time, please can you help me by that what you suggestions to fix this problem or where the problem exactly, I notice the model trained in just 4 epochs and I think is it not normal because I try to train with more than 4 epoch like 10 or 50 the result become worst I thing overfitting. please how can I solve the problem?  or what kind of problem I have, Please help me

<img width="460" alt="image" src="https://user-images.githubusercontent.com/49120272/190865192-1892ef0a-a726-46da-84ed-88a8b4ce42af.png">

![confusion_matrix](https://user-images.githubusercontent.com/49120272/190858461-28b228a7-2a8e-4744-8dba-d9f808f7bd00.png)
![labels](https://user-images.githubusercontent.com/49120272/190858517-ff55b338-aee9-4686-a240-c7ed5be696f0.jpg)
![F1_curve](https://user-images.githubusercontent.com/49120272/190858551-8319c1df-8a5b-4dc6-8730-93407dace8c2.png)
![PR_curve](https://user-images.githubusercontent.com/49120272/190858578-d88c
![R_curve](https://user-images.githubusercontent.com/49120272/190858589-e34e949e-21e7-41c2-a2d7-8810fe2037b0.png)
2e9f-a90c-429b-84e2-d9a662ad4144.png)

![labels_correlogram](https://user-images.githubusercontent.com/49120272/
![P_curve](https://user-images.githubusercontent.com/49120272/190858574-c283fa04-fbe6-4688-aaed-6bf01f23716d.png)
190858565-dab4843e-0d9c-43dc-90b2-1f264df92049.jpg)

![labels](https://user-images.githubusercontent.com/49120272/190858562-172772c3-cc48-455f-9673-d8107abed6b0.jpg)
![val_batch2_pred](https://user-images.githubusercontent.com/49120272/190858618-3bcfbda4-ccac-45f9-ac58-db27909c5e1c.jpg)
![val_batch1_labels](https://user-images.githubusercontent.com/49120272/190858697-6836fce4-737a-4c66-bea6-bd99631e5e3b.jpg)
![val_batch1_pred](https://user-images.githubusercontent.com/49120272/190858699-8ccd6922-da6b-4bc4-b8a0-84df4c1eed18.jpg)

![train_batch2](https://user-imag
![val_batch2_labels](https://user-images.githubusercontent.com/49120272/190858708-d2986cb7-1b11-4c38-b993-9238cdaacf41.jpg)

![val_batch0_pred](https://user-images.g
![val_batch2_pred](https://user-images.githubusercontent.com/49120272/190858714-b5fcd401-1477-4af1-a633-78c576b6ac48.jpg)
ithubusercontent.com/49120272/190858693-56d1497b-fb47-49d6-8c79-5b4bac90f388.jpg)
es.githu
![val_batch0_labels](https://user-images.githubusercontent.com/49120272/190858688-0aad5375-d7b7-4999-a886-e3d6aea75c25.jpg)
busercontent.com/49120272/190858683-f005facc-08dc-4420-ade7-17e0c7b3cbdb.jpg)

--------------------------------------------------------------------
some test results from 10% of the dataset these images not in training set

![Senario_12 083](https://user-images.githubusercontent.com/49120272/190858869-29f6980f-62a8-4373-86f8-b1a3283208e4.jpg)

![Senario_12 083](https://user-images.githubusercontent.com/49120272/190858892-4192bc95-0933-41e8-bf8b-a26171e9d937.jpg)
![t_5 353](https://user-images.githubusercontent.com/49120272/190858896-a7ed985d-1ab7-46c0-861e-4befd2a100b6.jpg)
![12 0009](https://user-images.githubusercontent.com/49120272/190858898-5caea475-be25-452d-846c-06fc3bea7c81.jpg)
![g 084](https://user-images.githubusercontent.com/49120272/190858900-ae64617c-6e06-4f18-97ec-e956519b032f.jpg)
![g_5 375](https://user-images.githubusercontent.com/49120272/190858901-58d054e7-9d8d-47e3-b9ea-fc5522ab81c9.jpg)
![g_8 006](https://user-images.githubusercontent.com/49120272/190858903-4210a5da-a1a5-483d-8086-8dd4885ce417.jpg)
![m_8 012](https://user-images.githubusercontent.com/49120272/190858905-c3cb390a-280c-4a31-af48-8dad5479ca3c.jpg)
![m_scenario_8 215](https://user-images.githubusercontent.com/49120272/190858906-9387f5a3-46a6-4352-9b75-d3fcf4370349.jpg)
![m_Senario_2 447](https://user-images.githubusercontent.com/49120272/190858907-f612e7f4-6d03-41e3-83ed-c3e0887b46ec.jpg)
![ms_Senario_5 552](https://user-images.githubusercontent.com/49120272/190858908-4fe69f7e-db8b-47d8-96ed-b9be2d42ba5d.jpg)
![satu-1 366 jpg](https://user-images.githubusercontent.com/49120272/190858913-ad8d27a7-9cee-4021-95eb-443fece0a81c.jpg)
====================================================
when I try to test the model in real time where I  captured the frames from the webcam the detection result is very bad 0.2 or 0.3 no more and also different from one class to another, for example, the eye_movment was very bad accuracy ?? 
I try to use yolov5n6 but the result still not good
can you help me

_Originally posted by @alkhalisy in https://github.com/ultralytics/yolov5/issues/8022#issuecomment-1250071394_

**Comment by glenn-jocher** [comment]
@alkhalisy 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results. 

Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.

If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.

We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.

## Dataset

- **Images per class.** ≥ 1500 images per class recommended
- **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
- **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
- **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
- **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
- **Label verification.** View `train_batch*.jpg` on train start to verify your labels appear correct, i.e. see [example](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#local-logging) mosaic.
- **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

<a href="https://arxiv.org/abs/1405.0312"><img width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png" alt="COCO Analysis"></a>


## Model Selection

Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models. 

<p align="center"><img width="700" alt="YOLOv5 Models" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png"></p>

- **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. [VOC](https://github.com/ultralytics/yolov5/blob/master/data/VOC.yaml), [VisDrone](https://github.com/ultralytics/yolov5/blob/master/data/VisDrone.yaml), [GlobalWheat](https://github.com/ultralytics/yolov5/blob/master/data/GlobalWheat2020.yaml)). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
```bash
python train.py --data custom.yaml --weights yolov5s.pt
                                             yolov5m.pt
                                             yolov5l.pt
                                             yolov5x.pt
                                             custom_pretrained.pt
```
- **Start from Scratch.** Recommended for large datasets (i.e. [COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [Objects365](https://github.com/ultralytics/yolov5/blob/master/data/Objects365.yaml), [OIv6](https://storage.googleapis.com/openimages/web/index.html)). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
```bash
python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
                                                      yolov5m.yaml
                                                      yolov5l.yaml
                                                      yolov5x.yaml
```


## Training Settings

Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.

- **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
- **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
- **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
- **Hyperparameters.** Default hyperparameters are in [hyp.scratch-low.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).

## Further Reading

If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains: http://karpathy.github.io/2019/04/25/recipe/

Good luck 🍀 and let us know if you have any other questions!

**Comment by alkhalisy** [comment]
> @alkhalisy 👋 Hello! Thanks for asking about improving YOLOv5 🚀 training results.
> 
> Most of the time good results can be obtained with no changes to the models or training settings, **provided your dataset is sufficiently large and well labelled**. If at first you don't get good results, there are steps you might be able to take to improve, but we always recommend users **first train with all default settings** before considering any changes. This helps establish a performance baseline and spot areas for improvement.
> 
> If you have questions about your training results **we recommend you provide the maximum amount of information possible** if you expect a helpful response, including results plots (train losses, val losses, P, R, mAP), PR curve, confusion matrix, training mosaics, test results and dataset statistics images such as labels.png. All of these are located in your `project/name` directory, typically `yolov5/runs/train/exp`.
> 
> We've put together a full guide for users looking to get the best results on their YOLOv5 trainings below.
> 
> ## Dataset
> * **Images per class.** ≥ 1500 images per class recommended
> * **Instances per class.** ≥ 10000 instances (labeled objects) per class recommended
> * **Image variety.** Must be representative of deployed environment. For real-world use cases we recommend images from different times of day, different seasons, different weather, different lighting, different angles, different sources (scraped online, collected locally, different cameras) etc.
> * **Label consistency.** All instances of all classes in all images must be labelled. Partial labelling will not work.
> * **Label accuracy.** Labels must closely enclose each object. No space should exist between an object and it's bounding box. No objects should be missing a label.
> * **Label verification.** View `train_batch*.jpg` on train start to verify your labels appear correct, i.e. see [example](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data#local-logging) mosaic.
> * **Background images.** Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.
> 
> [<img alt="COCO Analysis" width="800" src="https://user-images.githubusercontent.com/26833433/109398377-82b0ac00-78f1-11eb-9c76-cc7820669d0d.png">](https://arxiv.org/abs/1405.0312)
> 
> ## Model Selection
> Larger models like YOLOv5x and [YOLOv5x6](https://github.com/ultralytics/yolov5/releases/tag/v5.0) will produce better results in nearly all cases, but have more parameters, require more CUDA memory to train, and are slower to run. For **mobile** deployments we recommend YOLOv5s/m, for **cloud** deployments we recommend YOLOv5l/x. See our README [table](https://github.com/ultralytics/yolov5#pretrained-checkpoints) for a full comparison of all models.
> 
> <img alt="YOLOv5 Models" width="700" src="https://github.com/ultralytics/yolov5/releases/download/v1.0/model_comparison.png">
> 
> * **Start from Pretrained weights.** Recommended for small to medium sized datasets (i.e. [VOC](https://github.com/ultralytics/yolov5/blob/master/data/VOC.yaml), [VisDrone](https://github.com/ultralytics/yolov5/blob/master/data/VisDrone.yaml), [GlobalWheat](https://github.com/ultralytics/yolov5/blob/master/data/GlobalWheat2020.yaml)). Pass the name of the model to the `--weights` argument. Models download automatically from the [latest YOLOv5 release](https://github.com/ultralytics/yolov5/releases).
> 
> ```shell
> python train.py --data custom.yaml --weights yolov5s.pt
>                                              yolov5m.pt
>                                              yolov5l.pt
>                                              yolov5x.pt
>                                              custom_pretrained.pt
> ```
> 
> * **Start from Scratch.** Recommended for large datasets (i.e. [COCO](https://github.com/ultralytics/yolov5/blob/master/data/coco.yaml), [Objects365](https://github.com/ultralytics/yolov5/blob/master/data/Objects365.yaml), [OIv6](https://storage.googleapis.com/openimages/web/index.html)). Pass the model architecture yaml you are interested in, along with an empty `--weights ''` argument:
> 
> ```shell
> python train.py --data custom.yaml --weights '' --cfg yolov5s.yaml
>                                                       yolov5m.yaml
>                                                       yolov5l.yaml
>                                                       yolov5x.yaml
> ```
> 
> ## Training Settings
> Before modifying anything, **first train with default settings to establish a performance baseline**. A full list of train.py settings can be found in the [train.py](https://github.com/ultralytics/yolov5/blob/master/train.py) argparser.
> 
> * **Epochs.** Start with 300 epochs. If this overfits early then you can reduce epochs. If overfitting does not occur after 300 epochs, train longer, i.e. 600, 1200 etc epochs.
> * **Image size.** COCO trains at native resolution of `--img 640`, though due to the high amount of small objects in the dataset it can benefit from training at higher resolutions such as `--img 1280`. If there are many small objects then custom datasets will benefit from training at native or higher resolution. Best inference results are obtained at the same `--img` as the training was run at, i.e. if you train at `--img 1280` you should also test and detect at `--img 1280`.
> * **Batch size.** Use the largest `--batch-size` that your hardware allows for. Small batch sizes produce poor batchnorm statistics and should be avoided.
> * **Hyperparameters.** Default hyperparameters are in [hyp.scratch-low.yaml](https://github.com/ultralytics/yolov5/blob/master/data/hyps/hyp.scratch-low.yaml). We recommend you train with default hyperparameters first before thinking of modifying any. In general, increasing augmentation hyperparameters will reduce and delay overfitting, allowing for longer trainings and higher final mAP. Reduction in loss component gain hyperparameters like `hyp['obj']` will help reduce overfitting in those specific loss components. For an automated method of optimizing these hyperparameters, see our [Hyperparameter Evolution Tutorial](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution).
> 
> ## Further Reading
> If you'd like to know more a good place to start is Karpathy's 'Recipe for Training Neural Networks', which has great ideas for training that apply broadly across all ML domains: http://karpathy.github.io/2019/04/25/recipe/
> 
> Good luck 🍀 and let us know if you have any other questions!

**Comment by alkhalisy** [comment]
Dear Glenn Jocher Thanks for your response. but did you mean it is a dataset problem, if it is what is the best to solve this problem? why overfitting came early? any manner to drop down some nodes to solve the problem or decrease the conv. layers any suggestions?

**Comment by glenn-jocher** [comment]
@alkhalisy your deployment space and training space must be similar for results in training to generalize to deployment, i.e. collect more images that are similar to what the model will see in deployment.

**Comment by alkhalisy** [comment]
Dear Glenn Jocher thank you very much for clearing your suggested solution.
1- is there any other solution? because as I mentioned before this dataset should be used on online exam apps and in this scenario no fixed deployment environment like any house for any student.
2- I try before to remove all background from all images in the dataset by segmentation techniques. the result images just with person's actions no bg, I thought in this manner make the model focus in the person nor the environment but really the results still poor.
3- if I use grayscale images not RGB  or less color depth images in the dataset, is this may improve accuracy?
4- why training the model just for 4 epochs is the best result while more epoch decrease accuracy in the real world?
5- from the Training analytical data was sent (CM, P,R, MaP) any evidence for overfitting?
many thanks

**Comment by glenn-jocher** [comment]
@alkhalisy 2 is exactly the opposite of what you want. You want lots of variation and backgrounds.

All recommendations are already posted above in https://github.com/ultralytics/yolov5/issues/9456#issuecomment-1250122216 including using larger models.

**Comment by alkhalisy** [comment]
Thank you very much dear for you response and  your time

**Comment by alkhalisy** [comment]
Dear Glenn Jocher  how are you I hope you fine. PLS I need To Remove the small and Median objects Detection Layers  0f yolov5 , I need the model just detect large object its suitable for my problems I working on it  .  how can I do That exactly PLS what Steps can I do in  the Configuration File and Which File Exactly please can you explain in Details or steps. many thanks

**Comment by alkhalisy** [comment]
Dear Glenn Jocher  how are you I hope you fine. PLS I need To Remove the small and Median objects Detection Layers  0f yolov5 , I need the model just detect large object its suitable for my problems I working on it  .  how can I do That exactly PLS what Steps can I do in  the Configuration File and Which File Exactly please can you explain in Details or steps. many thanks

**Comment by alkhalisy** [comment]
Dear Glenn Jocher How are you? I hope you are fine. PLS, I need to remove
yolov5's small and medium object detection layers so that the model can
only detect large objects. It's suitable for the problems I work on
with it. How can I do that exactly? What steps can I take in the
configuration file, and which file exactly? Can you please explain in
detail or in steps? many thanks

-------------------------------------------------------------
Muhanad  Abdul Elah Alkhalisy
*MSc Software **Engineering*
University of Information Technology and Communications
Mobile: +96407718662757
Email: ***@***.***
----------------------------------------------------------------

**Comment by alkhalisy** [comment]
Dear Glenn Jocher How are you? I hope you are fine. PLS, I need to remove yolov5's small and medium object detection layers so that the model can only detect large objects. It's suitable for the problems I work on with it. How can I do that exactly? What steps can I take in the configuration file, and which file exactly? Can you please explain in detail or in steps? many thanks

**Comment by alkhalisy** [comment]
Dear Glenn Jocher How are you? I hope you are fine. PLS, I need to remove yolov5's small and medium object detection layers so that the model can only detect large objects. It's suitable for the problems I work on with it. How can I do that exactly? What steps can I take in the configuration file, and which file exactly? Can you please explain in detail or in steps? many thanks

**Comment by glenn-jocher** [comment]
@alkhalisy you can remove any inputs you want from Detect in your yaml, and then `python train.py --cfg new.yaml`. P5 is the largest output layer.
https://github.com/ultralytics/yolov5/blob/f8539a680041a9f4fbcc4fcdd8f540724da453af/models/yolov5s.yaml#L47

**Comment by alkhalisy** [comment]
> @alkhalisy you can remove any inputs you want from Detect in your yaml, and then `python train.py --cfg new.yaml`. P5 is the largest output layer.
> 
> https://github.com/ultralytics/yolov5/blob/f8539a680041a9f4fbcc4fcdd8f540724da453af/models/yolov5s.yaml#L47

Thank you very much for you response but pls I need also to Decrease FLOPS  so What Other Structure can I removed related by small and medium object in Head or backbone or other parts? can you help me by that. is the yaml file should look as bellow for delete small and medium object detect   

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ] 

or  I can  remove 20 (P4/16-medium) and  # 17 (P3/8-small) to decrease a little in FLOPS? ( I use the n model)
many thanks

**Comment by alkhalisy** [comment]
> @alkhalisy you can remove any inputs you want from Detect in your yaml, and then `python train.py --cfg new.yaml`. P5 is the largest output layer.
> 
> https://github.com/ultralytics/yolov5/blob/f8539a680041a9f4fbcc4fcdd8f540724da453af/models/yolov5s.yaml#L47

Thank you very much for you response but pls I need also to minimize a FLOPS  so What Other Structure can I removed related by small and medium object in Head or backbone or other parts? can you help me by that. is the yaml file should look as bellow for delete small and medium object detect   

   **[[23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]** 

or  I can  remove 20 (P4/16-medium) and  # 17 (P3/8-small) to decrease a little in FLOPS? ( I use the s model)
many thanks .

PLS where the 17 or p3 and 20 or p4 detection layers in the graph bellow, or how the graph look after delete 17 and 20 , and did you have a details graph or same thing let us understand what each part of yolov5 structurers  do in more details 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/49120272/208263844-e82dab84-593d-431c-83ef-3c380ec9aa23.png">

**Comment by alkhalisy** [comment]
> @alkhalisy you can remove any inputs you want from Detect in your yaml, and then `python train.py --cfg new.yaml`. P5 is the largest output layer.
> 
> https://github.com/ultralytics/yolov5/blob/f8539a680041a9f4fbcc4fcdd8f540724da453af/models/yolov5s.yaml#L47

Dear Sir , I use this Yaml file to delete the small and medium object detection but when try to train the model the error happen ??
# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 3, C3, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   **[[23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)**
  ]
error
<img width="694" alt="image" src="https://user-images.githubusercontent.com/49120272/210265376-bb826f83-f55e-49f3-b6d2-acf2315c36b6.png">

**Comment by alkhalisy** [comment]
Dear I try to remove P3 and P5 detection and still tp P4 and I do required change in the Neck and every thing become well and work . When I try to delete C5 from feature Extraction Backbone and do modification in the neck the error happen 
"File "/content/yolov5/models/yolo.py", line 334, in <listcomp>
    args.append([ch[x] for x in f])
IndexError: list index out of range"
why any I can not do any change to the backbone???

nc: 80  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [30,61, 62,45, 59,119]  # P4/16
  


backbone:
  
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 3, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 3, C3, [512]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]


head:
  [
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [[20], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

**Comment by glenn-jocher** [comment]
@alkhalisy Your modification to the backbone seems correct. Since you've removed C5 from the backbone, ensure that your head configuration caters to the changes. The indices in the head configuration should reflect the new backbone architecture. Please confirm if the head section has been updated to match the modifications in the backbone.
