### ISSUE TITLE
Could not run with cutomizing configuration outside the code directory

### ISSUE THREAD

**Issue by fireinice** [ultralytics/yolov5#9519]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

by check dataset it will resolve the relative path provided by the configuration yaml to the absolute path, and then it will report dataset not found if we use relative path in yaml and try to run outside where the train.py/val.py presents.
it seems related to the PR https://github.com/ultralytics/yolov5/pull/6489

have to write absolute path in the yaml which obstacle when move the data from machine to machine or user to user.

the error paste below, I wrote a val.py in /home/fireinice/work/train_script/ to wrap the val.py by import main method in /home/fireinice/yolov5/ where also     all other yolov5 codes located.

```
Dataset not found ⚠️, missing paths ['/home/fireinice/yolov5/train_data/images/val']
Traceback (most recent call last):
  File "/home/fireinice/work/train_script/val.py", line 426, in <module>
    main()
  File "/home/fireinice/work/train_script/val.py", line 400, in main
    run(**vars(opt))
  File "/home/fireinice/.virtualenvs/myvirtual/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/fireinice/yolov5/val.py", line 167, in run
    data = check_dataset(data)  # check
  File "/home/fireinice/yolov5/utils/general.py", line 492, in check_dataset
    raise Exception(emojis('Dataset not found ❌'))
Exception: Dataset not found ❌
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fireinice 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by fireinice** [comment]
closed

**Comment by glenn-jocher** [comment]
@fireinice great, thank you for letting me know! If you have any other questions or encounter any issues in the future, please don't hesitate to open a new issue. We're here to help! 😊
