### ISSUE TITLE
load network

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#9599]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello!

I would need to run yolo by passing the network's file s content, instead of the path-to-the-file. something along the lines of this:

```
            self.network = "C:\myfile.pt"
            with open(self.network, "rb") as file:
                file_data = file.read()
            run(weights=file_data)
```

instead of 

```           
            self.network = "C:\myfile.pt"
            run(weights=self.network)
```

Is this possible?

Reason for this is, that I want to have the network encrypted, and once it is decrypted it is loaded in memory like above. I do not want to save the decrypted file to the drive prior to loading it.

**Comment by glenn-jocher** [comment]
@tanzerlana we use torch.load() under the hood to load models from local storage. If you'd want to pass file contents rather than a file location you're probably going to need to customize your code.
https://pytorch.org/docs/stable/generated/torch.load.html

The specific file in YOLOv5 that loads all models is here. `weights` is a local filename or a URL filename.
https://github.com/ultralytics/yolov5/blob/bd9c0c42aee090b373db51c7393c972c26ed9913/models/experimental.py#L73-L111
