### ISSUE TITLE
Train Batch seems to skip some annotations

### ISSUE THREAD

**Issue by HCL-91** [ultralytics/yolov5#9608]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi, 
I am using a Figure QA dataset provided by Microsoft to train Yolov5.
After I started to train the model, I've looked into the ./runs/train folder to check samples of the train batch.

When I checked images of train batch (train_batch0, train_batch1, ... etc.)
I noticed that some of the images are missing labels.

<img width="307" alt="yolov5_inquiry" src="https://user-images.githubusercontent.com/67674024/192344820-7fe62c86-c294-4ca3-8f24-7c2c53b9204c.png">

As you can see none of the horizontal bars are marked on the image above.

I double checked that the label files included all of the annotations for each image, yet they don't show on the train batch images.

Does this mean that the model is not being trained on the full set of labels?

**Comment by glenn-jocher** [comment]
@HCL-91 train*.jpg images show the actual data your model is trained on, so if they are missing annotations then the model is not training on those. 

It's possible your labels may have been removed due to not passing candidate cuts. Candidate label criteria is here. You could relax the constraints on aspect ratio etc. and see if your labels appear in your mosaics.
https://github.com/ultralytics/yolov5/blob/6b2c9d1d0f5f9acad86ff9e7043f094a071aa6fe/utils/augmentations.py#L299-L305

**Comment by HCL-91** [comment]
Thanks Glenn!
I increased the ar_thr and set area_thr = 0.
Now all the labels are being detected and properly shown in mosaics.

**Comment by glenn-jocher** [comment]
@HCL-91 hmm interesting. Do you know which argument was responsible for removing your labels? 

Do you think we should update the default values?
