### ISSUE TITLE
onnx export exits without error and no onnx file is generated

### ISSUE THREAD

**Issue by dk-teknologisk-mlnn** [ultralytics/yolov5#9630]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

onnx export exits without error and no onnx file is generated. I have torch 1.12.1 and onnx 1.10.1.

 I added a print after torch.onnx.export and this line of code is never reached.

ONNX: starting export with onnx 1.10.1...
Export to hudscanner\prikker\weights\best.onnx opset 12 output names ['output0'] im shape torch.Size([1, 3, 1280, 1280]) dynamic False

(pytorch) C:\Python\
-----

    torch.onnx.export(
        model.cpu() if dynamic else model,  # --dynamic only compatible with cpu
        im.cpu() if dynamic else im,
        f,
        verbose=True,
        opset_version=opset,
        do_constant_folding=True,
        input_names=['images'],
        output_names=output_names,
        dynamic_axes=dynamic or None)
    print("should be done")

**Comment by sequoiagrove** [comment]
for reference, onnx export works with the older Yolov5.0 repo in the same environment.

**Comment by sequoiagrove** [comment]
I found that the onnx export succeeds if I wait with "import onnx" (and of course also wsait with LOGGER the version) until after the torch.onnx.export command.

**Comment by Wantcha** [comment]
> I found that the onnx export succeeds if I wait with "import onnx" (and of course also wsait with LOGGER the version) until after the torch.onnx.export command.

What does this mean? I'm having the same issue and I genuinely don't understand what your message refers to

**Comment by sequoiagrove** [comment]
in export.py, line 135 says "import onnx".
move that to line 159.
comment out line 137 to avoid error.

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
