### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ydyazeed** [ultralytics/yolov5#9644]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

cannot import name 'scale_coords' from 'utils.general' (/Users/yazeedshamsudeen/.cache/torch/hub/ultralytics_yolov5_master/utils/general.py)

I am getting this error while I try to import functions from detect.py. Could you help me solve this.

**Comment by MartinPedersenpp** [comment]
I think you are using an old or unofficial release, because there is no function scale_coords imported from detect.py in the master release.

**Comment by glenn-jocher** [comment]
@MartinPedersenpp hi there! It seems like the error you're encountering might be due to the usage of an old or unofficial release. The 'scale_coords' function you mentioned isn't part of the master release. Make sure you are using the latest official release from the YOLOv5 repository. If you need further assistance, feel free to ask!
