### ISSUE TITLE
How to print the detected class in Live frame?

### ISSUE THREAD

**Issue by thesaqibmumtaz** [ultralytics/yolov5#9647]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi,
I using webcam as source to get detection on real time and I want to print the detected class on the live frame!
is there any possible way to do this?
TIA.

**Comment by popcornkiller1088** [comment]
You can achieve this in many ways, one of the ways is by OpenCV:

`predict_image = model(image)
im_rgb = cv2.cvtColor(predict_image.imgs[0], cv2.COLOR_BGR2RGB) # Because of OpenCV reading images as BGR
cv2_imshow(im_rgb)`
you have to do more searching like, see how people render image in python in realtime, this is out of the scope for Yolo

**Comment by glenn-jocher** [comment]
@popcornkiller1088 hi there! You can print the detected class on the live frame using OpenCV. After making predictions with YOLOv5, you can use OpenCV to display the image and overlay the detected class. You can find more information on rendering images in real-time using Python from various resources. Good luck!

**Comment by thesaqibmumtaz** [comment]
> @popcornkiller1088 hi there! You can print the detected class on the live frame using OpenCV. After making predictions with YOLOv5, you can use OpenCV to display the image and overlay the detected class. You can find more information on rendering images in real-time using Python from various resources. Good luck!

Thanks.
