### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sadiyaafreen95** [ultralytics/yolov5#9651]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

even if the dataset is present in the dataset folder it gives filenotfound error for images and video , it gives the correct path but wont show data set ..

PS C:\Users\syed\Desktop\yolov5> python detect.py --source bus.jpg
detect: weights=yolov5s.pt, source=bus.jpg, data=data\coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5  2022-9-27 Python-3.8.8 torch-1.11.0+cpu CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 258, in <module>
    main(opt)
  File "detect.py", line 253, in main
    run(**vars(opt))
  File "C:\Users\syed\anaconda3\anacondanew\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 108, in run
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
  File "C:\Users\syed\Desktop\yolov5\utils\dataloaders.py", line 251, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: bus.jpg does not exist

**Comment by glenn-jocher** [comment]
@Sadiyaafreen95 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. 

Your error message is very clear, you must point to a valid file that exists.
FileNotFoundError: bus.jpg does not exist

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Sadiyaafreen95** [comment]
Sir I haven't done any changes in ultrlytics code,  but still I am not
getting the output. Images and vedio are unable to display, it gives me
image/vedio does not exist error ,but the path is correct. Please sir help
me with this .tomorrow I am having my final exam on this project .

**Comment by Sadiyaafreen95** [comment]
Sir , please check the code once again ..I am even finding error in the
execution of directory and glob type inputs .please sir , I am waiting for
your reply.
