### ISSUE TITLE
If i use this repo to train a yolov5 model on a custom dataset, is my model GPL and does my code become GPL?

### ISSUE THREAD

**Issue by pfeatherstone** [ultralytics/yolov5#967]
## ❔Question
If i use this repo to train a yolov5 model on a custom dataset, is my model GPL ? If i export the model to ONNX, then use some other repository to infer the model, is my code GPL because i'm using the model weights?

**Comment by glenn-jocher** [comment]
@pfeatherstone if you modify this repo in your work then the result should be maintained under the same license and available open source. 

If you simply use this repo without altering it, you own any resulting products (i.e. trained models) and are free to assign them any license you wish as I understand it.

**Comment by pfeatherstone** [comment]
Ok thanks. Had a legal debate at work today.

**Comment by glenn-jocher** [comment]
I understand the confusion, I'm confused myself. I contacted an attorney from https://www.softwarefreedom.org/ a month ago on the advice of a colleague, but an attorney there said that since Ultralytics was not a non-profit we would fall under their normal pricing plan of $1000 per hour for consultations and with help developing a licensing strategy. Naturally we neglected to follow through with them, and to date we still are not certain on our best licensing strategy.

The intention with the GPL 3.0. license is to prevent large players from appropriating the solution for their own paid products. This prevents for example Amazon from integrating YOLOv5 in their own AWS offerings, and then turning around and charging customers for those products via paid APIs etc., which I think we can all agree is wrong on every level. Unfortunately this is very common practice though, see https://unicorn.computer/aws-launches-ripoff-as-a-service

Our challenge is striking the right balance between adoption and usability while preventing scenarios like the one above. It can be a challenging path to find at times.

**Comment by Ownmarc** [comment]
> @pfeatherstone if you modify this repo in your work then the result should be maintained under the same license and available open source.
> 
> If you simply use this repo without altering it, you own any resulting products (i.e. trained models) and are free to assign them any license you wish as I understand it.

@glenn-jocher  I think this is wrong. Anything that touches/uses GPLv3 has to become GPLv3 if its distributed. Distributed means that the code is packaged/compiled or used in an app that is distributed. An api where the code stays behind this api would not be cosidered "distributed". AWS could offer Yolov5 as a service and make people pay for it as long as they do not "distribute" the code and that it remains on their servers. They created AGLP to cover for that.
