### ISSUE TITLE
Output video longer or shorter than the input video

### ISSUE THREAD

**Issue by aliaminibagh** [ultralytics/yolov5#9756]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When I use my custom best.pt as input of detect.py for detection on a video, the duration of the output video is more or less than the original file, and it does not actually output a live video. what is the reason?
My input video, for example, is about 3 minutes, but the output video is greater than 7 minutes.

When I use the same image size used in the train for inference(640), the length of the output video increases. And vice versa, the length of the output video is reduced(1280).

**Comment by glenn-jocher** [comment]
@aliaminibagh 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by dlrjsgh367** [comment]
저도 궁금합니다

**Comment by JerickoDG** [comment]
I am also experiencing this issue as of the moment and here are the details: https://github.com/ultralytics/yolov5/issues/12372

**Comment by glenn-jocher** [comment]
@JerickoDG thank you for bringing this to our attention. Please ensure your Python environment is up-to-date and check that your YOLOv5 code is current with the GitHub master branch. We recommend providing a minimal reproducible example as outlined in the issue template. This will assist us in diagnosing and resolving the issue promptly.
