### ISSUE TITLE
May I ask how to obtain the pixel coordinates of mask, and get the point coordinates of the segmentation box through --save_txt

### ISSUE THREAD

**Issue by WANGCHAO1996** [ultralytics/yolov5#9767]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

May I ask how to obtain the pixel coordinates of mask, and get the point coordinates of the segmentation box through --save_![image](https://user-images.githubusercontent.com/51087601/195060189-996315ef-a3c1-44f5-9ee9-cade31dbab1a.png)

**Comment by glenn-jocher** [comment]
@WANGCHAO1996 `python segment/predict.py --save-txt` saves segmentation masks. The box you can get yourself as it's just the outer limits of the segments.

**Comment by vladoossss** [comment]
When i use `--save-txt` i have next error:

```
in masks2segments
c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
ValueError: attempt to get argmax of an empty sequence
```

**Comment by glenn-jocher** [comment]
@vladoossss works for me:
<img width="1517" alt="Screenshot 2022-10-11 at 14 40 34" src="https://user-images.githubusercontent.com/26833433/195093195-b7f09216-42e7-4a64-8ff9-5b545c67961f.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by vladoossss** [comment]
> @vladoossss works for me: <img alt="Screenshot 2022-10-11 at 14 40 34" width="1517" src="https://user-images.githubusercontent.com/26833433/195093195-b7f09216-42e7-4a64-8ff9-5b545c67961f.png">
> 
> We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
> * ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃

Okay, thank you. Also when i run `python segment/val.py --save-json` i have next json without segmentation masks:
![image](https://user-images.githubusercontent.com/71467601/195094970-ea10425c-8576-4ec3-a1fc-3fc54a412c39.png)

**Comment by glenn-jocher** [comment]
val.py jsons will not save segmentation masks, only boxes.

**Comment by WANGCHAO1996** [comment]
> @WANGCHAO1996 `python segment/predict.py --save-txt` saves segmentation masks. The box you can get yourself as it's just the outer limits of the segments.
Hello, why do you see segmented data in the saved result diagram, but the data points in the saved label do not include this part? What is the reason?
![image](https://user-images.githubusercontent.com/51087601/195257259-b44a9c6b-0369-4d58-bcc6-603c48c907a3.png)

![image](https://user-images.githubusercontent.com/51087601/195257301-d5f6163c-de47-4cb0-aa52-adda1529b037.png)

**Comment by WANGCHAO1996** [comment]
```
def masks2segments(masks, strategy='largest'):
    # Convert masks(n,160,160) into segments(n,xy)
    segments = []
    for x in masks.int().cpu().numpy().astype('uint8'):
        c = cv2.findContours(x, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0]
        if strategy == 'concat':  # concatenate all segments
            c = np.concatenate([x.reshape(-1, 2) for x in c])
        elif strategy == 'largest':  # select largest segment
            c = np.array(c[np.array([len(x) for x in c]).argmax()]).reshape(-1, 2)
        segments.append(c.astype('float32'))
    return segments
```
Is it because this setting only returns the largest portion of the split

> @WANGCHAO1996 `python segment/predict.py --save-txt` saves segmentation masks. The box you can get yourself as it's just the outer limits of the segments.

**Comment by Kr-Sheshank** [comment]
![Screenshot from 2023-06-08 16-03-10](https://github.com/ultralytics/yolov5/assets/115135568/7930e65b-bbda-4151-96bf-ea8eaaa962a5)
I used --save-txt to generate the bounding box coordinate in yolov8, but it is not working; in the case of yolov5, only it works.
How to generate the coordinates in yolov8?
Please help

**Comment by glenn-jocher** [comment]
@Kr-Sheshank yolov8 is not a version that we maintain. For YOLOv5 you can refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/) for guidance.
