### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by lchenhi** [ultralytics/yolov5#9786]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Transferred 362/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
Optimizer groups: 62 .bias, 62 conv.weight, 59 other
train: Scanning 'MyData\labels\train2017.cache' images and labels... 118287 found, 0 missing, 1021 empty, 4 corrupted: 100%|██████████| 118287/118287 [00:00<?, ?it/s]
val: Scanning 'MyData\labels\val2017.cache' images and labels... 5000 found, 0 missing, 48 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
Plotting labels... 
Traceback (most recent call last):
  File "D:\yolov5-5.0\yolov5-5.0\train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "D:\yolov5-5.0\yolov5-5.0\train.py", line 210, in train
    plot_labels(labels, names, save_dir, loggers)
  File "D:\yolov5-5.0\yolov5-5.0\utils\plots.py", line 281, in plot_labels
    sns.pairplot(x, corner=True, diag_kind='auto', kind='hist', diag_kws=dict(bins=50), plot_kws=dict(pmax=0.9))
  File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\axisgrid.py", line 2144, in pairplot
    grid.map_diag(histplot, **diag_kws)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\axisgrid.py", line 1507, in map_diag
    func(x=vector, **plot_kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\distributions.py", line 1418, in histplot
    color = _default_color(method, hue, color, kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\utils.py", line 139, in _default_color
    scout, = method([np.nan], [np.nan], **kws)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\axes\_axes.py", line 2373, in bar
    width = self._convert_dx(width, x0, x, self.convert_xunits)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\axes\_axes.py", line 2182, in _convert_dx
    x0 = cbook._safe_first_finite(x0)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\cbook\__init__.py", line 1749, in _safe_first_finite
    return next(val for val in obj if safe_isfinite(val))
StopIteration

Process finished with exit code 1

### Additional

this exception shows up when I training coco2017, and all the parameters are default.

**Comment by glenn-jocher** [comment]
@lchenhi 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by L-xn** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.
> 
> ### Question
> Transferred 362/362 items from yolov5s.pt Scaled weight_decay = 0.0005 Optimizer groups: 62 .bias, 62 conv.weight, 59 other train: Scanning 'MyData\labels\train2017.cache' images and labels... 118287 found, 0 missing, 1021 empty, 4 corrupted: 100%|██████████| 118287/118287 [00:00<?, ?it/s] val: Scanning 'MyData\labels\val2017.cache' images and labels... 5000 found, 0 missing, 48 empty, 0 corrupted: 100%|██████████| 5000/5000 [00:00<?, ?it/s] Plotting labels... Traceback (most recent call last): File "D:\yolov5-5.0\yolov5-5.0\train.py", line 543, in train(hyp, opt, device, tb_writer) File "D:\yolov5-5.0\yolov5-5.0\train.py", line 210, in train plot_labels(labels, names, save_dir, loggers) File "D:\yolov5-5.0\yolov5-5.0\utils\plots.py", line 281, in plot_labels sns.pairplot(x, corner=True, diag_kind='auto', kind='hist', diag_kws=dict(bins=50), plot_kws=dict(pmax=0.9)) File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\axisgrid.py", line 2144, in pairplot grid.map_diag(histplot, **diag_kws) File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\axisgrid.py", line 1507, in map_diag func(x=vector, **plot_kwargs) File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\distributions.py", line 1418, in histplot color = _default_color(method, hue, color, kwargs) File "D:\anaconda3\envs\pytorch\lib\site-packages\seaborn\utils.py", line 139, in _default_color scout, = method([np.nan], [np.nan], **kws) File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib__init__.py", line 1423, in inner return func(ax, *map(sanitize_sequence, args), **kwargs) File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\axes_axes.py", line 2373, in bar width = self._convert_dx(width, x0, x, self.convert_xunits) File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\axes_axes.py", line 2182, in _convert_dx x0 = cbook._safe_first_finite(x0) File "D:\anaconda3\envs\pytorch\lib\site-packages\matplotlib\cbook__init__.py", line 1749, in _safe_first_finite return next(val for val in obj if safe_isfinite(val)) StopIteration
> 
> Process finished with exit code 1
> 
> ### Additional
> this exception shows up when I training coco2017, and all the parameters are default.

Hello!I had no problems running on Windows 10, but I had problems running on ubuntu22.04.I don't know what to do about it!

**Comment by Summer-God** [comment]
I have the same problem, using v5-6.0 code, StopIteration occurs.

**Comment by Summer-God** [comment]
I also have the same problem on win10. I am using code v5-6.0, and StopIteration occurs.

**Comment by vvsotnikov** [comment]
Hi! This is a bug in matplotlib 3.6.1, downgrading to 3.5.0 fixed the problem for me https://github.com/matplotlib/matplotlib/issues/24127

**Comment by glenn-jocher** [comment]
@vvsotnikov thanks for sharing your solution with the community! We appreciate your contribution. If anyone encounters a similar issue, they can refer to your workaround for resolving the problem. If you have any further questions or need assistance with anything else, feel free to ask!
