### ISSUE TITLE
Yolov5 initialization time.

### ISSUE THREAD

**Issue by manish33scss** [ultralytics/yolov5#9796]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I have converted using export.py pt -> engine, inference speed is improved but initialization is taking almost 45 seconds. What could be the problem ? 
Using jetson nano 4gb for inference. 
here's the link for reference : https://www.youtube.com/shorts/9g-P1vc8114

**Comment by glenn-jocher** [comment]
@manish33scss that is pretty slow. I'd recommend loading your YOLOv5 TensorRT model with PyTorch Hub. 

YOLOv5 🚀 [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) models allow for simple model loading and inference in a pure python environment without using `detect.py`. This allows you to leave the model loaded in the workspace rather than loading it every time you want to run inference like detect.py does.

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://docs.ultralytics.com/yolov5/tutorials/model_export) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by manish33scss** [comment]
Yes loading in the same manner,  loading .pt is almost instantaneously but inference is 120ms+. Any other approach that i can follow?

**Comment by glenn-jocher** [comment]
@manish33scss I didn't say load a PyTorch model I said load your TensorRT model.

**Comment by manish33scss** [comment]
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', 'my_weight.engine')  



Cap= cv2.VideoCapture(0)
While true:
           results = model(im)


           results.print()  
           results.pandas().xyxy[0] 



Like this !!

**Comment by manish33scss** [comment]
i kinda saved 20 seconds here. had to drop `model = torch.hub.load('ultralytics/yolov5', 'yolov5s')` this approach.

**Comment by glenn-jocher** [comment]
@manish33scss glad to hear you saved time! The method you used is a valid approach for loading the YOLOv5 TensorRT model directly.

If you have any further questions or need assistance, feel free to ask. Keep up the great work!
