### ISSUE TITLE
Training failed, use default configuration

### ISSUE THREAD

**Issue by athrunsunny** [ultralytics/yolov5#9823]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training, Validation

### Bug

Training failed, use default configuration
 Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      0/299         0G    0.04761    0.07293    0.02661         57        640: 100%|██████████| 32/32 [01:31<00:00,  2.84s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/16 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "G:/backup/project/yolofamily/yolov5/train.py", line 632, in <module>
    main(opt)
  File "G:/backup/project/yolofamily/yolov5/train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "G:/backup/project/yolofamily/yolov5/train.py", line 349, in train
    results, maps, _ = validate.run(data_dict,
  File "E:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "G:\backup\project\yolofamily\yolov5\val.py", line 213, in run
    loss += compute_loss(train_out, targets)[1]  # box, obj, cls
  File "G:\backup\project\yolofamily\yolov5\utils\loss.py", line 163, in __call__
    obji = self.BCEobj(pi[..., 4], tobj)
  File "E:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\modules\loss.py", line 713, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "E:\ProgramData\Anaconda3\envs\yolov5\lib\site-packages\torch\nn\functional.py", line 2960, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

However, val.py can be used separately
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
val: Scanning 'G:\backup\project\yolofamily\datasets\coco128\labels\train2017.cache' images and labels... 128 found, 0 missing, 2 empty, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 4/4 [00:25<00:00,  6.29s/it]
                   all        128        929      0.719      0.625      0.714      0.475
Speed: 2.2ms pre-process, 184.3ms inference, 5.5ms NMS per image at shape (32, 3, 640, 640)
Results saved to runs\val\exp2

### Environment

torch                     1.9.0+cpu
torchaudio                0.9.0
torchvision               0.10.0+cpu

OS ：windows
python：3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@athrunsunny latest torch with Windows training is part of our daily CI and this works without any errors:
https://github.com/ultralytics/yolov5/actions/runs/3261518070

**Comment by athrunsunny** [comment]
I'll try another version of torch

**Comment by mrshengzyzy** [comment]
same issue

```
torch                     1.12.1                   
torchaudio            0.12.1                 
torchvision            0.13.1 
OS ：macos
python：3.9
```

**Comment by athrunsunny** [comment]
@mrshengzyzy Using low version of torch (1.8 or 1.7)

**Comment by glenn-jocher** [comment]
@athrunsunny 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by sandeepwadhwa-ai** [comment]
Similar Issue. I have not changed the default code in any manner. After First epoch just before entering second epoch, this error occurs. Output is attached:-

Starting training for 25 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       0/24         0G     0.1227    0.04428     0.0614        203        640:  12%|█▏        | 32/272 [38:58<10:34:09, 158.54s/it]
       0/24         0G    0.07824    0.04504    0.03094        118        640: 100%|██████████| 272/272 [4:44:18<00:00, 62.71s/it]    
                 Class     Images  Instances          P          R      mAP50   mAP50-95:   0%|          | 0/70 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 634, in <module>
    main(opt)
  File "train.py", line 528, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 351, in train
    results, maps, _ = validate.run(data_dict,
  File "/yolov5/venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/yolov5/val.py", line 213, in run
    loss += compute_loss(train_out, targets)[1]  # box, obj, cls
  File "/yolov5/utils/loss.py", line 163, in __call__
    obji = self.BCEobj(pi[..., 4], tobj)
  File "/yolov5/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/yolov5/venv/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 713, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/yolov5/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2960, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.

**Comment by glenn-jocher** [comment]
@sandeepwadhwa-ai thanks for reaching out with this issue. It looks like you are encountering a runtime error related to an inplace update to an inference tensor outside InferenceMode. This has been known to occur when using certain combinations of PyTorch and YOLOv5. 

It's recommended to first ensure that you are using the latest version of YOLOv5 and PyTorch to see if the issue has already been addressed. If the issue persists, you can try using a different version of PyTorch, such as the one suggested by another user (e.g., 1.8 or 1.7). 

If the problem continues, please consider providing a minimal, reproducible example with the necessary steps to replicate the issue. This will greatly assist us in diagnosing and addressing the problem effectively.

Thank you for your understanding and cooperation!
