### ISSUE TITLE
WARNING  Environment does not support cv2.imshow() or PIL Image.show()

### ISSUE THREAD

**Issue by aleksandr-sokolov** [ultralytics/yolov5#9844]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

When trying to run the "python detect.py --source 0" script I get WARNING Environment does not support cv2.imshow() or PIL Image.show(). The script runs, but I don't get a window with a view of the real time object detection work.

Has anyone experienced this and what solutions could you advise me on?

My environment:

- YOLOv5 torch-1.12.1+cu116 CUDA:0 (GeForce GTX 1050, 4096MiB)
- Python-3.10.8
- OS: Windows 10

![screenshot](https://user-images.githubusercontent.com/52084888/196455113-083397c4-50c5-4c94-af9a-457268117db6.PNG)

Thank you in advance

Alex

**Comment by glenn-jocher** [comment]
@aleksandr-sokolov thanks for the bug report! I'm able to reproduce, I'll investigate a fix.

<img width="1535" alt="Screenshot 2022-10-18 at 21 57 53" src="https://user-images.githubusercontent.com/26833433/196531391-320f8357-7f6c-49e3-85f2-eb022c086035.png">

**Comment by glenn-jocher** [comment]
@aleksandr-sokolov good news 😃! Your original issue may now be fixed ✅ in PR #9847. 

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by aleksandr-sokolov** [comment]
@glenn-jocher thank you so much for the quick response and for fixing this issue. Everything is working perfectly now! 
You are the best!

**Comment by glenn-jocher** [comment]
@aleksandr-sokolov great!

**Comment by mlongoria1** [comment]
Hello, I am very new to yolov5 and have been experimenting for the past week or so. This project worked previously and then yesterday or the day before I cloned the repo again and it showed the symptoms discussed here on this issue. I will update the code with git pull to get the changes and give it a try.

But, I just wanted to say, for me(being a newbie) I never would have seen the WARNING text. It shows up for a short while during startup and then disappears off the screen while the source is set to webcam or ipcam with a URL. 

Because of this, I was wondering if you could implement a WARNING that is in yellow font color so it is more noticeable for newbies and pros alike. Or if it would be possible to add the WARNING to show up in the LOGGER output maybe every 10,15, or 20 lines or so which ever seems more appropriate? This way as the logger is being displayed "live" and people will realize there is an issue/warning with the current run of the program?

During the streaming of video from ipcam I would never have seen this warning easily, all I would see is the endless lines of logger info that keeps displaying until I shut down the python script.

Here is a sample of color-coded output and the lines where the warning could show up every 10 lines or so.

![FDuxBxui3f](https://user-images.githubusercontent.com/38320817/196712651-ad8d64a7-0964-4b31-bf89-b1de6011c26f.png)

Thank you

**Comment by glenn-jocher** [comment]
@mlongoria1 thanks for the feedback!

**Comment by nilanshu24** [comment]
@glenn-jocher the issue stays the same with me, can someone help?
I'm getting the same error that @aleksandr-sokolov mentioned. It has not been resolved yet i tried to clone the repository again.

**Comment by scraus** [comment]
Hello, @glenn-jocher! I also got the same error @aleksandr-sokolov mentioned though I have cloned the recent yolov5 version already...

**Comment by glenn-jocher** [comment]
@scraus @patricia-olivera Thanks for reaching out. We appreciate your patience as we work to resolve this issue. We'll investigate and update you as soon as possible.

**Comment by Ahmet-Ruchan** [comment]
"I was experiencing the same issue. I found the solution on this link. You can go and solve your problem there too."

[https://stackoverflow.com/questions/50783177/opencv-the-function-is-not-implemented-rebuild-the-library-with-windows](url)

**Comment by glenn-jocher** [comment]
@Ahmet-Ruchan i'm glad to hear you found a solution that worked for you. However, please note that we generally recommend referring to our official documentation for guidance on using YOLOv5 to ensure compatibility and up-to-date information. If you encounter any further issues or have questions, feel free to reach out here or check our documentation at the Ultralytics Docs. Happy detecting! 🚀
