### ISSUE TITLE
How can I save the best weight in each training

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9858]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, how can I save the best weight in each training,  I use --nosave to prevent too many weights but only save the last weights. How could I save both best and last weight in each training? 

I also find that using a weight.pt , here I call weight1, the detection look OK, but after I use next training weight, here I call weight2.pt, which is based on weight1,  python train.py --weights weight1.pt, this command will generate weight2.pt,  the detection rate decrease significantly if I use weight2.pt. I know there is a fluctuation,  but this kind of fluctuation is too large. Is there a way to prevent this to make the weight more consistent?

**Comment by glenn-jocher** [comment]
best.pt and last.pt are saved by default when training, nothing is needed, just train normaly:

```
python train.py 
```

**Comment by frabob2017** [comment]
I do not see it in my folder.  Sometimes, I saw it.  But most of time, I do not see. It makes me confused. 

![image](https://user-images.githubusercontent.com/57141860/196822549-dd12e86b-cea9-4071-9368-843074cd5d21.png)

**Comment by glenn-jocher** [comment]
@frabob2017 last.pt is created by every training automatically unless you use --nosave argument.

**Comment by frabob2017** [comment]
Yes, but I do not see best.pt after I run command.  Sometimes, I see it but most of time, I do not see it.  It is strange.

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
