### ISSUE TITLE
how to save the detect.py output into txt file

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/yolov5#9870]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hello, how can I save the python detect.py output into txt file rather than send to stdout.

I try     python detect.py  --weight weight.pt  --source mydate > output.txt  but it does not work.  output.txt is empty.

I also try   python detect.py  --weight weight.pt  --source   --save-txt  output.txt, the command does not run either.

**Comment by glenn-jocher** [comment]
@frabob2017 hi there! To save the output of detect.py to a txt file, use the `--save-txt` flag along with the `--source` and `--weights` flags. Here's the correct syntax:

```bash
python detect.py --source mydata --weights weights.pt --save-txt
```

This will save the output in a 'runs/detect' directory by default. You can find more details about this in the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). Let me know if you need further assistance!

**Comment by furiouskhan007** [comment]
How to save the time, Let suppose I am using custom model for one class(Ball) detection. if my model detect the ball, how to save the exact time when its detect ? for live and for video based as well?

**Comment by glenn-jocher** [comment]
@furiouskhan007 to save the exact time when a 'Ball' is detected, you can modify the `detect.py` script to record the timestamp whenever a detection is made. Here's a general approach you can take:

1. Import the necessary Python modules for date and time at the beginning of the script:
   ```python
   from datetime import datetime
   ```

2. In the part of the script where detections are processed (usually after the model inference step), check if the class 'Ball' is detected.

3. When a 'Ball' is detected, get the current time using `datetime.now()` and save it to a file.

For live detection, you would record the timestamp in real-time as frames are processed. For video, you would record the timestamp along with the frame timestamp or number.

Here's a pseudo-code snippet to illustrate the concept:

```python
# After detection and before results are printed or saved
if 'Ball' in detected_classes:
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open('detection_times.txt', 'a') as file:
        file.write(f"Ball detected at: {current_time}\n")
```

Make sure to open the file in append mode (`'a'`) so that each new detection is added to the file rather than overwriting it.

Remember to handle the file path and name appropriately, and ensure that the script has the necessary permissions to write to the file.

For more detailed instructions and to understand the exact points where you should insert this code, please refer to the [Ultralytics Docs](https://docs.ultralytics.com/yolov5/). If you need further assistance, feel free to ask!

**Comment by furiouskhan007** [comment]
I need assistance with this code. How can the timestamp be saved? How can I save the log in a text file whenever it detects objects? Example 
0, 1:43, 2/10/2024
3, 1:45, 2/10/2025

from ultralytics import YOLO
model = YOLO('yolov8n.pt')

source = 'path/to/video.mp4'

# Run inference on the source
results = model(source, stream=True, classes=[0,2,3] )  # generator of Results objects

**Comment by glenn-jocher** [comment]
@furiouskhan007 to save a timestamp and log whenever an object is detected using the provided code snippet, you'll need to iterate through the results and write the detection information to a file. Here's how you can do it:

1. Open a file in append mode before starting the inference loop.
2. Iterate through the results, which is a generator of `Results` objects.
3. For each frame with detections, write the class ID, frame timestamp, and current date to the file.

Here's an example of how you might modify your code:

```python
from ultralytics import YOLO
from datetime import datetime

model = YOLO('yolov8n.pt')
source = 'path/to/video.mp4'

# Open a file to log detections
with open('detections_log.txt', 'a') as log_file:
    # Run inference on the source
    for results in model(source, stream=True, classes=[0, 2, 3]):  # generator of Results objects
        # Get current time
        current_time = datetime.now().strftime("%H:%M, %d/%m/%Y")
        # Check if there are any detections
        if len(results.xyxy[0]) > 0:  # We have detections for this frame
            for *xyxy, conf, cls in results.xyxy[0]:  # Iterate through detections
                # Write class ID and timestamp to the log file
                log_file.write(f"{int(cls)}, {current_time}\n")
```

This code will append a line to `detections_log.txt` for each detected object with the class ID and the current timestamp. The `results.xyxy[0]` contains the detections in the format `[x1, y1, x2, y2, confidence, class]`. The `int(cls)` converts the class tensor to a Python integer.

Please note that the `stream=True` parameter is used to process video streams frame by frame. If you want to log the frame number or video timestamp instead of the current system time, you'll need to modify the code accordingly to extract that information from the video or the `Results` object.

Keep in mind that this is a general example, and you may need to adjust the code to fit your specific requirements and the exact structure of the `Results` object provided by the version of the Ultralytics YOLO you are using.
