### ISSUE TITLE
ModuleNotFoundError: No module named 'models.common'

### ISSUE THREAD

**Issue by oms12** [ultralytics/yolov5#9873]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

PyTorch Hub

### Bug

I encounter this error while loading the model with torch hub

Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /home/user/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "src/train.py", line 163, in <module>
    main(args)
  File "src/train.py", line 114, in main
    train(train_dl, netG, netD, netC, text_encoder, optimizerG, optimizerD, args)
  File "/home/user/Desktop/DF-GAN/code/lib/modules.py", line 76, in train
    real_multiL = getClassLabels(imgs)
  File "/home/user/Desktop/DF-GAN/code/lib/modules.py", line 35, in getClassLabels
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
  File "/home/user/Desktop/test/v2/v2/lib/python3.8/site-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/user/Desktop/test/v2/v2/lib/python3.8/site-packages/torch/hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 93, in yolov5s
    return _create('yolov5s', pretrained, channels, classes, autoshape, _verbose, device)
  File "/home/user/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
ModuleNotFoundError: No module named 'models.common'

### Environment

- YOLO v5
- Python 3.8
- Ubuntu 20.0

### Minimal Reproducible Example

model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@oms12 your command works correctly in my test. I'm unable to reproduce any issues here:

<img width="740" alt="Screenshot 2022-10-20 at 20 28 44" src="https://user-images.githubusercontent.com/26833433/197029080-436ea641-cf41-45c8-80aa-f95ca5d6f815.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Jboulery** [comment]
Had the same issue.
Be careful if one of your local python packages is named `models`. After renaming the folder it worked for me.

**Comment by m1rakram** [comment]
To my opinion, this is a bug. The main reason is that error message does not specify why the module is not found. In my project the reason was that i had the folder with the same name "models" and that was confusing the module loader. It would be nice to use more informative error message. btw thank you for open source model!

**Comment by glenn-jocher** [comment]
@m1rakram thanks for the feedback. We've built-in much improved error reporting in YOLOv8 for this failure mode:
https://github.com/ultralytics/ultralytics/blob/30fc4b537ff1d9b115bc1558884f6bc2696a282c/ultralytics/nn/tasks.py#L327-L359
