### ISSUE TITLE
--device parameter ignored

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/yolov5#9884]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

Hi!

my pc has 2 gpus. one for the monitor and one for the training. I want to run the code on gpu 0, ignoring the second gpu.
so I run this command:

`!python yolov5/train.py --device 0 --epochs 200 --batch-size 80 --cfg 'yolov5/models/yolov5s.yaml' --data 'datasets/CrateVision/Crate_Generic/data.yaml' --cache`

but it trains on both gpus anyway and gives this warning and then crashes due to memory missing in the second gpu:

```
WARNING ⚠️ DP not recommended, use torch.distributed.run for best DDP Multi-GPU results.
See Multi-GPU Tutorial at https://github.com/ultralytics/yolov5/issues/475 to get started.
/home/cnnserver/anaconda3/envs/YoloV5/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py:30: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable. 
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tanzerlana 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm training 8 single-GPU models currently in our Docker image and have no problems:

<img width="592" alt="Screenshot 2022-10-21 at 21 54 12" src="https://user-images.githubusercontent.com/26833433/197278395-62e99493-af7f-4644-a0b6-19de159ce2b4.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by tanzerlana** [comment]
Hello! thanks for the answer!

I am on Ubuntu, have 2 GPUS (Quadro RTX5000 and Quadro M2000). 
I do have the latest yolo version, unchanged, and all requirements installed with the requirements file in a dedicated conda environment. Nothing additional installed. 

simply calling this command, causes the training to start on all GPUs despite the "--device 0" flag.

!python yolov5/train.py --device 0 --epochs 200 --batch-size 80 --cfg 'yolov5/models/yolov5s.yaml' --data 'datasets/CrateVision/Crate_Generic/data.yaml' --cache

It starts with checking the images, then creates the cache successfully, starts the training, and then crashes due to missing memory in the GPU. If i remove the GPU, it works well and does run without problems. as soon as I add the GPU, it ignores the device 0 tag and runs on both gpus.

Thank you 

best regards

Igor

**Comment by tanzerlana** [comment]
Running it like this fixed the problem, but according to the documentation it should not be required...

!python -m torch.distributed.run --nproc_per_node 1 yolov5/train.py --device 0 --epochs 200 --batch-size 80 --cfg 'yolov5/models/yolov5s.yaml' --data 'datasets/CrateVision/Crate_Generic/data.yaml' --cache

**Comment by glenn-jocher** [comment]
@tanzerlana yes that's correct. DDP training should not be required for single-GPU training to work correctly. I'm not sure exactly what the issue is, but if you can produce a reproducible example in a common environment like our Docker image I can start debugging this. 

Currently I'm not able to produce any issues in a multi-GPU environment. We use an 8x GPU server running our Docker image that we are currently training 8 individual models on in single-GPU format and have no experienced any issues.
