### ISSUE TITLE
I want to pass the image read by opencv to the model I/F

### ISSUE THREAD

**Issue by Heartful-echo** [ultralytics/yolov5#9913]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi

I want to pass the image read by opencv to the model I/F.
I wrote a simple code.

`cap = cv2.VideoCapture (0)`
`_, img= cap.read()`
`results = model(img)`

Even if there is a person in front of the camera, it will not be detected.
Is this code written correctly?

**Comment by glenn-jocher** [comment]
@kazuya-uchida this is incorrect usage since cv2 loads in BGR and all YOLO models expect RGB. See PyTorch Hub tutorial for correct usage examples.

## Tutorials

- [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)  🚀 RECOMMENDED
- [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/)  ☘️ RECOMMENDED
- [Multi-GPU Training](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training)
- [PyTorch Hub](https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading) 🌟 NEW
- [TFLite, ONNX, CoreML, TensorRT Export](https://docs.ultralytics.com/yolov5/tutorials/model_export) 🚀
- [Test-Time Augmentation (TTA)](https://docs.ultralytics.com/yolov5/tutorials/test_time_augmentation)
- [Model Ensembling](https://docs.ultralytics.com/yolov5/tutorials/model_ensembling)
- [Model Pruning/Sparsity](https://docs.ultralytics.com/yolov5/tutorials/model_pruning_and_sparsity)
- [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution)
- [Transfer Learning with Frozen Layers](https://docs.ultralytics.com/yolov5/tutorials/transfer_learning_with_frozen_layers)
- [Architecture Summary](https://docs.ultralytics.com/yolov5/tutorials/architecture_description) 🌟 NEW
- [Weights & Biases Logging](https://github.com/ultralytics/yolov5/issues/1289)
- [Roboflow for Datasets, Labeling, and Active Learning](https://docs.ultralytics.com/yolov5/tutorials/roboflow_datasets_integration)  🌟 NEW
- [ClearML Logging](https://docs.ultralytics.com/yolov5/tutorials/clearml_logging_integration) 🌟 NEW
- [Deci Platform](https://github.com/ultralytics/yolov5/wiki/Deci-Platform) 🌟 NEW
- [Comet Logging](https://docs.ultralytics.com/yolov5/tutorials/comet_logging_integration) 🌟 NEW

Good luck 🍀 and let us know if you have any other questions!

**Comment by kazuya-uchida** [comment]
@glenn-jocher 

Thank you for your advice.

**Comment by glenn-jocher** [comment]
@Heartful-echo you're welcome! If you have any more questions or need further assistance, feel free to ask. We're here to help!
