### ISSUE TITLE
Multiple training with --cache does not release ram memory

### ISSUE THREAD

**Issue by llerbourg** [ultralytics/yolov5#9942]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

# Context
I train yolov5 on BDD100K dataset with command : 
`python train.py --img 640 --batch 128 --epochs 1 --data bdd100k.yaml --weights yolov5s.pt --cache --evolve`

# Problem
- 👍 During first evolve step, the `--cache` option stores 50GB of images in VRAM, **this is expected**
- 👎 During second evolve step, `htop` confirm that the first 50GB are NOT released, and 50GB more are allocated in VRAM. this is **NOT expected**

# Question
Does it look like a problem on my side ? How to release that cache memory ? Destroying the Dataset object ?

Thanks !

### Environment

- YOLOv5 🚀 4be26c4 Python-3.7.13 torch-1.12.1+cu116 CUDA:0 (NVIDIA A100-SXM4-40GB, 40354MiB)
- Python 3.7.13
- Ubuntu20

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@llerbourg cached images should be released from memory once the dataloader is deleted on training function exit.

Is the bug you are seeing reproducible on a common dataset? i.e. do you see it with VOC.yaml for example?
```
python train.py --img 640 --batch 64 --epochs 1 --data VOC.yaml --weights yolov5n.pt --cache --evolve
```

**Comment by glenn-jocher** [comment]
@llerbourg 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. I'm not able to reproduce any RAM issues when evolving with --cache. I evolved multiple generations of VOC with 13.7GB training set cached in RAM and so no increase over generations.

```
python train.py --img 640 --batch 64 --epochs 1 --data VOC.yaml --weights yolov5n.pt --cache --evolve
```

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
