### ISSUE TITLE
GPU not utilizing 100% memory 

### ISSUE THREAD

**Issue by KxFxN** [ultralytics/yolov5#9949]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

GPU not utilizing 100% memory !!

I tried Train multiple GPUs but Ram not use 100% memory 

**device for me.**
GTX 1080 Ti 11GB
GTX 1070 8GB

python 3.9.13
torch  1.12.1+cu113
torchaudio  0.12.1+cu113
torchvision  0.13.1+cu113

python train.py  --img 480 --batch 2 --epochs 100 --data ./data/coco_CBZ.yaml --weights ./models/yolov5s.pt --device 0,1 --name CBZ

What is the problem? Help me

```ruby
utoAnchor: 6.40 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Plotting labels to runs\train\CBZ4\labels.jpg... 
Image sizes 480 train, 480 val
Using 2 dataloader workers
Logging results to runs\train\CBZ4
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0%|          | 0/239 [00:00<?, ?it/s]                                                                                                                                              C:\Users\kuy50\AppData\Roaming\Python\Python39\site-packages\torch\cuda\nccl.py:15: UserWarning: PyTorch is not compiled with NCCL support
  warnings.warn('PyTorch is not compiled with NCCL support')
       0/99     0.312G     0.1153    0.09853    0.06285         14        480: 100%|██████████| 239/239 [01:54<00:00,  2.09it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 120/120 [00:29<00:00,  4.02it/s]
                   all        478       4773     0.0232      0.115     0.0149    0.00374

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       1/99     0.776G    0.09581    0.09177    0.05947         31        480: 100%|██████████| 239/239 [01:41<00:00,  2.36it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 120/120 [00:21<00:00,  5.48it/s]
                   all        478       4773     0.0467      0.209     0.0442     0.0132

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       2/99     0.776G    0.08696    0.08272    0.05724         32        480: 100%|██████████| 239/239 [01:40<00:00,  2.38it/s]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 120/120 [00:17<00:00,  6.92it/s]
                   all        478       4773     0.0387      0.153     0.0539      0.024

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
       3/99     0.776G    0.09386    0.06784    0.05689         23        480:   4%|▍         | 9/239 [00:04<01:50,  2.08it/s]
```

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by ghost** [comment]
@glenn-jocher Hello and firstly thanks for this awesome piece of work :) My question is i am getting cuda out of memory error even with autobatch --batch-size -1
Autobatch calculates 16 for my batch size which is %80 of my VRAM (GTX 1070 - 8GB) but training stops with error before it fills my GPU memory (like at %20)

Windows 10
yolov5m.pt 
Image size = 640

**Comment by glenn-jocher** [comment]
@k00r hello there! Thank you for your kind words about YOLOv5 🚀! 

Regarding your question, even though AutoBatch calculates a 90% CUDA memory utilisation batch size, there are many variables that may contribute to CUDA out of memory errors, such as the size of your model, image size, data augmentation, number of classes, and number of GPUs. 

You may want to try some of the following methods to reduce your memory usage:

- Reduce `--batch-size` even further
- Reduce `--img-size`
- Reduce the number of classes or use smaller anchor sizes 
- Train with fewer augmentations
- Train on a smaller sub-set of data

It is also important to check the error message you received as it may include helpful information about the cause of your CUDA out of memory error. You could provide more information about the error message or consult the documentation to debug the issue further.

I hope this helps, and good luck with your training!

**Comment by ghost** [comment]
@glenn-jocher It was image size for me :) the error disappeared when i reduced the size of my images in my dataset

**Comment by glenn-jocher** [comment]
@k00r great to hear that you have resolved your issue! Yes, the image size plays a significant role in the memory usage of YOLOv5 while training your custom data. By reducing the image size, you reduce the numbers of pixels that your GPU needs to process, which, in turn, reduces the memory requirements during training. 

If you have any other questions or issues, please don't hesitate to ask! We are always here to help.
