### ISSUE TITLE
Question about the feature maps 23rd layer Yolov5m?

### ISSUE THREAD

**Issue by snowbrood** [ultralytics/yolov5#9959]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am trying to train yolov5 from extracted features 

My extracted features are from the 23rd layer (which is input to the detect layer)

My question is why are the extracted features (for the input image size 640) of the shape 

(768x20x20) what does each number represent? Is 768  channel count and 20 x20 grid size . 
768 is a bit confusing to understand how that number came upon.

can It be broken into say N x 3 * (80+5) where 5 represents bounding box coords + obj and 80 represent class confidences and 3 because there are 3 channels in RGB, 

what does N represent?

**Comment by UNeedCryDear** [comment]
3 is number of anchors，N is batch-size,your batch-size is 3?
But 768 mod 85 !=0. Are you sure your number is 768, not 765?

**Comment by glenn-jocher** [comment]
@UNeedCryDear the feature map dimensions (768x20x20) at the 23rd layer represent 768 channels with a grid size of 20x20. Each grid cell contains predictions for the defined number of anchors (N). The 768 channels arise from the anchor boxes and predicted classes/confidences, not directly related to RGB. The discrepancy you observed may be due to additional auxiliary layers in YOLOv5. Feel free to consult the YOLOv5 documentation for comprehensive details on feature maps and anchoring.
