### ISSUE TITLE
training fail

### ISSUE THREAD

**Issue by alicera** [ultralytics/yolov5#9973]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

image https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html?from=groupmessage

I train my model with ngc docker.
Sometime I train the network , it will let linux disconect and reboot .
How can I debug it to find root cause ?

**Comment by alicera** [comment]
because it reboot and disconnect 
So I cant see any log on terminal

**Comment by glenn-jocher** [comment]
@alicera hi there! It seems like you're encountering an issue with your training and experiencing system disconnection and reboots. This appears to be a hardware or system stability issue rather than a specific YOLOv5 problem. To address this, I recommend checking your hardware components, including power supply, thermal management, and memory. Monitoring system logs and temperature readings during training might provide insights as well. Good luck, and let us know if you need further assistance!
