### ISSUE TITLE
Quantized model INT8 is not able to do inference or convert to any other type of model structure

### ISSUE THREAD

**Issue by Sanath1998** [ultralytics/yolov5#9979]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

Hi @glenn-jocher 

As  I have quantized FLOAT32 model to INT8 model, I'am not able to convert the model to any other formats nor able to inference using detect.py and val.py

Error msg:
1. While doing inference
---------------------------
ckpt = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model
AttributeError: 'collections.OrderedDict' object has no attribute 'to'
---------------------------

2. While converting to any other model type using export.py
---------------------------
[TRT] [E] ModelImporter.cpp:779: ERROR: images:232 In function importInput:
[8] Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype) && "Failed to convert ONNX date type to TensorRT data type."
---------------------------

@glenn-jocher Can you plz look onto this? Looking forward for your reply

**Comment by Sanath1998** [comment]
@glenn-jocher , my intent was to take a call on know-hows of converting model to quantized INT8 precison and doing inference on the INT8 precision mode?
Could you please explain me on this point

**Comment by glenn-jocher** [comment]
@Sanath1998 depends on the export format. Some are already doing this, i.e. `python export.py --tflite --int8`

**Comment by Sanath1998** [comment]
@glenn-jocher 
Can't we do quantization for other models which is exported into onnx, tensorrt etc?

**Comment by glenn-jocher** [comment]
Many formats support FP16 with the --half flag

**Comment by Sanath1998** [comment]
> Many formats support FP16 with the --half flag

@glenn-jocher actually the models before using --half flag and after using --half flag, the size of the model is same for both.
Actually once we reduce to fp16, the model size should decrease ryt?
Can u plz explain me the context on this

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. 

Not all formats support --half and --int8. See export.py code for details.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
